### ISSUE TITLE
enhancement request: Add VirtualBox support for EC2 Instance Backend

### ISSUE THREAD

**Issue by Conzar** [localstack/localstack#10048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Localstack Pro's [AWS EC2 Instance backend implementation](https://docs.localstack.cloud/user-guide/aws/elastic-compute-cloud) uses Docker.  This request is to implement an AWS EC2 Instance backend that uses a Virtual Machine. 

### 🧑‍💻 Implementation

I suggest making the EC2 Instance backend as a configuration parameter.  I think the configuration could be the following:

```yaml
ec2_backend: 
  type: container|vm
  container_service: docker|singularity|kubernetes
  vm_hypervisor: virtualbox|kvm|hyper-v
```
Noting that the initial implementation could focus on virtualbox only. 

### Anything else?

The primary reason for creating a Virtual Machine Backend is to provide the best compatibility with production systems.  Containers provide limited functionality especially for testing boot based systems.  An example is testing cloud init which requires a Virtual Machine.   

Cloud_init could be a dependency to testing other components like a Terraform Provisioner that requires a service to be running which could be setup via cloud_init.
