### ISSUE TITLE
bug: localstack ignores docker volume mount in docker-compose file when running in Github actions

### ISSUE THREAD

**Issue by santoshpavan** [localstack/localstack#10146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to run integration tests using docker-compose file as part of the Github Actions pipeline. I am already mounting the docker.sock file to the container but looks like it's being ignored as I am seeing the following statement - 

> Failed to create the runtime executor for the function named_lambda. Please ensure that Docker is available in the LocalStack container by adding the volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. Check out https://docs.localstack.cloud/user-guide/aws/lambda/#docker-not-available

It works fine locally and as part of the Jenkins pipeline. I am facing this issue only within Github Actions.

### Expected Behavior

Localstack should be able to detect the mounted docker.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

1. `docker compose up` using the docker-compose file. The file looks like below - 
This is the docker-compose file - 
```yaml
version: "3"
services:
  localstack:
    privileged: true
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack_main}"
    image: localstack/localstack:3.1.0
    ports:
      - "4566-4599:4566-4599"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock # this is default. Maybe can be removed
      - DATA_DIR=${DATA_DIR- }
      - LOCALSTACK_HOST=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=120
      - DOCKER_SDK_DEFAULT_RETRIES=5
      - LAMBDA_RUNTIME_IMAGE_MAPPING=PRIVATE_HUB/lambda/python:3.7
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
2. This is being run within Github Actions which looks like this - 
```yaml
name: Pull Requests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Getting OS info
        run: |
          cat /etc/os-release

      - name: Checking for docker
        run: |
          docker info
          ls -l /var/run/docker.sock

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          cache: 'pip' # caching pip dependencies

      - name: Docker compose
        run: |
         docker  --debug compose up --build -d

      - name: Run tests
        run: |
          mkdir ~/.aws
          if [ ! -f ~/.aws/config ]; then
            echo "[default]\nregion=us-east-1" >> ~/.aws/config
          else
            echo "File already exists"
          fi
          pytest

      - name: Docker compose down
        run: |
          docker compose down

```

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS (the GHA runner OS)
- LocalStack: 3.1.0
```

### Anything else?

In the GHA pipeline, I included a couple of logs for docker, as sanity check  and here are the outputs -

`docker info` gave

> Client: Docker Engine - Community
>  Version:    24.0.7
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   buildx: Docker Buildx (Docker Inc.)
>     Version:  v0.[11](https://github.expedia.biz/eg-virtualtour/vtetl-core-tf/actions/runs/20676779/jobs/29264714#step:4:12).2
>     Path:     /usr/libexec/docker/cli-plugins/docker-buildx
>   compose: Docker Compose (Docker Inc.)
>     Version:  v2.21.0
>     Path:     /usr/libexec/docker/cli-plugins/docker-compose

and `ls -l /var/run/docker.sock` gave `srw-rw---- 1 root docker 0 Jan 30 21:37 /var/run/docker.sock`

I presume that this means that the runner has the expected docker resources required.

Apart from the above log, I ran the tests as docker-compose to be able to see the localstack logs, and this is what I see - 

>  WARNING: Docker not available in the LocalStack container but required to run Lambda functions. Please add the Docker volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. https://docs.localstack.cloud/user-guide/aws/lambda/#docker-not-available

then during lambda invocation it pops up as an error log - 

> localstack_main   | 2024-01-30T21:52:59.479 ERROR --- [   asgi_gw_1] l.services.lambda_.hints   : Failed to create the runtime executor for the function named_lambda. Please ensure that Docker is available in the LocalStack container by adding the volume mount "/var/run/docker.sock:/var/run/docker.sock" to your LocalStack startup. Check out https://docs.localstack.cloud/user-guide/aws/lambda/#docker-not-available

And a bunch of more logs that looked relevant but not sure if it is - 

> localstack_main   | 2024-01-30T21:51:27.453 DEBUG --- [-functhread2] l.u.c.docker_sdk_client    : Creating Docker SDK client failed: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
