### ISSUE TITLE
[SQS] create default queue from docker-compose configuration

### ISSUE THREAD

**Issue by gopinath-langote** [localstack/localstack#1014]
Many times we use localstack for Integration testing. And you need to create a queue in test most of the time in order to test the behaviour. 

This features enables developers to create default queue on sqs from docker-compose file itself.

Does this make sense? Any opinion?

Ex:

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=${SERVICES- }
      - SQS-DEFAULT_QUEUES: test-queue1,test-queue2
```  
Regards,
@gopinath-langote
