### ISSUE TITLE
AWS::RDS::DBCluster deploying via CloudFormation fails with 'Parameter validation failed: Invalid type for parameter...' when specific fields are used from parameters

### ISSUE THREAD

**Issue by Relenna** [localstack/localstack#10197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, 
I'm not sure that this is a bug, but I haven't found a solution, so any help would be appreciated :) 

I need to deploy DBCluster via CloudFormation stack and part of its configuration should be passed through parameters. Those parameters have type number. But when I'm trying to pass them, stack creation fails with validation error: 

`Parameter validation failed: Invalid type for parameter ServerlessV2ScalingConfiguration.MaxCapacity, value: 16, type: <class 'str'>, valid types: <class 'float'>, <class 'decimal.Decimal'>, <class 'int'> `

For now I've found that affected fields are: 

- `ServerlessV2ScalingConfiguration.MaxCapacity`
- `ServerlessV2ScalingConfiguration.MinCapacity`
- `Port`

I've tried to use `deploy-stack` command with ` --parameter-overrides` and `create-stack` with` --parameters`, both lead to the same error. If this parameter has default value and I don't override it, stack deploys correctly

Example of cloud formation template that reproduces error: 
```
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Example of DBCluster with number parameter

Parameters:
  MaxCapacity:
    Type: Number
    Default: 16
 
Resources:
  TestDbCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Sub ${AWS::StackName}
      MasterUsername: dummyuser
      MasterUserPassword: dummypassword
      Engine: aurora-postgresql
      EngineMode: serverless
      ServerlessV2ScalingConfiguration:
        MaxCapacity: !Ref MaxCapacity
        MinCapacity: 0.5
```

### Expected Behavior

I expect that stack are created successfully. Or that I passed this parameters incorrectly and there are some correct way to do it. I didn't find information about it. Also, I didn't try to deploy it in AWS, so I'm not sure if it can be deployed with this configuration. For now the only thing I know, that using required value in 'default' field of parameters helps.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cloudformation deploy --stack-name testdb --template-file dbcluster_minimal_example.yaml --parameter-overrides MaxCapacity=16

OR

    awslocal cloudformation create-stack --stack-name testdb2 --template-body file://dbcluster_minimal_example.yaml --parameters '{"ParameterKey":"MaxCapacity", "ParameterValue":"16"}'

### Environment

```markdown
- OS: Ubuntu 20.04.6 LTS
- LocalStack (Pro): 3.1.1.dev20240205090040
```

**Comment by pinzon** [comment]
The solution for this issue has been merged. please make sure to pull the latest image.

**Comment by Relenna** [comment]
Hi, 
Thanks for fixing the issue. 
However, I found that it works for integer fields, but not for float ones. 

```
localstack-main  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack-main  | Invalid type for parameter ServerlessV2ScalingConfiguration.MinCapacity, value: 0.5, type: <class 'str'>, valid types: <class 'float'>, <class 'decimal.Decimal'>, <class 'int'>
```

The example more or less the same, but instead of changing MaxCapacity I tried to change MinCapacity

```
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Example of DBCluster with number parameter

Parameters:
  MinCapacity:
    Type: Number
    Default: 0.5
 
Resources:
  TestDbCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Sub ${AWS::StackName}
      MasterUsername: dummyuser
      MasterUserPassword: dummypassword
      Engine: aurora-postgresql
      EngineMode: serverless
      ServerlessV2ScalingConfiguration:
        MaxCapacity: 16
        MinCapacity: !Ref MinCapacity
```
With command line: 

`awslocal cloudformation deploy --stack-name testdb --template-file dbcluster_minimal_example.yaml --parameter-overrides MinCapacity=0.5`
