### ISSUE TITLE
Can't connect to Secrets Manager

### ISSUE THREAD

**Issue by emmkong** [localstack/localstack#1022]
I try to run localstak at local via docer compose

```
 localstack:
    image: localstack/localstack
    ports:
      - "8080:8080"
      - "4567-4584:4567-4584"
    environment:
      - DEFAULT_REGION=ap-southeast-2
      - DATA_DIR=/tmp/localstack/data
```

and try to connect secret manager via AWS cli after docker conatiner fully started

`aws --endpoint-url=http://localhost:4584 secretsmanager list-secrets`

and I got error `Connection was closed before we received a valid response from endpoint URL: "http://localhost:4584/".`

I also tried other services and they are all working as expected except secrets manager

Please help. Thanks
