### ISSUE TITLE
bug: Attempting to deploy a Cloudfront Distribution CDK Construct with an Origin containing CustomHeaders throws an error

### ISSUE THREAD

**Issue by SleepingTalent** [localstack/localstack#10236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to deploy a Cloudfront Distribution that contains an Origin with a customer header:
```
const lambda = new Function(this, "internal-message-handler", {
            runtime: Runtime.NODEJS_18_X,
            handler: "index.handler",
            code: Code.fromInline(`
                exports.handler = async (event) => {
                    console.log('event: ', event)
                    return { statusCode: 200, body: 'Message from internal message lambda'};
                };
               `),
        });
        const getMessageIntegration = new LambdaIntegration(lambda);

        const internalApi = new RestApi(this, 'message-api', {
            defaultCorsPreflightOptions: {
                allowOrigins: Cors.ALL_ORIGINS
            }});
        internalApi.root.addMethod('ANY');

 const internalMessageRoot = internalApi.root.addResource('internal-message');
 internalMessageRoot.addMethod('GET', getMessageIntegration);

 const internalRestApiOrigin = new RestApiOrigin(internalApi, {
        customHeaders: {
            ["My-Custom-header"]: "xxxxxxxxxxxx",
        }
});

new Distribution(this, "RestOriginDistributionTest", {
        comment: "RestOriginDistributionTest",
        defaultBehavior: {
            origin: internalRestApiOrigin,
            cachePolicy: CachePolicy.CACHING_DISABLED,
            viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            allowedMethods: AllowedMethods.ALLOW_ALL,
        },
        enableLogging: true,
        domainNames: ["test.com"],
        certificate: new Certificate(this, "Cert", {
                domainName: "test.com",
            }),
});
```
I receive the following error from localstack when deploying, the same stack deploys to AWS without issue:

`Unknown parameter in DistributionConfigWithTags.DistributionConfig.Origins.Items[0]: "OriginCustomHeaders", must be one of: Id, DomainName, OriginPath, CustomHeaders, S3OriginConfig, CustomOriginConfig, ConnectionAttempts, ConnectionTimeout, OriginShield, OriginAccessControlId)`

This error also occurs when you use an S3Origin construct
```
const webAppBucket = new BaseStaticWebsiteBucket(this, "S3OriginCloudfrontBucket", {
        bucketName: `s3-origin-cloudfront-test-webapp`,
});

const s3Origin = new S3Origin(webAppBucket, {
         customHeaders: {
             ["My-custom-header"]: "xxxxxxxxxxxx",
         }
});

new Distribution(this, "S3OriginDistributionTest", {
        comment: "S3OriginDistributionTest",
        defaultBehavior: {
            origin: s3Origin,
            cachePolicy: CachePolicy.CACHING_DISABLED,
            viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
            allowedMethods: AllowedMethods.ALLOW_ALL,
        },
        enableLogging: true,
});
```

However if I comment out the customHeaders property the Cloudfront Distribution deploys successfully to localstack*

```
        const s3Origin = new S3Origin(webAppBucket, {
             // customHeaders: {
             //     ["my-customer-header"]: "xxxxxxxxxxxx",
             // }
        });
```

### Expected Behavior

I expect the Cloudfront Distribution containing an Origin with a customHeader to be deployed without error.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I have the following docker-compose.yml

```
version: "3.7"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-pro:3.1.0
    network_mode: bridge
    ports:
    - "4566:4566"
    - "4510-4559:4510-4559"
    environment:
    - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- }
    - SKIP_SSL_CERT_DOWNLOAD=1
    - CLOUDFRONT_STATIC_PORTS=1
    - DOCKER_HOST=unix:///var/run/docker.sock
    - EXTRA_CORS_ALLOWED_ORIGINS=*
    - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
    - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
    - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
    - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
```
Deploying the following stack produces the error:

```
import {Stack, StackProps} from "aws-cdk-lib";
import {Construct} from "constructs";
import {
    AllowedMethods,
    CachePolicy, Distribution,
    ViewerProtocolPolicy
} from "aws-cdk-lib/aws-cloudfront";
import {RestApiOrigin} from "aws-cdk-lib/aws-cloudfront-origins";
import {RestApi} from "aws-cdk-lib/aws-apigateway";
import {Certificate} from "aws-cdk-lib/aws-certificatemanager";

export class FailingRestOriginStack extends Stack {
    constructor(scope: Construct, id: string, props?: StackProps) {
        super(scope, id, props);

         const lambda = new Function(this, "internal-message-handler", {
            runtime: Runtime.NODEJS_18_X,
            handler: "index.handler",
            code: Code.fromInline(`
                exports.handler = async (event) => {
                    console.log('event: ', event)
                    return { statusCode: 200, body: 'Message from internal message lambda'};
                };
               `),
        });
        const getMessageIntegration = new LambdaIntegration(lambda);

        const internalApi = new RestApi(this, 'message-api', {
            defaultCorsPreflightOptions: {
                allowOrigins: Cors.ALL_ORIGINS
            }});
        internalApi.root.addMethod('ANY');

        const internalMessageRoot = internalApi.root.addResource('internal-message');
        internalMessageRoot.addMethod('GET', getMessageIntegration);

        const internalRestApiOrigin = new RestApiOrigin(internalApi, {
            customHeaders: {
                ["My-Custom-header"]: "xxxxxxxxxxxx",
            }
        });

        new Distribution(this, "RestOriginDistributionTest", {
            comment: "RestOriginDistributionTest",
            defaultBehavior: {
                origin: internalRestApiOrigin,
                cachePolicy: CachePolicy.CACHING_DISABLED,
                viewerProtocolPolicy: ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
                allowedMethods: AllowedMethods.ALLOW_ALL,
            },
            enableLogging: true,
            domainNames: ["test.com"],
            certificate: new Certificate(this, "Cert", {
                domainName: "test.com",
            }),
        });
    }
}
```
**Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)**
`cdklocal bootstrap && cdklocal deploy --require-approval never`

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack: localstack-pro:3.1.0
```
