### ISSUE TITLE
bug: Incorrect 'Invalid parameter: TopicArn' error thrown when attempting to publish message to SNS Topic via AWS JS SDK v3

### ISSUE THREAD

**Issue by acarlson0000** [localstack/localstack#10262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Created SNS Topic via JS SDK v3
- Created SQS Queue via JS SDK v3
- Created Subscription via JS SDK v3
- Attempt to publish message via JS SDK v3 - receive 'Invalid parameter: TopicArn'
- Expected input format (see code below) - https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sns/command/PublishCommand/

```
node-1  |   '$metadata': {
node-1  |     httpStatusCode: 400,
node-1  |     requestId: undefined,
node-1  |     extendedRequestId: undefined,
node-1  |     cfId: undefined,
node-1  |     attempts: 1,
node-1  |     totalRetryDelay: 0
node-1  |   },
node-1  |   Error: {
node-1  |     Code: 'InvalidParameter',
node-1  |     Message: 'Invalid parameter: TopicArn',
node-1  |     Type: 'Sender',
node-1  |     message: 'Invalid parameter: TopicArn'
node-1  |   },
```

If you remove the `TopicArn` parameter, you receive:
`node-1  |     Message: "exception while calling sns.Publish: 'NoneType' object has no attribute 'split'",` - so I assume there is some issue when it makes the HTTP call and isn't being handled correctly

Have also attempted this via python / boto3 library, and receive the error. 

When using awslocal however, it works correctly:
`awslocal --endpoint http://localhost:4566 --region eu-west-1 sns publish --topic-arn arn:aws:sns:eu-west-1:000000000000:topic --message hello`

When using the same code with real AWS resources, it also works correctly.

### Expected Behavior

Should be able to publish a message to the SNS Topic when using valid parameters

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Docker Compose file:
```
version: "3"

services:
  node:
    depends_on:
      - localstack
    image: node:21
    volumes:
      - ./index.js:/index.js
      - ./node_modules:/node_modules
      - ./package.json:/package.json
    command: 'node index.js'

  localstack:
    image: localstack/localstack:3.1
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-west-1
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
```

package.json
```
{
  "devDependencies": {
    "@aws-sdk/client-sns": "^3.515.0",
    "@aws-sdk/client-sqs": "^3.515.0"
  }
}
```

index.js
```
const sns = require('@aws-sdk/client-sns');
const sqs = require('@aws-sdk/client-sqs');

const config = {
  region: 'eu-west-1',
  endpoint: 'http://localstack:4566',
  credentials: {
    accessKeyId: '',
    secretAccessKey: ''
  }
}

const snsClient = new sns.SNSClient(config)
const sqsClient = new sqs.SQSClient(config)

const runner = async () => {
  const topic = await snsClient.send(new sns.CreateTopicCommand({
    Name: 'topic'
  }))

  const queue = await sqsClient.send(new sqs.CreateQueueCommand({
    QueueName: 'queue'
  }))

  const { TopicArn } = topic;
  const { QueueUrl } = queue;

  const QueueArn = await sqsClient.send(new sqs.GetQueueAttributesCommand({
    QueueUrl,
    AttributeNames: ['QueueArn']
  }));

  const subscription = await snsClient.send(new sns.SubscribeCommand({
    TopicArn,
    Protocol: 'sqs',
    Endpoint: QueueArn.Attributes.QueueArn
  }))

  const publish = await snsClient.send(new sns.PublishCommand({
    TopicArn,
    Message: 'hello'
  }));

  console.log(publish)
}

runner();
```

To Run:
`docker-compose up localstack -d && npm i && docker-compose up node`

```
Error:
...
node-1  |   '$metadata': {
node-1  |     httpStatusCode: 400,
node-1  |     requestId: undefined,
node-1  |     extendedRequestId: undefined,
node-1  |     cfId: undefined,
node-1  |     attempts: 1,
node-1  |     totalRetryDelay: 0
node-1  |   },
node-1  |   Error: {
node-1  |     Code: 'InvalidParameter',
node-1  |     Message: 'Invalid parameter: TopicArn',
node-1  |     Type: 'Sender',
node-1  |     message: 'Invalid parameter: TopicArn'
node-1  |   },
```

### Environment

```markdown
- OS: MacOS Sonoma 14.3.1 (23D60)
- LocalStack: Docker - localstack/localstack:3.1
```
