### ISSUE TITLE
bug: SQS FIFO not moving messages into DLQ

### ISSUE THREAD

**Issue by antoniopangallo** [localstack/localstack#10281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SQS fifo is not moving messages into its DLQ when `maxReceiveCount` is reached

### Expected Behavior

I expect that after reaching `maxReceiveCount` messages are moved into FIFO DLQ

### How are you starting LocalStack?

With a docker-compose file

### CloudFormation

```json {
  "AWSTemplateFormatVersion": "2023-02-08",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "CARD_EVENTS_SQS": {
      "Type": "AWS::SQS::Queue",
      "Properties": {
        "QueueName": "local-card-events-service-sqs.fifo",
        "MessageRetentionPeriod": 300,
        "RedrivePolicy": {
          "deadLetterTargetArn": { "Fn::GetAtt": ["CARD_EVENTS_DLQ", "Arn"] },
          "maxReceiveCount": 1
        },
        "DelaySeconds": 5,
        "VisibilityTimeout": 300,
        "FifoQueue": true,
        "ContentBasedDeduplication": true
      }
    },
    "CARD_EVENTS_DLQ": {
      "Type": "AWS::SQS::Queue",
      "Properties": {
        "QueueName": "local-card-events-service-sqs-dlq",
        "MessageRetentionPeriod": 300
      },
      "DelaySeconds": 0,
      "VisibilityTimeout": 300,
      "FifoQueue": true,
      "ContentBasedDeduplication": true
    }
  },
  "StackName": "card-events-service"
}
```

### docker-compose

```yml
version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.1.0
    container_name: localstack-scalapay-card-events-service
    ports:
      - '${LOCALSTACK_PORT}:4566'
    environment:
      - SERVICES=ssm,cloudformation,lambda,logs,iam,sqs,events,dynamodb,apigateway
      - DEBUG=0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - LAMBDA_EXECUTOR=docker-reuse
      - DYNAMODB_REMOVE_EXPIRED_ITEMS=1
      - DYNAMODB_IN_MEMORY=1
      - TZ=UTC
    volumes:
      - './.env:/.env'
      - './.aws-local:/etc/localstack/init/ready.d'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './.tmp/localstack:/var/lib/localstack'
```

### Lambda
```javascript
export const start = async (sqsEvent: SQSEvent) => {
  return {
    batchItemFailures: sqsEvent.Records.map(({ messageId }) => ({ itemIdentifier: messageId }))
  };
};
```

Messages pushed into the `local-card-events-service-sqs.fifo` queue will correctly trigger the lambda. However, if the lambda fails to process the messages returning `messageId` into `batchItemFailures` array when the `maxReceiveCount=1` is reached  messages are not moved into DLQ. 

If I use normal queue (not FIFO) messages are correctly moved into DLQ.

### Environment

```markdown
- OS: OS Ventura 13.0 (22A380)
- LocalStack: 3.0.2 - 3.1.0 - latest (CE and PRO)
```
