### ISSUE TITLE
bug: DynamoDB Streams crashing during PutRecord

### ISSUE THREAD

**Issue by sidekick-eimantas** [localstack/localstack#10362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```shell
localstack-main  | 2024-02-29T19:32:13.004  INFO --- [functhread40] localstack.utils.threads   : Thread run method <function EventForwarder.forward_to_targets.<locals>._forward at 0xffff5e2e5800>(None) failed: An error occurred (ResourceInUseException) when calling the PutRecord operation: Stream arn:aws:kinesis:us-east-1:000000000000:stream/__ddb_stream_fca2ac46-2ecd-4477-a2f3-538fa7279e05 is not currently ACTIVE or UPDATING. Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
localstack-main  |     result = self.func(self.params, **kwargs)
localstack-main  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 193, in _forward
localstack-main  |     cls.forward_to_ddb_stream(account_id, region_name, records_to_ddb)
localstack-main  |   File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 201, in forward_to_ddb_stream
localstack-main  |     dynamodbstreams_api.forward_events(account_id, region_name, records)
localstack-main  |   File "/opt/code/localstack/localstack/services/dynamodbstreams/dynamodbstreams_api.py", line 85, in forward_events
localstack-main  |     kinesis.put_record(
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
localstack-main  |     return self._make_api_call(operation_name, kwargs)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
localstack-main  |     raise error_class(parsed_response, operation_name)
localstack-main  | botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the PutRecord operation: Stream arn:aws:kinesis:us-east-1:000000000000:stream/__ddb_stream_fca2ac46-2ecd-4477-a2f3-538fa7279e05 is not currently ACTIVE or UPDATING.
localstack-main  | 
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yml
version: "3"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: localstack/localstack
    ports:
      - "0.0.0.0:4510-4559:4510-4559"  # external service port range
      - "0.0.0.0:4566:4566"            # LocalStack Edge Proxy
    environment:
      SERVICES: dynamodb
      DYNAMODB_IN_MEMORY: 1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.docker}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/_localstack/health"]
      interval: "1s"
      timeout: "5s"
      retries: 15
      start_period: "1s"

secrets:
  pip.conf:
    file: "$HOME/.config/pip/pip.conf"
```

Put this up, then try to write something to a DynamoDB table

### Environment

```markdown
- OS: MacOS 14.3.1 23D60
- LocalStack: latest
```

### Anything else?

Waiting 2s~ after creating the table before using it resolves this
