### ISSUE TITLE
Unable to run localstack on aws codebuild

### ISSUE THREAD

**Issue by fedecastelli** [localstack/localstack#1044]
I use AWS CodePipeline for the CI/CD of my project. I discovered this amazing repo, and I want to use it for my unit tests. I use a managed (by AWS) environment image Ubuntu based and Python 3.6 installed on it.
I can't start my mock server running `localstack start` because I got the error below.

`Starting local dev environment. CTRL-C to quit.
ERROR: 'cd "/codebuild/output/src575220582/src/venv/lib/python3.6/site-packages/localstack" && npm install': b'npm WARN package.json localstack@0.0.1 No repository field.\nnpm WARN package.json localstack@0.0.1 No README data\nnpm http GET https://registry.npmjs.org/leveldown/3.0.1\nnpm http GET https://registry.npmjs.org/kinesalite/1.14.0\nnpm http GET https://registry.npmjs.org/kinesalite/1.14.0\nnpm http GET https://registry.npmjs.org/leveldown/3.0.1\nnpm http GET https://registry.npmjs.org/kinesalite/1.14.0\nnpm http GET https://registry.npmjs.org/leveldown/3.0.1\nnpm ERR! Error: CERT_UNTRUSTED\nnpm ERR! at SecurePair.<anonymous> (tls.js:1370:32)\nnpm ERR! at SecurePair.EventEmitter.emit (events.js:92:17)\nnpm ERR! at SecurePair.maybeInitFinished (tls.js:982:10)\nnpm ERR! at CleartextStream.read [as _read] (tls.js:469:13)\nnpm ERR! at CleartextStream.Readable.read (_stream_readable.js:320:10)\nnpm ERR! at EncryptedStream.write [as _write] (tls.js:366:25)\nnpm ERR! at doWrite (_stream_writable.js:223:10)\nnpm ERR! at writeOrBuffer (_stream_writable.js:213:5)\nnpm ERR! at EncryptedStream.Writable.write (_stream_writable.js:180:11)\nnpm ERR! at write (_stream_readable.js:583:24)\nnpm ERR! If you need help, you may report this log at:\nnpm ERR! <http://github.com/isaacs/npm/issues>\nnpm ERR! or email it to:\nnpm ERR! <npm-@googlegroups.com>\n\nnpm ERR! System Linux 4.14.70-67.55.amzn1.x86_64\nnpm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"\nnpm ERR! cwd /codebuild/output/src575220582/src/venv/lib/python3.6/site-packages/localstack\nnpm ERR! node -v v0.10.25\nnpm ERR! npm -v 1.3.10\nnpm ERR! \nnpm ERR! Additional logging details can be found in:\nnpm ERR! /codebuild/output/src575220582/src/venv/lib/python3.6/site-packages/localstack/npm-debug.log\nnpm ERR! not ok code 0\n'`

I don't know if it's an issue of localstack or it's an issue of AWS CodeBuild. Does anyone have the same problem?

**Comment by dmnlk** [comment]
please paste your buildspec.yml or Dockerfile

**Comment by fedecastelli** [comment]
My buildspec.yml file.
```
phases:
  install:
    commands:
      - sudo apt-get update -y
      - pip install --upgrade awscli
      - /usr/local/bin/pip3 install virtualenv
      - mkdir venv
      - /usr/local/bin/virtualenv venv
      - . venv/bin/activate
      - pip3 install -r requirements.txt
      - localstack start

  pre_build:
    commands:
      - python -m unittest discover tests

  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
```
It was a problem of node. I had to create a custom Docker image and I resolved the error.
Now the error is that the AWS CodeBuild is executed as a root and localstack can't be started as root. How can I fix this problem?

**Comment by chunyenHuang** [comment]
I am using localstack with docker. I wonder if there is other clean way to make it happen.

```yaml
version: 0.2
env:
  variables:
    TEST_NETWORK: codebuild-test-network
    DDB_ENDPOINT: localstack:4569
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm run localstack || true # custom command to run localstack in docker
      - npm install
      - docker network create $TEST_NETWORK || true
      - docker network connect --alias localstack $TEST_NETWORK localstack || true
      - docker network connect $TEST_NETWORK $(cat /proc/self/cgroup | grep 'docker' | sed 's/^.*\///' | tail -n1) || true
      - docker network inspect $TEST_NETWORK
  pre_build:
    commands:
      - npm test
    finally:
      - docker stop localstack || true
      - docker rm -f localstack || true
      - docker network rm $TEST_NETWORK || true
```
