### ISSUE TITLE
bug: Aurora Global DB -- Secondary Cluster Promotion

### ISSUE THREAD

**Issue by lek7hj** [localstack/localstack#10482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a global aurora db set up with a primary cluster and a secondary cluster, running 
`awslocal rds promote-read-replica-db-cluster --db-cluster-identifier test-db-aurora-us-west-2 --debug`
results in an internal error, and fails to promote the secondary cluster. 

### Expected Behavior

The secondary cluster should be promoted to a standalone cluster. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml 
```yaml 
version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro:3.0.2
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
      - "127.0.0.1:53:53/udp"
    environment:
      - SERVICES=s3,sns,dynamodb,ecr,lambda,cloudformation,cloudwatch,sts,iam,apigateway,route53,elbv2,ecs,ec2,logs,events,apigatewayv2,application-autoscaling,cloudtrail,rds,kms
      - PERSISTENCE=0
      - PORT_WEB_UI=18080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - SKIP_SSL_CERT_DOWNLOAD=1
      - OUTBOUND_HTTP_PROXY=${HTTP_PROXY}
      - OUTBOUND_HTTPS_PROXY=${HTTP_PROXY}
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
    volumes:
      - "../../shared/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"      
      - "./init-npm.sh:/etc/localstack/init/boot.d/init-npm.sh"
    networks:
      - "local"

networks:
  local:
    driver: "bridge"
```

exec docker-compose -f ./tests/features/docker-compose.yml -p localstack up -d;

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

	awslocal cloudformation create-stack --stack-name aurora-db --template-body file://tests/features/templates/aurora/aurora-global.yml --region us-east-1

	awslocal cloudformation create-stack --stack-name aurora-west --template-body file://tests/features/templates/aurora/aurora-west.yml --region us-west-2

### Environment

```markdown
- OS: macOS Sonoma 14.4
- LocalStack: localstack/localstack-pro:3.0.2
```

**Comment by lek7hj** [comment]
aurora global yaml 
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 
  A stack to create Aurora DB global clusters.
Resources:
  GlobalCluster:
    Type: 'AWS::RDS::GlobalCluster'
    Properties:
      GlobalClusterIdentifier: test-db-aurora-global
      SourceDBClusterIdentifier: !Ref RDSCluster
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: very
      MasterUserPassword: notsecure
      DBClusterIdentifier: test-db-aurora-us-east-1
      DBClusterParameterGroupName: default.aurora-postgresql14
      Engine: aurora-postgresql
      EngineVersion: '14.8'
  RDSDBInstance1:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceIdentifier: test-db-aurora-00
      DBParameterGroupName: default.aurora-postgresql14
      PubliclyAccessible: 'true'
      DBInstanceClass: db.r3.xlarge
  RDSDBInstance2:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceIdentifier: test-db-aurora-01
      DBParameterGroupName: default.aurora-postgresql14
      PubliclyAccessible: 'true'
      DBInstanceClass: db.r3.xlarge        
     

```

**Comment by lek7hj** [comment]
aurora west.yml 
```yaml 
AWSTemplateFormatVersion: '2010-09-09'
Description: 
  A stack to add a region to the existing global cluster.
Resources:
  RDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      GlobalClusterIdentifier: test-db-aurora-global
      DBClusterIdentifier: test-db-aurora-us-west-2
      DBClusterParameterGroupName: default.aurora-postgresql14
      Engine: aurora-postgresql
      EngineVersion: '14.8'
  RDSDBInstance1:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceIdentifier: test-db-aurora-00
      DBParameterGroupName: default.aurora-postgresql14
      PubliclyAccessible: 'true'
      DBInstanceClass: db.r3.xlarge
        
     
```
