### ISSUE TITLE
bug: Cloudformation doesn't support Fn::GetAtt dot.notation

### ISSUE THREAD

**Issue by lukestoward** [localstack/localstack#10481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not sure whether this is technically valid syntax, however it is possible to use `Fn::GetAtt SQSDeadLetterQueue.Arn` in a CloudFormation template when deploying to AWS directly.

However, when using LocalStack via the latest Docker image the above function results in the following error:

```
WARN --- [functhread12] l.s.c.engine.entities      : CFn resource failed to deploy: SQSQueue (Resource 'S' not found in stack example-sqs-stack)
```

Using `Fn::GetAtt [SQSDeadLetterQueue, Arn]` and `!GetAtt SQSDeadLetterQueue.Arn` works as expected. Raising this to highlight the disparity between LocalStack and remote AWS CloudFormation behaviour.

### Expected Behavior

I would expect the following syntax `Fn::GetAtt SQSDeadLetterQueue.Arn` to work in LocalStack.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Using the following files:

`template-example.yaml`

```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  SQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Sub: example-dlq

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Sub: example-queue
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: SQSDeadLetterQueue.Arn
        maxReceiveCount: 3
```

`init-localstack.sh`
```bash
#!/bin/bash

set -e

awslocal cloudformation deploy \
    --template-file /template-example.yaml \
    --stack-name example-sqs-stack \
    --region=eu-west-1
```

`docker-compose.yml`
```yaml
version: '3.9'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: cloudformation,sqs
      LS_LOG: info
    volumes:
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "./template-example.yaml:/template-example.yaml"
```

And running `docker compose up localstack` you should see the error mentioned above.

### Environment

```markdown
- OS: macOS Ventura 13.6.4
- LocalStack: `latest` (3.2.1.dev - 0288b872a)
```
