### ISSUE TITLE
bug: Unable to Connect to Localhost port when Invoking a Lambda function at an APIGateway Endpoint

### ISSUE THREAD

**Issue by imh0wie** [localstack/localstack#10535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As I am testing my APIGateway endpoint locally, I am setting up my microservice to be run in a container by running `docker-compose up`, followed by deploying my resources including the Lambda function used by my simple GET endpoint and a DynamoDB table and creating multiple random items in the table by `aws dynamodb put-item`. While testing, I am able to get the item by `aws dynamodb get-item`. However, when I try to (1) curl from the endpoint `http://localhost:4566/restapis/random_id/local/_user_request_/getUser` or (2) invoke the function at the endpoint,
I am always unable to fetch the desired item and got the same error message `"connect ECONNREFUSED 127.0.0.1:4566"`.

```
// serverless.yml

service:myapp-users
custom:
  # FOR TESTING LOCALLY
  localstack:
    host: http://localhost
    edgePort: 4566
    stages:
      - local
    autostart: true
provider:
  name: aws
  endpointType: regional
  runtime: nodejs20.x
  region: ${opt:region, 'ap-east-1'} # Default to ap-east-1 if not specified
  stage: ${opt:stage, 'dev'} # Default to dev if not specified
  environment:
    DYNAMODB_TABLE_NAME: myapp-users-${self:provider.stage}
    DYNAMODB_ENDPOINT: http://localhost:4566
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-deployments-${self:provider.region}
  plugins:
  - serverless-localstack
functions:
  getUser:
    handler: dist/getUser.handler
    events:
      - http:
          path: user
```

```
// docker-compose.yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=cloudformation,iam,apigateway,lambda,dynamodb,logs
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

This is how I initialize my DynamoDB client at the endpoint:
```
const dynamoDb = new DynamoDBClient(process.env.DYNAMODB_TABLE_NAME === "myapp-users-local" ? {
  endpoint: process.env.DYNAMODB_ENDPOINT,
  region: "us-east-1",
  credentials: {
    accessKeyId: "test",
    secretAccessKey: "test",
  },
  tls: false,
} : {});
```

### Expected Behavior

I am expecting I can fetch the item from either `curl -X GET ...`, `aws invoke ...`, or even a simple TS script that fetches the item locally using `fetch` API.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up` or `docker-compose -d`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. Deploy resources
```
yarn build
aws --endpoint-url=http://localhost:4566 s3 mb s3://myapp-users-local-deployments-ap-east-1
serverless deploy --stage local
```
2. Create random items with necessary keys

```
for ((i = 0; i < NUMBER_OF_FAKE_ITEMS; i++)); do
  aws dynamodb put-item \
    --table-name myapp-users-local \
    --item "{                             
        \"id\": {\"S\": \"$ID\"},
       ...
    }" \
    --endpoint-url http://localhost:4566
done
```

3.  Check existence with AWS CLi
```
aws dynamodb scan --table-name myapp-users-local --endpoint http://localhost:4566
aws dynamodb get-item --table-name myapp-users-local --key '{"userId": {"S": "ID OF ANY ITEM OBSERVED FROM LAST COMMAND"}}' --endpoint-url http://localhost:4566
```

4. Invoke function at the endpoint
```
aws lambda invoke \              
    --function-name myapp-users-local-getUser \
    --payload $(echo -n '{ "queryStringParameters": { "userId": "93e7e170cdfabc8c4415582e3328c519" } }' | base64) \
    response.json \
    --endpoint-url http://localhost:4566
```

### Environment

```markdown
- OS: macOS Sonoma 14.4
- LocalStack: latest
```

### Anything else?
As I tried to follow the solution for [issue 3068](https://github.com/localstack/localstack/issues/3068), I checked the information of the running containers by `docker ps` and the output is as follows:
<img width="1663" alt="Screenshot 2024-03-26 at 2 16 16 PM" src="https://github.com/localstack/localstack/assets/39065564/8530813b-e348-43f4-8a17-ee919415e68f">

I also tried to update the endpoint the `DynamoDBClient` connects as follows, but it did not work:
```
const dynamoDb = new DynamoDBClient(process.env.DYNAMODB_TABLE_NAME === "myapp-users-local" ? {
  endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}`,
  region: "us-east-1",
  credentials: {
    accessKeyId: "test",
    secretAccessKey: "test",
  },
  tls: false,
} : {});
```
