### ISSUE TITLE
bug: Lambdas don't HostedZone DNS Resolution after rebooting with Persistence

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#10543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting a custom domain name in Route53, lambdas will use that for resolving URLs when localstack is booted for the first time. However, if you use PERSISTENCE=1 and reboot the container, lamdbas will no longer use that DNS entry and instead attempt to hit real URLs

### Expected Behavior

The Route53 entry in LocalStack DNS should be respected even after rebooting with persistence

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yml`

```yml
version: "3.5"
services:
  localstack:
    container_name: "localstack-bugs"
    image: localstack/localstack-pro:3.2
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "80:80"
      - "443:443"
      - "4571:4571"
      - "46810:46810"
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - SNAPSHOT_SAVE_STRATEGY=ON_SHUTDOWN
      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - LAMBDA_REMOTE_DOCKER=${LAMBDA_REMOTE_DOCKER}
      - LAMBDA_DOCKER_FLAGS=${LAMBDA_DOCKER_FLAGS}
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/ssl/certs/:/etc/ssl/certs/"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
import { Stack, StackProps } from "aws-cdk-lib";
import { Construct } from "constructs";
import {
  ARecord,
  PublicHostedZone,
  RecordTarget,
} from "aws-cdk-lib/aws-route53";
import { Certificate } from "aws-cdk-lib/aws-certificatemanager";
import { LambdaIntegration, RestApi } from "aws-cdk-lib/aws-apigateway";
import {
  AllowedMethods,
  CachePolicy,
  Distribution,
  OriginProtocolPolicy,
  OriginRequestPolicy,
  ViewerProtocolPolicy,
} from "aws-cdk-lib/aws-cloudfront";
import { HttpOrigin } from "aws-cdk-lib/aws-cloudfront-origins";
import { Code, Function, Runtime } from "aws-cdk-lib/aws-lambda";
import { CloudFrontTarget } from "aws-cdk-lib/aws-route53-targets";

export class DnsInjectionStack extends Stack {
  constructor(scope: Construct, id: string, props: StackProps) {
    super(scope, id, props);

    const hostedZone = new PublicHostedZone(this, "HostedZone", {
      zoneName: "test.com",
    });

    const certificate = new Certificate(this, "Example", {
      domainName: "example.test.com",
    });

    const api = new RestApi(this, "test-api", {
      restApiName: "test-api",
      domainName: {
        domainName: "example.test.com",
        certificate,
      },
    });

    const distribution = new Distribution(this, "ApiCloudfront", {
      defaultBehavior: {
        origin: new HttpOrigin("example.test.com", {
          protocolPolicy: OriginProtocolPolicy.HTTPS_ONLY,
        }),
        allowedMethods: AllowedMethods.ALLOW_ALL,
        cachePolicy: CachePolicy.CACHING_DISABLED,
        originRequestPolicy: OriginRequestPolicy.ALL_VIEWER,
        viewerProtocolPolicy: ViewerProtocolPolicy.HTTPS_ONLY,
      },
      domainNames: ["example.test.com"],
      certificate: certificate,
    });

    new ARecord(this, "ARecord", {
      zone: hostedZone,
      recordName: "example.test.com.",
      target: RecordTarget.fromAlias(new CloudFrontTarget(distribution)),
    });

    const responseLambda = new Function(this, "response", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        "exports.handler = async (event) => ({statusCode: 201, body: JSON.stringify({ Hello: 'World' }) })",
      ),
    });

    api.root.addMethod("POST", new LambdaIntegration(responseLambda));

    const requestLambda = new Function(this, "request", {
      runtime: Runtime.NODEJS_20_X,
      handler: "index.handler",
      code: Code.fromInline(
        `exports.handler = async (event) => ({
              statusCode: 200,
              body: await fetch('https://example.test.com', { method: 'POST' }).then(data => data.text())
        })`,
      ),
    });

    api.root.addMethod("GET", new LambdaIntegration(requestLambda));
  }
}
```

```sh
CLOUDFRONT_URL=$(awslocal cloudfront list-distributions | jq -r .DistributionList.Items[0].DomainName)
curl "https://$CLOUDFRONT_URL/"

docker-compose down
docker-compose up -d

while [ ! "$(curl -s http://localhost:4566/_localstack/health | jq -c '.services | .[] | test("running|available") | not' | grep "false")" ]; do
  sleep 1
done

sleep 2

CLOUDFRONT_URL=$(awslocal cloudfront list-distributions | jq -r .DistributionList.Items[0].DomainName)
curl "https://$CLOUDFRONT_URL/"
```

In this stack we have two lambdas, on `POST /` to return a Hello World response and one on `GET /` to attempt fetching the first one with our url `https://example.text.com`.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 3.2 & Latest
```

### Anything else?

I've reproduced the issue here: https://github.com/Garethp/localstack-bugs/tree/dns-persistence
If you clone down the branch `dns-persistence`, run yarn install and then ./start.sh you should see the issue in action
