### ISSUE TITLE
bug: SAM Deploy with Image Based Lambdas that have a CompanionStack throws error: No updates are to be performed.

### ISSUE THREAD

**Issue by Chad-Bailer-Regal** [localstack/localstack#10562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using image based lambdas that have companion stacks subsequent applies throws the following error:
```
Error: An error occurred (ValidationError) when calling the UpdateStack operation: Unable to update stack "localstack-companion-stack-e4f29f11-CompanionStack": No updates are to be performed.

For more information please visit: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
```

This first apply works when it's just a create, but any subsequent apply fails and it does not respect the `no-fail-on-empty-changeset` flag. This issue appears to only happen with CompanionStack which is created when you are using a parameter in the `ImageUri` parameter of `AWS::Serverless::Function`. 

### Expected Behavior

Subsequent SAM deploys should not check companionstack for changes and shouldn't throw an error if there are no updates as that is expected.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### template.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  localstack-companionstack

  Sample SAM Template for localstack-companionstack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:

  LegacyStackName:
    Type: String

  Tag:
    Type: String

Globals:

  Function:
    Timeout: 30
    MemorySize: 320
    Environment:
      Variables:
        AWS_ACCOUNT_ID: !Ref AWS::AccountId

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: localstack-companionstack
      PackageType: Image
      ImageConfig:
        Command:
        - handler.handler
      ImageUri: !Sub 
        ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${LegacyStackName}:${Tag}  # End of Resource
```

#### samconfig.toml
```
# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "localstack-companion-stack"
s3_bucket = "aws-sam-cli-managed-test"
s3_prefix = "companionstack-test"
region = "us-east-1"


[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = [
    "LegacyStackName=companionstack-test",
    "Tag=latest",
]
[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal ecr create-repository --repository-name companionstack-test
awslocal s3api create-bucket --bucket aws-sam-cli-managed-test
docker build -t "000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4510/companionstack-test" .
docker push 000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4510/companionstack-test:latest
samlocal build --config-file samconfig.toml --template-file template.yaml --debug
samlocal deploy --config-file samconfig.toml  --no-fail-on-empty-changeset --no-confirm-changeset --resolve-image-repos
```
Then re-run sam build and deploy:
```
samlocal build --config-file samconfig.toml --template-file template.yaml --debug
samlocal deploy --config-file samconfig.toml  --no-fail-on-empty-changeset --no-confirm-changeset --resolve-image-repos
```

### Environment

```markdown
- OS: OSX 14 
- LocalStack: Localstack pro latest
- SAM 1.110.0
```

#### Example Dockerfile
```
# Simple Dockerfile illustrating Lambda container images in LocalStack

FROM public.ecr.aws/lambda/python:3.11

COPY ./handler.py ./

CMD [ "handler.handler" ]
```

#### Example handler.py
```
def handler(event, context):
    print('Hello from LocalStack Lambda container image!')
```
