### ISSUE TITLE
bug: Cannot use example from Docs for Docker Compose Pro Account

### ISSUE THREAD

**Issue by kynesis-root** [localstack/localstack#10576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot use `docker compose up -d` because LocalStack fails with an error:
```
Error response from daemon: Ports are not available: exposing port TCP 127.0.0.1:443 -> 0.0.0.0:0: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
```

I just followed the docs and this is my docker compose file:
```yaml
version: '3.8'

services:
    localstack:
        container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
        image: localstack/localstack-pro # required for Pro
        ports:
            - '127.0.0.1:4566:4566' # LocalStack Gateway
            - '127.0.0.1:4510-4559:4510-4559' # external services port range
            - '127.0.0.1:443:443' # LocalStack HTTPS Gateway (Pro)
        environment:
            - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-MY_TOKEN_IS_HERE}
            - DEBUG=${DEBUG:-0}
            - PERSISTENCE=${PERSISTENCE:-0}
        volumes:
            - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'
networks:
    dashboard_network:
        driver: bridge
```
I just copied paste the example from docs but it fails 

### Expected Behavior

I expect it to succeed and run

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Literally create this dummy docker compose file I provided above and run it.

### Environment

```markdown
- OS: M1 pro 14.4.1
- LocalStack: 3.3.0
```
