### ISSUE TITLE
bug: CREATE_FAILED ('NoneType' object is not subscriptable)

### ISSUE THREAD

**Issue by thangavignesh** [localstack/localstack#10592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This error is encountered when update the roles.

deploy: CREATE_FAILED ('NoneType' object is not subscriptable)
    at FullCloudFormationDeployment.monitorDeployment (C:\Users\tsivape\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:433:10615)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (C:\Users\tsivape\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:436:199343)
    at async C:\Users\tsivape\AppData\Roaming\npm\node_modules\aws-cdk\lib\index.js:436:180749

DEBUG=1

V2-M2E-AIO-1-sbx01-IAMStack": 'NoneType' object is not subscriptable Traceback (most recent call last):

  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1177, in _run

    self.do_apply_changes_in_loop(changes, stack)

  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1251, in do_apply_changes_in_loop

    self.apply_change(change, stack=stack)

  File "/opt/code/localstack/localstack/services/cloudformation/engine/template_deployer.py", line 1366, in apply_change

    progress_event = executor.deploy_loop(resource_provider_payload)  # noqa

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 725, in deploy_loop

    event = self.execute_action(resource_provider, payload)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/code/localstack/localstack/services/cloudformation/resource_provider.py", line 796, in execute_action

    return resource_provider.update(request)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/code/localstack/localstack/services/iam/resource_providers/aws_iam_role.py", line 219, in update

    name_changed = new_role_name and new_role_name != _states["RoleName"]

                                                      ~~~~~~~^^^^^^^^^^^^

TypeError: 'NoneType' object is not subscriptable

### Expected Behavior

IAM roles should be updated

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket


### Environment

```markdown
- OS:
- LocalStack:
```


### Anything else?

_No response_

**Comment by sannya-singal** [comment]
Hi @thangavignesh! Thanks for reaching out and logging this issue. 

We have a list of supported cloudformation resources and the subsequent operations supported by them [here](https://docs.localstack.cloud/user-guide/aws/cloudformation/#community-image) in our documentation. The resource type `AWS::IAM::Role` should support `create`, `update` and `delete` operations. 

Eg: 

Try deploying the following Cfn template: 

```
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
```
with `create-stack` command. We get `AWS cloudformation.CreateStack => 200` in LS logs. 

Now lets slightly update the template with the `Path`: 

```
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  RootRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/new/path"
```

and re-deploy it with `update-stack` command. We get `AWS cloudformation.UpdateStack => 200` in LS logs. 

Can you try the following: 
- run the sample with the `latest` docker image
- ensure its getting deployed against AWS

If the issue still persists kindly help us with the cfn template sample you are using, thanks!
