### ISSUE TITLE
bug: Different error response when missing API Gateway auth header

### ISSUE THREAD

**Issue by lukeprv** [localstack/localstack#10636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create an API Gateway REST API with an authorizer function and deploy into LocalStack:

```
Resources:

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: "Api"
      StageName: Example
      EndpointConfiguration: REGIONAL
      Auth:
        DefaultAuthorizer: Auth
        ApiKeyRequired: true
        Authorizers:
          Auth:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ReauthorizeEvery: 5

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "AuthorizerFunction"
      PackageType: Image
      ImageUri: !Sub "${ImageRepositoryUri}:${ImageTag}"
      ImageConfig:
        Command:
          - example.authorizer_handler

  MethodFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "MethodFunction"
      PackageType: Image
      ImageUri: !Sub "${ImageRepositoryUri}:${ImageTag}"
      ImageConfig:
        Command:
          - example.method_function
      Events:
        Generic:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: Api
```

Make a request to the API Gateway endpoint without the auth header:

```
$ curl -i -X POST http://example.localstack.address:4566/endpoint/
HTTP/1.1 403 
Content-Type: text/html; charset=utf-8
x-amzn-errortype: MissingAuthenticationTokenException
Content-Length: 108
Connection: close
date: Tue, 09 Apr 2024 15:32:17 GMT
server: hypercorn-h11

{"Type": "User", "message": "Missing Authentication Token", "__type": "MissingAuthenticationTokenException"}
```

### Expected Behavior

* The status code should be 401 (not 403) 
* Different `x-amzn-errortype` header
* Different body

```
$ curl -i -X POST https://actual.deployed.app/endpoint/
HTTP/2 401 
content-type: application/json
content-length: 26
date: Tue, 09 Apr 2024 15:33:35 GMT
x-amzn-requestid: ...
x-amzn-errortype: UnauthorizedException
x-amz-apigw-id: ...
x-cache: Error from cloudfront
via: ...
x-amz-cf-pop: ...
x-amz-cf-id: ...

{"message":"Unauthorized"}                                                                                            
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose with `image: localstack/localstack-pro`

### Environment

```markdown
- OS: macOS 13.0
- LocalStack: latest (3.3)
```
