### ISSUE TITLE
bug: Step Functions: heartbeat tokens become invalid when several executions run concurrently

### ISSUE THREAD

**Issue by mbaynton** [localstack/localstack#10648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I
 * start several (I'm usually running about 6 at once) executions of the same state machine
 * and that state machine has a step that sends to localstack SQS with `waitForTaskToken` and also utilizes `HeartbeatSeconds`
 * and my SQS consumers start sending heartbeat callbacks with their corresponding step function tokens

Then at first, all consumers' `SendTaskHeartbeat` calls work, but eventually at least one of the running `SendTaskHeartbeat` calls starts failing with this stringified `error`:
> {error 26 0  operation error SFN: SendTaskHeartbeat, https response error StatusCode: 400, RequestID: c95077cf-4251-464f-aa24-abdf9b7753d6, InvalidToken: }

Subsequent SendTaskHeartbeat calls continue to fail in the same manner until the state machine step times out on account of not having received any hearbeats for the defined `HeartbeatSeconds` period.

Some of the other concurrent SFN executions complete and others start during the time the longer one starts experiencing this issue, not sure if that's the cause.

### Expected Behavior

`SendTaskHeartbeat` calls continue to be accepted until I call back to SFN with a success or failure.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

By `docker compose run`ning a service with a defined dependency on `localstack`. docker-compose for the localstack service below.

```
version: '3.0'
services:
  localstack:
    image: localstack/localstack:3.3.0
    environment:
      - SERVICES=dynamodb,s3,sqs,stepfunctions
      - DATA_DIR=/var/lib/localstack/data
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - ./scripts/localstack-startup.sh:/docker-entrypoint-initaws.d/localstack-startup.sh:cached
      - ./tmp/localstack:/var/lib/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Probably requires more than a few commands, sorry.
We're experiencing this in a private codebase, I would have to write a reproduce from scratch.

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 3.3.0
```

### Anything else?

Fixed by using `PROVIDER_OVERRIDE_STEPFUNCTIONS=legacy`
