### ISSUE TITLE
Lambda Container Unable to Connect to Other Container as More Containers are Added.

### ISSUE THREAD

**Issue by fiferdc** [localstack/localstack#1069]
I'm working on an AWS project and have spent a good deal of time configuring Docker to run out project locally.  As it stands, the docker-compose script sets up our services as follows:

``` yaml
 mysql:
    image: mysql:5.6
    environment:
    - passwords...
    ports:
    - "3306:3306"
  localstack:
    depends_on:
      - mysql
    image: localstack/localstack
    environment:
    - SERVICES=lambda:4574
    - USE_SSL=false
    - LAMBDA_EXECUTOR=docker
    - LAMBDA_REMOTE_DOCKER=true
    - DOCKER_HOST=unix:///var/run/docker.sock
    - DEBUG=1
    - AWS_REGION=us-east-1
    - AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
    ports:
    - "4567-4583:4567-4583"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  foo-service:
    image: node:8
    depends_on:
    - localstack
    - mysql
```
We are using knex to handle MySQL connections and query generation.  With this setup, I can successfully make requests to _foo_ and see it read from the DB.  I can also verify that the lambda containers spawned by localstack can also connect to the DB and perform both read and write operations.

For our integration testing, we have the above compose file with the addition of:
```yaml
  mockhttp:
     ...
  test:
    image: node:8
    depends_on:
      - foo-service
    links:
      - localstack
```
I have excluded several sections of test's definition, but that should paint a clear enough picture of the setup.

The testing service is able connect and perform operations on the DB, as expected.  For whatever reason, with these five services, the spawned lambda container can no longer connect to the DB.  For the lambda, I have provided the IP address for the MySQL container as an environment variable at the time of the lambda function's creation (no errors about connecting on this address), but I am seeing connection timeouts that were not present in the lighter docker setup.

I am still trying to figure out how best to debug this and see if the error is outside of localstack, but any help understanding why the lambda container behaves differently in these two scenarios would be appreciated.
