### ISSUE TITLE
bug: SNS topic is not created when region is defined

### ISSUE THREAD

**Issue by xenosdio** [localstack/localstack#10696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to create an SNS topic through the `awslocal` CLI, if I specify the region in the arguments, the topic is not created, but the command does not also fail. It instead outputs the topic arn, but when I list the available topics it returns an empty list.

Below is an example of an attempt trying to create an SNS topic defining a region and then listing the available topics, and then doing it again, but without defining the region:

```bash
# awslocal sns create-topic --name localstack-topic --region eu-west-1
{
    "TopicArn": "arn:aws:sns:eu-west-1:000000000000:localstack-topic"
}
# awslocal sns list-topics
{
    "Topics": []
}
# awslocal sns create-topic --name localstack-topic                   
{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:localstack-topic"
}
# awslocal sns list-topics
{
    "Topics": [
        {
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:localstack-topic"
        }
    ]
}
```

### Expected Behavior

I would expect the SNS topic to be created when the region is defined.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
    image: localstack/localstack:3.3.0
    restart: always
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_SOCK=/var/run/docker.sock
      - MAIN_CONTAINER_NAME=localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal sns create-topic --name localstack-topic --region eu-west-1
    awslocal sns list-topics

### Environment

```markdown
- OS: MacOS 14.4.1
- LocalStack: 3.3.0
```
