### ISSUE TITLE
get secrets Manager Value parsing time error

### ISSUE THREAD

**Issue by respc** [localstack/localstack#1070]
```
caused by: parsing time "2018-05-23 13:16:57.198000" as "2006-01-02T15:04:05Z": cannot parse " 13:16:57.198000" as "T"
```

**Comment by whummer** [comment]
Thanks for reporting @xueyumin - can you please provide some more details about your environment, and a small self-contained example to reproduce this error? Thanks

**Comment by xueyumin** [comment]
docker-compose.yml
```yml
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
    environment:
      - SERVICES=secretsmanager:4584
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
```


```go
func GetSecretValue(svc secretsmanageriface.SecretsManagerAPI, secretID string) (*DBSecret, error) {

	input := &secretsmanager.GetSecretValueInput{
		SecretId:     aws.String(secretID),
		VersionStage: aws.String(version),
	}

	result, err := svc.GetSecretValue(input)
	if err != nil {
                 //   error : caused by: parsing time "2018-05-23 13:16:57.198000" as "2006-01-02T15:04:05Z": cannot parse " 13:16:57.198000" as "T"

		return nil, errors.Wrap(err, "secrets manager error")
	}

	var dbSecret DBSecret
	if err := json.Unmarshal([]byte(aws.StringValue(result.SecretString)), &dbSecret); err != nil {
		return nil, errors.Wrap(err, "JSON Unmarshal error")
	}

	return &dbSecret, nil
}
```

the time `2018-05-23 13:16:57.198000` format timezone is not included
correct format : `2006-01-02T15:04:05Z`

thank you so much
