### ISSUE TITLE
Connect to localhost:4568 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by DrakkenSaer** [localstack/localstack#1078]
Hi there, I am having trouble connecting to Kinesis on localstack. Everything runs fine when I run it locally, the error happens inside of our Jenkins pipeline.

Here is the Dockerfile I am using:
```
FROM hseeberger/scala-sbt:8u181_2.12.7_1.2.6

USER root
RUN apt-get update
RUN apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get -y install nodejs
RUN apt-get install npm
RUN curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
```

And here is my docker-compose.yml:
```
version: '3.6'

services:
  # AWS services in docker env
  localstack:
    image: localstack/localstack:latest
    environment:
    - SERVICES=kinesis,dynamodb,s3,cloudwatch
    - HOSTNAME_EXTERNAL=localstack
    - DATA_DIR=/tmp/localstack/data
    volumes:
    - "/tmp:/tmp"
    ports:
    - "4568:4568"
    - "4569:4569"
    - "4572:4572"
    - "4582:4582"

  postgres:
    image: "postgres:9.6"
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: *******
      POSTGRES_DB: table
      PGPASSWORD: *******
    volumes:
    - ./docker/postgres-init:/docker-entrypoint-initdb.d

  mocks:
    image: "jordimartin/mmock"
    volumes:
    - "./docker/mocks:/config"
    ports:
    - "8082:8082"
    - "8083:8083"
    - "8084:8084"

  aws-create-stream:
    image: "ivonet/aws-cli:1.0.0"
    links:
    - localstack
    volumes:
    - ${HOME}/.aws:/root/.aws:ro
    command: --endpoint-url=http://localstack:4568 kinesis create-stream --stream-name RawScanPipe --shard-count 1
    environment:
      - AWS_DEFAULT_REGION=us-east-1

  #PGAdmin gives a nice gui on the PostgreSQL DB
  pgadmin:
    image: dpage/pgadmin4
    links:
    - postgres
    depends_on:
    - postgres
    ports:
    - "8888:80"
    volumes:
    - ./docker/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: *********
      PGADMIN_DEFAULT_PASSWORD: *********
```

In case it matters, here is the segment in our Jenkins file where this gets called:
```
def sbtInside() {
  return "-u root -v /usr/bin/docker:/usr/bin/docker " +
          "-v /usr/local/bin/aws:/usr/local/bin/aws " +
          "-v /var/run/docker.sock:/var/run/docker.sock " +
          "-v /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/libltdl.so.7 " +
          "-v $HOME/.ivy2:/root/.ivy2 " +
          "-v $HOME/.sbt:/root/.sbt"
}

    stage("Unit/Functional Tests & Create Dockerfile") {
      app.inside(sbtInside()) {
        try {
          echo "Starting unit tests..."
          sh "TARGET=LOCAL sbt clean test"

          echo "Starting up test stack..."
          sh "docker-compose -f docker-compose.yml up -d"

          echo "Starting functional tests..."
          sh "TARGET=LOCAL " +
              "PRODUCT_ENABLED=true " +
              "sbt clean functional/test"
        } finally {
          echo "Tests complete!"
          sh "docker-compose -f docker-compose.yml down -v"
          sh "sbt docker"
        }
      }
    }
```

I am sure I am missing something simple, I just can't figure out what it is!
