### ISSUE TITLE
bug: ElastiCache: Unable to get ConfigurationEndpoint created by create-replication-group with REDIS_CONTAINER_MODE

### ISSUE THREAD

**Issue by rimokuto** [localstack/localstack#10825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't get ConfigurationEndpoint created by create-replication-group with `REDIS_CONTAINER_MODE=1`.

### Expected Behavior

ConfigurationEndpoint must be obtained.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml
```
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "4510-4521:4510-4521
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REDIS_CONTAINER_MODE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${LOCALSTACK_VOLUME_DIR:-/var/lib/localstack}:/var/lib/localstack"

```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal elasticache create-replication-group \
   --engine redis \
   --replication-group-id my-clustered-redis-replication-group \
   --replication-group-description 'my clustered replication group' \
   --cache-node-type cache.t2.micro \
   --num-node-groups 2 \
   --replicas-per-node-group 2
```

```
awslocal elasticache describe-replication-groups --no-cli-pager --output text --query "ReplicationGroups[].[ReplicationGroupId,ConfigurationEndpoint.Port]"
```

Return
```
my-clustered-redis-replication-group    None
```

### Environment

```markdown
- OS: WSL Ubuntu-20.04 on Windows 11
- LocalStack: latest(3.4.0)
```

### Anything else?

Terraform resource `aws_elasticache_replication_group` also does not complete.
