### ISSUE TITLE
bug: API Gateway integration Issues GET Request to S3 Instead of PUT

### ISSUE THREAD

**Issue by AlexBrohshtut** [localstack/localstack#10886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the Serverless Framework with LocalStack, a PUT integration request from API Gateway is incorrectly being sent as a GET request to S3. This results in a 404 Not Found error due to the object not being found in the S3 bucket.

Logs:
```log
localstack: 2024-05-24T05:15:58.371 DEBUG --- [   asgi_gw_0] rolo.gateway.wsgi          : PUT localhost:4566/restapis/kbn0oqb5iz/local/_user_request_/api/test.json
localstack: 2024-05-24T05:15:58.392 DEBUG --- [   asgi_gw_5] rolo.gateway.wsgi          : GET localhost:4566/restapis/kbn0oqb5iz/resources?limit=100
localstack: 2024-05-24T05:15:58.403  INFO --- [   asgi_gw_5] l.request.internal.aws     : AWS apigateway.GetResources => 200
localstack: 2024-05-24T05:15:58.406 DEBUG --- [   asgi_gw_0] l.s.apigateway.helpers     : Match found for path: '/api/test.json' and method: 'PUT'
localstack: 2024-05-24T05:15:58.407 DEBUG --- [   asgi_gw_0] l.s.apigateway.integration : Getting request for bucket bb245-sfp object test.json
localstack: 2024-05-24T05:15:58.412 DEBUG --- [   asgi_gw_3] rolo.gateway.wsgi          : GET s3.localhost.localstack.cloud:4566/bb245-sfp/test.json
localstack: 2024-05-24T05:15:58.415 DEBUG --- [   asgi_gw_3] l.aws.protocol.serializer  : Determined accept type (None) is not supported by this serializer. Using default of this serializer: application/xml
localstack: 2024-05-24T05:15:58.416  INFO --- [   asgi_gw_3] l.request.internal.aws     : AWS s3.GetObject => 404 (NoSuchKey)
localstack: 2024-05-24T05:15:58.418 DEBUG --- [   asgi_gw_0] l.s.apigateway.integration : Object test.json not found
localstack: 2024-05-24T05:15:58.419  INFO --- [   asgi_gw_0] localstack.request.http    : PUT /restapis/kbn0oqb5iz/local/_user_request_/api/test.json => 404; Request(b'{\n}\n', headers={'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/7.39.0', 'Accept': '*/*', 'Postman-Token': 'c4e6accf-a13b-4dd2-a196-74e562097295', 'Host': 'localhost:4566', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Content-Length': '4', '__apigw_request_region__': 'us-east-1'}); Response(b'{"Type": "User", "message": "Object test.json not found", "__type": "NotFoundException"}', headers={'Content-Type': 'text/html; charset=utf-8', 'x-amzn-errortype': 'NotFoundException', 'Content-Length': '88'})
```

### Expected Behavior

A PUT HTTP method of integrartion in API Gateway should result in a PUT request being sent to the S3 bucket.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Based on this repo: https://github.com/aws-samples/serverless-patterns//blob/master/apigw-s3-lambda-sls-py/serverless.yml
Docker compose:
```yaml
services:
    localstack:
        container_name: localstack
        image: localstack/localstack:3.4.0-arm64
        environment:
            - SERVICES=s3,iam,sts,lambda,apigateway,cloudformation,cloudwatch,logs,sqs
            - LS_LOG=trace
        ports:
            - '127.0.0.1:4566:4566'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
```

```yaml
service: sls-${self:custom.name}-sfp

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 3
  tracing:
    apiGateway: true

custom:
  name: bb245
  bucket_name: bb245-sfp
  localstack:
    stages:
      - local

functions:
  ProcessS3Data:
    handler: process_s3_data.lambda_handler
    role: ProcessS3DataIamRole
    memorySize: 256
    events:
      - s3:
          bucket: !Ref S3Bucket
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    IAMRoleForAPIGateway:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: apigateway.amazonaws.com
              Action: sts:AssumeRole
        Description: Role for ${self:service}
        Path: /
        Policies:
          - PolicyName: ${self:service}-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: s3:PutObject
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "S3Bucket"
                        - "/*"
    ProcessS3DataIamRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /ProcessS3DataIamRole/
        RoleName: Process-S3-Data-Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: Process-S3-Data-Role-Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: "Allow"
                  Action:
                    - s3:GetObject
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "S3Bucket"
                        - "/*"
    RestAPI:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:provider.stage}
        EndpointConfiguration:
          Types:
            - REGIONAL
    RestAPIResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: !GetAtt RestAPI.RootResourceId
        PathPart: api
        RestApiId: !Ref RestAPI
    RestAPIObjectPathResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: !Ref RestAPIResource
        PathPart: '{order_object_path+}'
        RestApiId: !Ref RestAPI
    RestAPIPutMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        HttpMethod: PUT
        AuthorizationType: NONE
        Integration:
          TimeoutInMillis: 7000
          Type: AWS
          IntegrationHttpMethod: PUT
          Uri: arn:aws:apigateway:${self:provider.region}:s3:path/bb245-sfp/{order_object_path}
          Credentials: !GetAtt IAMRoleForAPIGateway.Arn
          RequestParameters:
            integration.request.path.order_object_path: 'method.request.path.order_object_path'
          IntegrationResponses:
            - StatusCode: 200
            - StatusCode: 400
              SelectionPattern: 4\d{2}
            - StatusCode: 500
              SelectionPattern: 5\d{2}
          PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestParameters:
          method.request.path.order_object_path: true
          method.request.header.Content-Type: true
        OperationName: write-order-data-to-s3
        ResourceId: !Ref RestAPIObjectPathResource
        RestApiId: !Ref RestAPI
        MethodResponses:
          - StatusCode: 200
            ResponseModels:
              application/json: 'Empty'
          - StatusCode: 400
            ResponseModels:
              application/json: 'Error'
          - StatusCode: 500
            ResponseModels:
              application/json: 'Error'
    RestAPIDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId: !Ref RestAPI
      DependsOn:
        - RestAPIPutMethod
    RestAPIStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        DeploymentId: !Ref RestAPIDeployment
        Description: ${self:provider.stage} stage
        RestApiId: !Ref RestAPI
        StageName: ${opt:stage, 'local'}
        Variables:
          bucket_name: ${self:custom.bucket_name}
    S3Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        BucketName: ${self:custom.bucket_name}
        VersioningConfiguration:
          Status: Suspended
        AccessControl: Private

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
  ApiRootUrl:
    Value: !Sub 'https://${RestAPI}.execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/api/{order_object_path+}'
plugins:
  - serverless-python-requirements
  - serverless-localstack
```

### Environment

```markdown
- OS: MacOS Sonoma 14.4.1
- LocalStack:
  LocalStack version:3.4.0-arm64
  LocalStack Docker image sha: sha256:8569dadc82ddf0627569775dde517297351691ddbe28e60edd1f515b46f7ef2e
  LocalStack build date: 2024-04-25
  LocalStack build git hash: 6f971ac81
```

### Anything else?

Is there any viable way to put file from APi Gateway to S3 without lambda? Using
          `Uri: !Sub 'arn:aws:apigateway:${self:provider.region}:s3:action/PutObject?bucket=${self:custom.bucket_name}&key=test.js'`

Leads to:
```log
2024-05-24T05:27:24.784 DEBUG --- [   asgi_gw_1] rolo.gateway.wsgi          : PUT localhost:4566/restapis/a1jz3wmfrm/local/_user_request_/api/test.json
2024-05-24T05:27:24.830065723Z 2024-05-24T05:27:24.829 DEBUG --- [   asgi_gw_4] rolo.gateway.wsgi          : GET localhost:4566/restapis/a1jz3wmfrm/resources?limit=100
2024-05-24T05:27:24.837553207Z 2024-05-24T05:27:24.837  INFO --- [   asgi_gw_4] l.request.internal.aws     : AWS apigateway.GetResources => 200
2024-05-24T05:27:24.842231405Z 2024-05-24T05:27:24.841 DEBUG --- [   asgi_gw_1] l.s.apigateway.helpers     : Match found for path: '/api/test.json' and method: 'PUT'
2024-05-24T05:27:24.843509319Z 2024-05-24T05:27:24.843  WARN --- [   asgi_gw_1] l.s.apigateway.integration : Request URI does not match s3 specifications
2024-05-24T05:27:24.844409817Z 2024-05-24T05:27:24.844  INFO --- [   asgi_gw_1] localstack.request.http    : PUT /restapis/a1jz3wmfrm/local/_user_request_/api/test.json => 400; Request(b'{\n}\n', headers={'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/7.39.0', 'Accept': '*/*', 'Postman-Token': '2605d7bf-6021-48f6-acbe-880b6f2db8e2', 'Host': 'localhost:4566', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'Content-Length': '4', '__apigw_request_region__': 'us-east-1'}); Response(b'{"Type": "User", "message": "Request URI does not match s3 specifications", "__type": "InvalidRequest"}', headers={'Content-Type': 'text/html; charset=utf-8', 'x-amzn-errortype': 'InvalidRequest', 'Content-Length': '103'})
2024-05-24T05:27:27.493499945Z 
```
