### ISSUE TITLE
bug: Cannot list dynamodb streams on stream-enabled table

### ISSUE THREAD

**Issue by mn-prp** [localstack/localstack#10885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a stream enabled on a table, but if I call list-streams, I get an empty array back.
<img width="788" alt="image" src="https://github.com/localstack/localstack/assets/105884647/d983e210-d0a7-47a2-b20c-46fa29d741a6">
However, If I call `awslocal kinesis list-streams`, I do see the stream.

### Expected Behavior

I expect the streams to be listed in list-streams.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`ALLOW_NONSTANDARD_REGIONS=1 /opt/homebrew/bin/localstack start`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I set up the table using serverless offline

```
plugins:
  - serverless-esbuild
  - serverless-offline-dynamodb-streams
  - serverless-dynamodb

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 4566
      inMemory: true
      migrate: true
      seed: true
      noStart: true
    seed:
      streams:
        sources:
          - table: ${env:STREAMS_TABLE_NAME, 'streams'}
            sources:
              [./services/tailor/serverless-offline/streams-table-seed.json]
  serverless-offline-dynamodb-streams:
    apiVersion: '2013-12-02'
    endpoint: http://0.0.0.0:4566
    pollForever: true
    accessKeyId: 'dummy'
    secretAccessKey: 'dummy'

resources:
  Resources:
    StreamsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: orgCode
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        TableName: StreamsTable
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
          StreamEnabled: true
```

    awslocal dynamodb describe-table --table-name streams --query "StreamSpecification" # shows stream enabled
    awslocal dynamodbstreams list-streams # empty array
    awslocal kinesis list-streams # shows stream in array

### Environment

```markdown
- OS: MacOS 14.5
- LocalStack:
  LocalStack version: 3.3.0
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```
