### ISSUE TITLE
Lambda Function Can't Access LocalStack S3 object When Invoked Locally

### ISSUE THREAD

**Issue by VSVDEv** [localstack/localstack#10897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i try getObject from s3 bucket i get enpty result during sam local invocation. when I deploy function to localstack it works correct

### Expected Behavior

return object from s3 bucket

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`sam build`

`C:\Users\username\.aws`(windows) or ~/.aws (unix)

update config file adding endpoint_url

```config
[profile sv]
region = us-east-1
output = json
endpoint_url = http://localhost:4566
```

sam local generate-event s3 put --bucket vsvdevsource > events/s3.json

```json
{
  "Records": [
    {
      "eventVersion": "2.0",
      "eventSource": "aws:s3",
      "awsRegion": "us-east-1",
      "eventTime": "1970-01-01T00:00:00.000Z",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "EXAMPLE"
      },
      "requestParameters": {
        "sourceIPAddress": "127.0.0.1"
      },
      "responseElements": {
        "x-amz-request-id": "EXAMPLE123456789",
        "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH"
      },
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "testConfigRule",
        "bucket": {
          "name": "vsvdevsource",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          },
          "arn": "arn:aws:s3:::vsvdevsource"
        },
        "object": {
          "key": "test2.txt",
          "size": 1024,
          "eTag": "0123456789abcdef0123456789abcdef",
          "sequencer": "0A1B2C3D4E5F678901"
        }
      }
    }
  ]
}


```
```java

package vsvdev;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.S3Event;
import com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import com.amazonaws.services.s3.model.S3Object;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;


public class App2 implements RequestHandler<S3Event, String> {

     AmazonS3 s3 ;
    private static final String WORD_BREAK = "\\W+";




    public App2() {

    }

    @Override
    public String handleRequest(S3Event event, Context context) {

        String accesskey = "test";
        String secret = "test";
        String endpoint = "s3.localhost.localstack.cloud:4566";
        s3 = AmazonS3ClientBuilder.standard()
                // .withCredentials(new ProfileCredentialsProvider())
                .withCredentials((new AWSStaticCredentialsProvider(new BasicAWSCredentials(accesskey,secret))))

                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, "us-east-1"))

                // comment if you want to use virtual host style
                //  like https://bucket-name.s3.region-code.amazonaws.com/key-name
                .withPathStyleAccessEnabled(true)

                // localstack  works with both Path-style requests and Virtual-hosted–style requests
                // https://s3.region-code.amazonaws.com/bucket-name/key-name
                // https://bucket-name.s3.region-code.amazonaws.com/key-name

                // https://localhost:4566/bucket-name/key-name
                // https://bucket-name.localhost:4566/key-name
                //  GET https://vsvdevsource.s3.localhost.localstack.cloud:4566/test2.txt
                // GET https://s3.localhost.localstack.cloud:4566/vsvdevsource/test2.txt

                .build();

		
		
        LambdaLogger logger = context.getLogger();

        S3EventNotification.S3EventNotificationRecord record = event.getRecords().get(0);
       // logger.log("*******************The source bucket env is: " + System.getenv("SOURCE_BUCKET"));

        String bucketName = record.getS3().getBucket().getName();
        logger.log("*******************The source bucket is: " + bucketName);
        String key = record.getS3().getObject().getKey();
        logger.log("*******************The key is: " + key);
        String fileName = record.getS3().getObject().getKey();
        logger.log("*******************The filename is: " + fileName);

        String stringToRemove = "/key";
        
        // Using replace method
        String finalKey = fileName.replace(stringToRemove, "");
        logger.log("*******************The final name is: " + finalKey);




        String input = getFileFromS3(finalKey, bucketName);
        logger.log("*******************The input is: " + input);
        Set<String> uniqueWords;
        if (input.length() > 0) {
            uniqueWords = processString(input);
        } else {
            logger.log("Error: Input is empty ");
            throw new RuntimeException("Input is empty");
        }



        StringBuilder processedContent = new StringBuilder();
        for (String word : uniqueWords) {
            processedContent.append(word).append("\n");
        }



        String processedFileName = generateUniqueFileName(finalKey);
        logger.log("******************filename is : " + processedFileName);
        logger.log("******************content is : " + processedContent);
        logger.log("******************Destination bucket is : " + System.getenv("DESTINATION_BUCKET"));

        try {
            writeToS3(processedContent, processedFileName);
            logger.log("Processed file uploaded successfully: " + processedFileName);

            return processedFileName;
        } catch (Exception e) {
            logger.log("Processed file didn't uploaded successfully: " + processedFileName);
            logger.log("The reason is: " + e.getMessage());
            return "";
        }

    }

    public void writeToS3(StringBuilder processedContent, String processedFileName) throws Exception{

        
            ByteArrayInputStream output = new ByteArrayInputStream(processedContent.toString().getBytes(StandardCharsets.UTF_8));
            ObjectMetadata metadata = new ObjectMetadata();
            metadata.setContentLength(processedContent.length());
            String outputBucketName = "vsvdevdestination";
            PutObjectRequest putObjectRequest = new PutObjectRequest(outputBucketName, processedFileName, output, metadata);
            s3.putObject(putObjectRequest);
           
    
    }


    private String getFileFromS3(String fileName, String bucketName) {

        /// String bucketName = System.getenv("SOURCE_BUCKET");

        try {
            S3Object obj = s3.getObject(bucketName, fileName);
            byte[] bytes = obj.getObjectContent().readAllBytes();

            return new String(bytes, StandardCharsets.UTF_8);

        } catch (Exception e) {

            System.out.println("Exception here" + e);

            return "";
        }

    }

    private static Set<String> processString(String content) {
        return Arrays.stream(content.split(WORD_BREAK)).collect(Collectors.toSet());
    }

    private static String generateUniqueFileName(String fileName) {
        String[] parts = fileName.split("\\.");
        String extension = parts.length > 1 ? "." + parts[parts.length - 1] : "";
        return "processed-" + fileName.replace(extension, "") + "-" + System.currentTimeMillis() + extension;
    }
}


```

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Storage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Storage
      # Lambda deployed to localstack
      #Handler: vsvdev.App::handleRequest
      # Lambda locally tested with localstack
      Handler: vsvdev.App2::handleRequest
     # Handler: vsvdev.App3::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 15
      Policies:
        - S3ReadPolicy:
            BucketName: sourceconfigbckt
        - S3CrudPolicy:
            BucketName: destinationconfigbckt
      Environment:
        Variables:
          SOURCE_BUCKET: vsvdevsource
          DESTINATION_BUCKET: vsvdevdestination
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_ENDPOINT_URL: s3.localhost.localstack.cloud:4566 #localstack
          #AWS_ENDPOINT_URL: http://localhost:8080             #vsvdev emulator
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref sourceconfigbckt
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.txt'

  sourceconfigbckt:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vsvdevsource

  destinationconfigbckt:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vsvdevdestination
      
```

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>vsvdev</groupId>
    <artifactId>Storage</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <name>A sample to work with s3.</name>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-core</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
          <groupId>com.amazonaws</groupId>
          <artifactId>aws-lambda-java-events</artifactId>
          <version>3.11.0</version>
        </dependency>
        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>4.13.2</version>
          <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3 -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.12.710</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.google.code.gson/gson -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10</version>
        </dependency>

    </dependencies>

    <build>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>3.2.4</version>
          <configuration>
          </configuration>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>shade</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
</project>


```
aws s3api create-bucket --bucket vsvdevsource --profile sv

aws s3api create-bucket --bucket vsvdevdestination --profile sv

aws s3api list-objects --bucket vsvdevdestination --profile sv

aws s3api put-object --bucket vsvdevsource --key test2.txt --body test2.txt --profile sv

aws s3api list-objects --bucket vsvdevdestination --profile sv

sam local invoke Storage --event s3.json

```txt

Mounting C:\Users\vsvdev\Desktop\aws_lambda\s3\.aws-sam\build\Storage as /var/task:ro,delegated, inside runtime   
container
START RequestId: bd05044b-d401-4df9-b973-12f2639fa7fa Version: $LATEST
*******************The source bucket is: vsvdevsource*******************The key is: test2.txt*******************The filename is: test2.txt*******************The final name is: test2.txtException herecom.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to s3.localhost.localstack.cloud:4566 [s3.localhost.localstack.cloud/127.0.0.1] failed: Connection refused
*******************The input is: Error: Input is empty Input is empty: java.lang.RuntimeException
java.lang.RuntimeException: Input is empty
        at vsvdev.App2.handleRequest(App2.java:93)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)

END RequestId: fc09cfa1-e4cc-4602-a0a7-e40fa2ff4734
REPORT RequestId: fc09cfa1-e4cc-4602-a0a7-e40fa2ff4734  Init Duration: 0.04 ms  Duration: 2415.95 ms    Billed Duration: 2416 ms  Memory Size: 512 MB     Max Memory Used: 512 MB
{"errorMessage": "Input is empty", "errorType": "java.lang.RuntimeException", "stackTrace": ["vsvdev.App2.handleRequest(App2.java:93)", "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)", "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)", "java.base/java.lang.reflect.Method.invoke(Unknown Source)"]}
```

### Environment

```markdown
- OS: Windows 10 
- LocalStack:
  LocalStack version: latest 25 May 2024
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```
