### ISSUE TITLE
Problem resolving Env aws variables when deploying lambda CloudFormation

### ISSUE THREAD

**Issue by danielferayte** [localstack/localstack#10981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, i would like to mention a problem that i found when trying to deploy a lamba by Cloudformation:
i do have this template:
```
LambdaFunctionProcesoEnvio:
    Type: 'AWS::Lambda::Function'
    Properties:
      Timeout: 900
      Code:
        S3Bucket: mybucket
        S3Key: code.zip  
      FunctionName: proccesEnvio
      Runtime: nodejs20.x
      Handler: "src/claims/app.handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Description: Lambda claims
      Environment:
        Variables:
          DATABASE_SECRET_NAME: "co-claim-integration-layer-oracle-db-local"
          AUTHENTICATION_API_PATH: 'https://hlqwwkrg4g.execute-api.us-east-1.amazonaws.com/desa/api/autenticar'
      MemorySize: 128
```
The problem is when i do deploy this stack in localstack with aws --endpoint-url=http://localhost:4566 cloudformation deploy --stack-name myStack--template-file "./template.yml” and i see the lamba configuration with aws lambda get-function-configuration --function-name proccesEnvio --endpoint-url=http://localhost:4566
i do get this env values:

```
"Environment": {
    "Variables": {
      "DATABASE_SECRET_NAME": "co-claim-integration-layer-oracle-db-local"  
      "AUTHENTICATION_API_PATH": "https://hlqwwkrg4g.execu.amazonaws.com:4566/desa/api/autenticar",
  }
```
For some reason is changing the env value of AUTHENTICATION_API_PATH to the local, but that is not the idea since i need to use the external api. To resolve this i do tried to add the url to the DNS_NAME_PATTERNS_TO_RESOLVE_UPSTREAM in order to ignore this dns but it does not work, i have tried different patterns but the result is the same
```
localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - MAIN_DOCKER_NETWORK=salvatagio
      - DNS_NAME_PATTERNS_TO_RESOLVE_UPSTREAM=hlqwwkrg4g.execute-api.amazonaws.com
      # - LAMBDA_EXECUTOR=docker-reuse  # Ensure the Lambda executor is set to Docker
      # - LAMBDA_REMOTE_DOCKER=false  # Ensure the Lambda executor uses the host Docker network
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - salvatagio
```
To resolve this problem i just need to add a space in the lamba env variables
AUTHENTICATION_API_PATH: ' https://hlqwwkrg4g.execute-api.us-east-1.amazonaws.com/desa/api/autenticar'
whin this configuration localstack does not change the value when deploying the lamba, but i would like to know it this is a problem, or there is one way to resolve it without adding the space at the beginning of the variable

     

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

aws s3 mb s3://mybucket--endpoint-url=http://localhost:4566
aws s3 cp code.zip s3://salvatagio/ --endpoint-url=http://localhost:4566
aws --endpoint-url=http://localhost:4566 cloudformation deploy --stack-name myStack --template-file "./template.yml”
 aws lambda get-function-configuration --function-name proccesEnvio --endpoint-url=http://localhost:4566
