### ISSUE TITLE
bug: localstack: command not found on Github Actions

### ISSUE THREAD

**Issue by gkatsanos** [localstack/localstack#11034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
---
name: Main PR Pipeline
'on':
  pull_request:
jobs:
  validate_repo:
    runs-on: default-visable
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.head_ref || github.ref }}"
    - name: repository check
      run: |
        CONFIGURED_REPO=$(grep -w repository_name visable.yaml | cut -d : -f 2 | sed 's/[[:space:]"]//g')
        [ -z ${CONFIGURED_REPO} ] && exit 0
        [[ $GITHUB_REPOSITORY == $CONFIGURED_REPO ]] || exit 1
  docker_build:
    runs-on: default-visable
    if: "${{ github.event.inputs.skip_docker_build != 'true' }}"
    steps:
    - name: Detect configuration overwrite via environment variables
      shell: bash
      run: |
        echo "docker_file_path=$(echo ${DOCKER_FILE_PATH:-Dockerfile})" >> $GITHUB_OUTPUT
        echo "docker_build_args=$(echo ${{ env.DOCKER_BUILD_ARGS }})" >> $GITHUB_OUTPUT
        echo "docker_build_path=$(echo ${DOCKER_BUILD_PATH:-'.'})" >> $GITHUB_OUTPUT
        echo "image_name=$(echo ${IMAGE_NAME:-''})" >> $GITHUB_OUTPUT
        echo "latest_tag_enabled=$(echo ${LATEST_TAG_ENABLED:-'true'})" >> $GITHUB_OUTPUT
      id: configuration
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.head_ref || github.ref }}"
        submodules: recursive
    - name: Checkout Private Github Action
      uses: actions/checkout@v4
      with:
        repository: visable-dev/gh-action-docker-build
        ref: v1
        token: "${{ secrets.REPO_ACCESS_TOKEN }}"
        path: "./gh-action-docker-build/"
    - name: Build docker image
      uses: "./gh-action-docker-build"
      with:
        github_token: "${{ secrets.REPO_ACCESS_TOKEN }}"
        docker_file_path: "${{ steps.configuration.outputs.docker_file_path }}"
        build_args: "${{ steps.configuration.outputs.docker_build_args }}"
        docker_build_path: "${{ steps.configuration.outputs.docker_build_path }}"
        image_name: "${{ steps.configuration.outputs.image_name }}"
        latest_tag_enabled: "${{ steps.configuration.outputs.latest_tag_enabled }}"
    needs:
    - validate_repo
  cypress:
    runs-on: default-visable
    env:
      GITHUB_TOKEN: "${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}"
      IS_CYPRESS: 'true'
      S3_BUCKET_ARN: arn:aws:s3:::requests-frontend-local
      AWS_REGION: eu-central-1
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Start LocalStack
      uses: LocalStack/setup-localstack@v0.2.0
      with:
        image-tag: latest
        install-awslocal: 'true'
        configuration: DEBUG=1
    - name: Start localstack s3 bucket
      run: awslocal s3api create-bucket --bucket requests-frontend-local
    - uses: pnpm/action-setup@v4
      with:
        version: 9.1.1
    - name: Define proper Checkout REF
      shell: bash
      run: echo "ref=$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF}})" >> $GITHUB_OUTPUT
      id: extract_ref
    - uses: actions/checkout@v4
      with:
        ref: "${{ steps.extract_ref.outputs.ref }}"
    - name: setup github packages authentication
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_READ_ONLY_TOKEN_GITHUB }}" > ~/.npmrc
    - uses: cypress-io/github-action@v6
      id: cypress
      with:
        build: pnpm build
        start: pnpm start
        browser: chrome
    - name: cleanup repo files
      if: always()
      run: find . -mindepth 1 -delete
    needs:
    - validate_repo

```

```
/opt/actions-runner/_work/_temp/3545f172-bc69-4c08-a837-166fcf3daf1a.sh: line 12: localstack: command not found
```

### Expected Behavior

localstack starts

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

via the localstack github action 

### Environment
Amazon linux 2023
![image](https://github.com/localstack/localstack/assets/1768834/c6f06982-dc91-48e2-b425-e640b6caba4e)
![image](https://github.com/localstack/localstack/assets/1768834/75763e40-6267-42dd-860d-7cfed34b07e3)

```markdown
doesnt start
```

### Anything else?

no
