### ISSUE TITLE
feature request: support AWS SAM serverless connectors (`AWS::Serverless::Connector`)

### ISSUE THREAD

**Issue by davidjb** [localstack/localstack#11044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

Support for Connectors within AWS SAM configuration for simplifying IAM policies, allowing their centralised, declarative-style permission definitions over manually managing and repeating policies.

Description from the AWS Developer Guide:

> Connectors are an AWS Serverless Application Model (AWS SAM) abstract resource type, identified as `AWS::Serverless::Connector`, that provides simple and well-scoped permissions between your serverless application resources. Use the Connectors resource attribute by embedding it within a source resource. Then, define your destination resource and describe how data or events should flow between those resources. AWS SAM then composes the access policies necessary to facilitate the required interactions.

### 🧑‍💻 Implementation

SAM has its Connectors openly defined at https://github.com/aws/serverless-application-model/blob/develop/samtranslator/model/connector_profiles/profiles.json with a permissive license, so perhaps LocalStack could draw from this directly.

### Anything else?

* Blog Announcement: https://aws.amazon.com/about-aws/whats-new/2022/10/aws-sam-serverless-connectors/
* Developer Guide: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html
* Connector Reference: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/reference-sam-connector.html

**Comment by pinzon** [comment]
Hello! I just did a quick triage of your issues and it seems to me that the latest version of LocalStack already supports the AWS::Serverless::Connector resource.

I used the template from the docs:
```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !GetAtt Function.Arn
          Protocol: lambda

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs16.x
      Handler: index.handler
      InlineCode: |
        const AWS = require('aws-sdk');
        exports.handler = async (event, context) => {
          const docClient = new AWS.DynamoDB.DocumentClient();
          await docClient.put({ 
            TableName: process.env.TABLE_NAME, 
            Item: {
              id: context.awsRequestId,
              event: JSON.stringify(event)
            }
          }).promise();
        };
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

  Table:
    Type: AWS::Serverless::SimpleTable

  TopicToFunctionConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source: 
        Id: Topic
      Destination: 
        Id: Function
      Permissions:
        - Write

  FunctionToTableConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source: 
        Id: Function
      Destination: 
        Id: Table
      Permissions:
        - Write
```

And the processed template is:
```json
{
        "Transform": "AWS::Serverless-2016-10-31",
        "Resources": {
            "Topic": {
                "Type": "AWS::SNS::Topic",
                "Properties": {
                    "Subscription": [
                        {
                            "Endpoint": {
                                "Fn::GetAtt": [
                                    "Function",
                                    "Arn"
                                ]
                            },
                            "Protocol": "lambda"
                        }
                    ]
                }
            },
            "Function": {
                "Type": "AWS::Lambda::Function",
                "Properties": {
                    "Code": {
                        "ZipFile": "const AWS = require('aws-sdk');\nexports.handler = async (event, context) => {\n  const docClient = new AWS.DynamoDB.DocumentClient();\n  await docClient.put({ \n    TableName: process.env.TABLE_NAME, \n    Item: {\n      id: context.awsRequestId,\n      event: JSON.stringify(event)\n    }\n  }).promise();\n};\n"
                    },
                    "Handler": "index.handler",
                    "Role": {
                        "Fn::GetAtt": [
                            "FunctionRole",
                            "Arn"
                        ]
                    },
                    "Runtime": "nodejs16.x",
                    "Environment": {
                        "Variables": {
                            "TABLE_NAME": {
                                "Ref": "Table"
                            }
                        }
                    },
                    "Tags": [
                        {
                            "Key": "lambda:createdBy",
                            "Value": "SAM"
                        }
                    ]
                }
            },
            "FunctionRole": {
                "Type": "AWS::IAM::Role",
                "Properties": {
                    "AssumeRolePolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Action": [
                                    "sts:AssumeRole"
                                ],
                                "Effect": "Allow",
                                "Principal": {
                                    "Service": [
                                        "lambda.amazonaws.com"
                                    ]
                                }
                            }
                        ]
                    },
                    "ManagedPolicyArns": [
                        "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
                    ],
                    "Tags": [
                        {
                            "Key": "lambda:createdBy",
                            "Value": "SAM"
                        }
                    ]
                }
            },
            "Table": {
                "Type": "AWS::DynamoDB::Table",
                "Properties": {
                    "AttributeDefinitions": [
                        {
                            "AttributeName": "id",
                            "AttributeType": "S"
                        }
                    ],
                    "KeySchema": [
                        {
                            "AttributeName": "id",
                            "KeyType": "HASH"
                        }
                    ],
                    "BillingMode": "PAY_PER_REQUEST"
                }
            },
            "TopicToFunctionConnectorWriteLambdaPermission": {
                "Type": "AWS::Lambda::Permission",
                "Metadata": {
                    "aws:sam:connectors": {
                        "TopicToFunctionConnector": {
                            "Source": {
                                "Type": "AWS::SNS::Topic"
                            },
                            "Destination": {
                                "Type": "AWS::Serverless::Function"
                            }
                        }
                    }
                },
                "Properties": {
                    "Action": "lambda:InvokeFunction",
                    "FunctionName": {
                        "Fn::GetAtt": [
                            "Function",
                            "Arn"
                        ]
                    },
                    "Principal": "sns.amazonaws.com",
                    "SourceArn": {
                        "Ref": "Topic"
                    }
                }
            },
            "FunctionToTableConnectorPolicy": {
                "Type": "AWS::IAM::ManagedPolicy",
                "Metadata": {
                    "aws:sam:connectors": {
                        "FunctionToTableConnector": {
                            "Source": {
                                "Type": "AWS::Serverless::Function"
                            },
                            "Destination": {
                                "Type": "AWS::Serverless::SimpleTable"
                            }
                        }
                    }
                },
                "Properties": {
                    "PolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Action": [
                                    "dynamodb:PutItem",
                                    "dynamodb:UpdateItem",
                                    "dynamodb:DeleteItem",
                                    "dynamodb:BatchWriteItem",
                                    "dynamodb:PartiQLDelete",
                                    "dynamodb:PartiQLInsert",
                                    "dynamodb:PartiQLUpdate"
                                ],
                                "Resource": [
                                    {
                                        "Fn::GetAtt": [
                                            "Table",
                                            "Arn"
                                        ]
                                    },
                                    {
                                        "Fn::Sub": [
                                            "${DestinationArn}/index/*",
                                            {
                                                "DestinationArn": {
                                                    "Fn::GetAtt": [
                                                        "Table",
                                                        "Arn"
                                                    ]
                                                }
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    "Roles": [
                        {
                            "Ref": "FunctionRole"
                        }
                    ]
                }
            }
        }
    }
```

There isn't a new resource there that LocalStack doesn't already support. If you have any issue with the utilization of this resource feel free to comment again. I'm closing this issue for now.
