### ISSUE TITLE
bug: Boostrap uses incorrect ARN partition, unable to bootstrap using GovCloud regions.

### ISSUE THREAD

**Issue by jpSimkins** [localstack/localstack#11108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am a new user evaluating LocalStack to be used for our dev team. I am currently in the Trial period using Pro as this is most likely what my team will require. Today is my first day using this and it's been a ride so far to say the least...

The current issue I am experiencing is due to the bootstrap procedure.

When I deploy my stack, it  gives the following response:

```
> cdklocal deploy --profile localstack


✨  Synthesis time: 2.61s


 ❌ Deployment failed: Error: PcnGov-Dev-Sand-CDK: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
    at Deployments.validateBootstrapStackVersion (/home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:454:12210)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Deployments.buildSingleAsset (/home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:454:10975)
    at async Object.buildAsset (/home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:454:197349)
    at async /home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:454:181491

PcnGov-Dev-Sand-CDK: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
 ELIFECYCLE  Command failed with exit code 1.
```

That makes sense, I like how you still need to bootstrap even for localstack.

So next I tried to bootstrap:

```
> cdklocal bootstrap --profile localstack

 ⏳  Bootstrapping environment aws://000000000000/us-gov-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
3:39:57 PM | UPDATE_FAILED        | AWS::IAM::Role          | LookupRole
Failed to delete resource with id LookupRole of type AWS::IAM::Role

3:39:57 PM | UPDATE_FAILED        | AWS::IAM::Role          | LookupRole
Resource handler returned message: "Failed to delete resource with id LookupRole of type AWS::IAM::Role" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None

 ❌  Environment aws://000000000000/us-gov-west-1 failed bootstrapping: Error: The stack named CDKToolkit failed to deploy: CREATE_FAILED (Resource handler returned message: "Failed to delete resource with id LookupRole of type AWS::IAM::Role" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None): Failed to delete resource with id LookupRole of type AWS::IAM::Role, Resource handler returned message: "Failed to delete resource with id LookupRole of type AWS::IAM::Role" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None
    at FullCloudFormationDeployment.monitorDeployment (/home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:451:10568)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:456:2329
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:456:2174)
    at async exec4 (/home/jpsimkins/Projects/PCN/pcn-monorepo-example/infrastructure/node_modules/.pnpm/aws-cdk@2.147.1/node_modules/aws-cdk/lib/index.js:509:54331)

The stack named CDKToolkit failed to deploy: CREATE_FAILED (Resource handler returned message: "Failed to delete resource with id LookupRole of type AWS::IAM::Role" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None): Failed to delete resource with id LookupRole of type AWS::IAM::Role, Resource handler returned message: "Failed to delete resource with id LookupRole of type AWS::IAM::Role" (RequestToken: 10c10335-276a-33d3-5c07-018b684c3d26, HandlerErrorCode: InvalidRequest)None
 ELIFECYCLE  Command failed with exit code 1.
```

This is where I am stuck.

What appears to be the issue, is that I am using `us-gov-west-1`, as this is a requirement. 

The issue with the bootstrap is that it is looking for a resource with the partition using `aws`. For GovCloud, the partition is `aws-us-gov`.

To confirm this is the case, I switched my region to use `us-west-1` and I was able to bootstrap with no issue.

### Expected Behavior

I expected the bootstrap to work for `us-gov-west-1` region using the proper ARN in the bootstrap process. This is not the case.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I have setup a AWS profile named `localstack`:

### AWS Profile Setup:

**config:**

```
[profile localstack]
region = us-gov-west-1
output = json
```

**credentials:**
```
[localstack]
aws_access_key_id = test
aws_secret_access_key = test
```

### Docker compose:
```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro:stable
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=account,acm-pca,acm,amplify,apigateway,apigatewaymanagementapi,apigatewayv2,appconfig,appconfigdata,application-autoscaling,appsync,athena,autoscaling,backup,batch,ce,cloudformation,cloudfront,cloudtrail,codecommit,cognito-identity,cognito-idp,dms,docdb,dynamodb,ec2,ecr,ecs,efs,eks,elasticache,elasticbeanstalk,elastictranscoder,elb,elbv2,emr-serverless,emr,events,fis,glacier,glue,identitystore,iot-data,iot,iotanalytics,iotwireless,kafka,kinesis,kinesisanalytics,kinesisanalyticsv2,kms,lakeformation,lambda,logs,managedblockchain,mediastore-data,mediastore,memorydb,mq,mwaa,neptune,opensearch,organizations,pinpoint,pipes,qldb-session,qldb,ram,rds-data,rds,redshift-data,redshift,route53,s3,sagemaker-runtime,sagemaker,serverlessrepo,servicediscovery,ses,sesv2,sqs,ssm,sso-admin,stepfunctions,textract,timestream-query,timestream-write,transfer,wafv2,xray,cloudwatch,config,dynamodbstreams,es,firehose,iam,resource-groups,resourcegroupstaggingapi,route53resolver,s3control,scheduler,secretsmanager,sns,sts,support,swf,transcribe
      - LOCALSTACK_AUTH_TOKEN="REDACTED"
      - AWS_ENDPOINT_URL=https://localhost.localstack.cloud:4566
      - AWS_DEFAULT_REGION=us-gov-west-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### package.json:

```json
{
  "name": "pcn-localstack-prototype",
  "private": true,
  "packageManager": "pnpm@9.4.0",
  "bin": {
    "cdk": "bin/index.js"
  },
  "scripts": {
    "//----[ Tools ]----//": "echo 'This is just a separator, nothing to see here' && exit 1",
    "bootstrap": "pnpm run clean:root && pnpm install",
    "build": "rm -rf ./dist && tsc",
    "test": "jest --coverage --colors",
    "//----[ LocalStack ]----//": "echo 'This is just a separator, nothing to see here' && exit 1",
    "localstack:start": "docker compose -f docker-compose.yaml up -d",
    "localstack:stop": "docker compose -f docker-compose.yaml down",
    "localstack:bootstrap": "cdklocal bootstrap -v --profile localstack",
    "localstack:deploy": "cdklocal deploy --profile localstack",
    "cdk:context:list": "cdk context",
    "//----[ Docs, Linting & Formatting ]----//": "echo 'This is just a separator, nothing to see here' && exit 1",
    "docs:generate": "typedoc ./lib/index.ts",
    "eslint:lint": "pnpm -r --if-present run eslint:lint",
    "eslint:lint-and-fix": "pnpm -r --if-present run eslint:lint-and-fix",
    "prettier:format": "pnpm -r --if-present run --stream prettier:format",
    "//----[ Clean Up ]----//": "echo 'This is just a separator, nothing to see here' && exit 1",
    "clean:root": "rm -rf node_modules",
    "clean:root:force": "rm -rf node_modules && rm -f package-lock.json",
    "//----[ Debug Details ]----//": "echo 'This is just a separator, nothing to see here' && exit 1",
    "cdk:version": "cdk --version",
    "cdklocal:version": "cdklocal --version",
    "tsc:version": "tsc --version",
    "github:report:env": "echo ' - **CDK CLI Version :** ' $(cdk --version) ; echo ' - **Module Version :** ' $(cdk --version | cut -f1 -d ' ') ; echo ' - **Node.js Version :** ' $(node --version) ; echo ' - **OS               :** ' $(uname -a) ; echo ' - **Language (Version):** Typescript ('$(tsc --version)')'"
  },
  "dependencies": {
    "aws-cdk-lib": "2.147.1",
    "constructs": "^10.3.0",
    "path": "^0.12.7",
    "source-map-support": "^0.5.21"
  },
  "devDependencies": {
    "@types/jest": "^29.5.12",
    "@types/lodash": "^4.17.5",
    "@types/node": "^20.14.9",
    "@typescript-eslint/parser": "^7.14.1",
    "aws-cdk": "2.147.1",
    "aws-cdk-local": "2.18.0",
    "dotenv-cli": "7.4.2",
    "eslint": "8.56.0",
    "eslint-config-prettier": "9.1.0",
    "eslint-plugin-import": "2.29.1",
    "eslint-plugin-jest": "28.6.0",
    "eslint-plugin-prettier": "5.1.3",
    "eslint-plugin-simple-import-sort": "12.1.0",
    "execa": "^9.3.0",
    "jest": "^29.7.0",
    "jest-extended": "^4.0.2",
    "jsii": "^5.4.24",
    "lint-staged": "^15.2.7",
    "lodash": "^4.17.21",
    "prettier": "^3.3.2",
    "rimraf": "^5.0.7",
    "ts-jest": "^29.1.5",
    "ts-node": "^10.9.2",
    "typedoc": "^0.26.2",
    "typescript": "5.5.2"
  },
  "lint-staged": {
    "*.ts": [
      "prettier --write"
    ]
  }
}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I use VS Code and click run on `localstack:bootstrap`. 
This runs:
```
cdklocal bootstrap -v --profile localstack
```

### Environment

```markdown
- OS: Linux Zeus 6.8.0-35-generic \#35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- LocalStack:
  LocalStack version: 3.5.0
  LocalStack Docker image sha: 1b8e5ca2e9cc456b923a4ee167bf80fd1c96d76684fb691a0009d14148bb019a
  LocalStack build date:
  LocalStack build git hash:

I am using the latest version as of today. The Desktop app should be able to give me these details...
```
