### ISSUE TITLE
Accessing s3 bucket on amazon cloud from lambda function fails with NoSuchBucket error

### ISSUE THREAD

**Issue by petr-pokorny-1** [localstack/localstack#11110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the following code outside of localstack, it downloads file content from the s3 bucket on aws cloud. When it runs in lambda in localstack, the code fails with `error: NoSuchBucket: The specified bucket does not exist`
The configuration for s3Client explicitly defines `endpoint: 'https://s3.amazonaws.com'` so it should reach to real aws s3 service.

```typescript
        endpoint: 'https://s3.amazonaws.com',
        region: 'us-east-1',
        logger: console,
        credentials: {
            accessKeyId: "<access key id>",
            secretAccessKey: "<secret>"
        }
    }

    const getObjectParams = {
        Bucket: '<bucket name>',
        Key: '<key>'
    }

    const s3 = new S3Client(s3Config)
    const response = await s3.send(new GetObjectCommand(getObjectParams))
    const content = await response.Body?.transformToString()
```

### Expected Behavior

The file should be downloaded. Instead, the following error occurs:

`error: NoSuchBucket: The specified bucket does not exist`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up with docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_CONTAINER_NAME:-localstack}"
    image: "localstack/localstack-pro:${LOCALSTACK_VERSION:-latest}"  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-0}
      - USE_SSL=${USE_SSL:-1}
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - ECS_REMOVE_CONTAINERS=${ECS_REMOVE_CONTAINERS:-0}
      - DISABLE_EVENTS=${DISABLE_EVENTS:-0} # disable usage tracking
      - DYNAMODB_SHARE_DB=${DYNAMODB_SHARE_DB:-1}
      - DISABLE_CORS_CHECKS=1
      - DOCDB_PROXY_CONTAINER=1
      - LAMBDA_DISABLE_AWS_ENDPOINT_URL=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/_localstack/health?reload"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  default:
    driver: bridge
```

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- LocalStack:
LocalStack version: 3.5.1.dev20240624022330
LocalStack build date: 2024-06-24
LocalStack build git hash: 51dd910
```

### Anything else?

I also tried [MinIO client](https://github.com/minio/minio-js), but getting the same result - it downloads file from s3 when it runs outside of localstack, but fails on NoSuchBucket error when running in the lambda in localstack.

```typescript
  const minioClient = new Client({
    endPoint: 's3.amazonaws.com',
    useSSL: true,
    accessKey: '...',
    secretKey: '...'
  })

  await minioClient.fGetObject('bucket name', 'key', '<filePath>')
```
