### ISSUE TITLE
bug: CloudFormation stack related tags missing from resource

### ISSUE THREAD

**Issue by jcollado** [localstack/localstack#11119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While reproducing #10768, I noticed that CloudFormation stack related tags are missing from the resource under test. In this case an EC2 security group. The tags that are missing are:
- `aws:cloudformation:logical-id`
- `aws:cloudformation:stack-id`
- `aws:cloudformation:stack-name`

### Expected Behavior

To behave in the same way as AWS CloudFormation, LocalStack ClouFormation should add the missing tags to all resources.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    bin/localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Given this CloudFormation template in `cfn.yaml` file:

```
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group
      Tags:
        - Key: key1
          Value: value1
        - Key: key2
          Value: value2
```

run:

```
awslocal cloudformation create-stack --stack-name sg --template-body "$(cat cfn.yaml)"
awslocal ec2 describe-security-groups
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack:
  LocalStack version: 3.5.1.dev
  LocalStack Docker image sha256:210fae65f0084375f70832454a40aa3e30bd96fa2b3d9604206ebc426c4637c3
  LocalStack build date: 2024-06-18
  LocalStack build git hash: 4858edd6b
```
