### ISSUE TITLE
bug: Cloudfront multiple cache behavior with PathPattern is not working as expected

### ISSUE THREAD

**Issue by rondinellimorais** [localstack/localstack#11200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to implement multiple cache behavior based on PathPattern but I'm not able to make it work on localstack

### Expected Behavior

Scenario 1: {CLOUDFRONT_URL}**/video1.txt** -> fetch data from `bucket1/video1.txt`
Scenario 2: {CLOUDFRONT_URL}/**public-assets/image003.txt** -> fetch data from `bucket2/public-assets/image003.txt`

**bucket1** => `app-tests-source-files-bucket-000000000000`
**bucket2** => `app-tests-other-source-files-bucket-000000000000`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack

    docker-compose up

```yaml
version: "3.1"

services:
  localstack:
    image: localstack/localstack-pro:3.5.0
    container_name: localstack-main
    networks:
      - lambda-network
    ports:
      - "4566-4597:4566-4597"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
      - "53:53"                # DNS config (required for Pro)
      - "53:53/udp"            # DNS config (required for Pro)
      - "443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - SERVICES=secretsmanager,cloudformation,events,dynamodb,sqs,ses,s3,cognito-idp,iam,sts,apigateway,apigatewayv2,lambda,cloudwatch,ecr,ecs,eks,cloudfront,acm,route53,route53resolver,stepfunctions,logs,ec2
      - DEBUG=1
      - LAMBDA_DOCKER_NETWORK=lambda-network
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=300
      - USE_LEGACY_PORTS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- }
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_APIGATEWAY=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${TMPDIR:-/var/lib/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  lambda-network:
    name: lambda-network
    driver: bridge
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```yaml
# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
    Description: Domain name for public CDN (e.i -> cdn.example.com)
    Default: cdnlocal.example.com

Outputs:
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-source-files-bucket-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    DependsOn:
      - SourceBucket
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: XPTO website 1

  SourceBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SourceBucket
      PolicyDocument:
        Id: xpto-policy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForCloudFrontPrivateContent
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject*
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SourceBucket
                - /*

  OtherSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-other-source-files-bucket-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  OtherCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    DependsOn:
      - OtherSourceBucket
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: XPTO website 2

  OtherSourceBucketBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OtherSourceBucket
      PolicyDocument:
        Id: xpto-policy
        Version: 2012-10-17
        Statement:
          - Sid: PolicyForCloudFrontPrivateContent
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OtherCloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: s3:GetObject*
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref OtherSourceBucket
                - /*

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: xpto-cachepolicy
        MinTTL: 1
        DefaultTTL: 60
        MaxTTL: 60
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none

  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: xpto-response-headers-policy
        CustomHeadersConfig:
          Items:
            - Header: Cache-Control
              Override: true
              Value: !Sub max-age=60

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      ValidationMethod: !Sub ${DomainName}.

  Distribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CachePolicy
      - ResponseHeadersPolicy
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_All
        HttpVersion: http2
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        Origins:
          - Id: xpto-website-1
            DomainName: !GetAtt SourceBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
          - Id: xpto-website-2
            DomainName: !GetAtt OtherSourceBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${OtherCloudFrontOriginAccessIdentity}
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: xpto-website-1
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: !Ref CachePolicy
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
        CacheBehaviors:
          - PathPattern: /public-assets/*
            Compress: true
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: xpto-website-2
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: !Ref CachePolicy
            ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: !Ref DomainName

  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - Distribution
    Properties:
      HostedZoneId: !Ref HostedZone
      Comment: DNS name for cloud front CDN
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # static hosted zone id to cloudfront
        DNSName: !GetAtt Distribution.DomainName
```

```
awslocal s3api put-object \
  --bucket app-tests-source-files-bucket-000000000000 \    
  --key video1.txt \
  --body /Users/rondinellimorais/Downloads/media001.txt
```
```
awslocal s3api put-object \
  --bucket app-tests-other-source-files-bucket-000000000000 \    
  --key public-assets/image003.txt \
  --body /Users/rondinellimorais/Downloads/image003.txt
```

Scenario 1 works and I can see this output in the logs:

URL: https://32629848.cloudfront.localhost.localstack.cloud/video1.txt

```log
localstack-main | 2024-07-13T14:33:00.269  INFO --- [et.reactor-1] l.s.cloudfront.provider    : Forwarding CloudFront invocation: GET https://app-tests-source-files-bucket-000000000000.s3.localhost.localstack.cloud/video1.txt, Host header app-tests-source-files-bucket-000000000000.s3.localhost.localstack.cloud
localstack-main | 2024-07-13T14:33:00.360  INFO --- [et.reactor-0] localstack.request.aws     : AWS s3.GetObject => 200
localstack-main | 2024-07-13T14:33:00.365 DEBUG --- [et.reactor-1] l.s.cloudfront.provider    : Response status code 200 for https://app-tests-source-files-bucket-000000000000.s3.localhost.localstack.cloud/video1.txt
localstack-main | 2024-07-13T14:33:00.369  INFO --- [et.reactor-1] localstack.request.http    : GET /video1.txt => 200
```

But scenario 2 does not.

URL: https://32629848.cloudfront.localhost.localstack.cloud/public-assets/image003.txt

```log
localstack-main | 2024-07-13T14:33:59.948  INFO --- [et.reactor-0] l.s.cloudfront.provider    : Forwarding CloudFront invocation: GET https://app-tests-source-files-bucket-000000000000.s3.localhost.localstack.cloud/public-assets/image003.txt, Host header app-tests-source-files-bucket-000000000000.s3.localhost.localstack.cloud
localstack-main | 2024-07-13T14:34:00.153  INFO --- [et.reactor-1] localstack.request.aws     : AWS s3.GetObject => 404 (NoSuchKey)
localstack-main | 2024-07-13T14:34:00.156 DEBUG --- [et.reactor-0] l.s.cloudfront.provider    : Response status code 404 for https://app-tests-source-files-bucket-000000000000.s3.localhost.localstack.cloud/public-assets/image003.txt
localstack-main | 2024-07-13T14:34:00.161  INFO --- [et.reactor-0] localstack.request.http    : GET /public-assets/image003.txt => 404
```

The logs show that it is trying to fetch both files from the same bucket, when using `PathPattern` /public-assets/* the redirect to the second bucket does not occur.

Is there any additional configuration I have to do? The above scenarios work perfectly in the AWS environment.

### Environment

```markdown
- OS: macOs Big Sur 11.7.10
- LocalStack:
  LocalStack version: 3.5.1.dev20240613112149
  LocalStack Docker image sha: sha256:c0d346a4b726f167e16451d01a217dfe17f07994ac30f7ab61b57aa321b3e4d6
  LocalStack build date: 2024-06-13
  LocalStack build git hash: 5eb9042
```
