### ISSUE TITLE
bug: AttributeError: 'NoneType' object has no attribute 'listeners'

### ISSUE THREAD

**Issue by mohamedhafizelhaj** [localstack/localstack#11223]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The setup is simple: it is a 3-tier web application, a static website hosted on an S3 bucket located behind a CloudFront distribution is my web tier, then we have an API Gateway that the web-tier use to connect to the application tier, the API Gateway is connected to my VPC, where the application tier resides via a VPC link, which forwards the requests to a network load balancer, which in turn forwards the request to the EC2 instances in an ASG, the EC2 have a simple PHP script running to test the flow, and a security group allowing inbound traffic for the NLB to reach it. When trying to call the API, I get {"error": "Unexpected exception", "message": "'NoneType' object has no attribute 'listeners'", "type": "AttributeError"} which seems like a python error, although I have no python scripts running throughout my stack, which led me to think it is an internal bug, I have make sure that all components: the NLB, the listener, the target group, the VPC link are all deployed successfully as shown by querying them via the CLI.

```
2024-07-17T20:49:49.132 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/handlers.py", line 27, in __call__
    router_response = self.router.dispatch(context.request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/router.py", line 381, in dispatch
    return self.dispatcher(request, handler, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/dispatcher.py", line 72, in _dispatch
    result = endpoint(request, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_ext/services/elb/routing.py.enc", line 104, in forward_elb_invocation
    for A in E.listeners.values():
             ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'listeners'

```

### Expected Behavior

The call to the API succeeds, which will forward it to the NLB through the VPC link, which in turn will forward it to the EC2 instances in the ASG.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for the Three-Tier-Web-Application project

Parameters:
  FrontEndBucketName:
    Type: String
    Description: The name of the S3 bucket for the front-end website.
    Default: frontend

Resources:

  ######################################
  #             CloudFront             #
  ######################################

  CDNOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: CDNOriginAccessControleForS3
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CachingOptimizedCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 1
        Name: CachingOptimized
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

  CDNDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt S3FrontEndBucket.RegionalDomainName
            Id: MainFrontEndBucket
            OriginAccessControlId: !Ref CDNOriginAccessControl
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          CachePolicyId: !Ref CachingOptimizedCachePolicy
          Compress: true
          TargetOriginId: MainFrontEndBucket
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  ######################################
  #         S3-hosted website          #
  ######################################

  S3FrontEndBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref FrontEndBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  FrontEndBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3FrontEndBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Resource: !Join
              - ''
              - - !GetAtt S3FrontEndBucket.Arn
                - /*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CDNDistribution}

  ######################################
  #           VPC and subnets          #
  ######################################

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  VPCPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      VpcId: !Ref VPC

  VPCPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      VpcId: !Ref VPC

  VPCPrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      VpcId: !Ref VPC

  VPCPrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: 10.0.4.0/24
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      VpcId: !Ref VPC

  ######################################
  #             API Gateway            #
  ######################################

  VPCLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: VPCLink
      SubnetIds:
        - !Ref VPCPrivateSubnet1
        - !Ref VPCPrivateSubnet2
      Tags:
        Project: Three-Tier-Web-Application

  API:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: API
      ProtocolType: HTTP
      Tags:
        Project: Three-Tier-Web-Application

  APIIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref API
      ConnectionId: !Ref VPCLink
      ConnectionType: VPC_LINK
      IntegrationType: HTTP_PROXY
      IntegrationMethod: ANY
      IntegrationUri: !Sub http://${NetworkLoadBalancer.DNSName}
      PayloadFormatVersion: '1.0'

  APIRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref API
      AuthorizationType: NONE
      RouteKey: ANY /{proxy+}
      Target: !Join
        - /
        - - integrations
          - !Ref APIIntegration

  ######################################
  #       Network Load Balancer        #
  ######################################

  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the NLB
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      VpcId: !Ref VPC

  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: NetworkLoadBalancer
      Scheme: internal
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Subnets:
        - !Ref VPCPrivateSubnet1
        - !Ref VPCPrivateSubnet2
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      Type: network

  NetworkLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref NetworkLoadBalancerTargetGroup
          Type: forward
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 80
      Protocol: TCP

  NetworkLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: NetworkLoadBalancerTargetGroup
      Port: 80
      Protocol: TCP
      HealthCheckPort: '80'
      HealthCheckProtocol: TCP
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      TargetType: instance
      VpcId: !Ref VPC

  ######################################
  #      EC2 instances in an ASG       #
  ######################################

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies: 
        - PolicyName: EC2AuroraAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds-db:connect
                Resource:
                  - !Ref AuroraCluster
      Tags: 
        - Key: Project
          Value: Three-Tier-Web-Application

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EC2 instances
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ELBSecurityGroup
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
      VpcId: !Ref VPC

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-04e8b3e527208c8cf
        InstanceType: t2.micro
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Project
                Value: Three-Tier-Web-Application

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: EC2AutoScalingGroup
      VPCZoneIdentifier:
        - !Ref VPCPrivateSubnet1
        - !Ref VPCPrivateSubnet2
      DesiredCapacity: '2'
      LaunchTemplate:
        LaunchTemplateId: !Ref EC2LaunchTemplate
        Version: !GetAtt EC2LaunchTemplate.LatestVersionNumber
      MaxSize: '3'
      MinSize: '1'
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application
          PropagateAtLaunch: true
      TargetGroupARNs:
        - !Ref NetworkLoadBalancerTargetGroup

  ######################################
  #        Amazon Aurora Cluster       #
  ######################################

  AuroraClusterMasterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 18
      Name: AuroraClusterMasterSecret
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  AuroraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Aurora cluster
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  AuroraClusterSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Aurora cluster subnet group
      DBSubnetGroupName: AuroraClusterSubnetGroup
      SubnetIds:
        - !Ref VPCPrivateSubnet3
        - !Ref VPCPrivateSubnet4
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: 8.0.mysql_aurora.3.03.0
      DBClusterIdentifier: AuroraCluster
      DBSubnetGroupName: !Ref AuroraClusterSubnetGroup
      VpcSecurityGroupIds:
        - !Ref AuroraSecurityGroup
      MasterUserSecret:
        SecretArn: !Ref AuroraClusterMasterSecret
      StorageEncrypted: true
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  AuroraPrimary:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: AuroraPrimary
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

  AuroraReadReplica:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceIdentifier: AuroraReadReplica
      Tags:
        - Key: Project
          Value: Three-Tier-Web-Application

Outputs:
  S3BucketName:
    Description: Name of the S3 bucket for the front-end website.
    Value: !Ref S3FrontEndBucket

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !Join
      - ''
      - - https://
        - !GetAtt CDNDistribution.DomainName

  APIEndpoint:
    Description: API Endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref API
        - .execute-api
        - .localhost.localstack.cloud:4566
```

### Environment

```markdown
- OS: Windows 11 Pro
- LocalStack:
  LocalStack version: 3.5.0
  LocalStack Docker image sha: sha256:2bdc8cb09d2a9c149757b62a990d101d953285ad116d5bec73f6cd870475ac43
  LocalStack build date: 2024-06-21T04:37:48.702715479Z
  LocalStack build git hash: -
```
