### ISSUE TITLE
bug: Kinesis event source mapping with onFailure destination not working when ReportBatchItemFailures is enabled

### ISSUE THREAD

**Issue by Cfuzz** [localstack/localstack#11262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Kinesis event source mapping with an SQS queue as onFailure destination and ReportBatchItemFailures set in the FunctionResponseTypes. I see the following response from the lambda in the locastack logs:

`POST /_localstack_lambda/913e52d7680becfcc0ff2876c9cfaeda/invocations/5084f4b4-5807-4466-8410-a720c71df70b/response => 202; Request(b'{"batchItemFailures":[{"itemIdentifier":"49654227999190512994328020514486703479574350604747669506"}]}', headers={'Host': '172.21.0.2:4566', 'User-Agent': 'Go-http-client/1.1', 'Content-Length': '101', 'Content-Type': 'application/json', 'Accept-Encoding': 'gzip'}); Response(b'', headers={'Content-Type': 'text/plain; charset=utf-8'})`

However the DLQ is empty.

Note: If I remove the batch item failures config and throw exception from the lambda instead, I can see a message in the DLQ so the problem is specific to the case when batch item failures are reported.

### Expected Behavior

I should see a failure message in the DLQ that has been configured as the onFailure destination.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1.  Start localstack
2. Deploy a lambda, create a kinesis stream, a dlq and set up an event source mapping. I have a cloudformation script for this. The event configuration of the serverless::function is as follows:
```
Events:
  KinesisEvent:
    Type: Kinesis
    Properties:
      Stream: 
        Fn::Sub: arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/my-stream
      StartingPosition: TRIM_HORIZON
      BatchSize: 100
      MaximumBatchingWindowInSeconds: 10
      MaximumRetryAttempts: 0
      BisectBatchOnFunctionError: false
      FunctionResponseTypes: 
          - ReportBatchItemFailures
      DestinationConfig: 
        OnFailure: 
          Destination: 
            Fn::GetAtt:
              - MyDeadLetterQueue
              - Arn 
      Enabled: true
```
3. Publish a message known to cause the lambda to return a failure to Kinesis using the aws cli:
`aws kinesis put-record --stream-name my-stream --data "<base64 encoded message>" --partition-key 1`
4. Since the lambda returns a batch failure response, a failure message should go to the configured DLQ.

### Environment

```markdown
- OS:Windows 11 Enterprise build 22631.3737
- LocalStack version: 3.5.1.dev
- LocalStack build date: 2024-07-24
- LocalStack build git hash: fcc74f244
```
