### ISSUE TITLE
bug: Cloudformation validating ArchivePolicy property type from AWS::SNS::Topic wrong

### ISSUE THREAD

**Issue by pjferreira** [localstack/localstack#11289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to create and deploy a SNS topic via CloudFormation where we configure `ArchivePolicy` property values (i.e. set `MessageRetentionPeriod`, see **Steps to Reproduce** for more details) it fails validation because it is expecting a string rather than a json like value (or equivalent in yaml).

Here is an example of the error when using LocalStack via the latest Docker image:
```
WARN --- [-functhread5] l.s.c.engine.entities      : CFn resource failed to deploy: SNS (Parameter validation failed:; Invalid type for parameter Attributes.ArchivePolicy, value: {'MessageRetentionPeriod': 30}, type: <class 'dict'>, valid types: <class 'str'>)
```

This works as expected when deploying to AWS.

### Expected Behavior

I would expect `ArchivePolicy` property to allow json like values as per [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Using the following files:

`template-example.yaml`
```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  SNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: example-topic
      FifoTopic: true
      ArchivePolicy:
        MessageRetentionPeriod: 30
```

`init-localstack.sh`
```
#!/bin/bash

set -e

awslocal cloudformation deploy \
    --template-file /template-example.yaml \
    --stack-name example-sns-stack \
    --region=eu-west-1
```

`docker-compose.yml`
```
version: '3.9'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: cloudformation,sns
      LS_LOG: info
    volumes:
      - "./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh"
      - "./template-example.yaml:/template-example.yaml"
```
And running `docker compose up localstack` you should see the error mentioned above.

### Environment

```markdown
- OS: macOS Sonoma 14.3.1
- LocalStack:
LocalStack version: 3.6.1.dev (latest)
LocalStack build date: 2024-07-30
LocalStack build git hash: 85b16b2d8
```
