### ISSUE TITLE
bug: MFA configuration in Cognito user pool not working

### ISSUE THREAD

**Issue by TeemuLeino** [localstack/localstack#11292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MFA Configuration value in Cognito user pool always remains `OFF`, even though it's defined `ON` in Cloudformation template or changed with `awslocal cognito-idp set-user-pool-mfa-config` command.

### Expected Behavior

MFA Configuration value in Cognito user pool should follow the value defined in Cloudfromation stack template. Also it should be changeable with `awslocal cognito-idp set-user-pool-mfa-config` command.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Localstack pro container started with docker compose.

Cognito user pool created with `serverless` and `localstack-serverless` plugin, by having this in the `resources` section:
```
Resources:
    MyUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: my-test-user-pool
        MfaConfiguration: ON
        EnabledMfas:
          - SOFTWARE_TOKEN_MFA
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: True
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 12
            RequireLowercase: True
            RequireNumbers: True
            RequireSymbols: True
            RequireUppercase: True
            TemporaryPasswordValidityDays: 7
        UsernameConfiguration:
          CaseSensitive: False
        EmailConfiguration:
          EmailSendingAccount: DEVELOPER
          From: Testing <no-reply@example.org>
          ReplyToEmailAddress: 'no-reply@example.org'
        Schema:
          - Name: email
            Required: True
            Mutable: True
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate:
            - email
    MyUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref MyUserPool
        GenerateSecret: False
        PreventUserExistenceErrors: ENABLED
        AccessTokenValidity: 15
        IdTokenValidity: 15
        RefreshTokenValidity: 12
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: hours
```

After deploying the stack with `sls deploy` command, user pool is created but with `MfaConfiguration: OFF` configuration.

If tried to change with
```
awslocal cognito-idp set-user-pool-mfa-config --user-pool-id <USER_POOL_ID> --software-token-mfa-configuration Enabled=true --mfa-configuration ON
```

the configuration still remains as `MfaConfiguration: OFF`.

### Environment

```markdown
- OS: MacOS Sonoma 14.5
- LocalStack:
  LocalStack version: 3.5.1.dev20240625022401
  LocalStack Docker image sha: sha256:3513a6de03d8f09ca5f4e08e859c381df52cfd617795619c8ceb75b73f951dc7
  LocalStack build date: 2024-06-25
  LocalStack build git hash: 8d22880
```
