### ISSUE TITLE
bug: SES command create-configuration-set-event-destination does not take into account MatchingEventTypes value in event-destination option

### ISSUE THREAD

**Issue by adel1ne** [localstack/localstack#11324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to limit the number of EventTypes when creating a create-configuration-set-event-destination in SES. However, when sending an email, I receive two notifications with eventType: 'send' and eventType: 'delivery', regardless of the values in MatchingEventTypes.

### Expected Behavior

When creating a create-configuration-set-event-destination in SES and specifying only the value 'delivery' in MatchingEventTypes, there should only be one notification sent to the queue with eventType=delivery.

### How are you starting LocalStack?

With a docker-compose file

#### I started localstack with docker-compose:
```
version: "3.9"

volumes:
  localstack-data:

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:3.1.0

    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
```

##### verify domain identity
`awslocal ses verify-domain-identity --domain local.test.com --region us-west-2`

##### create queue
`sqs create-queue --queue-name mail-incoming-queue --region us-west-2`

##### create SNS topic for SES events
`sns create-topic --name mail-topic --region us-west-2`

##### subscribe queue to topic
`sns subscribe --region us-west-2 --topic-arn arn:aws:sns:us-west-2:000000000000:mail-topic --protocol sqs --notification-endpoint arn:aws:sqs:us-west-2:000000000000:mail-incoming-queue`

##### create SES config set
`awslocal ses create-configuration-set --configuration-set "{\"Name\":\"ses_config_set\"}" --region us-west-2`

##### create event destination
`awslocal ses create-configuration-set-event-destination --configuration-set-name ses_config_set --event-destination '{"Name":"some_name","Enabled":true,"MatchingEventTypes":["delivery"],"SNSDestination":{"TopicARN":"arn:aws:sns:us-west-2:000000000000:mail-topic"}}' --region us-west-2`

##### send email via ses with created set
`awslocal ses  send-email --destination '{"ToAddresses":["din@local.test.com"]}' --message '{"Subject":{"Data":"Test Link"},"Body":{"Html":{"Data":"<a href=\"nba.com\">Link test</a>"}}}' --configuration-set-name ses_config_set --from 'sam@local.test.com' --region us-west-2`

In the queue, I see two messages. When I try to retrieve them using the command (executing it twice):
`awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/mail-incoming-queue --region us-west-2`
I receive two messages with `eventType = send` and `eventType = delivery`.

### Environment

```markdown
- OS: Windows 10
  LocalStack version: 3.6.1.dev
  LocalStack Docker image sha: sha256:3cdbde21220c452e346e3b5713890e79c9a2cca84bd3095f2a60abf83dab61d1
```
