### ISSUE TITLE
Installation via Helm not working

### ISSUE THREAD

**Issue by SledgeHammer01** [localstack/localstack#11339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running on Windows 11 Pro x64, Docker+Kubernetes on a WSL2 back end. I am 100% that earlier this year, my installation process was working since my Helm 0.6.5 values are pinned to Localstack 2.3.2.

When I try to apply my terraform, I get `exception during call chain: Installation of kinesis-local failed`.  I'm positive this was working several months ago, so not sure what happened. If I remove the Kinesis part of my terraform, the rest (DynamoDB, S3 and Lambda) seems to work.

```
image:
  tag: 2.3.2
ingress:
  enabled: true
  hosts:
    - host: localstack.xxx.com
      paths:
        - path: /
          pathType: Prefix
mountDind:
  enabled: 'true'
persistence:
  enabled: 'true'
  existingClaim: localstack
service:
  type: ClusterIP
volumeMounts:
  - mountPath: /etc/localstack/init
    name: localstack-scripts
  - mountPath: /etc/localstack/state
    name: localstack-state
volumes:
  - hostPath:
      path: /run/desktop/mnt/host/c/users/xxx/.localstack/scripts
    name: localstack-scripts
  - hostPath:
      path: /run/desktop/mnt/host/c/users/xxx/.localstack/state
    name: localstack-state

```

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows 11 Pro x64
      Docker 4.33.1 w/ Kubernetes enabled
      Installation via Helm
- LocalStack:
  LocalStack version:
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```
