### ISSUE TITLE
bug: Unable to use Amazon Bedrock on lambda function.

### ISSUE THREAD

**Issue by tori-takashi** [localstack/localstack#11364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to use Amazon Bedrock on live AWS environment from lambda but not working.

docker-compose.yml

```yaml
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-pro # required for Pro
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (Pro)
    environment:
      - SERVICES=s3,sqs,lambda,iam,ecr,cloudformation,cloudwatch,logs,kms
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - MAIN_CONTAINER_NAME=localstack
      - CFN_STRING_REPLACEMENT_DENY_LIST=https://bedrock-runtime.ap-northeast-1.amazonaws.com
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Lambda environment variables from CloudFunction yaml

```yaml
  Function1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Function1
      MemorySize: 3008
      Role: !Ref RoleArn
      Timeout: 60
      PackageType: Image
      Architectures:
        - x86_64
      Code:
        ImageUri: !Sub ${Repo1Uri}:latest
      ReservedConcurrentExecutions: 5
      LoggingConfig:
        LogGroup: !Ref LogGroup1
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO
      Environment:
        Variables:
          AWS_LLM_ENDPOINT_URL: https://bedrock-runtime.ap-northeast-1.amazonaws.com
          AWS_ACCESS_KEY_ID_LLM: !Ref AWS_ACCESS_KEY_ID_LLM
          AWS_SECRET_ACCESS_KEY_LLM: !Ref AWS_SECRET_ACCESS_KEY_LLM
          REGION_NAME_LLM: !Ref REGION_NAME_LLM
``` 

```
boto3==1.34.162
```

```Dockerfile
FROM public.ecr.aws/lambda/python:3.12

# https://qiita.com/eiji-noguchi/items/f44e7c7369d0a7ffe681
# https://github.com/aws/aws-lambda-base-images/issues/128#issuecomment-1847483997
RUN dnf install -y tar gzip git gcc

COPY app.py ${LAMBDA_TASK_ROOT}
COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt
CMD [ "app.handler" ]
```

Partial lambda handler codes.

```python
import boto3

def handler(event: dict, context):
  aws_access_key_id = os.getenv('AWS_ACCESS_KEY_ID') if os.getenv(
      'AWS_ACCESS_KEY_ID') else 'dummy'
  aws_secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY') if os.getenv(
      'AWS_SECRET_ACCESS_KEY') else 'dummy'
  region_name = os.getenv('REGION_NAME') if os.getenv(
      'REGION_NAME') else 'us-east-1'
  model_id = os.getenv('MODEL_ID') if os.getenv(
      'MODEL_ID') else 'anthropic.claude-3-5-sonnet-20240620-v1:0'

  bucket_name = os.getenv('BUCKET_NAME')
  sqs_queue_url = os.getenv('SQS_QUEUE_URL')

  session = Session(aws_access_key_id=aws_access_key_id,
                    aws_secret_access_key=aws_secret_access_key,
                    region_name=region_name
                    )

  aws_access_key_id_llm = os.getenv('AWS_ACCESS_KEY_ID_LLM') if os.getenv(
      'AWS_ACCESS_KEY_ID_LLM') else 'dummy'
  aws_secret_access_key_llm = os.getenv('AWS_SECRET_ACCESS_KEY_LLM') if os.getenv(
      'AWS_SECRET_ACCESS_KEY_LLM') else 'dummy'
  region_name_llm = os.getenv('REGION_NAME_LLM') if os.getenv(
      'REGION_NAME_LLM') else 'ap-northeast-1'
  session_llm = Session(aws_access_key_id=aws_access_key_id_llm,
                        aws_secret_access_key=aws_secret_access_key_llm,
                        region_name=region_name_llm
                        )

  s3 = session.client(service_name='s3',)
  sqs = session.client(service_name='sqs')
  llm = session_llm.client(service_name='bedrock-runtime',
                           endpoint_url=os.getenv('AWS_LLM_ENDPOINT_URL'),
                           verify=False
                           )

  response = llm.invoke_model(
              body=body,
              modelId=modelId,
              accept=accept,
              contentType=contentType
        )
```

Cloudwatch Logs

```
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. 
However, in rare cases, a Lambda runtime update can cause unexpected function behavior. 
For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. 
To determine if the runtime has been updated, check the runtime version in the INIT_START log entry.

If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. 
For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html 

[ERROR] ClientError: An error occurred (InternalFailure) when calling the InvokeModel operation: API for service 'bedrock-runtime' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information 

Traceback (most recent call last):   
File "/var/task/app.py", line 231, in figure_extractor_handler generate_text()   
File "/var/task/app.py", line 144, in generate_text   title=self.generate_text_from_llm(),   
File "/var/task/app.py", line 183, in generate_text_from_llm     response = llm.invoke_model(   
File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call     return self._make_api_call(operation_name, kwargs)   
File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 1009, in _make_api_call     raise error_class(parsed_response, operation_name)
```

### Expected Behavior

Enable to switch boto3 for localstack or live.

The best one is just enable to use Bedrock.  

Or

1. live key environment variable name settings on docker-compose.yml environment variables

```yaml
    environment:
      - SERVICES=s3,sqs,lambda,iam,ecr,cloudformation,cloudwatch,logs,kms
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN} # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - MAIN_CONTAINER_NAME=localstack
      - LIVE_ACCESS_KEY_ID_ENV_NAME=AWS_ACCESS_KEY_ID_LLM
```

2. set live key on CloudFormation Environment variables with LIVE_ACCESS_KEY_ID name.

```yaml
      Environment:
        Variables:
          AWS_LLM_ENDPOINT_URL: https://bedrock-runtime.ap-northeast-1.amazonaws.com
          AWS_ACCESS_KEY_ID_LLM: !Ref AWS_ACCESS_KEY_ID_LLM
          AWS_SECRET_ACCESS_KEY_LLM: !Ref AWS_SECRET_ACCESS_KEY_LLM
          REGION_NAME_LLM: !Ref REGION_NAME_LLM
```

3. then use live environment

```python
  aws_access_key_id_llm = os.getenv('AWS_ACCESS_KEY_ID_LLM') if os.getenv(
      'AWS_ACCESS_KEY_ID_LLM') else 'dummy'
  aws_secret_access_key_llm = os.getenv('AWS_SECRET_ACCESS_KEY_LLM') if os.getenv(
      'AWS_SECRET_ACCESS_KEY_LLM') else 'dummy'
  region_name_llm = os.getenv('REGION_NAME_LLM') if os.getenv(
      'REGION_NAME_LLM') else 'ap-northeast-1'

  session_llm = Session(aws_access_key_id=aws_access_key_id_llm,
                        aws_secret_access_key=aws_secret_access_key_llm,
                        region_name=region_name_llm
                        )
  llm = session_llm.client(service_name='bedrock-runtime')
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal lambda invoke --function-name lambda1 outfile

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack: LocalStack Pro
  LocalStack version: v3.6.0
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```
