### ISSUE TITLE
bug: Unable to create AWS::Serverless::Function via Cloud Formation Template

### ISSUE THREAD

**Issue by Sutty100** [localstack/localstack#11362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to deploy a Lambda function via Cloud Formation the stack ends up with the state CREATE_FAILED and the Stack status reason is:
> Unable to resolve Ref for resource "ServerlessDeploymentApplication" (yet)

### Expected Behavior

The Cloud Formation Stack is successfully deployed and a Lambda function is created

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Using the Test Containers Local Stack Java Library

```
        localStackContainer = new LocalStackContainer(DockerImageName.parse("localstack/localstack").withTag("3.6.0"))
                .withServices(SQS, CLOUDFORMATION, DYNAMODB, LAMBDA, API_GATEWAY, S3, IAM, CLOUDWATCHLOGS);
        localStackContainer.start(); 
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Cloud Formation file attempting to be deployed is

The Cloud Formation file looks like this

```
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for spring-lambda Lambda Function.
Parameters:
  Service:
    Type: String
  Env:
    Type: String
  CodeBucket:
    Type: String
  CodeFile:
    Type: String



Resources:
  Javafunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Service}-${Env}"
      AutoPublishAlias: LIVE
      DeploymentPreference:
        Type: AllAtOnce
      Handler: com.foo.bar.poc.lambda.snapstart.SnapstartStreamLambdaHandler::handleRequest
      Runtime: java21
      Timeout: 60
      MemorySize: 1024
      Description: !Ref CodeFile
      Tracing: Active
      CodeUri:
        Bucket: !Ref CodeBucket
        Key: !Ref CodeFile
      Role: arn:aws:iam::000000000000:role/spring-lambda-mock-lambda-role
      Environment:
        Variables:
          ENV: !Sub "${Env}"
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
          SPRING_PROFILES_ACTIVE: humanReadableLogs

  SimpleDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: simple-dynamo
```

Using the Java AWS SDK V2 this is then attempted to be deployed

```
        var cfnClient = CloudFormationClient.builder()
                .region(Region.EU_WEST_1)
                .endpointOverride(localStackContainer.getEndpointOverride(CLOUDFORMATION))
                .build();

            cfnClient.createStack(builder -> builder.stackName("mock-spring-lambda")
                    .templateBody(cfnTemplate)
                    .capabilities(Capability.CAPABILITY_AUTO_EXPAND)
                    .parameters(List.of(Parameter.builder().parameterKey("Service").parameterValue("spring-lambda").build(),
                            Parameter.builder().parameterKey("Env").parameterValue("mock").build(),
                            Parameter.builder().parameterKey("Service").parameterValue("spring-lambda").build(),
                            Parameter.builder().parameterKey("CodeBucket").parameterValue("code-bucket").build(),
                            Parameter.builder().parameterKey("CodeFile").parameterValue("code.zip").build())));

```

The S3 bucket containing the Zip has already been successfully created and I have validated via the AWS CLI the contents of the file.

### Environment

```markdown
- OS: OS X 12.7.5
- LocalStack:
  LocalStack version: 3.6.0
```
