### ISSUE TITLE
bug: StartupScript runs twice with HELM deployment

### ISSUE THREAD

**Issue by mosie7** [localstack/localstack#11430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am deploying a localstack container using helm with `enableStartupScripts: true` However the script I have put in the `startupScriptContent:` runs twice.

```
startupScriptContent: |
  #!/bin/bash

  echo "Hello World"
  exit 0
```

### Expected Behavior

I expect that the script only runs once 

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

Steps 
1. Create a values yaml (see below for my example)
2. Deploy localstack using helm command like below 

`helm upgrade --install --values=./localstack.values.yaml --namespace user test localstack/localstack`

```
image:
  repository: localstack/localstack
  tag: latest
  pullPolicy: Always

extraEnvVars:
  - name: SERVICES
    value: "sqs,s3,sns"
  - name: SQS_ENDPOINT_STRATEGY
    value: "path"

service:
  type: ClusterIP
  ports:
    - name: http
      port: 4566
      targetPort: 4566

podAnnotations:
  sidecar.istio.io/inject: "false"

enableStartupScripts: true

startupScriptContent: |
  #!/bin/bash

  echo "Hello World"
  exit 0
```

### Environment

```markdown
Mac OS: 14.4.1 (23E224
LocalStack version: 3.7.0
LocalStack build date: 2024-08-29
LocalStack build git hash: 6aa750570
```

### Anything else?

POD LOGS 

```
LocalStack version: 3.7.0
LocalStack build date: 2024-08-29
LocalStack build git hash: 6aa750570

Hello World
Hello World
Ready.
```
