### ISSUE TITLE
bug: Issue with Creating DynamoDB Table on LocalStack

### ISSUE THREAD

**Issue by MichaelHarden** [localstack/localstack#11467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I encountered an issue while using Crossplane to create a DynamoDB table on LocalStack. The process fails with the following error message, whereas it works successfully when applied directly to AWS.

Error Message
```
message: |-
  observe failed: cannot run refresh: refresh failed: Cannot index a set value: Block type "global_secondary_index" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
  Cannot index a set value: Block type "global_secondary_index" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
  Cannot index a set value: Block type "global_secondary_index" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
  Cannot index a set value: Block type "global_secondary_index" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
reason: ReconcileError
status: "False"
type: Synced
```

### Expected Behavior

The DynamoDB table should be created successfully in LocalStack, just like when applied to AWS.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

using the helm release to install onto a k3d cluster with mage

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

apply the following yaml onto a k3d cluster with crossplane installed with dynamodb provider and local stack

```
apiVersion: dynamodb.aws.upbound.io/v1beta1
kind: Table
metadata:
  name: gwcp-59316-cannot-index-set-value
spec:
  deletionPolicy: Delete
  forProvider:
    attribute:
    - name: UserId
      type: S
    - name: GameTitle
      type: S
    - name: IsTenant
      type: S
    - name: TenantClusterGSI-SK
      type: S
    - name: TopScore
      type: "N"
    billingMode: PROVISIONED
    deletionProtectionEnabled: false
    globalSecondaryIndex:
    - hashKey: GameTitle
      name: GameTitleIndex
      nonKeyAttributes:
      - UserId
      projectionType: INCLUDE
      rangeKey: TopScore
    - hashKey: IsTenant
      name: TenantClusterGSI
      projectionType: ALL
      rangeKey: TenantClusterGSI-SK
    hashKey: UserId
    pointInTimeRecovery:
    - enabled: true
    region: us-west-2
    serverSideEncryption:
    - enabled: false
    streamEnabled: false
  initProvider:
    globalSecondaryIndex:
    - hashKey: GameTitle
      name: GameTitleIndex
      nonKeyAttributes:
      - UserId
      projectionType: INCLUDE
      rangeKey: TopScore
      readCapacity: 4
      writeCapacity: 6
    - hashKey: IsTenant
      name: TenantClusterGSI
      projectionType: ALL
      rangeKey: TenantClusterGSI-SK
      readCapacity: 2
      writeCapacity: 3
    readCapacity: 3
    writeCapacity: 4
  managementPolicies:
  - Create
  - Update
  - Delete
  - Observe
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: gwcp-59316-cannot-index-set-value-5nxff
    namespace: crossplane-system
```

### Environment

```markdown
- OS: linux docker image golang 1.23-bookworm
- LocalStack: helm release v0.6.16
  LocalStack version: v3.7.1
```
