### ISSUE TITLE
bug: invalid region doesn't return error

### ISSUE THREAD

**Issue by notdodo** [localstack/localstack#11519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. create a lambda on eu-west-1
2. create a lambda on us-east-1
3. using awslocal run `awslocal lambda list-functions --region eu-west-1`: return correctly the first lambda
4. using awslocal run `awslocal lambda list-functions --region us-east-1`: return correctly the second lambda
5. using awslocal run `awslocal lambda list-functions --region asodifj`: return always the second lambda; even for other regions not enabled

Same output without using awslocal but the standard awscli

### Expected Behavior

Return an error for invalid/non-existing regions

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - EAGER_SERVICE_LOADING=1
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. using awslocal run `awslocal lambda list-functions --region eu-west-1`: return correctly the first lambda
2. using awslocal run `awslocal lambda list-functions --region us-east-1`: return correctly the second lambda
3. using awslocal run `awslocal lambda list-functions --region asodifj`: return always the second lambda; even for other regions not enabled

### Environment

```markdown
- OS: Mac, Sonoma
- LocalStack:
  LocalStack version: latest
  LocalStack Docker image sha:
  LocalStack build date:
  LocalStack build git hash:
```
