### ISSUE TITLE
bug: SNS Topic does not respect Content-Type for Subscribed HTTP Endpoint

### ISSUE THREAD

**Issue by hop-along-polly** [localstack/localstack#11617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using this command
```
awslocal sns publish \
    --topic-arn arn:aws:sns:us-east-1:000000000000:local-events \
    --message '{ "clientId": "13471337" }' \
    --message-structure json
```

I am able to successfully publish a message to SNS running in Localstack. The HTTP endpoint I've subscribed to the `local-events` SNS topic receives the notification, but the message body is empty i.e. `{}`.

### Expected Behavior

I would expect the Request Body in my HTTP Endpoint to be `'{ "clientId": "13471337" }'` OR `{ "message": "13471337" }`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

**docker-compose.yml** file
```yaml
version: '3.8'

services:
  my-api:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/opt/my-api/src

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=sns
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack
      # https://docs.localstack.cloud/references/init-hooks/
      - ./localstack-init-scripts/:/etc/localstack/init/ready.d/ # init.py script included below for reference.

volumes:
  localstack-data:
```

**localstack-init-scripts/init.py**
```python
import boto3
import requests

# SNS Client
sns = boto3.client('sns', endpoint_url='http://localhost:4566', region_name='us-east-1')

# Create Topic
topic_arn = sns.create_topic(Name='local-events')['TopicArn']
print('Topic Arn:', topic_arn)

#Subscribe HTTP endpoint to Topic
subscription_arn = sns.subscribe(
    TopicArn=topic_arn,
    Protocol='http',
    Endpoint='http://host.docker.internal:3000/events',
    # I've also tried Endpoint='http://my-api:3000/events',
    ReturnSubscriptionArn=True
)['SubscriptionArn']
print('Subscription Arn:', subscription_arn)

# Get the Subscription Token and Confirm the Subscription
token_res = requests.get(f'http://localhost:4566/_aws/sns/subscription-tokens/{subscription_arn}').json()
print('Token Res:', token_res)
confirmation_status_code = sns.confirm_subscription(
    TopicArn=topic_arn,
    Token=token_res['subscription_token']
).get('ResponseMetadata', {}).get('HTTPStatusCode', 500)

confirmed = True if confirmation_status_code == 200 else False 
print('Subscription Confirmed:', confirmed)
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal sns publish \
    --topic-arn arn:aws:sns:us-east-1:000000000000:local-events \
    --message '{ "clientId": "13471337" }' \
    --message-structure json
```

### Environment

```markdown
- OS: Mac OSX Sonoma 14.6.1
- LocalStack:
  LocalStack version: 3.7.3.dev37
  LocalStack Docker image sha: sha256:c95a34a63785cdf6a701f4ea8d455af2168baa0da4bc2577ea4678683d0f69af
  LocalStack build date: 2024-09-19
  LocalStack build git hash: b770a274e
```
