### ISSUE TITLE
Localstack S3 url replaces %20 resulting in 404 from browser

### ISSUE THREAD

**Issue by 5t33** [localstack/localstack#11642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
music-xml-tagging) ➜  musicxml-tagging 🔧 git:(repertoire-additional-fields) ✗ awslocal s3 ls s3://museflow-music-xml-output-bucket-local/repertoire/PNO/Alexander%20Goedicke%20-%20Eastern%20Melody/2024-10-04T23:46:24.000Z/png/Alexander%20Goedicke%20-%20Eastern%20Melody.musicxml_1_time_sig_600.png
2024-10-04 23:46:30      36037 Alexander%20Goedicke%20-%20Eastern%20Melody.musicxml_1_time_sig_600.png
```
As you can see in the above awslocal s3 command, the file is downloaded. However, if I run a curl, as you can see below: 

```
(music-xml-tagging) ➜  musicxml-tagging 🔧 git:(repertoire-additional-fields) ✗ docker run --entrypoint /bin/bash -it sha256:53a0fad1e479c75f4f743b3efcd00f60d8df007b6f2d5ec965a156ab07454a91
bash-4.2# curl http://host.docker.internal:4566/museflow-music-xml-output-bucket-local/repertoire/PNO/Alexander%20Goedicke%20-%20Eastern%20Melody/2024-10-04T23:46:24.000Z/png/Alexander%20Goedicke%20-%20Eastern%20Melody.musicxml_1_time_sig_600.png
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><RequestId>3b95b172-43d4-42b6-9ef8-3de5f2a9835f</RequestId><Key>repertoire/PNO/Alexander Goedicke - Eastern Melody/2024-10-04T23:46:24.000Z/png/Alexander Goedicke - Eastern Melody.musicxml_1_time_sig_600.png</Key></Error>bash-4.2# 
bash-4.2# 
```
I get a 404, and specifically the returned error code is telling: `Alexander Goedicke - Eastern Melody.musicxml_1_time_sig_600.png` seems to be the key that localstack is looking for internally.

Since I'm URL encoding my strings before uploading my data, they container %20 for spaces. Localstack seems to be decoding them in the query, and searching for the decoded string, not the encoded string. 

### Expected Behavior

the same key value is returned via curl and s3. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

my docker compose file:
```
version: '3.1'


services: 

  localstack:
    image: localstack/localstack:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=abcd
      - AWS_SECRET_ACCESS_KEY=efgh
      - EDGE_PORT=4566
      - SERVICES=s3
      - CLEAR_TMP_FOLDER=0
      - PROVIDER_OVERRIDE_S3=asf # https://github.com/localstack/localstack/issues/7374
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/var/liblocalstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
    awslocal s3 mb s3://museflow-music-xml-output-bucket-local
    awslocal s3 cp Alexander%20Goedicke%20-%20Eastern%20Melody.musicxml_1_time_sig_600.png s3://museflow-music-xml-output-bucket-local/repertoire/PNO/Alexander%20Goedicke%20-%20Eastern%20Melody/2024-10-04T23:46:24.000Z/png/Alexander%20Goedicke%20-%20Eastern%20Melody.musicxml_1_time_sig_600.png
docker run --entrypoint /bin/bash -it public.ecr.aws/lambda/nodejs:20
curl http://host.docker.internal:4566/museflow-music-xml-output-bucket-local/repertoire/PNO/Alexander%20Goedicke%20-%20Eastern%20Melody/2024-10-04T23:46:24.000Z/png/Alexander%20Goedicke%20-%20Eastern%20Melody.musicxml_1_time_sig_600.png
```

here's my file:
![Alexander%20Goedicke%20-%20Eastern%20Melody musicxml_1_time_sig_600](https://github.com/user-attachments/assets/9fd424f8-5474-400b-9fa7-98cdc17f3d48)

### Environment

```markdown
- OS: mac os m2
- LocalStack: 
  LocalStack version: 3.8
  LocalStack Docker image sha: sha256:79265d9801b8684ab630232c7403985334aa13ff8923cdb97b8c790f189e6793
  LocalStack build date:
  LocalStack build git hash:
```

### Anything else?

seems relatred to this https://github.com/localstack/localstack/issues/9112
