### ISSUE TITLE
bug: `_custom_key_material_` does not seem to work for SECP256k1

### ISSUE THREAD

**Issue by freemanzMrojo** [localstack/localstack#11678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running the following script in a docker-compose context the logs succeed when creating the actual key but the key created is not using the provided custom key material (it works for the `keyId` aka `CUSTOM_ID` though):

```
CUSTOM_KEY_MATERIAL="base64 secp256k1 private key"
CUSTOM_ID="custom id"

awslocal kms create-key --tags "[{\"TagKey\":\"_custom_key_material_\",\"TagValue\":\"$CUSTOM_KEY_MATERIAL\"},{\"TagKey\":\"_custom_id_\",\"TagValue\":\"$CUSTOM_ID\"}]" --key-usage SIGN_VERIFY --key-spec ECC_SECG_P256K1
```

When running the tests both sign and get public key return something but those are not definitely the values I am expecting (actually every time I restart it it creates new key material associated to the provided ID, I am generating an address from the public key in my test).

### Expected Behavior

The key is created with the custom material.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose -f docker-compose.localstack.yml up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    The sequence above

### Environment

```markdown
- OS: MacOS Ventura 13.0.1
- LocalStack:
  LocalStack version: 3.3.0
  LocalStack Docker image sha: sha256:b5c082a6d78d49fc4a102841648a8adeab4895f7d9a4ad042d7d485aed2da10d
```

### Anything else?

This is the configuration within the docker-compose file:

```
services:
  localstack:
    container_name: localstack
    hostname: localstack
    image: localstack/localstack:3.3.0
    restart: always
    ports:
      - 4599:4599
    environment:
      - SERVICES=kms
      - HOSTNAME_EXTERNAL=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - GATEWAY_LISTEN=0.0.0.0:4599
      - AWS_ENDPOINT_URL=http://localstack:4599
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - ./localstack/init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: 
      [
        "/bin/sh",
        "-c",
        "apt-get update && apt-get -y install jq && docker-entrypoint.sh"
      ]
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - $$(awslocal kms list-keys | jq '.Keys | length | . == 1') || exit 1; # There is 1 key at the moment
      interval: 5s
      timeout: 20s
      start_period: 2s
```
