### ISSUE TITLE
bug: make persistent

### ISSUE THREAD

**Issue by alexey-evometa** [localstack/localstack#11716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yml
services:
  localstack:
    image: localstack/localstack
    container_name: my_localstack
    hostname: "localstack"
    ports: [ "127.0.0.1:4566:4566" ]
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_S3_REGION_NAME=us-east-1
      - AWS_S3_BUCKET_NAME=my
    volumes:
      - ./localstack/point1:/tmp/localstack
      - ./localstack/point1:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

### Expected Behavior

Save S3 files to local dir

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

- `docker-compose up -d`
- upload files to S3
- `docker-compose down`
- `docker-compose up -d`
- see uploaded files

### Environment

```markdown
- OS: linux
- LocalStack:
  LocalStack version: 2.26.0
  LocalStack Docker image sha: 82dddb92a148411555020d8e344386a8532ac1f7f47ea7b3955d99bc42208e5c
  LocalStack build date:
  LocalStack build git hash:
```
