### ISSUE TITLE
bug: APIGatewayV2 sets `routeKey` to the `method` + `rawPath`

### ISSUE THREAD

**Issue by jlantto** [localstack/localstack#11762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've set up an endpoint that looks like this:

```
api.addRoute({
  methods: ["GET"],
  path: "/customers/{id}"
})
```

When running in LocalStack the request passed through to my handler has a `routeKey` property `GET /customers/123`

### Expected Behavior

In AWS the `routeKey` property is `GET /customers/{id}`.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
```yaml
services:
  localstack:
    hostname: localstack
    network_mode: bridge
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - PROVIDER_OVERRIDE_APIGATEWAY=1
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
    #      - PERSISTENCE=1
#      - SNAPSHOT_SAVE_STRATEGY=ON_SHUTDOWN
#      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: MacOS
- LocalStack:
  LocalStack version: 3.8.2.dev53
  LocalStack Docker image sha: sha256:c9619e9888ef1da92c7a23ec44f8fee796999167c0322e9260a19feca0c92869
  LocalStack build date: 2024-10-24
  LocalStack build git hash: abc3b266
```
