### ISSUE TITLE
bug: APIGatewayV2 proxy call loop when using node fetch

### ISSUE THREAD

**Issue by jlantto** [localstack/localstack#11763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an APIGatewayV2 set up like this:
```
customerApi.addRoutes({
  authorizer: customerAuthorizer,
  methods: ["GET"],
  path: "/whoami",
  integration: new apiIntegrations.HttpLambdaIntegration("customer-api-handler", f),
});

addProxy(this, config, customerApi.url, "/whoami");

```

where the `addProxy` utility looks like this:

```
export function addProxy(stack: Construct, config: EnvConfiguration, host: string | undefined, basePath: string) {
  if (!host) {
    throw new Error("Host is required for proxy");
  }
  if (host.endsWith("/")) {
    host = host.slice(0, -1);
  }
  const apiGatewayId = Fn.importValue(`${config.environment}-api-gateway-id`);
  const apiGateway = HttpApi.fromHttpApiAttributes(stack, `${config.environment}-api-gateway-${basePath}`, {
    httpApiId: apiGatewayId,
  });

  new HttpRoute(stack, `${config.environment}Proxy${basePath}`, {
    httpApi: apiGateway,
    routeKey: HttpRouteKey.with(basePath, HttpMethod.ANY),
    integration: new HttpUrlIntegration(`${config.environment}Proxy${basePath}`, `${host}${basePath}`, {
      method: HttpMethod.ANY,
    }),
  });
  new HttpRoute(stack, `${config.environment}Proxy${basePath}s`, {
    httpApi: apiGateway,
    routeKey: HttpRouteKey.with(`${basePath}/{proxy+}`, HttpMethod.ANY),
    integration: new HttpUrlIntegration(`${config.environment}Proxy${basePath}s`, `${host}${basePath}/{proxy}`, {
      method: HttpMethod.ANY,
    }),
  });
}
```

and the parent gateway is set up like this in another stack:

```
const gateway = new apigateway.HttpApi(stack, "api-gateway", {});

new CfnOutput(stack, "api-gateway-id-output", {
  exportName: `${config.environment}-api-gateway-id`,
  value: gateway.apiId,
});
```

If I query the parent gateway with curl everything works and the output looks like this:

```
`localstack-main  | 2024-10-29T15:31:18.692 DEBUG --- [et.reactor-3] l.s.l.i.version_manager    : [jonas-customer-user-whoami-29a2fc5f-3b4a-4353-91cf-fd3becefd7ec] END RequestId: 29a2fc5f-3b4a-4353-91cf-fd3becefd7ec
localstack-main  | 2024-10-29T15:31:18.692 DEBUG --- [et.reactor-3] l.s.l.i.version_manager    : [jonas-customer-user-whoami-29a2fc5f-3b4a-4353-91cf-fd3becefd7ec] REPORT RequestId: 29a2fc5f-3b4a-4353-91cf-fd3becefd7ec	Duration: 16.60 ms	Billed Duration: 17 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
localstack-main  | 2024-10-29T15:31:18.692 DEBUG --- [et.reactor-3] l.s.lambda_.provider       : Lambda invocation duration: 24.67ms
localstack-main  | 2024-10-29T15:31:18.693  INFO --- [t.reactor-12] localstack.request.http    : GET /whoami => 200
```

But when I query the same endpoint with nodeJS `fetch` I get this:

```
localstack-main  | 2024-10-29T15:32:50.744 DEBUG --- [et.reactor-2] l.p.c.s.a.n.e.router       : APIGW v2 HTTP Endpoint called
localstack-main  | 2024-10-29T15:32:50.745 DEBUG --- [et.reactor-2] l.p.c.s.a.n.e.h.h.parse    : Initializing $context='{'accountId': '000000000000', 'apiId': '01ea2f29', 'domainName': '01ea2f29.execute-api.localhost.localstack.cloud:4566', 'domainPrefix': '01ea2f29', 'extendedRequestId': 'a0fd150d', 'httpMethod': 'GET', 'identity': {'accountId': None, 'accessKey': None, 'caller': None, 'cognitoAmr': None, 'cognitoAuthenticationProvider': None, 'cognitoAuthenticationType': None, 'cognitoIdentityId': None, 'cognitoIdentityPoolId': None, 'principalOrgId': None, 'sourceIp': '127.0.0.1', 'user': None, 'userAgent': 'node', 'userArn': None}, 'path': '/whoami', 'protocol': 'HTTP/1.1', 'requestId': 'a0fd150d', 'requestTime': '29/Oct/2024:15:32:50 ', 'requestTimeEpoch': 1730215970745, 'routeKey': '', 'stage': '$default'}'
localstack-main  | 2024-10-29T15:32:50.746 DEBUG --- [et.reactor-2] l.p.c.s.a.n.e.h.h.parse    : Initializing $stageVariables='None'
localstack-main  | 2024-10-29T15:32:50.746 DEBUG --- [et.reactor-2] l.p.c.s.a.n.e.h.h.router   : Updating $context.routeKey='ANY /whoami'
localstack-main  | 2024-10-29T15:32:50.746 DEBUG --- [et.reactor-2] l.p.c.s.a.n.e.h.i.http     : Sending request to https://f1776649.execute-api.localhost.localstack.cloud:4566/whoami
localstack-main  | 2024-10-29T15:32:50.763 DEBUG --- [et.reactor-1] l.p.c.s.a.n.e.router       : APIGW v2 HTTP Endpoint called
localstack-main  | 2024-10-29T15:32:50.763 DEBUG --- [et.reactor-1] l.p.c.s.a.n.e.h.h.parse    : Initializing $context='{'accountId': '000000000000', 'apiId': '01ea2f29', 'domainName': '01ea2f29.execute-api.localhost.localstack.cloud:4566', 'domainPrefix': '01ea2f29', 'extendedRequestId': '1d2248be', 'httpMethod': 'GET', 'identity': {'accountId': None, 'accessKey': None, 'caller': None, 'cognitoAmr': None, 'cognitoAuthenticationProvider': None, 'cognitoAuthenticationType': None, 'cognitoIdentityId': None, 'cognitoIdentityPoolId': None, 'principalOrgId': None, 'sourceIp': '127.0.0.1', 'user': None, 'userAgent': 'node', 'userArn': None}, 'path': '/whoami', 'protocol': 'HTTP/1.1', 'requestId': '1d2248be', 'requestTime': '29/Oct/2024:15:32:50 ', 'requestTimeEpoch': 1730215970763, 'routeKey': '', 'stage': '$default'}'
localstack-main  | 2024-10-29T15:32:50.763 DEBUG --- [et.reactor-1] l.p.c.s.a.n.e.h.h.parse    : Initializing $stageVariables='None'
localstack-main  | 2024-10-29T15:32:50.763 DEBUG --- [et.reactor-1] l.p.c.s.a.n.e.h.h.router   : Updating $context.routeKey='ANY /whoami'
localstack-main  | 2024-10-29T15:32:50.763 DEBUG --- [et.reactor-1] l.p.c.s.a.n.e.h.i.http     : Sending request to https://f1776649.execute-api.localhost.localstack.cloud:4566/whoami
localstack-main  | 2024-10-29T15:32:50.772 DEBUG --- [et.reactor-6] l.p.c.s.a.n.e.router       : APIGW v2 HTTP Endpoint called
localstack-main  | 2024-10-29T15:32:50.772 DEBUG --- [et.reactor-6] l.p.c.s.a.n.e.h.h.parse    : Initializing $context='{'accountId': '000000000000', 'apiId': '01ea2f29', 'domainName': '01ea2f29.execute-api.localhost.localstack.cloud:4566', 'domainPrefix': '01ea2f29', 'extendedRequestId': '241f4152', 'httpMethod': 'GET', 'identity': {'accountId': None, 'accessKey': None, 'caller': None, 'cognitoAmr': None, 'cognitoAuthenticationProvider': None, 'cognitoAuthenticationType': None, 'cognitoIdentityId': None, 'cognitoIdentityPoolId': None, 'principalOrgId': None, 'sourceIp': '127.0.0.1', 'user': None, 'userAgent': 'node', 'userArn': None}, 'path': '/whoami', 'protocol': 'HTTP/1.1', 'requestId': '241f4152', 'requestTime': '29/Oct/2024:15:32:50 ', 'requestTimeEpoch': 1730215970772, 'routeKey': '', 'stage': '$default'}'
```

And then it repeats until LocalStack hangs and needs to be shutdown before becoming responsive again. Not even `awslocal` gets any responses before that.

Calling the child apigateway works fine in fetch, but gives the same log output as curl, i.e. not `APIGW v2 HTTP Endpoint called`. Postman also works just fine, but also with the same log output as `curl`. What can I do to figure out what's going wrong?

### Expected Behavior

LocalStack should behave the same way regardless of which way I call the endpoint. And it shouldn't hang.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
```yaml
services:
  localstack:
    hostname: localstack
    network_mode: bridge
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=1
      - PROVIDER_OVERRIDE_APIGATEWAY=next_gen
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
    #      - PERSISTENCE=1
#      - SNAPSHOT_SAVE_STRATEGY=ON_SHUTDOWN
#      - SNAPSHOT_LOAD_STRATEGY=ON_STARTUP
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: MacOS
- LocalStack:
  LocalStack version: 3.8.2.dev60
  LocalStack Docker image sha: sha256:c9619e9888ef1da92c7a23ec44f8fee796999167c0322e9260a19feca0c92869
  LocalStack build date: 2024-10-28
  LocalStack build git hash: 1ac37238
```

### Anything else?

In the end LocalStack fails with `Read timeout on endpoint URL: "http://localhost:4566/`.
