### ISSUE TITLE
bug: Docker image error reading push output: no such host

### ISSUE THREAD

**Issue by cedric-fauth** [localstack/localstack#11790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

First I tried this using localstack 3.8 but got the error after rebooting the PC. I downgraded to 3.6 and it worked. A few days later I continued working and the error occured again but now with version 3.6.

When setting up a repo or(?) pushing an image to localstack using pulumi I get the following error:

```python
repo = aws.ecr.Repository(
    f'{name}-service-repo',
    force_delete=True,
    opts=opts,
)

image = docker.Image(
    f'{name}-initial-image',
    build=docker.DockerBuildArgs(
        context='.',
        dockerfile='./resources/ecs/Dockerfile',
        args={'PORT': str(port)},
    ),
    image_name=repo.repository_url,
)
```

```
docker:index:Image (test-initial-image):
error: error reading push output: Get "https://000000000000.dkr.ecr.eu-central-1.localhost:4566/v2/": dialing 000000000000.dkr.ecr.eu-central-1.localhost:4566 with direct connection: resolving host 000000000000.dkr.ecr.eu-central-1.localhost: lookup 000000000000.dkr.ecr.eu-central-1.localhost: no such host

```

### Expected Behavior

Should return a valid push output with image_name and repository_url defined.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:3.6
    environment:
      MAIN_DOCKER_NETWORK: nw
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN}
      LOCALSTACK_HOST: localhost
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:443:443" # LocalStack HTTPS Gateway (only required for Pro)
    volumes:
      ...
    networks:
      - nw

```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```python
import pulumi_aws as aws
import pulumi_awsx as awsx
import pulumi_docker as docker
import pulumi_github as github
import pulumi_random as random

repo = aws.ecr.Repository(
    f'{name}-service-repo',
    force_delete=True,
    opts=opts,
)

image = docker.Image(
    f'{name}-initial-image',
    build=docker.DockerBuildArgs(
        context='.',
        dockerfile='./resources/ecs/Dockerfile',
        args={'PORT': str(port)},
    ),
    image_name=repo.repository_url,
)
image_uri = image.image_name
```

### Environment

```markdown
- OS: Ubuntu on WSL 2 with Docker Desktop installed on Windows
- LocalStack: 

LocalStack version: 3.6.1.dev20240725063846
LocalStack build date: 2024-07-25
LocalStack build git hash: 33f0744
```
