### ISSUE TITLE
bug:Websocket $connect route : Received error on $connect event handler - denying WebSocket connection: Exception during $connect action: 'NoneType' object has no attribute 'details'

### ISSUE THREAD

**Issue by fridaystreet** [localstack/localstack#11824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to get a simple websocket up and running but the $connect route doesn't seem to work and throws the following error. My lambda function is actuall invoked and I can out put the contents of event/context.

Not entirely sure what this error is but sounds like the response from function isn't being handled?

It is being built with serverless, config below, again prettyy standard serverless setup. Using locakstack pro

Lambda invocation duration: 9839.32ms
2024-11-11T05:01:59.095  INFO --- [functhread27] l.p.c.s.a.n.e.w.websocket_ : Error invoking integration request for route "$connect": 'NoneType' object has no attribute 'details'
2024-11-11T05:01:59.097 DEBUG --- [functhread10] l.p.core.utils.websockets  : Received error on $connect event handler - denying WebSocket connection: Exception during $connect action: 'NoneType' object has no attribute 'details'
2024-11-11T05:01:59.105  INFO --- [functhread10] websockets.server          : connection closed
2024-11-11T05:01:59.168  INFO --- [functhread27] localstack.utils.threads   : Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0xffff58b36340>(None) failed: Exception during $connect action: 'NoneType' object has no attribute 'details' Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/execute_api/websockets_legacy/websocket_async_handler.py.enc", line 61, in v2_invoke_action_from_websocket_next_gen
    I=A.data_as_string();N=create_integration_payload_event(A);R=json.dumps(json_safe(I))if isinstance(I,(dict,list))else I;A.data=N['body']=str(R);A.context=get_event_request_context(A);C=v2_invoke_integration_request(A,H,N)
                                                                                                                                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigateway/legacy/integrations.py.enc", line 150, in v2_invoke_integration_request
    if C.headers.get('origin'):add_allow_origin_header(C,A)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigateway/legacy/apigateway_utils.py.enc", line 259, in add_allow_origin_header
    if _K in B.details:
             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'details'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/threads.py", line 60, in run
    result = self.func(self.params, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/utils/asyncio.py", line 51, in _run
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/execute_api/websockets_legacy/websocket_async_handler.py.enc", line 41, in A
    B=v2_invoke_action_from_websocket_next_gen(A,C,F.api_config)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/execute_api/websockets_legacy/websocket_async_handler.py.enc", line 65, in v2_invoke_action_from_websocket_next_gen
    if E==_B:raise ConnectionDeniedException(f"Exception during $connect action: {J}")from J
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack.pro.core.services.apigateway.legacy.models.ConnectionDeniedException: Exception during $connect action: 'NoneType' object has no attribute 'details'

2024-11-11T05:01:59.168 DEBUG --- [functhread27] localstack.utils.threads   : FINISHED: <Future at 0xffff593f9650 state=finished raised ConnectionDeniedException>
2024-11-11T05:01:59.180 DEBUG --- [et.reactor-3] l.s.cloudwatch.provider_v2 : starting cloudwatch scheduler

### Expected Behavior

returns the response on $coneect

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

localstack docker compose

```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}" #localstack/localstack-full for web interface
    image: localstack/localstack-pro
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
      - "8080:8080"                    # LocalStack Dashboard
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - LOCALSTACK_AUTH_TOKEN="ls-DuLeRINu-zUCo-9893-1000-HEvohATa4da8"
      - DEBUG=${DEBUG:-0}
      - DOCKER_SOCK=/var/run/docker.sock
      - LAMBDA_DEBUG_MODE=${LAMBDA_DEBUG_MODE:-0}
      - LAMBDA_DEBUG_MODE_CONFIG_PATH=${LAMBDA_DEBUG_MODE:+/app/debug_config.yaml}
      - PROVIDER_OVERRIDE_APIGATEWAY=next_gen
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=300
      - LAMBDA_LIMITS_TOTAL_CODE_SIZE = 8880530636800
      - LAMBDA_LIMITS_CODE_SIZE_ZIPPED = 5552428800
      - LAMBDA_LIMITS_CODE_SIZE_UNZIPPED = 55262144000
      - LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE = 7770167211
      - DYNAMODB_REMOVE_EXPIRED_ITEMS=1
      - GATEWAY_LISTEN=0.0.0.0
      - START_WEB=1
      - LAMBDA_REMOVE_CONTAINERS=1
      - DISABLE_CORS_CHECKS=1 #would be great to know how to fix this
      - DISABLE_CUSTOM_CORS_APIGATEWAY=0 #so it can properly emulate live environment
      
      ```

### Environment

```markdown
- OS:mac
- LocalStack:
  LocalStack version: 3.8.2.dev94
LocalStack build date: 2024-11-08
LocalStack build git hash: aae1a03f

Serverless v4.4.7

This is the websocket function, taken from the localstack docs


export const handleWebSocket = function(event, context, callback) {
  console.log('ws', event)
  callback(null, event);
};
```
```


### Anything else?

webSocketHandler:
    handler: dist/index.handleWebSocket
    tracing: PassThrough
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
