### ISSUE TITLE
Layers for lambda function does not work on python3.9 runtime (Localstack Pro)

### ISSUE THREAD

**Issue by long-tran-dss** [localstack/localstack#11881]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently I’m trying to use the matplotlib library in my source code so I want to create a layer. However it is not working now. I don’t know if I’m configuring it wrong, so when I invoke the lambda function, so when I invoke the lambda function the layer doesn’t work?

Error :
`2024-11-19 20:02:22 2024-11-19T11:02:22.661  WARN --- [et.reactor-0] l.s.l.i.executor_endpoint  : Execution environment startup failed: {"errorMessage": "Unable to import module 'src/api/v1/route/lane': No module named 'matplotlib'", "errorType": "Runtime.ImportModuleError", "requestId": "", "stackTrace": []}`

### Expected Behavior

lambda function works properly with matplotlib

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

→ To intall lib and zip it to matplotlib.zip
`pip install -r requirements.txt -t layer` 

→ To create layers
```
aws --endpoint-url http://localhost:4566 lambda publish-layer-version --layer-name matplotliblayer \ 
          --license-info "MIT" \ 
          --zip-file fileb://layer/matplotlib.zip \ 
          --compatible-runtimes python3.9 \ 
          --compatible-architectures "arm64" "x86_64"
```

→ To create lambda function
```
aws --endpoint-url=http://localhost:4566 lambda create-function \ 
       --function-name lane-fuction \
       --runtime python3.9 \ 
       --role arn:aws:iam::000000000000:role/lambda-role \ 
       --handler src/api/v1/route/lane.main \ 
       --zip-file fileb://src/route.zip \ 
       --timeout 120 \ 
       --layers arn:aws:lambda:ap-northeast-1:000000000000:layer:matplotliblayer:1
```

The structure of the matplotlib.zip file is as follows: 
matplotlib.zip
___└── python
_______└── dependencies

I also tried the structure as shown in the AWS docs
![image](https://github.com/user-attachments/assets/571c588e-363e-43e1-9f49-9b256c770529)

### Environment

```markdown
- OS: Windows
- LocalStack:
  LocalStack version: 3.8.2.dev105
  LocalStack Docker image sha:
  LocalStack build date: 2024-11-14
  LocalStack build git hash: e42c433a
```

**Comment by MarcelStranak** [comment]
Hello @long-tran-dss,

It is necessary to include a Linux-compatible version of the Python library in your Lambda layer; otherwise, it will result in the error you have encountered.

You can find more details at https://docs.aws.amazon.com/lambda/latest/dg/packaging-layers.html

For Python layers: https://docs.aws.amazon.com/lambda/latest/dg/python-layers.html#python-layer-compatibility

Here is an example how to get the correct version of the library:

```powershell
# Download the linux version of python library
pip install matplotlib --platform manylinux2014_x86_64 --only-binary=:all:  --python-version 3.12  --target ./packages/python
# Create a ZIP archive of the Lambda layer
Compress-Archive -Path .\packages\* -DestinationPath layer.zip -Force
```

**Comment by long-tran-dss** [comment]
@MarcelStranak  
I tried using config 
> For Python layers: https://docs.aws.amazon.com/lambda/latest/dg/python-layers.html#python-layer-compatibility 
However, localstack only works with [layer containing request](https://docs.aws.amazon.com/lambda/latest/dg/python-layers.html#python-layer-packaging) but not for [manylinux wheel distributions](https://docs.aws.amazon.com/lambda/latest/dg/python-layers.html#python-layer-manylinux)

**Comment by MarcelStranak** [comment]
Hi @long-tran-dss,

Please refer to a complete example that uses the pandas package with Python 3.12.
Make sure both files are in the same directory before running `deploy.ps1`.
Don't forget to provide your `LOCALSTACK_AUTH_TOKEN`.

`docker-compose.yml`
```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}  # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

`deploy.ps1`
```powershell
# Define variables
$functionName = "addTenAndMultiplyByTwo"
$runtime = "python3.12"
$role = "arn:aws:iam::000000000000:role/lambda-role"  # Dummy role, replace with actual role ARN
$handler = "lambda_function.handler"
$zipFile = "lambda_function.zip"
$zipFileLayer = "pandas_layer.zip"
$payload = '{"number": 10}'

# Install dependencies and package the Lambda function
if (-not (Test-Path .\packages)) {
	pip install pandas --platform manylinux2014_x86_64 --only-binary=:all:  --python-version 3.12  --target ./packages/python
}

# Create a ZIP archive of the Lambda layer
Compress-Archive -Path .\packages\* -DestinationPath $zipFileLayer -Update

# Lambda function code
$lambdaContent = @'
import pandas as pd

def handler(event, context):
    number = event.get("number", 0)
    df = pd.DataFrame({"number": [number]})
    df["result"] = (df["number"] + 10) * 2
    result = int(df["result"].values[0])
    return {"statusCode": 200, "body": {"original_number": number, "result": result}}
'@

$lambdaContent | Out-File -FilePath .\lambda_function.py -Encoding utf8


# Create a ZIP archive of the Lambda function
Compress-Archive -Path .\lambda_function.py -DestinationPath $zipFile -Update

docker compose up -d --wait

# Deploy the Lambda function using AWS CLI
aws lambda create-function `
    --function-name $functionName `
    --runtime $runtime `
    --role $role `
    --handler $handler `
    --zip-file fileb://$zipFile `
    --timeout 15 `
    --memory-size 128

# Publish the Lambda layer using AWS CLI
aws lambda publish-layer-version `
	--layer-name pandas_layer `
	--description "Pandas layer" `
	--zip-file fileb://$zipFileLayer

# Wait for the Lambda function to be ready
aws lambda wait function-active --function-name $functionName

# Update the Lambda function to use the layer
aws lambda update-function-configuration `
	--function-name $functionName `
	--layers arn:aws:lambda:us-east-1:000000000000:layer:pandas_layer:1 

# Wait for the Lambda function to be ready
aws lambda wait function-active --function-name $functionName

# Invoke the Lambda function using AWS CLI
$response = aws lambda invoke `
    --function-name $functionName `
    --payload $payload `
    output.json

# Print the Lambda response
Get-Content -Path output.json 

docker compose down
```
