### ISSUE TITLE
Error creating DynamoDB table w/global secondary index using PAY_PER_REQUEST billing mode

### ISSUE THREAD

**Issue by lwoodson** [localstack/localstack#1193]
I am getting an error attempting to create a DynamoDB table via cloudformation using the new `PAY_PER_REQUEST` billing model when it has a `GlobalSecondaryIndex` without a `ProvisionedThroughput` as the [cloudformation says is required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-gsi.html#cfn-dynamodb-gsi-provisionthroughput).  This is using version `0.9.0` released through dockerhub. 

### My table def:
```yaml
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: store-events
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: customer_store_order
            AttributeType: S
          - AttributeName: occurred_at
            AttributeType: N
          - AttributeName: store_platform
            AttributeType: S
        KeySchema:
          - AttributeName: customer_store_order
            KeyType: HASH
          - AttributeName: occurred_at
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ByStorePlatform
            KeySchema:
              - AttributeName: store_platform
                KeyType: HASH
              - AttributeName: occurred_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: purge_at
          Enabled: true
```

### Error I am receiving
```
localstack_1  | 2019-03-13T18:09:20:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method DynamoDB.create_table of <botocore.client.DynamoDB object at 0x7f85fe084810>> with params: {'GlobalSecondaryIndexes': [{'KeySchema': [{'KeyType': 'HASH', 'AttributeName': 'store_platform'}, {'KeyType': 'RANGE', 'AttributeName': 'occurred_at'}], 'IndexName': 'ByStorePlatform', 'Projection': {'ProjectionType': 'ALL'}}], 'AttributeDefinitions': [{'AttributeName': 'customer_store_order', 'AttributeType': 'S'}, {'AttributeName': 'occurred_at', 'AttributeType': 'N'}, {'AttributeName': 'store_platform', 'AttributeType': 'S'}], 'ProvisionedThroughput': {'WriteCapacityUnits': 5, 'ReadCapacityUnits': 5}, 'KeySchema': [{'KeyType': 'HASH', 'AttributeName': 'customer_store_order'}, {'KeyType': 'RANGE', 'AttributeName': 'occurred_at'}], 'TableName': 'orders-webhooks-local-events'} for resource: {'Type': 'AWS::DynamoDB::Table', 'Properties': {'GlobalSecondaryIndexes': [{'KeySchema': [{'KeyType': 'HASH', 'AttributeName': 'store_platform'}, {'KeyType': 'RANGE', 'AttributeName': 'occurred_at'}], 'IndexName': 'ByStorePlatform', 'Projection': {'ProjectionType': 'ALL'}}], 'AttributeDefinitions': [{'AttributeName': 'customer_store_order', 'AttributeType': 'S'}, {'AttributeName': 'occurred_at', 'AttributeType': 'N'}, {'AttributeName': 'store_platform', 'AttributeType': 'S'}], 'TableName': 'orders-webhooks-local-events', 'BillingMode': 'PAY_PER_REQUEST', 'TimeToLiveSpecification': {'Enabled': True, 'AttributeName': 'purge_at'}, 'KeySchema': [{'KeyType': 'HASH', 'AttributeName': 'customer_store_order'}, {'KeyType': 'RANGE', 'AttributeName': 'occurred_at'}]}}
localstack_1  | 2019-03-13T18:09:20:INFO:werkzeug: 127.0.0.1 - - [13/Mar/2019 18:09:20] "POST / HTTP/1.1" 500 -
localstack_1  | 2019-03-13T18:09:20:ERROR:werkzeug: Error on request:
localstack_1  | Traceback (most recent call last):
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack_1  | execute(self.server.app)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack_1  | application_iter = app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 101, in __call__
localstack_1  | return backend_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack_1  | return self.wsgi_app(environ, start_response)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack_1  | response = self.handle_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack_1  | response = self.full_dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack_1  | rv = self.handle_user_exception(e)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack_1  | reraise(exc_type, exc_value, tb)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack_1  | rv = self.dispatch_request()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack_1  | return self.view_functions[rule.endpoint](**req.view_args)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
localstack_1  | result = self.callback(request, request.url, {})
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 117, in dispatch
localstack_1  | return cls()._dispatch(*args, **kwargs)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 200, in _dispatch
localstack_1  | return self.call_action()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/responses.py", line 274, in call_action
localstack_1  | response = method()
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 196, in list_stack_resources
localstack_1  | stack_name_or_id)
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 246, in list_stack_resources
localstack_1  | return stack.stack_resources
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 97, in stack_resources
localstack_1  | return self.resource_map.values()
localstack_1  | File "/usr/lib/python2.7/_abcoll.py", line 418, in values
localstack_1  | return [self[key] for key in self]
localstack_1  | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 403, in __getitem__
localstack_1  | resource_logical_id, resource_json, self, self._region_name)
localstack_1  | File "/home/travis/build/localstack/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 116, in parse_and_create_resource
localstack_1  |
localstack_1  | File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 544, in deploy_resource
localstack_1  | raise e
localstack_1  | ClientError: An error occurred (ValidationException) when calling the CreateTable operation: No provisioned throughput specified for the global secondary index
```

This seems related to but slightly different than https://github.com/localstack/localstack/issues/1089
