### ISSUE TITLE
localstack with fixed IP does not work

### ISSUE THREAD

**Issue by Tirthas** [localstack/localstack#11955]
Hi Team,

Recently i started using localstack (community) to test things in my local machine. I saw in the localstack doc that to connect localstack resource (SQS in my case) from another container hosting my .Net application I should configure the dns in my application container.

So I changed mydocker-compose.yaml file like so:

##########################################
```yaml
version: "3.7"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.1.0    
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range      
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"    
    networks:
      backend:
        # Set the container IP address in the 10.0.2.0/24 subnet
        ipv4_address: 10.0.2.20
      
  application:
    image: ghcr.io/localstack/localstack-docker-debug:main
    entrypoint: ""
    command: ["sleep", "infinity"]
    dns:
      # Set the DNS server to be the LocalStack container
      - 10.0.2.20
    networks:
      - backend
      
networks:
  frontend:
  backend:
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 10.0.2.0/24
```
    
###############

But when i try to do docker-compose up --build localstack
[+] Running 1/1
 ✔ Container localstack-main  Recreated                                                                            0.4s
Attaching to localstack-main
Error response from daemon: Invalid address 10.0.2.20: It does not belong to any of this network's subnets

Please let me know where i am going wrong. Is this docker desktop cache, how do i clear it and start fresh. 
Restarting docker desktop did not help :(.
