### ISSUE TITLE
bug: CloudFormation "Sub" function not escaping ${} when ! is present

### ISSUE THREAD

**Issue by Ryther** [localstack/localstack#12031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to escape the `${account_id}` string with the suggested method in the AWS CF Docs by using `${!account_id}`, I get the following error:
`Template format error: Unresolved resource dependencies [!account_id] in the Resources block of the template`

### Expected Behavior

As stated in the [AWS Docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#w40aac23c24c69b7) in the last part of the "**_String_**" section:

> To write a dollar sign and curly braces (${}) literally, add an exclamation point (!) after the open curly brace, such as ${!Literal}. CloudFormation resolves this text as ${Literal}.

the expected result is a string containing the literal `${account_id}` without trying to resolve it.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
- Using `docker-compose.yml`:
    ```yaml
    services:
      test-localstack:
        image: localstack/localstack:4.0.2
        container_name: test-localstack
        env_file:
        - path: ./docker-compose/.docker-env
          required: false
        - path: ./docker-compose/localstack/.localstack-env
          required: true
        healthcheck:
          test:
          - "CMD"
          - "test"
          - "-f"
          - "/tmp/ready"
          interval: 5s
          timeout: 1s
          start_period: 15s
          retries: 10
        volumes:
        - "./docker-compose/localstack/etc/localstack/init/ready.d:/etc/localstack/init/ready.d"
        - "./docker-compose/localstack/tmp/config:/tmp/config"
        - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
        - 4571:4566
    ```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal cloudformation create-stack --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" "CAPABILITY_AUTO_EXPAND" --stack-name "${stack_name}" --template-body "file://${template_file}" --parameters "${parameters_param[@]}" --endpoint-url="${INIT_AWS_ENDPOINT}" --profile "${INIT_AWS_PROFILE}" --region "${INIT_AWS_REGION}"
```

### Environment

```markdown
- OS: Windows 11 - WSL2 (Arch linux)
- LocalStack:
  LocalStack version: 4.0.3
  LocalStack Docker image sha: 17c2f79ca4e1f804eb912291a19713d4134806325ef0d21d4c1053161dfa72d0
  LocalStack build date: 2024-11-29
  LocalStack build git hash: aa795ed1c
```
