### ISSUE TITLE
bug: Error in apigatewayv2 HTTP API invocation: 'AuthorizerPayloadFormatVersion'

### ISSUE THREAD

**Issue by Solvegam** [localstack/localstack#12085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Endpoint protected by cognito authorizer (used with http API Gateway) returns error in the response body:
```
Error in apigatewayv2 HTTP API invocation: 'AuthorizerPayloadFormatVersion'
```
while in logs the following can be found:
```
2025-01-01T20:52:16.372  WARN --- [et.reactor-1] l.p.c.s.a.n.e.h.h.exceptio : Non Gateway Exception raised: 'AuthorizerPayloadFormatVersion'
#Traceback (most recent call last):
l  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
*    handler(self, self.context, response)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/execute_api/http/handlers/authorize.py.enc", line 17, in __call__
    E.authorize(B,D)
  File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack/pro/core/services/apigatewayv2/next_gen/execute_api/http/authorizers/request.py.enc", line 42, in authorize
    C=authorizer;A=context;F=B.get_identity_source_values(context=A,identity_sources=C['IdentitySource']);I=C['AuthorizerPayloadFormatVersion'];J=C.get('EnableSimpleResponses');K=get_lambda_function_arn_from_invocation_uri(C['AuthorizerUri']);L=C.get('AuthorizerCredentialsArn');M=f"arn:{get_partition(A.region)}:execute-api:{A.region}:{A.account_id}:{A.api_id}/authorizers/{C['AuthorizerId']}"
                                                                                                            ~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+KeyError: 'AuthorizerPayloadFormatVersion'
```

But the thing is that `AuthorizerPayloadFormatVersion` should not be mentioned in Cognito Authorizer.

### Expected Behavior

Authorizer successfully authorises request and lambda function is invoked

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

     bin/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In zip file entire example project can be found 
[example.zip](https://github.com/user-attachments/files/18286616/example.zip)
To run the project you will need java 21, maven, sam cli, localstack.

Sequence of commands
```shell
LOCALSTACK_AUTH_TOKEN=<token> DEBUG=1 localstack start
sam build 
AWS_ENDPOINT_URL=http://localhost:4566 sam deploy --profile localstack

# to sign up as user
curl --location 'http://localhost:4566/' \
--header 'X-Amz-Target: AWSCognitoIdentityProviderService.SignUp' \
--header 'Content-Type: application/x-amz-json-1.1' \
--data-raw '{
  "ClientId": "{{clientId}}",
  "Username": "testuser",
  "Password": "StrongP@ssw0rd",
  "UserAttributes": [
    {
      "Name": "email",
      "Value": "some@gmail.com"
    }
  ]
}

# to confirm user as admin
curl --location 'http://localhost:4566/' \
--header 'X-Amz-Target: AWSCognitoIdentityProviderService.AdminConfirmSignUp' \
--header 'Content-Type: application/x-amz-json-1.1' \
--data '{
  "UserPoolId": "{{userPoolId}}",
  "Username": "testuser"
}'

# to get authorisation code
https://localhost:4566/_aws/cognito-idp/login?response_type=code&client_id={{cognitoClientId}}&redirect_uri=http://localhost:8080/callback

# to get access token 
curl --location 'http://localhost:4566/_aws/cognito-idp/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'client_id={{clientId}}' \
--data-urlencode 'code={{authroizationCodeFromRedirect}}' \
--data-urlencode 'redirect_uri=http://localhost:8080/callback'

# to make call to /hello
curl --location 'http://localhost:4566/restapis/b44d8b0c/Prod/_user_request_/hello' \
--header 'Authorization: Bearer {{accessTokenFromPreviousStep}}'
```

below you can find used sam template 
 ```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  java-api

  Sample SAM Template for java-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            ApiId: !Ref MyHttpApi
            Auth:
              Authorizer: CognitoAuthorizer

  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: LinkCheckerUserPool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      UserPoolAddOns:
        AdvancedSecurityMode: ENFORCED
  MyUserPoolWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MyUserPoolWebClient
      UserPoolId: !Ref MyUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      CallbackURLs:
        - http://localhost:8080/callback
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt MyUserPool.Arn
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${MyUserPool}"
              audience:
                - !Ref MyUserPoolWebClient
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
Outputs:
  HttpApiId:
    Description: "ID of the HTTP API Gateway"
    Value: !Ref MyHttpApi
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref MyUserPoolWebClient
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref MyUserPool
```

### Environment

```markdown
- OS: masOS Sequoia 15.2
- LocalStack:
  LocalStack version: 4.0.4.dev53
  LocalStack Docker image sha:
  LocalStack build date: 2024-12-17
  LocalStack build git hash: 9e2ae52cb
```
