### ISSUE TITLE
Using docker networks with docker compose

### ISSUE THREAD

**Issue by rlpacht** [localstack/localstack#1212]
I have have two services running in two separate docker containers that need to share a SQS queue. I'm trying to use docker networks and I get get `localstack` to run in the docker-container but it can't connect to `http://localstack:4576/`. I'll be the first to admit that I don't know docker networks all that well so I could be doing something wrong, but I also wanted to check if this is even something that localstack supports. I've included the relevant parts of the `docker-compose.yml`

```
version: '3.3'
services:
  app:
    build: .
    image: app
    environment:
      - AWS_PROFILE=<MY_PROFILE>
    networks:
      - default
      - db
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - 4576:4576
      - 4584:4584
    environment:
      - SERVICES=sqs:4576,secretsmanager:4584
      - HOSTNAME=localhost
    networks:
      - localstack

  create-queue:
    image: app
    environment:
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=us-west-2
    entrypoint: ["./bin/wait-for-sqs.sh", "localstack"]
    command: ["yarn", "run", "create-queue"]
    depends_on:
      - localstack

networks:
  default:
  db:
  localstack:

```

**Comment by shenie** [comment]
It's possible and it can be done without creating custom networks.

The default compose network will do. Inside your `create-queue` & `app` services you can get to localstack via the localstack service name, i.e. `http://localstack:<port-of-the-aws-service>`

**Comment by rlpacht** [comment]
I wasn't clear in my original post and I've edited it to fix that, but the two services are running in separate docker containers. the code I posted is from the service that's running localstack and  creating the queue. 

In testing this I've found that I can't connect to a custom network at all. It fails to connect localstack if I `networks` defined at all in the localstack section of my docker-compose

**Comment by lansana** [comment]
It seems there was bug in LocalStack which was only fixed for Lambda: https://github.com/localstack/localstack/pull/883 https://github.com/localstack/localstack/pull/567

**Comment by joelmukuthu** [comment]
I got this to work by adding the `HOSTNAME_EXTERNAL` env variable. This was based on a fix I found in this issue: https://gitlab.com/gitlab-org/gitlab-runner/issues/3092.

Here's a docker-compose file that works:

```yml
version: "3"
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs:4576
      - HOSTNAME_EXTERNAL=localstack

  app:
    build: .
    depends_on:
      - localstack
    environment:
      SQS_ENDPOINT: http://localstack:4576
```

Note that it takes a while for the localstack services to start even after the container itself is running. So if you have a script trying to connect to `http://localstack:4576`, expect some `connect ECONNREFUSED` errors for a few seconds while the service starts.

**Comment by whummer** [comment]
Great, thanks for providing the solution @joelmukuthu ! /cc @lansana @rlpacht

**Comment by dhagan-va** [comment]
I had a similar problem (I think) and it was solved by  seting

` network_mode: host`

**Comment by NicolajKN** [comment]
For anyone having trouble connecting to SQS queues between docker-compose services, what worked for me was supplying both internal and external hostname, as well as supplying the SQS port explicitly:

```yaml
version: '3.9'
services:
  my-service:
    build:
      context: ./my-service
    environment:
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT=http://localstack:4566
      - SQS_QUEUE=http://localstack:4566/000000000000/my-queue.fifo
    depends_on:
      - localstack
  localstack:
    image: localstack/localstack
    environment:
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
      - SQS_PORT_EXTERNAL=4566
      - AWS_DEFAULT_REGION=eu-central-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
