### ISSUE TITLE
Creating EBS snapshot throws error 501

### ISSUE THREAD

**Issue by chickencoding123** [localstack/localstack#12138]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Running:
```sh
awslocal ebs start-snapshot --volume-size 1 --profile localstack
```

Outputs:
```sh
An error occurred (InternalFailure) when calling the StartSnapshot operation: API for service 'ebs' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
```

Localstack docker is showing a more detailed output:
```sh
localstack-main  | 2025-01-14T14:12:32.625 ERROR --- [et.reactor-0] l.aws.handlers.logging     : exception during call chain
localstack-main  | Traceback (most recent call last):
localstack-main  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/rolo/gateway/chain.py", line 166, in handle
localstack-main  |     handler(self, self.context, response)
localstack-main  |   File "/opt/code/localstack/localstack-core/localstack/aws/handlers/service_plugin.py", line 36, in __call__
localstack-main  |     return self.require_service(chain, context, response)
localstack-main  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack-main  |   File "/opt/code/localstack/localstack-core/localstack/aws/handlers/service_plugin.py", line 47, in require_service
localstack-main  |     raise NotImplementedError
localstack-main  | NotImplementedError
localstack-main  | 2025-01-14T14:12:32.626  INFO --- [et.reactor-0] l.aws.handlers.service     : API for service 'ebs' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/ for further information
localstack-main  | 2025-01-14T14:12:32.626  INFO --- [et.reactor-0] localstack.request.aws     : AWS ebs.StartSnapshot => 501 (InternalFailure)
```

I have checked https://docs.localstack.cloud/references/coverage/coverage_ec2/ and see:
>CreateSnapshot	✔️	community	

There are no previous warnings or errors.

docker-compose.yml
```yml
services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    ports:
      - 127.0.0.1:4566:4566            # LocalStack Gateway
      - 127.0.0.1:4510-4559:4510-4559  # external services port range
    environment:
      - DEBUG=1
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

~/.aws/config
[profile localstack]
region=us-east-1
output=json
endpoint_url=http://localhost:4566
account_id=000000000000
ec2=http://localhost:4597

~/.aws/credentials
[localstack]
aws_access_key_id=test
aws_secret_access_key=test

### Expected Behavior

https://docs.localstack.cloud/references/coverage/coverage_ec2/ corrected to say `CreateSnapshot` is a PRO feature or the code in this repository is fixed to allow creating snapshots.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal ebs start-snapshot --volume-size 1 --profile localstack

### Environment

```markdown
- OS: Ubuntu 24.04 LTS
- LocalStack: docker compose
  LocalStack version: 4.0.4.dev98
  LocalStack Docker image sha:
  LocalStack build date: 2025-01-10
  LocalStack build git hash: 630b2a111
```
