### ISSUE TITLE
feature: Describe RDS engine default parameters

### ISSUE THREAD

**Issue by adinhodovic** [localstack/localstack#12334]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

I'd like to create DBClusterParameterGroup, but using the rds controller I see the following error:

This is the spec using parameterOverrides.

```
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBClusterParameterGroup
metadata:
  name: test-local
  namespace: tenant
spec:
  description: Parameter group for test-local.
  family: aurora-postgresql16
  name: test-local
  parameterOverrides:
    rds.logical_replication: "1"
    track_commit_timestamp: "1"
```

I see in the localstack logs:

```
The describe_engine_default_parameters action has not been implemented
localstack.request.aws     : AWS rds.DescribeEngineDefaultParameters => 501 (InternalFailure)
```

And the resource does not get created.
