### ISSUE TITLE
bug: LoggingConfig.LogFormat of Lambda function not applied via CloudFormation or SAM

### ISSUE THREAD

**Issue by kakakakakku** [localstack/localstack#12424]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Currently, AWS Lambda supports `LoggingConfig.LogFormat` setting to choose the log format from `Text` or `JSON`.

- https://docs.aws.amazon.com/lambda/latest/api/API_LoggingConfig.html
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-function.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html

Although LocalStack supports `LoggingConfig.LogFormat`, it is not supported when deploying with AWS CloudFormation or AWS SAM.

- AWS CLI: OK🙆‍♂️
- AWS CloudFormation: NG🙅
- AWS SAM: NG🙅

### Expected Behavior

`LoggingConfig.LogFormat` should also be supported in AWS CloudFormation and AWS SAM.

### How are you starting LocalStack?

With the `localstack` script

## AWS CLI

Check `LoggingConfig.LogFormat` attributes👀
`LogFormat` set `JSON`.

```sh
$ awslocal lambda create-function \
  --function-name function-cli \
  --runtime python3.12 \
  --role arn:aws:iam::000000000000:role/function-role \
  --handler app.lambda_handler \
  --zip-file fileb://app.zip \
  --logging-config LogFormat=JSON

$ awslocal lambda get-function-configuration --function-name function-cli
{
    "FunctionName": "function-cli",
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:000000000000:function:function-cli",
    "Runtime": "python3.12",
    "Role": "arn:aws:iam::000000000000:role/function-role",
    "Handler": "app.lambda_handler",
    "CodeSize": 219,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2025-03-22T03:27:01.941729+0000",
    "CodeSha256": "OLn3OOQr7kkPDqZFzMn0oYcoe8QMIB0pG1HTCzwwMe8=",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "fd9447d1-4e9c-49e6-9469-d31d750674ae",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip",
    "Architectures": [
        "x86_64"
    ],
    "EphemeralStorage": {
        "Size": 512
    },
    "SnapStart": {
        "ApplyOn": "None",
        "OptimizationStatus": "Off"
    },
    "RuntimeVersionConfig": {
        "RuntimeVersionArn": "arn:aws:lambda:ap-northeast-1::runtime:8eeff65f6809a3ce81507fe733fe09b835899b99481ba22fd75b5a7338290ec1"
    },
    "LoggingConfig": {
        "LogFormat": "JSON",
        "ApplicationLogLevel": "INFO",
        "SystemLogLevel": "INFO",
        "LogGroup": "/aws/lambda/function-cli"
    }
}
```

## AWS CloudFormation

Check `LoggingConfig.LogFormat` attributes👀
`LogFormat` set `Text`.

```yaml
AWSTemplateFormatVersion: 2010-09-09

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: function-cfn
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: cfn-assets 
        S3Key: app.zip
      Architectures:
        - x86_64
      LoggingConfig:
        LogFormat: JSON
      Role: arn:aws:iam::000000000000:role/role-cfn
```

```sh
$ awslocal cloudformation deploy --stack-name function-cfn --template-file ./cfn-template.yaml

$ awslocal lambda get-function-configuration --function-name function-cfn
{
    "FunctionName": "function-cfn",
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:000000000000:function:function-cfn",
    "Runtime": "python3.12",
    "Role": "arn:aws:iam::000000000000:role/role-cfn",
    "Handler": "lambda_function.lambda_handler",
    "CodeSize": 219,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2025-03-22T03:43:22.492556+0000",
    "CodeSha256": "OLn3OOQr7kkPDqZFzMn0oYcoe8QMIB0pG1HTCzwwMe8=",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "1a553068-ec80-40ef-a7d5-842a5bebe8d2",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip",
    "Architectures": [
        "x86_64"
    ],
    "EphemeralStorage": {
        "Size": 512
    },
    "SnapStart": {
        "ApplyOn": "None",
        "OptimizationStatus": "Off"
    },
    "RuntimeVersionConfig": {
        "RuntimeVersionArn": "arn:aws:lambda:ap-northeast-1::runtime:8eeff65f6809a3ce81507fe733fe09b835899b99481ba22fd75b5a7338290ec1"
    },
    "LoggingConfig": {
        "LogFormat": "Text",
        "LogGroup": "/aws/lambda/function-cfn"
    }
}
```

## AWS SAM

Check `LoggingConfig.LogFormat` attributes👀
`LogFormat` set `Text`.

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: function-sam
      CodeUri: ./src
      Handler: app.lambda_handler
      Runtime: python3.12
      LoggingConfig:
        LogFormat: JSON
```

```sh
$ export AWS_ENDPOINT_URL=http://localhost:4566

$ sam build
$ sam deploy --guided

$ awslocal lambda get-function-configuration --function-name function-sam
{
    "FunctionName": "function-sam",
    "FunctionArn": "arn:aws:lambda:ap-northeast-1:000000000000:function:function-sam",
    "Runtime": "python3.12",
    "Role": "arn:aws:iam::000000000000:role/function-sam-FunctionRole-63d60549",
    "Handler": "app.lambda_handler",
    "CodeSize": 159,
    "Description": "",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2025-03-22T03:29:07.816702+0000",
    "CodeSha256": "KWExRZk35mhNwY2k+bBZIiFCS+PTSqNHR4gJzpyjQ8Q=",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "92a53e77-2dbd-4305-9f93-85a4666cbabf",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip",
    "Architectures": [
        "x86_64"
    ],
    "EphemeralStorage": {
        "Size": 512
    },
    "SnapStart": {
        "ApplyOn": "None",
        "OptimizationStatus": "Off"
    },
    "RuntimeVersionConfig": {
        "RuntimeVersionArn": "arn:aws:lambda:ap-northeast-1::runtime:8eeff65f6809a3ce81507fe733fe09b835899b99481ba22fd75b5a7338290ec1"
    },
    "LoggingConfig": {
        "LogFormat": "Text",
        "LogGroup": "/aws/lambda/function-sam"
    }
}
```

### Environment

```markdown
$ localstack --version
LocalStack CLI 4.2.0
```
