### ISSUE TITLE
Localstack failing to start (0.9.2 and latest)

### ISSUE THREAD

**Issue by adamdavis40208** [localstack/localstack#1298]
```
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Traceback (most recent call last):
localstack_1     |   File "/usr/bin/supervisord", line 11, in <module>
localstack_1     |     sys.exit(main())
localstack_1     |   File "/usr/lib/python3.6/site-packages/supervisor/supervisord.py", line 350, in main
localstack_1     |     options = ServerOptions()
localstack_1     |   File "/usr/lib/python3.6/site-packages/supervisor/options.py", line 439, in __init__
localstack_1     |     existing_directory, default=tempfile.gettempdir())
localstack_1     |   File "/usr/lib/python3.6/tempfile.py", line 298, in gettempdir
localstack_1     |     tempdir = _get_default_tempdir()
localstack_1     |   File "/usr/lib/python3.6/tempfile.py", line 233, in _get_default_tempdir
localstack_1     |     dirlist)
localstack_1     | FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/opt/code/localstack']
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
localstack_1     | Waiting for all LocalStack services to be ready
```

The docker-compose file i'm using:

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4568:4568"
      - "4569:4569"
      - "4561:4561"
      - "9090"
    environment:
      - SERVICES=sqs:4568,s3:4569
      - DEFAULT_REGION=us-west-2
      - PORT_WEB_UI=9090
      - JAVA_TOOL_OPTIONS=-Xmx200M
```

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01
