### ISSUE TITLE
Unable to execute lambda

### ISSUE THREAD

**Issue by alexanderwanyoike** [localstack/localstack#1362]
Hello Im currently having an issue executing lambda.

The create lambda function uploaded a zip file and the localstack mounted volume shows evidence of the zip file being extracted. create function and create alias call didn't throw any corresponding errors.

    lambda_1    | 2019-06-07T12:28:45:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:TestFunction: expected str, bytes or os.PathLike object, not int Traceback (most recent call last):
    lambda_1    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 313, in run_lambda
    lambda_1    |     event, context=context, version=version, asynchronous=asynchronous)
    lambda_1    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 58, in execute
    lambda_1    |     result, log_output = self._execute(func_arn, func_details, event, context, version, asynchronous)
    lambda_1    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 200, in _execute
    lambda_1    |     result, log_output = self.run_lambda_executor(cmd, environment, asynchronous)
    lambda_1    |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 115, in run_lambda_executor
    lambda_1    |     process = run(cmd, asynchronous=True, stderr=subprocess.PIPE, outfile=subprocess.PIPE, env_vars=env_vars)
    lambda_1    |   File "/opt/code/localstack/localstack/utils/common.py", line 854, in run
    lambda_1    |     return do_run(cmd)
    lambda_1    |   File "/opt/code/localstack/localstack/utils/common.py", line 829, in do_run
    lambda_1    |     stderr=stderr_arg, stdout=stdout_arg, env=env_dict, cwd=cwd, preexec_fn=os.setsid)
    lambda_1    |   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    lambda_1    |     restore_signals, start_new_session)
    lambda_1    |   File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    lambda_1    |     env_list.append(k + b'=' + os.fsencode(v))
    lambda_1    |   File "/opt/code/localstack/.venv/lib/python3.6/os.py", line 800, in fsencode
    lambda_1    |     filename = fspath(filename)  # Does type-checking of `filename`.
    lambda_1    | TypeError: expected str, bytes or os.PathLike object, not intMy configuration is as follows

```
lambda:
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda
      - PORT_WEB_UI=8080
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_EXECUTOR=docker
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: on-failure
    ports:
      - 4574:4574
    networks:
      - webnet
    volumes:
      - ./.localstack:/tmp/localstack
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-102) by [Unito](https://www.unito.io/learn-more)
