### ISSUE TITLE
Error: /dev/fd/63: line 1: export: `6DD5EBD2_PORT_3080_TCP_PROTO=tcp': not a valid identifier

### ISSUE THREAD

**Issue by JoeyLuffa** [localstack/localstack#1387]
I am using k8s to deploy the localstack service and the yaml file looks like:
```
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  ports:
    - name: http-dynamodb
      port: 1080
      targetPort: dynamodb
    - name: http-sqs
      port: 2080
      targetPort: sqs
    - name: http-kinesis
      port: 3080
      targetPort: kinesis
    - name: http-s3
      port: 4080
      targetPort: s3
    - name: http-secretsmanager
      port: 5080
      targetPort: secretsmanager
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
 spec:
  replicas: 1
   template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - image: localstack/localstack:latest
        name: localstack
        env:
        - name: SERVICES
          value: "dynamodb,sqs,kinesis,s3,secretsmanager"
        - name: DEBUG
          value: "true"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        ports:
        - containerPort: 4569
          name: dynamodb
          protocol: TCP
        - containerPort: 4576
          name: sqs
          protocol: TCP
        - containerPort: 4568
          name: kinesis
          protocol: TCP
        - containerPort: 4572
          name: s3
          protocol: TCP
        - containerPort: 4584
          name: secretsmanager
          protocol: TCP
```

However, the localstack pod failed to start up and the error message is: 

```
/dev/fd/63: line 1: export: `6DD5EBD2_PORT_3080_TCP_PROTO=tcp': not a valid identifier
```

Any reasons behind this?
PS: it works with localstack/localstack:0.9.0. And starting from localstack/localstack:0.9.1, the error occurs.
