### ISSUE TITLE
CloudFormation does not expose ExportName

### ISSUE THREAD

**Issue by rbu** [localstack/localstack#1408]
Given a CF template that defines outputs as named exports, I expect the "describe-stack" endpoint to include the exported names. With localstack, that is currently not the case.

Example template:
```yaml
  Outputs:
    VPCId:
      Value: {Ref: MyVPC}
      Export:
        Name: My-VPCId

  Resources:
    MyVPC:
      Properties:
        CidrBlock: 10.0.0.0/16
      Type: AWS::EC2::VPC

```

AWS:
```
$ aws cloudformation describe-stacks
...
                {
                    "OutputKey": "VPCId",
                    "OutputValue": "vpc-0123456789",
                    "ExportName": "My-VPCId"
                },

```

localstack:
```
$ aws cloudformation --endpoint-url=http://localhost:4581/ describe-stacks
...
                {
                    "OutputKey": "VPCId",
                    "OutputValue": "vpc-0123456789"
                },
...
```
