### ISSUE TITLE
Discrepancy between actual port-constants vs ports in README

### ISSUE THREAD

**Issue by Jaskaranbir** [localstack/localstack#1458]
I noticed that README specifies different ports than the ones actually present in [constants](https://github.com/localstack/localstack/blob/4fe68f064b2f3d6dff2a102ba2de4793502ccf1b/localstack/constants.py).

For example:

* DynamoDB: README says port is `4569` while its specified as `4564` in [constants](https://github.com/localstack/localstack/blob/4fe68f064b2f3d6dff2a102ba2de4793502ccf1b/localstack/constants.py#L21). I was unable to connect to `4569` port from my application, while `4564` worked.

* Its similar case for S3: README says its port `4572` but in [constants](https://github.com/localstack/localstack/blob/4fe68f064b2f3d6dff2a102ba2de4793502ccf1b/localstack/constants.py#L22) its `4563`. However, the S3 clients still connects on port `4572` successfully, somehow.

It hasn't been very long since I started using this project so I am unsure if this is somehow intentional and somewhere the ports are mapped (couldn't find anything much in source-code's initial skimming though).

This can be the cause of a good number of connection-issues people are talking about. Is this something that should be looked into? I am willing to create a PR if this gets confirmation.

**Comment by whummer** [comment]
Hi @Jaskaranbir , thanks for reporting. Some of the services in LocalStack use two ports - one for the internal/backend API, and one for a frontend proxy that is used to intercept, process, and forward requests. In that sense, what you're seeing is expected, and not a bug in the documentation.

See here for the port mappings of the client-exposed ports: https://github.com/localstack/localstack-python-client/blob/master/localstack_client/config.py#L5-L37

However, the fact that you cannot connect to `4569` is an issue. This is the proxy server for DynamoDB should be accessible. How exactly are you starting LocalStack? Can you access other services on their exposed frontend port?

**Comment by Jaskaranbir** [comment]
Thanks for the response @whummer. I am accessing localstack using Docker, and below is the compose-file:

```YAML
version: '3.7'

services:
  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4560-4590:4560-4590"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
    networks:
      - testnet

networks:
  testnet:
```

Yes, I can access S3 at actual port as mentioned in README. I'll try to test other services too when I get chance, if that'll help.

**Comment by pf22099** [comment]
Have same issue while connecting to Dynamodb in our CI job: 
`Could not connect to the endpoint URL: "http://localhost:4569/"`

It worked fine before but started failing since yesterday.

here is the CI config:
```
- type: run
    name: start localstack
    command: localstack_venv/bin/localstack start
    daemon: true
    env:
      SERVICES: "dynamodb"
- type: run
    name: wait for localstack dynamodb to start up
    command: until localstack_venv/bin/aws --region us-east-1 --endpoint-url=http://localhost:4569 dynamodb list-tables; do sleep 1; done
```

**Comment by radhakr** [comment]
I have the same issue as well. I am unable to connect to Dynamodb, however, I wanted to share an interesting fact that I observed.

My setup is a standard setup of localstack using docker compose for testing my Java application that uses spring-cloud-stream-kinesis (version 1.2.0) for streaming data via Kinesis.

**Works** CLI is able to connect to localstack Dynamodb and perform all actions
**Doesn't work** The app fails when it tries to connect to localstack Dynamodb.

Also on a side note, when I set the localstack version to 0.9.6 the same app (with no changes) works fine.

**Comment by whummer** [comment]
@pf22099 @radhakr Does your CI or local environment support Docker? Please note that version 0.10.0 introduced a breaking change which starts LocalStack in Docker by default. If you want to start it on the host, please use the `--host` flag:
```
- type: run
    name: start localstack
    command: localstack_venv/bin/localstack start --host
    daemon: true
    env:
      SERVICES: "dynamodb"
```

@Jaskaranbir Thanks for posting the config. Your docker-compose stack works for me. After starting the stack, both these commands actually work:
```
awslocal s3 ls
awslocal dynamodb list-tables
```
Not sure how to debug this further. Have you tried pulling the latest version of the image? Are you seeing anything suspicious in the logs?
