### ISSUE TITLE
critical: localstack startup error

### ISSUE THREAD

**Issue by Tochemey** [localstack/localstack#1465]
Hello

I am having the following error anytime I am using it in docker-compose. Please this is not the first time I have seen it reported. Any guidance will help us. This is a wonderful library. I am using docker for mac.

Error:
```
localstack_1               | 2019-08-06T21:06:53:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: /namely-protorepo-descriptor-ops (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2fe0c91d68>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
localstack_1               |     (self._dns_host, self.port), self.timeout, **extra_kw)
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
localstack_1               |     raise err
localstack_1               |   File "/opt/code/localstack/.venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
localstack_1               |     sock.connect(sa)
localstack_1               | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1               |
localstack_1               | During handling of the above exception,
```

**Comment by Deblob12** [comment]
Could you try this Docker-Compose file instead?

```
version: "3"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4568-4597:4568-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,s3,lambda,cloudwatchlogs,iam,sqs,kinesis
      - DEFAULT_REGION=us-west-2
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_EXECUTION_ENV=True
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp"
```
