### ISSUE TITLE
Feature - Operate mocking multiple accounts

### ISSUE THREAD

**Issue by rpattcorner** [localstack/localstack#1498]
We're implementing a cross-account configuration utility, and selecting a mocking framework.  From what I can tell localstack implements a wide range of services, but the scope of the mocking is a single account.  To test that hypothesis (using [localstack-client](https://github.com/localstack/localstack-python-client) I've implemented two sessions and added same-named roles to each.  This should create a name collision failure, but instead creates a consistent set of same-named roles across both sessions.

[digression ... that's probably a defect and should throw a 'RoleExists' exception]

So it looks like all sessions are one, which pretty much prevents using localstack for cross account testing 

:(

Is there a recommended approach for the use case:

* Create a user in account A
* Create a role in account B and allow user to assume it
* Create another role in account C and allow user to assume it

?

I see there are some partly hidden flags on creating sessions for each invocation like `CREATE_NEW_SESSION_PER_BOTO3_CONNECTION` and `CUSTOM_BOTO3_SESSION`, but not much documentation there, and given that session separation doesn't seem to exist, I'm not too hopeful -- they may just be sugar for what I did by hand?

Then there are nasty kludges like settling for just 2 accounts and trying to drive them to different regions.  Could that work in a pinch?

Do we have any capability or experience/doc in dealing with multiple accounts in a test?

pytest_localstack does seem to have some separation for accounts, but sadly does not implement IAM, where the bulk of the work is!

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-111) by [Unito](https://www.unito.io/learn-more)

**Comment by giorgioazzinnaro** [comment]
Also interested in this!
I'd also love to be able to use [AWS Organizations](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html) API to create accounts, OUs, service control policies...

We're doing some work around the *provisioning* of new accounts in an organization with a template (deleting default internet gateway or default VPC, provisioning new VPCs and subnets, attaching transit gateways and creating default roles and IdP and so on) and it's particularly awful to do in AWS because for any account created for tests you have to reset the root password and delete it manually, and yet they still remain in the Organization cluttering it...

**Comment by whummer** [comment]
Thanks for reporting @rpattcorner @giorgioazzinnaro . Multi-account setups are currently not directly supported, but a possible workaround could be to:
* spin up two LocalStack instances
* use different port configurations for the services in the two instances
* configure `TEST_AWS_ACCOUNT_ID` to use different account IDs for the two instances (https://github.com/localstack/localstack/blob/master/localstack/constants.py#L44)

Would that work?

**Comment by giorgioazzinnaro** [comment]
Hey @whummer !

Thanks for the hint!
I think for the work I'm doing this is only partially suitable however..

To better explain my requirement: I am working on a "Landing Zone"/"Account Vending Machine" implementation, and because of that, I actually need to be able to provision accounts via the API, then assume roles from other accounts and execute other actions there.

I'm wondering whether the actual implementation could be the logic you're suggesting? That we simply spin up new localstack instances when triggered via the Organizations API

**Comment by rpattcorner** [comment]
@whummer I've been working on your suggestion to start two stacks (and abandon pytest-localstack), as for unknown reasons the latest `localstack` that pytest_localstack pulls isn't the one with the fix for #2647 .  However I'm working in Python and there seems to be no way to point a localstack session to a particular instance started in docker-compose.  Do you have any thoughts on how to do so?  

Basic code would be:
```
import localstack_client.session

session = localstack_client.session.Session()  #  Magic happens here to point to either localstack_identity or localstack_target below
iam = session.client('iam')
```
An outline of the docker compose would be:
```
version: '2.1'
services:
  localstack_identity:
    image: localstack/localstack:0.11.1
    environment:
      - EDGE_PORT=4566
      - TEST_AWS_ACCOUNT_ID="123456789012"
      - SERVICES=iam
      ...
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack_id"
      - "/var/run/docker.sock:/var/run/docker.sock_id"
  localstack_target:
    image: localstack/localstack:0.11.1
    environment:
      - EDGE_PORT=4567
      - TEST_AWS_ACCOUNT_ID="987654321098"
      - SERVICES=iam
...
```
