### ISSUE TITLE
Invalid bucket name "stack:4572": bucket name must match regex...

### ISSUE THREAD

**Issue by wesselvdv** [localstack/localstack#1506]
Using a different `LOCALSTACK_HOSTNAME` than `localhost` results in an error when trying to deploy a cloudformation stack from a template that is in a bucket. Seems moto has some code that is checking whether or not the s3 hostname is localhost, and if it isn't it's incorrectly discerning the bucket name:

https://github.com/spulec/moto/blob/2fa4d2fb4a9f2bfd7aecf7004d2c6c1a04863283/moto/s3/responses.py#L135

This causes me to have to jump through a few hoops to get localstack and serverless to work in a docker-compose configuration.

UPDATE:

Seems to have nothing to do with the `LOCALSTACK_HOSTNAME` variable, but more with the url referenced in the template itself. If it isn't localhost, or the normal s3.\<region\>.amazonaws.com structure it will incorrectly parse the bucket name and come up with this error.

**Comment by whummer** [comment]
Thanks for reporting @wesselvdv . Any chance you can provide a short CloudFormation template to reproduce this issue? Thanks

**Comment by wesselvdv** [comment]
@whummer I actually didn't use any Cloudformation for this. Atleast not directly, I am using serverless. Here's the basic serverless.yml:

```yaml
service: simulator

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  profile: default

plugins:
  - serverless-localstack

functions:
  simulator: # A Function
    handler: dist/index.handler

resources:
  Resources:
    S3Assets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cws.simulation.results

custom:
  localstack:
    host: http://localhost  # optional - LocalStack host to connect to
    lambda:
      mountCode: False
```

BIggest requirement is running serverless from inside a docker container, and having localstack inside another. This results in a different localstack url than localhost, hence the error.
