### ISSUE TITLE
One port to rule them all: Single endpoint with routing to configured services

### ISSUE THREAD

**Issue by ofirnk** [localstack/localstack#151]
Using `localstack` and mocking an AWS service is a pleasure.
Our problem begin when we want to mock few services:
Configuring each becomes a mess.

Exposing a single port that will route requests based on service request would make the whole stack much similar to AWS infra.

WDYT?

**Comment by whummer** [comment]
Hi @ofirnk , generally that's a great proposal, but the implementation is not straight-forward. It becomes a bit tricky if you take the following two key assumptions (which we currently take as a given):
* **Assumption 1**: We want to ensure compatibility with existing AWS CLIs/SDKs,
and
* **Assumption 2**: We do _not_ want to rely on local DNS configurations/workarounds (i.e., it LocalStack should work out of the box, without having to change the local `/etc/hosts` file or similar).

If we use a single port, then the routing you are proposing can basically only work with either of the following techniques:
* **Option A**: Use a custom HTTP header (or custom URL path prefix) to specify the service type
or
* **Option B**: Use a custom domain name to address the different services.

Option A breaks Assumption 1, whereas Option B breaks Assumption 2. 

There is a also another related discussion going on here: https://github.com/localstack/localstack/issues/140

When you say it becomes a mess, which part particularly are you referring to? Which programming languages are you accessing LocalStack from? Maybe we can find another workaround (e.g., client library wrappers) to make things a bit cleaner.

**Comment by ofirnk** [comment]
What I was thinking is a routing from - lets say - port 4444 to any of the other ports.
That could be a python proxying service that would parse the headers/content of the request and would forward it to the configured service, like 4576 for sqs.

This way, there's no DNS workaround needed, and it still works with current solutions.

I'm not familiar so much with AWS headers/request content - do you find it plausible to be implemented this way?

**Comment by ofirnk** [comment]
Adding to last comment - implementing a request log will enable a (very) naive data persistency by replaying all http call on service start 
Connected to #151

**Comment by whummer** [comment]
Good point. We'd still need to do a full analysis for all services, but I believe that in *most* cases it should be possible to determine the target service based on request headers and/or payload.

But again, before starting to tackle this work, we should first validate our assumptions and make sure that we're not running into edge cases that will invalidate the entire approach.

**Comment by ofirnk** [comment]
How about running a transparent proxy with logs enabled?
If run on the full exposed port range and running the full test suite, that
will give a fair (or full?) amount of the possible request and how they
look in terms of headers, query params etc'...

**Comment by kristofferostlund** [comment]
I'm interested in this too, and it _should be possible_ since it's possible to do this `moto` in its standalone mode where one doesn't supply any service. E.G. when started something like this (probably works fine without the flags, but I haven't tested without them myself):

```
moto_server -p 3000 -H 0.0.0.0
```

If I'm not mistaken, they've managed to do this in a _fairly_ straightforward way [here](https://github.com/spulec/moto/blob/master/moto/server.py#L50), or am I missing something?

**Comment by cristiangrama** [comment]
@ofirnk I have something similar to your idea but using traefik (https://traefik.io/). With my configuration I am able to give it a custom domain for each service and thus not relying on the ports. It looks like this
```
localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sns:4575,sqs:4576,dynamodb:4577
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    labels:
      traefik.enable: true

      traefik.dashboard.backend: dashboard.localstack
      traefik.dashboard.frontend.rule: Host:dashboard.localdomain
      traefik.dashboard.port: 8080

      traefik.sns.backend: sns.localstack
      traefik.sns.frontend.rule: Host:sns.localdomain
      traefik.sns.port: 4575

      traefik.sqs.backend: sqs.localstack
      traefik.sqs.frontend.rule: Host:sqs.localdomain}
      traefik.sqs.port: 4576

      traefik.dynamodb.backend: dynamodb.localstack
      traefik.dynamodb.frontend.rule: Host:dynamodb.localdomain}
      traefik.dynamodb.port: 4577
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack/data
```

**Comment by mhmoudgmal** [comment]
@whummer as I depend a lot on localstack locally I was trying to build a simple proxy server as single endpoint that routes the aws requests to the corresponding localstack services, it seems to be working however I'm open for feedback and suggestions! Thanks

**Comment by geoffwright** [comment]
I recently started using localstack with ansible and hit problems with multiple endpoints and ended up here. All the fault of ansible modules that need to contact two service but only allow for one endpoint to be defined.

I've got around this by adding a haproxy container to docker compose with a very [basic config](https://gist.github.com/geoffwright/43ce420dc3f3f6a688aca029043c0b30) which does the job and can be added to with other services as needed

**Comment by whummer** [comment]
Quick update @ofirnk @kristofferostlund @mhmoudgmal @geoffwright @cristiangrama

A major change has been added in #2250 . Starting with version `0.11.0`, all APIs are now exposed via a single _edge service_, which is accessible on http://localhost:4566 by default (see updated instructions in the [README](https://github.com/localstack/localstack#overview)).

Can you please give it a try with the `latest` version of the Docker image, and report here if there are any issues accessing the services via the edge URL http://localhost:4566 . Thanks

**Comment by kristofferostlund** [comment]
> Can you please give it a try with the `latest` version of the Docker image, and report here if there are any issues accessing the services via the edge URL http://localhost:4566 . Thanks

(sorry for the late response, it's been a busy few weeks...) I can give it a spin this weekend! I've switched workplaces and we currently don't use AWS at work

**Comment by kristofferostlund** [comment]
@whummer I tried a few endpoints for `s3`, `dynamodb`, and  `sqs` with great results! Nicely done!

**Comment by cristiangrama** [comment]
@kristofferostlund Can you share exactly how you are hitting the different endpoints?

**Comment by kristofferostlund** [comment]
@cristiangrama For the simple test I had a setup like:

```yaml
# docker-compose.yaml
version: '2.0'

services:
  aws-mock:
    image: localstack/localstack:0.11.0
    environment:
      EDGE_PORT: 4566
      SERVICES: s3,dynamodb,sqs
      DEFAULT_REGION: eu-central-1
    ports:
      - 4566:4566
```

Which I ran with `docker-compose up -d` so it's running in the background.

And then the test app looked something like:

```js
// app.js
const s3Client = require('./s3')
const dynamoDBClient = require('./dynamodb')
const sqsClient = require('./sqs')

async function main() {
  const config = {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    endpoint: process.env.AWS_ENDPOINT,
    region: process.env.AWS_REGION,
  }

  const s3 = s3Client(config)
  const dynamoDB = dynamoDBClient(config)
  const sqs = sqsClient(config)

  let buckets = await s3.listBuckets()
  if (buckets.length === 0) {
    console.log('No buckets found, creating bucket!')
    s3.createBucket('test-bucket')

    buckets = await s3.listBuckets()
  }

  for (const bucket of buckets) {
    console.log(`There's a bucket called: ${bucket.name}`)
  }

  let tables = await dynamoDB.listTables()
  console.log({ tables })

  let queues = await sqs.listQueues()
  if (queues.length === 0) {
    await sqs.createQueue('test-queue')
    queues = await sqs.listQueues()
  }

  for (const queue of queues) {
    console.log(`There's a queue called ${queue}`)
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})

```

```js
//dynamodb.js
const { DynamoDB } = require('aws-sdk')

module.exports = ({ accessKeyId, secretAccessKey, endpoint, region }) => {
  const db = new DynamoDB({ accessKeyId, secretAccessKey, endpoint, region })

  const listTables = async () => {
    const response = await db.listTables().promise()
    return response.TableNames.map((table) => ({ name: table }))
  }

  return { listTables }
}

```

```js
// s3.js
const { S3 } = require('aws-sdk')

module.exports = ({ accessKeyId, secretAccessKey, endpoint, region }) => {
  const s3Options = { accessKeyId, secretAccessKey, endpoint, region }
  if (endpoint != null && endpoint.includes('localhost')) {
    s3Options.s3ForcePathStyle = true
  }

  const s3 = new S3(s3Options)

  const createBucket = async (name) => {
    await s3.createBucket({ Bucket: name }).promise()

    return true
  }

  const listBuckets = async () => {
    const response = await s3.listBuckets().promise()

    return response.Buckets.map((bucket) => ({ name: bucket.Name, createdAt: bucket.CreationDate }))
  }

  const list = async (bucket) => {
    const response = await s3.listObjectsV2({ Bucket: bucket }).promise()

    return response.Contents.map((item) => ({
      bucket: bucket,
      key: item.Key,
      eTag: item.ETag,
      changedAt: item.LastModified,
      size: item.Size,
    }))
  }

  return { createBucket, listBuckets, list }
}
```

```js
// sqs.js
const { SQS } = require('aws-sdk')

module.exports = ({ accessKeyId, secretAccessKey, endpoint, region }) => {
  const sqs = new SQS({ accessKeyId, secretAccessKey, endpoint, region })

  const createQueue = async (name) => {
    await sqs.createQueue({ QueueName: name }).promise()

    return true
  }

  const listQueues = async () => {
    const response = await sqs.listQueues().promise()
    return response.QueueUrls || []
  }

  return { createQueue, listQueues }
}
```
