### ISSUE TITLE
S3 doesn't work behind a reverse proxy with rewrite rules

### ISSUE THREAD

**Issue by zombor** [localstack/localstack#1538]
Hello-

I'm trying to use localstack inside a local deployment of kubernetes exposing the services via an Istio `VirtualService`:

```
spec:
  gateways:
  - test
  hosts:
  - test.test
  - match:
    - uri:
        prefix: /s3
    rewrite:
      uri: /
    route:
    - destination:
        host: test-localstack
        port:
          number: 4572
```

This exposes the localstack service running inside the kubernetes cluster to the host machine on `http://test.test/s3`, proxies that request to the localstack container's `4572` port and rewrite the path to `/` (since localstack won't work with the `/s3` url path of course).

This works fine for many services in localstack since they don't use path based routing. However when using S3 commands like `aws --endpoint-url http://test.test/s3 s3 ls s3://test`, this causes the following error:

```
2019-09-04T14:18:25:ERROR:localstack.services.generic_proxy: Error forwarding request: list index out of range Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 227, in forward
    path=path, data=data, headers=forward_headers)
  File "/opt/code/localstack/localstack/services/s3/s3_listener.py", line 515, in forward_request
    bucket = path.split('/')[1]
IndexError: list index out of range
```

This is because the path getting fed into the s3 service ends up being `//test` and the bucket parsing fails on this. There's also many other places where the path is being parsed to determine names that will also fail when the path starts with `//`.

I suspect this is the case for any reverse proxy that is put in front of localstack that rewrites the URI.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-116) by [Unito](https://www.unito.io/learn-more)
