### ISSUE TITLE
Does LocalStack support nested CloudFormation Templates?

### ISSUE THREAD

**Issue by soynog** [localstack/localstack#1566]
Hi, I'm trying to get LocalStack set up for integration testing and having a lot of trouble building CloudFormation templates that include nested stacks referenced via the `TemplateURL` property. Is this just not a thing that works in LocalStack? I've tried setting TemplateURL to a local file as well as to an object in an S3 bucket created with LocalStack.

For example if I call `create-stack` on a `template.yaml` containing the following:
```
Resources:
  SNSTopics:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://localhost:4572/artifacts/sns.yaml
```

...the stack builds but the referenced `sns.yaml` stack does not get built; whereas if I call `create-stack` directly on the referenced file it builds fine.

Thanks for any help/advice you can give!
