### ISSUE TITLE
Unable to parse cloudformation template

### ISSUE THREAD

**Issue by Tasemu** [localstack/localstack#1572]
Hi, i have a cloudformation template that is not working with localstack. It works fine until I add this block, after much commenting out of lines, i have worked out that is creates the stack fine as long as I do not have the lines containing !FindInMap... This looks totally fine to be but localstack breaks and throws an unable to parse error.

It is also worth noting that I am using the same block of code under LogGroupName in another resource and it is working totally fine. It just seems to be for the Log Group resource.

```
# SEEMS AS THOUGH FINDINMAP IS BREAKING THIS
  HeartbeatHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - FooHandler
    Properties:
      RetentionInDays: !Ref FooRetention
      LogGroupName:
        Fn::Join:
          - '_'
          - - '/aws/lambda/AWS_DUB_LAM'
            - !FindInMap [ AccountInfo, !Ref "AWS::AccountId", ID ]
            - !If [ FeatureBranch, !Ref "gitBranch", !Ref "AWS::NoValue" ]
            - 'MessageFooHandler'
            - !FindInMap [ AccountInfo, !Ref "AWS::AccountId", ENV ]

# HOWEVER THIS RESOURCE IS WORKING WITH THE SAME LOGGROUPNAME
  LogGroupSubscriptionHeartbeatService:
    Type: AWS::Logs::SubscriptionFilter
    DependsOn:
      - FooLogGroup
    Properties:
      DestinationArn: !Ref MessageServicelogFooArn
      FilterPattern: ''
      LogGroupName:
        Fn::Join:
          - '_'
          - - '/aws/lambda/AWS_DUB_LAM'
            - !FindInMap [ AccountInfo, !Ref "AWS::AccountId", ID ]
            - !If [ FeatureBranch, !Ref "gitBranch", !Ref "AWS::NoValue" ]
            - 'MessageFooHeartbeatHandler'
            - !FindInMap [ AccountInfo, !Ref "AWS::AccountId", ENV ]
```
