### ISSUE TITLE
Layers no longer work in localstack pro

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1672]
Layers are listed as supported, and I'm fairly sure they used to work.

Layers don't work when deployed via cloudformation (and by extension, serverless).

The following `serverless.yml` errors out with error code `500`:
```yaml
service: "layertest"

provider:
  name: "aws"
  runtime: "nodejs10.x"
functions:
  hello:
    handler: "handler.hello"
    layers:
      - "{ Ref: TestLambdaLayer }"

layers:
  TestLambdaLayer:
    path: "l"

plugins:
  - "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```

On the localstack end `Exception: CloudFormation deployment for resource type Lambda::LayerVersion not yet implemented` is outputted.
