### ISSUE TITLE
Unable to deploy custom Gateway Responses via Cloudfront

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1675]
The following example `serverless.yml` fails to deploy on localstack:

```yaml
service: "localtest"

provider:
  name: "aws"
  runtime: "nodejs10.x"

functions:
  hello:
    handler: "handler.hello"
    
resources:
  Resources:
    ApiGatewayRestApi:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
        Name: "${self:provider.stage}-${self:service}"
    GatewayResponseDefault400:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: "DEFAULT_4XX"
        ResponseTemplates:
          application/json: '{"errors":[{"message":"Custom text."}]}'
    GatewayResponseUnauthorized:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: "UNAUTHORIZED"
        ResponseTemplates:
          application/json: '{"errors":[{"message":"Custom text!", "extra":"Some extra info"}]}'
    GatewayResponseDefault500:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: "DEFAULT_5XX"
        ResponseTemplates:
          application/json: '{"errors":[{"message":$context.error.messageString}]}'
    GatewayResponseIntegrationTimeout:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: "INTEGRATION_TIMEOUT"
        ResponseTemplates:
          application/json: '{"errors":[{"message":$context.error.messageString}]}'

plugins:
- "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```

The error on the localstack end is `Exception: CloudFormation deployment for resource type ApiGateway::GatewayResponse not yet implemented`.
