### ISSUE TITLE
Cannot deploy lambdas with cron schedules

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1676]
The following example `serverless.yml` fails to deploy on localstack:

```yaml
service: "localtest"

provider:
  name: "aws"
  runtime: "nodejs10.x"

functions:
  hello:
    handler: "handler.hello"
    events:
      - schedule: "cron(0 * * * ? *)"

plugins:
- "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```

The error on the localstack end is `CloudFormation deployment for resource type Events::Rule not yet implemented`.
