### ISSUE TITLE
When deploying a service with errors using a custom deployment bucket, lambdas appear to already exist

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1677]
When trying to deploy a serverless service that does not currently deploy correctly onto localstack using a custom deployment bucket, the lambdas seems to be created regardless (???) but not as part of the stack, with localstack outputting `botocore.errorfactory.ResourceConflictException: An error occurred (ResourceConflictException) when calling the CreateFunction operation: Function already exist` .

For example, the `serverless.yml` below would currently fail to deploy due to  #1676 , but because a `deploymentBucket` was added, it will instead fail due to `Function already exist`. Subsequently removing `deploymentBucket` or even `events` from the the file will not allow it to deploy - it will fail until localstack is restarted ( or until the lambda is manually deleted?).

I've also reproduced this with services suffering from #1675. 

```yaml
service: "localtest"

provider:
  name: "aws"
  runtime: "nodejs10.x"
  deploymentBucket:
    name: "testbucket"

functions:
  hello:
    handler: "handler.hello"
    events:
      - schedule: "cron(0 * * * ? *)"

plugins:
- "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```

**Comment by whummer** [comment]
Hi @Jaystified , can you please try with the `latest` version. When I try to deploy your sample in a fresh LocalStack instance, I get a `ServerlessError: Could not locate deployment bucket. Error: The specified bucket does not exist` (which is expected).

It does work, however, if `serverless-deployment-bucket` gets added to the list of plugins:
```
plugins:
  - serverless-localstack
  - serverless-deployment-bucket
```

**Comment by Jaystified** [comment]
I should've clarified: The deployment bucket should actually exist in localstack (I create it using `awslocal s3api create-bucket --bucket testbucket` before using `sls deploy`).

The issue is still present with the latest version (it seems to require another error to manifest). 

The following `serverless.yml` will reproduce it with today's update(using #1675):

```yaml
service: "localtest"

provider:
  name: "aws"
  runtime: "nodejs10.x"
  deploymentBucket:
    name: "testbucket"

functions:
  hello:
    handler: "handler.hello"

resources:
  Resources:
    ApiGatewayRestApi:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
        Name: "${self:provider.stage}-${self:service}"
    GatewayResponseDefault400:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        RestApiId:
          Ref: "ApiGatewayRestApi"
        ResponseType: "DEFAULT_4XX"
        ResponseTemplates:
          application/json: '{"errors":[{"message":"Custom text."}]}'

plugins:
  - "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```

**Comment by Jaystified** [comment]
This issue also comes up with #1682 . 
The main problem with this issue is that is hides other problems and makes debugging difficult.

**Comment by Jaystified** [comment]
I am still experiencing this issue.

Here's another example:
```yaml
service: "localtest"

provider:
  name: "aws"
  runtime: "nodejs10.x"
  deploymentBucket:
    name: "testbucket"

functions:
  hello:
    handler: "handler.hello"
    events:
    - sns:
        arn: "arn:aws:sns:us-west-2:111111111:foo"
plugins:
  - "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```
The `testbucket` bucket is created beforehand.
The SNS topic is **NOT** created and is left missing on purpose.

On AWS, this fails to deploy due to a validation error.
On localstack it is a generic "500" due to "Function already exist".
