### ISSUE TITLE
API Gateway unable to find any integrations

### ISSUE THREAD

**Issue by Jaystified** [localstack/localstack#1727]
With today's update, API Gateway consistently fails to find any of its' defined paths.

For example, the following `serverless.yml` :
```yaml
service: "localtest"

provider:
  name: "aws"
  runtime: "nodejs10.x"

functions:
  hello:
    handler: "handler.hello"
    events:
      - http:
          path: "/"
          method: "get"
          integration: "lambda-proxy"
      - http:
          path: "/test"
          method: "get"
          integration: "lambda-proxy"
plugins:
  - "serverless-localstack"

custom:
  localstack:
    stages:
      - "local"
```

If deployed, will result in the following:
```
~$ sls deploy --stage local
Serverless: Using serverless-localstack
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service localtest.zip file to S3 (3.02 KB)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.
Serverless: Stack update finished...
Service Information
service: localtest
stage: local
region: us-east-1
stack: localtest-local
resources: 11
api keys:
  None
endpoints:
  GET - http://localhost:4567/restapis/sz3ijrff91/local/_user_request_/
  GET - http://localhost:4567/restapis/sz3ijrff91/local/_user_request_/test
functions:
  hello: localtest-local-hello
layers:
  None
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
~$ curl http://localhost:4567/restapis/sz3ijrff91/local/_user_request_/
{"message": "Unable to find integration for path /restapis/sz3ijrff91/local/_user_request_/"}
~$ curl http://localhost:4567/restapis/sz3ijrff91/local/_user_request_/test
{"message": "Unable to find integration for path /restapis/sz3ijrff91/local/_user_request_/test"}
```
