### ISSUE TITLE
CloudFormation - S3 notification configuration not created

### ISSUE THREAD

**Issue by pejta2207** [localstack/localstack#1752]
Hello,

I'm trying to create an S3 bucket with Notification Configuration (S3 event to SQS on object creation). However, even though I am able to create S3 events with aws cli, I cannot make this work with CloudFormation.

What I did was create two separate CloudFormation templates, to make sure that it's not a problem with dependencies:

**Queue template**
```
Resources:
  TestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: test-queue
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600
```

**Bucket template**
```
Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test-bucket
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: arn:aws:sqs:us-east-1:000000000000:test-queue
```

Unfortunately, queue and bucket are created, but no bucket notification configuration is present on the bucket.

Is this feature supported with CloudFormation? Or maybe I am missing something? Thanks!
