### ISSUE TITLE
ERROR no module handler using serverless-python-requirements

### ISSUE THREAD

**Issue by szdrasiak** [localstack/localstack#1757]
Hey, I'm want to use `localstack` to test lambda localy, I can deploy and invoke lambdas with standard python libraries, but when I'm using `serverless-python-requirements` to pack for example `requests`, `pandas` etc, I can deploy lambda without any problems but when I try to invoke it I'm getting:

`[ERROR] Runtime.ImportModuleError: Unable to import module 'handler': No module named 'handler'`

```
service: lambda-worker

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  stage: ${opt:stage, 'local'}


plugins:
  - serverless-python-requirements
  - serverless-localstack
  - serverless-package-external
custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
  localstack:
    stages:
      - local
    host: http://localhost

    lambda:
      mountCode: False
  stages:
    - local
    - prod
  packageExternal:
    external:
      - '../common'

package:
  individually: true

functions:
  main:
    handler: handler.main
    events:
      - sqs: arn:aws:sqs:us-east-1:000000000000:qwe-queue
    environment:
      DB_SECRET_ARN: arn:aws:secretsmanager:us-east-1:000000000:secret:dbSecret
      AWS_STORAGE_BUCKET_NAME: qwe
```
