### ISSUE TITLE
Add flag to enable/disable removal of Docker containers after Lambda execution

### ISSUE THREAD

**Issue by ciaranevans** [localstack/localstack#1851]
Having upgraded to the latest LocalStack version, I've noticed that Docker containers from Lambda executions are immediately removed when they terminate.

This was added in https://github.com/localstack/localstack/pull/1584

I can appreciate the need to clean up containers, however this feature of having them stay up is actually very useful for debugging things when they go wrong!

Would it be possible to have a flag so that when running LocalStack we can specify whether to remove containers on completion? Something like:

```
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4593:4567-4593"
    environment:
      - SERVICES=serverless,ssm,stepfunctions
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - REMOVE_CONTAINERS_ON_LAMBDA_TERMINATE=true #(or false)
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Thanks for the great work folks!
