### ISSUE TITLE
Is it possible to seed KMS?

### ISSUE THREAD

**Issue by matthew-gill** [localstack/localstack#1871]
@whummer thanks so much for adding KMS to localstack!

A quick question on key seeding. AFAIK, there's no way to create keys with a specific KeyId. Which means I need to make changes each time to my local set up to point to the generated ARN for the KMS key.

In @nsmithuk 's local-kms which I believe this service uses, it was possible to specify a `seed.yml` file which would allow me to manually specify the KeyId / ARN.

Any ideas on how I can specify a KeyId during creation?

**Comment by nsmithuk** [comment]
Hi @matthew-gill 

I've not given this a try in the context of localstack, but the local-kms binary will look for a seeding file at `/init/seed.yaml` by default. This might be as simple as mounting your seeding file to that path within the localstack container.

**Comment by matthew-gill** [comment]
> Hi @matthew-gill
> 
> I've not given this a try in the context of localstack, but the local-kms binary will look for a seeding file at `/init/seed.yaml` by default. This might be as simple as mounting your seeding file to that path within the localstack container.

Heh! It works... definitely should've tried that first! Thanks :)

**Comment by matthew-gill** [comment]
Follow up question @nsmithuk I need to make sure I can persist my kms data in locastack.
I see that in your documentation you can specify `DATA_PATH` as an environment variable.

It appears as if localstack honours this... although I'm concerned that this'll likely change in the future to something KMS specific. Any ideas on how to ensure that data is always going to be persisted?

For now I've set up my docker-compose to look like this:

```
services:
    localstack:
        image: localstack/localstack
        ports:
            - "8000:8080"
        environment:
            - SERVICES=sqs,kms
            - HOSTNAME=localstack
            - DEFAULT_REGION=eu-west-1
            - DATA_PATH=/kms/data
        volumes:
            - ./docker/config/localstack:/docker-entrypoint-initaws.d
            - ./docker/config/kms/seed.yaml:/init/seed.yaml
            - kms-data:/kms/data
```
