### ISSUE TITLE
Elasticsearch not starting up in latest version

### ISSUE THREAD

**Issue by AntonFagerberg** [localstack/localstack#1881]
This is our docker-compose
```
  localstack:
    image: localstack/localstack
    container_name: localstack-dimr
    ports:
      - "8000:4569"
      - "8001:4571"
    environment:
      - SERVICES=dynamodb,es
      - DEFAULT_REGION=eu-west-1
      - START_WEB=0
```

When running localstack `0.10.6` we get this output:

```
Starting mock DynamoDB (http port 4569)...
Starting local Elasticsearch (http port 4571)...
Starting mock ES service (http port 4578)...
```

When running the latest version (published 12/18/2019 at 11:35 pm) Elasticsearch is missing

```
Starting mock DynamoDB (http port 4569)...
Starting mock ES service (http port 4578)...
```

Is this a bug or do we have to change our docker-compose some how? Perhaps related to #1865?
