### ISSUE TITLE
Localstack with Testcontainers - Amazon SNS - Topic does not exists - Unable to Send SMS 

### ISSUE THREAD

**Issue by piotrmackowiak** [localstack/localstack#1882]
There is is impossible to send SMS with testcontainer because of

com.amazonaws.services.sns.model.NotFoundException: Topic does not exist (Service: AmazonSNS; Status Code: 404; Error Code: NotFound; Request ID: 193cc1a7)

the problem is that original amazon sdk does not require topic to do this. Here is source code what works correctly with Amazon SDK (and not with testcontainer)

PublishResult publishResult = amazonSNS.publish(new PublishRequest() .withMessage(smsMessage.getFormattedMessage()) .withPhoneNumber(smsMessage.getPhoneNumber()) .withMessageAttributes(smsConfigurationAttributes) );

Amazon SDK version: 1.11,642
Testcontainers version: 1.12.3

**Comment by natflow** [comment]
I had a similar issue and it was fixed by passing a `AWS_DEFAULT_REGION` env var to the `localstack` container that matched my code's expectations:

```yaml
  app:
    # ...
    environment:
      AWS_DEFAULT_REGION: us-west-1

  localstack:
    image: localstack/localstack
    environment:
      AWS_DEFAULT_REGION: us-west-1
```
