### ISSUE TITLE
java.lang.NoSuchMethodError: DynamodbStreamRecord.setUserIdentity

### ISSUE THREAD

**Issue by rrjavadev** [localstack/localstack#1960]
While trying to trigger a lambda written in Java using DynamoDB stream, I am receiving the following error.

```
localstack_1  | Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.services.lambda.runtime.events.DynamodbEvent$DynamodbStreamRecord.setUserIdentity(Lcom/amazonaws/services/dynamodbv2/model/Identity;)V
localstack_1  |         at cloud.localstack.lambda.DDBEventParser.parse(DDBEventParser.java:29)
localstack_1  |         at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:103)
```

In the cloud formation template, this is how the DynamoDB table has been configured.

```
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}-${mytablename}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: version
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: TRUE
```

And the event source is configured as given below.

```
  FunctionEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      Enabled: true
      StartingPosition: LATEST
      EventSourceArn: !GetAtt MyTable.StreamArn
      FunctionName: !Ref JavaFunction
```

And the java function is configured as:

```
  JavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Service}-${Env}"
      AutoPublishAlias: LIVE
      DeploymentPreference:
        Type: Globals.DEPLOY_STRATEGY
      Handler: com.xyz.EventLocalHandler
      Runtime: java8
      Timeout: 240
      MemorySize: 1024
      Tracing: Active
      CodeUri:
        Bucket: my-bucket
        Key: my-lambda.zip
      Environment:
        Variables:
          ENV: !Sub "${Env}"
```

All the services are up and running in Localstack. I can see the table, put value into the DB and this in turn triggers the lambda without any errors. One warning that appears in the log is given below.

```
localstack_1  | 2020-01-17T10:57:49:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.dynamodb2.models.Table'>
```

I am not sure whether this will cause any problem.

After searching online, I found that Localstack is trying read userIdentity attribute present in Record.java object.
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/Record.html

However I am not sure how we can explicitly set this value. In the real AWS world it is not necessary to set this value in the cloud formation script. Still the event in DynamoDB stream triggers the lambda and get's processed successfully. This only happens in Localstack.

Request your advice on this.

Edited: I am using 1.11 version of aws sdk. Localstack is using 2.x versions. That could be why this problem is occurring. I will troubleshoot this.

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-147) by [Unito](https://www.unito.io/learn-more)
