### ISSUE TITLE
Dashboard does not work when only some resources are deployed.

### ISSUE THREAD

**Issue by theskipster** [localstack/localstack#205]
WIth the following docker-compose service definition, the services come up, but the dashboard has nothing in it.

![screen shot 2017-07-26 at 10 14 19 am](https://user-images.githubusercontent.com/1102888/28625774-42e9f6e6-71eb-11e7-90b1-a0b61521290f.png)

Dockerfile
```
FROM localstack/localstack
```
docker-compose.yaml
```yaml
  aws:
    build: ./mycompany-aws
    image: mycompany-aws:v1
    container_name: mycompany-v1-aws
    env_file: .env # A bunch of variables used in the container
    environment:
      - SERVICES=sqs,s3
      - DEFAULT_REGION=us-east-1
    ports:
      # - "4567:4567" # API Gateway
      # - "4568:4568" # Kinesis
      # - "4569:4569" # DynamoDB
      # - "4570:4570" # DynamoDB Streams
      # - "471:4571" # ElasticSearch
      - "4572:4572" # S3
      # - "4573:4573" # Firehose
      # - "4574:4574" # Lambda
      # - "4575:4575" # SNS
      - "4576:4576" # SQS
      # - "4577:4577" # RedShift
      - "8080:8080" # Dashboard - NOT WORKING
    labels:
      - com.mycompany.name.pretty=aws
```
