### ISSUE TITLE
Is it possible to create Resource of type AWS::Serverless::Application and access its Outputs attributes from template in Localstack?

### ISSUE THREAD

**Issue by patelatharva** [localstack/localstack#2079]
I have my serverless.yml with following content. I am using LocalStack to emulate aws stack

```
service: blah
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-localstack
custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    autostart: true  # optional - start LocalStack in Docker on Serverless deploy
    endpoints:
      # This section is optional - can be used for customizing the target endpoints
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
    lambda:
      # Enable this flag to improve performance
      mountCode: false
    docker:
      # Enable this flag to run "docker ..." commands as sudo
      sudo: false   
resources:
  Resources:
    MyLambdaEdgeProtectedSpaSetup:
      Type: AWS::Serverless::Application
      Properties:
        Location: "template.yaml"
          # ApplicationId: uri of the application id on aws app repository
          # SemanticVersion: blah blah
    AlanTuring:
      Type: AWS::Cognito::UserPoolUser
      Properties:
        Username: alan.turing@example.com
        UserPoolId: !GetAtt MyLambdaEdgeProtectedSpaSetup.Outputs.UserPoolId
    EdsgerDijkstra:
      Type: AWS::Cognito::UserPoolUser
      Properties:
        Username: edgser.dijkstra@example.com
        UserPoolId: !GetAtt MyLambdaEdgeProtectedSpaSetup.Outputs.UserPoolId

  Outputs:
    MySpaS3Bucket:
      Description: The S3 Bucket into which my SPA will be uploaded
      Value: !GetAtt MyLambdaEdgeProtectedSpaSetup.Outputs.S3Bucket
```

Here the localstack logs is showing error while accessing MyLambdaEdgeProtectedSpaSetup.Outputs.UserPoolId attributes. Is localstack able to create application from template.yaml that describe application in SAM formation languge?

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-156) by [Unito](https://www.unito.io/learn-more)
