### ISSUE TITLE
Cloudformation "Conditionals" support

### ISSUE THREAD

**Issue by ndpratas** [localstack/localstack#2083]
I was testing Localstack's cloudformation support and bumped into a problem regarding the use of "Conditions". It seams to me that Localstack is ignoring "Conditions" in resources, thus creating and validating them regardless if the contition returns true or false.

**EXAMPLE:**

template.yml snippet:
```
"
(...)
Parameters:
  MyTestSNSTopicArn:
    Description: Arn of SNS topic
    Type: String
    Default: ""
(...)
Conditions:
#Check if is Production by AccountID
  IsPRD:
    Fn::Equals:
    - !Ref "AWS::AccountId"
    - xxxxxxxxxxxxxx
(...)
Resources:
  MyTestSubscription:
    Type: 'AWS::SNS::Subscription'
    Condition: IsPRD
    Properties:
      TopicArn: !Ref MyTestSNSTopicArn
      Endpoint: !GetAtt MyTestSQSQueue.Arn
      Protocol: sqs
      RawMessageDelivery: 'false'
(...)

"
```

When I try to deploy this stack:
1st - I get the error that the "MyTestSNSTopicArn" ARN does not exist, which is correct (because I'm not in PRD therefore I don't even have the topic to subscribe) but it should deploy anyway because the Condition should return false.

```
localstack_1            | 2020-02-24T14:57:32:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "MyTestSubscription": Parameter validation failed:
localstack_1            | Missing required parameter in input: "TopicArn" Traceback (most recent call last):
localstack_1            |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 185, in parse_and_create_resource
localstack_1            |     return _parse_and_create_resource(logical_id, resource_json,
localstack_1            |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 287, in _parse_and_create_resource
localstack_1            |     result = deploy_func(logical_id, resource_map_new, stack_name=stack_name)
localstack_1            |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 823, in deploy_resource
localstack_1            |     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
localstack_1            |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 849, in execute_resource_action
localstack_1            |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name)
localstack_1            |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 922, in configure_resource_via_sdk
localstack_1            |     raise e
localstack_1            |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 919, in configure_resource_via_sdk
localstack_1            |     result = function(**params)
localstack_1            |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_1            |     return self._make_api_call(operation_name, kwargs)
localstack_1            |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 598, in _make_api_call
localstack_1            |     request_dict = self._convert_to_request_dict(
localstack_1            |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 646, in _convert_to_request_dict
localstack_1            |     request_dict = self._serializer.serialize_to_request(
localstack_1            |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
localstack_1            |     raise ParamValidationError(report=report.generate_report())
localstack_1            | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack_1            | Missing required parameter in input: "TopicArn"
```

2nd - Then if I assign a valid ARN to "MyTestSNSTopicArn" it deploys the stack but the resource gets deployed as well (and it shouldn't because, again, the condition returns false). 
I validated resource creation by running "awslocal sns list-subscriptions" command and seeing the subscription resource in the output.

As an additional test I deployed the same cloudformation template in real AWS and got the expected result: If conditional returns false the resource DOES NOT get deployed and DOES NOT get validated (thus doesn't really matter if Ref's are valid or just empty strings like in my example above)

Is there support for Conditions in localstack or currently it is not supported? Any ideas? 

Thanks =)
