### ISSUE TITLE
Inaccessible host: `demo-bucket.localstack'. This service may not be available in the `us-east-1' region.

### ISSUE THREAD

**Issue by abinhho** [localstack/localstack#2123]
Hello,
I did try on real aws S3 and it's worked but not worked on localstack.

I am using docker on my project like this
```
version: '3.5'
services:
  myproject_api:
    container_name: myproject_api
    build:
      context: .
      dockerfile: Dockerfile.local
      target: dev
    restart: always
    depends_on:
      - localstack
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/myproject_api/src
      - ./dist:/myproject_api/dist

  localstack:
    image: localstack/localstack:latest
    container_name: myproject_localstack
    ports:
      - "4569:4569"
      - "4582:4582"
      - "4574:4574"
      - "4572:4572"
      - "8055:8080"
    environment:
      - SERVICES=dynamodb,cloudwatch,lambda,s3
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - myproject

networks:
  myproject:
    driver: bridge

```

This is .env file
```
AWS_S3_BUCKET_NAME=demo-bucket
AWS_ACCESS_KEY_ID=foobar
AWS_SECRET_ACCESS_KEY=foobar
LOCALSTACK_HOSTNAME=localstack
```

This is the code
```
import { Injectable } from "@nestjs/common";
import * as AWS from 'aws-sdk';
const uuidv4 = require("uuid/v4");
const mime = require('mime-types')

@Injectable()
export class MyUploadService {
  private s3 = new AWS.S3({
    endpoint: process.env.NODE_ENV !== 'production' ? `localstack:4572` : undefined,
  });
  private bucketName = process.env.AWS_S3_BUCKET_NAME;
  private acl = 'public-read'

  constructor() {

    AWS.config.update({
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    });
  }

  public async uploadImage(file: any, path: string = "") {
    const filename = [uuidv4(), mime.extension(file.mimetype)].join(".");

    let urlKey = filename;
    if (path) {
      urlKey = [path, urlKey].join("/");
    }

    const params = {
      Body: file.buffer,
      Bucket: this.bucketName,
      Key: urlKey,
      ACL: this.acl,
      ContentType: file.mimetype,
    };

    return await this.s3
      .putObject(params)
      .promise()
      .then(
        data => {
          const publicUrlFull = this.s3.getSignedUrl("getObject", { Key: urlKey, Bucket: this.bucketName });
          const publicUrl = publicUrlFull.split("?")[0];

          return { urlKey, publicUrl };
        },
        error => {
          throw error;
        }
      );
  }
}

```

I did run:
```
$ aws --endpoint-url=http://localhost:4572 s3api put-bucket-acl --bucket demo-bucket --acl public-read
$ aws --endpoint-url=http://localhost:4572 s3 mb s3://demo-bucket
```

**Comment by whummer** [comment]
Thanks for reporting @abinhho . Please ensure that your S3 client uses _path style addressing_ - this is required to get your application to talk to LocalStack S3 on `localhost`. This is mentioned in the Troubleshooting section of the README and has already been discussed in [various](https://github.com/localstack/localstack/issues/836) [other](https://github.com/localstack/localstack/issues/43) [threads](https://github.com/localstack/localstack/issues/1180).

Please report here if the problem persists or if there is any other issue. Thanks

**Comment by abinhho** [comment]
@whummer 
I figured out and now I went to this step:
```
server.test.pem
server.test.pem.crt
server.test.pem.key
```
But I don't know how to create this 3 files. I used some ssl generator online like https://certificatetools.com/ but just got 2 files.

Please help!

**Comment by guillaumemaka** [comment]
Hi @whummer I have the same issue

Here my docker-compose.yml
```yaml
version: '3.7'

services:
  app:
    image: vt-rest-api:latest-dev
    build:
      context: .
      target: dev
    # env_file: .env
    environment:
      JWT_SECRET: averysecretkey
      NODE_ENV: test
      MONGO_URI: mongodb://root:example@mongodb:27017/habilhome_development?authSource=admin
      AWS_ENDPOINT: http://aws_localstack:4566,
      FALLBACK_EMAIL_ADDRESS: test@example.com
    volumes:
      - "${PWD}/src:/app/src:delegated"
    ports:
      - "5001:4000"
    depends_on:
      - mongodb
      # - nats
      - aws_localstack
    restart: always

  mongodb:
    hostname: mongodb
    image: mongo:4.4.4
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - ./data/db:/data/db

  aws_localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - HOSTNAME_EXTERNAL=aws_localstack
      - SERVICES=s3,sqs
      - DEBUG=1
      - PORT_WEB_UI=${PORT_WEB_UI-8080}
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

AWS.config
```js
const accessKeyId = process.env.AWS_ACCESS_KEY_ID;
const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
const region = process.env.AWS_REGION || "ca-central-1";
const endpoint =  process.env.AWS_ENDPOINT

aws.config.update({
accessKeyId,
secretAccessKey,
region,
s3: {
    endpoint
},
sqs: {
    endpoint
},
s3ForcePathStyle: true,
});
```

I can reach the health endpoint with axios but aws-sdk can resolve the hostname, it worked fine 2 weeks ago.

I looked in the docker-compose file in the repo root, I see the use network_mode: bridge but he didn't work too. 

The name resolution seem to work as axios can resolve the hostname but not the aws-sdk. I use aws-sdk@^2.769.0
