### ISSUE TITLE
S3 bucket not created since 0.10.8

### ISSUE THREAD

**Issue by heichwald** [localstack/localstack#2240]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Not able to create a S3 bucket using cloudformation since version 0.10.8.
Buckets list is empty while the stack is created successfully.
This is working on 0.10.7
...

## Expected behavior
The S3 bucket should be created
...

## Actual behavior
No buckets are created
...

# Steps to reproduce

```
docker run --rm -it -p 9001:4581 -p 9002:4572 -e DEBUG=1 localstack/localstack`
```

```
AWSTemplateFormatVersion: "2010-09-09"
Description: Buckets used for storing event-sync lambdas for local tests.
Resources:
  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: apiservices-local-us-east-1
```

```
aws cloudformation deploy \
    --endpoint-url "http://localhost:9001" \
    --no-fail-on-empty-changeset \
    --region us-east-1 \
    --stack-name apiservices-local-event-sync-us-east-1-buckets \
    --template-file s3-buckets.yaml

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - apiservices-local-event-sync-us-east-1-buckets
```

```
aws cloudformation describe-stacks --region us-east-1 --stack-name apiservices-local-event-sync-us-east-1-buckets --endpoint-url "http://localhost:9001"

{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/apiservices-local-event-sync-us-east-1-buckets/914e468b-8d7d-47f9-8611-fa57cdb4f7e7",
            "StackName": "apiservices-local-event-sync-us-east-1-buckets",
            "Parameters": [],
            "CreationTime": "2020-04-02T16:16:41.455Z",
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Outputs": [],
            "Tags": []
        }
    ]
}
```

```
aws s3api --endpoint-url "http://localhost:9002" list-buckets --region us-east-1

{
    "Buckets": [],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

## Command used to start LocalStack

`docker run --rm -it -p 9001:4581 -p 9002:4572 -e DEBUG=1 localstack/localstack`
