### ISSUE TITLE
Lambda model missing or not preserving attributes

### ISSUE THREAD

**Issue by jacobisaliveandwell** [localstack/localstack#2398]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Lambda is not retaining some values:
- `kms_key_arn`
- `tags`
- `vpc_config` (and it's object's children)

I assume they are missing from the model or something?

## Expected behavior

I should be able to create a function with terraform, using kms and vpc, without triggering changes on subsequent `apply` runs.

## Actual behavior

Terraform applies successfully the first time, but the second time identifies these as not specified (`+`).

# Steps to reproduce

## Command used to start LocalStack

```yaml
version: "2"
services:
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - "4566:4566"
      - "4567:4567"
      - "4568:4568"
      - "4569:4569"
      - "4570:4570"
      - "4571:4571"
      - "4572:4572"
      - "4573:4573"
      - "4574:4574"
      - "4575:4575"
      - "4576:4576"
      - "4577:4577"
      - "4578:4578"
      - "4579:4579"
      - "4580:4580"
      - "4581:4581"
      - "4582:4582"
      - "4583:4583"
      - "4584:4584"
      - "4585:4585"
      - "4586:4586"
      - "4587:4587"
      - "4588:4588"
      - "4589:4589"
      - "4590:4590"
      - "4591:4591"
      - "4592:4592"
      - "4593:4593"
      - "4594:4594"
      - "4595:4595"
      - "4596:4596"
      - "4597:4597"
      - "4599:4599"
      - "8080:8080"
      - "51492:51492"
    environment:
      - "HOSTNAME_EXTERNAL=localhost"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

It's difficult to include all the code, but I think this is sufficient to adapt for anyone testing this.

```hcl
resource "aws_lambda_function" "hello_world" {
  provider = aws.localstack

  function_name = "hello_world"
  tags          = local.tags
  publish       = true

  vpc_config {
    subnet_ids         = [aws_subnet.default.id]
    security_group_ids = [aws_security_group.default.id]
  }

  runtime     = "python3.8"
  role        = aws_iam_role.default.arn
  kms_key_arn = aws_kms_key.default.arn
  s3_bucket   = aws_s3_bucket_object.src.bucket
  s3_key      = aws_s3_bucket_object.src.key
  handler     = "src.hello_world.handler.HelloWorldHandler"

  depends_on = [
    aws_iam_role_policy.default,
    aws_cloudwatch_log_group.hello_world,
  ]
}
```
