### ISSUE TITLE
0.10.7 not executing init scripts

### ISSUE THREAD

**Issue by antsab20** [localstack/localstack#2400]
0.10.7 no longer executes the init scripts when restarted. This feature worked fine last week.
I had to dowgrade 0.10.6 to have it working again 

The init scripts:
```
#!/bin/bash
awslocal s3 mb s3://s3-bucket
awslocal sqs create-queue --queue-name testing-queue
```

The docker-compose:
```
  localstack:
    image: localstack/localstack:0.10.7
    container_name: localstack
    restart: "unless-stopped"
    ports:
      - '8055:8080'
      - '4572:4572'
      - '4576:4576'
    environment:
      - LOCALSTACK_SERVICES=s3:4572,sqs:4576
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './localstack/init:/docker-entrypoint-initaws.d'
      - './localstack/resources:/tmp/resources'
```
