### ISSUE TITLE
Using S3 Localstack with docker-compose

### ISSUE THREAD

**Issue by alyyousuf7** [localstack/localstack#2427]
I have used localstack in docker-compose along with my other services:

```yml
services:
  my-web:
    build: web/
    ports:
      - 3000:80

  my-api:
    build: api/
    environment:
      AWS_ENDPOINT: http://localstack:4566
    ports:
      - 4000:80

  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
    ports:
      - 4566:4566
```

I'm using NodeJS, so in I'm providing the following config to S3 aws-sdk:
```js
export const S3 = new AWS.S3({
    endpoint: config.aws.endpoint, // config.aws.endpoint = ENV[AWS_ENDPOINT]
    // Only for Localstack: If you omit this, you'll have to add bucket name to
    // the 'Key' property of the object.
    // https://github.com/localstack/localstack/issues/2123
    //
    // Also read about it here:
    // https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#path-style-access
    // https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#virtual-hosted-style-access
    s3ForcePathStyle: config.aws.endpoint ? true : false,
});
```

When I upload S3 Object to a publicly-readable bucket from `my-api`, the `Location` I get, has the domain and port `localstack:4566`. For example: `http://localstack:4566/my-bucket/my-object`

But when the same location is forwarded from `my-api` to `my-web`, of course the web is running on my browser, my host machine does not recognize to hostname `localstack`. It does work if I replace the URL to `localhost` in either `my-web` or `my-api`, but that's not the actual solution.

Is there a better way to change the hostname in Object Location returned by the `aws-sdk` without bloating my actual code in `my-api` and `my-web`?
