### ISSUE TITLE
Get status of each service (docker) 

### ISSUE THREAD

**Issue by hunk** [localstack/localstack#2454]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
the health checks do not return the services (docker)

## Expected behavior
the documentation says
> The service health check endpoint http://localhost:8080/health provides basic information about the status of each service (e.g., {"s3":"running","es":"starting"}).
...

## Actual behavior
When I get the health checks show `{"status":"OK"}`

# Steps to reproduce

## Command used to start LocalStack
I up the next docker-compose.yml

```
---
version: '3.7'

services:
  localstack:
    image: localstack/localstack  
    ports:
      - 8080:8080
    environment:
      - SERVICES=s3,es
      - DATA_DIR=/tmp/localstack/data
```

``` bash
docker-compose up
```

and run 
``` bash
curl http://localhost:8080/health\?reload
```

I have something wrong or whats the steps to get the status of each service. the services are working fine. just do no have the status.
