### ISSUE TITLE
S3 storage class header does not work for larger files

### ISSUE THREAD

**Issue by Keeo** [localstack/localstack#2481]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Requested storage class gets ignored for files over 8mb.

## Expected behavior

Store the file in specified storage class even for files that are over this size.

## Actual behavior

File is uploaded to STANDARD storage class instead.

# Steps to reproduce
I created two files that can reproduce the issue. The *docker-compose.yaml* to start localstack and python script *main.py* to reproduce the issue. [Boto3](https://pypi.org/project/boto3/) is only dependency `pip install boto3`. Then start the *docker-compose.yaml* file and execute the script *python3 main.py*. It will generate files from 1 to 20 mb, upload them and print their storage class.

```yaml
# docker-compose.yaml
version: "3"
localstack:
      image: localstack/localstack
      restart: unless-stopped
      ports:
        - "4566:4566"
        - "4572:4572"
        - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
      environment:
        - SERVICES=s3:4572
        - DEBUG=0
        - DATA_DIR=/tmp/localstack/data
        - PORT_WEB_UI=${PORT_WEB_UI- }
        - HOST_TMP_FOLDER="/tmp/localstack"
      volumes:
        - "./.docker/localstack:/tmp/localstack"
```

```python
# main.py
from tempfile import NamedTemporaryFile

import boto3

aws_access_key_id = "any"
aws_secret_access_key = "any"
endpoint_url = "http://localhost:4572"
bucket_name = "test-bucket"
file_name = "large.file"

s3 = boto3.client(
    's3',
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    endpoint_url=endpoint_url,
)

s3_resource = boto3.resource(
    's3',
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    endpoint_url=endpoint_url,
)

s3.create_bucket(Bucket=bucket_name)

for i in range(1, 20):
    with NamedTemporaryFile() as f:
        f.seek(int(i * 1e6))
        f.write(b"\0")
        f.flush()
        s3.upload_file(
            f.name,
            bucket_name,
            f"{file_name}-{i}",
            ExtraArgs={'StorageClass': 'DEEP_ARCHIVE'},
            #Callback=lambda x: print(x),
        )

    objects = s3_resource.Bucket(bucket_name).objects.all()
    filtered = filter(lambda x: x.key == f"{file_name}-{i}", objects)
    print(i, dict(map(lambda x: (x.key, x.storage_class), filtered)))

```
```txt
1 {'large.file-1': 'DEEP_ARCHIVE'}
2 {'large.file-2': 'DEEP_ARCHIVE'}
3 {'large.file-3': 'DEEP_ARCHIVE'}
4 {'large.file-4': 'DEEP_ARCHIVE'}
5 {'large.file-5': 'DEEP_ARCHIVE'}
6 {'large.file-6': 'DEEP_ARCHIVE'}
7 {'large.file-7': 'DEEP_ARCHIVE'}
8 {'large.file-8': 'DEEP_ARCHIVE'}
9 {'large.file-9': 'STANDARD'} <-------- Files starting with size 9*1e6b are stored to STANDARD instead.
10 {'large.file-10': 'STANDARD'}
11 {'large.file-11': 'STANDARD'}
12 {'large.file-12': 'STANDARD'}
13 {'large.file-13': 'STANDARD'}
14 {'large.file-14': 'STANDARD'}
15 {'large.file-15': 'STANDARD'}
16 {'large.file-16': 'STANDARD'}
17 {'large.file-17': 'STANDARD'}
18 {'large.file-18': 'STANDARD'}
19 {'large.file-19': 'STANDARD'}
```

## Command used to start LocalStack
docker-compose up -d
