### ISSUE TITLE
Cannot connect to DynamoDB from lambda

### ISSUE THREAD

**Issue by umatbro** [localstack/localstack#2511]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description
I'm using localstack for local development. I have a DynamoDB table named `readings` and I'd like 
to insert items from a lambda function.
I have a simple function in python runtime:

```python
import os
import boto3

def lambda_handler(events, context):
    DYNAMODB_ENDPOINT_URL = os.environ.get("DYNAMODB_ENDPOINT_URL")
    dynamodb = boto3.resource("dynamodb", endpoint_url=DYNAMODB_ENDPOINT_URL)
    readings_table = dynamodb.Table(DYNAMODB_READINGS_TABLE_NAME)

    readings_table.put_item(Item={"reading_id": "10", "other": "test"})
```

I cannot figure out what is the proper endpoint url for my local DynamoDB.
I have tried different combinations of `localhost`, `localstack` and ports `4566`, `4569`, each time I get error `EndpointConnectionError`

## Expected behavior
Items are inserted in the table.

## Actual behavior
Lambda cannot connect to dynamodb and error `[ERROR] EndpointConnectionError: Could not connect to the endpoint URL: "http://localstack:4569/"` is raised.

# Steps to reproduce

Run localstack image with docker-compose, set `LOCALSTACK_HOSTNAME=localstack` and try to access dynamodb resource from lambda.

## Command used to start LocalStack
docker-compose service I'm using:
```yml
    localstack:
        image: localstack/localstack:0.11.2
        ports:
            - 4566:4566
            - 8080:8080
        environment:
            SERVICES: "dynamodb,sqs,lambda,iam"
            DATA_DIR: "/tmp/localstack/data"
            PORT_WEB_UI: "8080"
            LOCALSTACK_HOSTNAME: localstack
            LAMBDA_EXECUTOR: docker
            AWS_ACCESS_KEY_ID: "test"
            AWS_SECRET_ACCESS_KEY: "test"
            AWS_DEFAULT_REGION: "us-east-1"
        volumes:
            - localstack_volume:/tmp/localstack/data
            - /var/run/docker.sock:/var/run/docker.sock
            # When a container is started for the first time, it will execute files with extensions .sh that are found in /docker-entrypoint-initaws.d. 
            # Files will be executed in alphabetical order. You can easily create aws resources on localstack using `awslocal` (or `aws`) cli tool in the initialization scripts.
            # Here I run creating dynamodb tables, roles, etc.
            - ./localstack-startup-scripts/:/docker-entrypoint-initaws.d/
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...
