### ISSUE TITLE
S3 data directory

### ISSUE THREAD

**Issue by sanster23** [localstack/localstack#252]
Hi,
I have been trying to use Localstack for testing my dummy AWS infrastructure and somewhere along the line when i am uploading the files to S3 from multiple users simultaneously and most of the requests are timed out, even though the files were not that big. So is there a way to change the data directory where the S3 stores files. Because I can't seem to find the current location configurations. Also i want to keep data in disk instead of RAM.

**Comment by jonaskint** [comment]
@sanster23 the data is stored in /tmp/localstack/data/s3_api_calls.json . Just did a test and that json grows when I started uploading files :)

**Comment by ankitbansal289** [comment]
I am not getting the tmp/localstack/data folder 

![image](https://user-images.githubusercontent.com/49555753/56030516-a63cce80-5d3a-11e9-84ee-89ba0eb50192.png)

**Comment by jayco** [comment]
Hey I know its a bit late but for anyone else and searching and @ankitbansal289 you need to create it:

docker-compose example:
```
    localstack:
        image: localstack/localstack
        ports:
            - 4576:4576
            - 4575:4575
            - 4572:4572
            - 8055:8080
        environment:
            - DOCKER_HOST=unix:///var/run/docker.sock
            - SERVICES=sqs:4576, sns:4575, s3:4572
            - DEFAULT_REGION=ap-southeast-2
            - HOSTNAME_EXTERNAL=localstack
            - DATA_DIR=/tmp/localstack/data
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            -./.localstack:/tmp/localstack
```
