### ISSUE TITLE
cloudformation deploy doesn't create the stack resources

### ISSUE THREAD

**Issue by rakcy** [localstack/localstack#2528]
# Type of request: This is an issue with `cloudformation deploy`

[x] bug report
[ ] feature request

# Detailed description

Localstack Docker Version: `0.11.2`
awslocal version: `aws-cli/1.18.74 Python/3.6.9 Darwin/19.4.0 botocore/1.16.24`

When I run the command below:
```
$ awslocal  cloudformation deploy --template-file template.yml --stack-name test
```

I get the error below from localstack docker:
```
2020-06-08T09:30:34:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id test does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
2020-06-08T09:30:34:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeChangeSet" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id arn:aws:cloudformation:us-east-1:123456789012:changeSet/awscli-cloudformation-package-deploy-1591607269/d30d36bf-0a4c-441a-84b0-7c0c9030a8a9 does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
```

## Expected behavior

Stack and its resources are created

## Actual behavior

Stack is created but it has 0 resources

```
$ awslocal cloudformation describe-stacks --stack-name test

{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/test/a6c04ecb-339b-46bf-8544-1a0b38901573",
            "StackName": "test",
            "ChangeSetId": "arn:aws:cloudformation:us-east-1:000000000000:changeSet/awscli-cloudformation-package-deploy-1591607269/d30d36bf-0a4c-441a-84b0-7c0c9030a8a9",
            "Description": "Hello World Function",
            "Parameters": [],
            "CreationTime": "2020-06-08T09:07:50Z",
            "StackStatus": "CREATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Outputs": [],
            "Tags": []
        }
    ]
}
```

```
$ awslocal cloudformation describe-stack-resources --stack-name test

{
    "StackResources": []
}
```

# Steps to reproduce

## Command used to start LocalStack

```
$ docker-compose up -d
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
# This should create the stack with all of its resources
$ awslocal  cloudformation deploy --template-file template.yml --stack-name test

# Stack is created
$ awslocal cloudformation describe-stacks --stack-name test

# 0 resources
$ awslocal cloudformation describe-stack-resources --stack-name test
```

**Comment by mcintyre94** [comment]
Seeing the same thing.

Sample template.yml:

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # IAM role for running the step function
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunction"
            Resource: "*"
```

```bash
$ awslocal cloudformation deploy --stack-name stack1 --template-file template.yaml --capabilities CAPABILITY_IAM

Waiting for changeset to be created..

'Status'
```

Same debug message you're seeing.

`awslocal cloudformation create-stack --stack-name stack1 --template-body file://template.yaml --capabilities CAPABILITY_IAM` works perfectly.

Especially when setting a few parameters, the `cloudformation deploy` command is much nicer than `create-stack` and it's a real shame not to be able to use it here.
