### ISSUE TITLE
"Unable to find executor" on invoke nodejs lambda function

### ISSUE THREAD

**Issue by tylerbrandt** [localstack/localstack#253]
First of all, is the `nodejs6.10` runtime supported for lambda (I can't find any specific documentation of what runtimes are supported, but the comments in #66 implies it is there)?

I'm trying to create an application using localstack for local development, and I'm running into some issues with the lambda portion. I need to use nodejs for the lambda function, but the function cannot be invoked. The error is:
```
Exception: Unable to find executor for Lambda function "testfn". Note that Node.js Lambdas currently require LAMBDA_EXECUTOR=docker
```
I put together this example repo to demonstrate the issue, but feel free to let me know if you need any additional information: https://github.com/tylerbrandt/localstack-demo

Thanks!

**Comment by KamuelaFranco** [comment]
You'll need to run localstack with `LAMBDA_EXECUTOR=docker` set in the current environment.

**Comment by tylerbrandt** [comment]
@KamuelaFranco thanks for the response! Do you mean the environment that is running localstack? I thought that's what I was doing in [docker-compose](https://github.com/tylerbrandt/localstack-demo/blob/0f30e22c9fc8574054bda780b855af932ef02116/docker-compose.yml#L10). Or do you mean the "client" environment (from which I'm sending the `aws-cli` calls)?

**Comment by KamuelaFranco** [comment]
The environment where you're running localstack. I can't completely confirm, but running localstack directly through docker will likely not pass in the environment variables. It will have to be run like this: `LAMDBA_EXECUTOR=docker localstack start --docker`

**Comment by tylerbrandt** [comment]
Thanks for the tip; it works with the "direct" command (once I modified it for macOS as described in the docs):
```sh
TMPDIR=/private$TMPDIR LAMBDA_EXECUTOR=docker localstack start --docker
```
However, for my use case I'd really prefer to run `localstack` itself through `docker-compose`. Can you help me understand what the (meaningful) differences are between my [docker-compose.yml](https://github.com/tylerbrandt/localstack-demo/blob/d440552304e7a1fe898660f330613126e849c4ec/docker-compose.yml#L4) and this command, and how to configure it correctly?

**Comment by tylerbrandt** [comment]
I was able to resolve the problem in the docker-compose service, inspired by the docker-compose file in this repo:
```
version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4574:4574'
    environment:
      SERVICES: lambda
      LAMBDA_EXECUTOR: docker
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
      - "/private${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
Now, I'm getting a different error but it is running nodejs so I think that might be something legitimate to do with my configuration. Thanks for your help!
