### ISSUE TITLE
java.lang.NoClassDefFoundError showing up when using lambda layer with lambda java function.

### ISSUE THREAD

**Issue by kvudathu** [localstack/localstack#2605]
# Type of request: This is a bug report, java.lang.NoClassDefFoundError showing when using lambda layer with java function.
Using pro account.

# Detailed description
Trying to invoke java lambda with lambda layers after deploying the stack using severless script below. Everything works perfectly when I run serverless to deploy on aws. Even sls invoke doesn't give NoClassDefFoundError error. 
I'm confused why localstack is giving NoClassDefFoundError if lambda layers do the contain the class AwsSdkRequestFailure. The lambda function in aws works great.

Error is as follows:
```
{"errorMessage":"Lambda process returned error status code: 1. Result: . Output:\nException in thread \"main\" java.lang.NoClassDefFoundError: com/trendmicro/np/ms/connector/exceptions/AwsSdkRequestFailure\n\tat java.base/java.lang.Class.forName0(Native Method)\n\tat java.base/java.lang.Class.forName(Unknown Source)\n\tat cloud.localstack.LambdaExecutor.getHandler(LambdaExecutor.java:150)\n\tat cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:64)\nCaused by: java.lang.ClassNotFoundException: com.trendmicro.np.ms.connector.exceptions.AwsSdkRequestFailure\n\tat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)\n\tat java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)\n\tat java.base/java.lang.ClassLoader.loadClass(Unknown Source)\n\t... 4 more","errorType":"Exception","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 527, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 136, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 128, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 143, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 139, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 121, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 109, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 264, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 173, in run_lambda_executor\n    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}
```

My code is as follows:
severless.yml
```
service: gateway-discovery

provider:
  name: aws
  region: us-west-2
  stage: ${opt:stage, 'aws'}
  role: ${self:custom.lambdaIamRole.${self:provider.stage}}
  logRetentionInDays: 90

package:
  individually: true

layers:
  lambdaLibs:
    package:
      artifact: build/lambda/layers/java/gateway-discovery-layer.zip
    name: gateway-discovery-layer
    description: "libraries needed for gateway-discovery lambdas"
    compatibleRuntimes:
      - java11

functions:
  igw-gateway-status:
    runtime: java11
    package:
      artifact: build/lambda/functions/java/igw-gateway-status/lambda.zip
    handler: com.trendmicro.np.gatewaydiscovery.IgwGatewayStatus
    layers:
      - {Ref:  LambdaLibsLambdaLayer}
    reservedConcurency: 100
    memorySize: 512
    timeout: 20

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - dev
    host: http://localhost  # optional - LocalStack host to connect to
    autostart: false  # optional - start LocalStack in Docker on Serverless deploy
  stages:
    - dev
    - aws
  lambdaIamRole:
    dev: arn:aws:iam::000000000000:role/gateway-lambda-role
    aws: arn:aws:iam::fakeaccount:role/LambdaGatewayDiscovery
```
docker-compose.yml
```
version: '3.3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=12345
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Serverless logs
```
 sls deploy -s dev
Serverless: Using serverless-localstack
Serverless: Warning: Unable to find plugin named: TypeScriptPlugin
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service lambda.zip file to S3 (2.76 KB)...
Serverless: Uploading service gateway-discovery-layer.zip file to S3 (56.82 MB)...
Serverless: Validating template...
Serverless: Skipping template validation: Unsupported in Localstack
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
.
Serverless: Stack update finished...
Service Information
service: gateway-discovery
stage: dev
region: us-west-2
stack: gateway-discovery-dev
resources: 6
api keys:
  None
endpoints:
  None
functions:
  igw-gateway-status: gateway-discovery-dev-igw-gateway-status
layers:
  lambdaLibs: arn:aws:lambda:us-west-2:000000000000:layer:gateway-discovery-layer
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
```

policy.json used to create IAM role
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage",
                "sqs:GetQueueAttributes",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "sts:AssumeRole"
            ],
            "Resource": "*"
        }
    ]
}
```

## Command used to start LocalStack
docker-compose up -d
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
awslocal  iam create-role --role-name gateway-lambda-role --assume-role-policy-document file://policy.json
sls deploy -s dev
awslocal lambda invoke --function-name gateway-discovery-dev-igw-gateway-status output.txt
...

Thanks
