### ISSUE TITLE
Cloudformation deploy with (only) an IAM resource not working

### ISSUE THREAD

**Issue by mcintyre94** [localstack/localstack#2624]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I initially reported this on https://github.com/localstack/localstack/issues/2528, but the OP there has closed it as it's fixed on `latest` for them - so my issue is probably not a dupe of theirs. Figured it probably makes more sense to have a new issue and add some more details than to reopen their resolved one.

## Expected behavior

When I upload a template that contains an IAM resource using `cloudformation deploy`, the stack is created and the IAM role is created. There are no erorr messages and the exit code of the deploy command is 0.

## Actual behavior

**In the shell running `cloudformation deploy`:**

I get an unexpected output:

```
Waiting for changeset to be created..

'Status'
```

The exit code is 255:

```bash
$ echo $?
255
```

The stack has been created:

```bash
$ awslocal cloudformation list-stacks
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/stack1/1b8fa922-273a-4a78-8ba2-b7cebc5b96bd",
            "StackName": "stack1",
            "TemplateDescription": "None",
            "CreationTime": "2020-06-26T08:49:12Z",
            "StackStatus": "CREATE_COMPLETE"
        }
    ]
}
```

It has no resources:

```bash
$ awslocal cloudformation describe-stack-resources --stack-name stack1
{
    "StackResources": []
}
```

There are no IAM roles:

```bash
$  awslocal iam list-roles
{
    "Roles": []
}
```

**In the localstack shell:**

```
2020-06-26T08:40:21:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeStacks" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id stack1 does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
2020-06-26T08:40:21:DEBUG:localstack.services.cloudformation.cloudformation_listener: Error response for CloudFormation action "DescribeChangeSet" (400) POST /: b'<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>Stack with id arn:aws:cloudformation:us-east-1:123456789:changeSet/awscli-cloudformation-package-deploy-1593160821/6a1125ec-9940-4c57-a516-6377832f0971 does not exist</Message>\n  </Error>\n  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>\n</ErrorResponse>'
```

# Steps to reproduce

## Command used to start LocalStack

```bash
DEBUG=1 localstack start
```

I also tried manually running the `docker run` that translates to in case `localstack/localstack` wasn't latest:

```bash
docker run -it -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -e DEBUG="1" -e LOCALSTACK_HOSTNAME="localhost" -p 443:443 -p 4566:4566 --rm --privileged --name localstack_main -p 8080-8081:8080-8081 -p 4567-4617:4567-4617 -p 10000:10000  -v "/private/var/folders/k6/s4wg10352ds18zzs_fc295r80000gn/T/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/private/var/folders/k6/s4wg10352ds18zzs_fc295r80000gn/T/localstack" "localstack/localstack:latest"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

template.yaml:

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # IAM role for running the step function
  ExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunction"
            Resource: "*"
```

Deploy command:

`awslocal cloudformation deploy --stack-name stack1 --template-file cfntest.yml --capabilities CAPABILITY_IAM`

If I instead use the `create-stack` command, then that works perfectly: 

`awslocal cloudformation create-stack --stack-name stack1 --template-body file://template.yaml --capabilities CAPABILITY_IAM`

This is a workable workaround, but for a more complex stack with parameters the `deploy` equivalent is significantly nicer to use.
