### ISSUE TITLE
Error during CreateDeployment call when trying to create a Serverless Api in CloudFormation template

### ISSUE THREAD

**Issue by rikbruil** [localstack/localstack#2642]
# Type of request: This is a ...

[x] bug report
[  ] feature request

# Detailed description

When trying to create a simple ApiGateway resource connected to a Lambda function in a CloudFormation template using Localstack, I run into the error `The REST API doesn't contain any methods` during stack creation.

It seems very similar to #1909, although that issue has been closed and seems to have been resolved for the reporter after a fix was released.

It seems to be related to the order of creation of the resources. It looks like it tries to call `CreateDeployment` before any methods have been registered on the Api resource. (Could be related to a missing DependsOn property under the hood when creating the Deployment resource, according to [this StackOverflow thread](https://stackoverflow.com/questions/56944526/cloudformation-stack-errors-with-rest-api-doesnt-contain-any-methods))

## Expected behavior

The ApiGateway resource gets created successfully.

## Actual behavior

You get the error `The REST API doesn't contain any methods` during stack creation, and the creation of the resource fails.

Detailed error output:

```
localstack_main | 2020-06-29T12:09:09:INFO:localstack.services.cloudformation.cloudformation_starter: Updating resource ID from 912fdcc1 to 2y20hm4ov5 (us-east-1)
localstack_main | 2020-06-29T12:09:09:WARNING:localstack.services.cloudformation.cloudformation_starter: Unable to determine physical_resource_id for resource <class 'moto.apigateway.models.RestAPI'>
localstack_main | 2020-06-29T12:09:09:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.APIGateway object at 0x7fd3e9f74280>> with params: {'restApiId': '2y20hm4ov5', 'stageName': 'Stage', 'description': 'RestApi deployment id: c72b985b3fef01cb6e47adb61f4a543c86e5a1fc'} for resource: {'Type': 'AWS::ApiGateway::Deployment', 'Properties': {'Description': 'RestApi deployment id: c72b985b3fef01cb6e47adb61f4a543c86e5a1fc', 'RestApiId': '2y20hm4ov5', 'StageName': 'Stage'}}
localstack_main | 2020-06-29T12:09:09:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "ApiDeploymentc72b985b3f": An error occurred (BadRequestException) when calling the CreateDeployment operation: The REST API doesn't contain any methods Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 215, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 340, in _parse_and_create_resource
localstack_main |     result = deploy_func(logical_id, resource_map_new, stack_name=stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1070, in deploy_resource
localstack_main |     return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1100, in execute_resource_action
localstack_main |     result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name)
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1177, in configure_resource_via_sdk
localstack_main |     raise e
localstack_main |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1174, in configure_resource_via_sdk
localstack_main |     result = function(**params)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_main |     return self._make_api_call(operation_name, kwargs)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
localstack_main |     raise error_class(parsed_response, operation_name)
localstack_main | botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateDeployment operation: The REST API doesn't contain any methods
localstack_main | 
```

# Steps to reproduce

## Command used to start LocalStack

Using the latest released Docker image (0.11.3), although this also occurs in earlier 0.10.x versions.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal cloudformation create-stack --stack-name "automation"  --template-body "file://cloudformation.yaml"
```

The template used is taken from the [AWS documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-resource-api--examples--simpleapiexample). 

I have added a Name property to the Api resource to get around the issue reported in #2641 

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template with a simple API definition
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyApi
      StageName: prod
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: Api
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
            return {'body': 'Hello World!', 'statusCode': 200}
```
