### ISSUE TITLE
CreateFunction returns "413 Request Entity Too Large" for 23MB Lambda Zipfile

### ISSUE THREAD

**Issue by shawnrusaw-wf** [localstack/localstack#2727]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

## Expected behavior

The Lambda function should be created since the real limit is 50MB as per https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html

## Actual behavior

`CreateFunction` command returns 

```
An error occurred (413) when calling the CreateFunction operation:
<!doctype html>
<title>413 Request Entity Too Large</title>
<h1>Request Entity Too Large</h1>
Entity is too large
```

for a python Zip file that is only 23MB in size (approx)

```
%> ls -la /var/folders/.../lambda.zip
-rw-------  1 me  group  22620820 Jul 15 06:47 /var/folders/.../lambda.zip
```

# Steps to reproduce

## Command used to start LocalStack

docker-compose entry like:

```
  localstack:
    image: localstack/localstack:0.11.3
    environment:
      SERVICES: sqs,kinesis,dynamodb,lambda
      HOSTNAME: localstack
      DOCKER_HOST: unix:///var/run/docker.sock
      USE_SSL: 'true'
      DEFAULT_REGION: us-east-1
      LAMBDA_EXECUTOR: local
      LAMBDA_JAVA_OPTS: -Xmx512M
      # AWS_ACCOUNT_ID: anything - is not supported yet on kinesis, do not use
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
%> aws --endpoint-url="https://localhost:4566" lambda create-function ...
```
