### ISSUE TITLE
Problems with spring cloud message attributes

### ISSUE THREAD

**Issue by vinicius-rosa-ifood** [localstack/localstack#2731]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I'm trying to use the latest version, currently 0.11.3 with spring cloud and noticed that when it sends message attributes of type "Number.java.lan.Long", localstack returns an error. I was using version 0.11.2 and it works fine.

## Expected behavior

Message successfully sent

## Actual behavior

An error is returned with `The message attribute 'timestamp' has an invalid message attribute type, the set of supported type prefixes is Binary, Number, and String.` message.

# Steps to reproduce
1 -  Pull the latest version of localstack image(currently 0.11.3)
2 - Run using docker compose 
2 - Create queue 
3 - Try to send a message with message attribute of type "Number.java.lang.Long"

## Command used to start LocalStack

**Docker compose file**
```
version: "3"
services:
  aws_local:
    container_name: aws_local
    image: "localstack/localstack:latest"
    ports:
      - "4569-4584:4569-4584"
      - "8081:8080"
    environment:
      - AWS_CBOR_DISABLE=true
      - SERVICES=s3,sns,sqs,dynamodb
```

```
docker-compose up -d
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws --endpoint-url=http://localhost:4576 --region=us-east-1 sqs create-queue --queue-name "MY_AWSOME_QUEUE"

aws --endpoint-url=http://localhost:4576 \
--region=us-east-1 \
sqs send-message \
--queue-url "http://localhost:4576/000000000000/MY_AWSOME_QUEUE" \
--message-body "{\"name\":test,\"uuid\":\"e890fc87-6627-4d1a-83bf-4fd2541719b3\"}" \
--message-attributes '{ "id":{ "DataType":"String","StringValue":"d91bf94f-9191-3429-527c-58b90dc06b55" }, "contentType":{ "DataType":"String","StringValue":"application/json"}, "timestamp":{ "DataType":"Number.java.lang.Long","StringValue":"1594851603437"}  }'
```
