### ISSUE TITLE
CloudFormation: Read timeout

### ISSUE THREAD

**Issue by lfantone** [localstack/localstack#2757]
# Type of request
* [x] bug report
* [ ] feature request

# Detailed description
I'm trying to deploy a simple cloudformation template that describe a serverless application into localstack but when the template is uploaded with either the _Localstack PRO dashboard_, _aws cli_ or _aws cdk_ the docker logs are being spawned with a lot of timeout errors and the whole _localstack_ stops working.

## Expected behavior
The CloudFormation template is uploaded correctly and the resources are being created. And also If there are timeout errors, localstack should not stop working and responding.

## Actual behavior
The localstack docker image console shows:

```console
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
localstack_1  |     six.raise_from(e, None)
localstack_1  |   File "<string>", line 3, in raise_from
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
localstack_1  |     httplib_response = conn.getresponse()
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
localstack_1  |     response.begin()
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 303, in begin
localstack_1  |     version, status, reason = self._read_status()
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
localstack_1  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
localstack_1  |   File "/usr/lib/python3.8/socket.py", line 669, in readinto
localstack_1  |     return self._sock.recv_into(b)
localstack_1  | socket.timeout: timed out
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 254, in send
localstack_1  |     urllib_response = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 379, in increment
localstack_1  |     raise six.reraise(type(error), error, _stacktrace)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
localstack_1  |     raise value
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
localstack_1  |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
localstack_1  |     raise ReadTimeoutError(
localstack_1  | urllib3.exceptions.ReadTimeoutError: AWSHTTPConnectionPool(host='22b2deb0bd0f', port=4567): Read timed out. (read timeout=60)
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 767, in retrieve_resource_details
localstack_1  |     result = aws_stack.connect_to_service('apigateway').get_deployments(restApiId=api_id)['items']
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 621, in _make_api_call
localstack_1  |     http, parsed_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/client.py", line 641, in _make_request
localstack_1  |     return self._endpoint.make_request(operation_model, request_dict)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
localstack_1  |     return self._send_request(request_dict, operation_model)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
localstack_1  |     while self._needs_retry(attempts, operation_model, request_dict,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 253, in _needs_retry
localstack_1  |     responses = self._event_emitter.emit(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
localstack_1  |     return self._emitter.emit(aliased_event_name, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
localstack_1  |     return self._emit(event_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
localstack_1  |     response = handler(**kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
localstack_1  |     if self._checker(attempts, response, caught_exception):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
localstack_1  |     should_retry = self._should_retry(attempt_number, response,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
localstack_1  |     return self._checker(attempt_number, response, caught_exception)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
localstack_1  |     checker_response = checker(attempt_number, response,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
localstack_1  |     return self._check_caught_exception(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
localstack_1  |     raise caught_exception
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 200, in _do_get_response
localstack_1  |     http_response = self._send(request)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 269, in _send
localstack_1  |     return self.http_session.send(request)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/botocore/httpsession.py", line 289, in send
localstack_1  |     raise ReadTimeoutError(endpoint_url=request.url, error=e)
localstack_1  | botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "http://22b2deb0bd0f:4567/restapis/rrtl8feyjm/deployments"
localstack_1  |  - {'Type': 'AWS::ApiGateway::Deployment', 'Properties': {'RestApiId': 'rrtl8feyjm', 'Description': 'Automatically created by the RestApi construct'}, 'DependsOn': ['conferenceschedulerapiitemsOPTIONS145133B1', 'conferenceschedulerapiitemsPOSTA09A4B3B', 'conferenceschedulerapiitems0D2333A0'], 'Metadata': {'aws:cdk:path': 'ConferenceSchedulerStack/conference-scheduler-api/Deployment/Resource'}} {}
localstack_1  | 2020-07-22T07:59:26:WARNING:urllib3.connectionpool: Connection pool is full, discarding connection: 22b2deb0bd0f
localstack_1  | 2020-07-22T07:59:26:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource ApiGateway::Deployment: Read timeout on endpoint URL: "http://22b2deb0bd0f:4567/restapis/rrtl8feyjm/deployments" Traceback (most recent call last):
```

```console
ConferenceSchedulerStack: creating CloudFormation changeset...

 ❌  ConferenceSchedulerStack failed: Error [TimeoutError]: Connection timed out after 120000ms
    at ClientRequest.<anonymous> (/Users/lfantone/Workspace/confscheduler/node_modules/aws-sdk/lib/http/node.js:86:34)
    at Object.onceWrapper (events.js:416:28)
    at ClientRequest.emit (events.js:310:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at Socket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:416:28)
    at Socket.emit (events.js:322:22)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17) {
  code: 'TimeoutError',
  time: 2020-07-22T08:16:39.899Z,
  region: 'us-west-1',
  hostname: 'localhost',
  retryable: true
}
Connection timed out after 120000ms
```

And then none of the localstack services works anymore, any subsequent command to aws will end in a timeout.

# Steps to reproduce
Create a new CloudFormation Stack using the template below with the Localstack dashboard or upload it with the _aws cli_.

```yml
Resources:
  conferenceschedulerA49C5E4D:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: key
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: key
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: development-conference-scheduler
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler/Resource
  createuserServiceRole9B06EF7C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/create-user/ServiceRole/Resource
  createuserServiceRoleDefaultPolicy56144C67:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - conferenceschedulerA49C5E4D
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: createuserServiceRoleDefaultPolicy56144C67
      Roles:
        - Ref: createuserServiceRole9B06EF7C
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/create-user/ServiceRole/DefaultPolicy/Resource
  createuserADA9FC05:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3BucketCD049D8F
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3VersionKeyEB34933F
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3VersionKeyEB34933F
      Handler: index.createUserHandler
      Role:
        Fn::GetAtt:
          - createuserServiceRole9B06EF7C
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: conferenceschedulerA49C5E4D
    DependsOn:
      - createuserServiceRoleDefaultPolicy56144C67
      - createuserServiceRole9B06EF7C
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/create-user/Resource
      aws:asset:path: asset.aa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622f
      aws:asset:property: Code
  conferenceschedulerapiF4E213A7:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Conference Scheduler API Service
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Resource
  conferenceschedulerapiCloudWatchRole13083343:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/CloudWatchRole/Resource
  conferenceschedulerapiAccount4CE39CD7:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - conferenceschedulerapiCloudWatchRole13083343
          - Arn
    DependsOn:
      - conferenceschedulerapiF4E213A7
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Account
  conferenceschedulerapiDeploymentC02214A055bc333b06e34ec6f12b73ef8c4f88f5:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: conferenceschedulerapiF4E213A7
      Description: Automatically created by the RestApi construct
    DependsOn:
      - conferenceschedulerapiitemsOPTIONS145133B1
      - conferenceschedulerapiitemsPOSTA09A4B3B
      - conferenceschedulerapiitems0D2333A0
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Deployment/Resource
  conferenceschedulerapiDeploymentStageprodBD2ECBF7:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: conferenceschedulerapiF4E213A7
      DeploymentId:
        Ref: conferenceschedulerapiDeploymentC02214A055bc333b06e34ec6f12b73ef8c4f88f5
      StageName: prod
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/DeploymentStage.prod/Resource
  conferenceschedulerapiitems0D2333A0:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - conferenceschedulerapiF4E213A7
          - RootResourceId
      PathPart: items
      RestApiId:
        Ref: conferenceschedulerapiF4E213A7
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Default/items/Resource
  conferenceschedulerapiitemsPOSTApiPermissionConferenceSchedulerStackconferenceschedulerapiB7905FBBPOSTitemsBD38D967:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - createuserADA9FC05
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-west-1:0000000000:"
            - Ref: conferenceschedulerapiF4E213A7
            - /
            - Ref: conferenceschedulerapiDeploymentStageprodBD2ECBF7
            - /POST/items
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Default/items/POST/ApiPermission.ConferenceSchedulerStackconferenceschedulerapiB7905FBB.POST..items
  conferenceschedulerapiitemsPOSTApiPermissionTestConferenceSchedulerStackconferenceschedulerapiB7905FBBPOSTitems038D04EE:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - createuserADA9FC05
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-west-1:0000000000:"
            - Ref: conferenceschedulerapiF4E213A7
            - /test-invoke-stage/POST/items
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Default/items/POST/ApiPermission.Test.ConferenceSchedulerStackconferenceschedulerapiB7905FBB.POST..items
  conferenceschedulerapiitemsPOSTA09A4B3B:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId:
        Ref: conferenceschedulerapiitems0D2333A0
      RestApiId:
        Ref: conferenceschedulerapiF4E213A7
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-west-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - createuserADA9FC05
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Default/items/POST/Resource
  conferenceschedulerapiitemsOPTIONS145133B1:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: OPTIONS
      ResourceId:
        Ref: conferenceschedulerapiitems0D2333A0
      RestApiId:
        Ref: conferenceschedulerapiF4E213A7
      AuthorizationType: NONE
      Integration:
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.Access-Control-Allow-Credentials: "'false'"
              method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,PUT,POST,DELETE'"
            StatusCode: "200"
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        Type: MOCK
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true
            method.response.header.Access-Control-Allow-Origin: true
          StatusCode: "200"
    Metadata:
      aws:cdk:path: ConferenceSchedulerStack/conference-scheduler-api/Default/items/OPTIONS/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.53.0,@aws-cdk/assets=1.53.0,@aws-cdk/aws-apigateway=1.53.0,@aws-cdk/aws-applicationautoscaling=1.53.0,@aws-cdk/aws-autoscaling-common=1.53.0,@aws-cdk/aws-cloudwatch=1.53.0,@aws-cdk/aws-codeguruprofiler=1.53.0,@aws-cdk/aws-dynamodb=1.53.0,@aws-cdk/aws-ec2=1.53.0,@aws-cdk/aws-events=1.53.0,@aws-cdk/aws-iam=1.53.0,@aws-cdk/aws-kms=1.53.0,@aws-cdk/aws-lambda=1.53.0,@aws-cdk/aws-logs=1.53.0,@aws-cdk/aws-s3=1.53.0,@aws-cdk/aws-s3-assets=1.53.0,@aws-cdk/aws-sqs=1.53.0,@aws-cdk/aws-ssm=1.53.0,@aws-cdk/cloud-assembly-schema=1.53.0,@aws-cdk/core=1.53.0,@aws-cdk/custom-resources=1.53.0,@aws-cdk/cx-api=1.53.0,@aws-cdk/region-info=1.53.0,jsii-runtime=node.js/v12.16.3
Parameters:
  AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3BucketCD049D8F:
    Type: String
    Description: S3 bucket for asset "aa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622f"
  AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3VersionKeyEB34933F:
    Type: String
    Description: S3 key for asset version "aa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622f"
  AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fArtifactHash25AFBA3C:
    Type: String
    Description: Artifact hash for asset "aa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622f"
Outputs:
  conferenceschedulerapiEndpointB7025EA3:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: conferenceschedulerapiF4E213A7
          - .execute-api.us-west-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: conferenceschedulerapiDeploymentStageprodBD2ECBF7
          - /
```

## Command used to start LocalStack
`docker-compose up`

docker-compose config file:

```yml
version: '3.7'
services:
  localstack:
    image: localstack/localstack-full:latest
    ports:
      - '53:53'
      - '443:443'
      - '4510-4520:4510-4520'
      - '4566-4620:4566-4620'
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - DATA_DIR=/tmp/localstack/confscheduler-data
      - DEBUG=true
      - DEFAULT_REGION=us-west-1
      - DOCKER_HOST=unix://var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - LOCALSTACK_API_KEY=...
      - PORT_WEB_UI=8080
      - SERVICES=cloudformation,kms,cloudwatch,ssm,serverless
      - USE_LIGHT_IMAGE=false
    volumes:
      - .localstack:/tmp/localstack
      - /var/run/docker.sock

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
`aws cloudformation update-stack --stack-name ConferenceSchedulerStack --endpoint http://localhost:4566 --profile offline --template-body file://./template.yml --parameters '[{"ParameterKey":"AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3BucketCD049D8F","ParameterValue":"cdktoolkit-stagingbucket-bt3m65cwv18w"},{"ParameterKey":"AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fS3VersionKeyEB34933F","ParameterValue":"assets/||aa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622f.zip"},{"ParameterKey":"AssetParametersaa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622fArtifactHash25AFBA3C","ParameterValue":"aa1cc673312c2caa4e64f7daca46c2372c0f4bcbed90f21d591fdc8bb279622f"}]'`

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-223) by [Unito](https://www.unito.io/learn-more)
