### ISSUE TITLE
Latest docker container has broken S3 to SQS notifications

### ISSUE THREAD

**Issue by samudurand** [localstack/localstack#2816]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
The container tagged "latest" on docker hub (which I assume is 0.11.3) has broken notifications between S3 and SQS. I had to back down to 0.11.0 to get one that worked (I haven't tested the versions between). ]

Another bug less problematic is that you cannot create SQS queues with `awslocal`, the queues created that way are not available when using `list-queues`, they need to be created using `aws --endpoint-url` (see Steps To reproduce)

## Expected behavior
When configuring S3 notifications to SQS with the following configuration, a message should be sent to SQS:

```
{
  "QueueConfigurations": [
    {
      "QueueArn": "arn:aws:sqs:eu-west-1:000000000000:documents-created",
      "Events": [
        "s3:ObjectCreated:*"
      ]
    }
  ]
}
```

## Actual behavior
An error is generated in the docker-compose logs : 

```
localstack_1  | 2020-08-07T09:03:52:WARNING:localstack.services.s3.s3_listener: Unable to send notification for S3 bucket "documents-bucket" to SQS queue "arn:aws:sqs:eu-west-1:000000000000:documents-created": An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueUrl operation: The specified queue does not exist for this wsdl version.
```

# Steps to reproduce
Use an init script containing the following lines (or use similar commands from the command line once the container is started and ready) : 

```
export AWS_ACCESS_KEY_ID=foobar
export AWS_SECRET_ACCESS_KEY=foobar
export AWS_DEFAULT_REGION=eu-west-1

awslocal s3 mb s3://documents-bucket
aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name documents-created # Cannot use awslocal, the queue is not created properly
awslocal s3api put-bucket-notification-configuration --bucket documents-bucket --notification-configuration file:///docker-entrypoint-initaws.d/notification.json
```

## Command used to start LocalStack
Docker compose file : 

```
version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4572:4572"  # S3
      - "4576:4576"  # SQS
    environment:
      LOCALSTACK_SERVICES: s3,sqs
    volumes:
      - ./localstack-aws:/docker-entrypoint-initaws.d
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-232) by [Unito](https://www.unito.io/learn-more)
