### ISSUE TITLE
Lambda executor incompatible with aws-lambda-java-events version 3.x

### ISSUE THREAD

**Issue by srt4** [localstack/localstack#2852]
# Type of request: This is a ...
[x] feature request

# Detailed description
`cloud.localstack.LambdaExecutor` included with `localstack-utils-fat.jar` imports `aws-lambda-java-events` from major version 2.

The `S3Event` class from 2.x and 3.x contains a `List<S3EventNotificationRecord>`, however between 2.x and 3.x of the SDK, the package of `S3EventNotification` has changed. A Lambda function compiled with version 3 does not recognize the input provided by the `LambdaExecutor`. 

For example: 

3.1.6 (used to build the Lambda function): 
`com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification`

2.x (included with `localstack-utils-fat.jar`: 
`com.amazonaws.services.s3.event.S3EventNotification`

A workaround is to build the Lambda function with 2.x of `aws-lambda-java-events`. 

## Expected behavior
The `S3Event` passed in by `LambdaExecutor` should be compatible with the version of `aws-lambda-java-events` used by the `RequestHandler`. 

## Actual behavior
The `S3Event` is created using the 2.x version of the `aws-lambda-java-events` SDK, which will cause a `ClassNotFoundException` when passed to a `RequestHandler` using version 3.x. 

# Steps to reproduce
## Command used to start LocalStack
`docker-compose.yml`

```yml
version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: file_reader_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,iam
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
In `build.gradle`: 

```groovy
dependencies {
    // ...
    compile group: 'com.amazonaws', name: 'aws-lambda-java-events', version: '3.1.0'
```

In the `RequestHandler`: 

```java
public class FileReader implements RequestHandler<S3Event, Object> {

  public Object handleRequest(S3Event event, Context context) {
    String key = getS3Key(event); 
    // ... 
  }
 
  public static String getS3Key(S3Event event) {
    try {
      // ClassNotFound exception occurs here 
      return event.getRecords().get(0).getS3().getObject().getKey();
    }
    catch (Exception any) {
      // ...
    }
  }

} 
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-237) by [Unito](https://www.unito.io/learn-more)

**Comment by Guanchuwu** [comment]
This post is so nice. Have you fixed this issue? I have met the same issue while I was developing on lambda though localstack. 
Would love to hear some feedback.
Thanks.

**Comment by sergey-morenets** [comment]
@Guanchuwu No, this issue is still reproduces in the latest LocalStack version (0.13.1)

**Comment by drmcl** [comment]
any update on this?

**Comment by aktakalariya** [comment]
Hello All, I am also facing this same issue in latest version also. Is there any work around or solution for this issue?

**Comment by joe4dev** [comment]
Hi @srt4, thanks for reaching out and providing a useful example.

## Reproduction

I can reproduce this issue when using the `local` Lambda executor (see [Lambda Executor Modes](https://docs.localstack.cloud/references/lambda-executors/) in the docs).
Details: I get a `ClassCastException` using the old provider and the new Lambda provider currently doesn't support creating Java functions in local mode (Function status: `Error while creating lambda: Docker not available`).

## Workaround

Especially for Java, I recommend using the default `docker` Lambda executor mode here. Update the `docker-compose.yml` as follows:

```yaml
version: '3'
services:
  localstack:
    image: localstack/localstack:1.3.0
    # Alternatively use the very latest build but remember to pull for updating
    # image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"
    # environment:
      # Deprecated: see https://docs.localstack.cloud/references/configuration/#deprecated
      # - SERVICES=s3,lambda,iam
      # Explicitly configure Docker socket if not detected automatically
      # - DOCKER_HOST=unix:///var/run/docker.sock
      # Optionally use new lambda provider
      # - PROVIDER_OVERRIDE_LAMBDA=asf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Notable changes:

1. Under `volumes`, add the bindmount of the Docker socket such that LocalStack has access to the Docker daemon to launch Lambdas.
2. Change the `container_name` to `localstack_main`
3. Remove the deprecated `SERVICES` flag because all services are now loaded lazily by default

Hint: you can validate the `docker-compose.yml` config using the CLI `localstack config validate --file docker-compose.yml`

## Follow-Up

Does this fix the issue for you @srt4 @aktakalariya @drmcl @sergey-morenets @Guanchuwu
