### ISSUE TITLE
Ansible <->Localstack:: Unable to determine forwarding port for API "localhost"

### ISSUE THREAD

**Issue by szandala** [localstack/localstack#2902]
# Type of request: This is a ...
[X] bug report
[ ] feature request

# Detailed description
When trying to launch dummy EC2 via I receive error:
`localstack    | 2020-08-28T21:05:29:INFO:localstack.services.edge: Unable to determine forwarding port for API "localhost" - please make sure this API is enabled via the SERVICES configuration`
...

## Command used to start LocalStack
```yaml
version: '3.7'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sts,ec2
      - DEBUG=1
      - DATA_DIR=/data
      - USE_SSL=0
      - DEFAULT_REGION=eu-west-2
    volumes:
      - /localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Ansible playbook with task:

```yaml
    - name: Launch new TEST instance
      ec2:
        aws_access_key: funny_key
        aws_secret_key: even_more_funny_key
        validate_certs: false
        ec2_url: "http://localhost:4566"
        debug_botocore_endpoint_logs: true
        instance_type: "t2.micro"
        image: "{{ ami_find.images[0].image_id }}"
      register: test_instance
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-242) by [Unito](https://www.unito.io/learn-more)

**Comment by szandala** [comment]
@ninhkd : can I help You somehow in debugging this?

**Comment by szandala** [comment]
Any idea on this issue?

**Comment by whummer** [comment]
Thanks for reporting @szandala . It's been a while since this issue has been opened - can you please provide some more details about the exact setup you're using? It seems that there are multiple different versions of AWS modules for Ansible.

With a recent version of Ansible:
```
$ ansible --version
ansible [core 2.11.7]
...
```

... the following config seems toe deploy properly - or at least correctly interact with the LocalStack APIs:
```
- name: My playbook
  hosts: localhost
  module_defaults:
    group/aws:
      aws_access_key: "test"
      aws_secret_key: "test"
      region: "us-east-1"
      endpoint_url: "http://localhost:4566"
  tasks:
    - ec2_instance:
        image:
          id: test123
```

Please let us know if the problem persists - happy to look into it in more detail if you can provide an isolated example to replicate this issue.. Thanks!
