### ISSUE TITLE
SQS -Creating queue via cli doesn't appear when trying to use it via SDK

### ISSUE THREAD

**Issue by joro550** [localstack/localstack#2913]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I am creating a queue via the aws cli, I can see in the cli that it has been created successfully but when I try and add a message to it via the sdk it seems to fail.

Few notes:
 - Yes I can add messages to a cli created queue from the cli
 - Yes I can create and add a message to a queue created via the sdk but it doesn't appear via the cli

## Expected behavior
I create a queue via the cli and can use it via the sdk

## Actual behavior
Sdk throws "Queue Does not exist" error

# Steps to reproduce

* Create queue via the cli
* Run code 

## Command used to start LocalStack
`docker compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

docker compose:
```
version: '3.4'
 services:
  test.localstack:
    container_name: test-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Code:
```
using System;
using Amazon;
using Amazon.SQS;
using Amazon.SQS.Model;
using System.Threading.Tasks;

namespace ConsoleApp7
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var sqsClient = new AmazonSQSClient(new AmazonSQSConfig
            {
                UseHttp = true,
                
                RegionEndpoint = RegionEndpoint.EUWest1,
                ServiceURL = "http://localhost:4566"
            });


            var queues = await sqsClient.ListQueuesAsync(new ListQueuesRequest()); // this will give a response with 0 queues

            // var queue = await sqsClient.CreateQueueAsync(new CreateQueueRequest("MarksQueue2"));

            await sqsClient.SendMessageAsync(new SendMessageRequest("http://localhost:4566/000000000000/MarksQueue2",
                $"Hello World {Guid.NewGuid()}"));


            var attributes = await sqsClient.GetQueueAttributesAsync(new GetQueueAttributesRequest
            {
                QueueUrl = "http://localhost:4566/000000000000/MarksQueue2"
            });


            Console.WriteLine("Hello World!");
        }
    }
}

```
Create queue via the cli:

```
aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/MarksQueue2"
    ]
}
```

*Just to note*: I know if you use docker compose and run the application within the container you have to use `test.localstack:4566` to connect to the container - I have tried this both ways and neither work. The example above is me running the test applicaiton as a stand alone console application

*Another note*: I feel like I should mention my default region is eu-west-1:

```
> aws --endpoint-url=http://localhost:4566 configure get region
 eu-west-1
```
