### ISSUE TITLE
SNS message ID doesn't match in the response and the notification

### ISSUE THREAD

**Issue by ignas-sakalauskas-cko** [localstack/localstack#2924]
# Type of request: This is a ...

[x] bug report
[] feature request

# Detailed description

Publishing a new SNS message returns a message ID that doesn't match the message ID in the notification sent.

## Expected behavior

Message ID returned after publishing the SNS notification should be the same as in the notification sent.

## Actual behavior

Publishing SNS notification returns wrong and cut off message ID.

# Steps to reproduce

## Command used to start LocalStack

```
version: "3.7"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb,secretsmanager,sns,sqs,es
      - HOSTNAME=localstack
      - DEFAULT_REGION=eu-west-1
    ports:
      - "4566:4566"
      - "4571:4571"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Command:
```
awslocal sns publish --topic-arn arn:aws:sns:eu-west-1:000000000000:notifications --message "test"
```
Response:
```
{
    "MessageId": "bbff1eea"
}
```

However, the actual message ID in the notification was `0a520ffc-028e-44c8-a6c6-7e528a90f610`
