### ISSUE TITLE
Creation of Elastic Search using LocalStack

### ISSUE THREAD

**Issue by hacker7897iiita** [localstack/localstack#2944]
# Type of request: bug report
I was not able to create an elastic search using localstack 0.11.0. I have been trying for days but was not able to figure the mistake. I get this error whenever I execute my tests -  java.lang.IllegalStateException: Service to port mapping has not been determined yet

[x] bug report
[ ] feature request

# Detailed description
docker.yml file

```
version: '3'
services:
  localstack:
    image: localstack/localstack:0.11.0
    container_name: pay_payment_visualizations_service_localstack
    ports:
      - "3575:4566"
    environment:
      - DEFAULT_REGION=us-west-2
      - SERVICES=s3
```

My code to create elastic search

```
@ExtendWith(LocalstackDockerExtension.class)
@LocalstackDockerProperties(services = { "es" })
public class LocalStackClass {
    public static void startElasticSearch() {
        final String esEndpoint = Localstack.INSTANCE.getEndpointElasticsearch();
        final AwsClientBuilder.EndpointConfiguration esEndpointConfiguration = new AwsClientBuilder.EndpointConfiguration(esEndpoint, "us-west-2");
        final AWSElasticsearch esClient = AWSElasticsearchClientBuilder.standard().
            withEndpointConfiguration(esEndpointConfiguration).
            build();

        final CreateElasticsearchDomainRequest createElasticsearchDomainRequest = new CreateElasticsearchDomainRequest();
        createElasticsearchDomainRequest.setDomainName("es1");
        esClient.createElasticsearchDomain(createElasticsearchDomainRequest);
    }
}
```

...

## Expected behavior 
Should create an elastic search 

...

## Actual behavior
 java.lang.IllegalStateException: Service to port mapping has not been determined yet

...

# Steps to reproduce
## Command used to start LocalStack
./graldew clean build
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-253) by [Unito](https://www.unito.io/learn-more)
