### ISSUE TITLE
Service "dynamodb" not yet available, retrying

### ISSUE THREAD

**Issue by vvmoorthy** [localstack/localstack#2960]
# Type of request: This is a ...
[ X] bug report
[ ] feature request

# Detailed description
We are attempting to use AWS Localstack as part of our CI/CD pipeline. Our service containers run in Kubernetes pods and we are trying to bring up AWS Localstack container inside a kube pod to test our services using kinesis. The container starts but then we keep getting the message: WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying... 
...

## Expected behavior
AWS Localstack starts for Kinesis and Dynamodb
...

## Actual behavior
From Container logs:
aws-localstack Waiting for all LocalStack services to be ready

aws-localstack Waiting for all LocalStack services to be ready

aws-localstack Waiting for all LocalStack services to be ready

WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying... 

From localstack_infra.err has the following:


```
2020-09-03T16:16:23:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
2020-09-03T16:16:37:ERROR:localstack.services.dynamodb.dynamodb_starter: DynamoDB health check failed:  Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/plugins.py", line 96, in check_infra
    check_service_health(api=name, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 115, in check_service_health
    raise e
  File "/opt/code/localstack/localstack/services/plugins.py", line 111, in check_service_health
    plugin.check(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/plugins.py", line 45, in check
    return self.check_function(expect_shutdown=expect_shutdown, print_error=print_error)
  File "/opt/code/localstack/localstack/services/dynamodb/dynamodb_starter.py", line 29, in check_dynamodb
    assert isinstance(out['TableNames'], list)
TypeError: 'NoneType' object is not subscriptable
```

From localstack_infra.log has the following:


```
│ aws-localstack 2020-09-03 07:58:31,680 INFO supervisord started with pid 13                                                                                                                                                                                                
│ aws-localstack 2020-09-03 07:58:32,681 INFO spawned: 'dashboard' with pid 19                                                                                                                                                                                               
│ aws-localstack 2020-09-03 07:58:32,683 INFO spawned: 'infra' with pid 20                                                                                                                                                                                                   
│ aws-localstack 2020-09-03 07:58:32,696 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)                                                                                                                               │
│ aws-localstack 2020-09-03 07:58:32,700 INFO exited: dashboard (exit status 0; expected)                                                                                                                                                                                    
│ aws-localstack (. .venv/bin/activate; exec bin/localstack start --host)                                                                                                                                                                                                    
│ aws-localstack LocalStack version: 0.11.4                                                                                                                                                                                                                                  
│ aws-localstack Starting local dev environment. CTRL-C to quit.                                                                                                                                                                                                             
│ aws-localstack 2020-09-03T07:58:33:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7fedf59a3670>                                                                                              
│ aws-localstack 2020-09-03T07:58:33:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7fedf675a8b0>                                                                                               │
│ aws-localstack 2020-09-03T07:58:33:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7fedf675a5e0>                                                                                                   │
│ aws-localstack 2020-09-03 07:58:34,647 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)                                                                                                                                   │
│ aws-localstack Waiting for all LocalStack services to be ready                                                                                                                                                                                                             │ aws-localstack Starting edge router (https port 4566)...                                                                                                                                                                                                                   │ aws-localstack 2020-09-03T07:58:41:DEBUG:bootstrap.py: Plugin loading took 7.536028861999512 sec                                                                                                                                                                           │ aws-localstack 2020-09-03T07:58:41:INFO:botocore.credentials: Found credentials in environment variables.                                                                                                                                                                  │ aws-localstack 2020-09-03T07:58:41:INFO:botocore.credentials: Found credentials in environment variables.                                                                                                                                                                  │ aws-localstack Running on 0.0.0.0:4566 over https (CTRL + C to quit)                                                                                                                                                                                                       │ aws-localstack Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...                                                                                                                                                                    │ aws-localstack Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...                                                                                                                                                                     │ aws-localstack Initializing DynamoDB Local with the following configuration:                                                                                                                                                                                               │ aws-localstack Port:    51723                                                                                                                                                                                                                                              │ aws-localstack InMemory:    false                                                                                                                                                                                                                                          │ aws-localstack DbPath:    /tmp/localstack/data/dynamodb                                                                                                                                                                                                                    │ aws-localstack SharedDb:    true                                                                                                                                                                                                                                           │ aws-localstack shouldDelayTransientStatuses:    false                                                                                                                                                                                                                      │ aws-localstack CorsParams:    *                                                                                                                                                                                                                                            │ aws-localstack Listening at http://:::51919                                                                                                                                                                                                                                │ aws-localstack                                                                                                                                                                                                                                                             │ aws-localstack Running on 0.0.0.0:4569 over http (CTRL + C to quit)                                                                                                                                                                                                        │ aws-localstack Running on 0.0.0.0:4566 over https (CTRL + C to quit)                                                                                                                                                                                                       │ aws-localstack Starting mock DynamoDB service in http ports 4566 (recommended) and 4569 (deprecated)...                                                                                                                                                                    │ aws-localstack Starting mock Kinesis service in http ports 4566 (recommended) and 4568 (deprecated)...                                                                                                                                                                     │ aws-localstack Initializing DynamoDB Local with the following configuration:                                                                                                                                                                                               │ aws-localstack Port:    51723                                                                                                                                                                                                                                              │ aws-localstack InMemory:    false                                                                                                                                                                                                                                          │ aws-localstack DbPath:    /tmp/localstack/data/dynamodb                                                                                                                                                                                                                    │ aws-localstack SharedDb:    true                                                                                                                                                                                                                                          │ aws-localstack shouldDelayTransientStatuses:    false                                                                                                                                                                                                                      │ aws-localstack CorsParams:    *                                                                                                                                                                                                                                            │ aws-localstack Listening at http://:::51919                                                                                                                                                                                                                                │ aws-localstack                                                                                                                                                                                                                                                             │ aws-localstack Running on 0.0.0.0:4569 over http (CTRL + C to quit)                                                                                                                                                                                                        │ aws-localstack Running on 0.0.0.0:4568 over http (CTRL + C to quit)                                                                                                                                                                                                        │ aws-localstack Waiting for all LocalStack services to be ready                                                                                                                                                                                                             │ aws-localstack Waiting for all LocalStack services to be ready                                                                                                                                                                                                             │ aws-localstack 2020-09-03T07:58:57:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...                                                                                                                                                  │
```

...

# Steps to reproduce
## Command used to start LocalStack
kubernetes manifest

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-localstack
  labels:
    product: apptest
    type: service
    app: aws-localstack
    version: v1
    app.kubernetes.io/version: "1.16.0"
spec:
  selector:
    matchLabels:
      app: aws-localstack
      version: v1
  template:
    metadata:
      labels:
        app: aws-localstack
        version: v1
        app: aws-localstack
        version: v1
        app.kubernetes.io/version: "1.16.0"
    spec:
      volumes:
          - name: dockersock
            hostPath:
              path: /var/run/docker.sock
          - name: localstacktmp
            hostPath:
              path: /tmp/localstack
      containers:
        - name: aws-localstack
          image: localstack/localstack:latest
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "1000m"
          ports:
            - name: localstack-port
              containerPort: 4566
            - name: kinesis-port
              containerPort: 4568
            - name: dynamodb-port
              containerPort: 4569
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
            - name: localstacktmp
              mountPath: /tmp
          env:
          - name:  SERVICES
            value: "kinesis,dynamodb"
          - name:  DATA_DIR
            value: "/tmp"
          - name:  AWS_ACCESS_KEY_ID
            value: "localid"
          - name:  AWS_SECRET_ACCESS_KEY
            value: "localkey"
          - name:  AWS_DEFAULT_REGION
            value: "us-east-1"
          - name:  DEBUG
            value: "1"
...
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...



┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-258) by [Unito](https://www.unito.io/learn-more)
