### ISSUE TITLE
SQS receive-message always returns all MessageAttributes

### ISSUE THREAD

**Issue by philBrown** [localstack/localstack#2965]
# Type of request: This is a ...

- [x] bug report
- [ ] feature request

# Detailed description

When retrieving messages from SQS, LocalStack returns all `MessageAttributes` no matter what `message-attribute-names` is set to.

This deviates from the real SQS which will only return the `MessageAttributes` specified, or none if the option is omitted.

## Expected behavior

When using `sqs receive-message`, LocalStack SQS returns the `MessageAttributes` specified in the `message-attribute-names` option or none if omitted.

## Actual behavior

LocalStack SQS always returns all `MessageAttributes`, no matter what option is passed.

# Steps to reproduce

1. Create a queue and send a message to it with message attributes

    ``` bash
    awslocal sqs create-queue --queue-name MyQueue
    awslocal sqs send-message --queue-url http://localhost:4566/000000000000/MyQueue \
      --message-body "hi" \
      --message-attributes 'firstAttribute={DataType=String, StringValue="hello world"}, secondAttribute={DataType=String,StringValue="goodbye world "}'
    ```
2. Receive the message from the queue, specifying no message attributes or even a specific attribute name (not "All")

    ``` bash
    awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/MyQueue
    ```
   or
    ``` bash
    awslocal sqs receive-message --queue-url http://localhost:4566/000000000000/MyQueue \
      --message-attribute-names "firstAttribute"
    ```

## Command used to start LocalStack

Using `docker-compose.yml`
``` yml
version: '2.1'

services:
  localstack:
    container_name: "aws-localstack"
    image: localstack/localstack:0.11.4
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - DEFAULT_REGION=ap-southeast-2
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/docker-entrypoint-initaws.d"
```
``` bash
docker-compose up
```
