### ISSUE TITLE
Connection was closed before we received a valid response from endpoint URL

### ISSUE THREAD

**Issue by saley89** [localstack/localstack#3080]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

When using the latest version of localstack (0.11.6):

localstack/localstack:latest
DIGEST:sha256:17351895c3ec7df5a014cf94f965223ac80d678535ccae05a4e9d2898999daaf

To connect to Kinesis port (4568), we are seeing "Connection was closed before we received a valid response from endpoint url" error.  On previous version from 0.11.5 previous, this did not happen.  We have now had to fix our version to 0.11.5 to continue with development.

## Expected behavior

Using the latest version of localstack allows us to connect to the Kinesis port without issue.

```
$ aws --endpoint-url http://localhost:4568 --region eu-west-1 kinesis list-streams
{
    "StreamNames": []
}
```
## Actual behavior

When attempting to connect to localstack on port 4568 we see the error.

```
$ aws --endpoint-url http://localhost:4568 --region eu-west-1 kinesis list-streams

Connection was closed before we received a valid response from endpoint URL: "http://localhost:4568/".
```

# Steps to reproduce

## Command used to start LocalStack

```
docker run -it localstack/localstack:latest
```
## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
$ aws --endpoint-url http://localhost:4568 --region eu-west-1 kinesis list-streams
```

**Comment by ahmedshuhel** [comment]
@saley89 See if this works

```
aws --endpoint-url http://localhost:4566 --region eu-west-1 kinesis list-streams
```

> Note: Starting with version 0.11.0, all APIs are exposed via a single edge service, which is accessible on http://localhost:4566 by default (customizable via EDGE_PORT, see further below).

**Comment by whummer** [comment]
Thanks for reporting @saley89 , and thanks for providing the solution @ahmedshuhel . As has been mentioned, please use the single port `4566` (edge service) to access all LocalStack APIs from now on. Thanks

**Comment by kngmat004** [comment]
Unfortunately I think this is still a problem.  There appears to be some local python dependency causing the underlying issue:


`2021-05-27 09:14:50,741 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://localhost:4566/, headers={'X-Amz-Target': b'DynamoDB_20120810.CreateTable', 'Content-Type': b'application/x-amz-json-1.0', 'User-Agent': b'aws-cli/2.0.22 Python/3.7.3 Linux/5.4.0-73-generic botocore/2.0.0dev26', 'X-Amz-Date': b'20210527T071450Z', _request, SignedHeaders=content-type;host;x-amz-date;x-amz-target, , 'Content-Length': '260'}>
2021-05-27 09:14:50,742 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:4566
2021-05-27 09:14:50,743 - MainThread - botocore.hooks - DEBUG - Event needs-retry.dynamodb.CreateTable: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x7fe488305048>>
2021-05-27 09:14:50,743 - MainThread - botocore.retries.standard - DEBUG - Retry needed, retrying request after delay of: 0.1188545362609198
2021-05-27 09:14:50,743 - MainThread - botocore.endpoint - DEBUG - Response received to retry, sleeping for 0.1188545362609198 seconds
2021-05-27 09:14:50,862 - MainThread - botocore.hooks - DEBUG - Event request-created.dynamodb.CreateTable: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fe4883b4898>>
2021-05-27 09:14:50,862 - MainThread - botocore.hooks - DEBUG - Event choose-signer.dynamodb.CreateTable: calling handler <function set_operation_specific_signer at 0x7fe48a106d08>
2021-05-27 09:14:50,863 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2021-05-27 09:14:50,863 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
`

**Comment by kevinadhiguna** [comment]
I faced the same error. I was completely new to Localstack and was trying to spin up a docker container powered by docker-compose.yml.

## Steps to reproduce :

What I did was :
1. Copying the entire docker-compose.yml from https://github.com/localstack/localstack/blob/master/docker-compose.yml
```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro
      - "127.0.0.1:53:53/udp"            # only required for Pro
      - "127.0.0.1:443:443"              # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

2. As I wanted S3 service, I set up `.env` file like this : 
```
LOCALSTACK_DOCKER_NAME=aws_localstack
SERVICE=s3
```

3. Run : `docker-compose up`.

![0 docker-ctr-log](https://user-images.githubusercontent.com/43397636/141278148-8bd7ab7d-7627-428f-8eed-983ec7868d4d.png)

The log said the mock S3 service was already running on port 4556.

4. Then I opened a new tab (splitted the terminal) without terminating the docker process and ran `aws --endpoint-url http://localhost:4566 s3 ls` to list s3 buckets. I saw the error like below :

![1 aws-cli-s3-command-failed](https://user-images.githubusercontent.com/43397636/141280007-a6a584bc-552b-49aa-845b-c4fa95e5f9db.png)

---

<br />

## Solution that worked for me: 

What I did was modifying `ports` in the docker-compose.yml :
```diff
 ports:
      # - "127.0.0.1:53:53"                # only required for Pro
      # - "127.0.0.1:53:53/udp"            # only required for Pro
      # - "127.0.0.1:443:443"              # only required for Pro
      # - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
-     - "127.0.0.1:4566:4566"
-     - "127.0.0.1:4571:4571"
+    - "4566:4566"
+    - "4571:4571"
```

The whole `docker-compose.yml` was like this :
```yml
version: "3.8"

services:
  localstack:
    # "${LOCALSTACK_DOCKER_NAME-localstack_main}" means docker-compose.yml will refer to the value of variable called LOCALSTACK_DOCKER_NAME in a .env file. Otherwise the docker container is named "localstack_main".
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # From 2020-07-11 onwards, the default image "localstack/localstack" in Docker Hub refers to the “light version”, which has some large dependency files like Elasticsearch removed
    # In case you need the full set of dependencies, the "localstack/localstack-full" image can be used instead
    image: localstack/localstack
    network_mode: bridge
    ports:
      ### Default config ###
      #- "127.0.0.1:53:53"                # only required for Pro
      #- "127.0.0.1:53:53/udp"            # only required for Pro
      #- "127.0.0.1:443:443"              # only required for Pro
      #- "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      #- "127.0.0.1:4566:4566"
      #- "127.0.0.1:4571:4571"
      ### Modified config ###
      - "4566:4566"
      - "4571:4571"
    environment:
      # Specify the services in a variable named SERVICES, otherwise localstack does not work...
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      #- LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

My repository for this project (including `.env.example`) is available here : https://github.com/kevinadhiguna/jiyu/tree/master/aws-localstack
