### ISSUE TITLE
Service not yet available (docker-compose)

### ISSUE THREAD

**Issue by zefexdeveloper** [localstack/localstack#3131]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I'm trying to run LocalStack using `docker-compose` but it doesn't seem to be working.

## Expected behavior

It should make the services available.

## Actual behavior

> localstack_1  | Waiting for all LocalStack services to be ready
> localstack_1  | 2020-10-19T16:32:09:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
> localstack_1  | 2020-10-19T16:32:12:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...
> localstack_1  | Waiting for all LocalStack services to be ready
> localstack_1  | 2020-10-19T16:32:15:WARNING:localstack.services.plugins: Service "dynamodb" not yet available, retrying...

# Steps to reproduce

## Command used to start LocalStack

```
version: "3"
services:
  localstack:
    image: localstack/localstack
    restart: always
    environment:
      SERVICES: ${LOCALSTACK_SERVICES}
      DEFAULT_REGION: ${LOCALSTACK_DEFAULT_REGION}
      DATA_DIR: ${LOCALSTACK_DATA_DIR}
    ports:
      - 4566:4566
    volumes:
      - ${LOCALSTACK_TMPDIR}:/tmp/localstack
```

.env:
```
LOCALSTACK_SERVICES="sqs,dynamodb,s3"
LOCALSTACK_DEFAULT_REGION="sa-east-1"
LOCALSTACK_TMPDIR=/tmp/localstack
LOCALSTACK_DATA_DIR=/tmp/localstack/data
```
