### ISSUE TITLE
Elasticsearch does not have the S3 plugins installed

### ISSUE THREAD

**Issue by rj93** [localstack/localstack#3141]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
I am trying to configure a Elasticsearch service, with a repository of type `s3`. However I am getting an error saying that the repository type `s3` does not exist, this is usually because it doesn't have the plugin installed.

## Expected behavior
When I create a Elasticsearch repository of type `s3` it is successful.

## Actual behavior
When I attempt to create a repository I get a 500 Internal Server error with response body:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "repository_exception",
                "reason": "[s3_repository] repository type [s3] does not exist"
            }
        ],
        "type": "repository_exception",
        "reason": "[s3_repository] repository type [s3] does not exist"
    },
    "status": 500
}
```

# Steps to reproduce
Using this `docker-compose.yml`

```yaml
version: "3.8"
services:
  localstack:
    image: localstack/localstack-full:0.11.6
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=s3,es
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/volumes/localstack:/tmp/localstack"
```

## Command used to start LocalStack
```bash
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```bash
awslocal s3api create-bucket --bucket my-bucket
awslocal es create-elasticsearch-domain --domain-name domain-test2 --elasticsearch-version 6.4
```

## Create Elasticsearch repository
```bash
curl --location --request PUT 'localhost:4571/_snapshot/s3_repository' \
--header 'Content-Type: application/json' \
--data-raw '{
  "type": "s3",
  "settings": {
    "bucket": "my-bucket",
    "region": "eu-west-1"
  }
}'
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-299) by [Unito](https://www.unito.io/learn-more)
