### ISSUE TITLE
S3 event not triggering the lambda function in localstack

### ISSUE THREAD

**Issue by iamjai-3** [localstack/localstack#3183]
**Serverless.yml**

```
service: ls-node

frameworkVersion: '2'


plugins:
  - serverless-plugin-typescript
  - serverless-localstack
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-s3-local
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: us-east-1
  profile: test

  iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutBucketNotification
          - s3:GetObject
        Resource: ["arn:aws:s3:::iamjai-dev/*"]

functions: 
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: iamjai-dev
          events: 
            - s3:ObjectCreated:*
    environment:
      TEST_NAME: "iamjai"
      TEST_MAIL: "jai@jai.com"

custom:
  localstack:
    stages:
      - local
  bucket: iamjai-dev
  dotenv:
    path: ../.env
    basePath: ../
    logging: false
    # include:
    #   - CLIENT
    #   - DATE
  s3:
    host: localhost
    directory: /tmp
```

**handler.js**

```
'use strict';
'use strict';

const AWS = require('aws-sdk');
const s3 = new AWS.S3({ 
    accessKeyId: "1234", 
    secretAccessKey: "5678", 
    endpoint: new AWS.Endpoint('http://localhost:4566'), 
    s3ForcePathStyle: true, 
  
});

const csv = require('csvtojson')

module.exports.hello = async event => {
  console.log("Executed!!!!!")
  const Bucket = event.Records[0].s3.bucket.name;
  const Key = event.Records[0].s3.object.key;
  const data = await s3.getObject({ Bucket, Key }).promise();
  const params = {
            Bucket: Bucket,
            Key: Key,
          };
  const stream = s3.getObject(params).createReadStream();
  // convert csv file (stream) to JSON format data
  const jsonArray = await csv().fromStream(stream);
  console.log(JSON.stringify(stream))
  console.log(jsonArray.length);
  // console.log('NAME: ', process.env.NAME);
  // console.log('EMAIL: ', process.env.MAIL);
  console.log("Raw text:\n" + data.Body.toString('ascii'));
  
};
```

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-77) by [Unito](https://www.unito.io/learn-more)
