### ISSUE TITLE
Cognito deployment breaks with lambda triggers

### ISSUE THREAD

**Issue by msteve-tokzu** [localstack/localstack#3189]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
When custom cognito triggers are deployed using the CDK, the deployment fails. 

Initially it appeared as though this was a roles issue but when `myDdbTable.grantReadWriteData(lambdaFn);` is done, the lambda won't deploy (`awslocal lambda list-functions` returns an empty list). So that is probably another issue here. Not sure if this is related...

When I try to deploy with a a `cdklocal deploy` the following error occurs in the logs and the deployment fails:
```
localstack_main | 2020-10-28T00:45:37:DEBUG:localstack.services.cloudformation.cloudformation_starter: Unable to resolve attribute reference ['cogsignupServiceRoleFE6CAACA', 'Arn'] in resource map keys ['mytable0FC8E698', 'apilambdaServiceRole047C112A', 'apilambda941BBFFC', 'cogsignupServiceRoleFE6CAACA', 'cogsignupF20EC8E8', 'cogsignupPreSignUpCognito639C1C9E', 'ReproStackpool94FDFD3C', 'ReproStackweb296741DF', 'myapiendpoint332215CC', 'myapiendpointCloudWatchRole7220F502', 'myapiendpointAccount8810C881', 'myapiendpointDeploymentF8D80F44df6d5cf5e28dee64eb274f98db0924df', 'myapiendpointDeploymentStageprod17B567BB', 'myapiendpointapi5DBD5C76', 'myapiendpointapiproxy85819254', 'myapiendpointapiproxyANYApiPermissionReproStackmyapiendpointA0B7A40DANYapiproxy2477C754', 'myapiendpointapiproxyANYApiPermissionTestReproStackmyapiendpointA0B7A40DANYapiproxyDF9DE0AB', 'myapiendpointapiproxyANY2D8224A9', 'CDKMetadata']
localstack_main | 2020-10-28T00:45:37:WARNING:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:ReproStack-lambda-663e3059
localstack_main | 2020-10-28T00:45:37:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "cogsignupF20EC8E8": 'Role' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 283, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 355, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 337, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 318, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 778, in Lambda_create_from_cloudformation_json
localstack_main |     result = Lambda_create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/awslambda/models.py", line 539, in create_from_cloudformation_json
localstack_main |     "Role": properties["Role"],
localstack_main | KeyError: 'Role'
localstack_main |
localstack_main | 2020-10-28T00:45:37:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "cogsignupF20EC8E8": 'Role' Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 283, in parse_and_create_resource
localstack_main |     return _parse_and_create_resource(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 355, in _parse_and_create_resource
localstack_main |     raise moto_create_error
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 337, in _parse_and_create_resource
localstack_main |     resource = parse_and_create_resource_orig(
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/cloudformation/parsing.py", line 318, in parse_and_create_resource
localstack_main |     resource = resource_class.create_from_cloudformation_json(
localstack_main |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 778, in Lambda_create_from_cloudformation_json
localstack_main |     result = Lambda_create_from_cloudformation_json_orig(resource_name, cloudformation_json, region_name)
localstack_main |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/awslambda/models.py", line 539, in create_from_cloudformation_json
localstack_main |     "Role": properties["Role"],
localstack_main | KeyError: 'Role'
``` 

## Expected behavior

2 custom triggers are deployed that get triggered when a user signs up and confirms their sign up

## Actual behavior

Deployment fails

# Steps to reproduce

Deploy the following stack (used cdklocal CLI version `1.64.1-dev1` and localstack `0.12.0`). I can't use a later version due to the moto issue with cloudformation and Fn::GetAtt fails on a missing Lambda FunctionName parameter (verified it's present in the generated template)... I assume the GetAtt is a known issue based on moto defects.

Current dependencies used in the CDK:
```
    "@aws-cdk/aws-apigateway": "1.64.1",
    "@aws-cdk/aws-cognito": "1.64.1",
    "@aws-cdk/aws-dynamodb": "1.64.1",
    "@aws-cdk/aws-lambda": "1.64.1",
    "@aws-cdk/aws-s3-assets": "1.64.1",
    "@aws-cdk/core": "1.64.1",
```

Here is a repro CDK stack
```typescript
import * as cdk from "@aws-cdk/core";
import * as ddb from "@aws-cdk/aws-dynamodb";
import * as lambda from "@aws-cdk/aws-lambda";
import * as apigw from "@aws-cdk/aws-apigateway";
import * as cognito from "@aws-cdk/aws-cognito";
import {UserPool, AccountRecovery, StringAttribute} from "@aws-cdk/aws-cognito";
import { CfnOutput, CfnParameter, Duration } from "@aws-cdk/core";
import * as path from "path";

export class ReproStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create databases
    const myTable = new ddb.Table(this, "mytable", {
      partitionKey: {
        name: "Pk",
        type: ddb.AttributeType.STRING,
      },
      tableName: "mytable",
      billingMode: ddb.BillingMode.PAY_PER_REQUEST,
    });

    const lambdaFn = new lambda.Function(this, "apilambda", {
      code: lambda.Code.fromAsset(
        path.join(__dirname, "../../../out/function.zip")
      ),
      timeout: cdk.Duration.seconds(300),
      runtime: lambda.Runtime.GO_1_X,
      handler: "server_unix",
      environment: {
        TABLE_NAME: myTable.tableName,
      },
    });

    const localCode = lambda.Code.fromCfnParameters({
      bucketNameParam: new CfnParameter(this, "localBucketName", {
        default: "__local__",
        type: "String"
      }),
      objectKeyParam: new CfnParameter(this, "localObjectPath", {
        default: path.join(__dirname, "../../../out/"),
        type: "String"
      })
    });

    const signUpLambdaFn = new lambda.Function(this, "cogsignup", {
      code: localCode,
      timeout: cdk.Duration.seconds(300),
      runtime: lambda.Runtime.GO_1_X,
      handler: "cog_signup",
      environment: {
        USER_PROFILE_TABLE_NAME: myTable.tableName,
      },
    });
    
    // Issue #1: Lambda trigger will cause a cloudformation key error on Role.
    const postConfLambdaFn = new lambda.Function(this, "cogpostconf", {
      code: localCode,
      timeout: cdk.Duration.seconds(300),
      runtime: lambda.Runtime.GO_1_X,
      handler: "cog_postconf",
      environment: {
        USER_PROFILE_TABLE_NAME: myTable.tableName,
      },
    });

    // Create user pool
    const userPool: UserPool = new cognito.UserPool(this, id + "pool", {
      userPoolName: `${id}-pool`,
      autoVerify: {
        email: true
      },
      passwordPolicy: {
        minLength: 8,
        requireDigits: false,
        requireLowercase: false,
        requireSymbols: false,
        requireUppercase: false,
        tempPasswordValidity: Duration.days(7)
      },
      selfSignUpEnabled: true,
      accountRecovery: AccountRecovery.EMAIL_ONLY,
      signInAliases: {
        email: true,
        preferredUsername: true,
        username: true
      },
      signInCaseSensitive: false,
      standardAttributes: {
        givenName: {
          mutable: true,
          required: false
        },
        familyName: {
          mutable: true,
          required: false
        },
        email: {
          mutable: true,
          required: true
        },
        phoneNumber: {
          mutable: true,
          required: false
        },
        profilePicture: {
          mutable: true,
          required: false
        },
        birthdate: {
          mutable: true,
          required: false
        }
      },
      customAttributes: {
        'dummystuff': new StringAttribute({
          mutable: true
          
        })
      },
      lambdaTriggers: {
        preSignUp: signUpLambdaFn//,
        // Uncomment the line below to demonstrate Issue #1
        // postConfirmation: postConfLambdaFn
      }
    });

    const userPoolId = new CfnOutput(this, "UserPoolId", {
      value: userPool.userPoolId
    });

    // Create client with some cfn goodness
    const userPoolClient = new cognito.UserPoolClient(this, id + "web", {
      userPool: userPool,
      generateSecret: false,
      authFlows: {
        adminUserPassword: true,
        userPassword: true
      },
      oAuth: {
        callbackUrls: ["http://localhost:3000"],
        scopes: [
          cognito.OAuthScope.COGNITO_ADMIN,
          cognito.OAuthScope.EMAIL,
          cognito.OAuthScope.OPENID,
          cognito.OAuthScope.PHONE,
          cognito.OAuthScope.PROFILE
        ],
        flows: {
          authorizationCodeGrant: true,
          implicitCodeGrant: true
        }
      }
    });

    const userPoolClientId = new CfnOutput(this, "UserPoolClientId", {
      value: userPoolClient.userPoolClientId
    });

    // Issue #2 Uncomment these lines and no lambdas will deploy
    //myTable.grantReadWriteData(lambdaFn);
    //myTable.grantReadWriteData(signUpLambdaFn);
    //myTable.grantReadWriteData(postConfLambdaFn);

    const api = new apigw.RestApi(this, "myapiendpoint", {
      restApiName: "MyRestApi",
    });
    const apiRoot = api.root.addResource("api");
    const integration = new apigw.LambdaIntegration(lambdaFn);
    const proxy = apiRoot.addProxy({
      anyMethod: true,
      defaultIntegration: integration,
    });
  }
}
```

At first glance this almost seems like a dependency tree error with the resources but I haven't had a chance to go through the moto code to confirm this. I tried revving to localstack latest and also the latest version of cdklocal but then ran into the `Fn::GetAttr` issue in moto.

## Command used to start LocalStack

Localstack was deployed in docker compose with the following command `TMPDIR=`pwd`/lsdata docker-compose up --remove-orphans`

Prior to running the docker compose file, the lsdata directory is removed and a `docker-compose rm` is run.

Versions of docker:
* Docker Compose: `1.27.4`
* Docker: `19.03.13`

Here is the docker compose file. Excuse the mocks in here:
```yaml
version: "2.1"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.0
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      # - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=edge,logs,cloudwatch,cognito,ses,lambda,s3,dynamodb,cloudformation,apigateway,dynamodbstreams,es,iam
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=false
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - SMTP_HOST=smtpmock:1025
      - SMTP_USER=dummy
      - SMTP_PASS=dummy
      - SMTP_EMAIL=dummy@example.com
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  smtpmock:
    container_name: "${LOCALSTACK_DOCKER_NAME-smtpmock}"
    image: reachfive/fake-smtp-server
    ports:
      - "1025:25"
      - "1080:1080"
  #kibana:
    #image: amazon/opendistro-for-elasticsearch-kibana:1.8.0
    #build: .
    #container_name: "${LOCALSTACK_DOCKER_NAME-kibana}"
    #ports:
    #  - 5601:5601
    #expose:
    #  - "5601"
    #environment:
    #  ELASTICSEARCH_HOSTS: http://localstack:4571
    #depends_on:
    #  - localstack
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See above for snippets.
