### ISSUE TITLE
Get s3 object with presigned URL fails with SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by gsf4726** [localstack/localstack#3194]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Using the Node.js AWS SDK, I'm calling [`getSignedUrlPromise()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrlPromise-property) to generate a signed URL with localstack like:

```
let signedUrl = await this.s3.getSignedUrlPromise('getObject', signedUrlParms);
```

This function successfully generates the following URL:

```
http://localstack:4566/cfs-9/dev-machine/60c19060-1923-11eb-9caf-7b34a69cf076?AWSAccessKeyId=test&Expires=1603894600&Signature=WHqT7%2B623TR2HOmXuaIYQtTWEwI%3D
```

Then later I want download the S3 object using javascript/axios like:

```
response = await axios.get(signedUrl, { responseType: 'stream' });
```

## Expected behavior

The S3 object is successfully downloaded from the presigned URL.

## Actual behavior

An 403 response is returned when getting the S3 with the presigned URL:
```
<?xml version=\"1.0\" encoding=\"utf-8\"?>
<Error>
  <Code>SignatureDoesNotMatch</Code>
  <Message>The request signature we calculated does not match the signature you provided.                     Check your key and signing method.</Message>
  <RequestId>6dbd5c4c</RequestId>
  <HostId>7667071f</HostId>
  <AWSAccessKeyId>test</AWSAccessKeyId>
  <StringToSign>GET\n\n\n1603893567\n/cfs-9/dev-machine/60c19060-1923-11eb-9caf-7b34a69cf076</StringToSign>
  <SignatureProvided>XkuQ5akUzpbjzQ+12yurS5sOFd4=</SignatureProvided>
  <StringToSignBytes>586b755135616b557a70626a7a512b31327975725335734f4664343d</StringToSignBytes>
</Error>
```

Update: 
Should also note that this same code works fine in AWS. Also, and probably obviously, this code worked in localstack in versions 0.11.3 and earlier, before the signed URL authentication logic was added.
# Steps to reproduce

See above

## Command used to start LocalStack

docker-compose via:
```
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See above
