### ISSUE TITLE
Possible memory leak in sns and sqs services.

### ISSUE THREAD

**Issue by giancluciano** [localstack/localstack#3233]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
In the localstack docker image, I'm using the sns and sqs services for a project, when it start to process the messages the container starts to use more and more memory and when it finishes sending the messages the container doesn't drop the additional memory, so I have to restart the localstack to be able to execute the project routine several times.

...

## Expected behavior
* Clear the memory after a while.
...

## Actual behavior
* Memory consumption grows forever.
...

# Steps to reproduce
* Start the localstack container with docker-compose, using sns and sqs services
* Run terraform to create a topic and queue
* Sends messages while observing `docker stats`

## Command used to start LocalStack
This is my docker-compose.yml

```
    localstack:
        image: localstack/localstack-light
        container_name: localstack
        environment:
            - SERVICES=sqs,sns
            - DEFAULT_REGION=us-east-1
            - AWS_SQS_REGION=us-east-1
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=mock_access_key
            - AWS_SECRET_ACCESS_KEY=mock_secret_key
        ports:
            - "4566:4566"
    terraform:
        image: hashicorp/terraform:light
        entrypoint: /bin/sh -c
        command: ['/bin/terraform init /tf && /bin/terraform apply -auto-approve /tf']
        volumes:
          - type: 'bind'
            source: './localstack'
            target: '/tf'
        depends_on: 
            - localstack
```

And I just run `docker-compose run terraform` to start localstack.
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
...

┆Issue is synchronized with this [Jira Task](https://localstack.atlassian.net/browse/LOC-59) by [Unito](https://www.unito.io/learn-more)
