### ISSUE TITLE
put-object fails with 413 on big files ~2.4GB

### ISSUE THREAD

**Issue by adrienDog** [localstack/localstack#3257]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Hello,

thanks a lot for your project. I an working with GeoTIFF files that are usually several GB, hence I would benefit a lot I think from a the local aws environment provided by localstack.

Unfortunately when I try to upload a GeoTIFF of ~2.4GB it fails after 5s:

```
$ aws --endpoint-url http://localhost:4566 s3api put-object --bucket my-bucket --key test/cog.tif --body ./sources/cog.tif --acl public-read

An error occurred (413) when calling the PutObject operation: Request Entity Too Large
```

## Expected behavior
I expect to get a similar successful response like we do for smaller files:

```
$ aws --endpoint-url http://localhost:4566 s3api put-object --bucket my-bucket --key test/logs.txt --body ./sources/logs.txt --acl public-read
{
    "ETag": "\"4e5e862eb6f038444552c64dea355422\""
}
```

## Actual behavior
A 413 error is returned:

```
An error occurred (413) when calling the PutObject operation: Request Entity Too Large
```

# Steps to reproduce
## Command used to start LocalStack
```
docker-compose up -d
```

with docker-compose.yml as follows:

```yml
version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
On Ubuntu 20.04 using awscli:

```
$ aws --version
aws-cli/2.1.2 Python/3.7.3 Linux/5.4.0-53-generic exe/x86_64.ubuntu.20
```

Choose a file that is around 2.4GB and do the following:

### Create a bucket
```
aws --endpoint-url http://localhost:4566 s3api create-bucket --bucket my-bucket
```

### Upload the big file
```
aws --endpoint-url http://localhost:4566 s3api put-object --bucket my-bucket --key big_file --body ./sources/big_file --acl public-read
```

An error should occur:

```
An error occurred (413) when calling the PutObject operation: Request Entity Too Large
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-334) by [Unito](https://www.unito.io/learn-more)
