### ISSUE TITLE
Rust Lambda stuck in localstack

### ISSUE THREAD

**Issue by Frederick888** [localstack/localstack#3264]
# Type of request: This is a ...
[x] bug report
[ ] feature request

# Detailed description
Simple Rust Lambda function got stuck in localstack.

## Expected behavior
Lambda works normally as it does in AWS.

## Actual behavior
Lambda can start, but it gets stuck as soon as it tries to read request.

Via `docker logs <container id>` I can see:
```
Started!
START RequestId: 8736a8ca-e1b1-151b-ec25-1d825d277d49 Version: $LATEST
```

# Steps to reproduce
## Command used to start LocalStack
```yaml
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR-/tmp/localstack}
      - HOSTNAME_EXTERNAL=xxx.lan
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Then `docker-compose up`.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```rust
use lambda_runtime::error::HandlerError;
use lambda_runtime::lambda;
use serde::{Deserialize, Serialize};
use std::error::Error;

#[derive(Deserialize, Debug, Clone)]
struct FooRequest {
    bar: String,
}

#[derive(Serialize, Clone)]
struct FooResponse {
    success: bool,
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("Started!");

    lambda!(hello_world);

    Ok(())
}

fn hello_world(ev: FooRequest, _ctx: lambda_runtime::Context) -> Result<FooResponse, HandlerError> {
    println!("{:?}", ev);
    Ok(FooResponse { success: true })
}
```

```sh
$ cargo build --target=x86_64-unknown-linux-musl --release
$ cp target/x86_64-unknown-linux-musl/release/hello_world ./bootstrap
$ zip -j lambda.zip bootstrap
$ aws --endpoint-url http://xxx:4566 lambda create-function --function-name "helloworld" --handler "hello.world" --runtime provided.al2 \
    --zip-file fileb://./lambda.zip --role "" --environment Variables={RUST_BACKTRACE=1} \
    --timeout 30 --memory-size 512
$ aws --endpoint-url http://xxx:4566 lambda invoke --function-name helloworld --payload '{"bar":"bar"}' ./output.json
```

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-341) by [Unito](https://www.unito.io/learn-more)

**Comment by Frederick888** [comment]
Sorry, accidentally hit enter, will fill in details in a min.

**Comment by needanamehelp** [comment]
Okay, I'll try and look into this issue, thank you :)

**Comment by macnev2013** [comment]
Thanks for reporting @Frederick888 . I tried to reproduce the issue. But I am getting some errors when using this command `cargo build --target=x86_64-unknown-linux-musl --release`. Can you provide a zip package which is working on real AWS, It would help us a lot in reproducing the issue. Thanks.

**Comment by Frederick888** [comment]
@macnev2013 Sure :) 
[lambda.zip](https://github.com/localstack/localstack/files/5662486/lambda.zip)

Btw if you have trouble building the code, make sure you have:
1. Added the following dependencies into `Cargo.toml`
  ```toml
  [dependencies]
  lambda_runtime = "0.2.1"
  serde = { version = "1.0.117", features = ["derive"] }
  serde_json = "1.0.59"
  ```
0. Installed the target by running `rustup target add x86_64-unknown-linux-musl`
0. If you are using macOS, [`musl-cross`](https://github.com/FiloSottile/homebrew-musl-cross) also needs to be installed beforehand; or simply build it in Docker
