### ISSUE TITLE
S3 presigned url CORS issue (403)

### ISSUE THREAD

**Issue by mkosir** [localstack/localstack#3266]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Trying to upload file (.jpeg) from browser (PUT request) with generated presigned url.
Code is working without any errors when using it on "live" AWS S3 service, but receiving 403 on LocalStack.

## Expected behavior
File should be uploaded to S3 bucket.

## Actual behavior
Receiving 403 response when trying to upload file from browser.

### Config:
```yml
  aws_s3_rentprovision:
    container_name: 'aws_s3_rentprovision'
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-central-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    volumes:
      - './aws-s3:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Bucket CORS is setup and confirmed with `aws --endpoint-url=http://localhost:4566 s3api get-bucket-cors --bucket my-bucket`
```js
{
  "CORSRules": [
    {
      "AllowedHeaders": ["*"],
      "AllowedMethods": ["GET", "PUT", "POST", "DELETE"],
      "AllowedOrigins": ["*"],
      "ExposeHeaders": []
    }
  ]
}
```
Bucket ACL setup as `aws --endpoint-url=http://localhost:4566 s3api put-bucket-acl --bucket my-bucket --acl public-read`

### Code:
Backend:
```js
const awsCredentialsS3 = {
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  region: process.env.AWS_S3_REGION,
  endpoint: 'http://localhost:4566',
  s3ForcePathStyle: true,
};

export const s3GetSignedUrlForObjectPut = (
  bucket: string,
  objectPath: string,
  ACL: ACL,
  expirationTimeInSec: number | null,
): string => {
  const s3 = new S3(awsCredentialsS3);

  const params: { ACL: ACL; Expires: number; [key: string]: any } = {
    Bucket: bucket,
    Key: objectPath,
    ACL: ACL,
    Expires: expirationTimeInSec ?? undefined,
    ContentType: 'image/jpeg',
  };

  const url = s3.getSignedUrl('putObject', params);
  return url;
};
```
Frontend:
```js
  const response = await axios.request({
    url: s3UploadFileObject.signedUrl,
    method: 'PUT',
    data: s3UploadFileObject.file,
  });
```
Any info on what should be setup differently highly appreciated.
Nevertheless LocalStack is really awesome to work with, keep up 🚀
