### ISSUE TITLE
SQS purge/delete not working

### ISSUE THREAD

**Issue by BeyondEvil** [localstack/localstack#3279]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I run localstack using the docker container and hit an issue where SQS found "ghost" messages on the queue.

Neither purge-queue or delete-message would remove it, even tho the commands ran successfully.

Deleting the image and associated volume didn't help. What helped was to delete the `recorded_api_calls.json` in the `/tmp/localstack/data` directory.

## Expected behavior

Purge and delete should work as expected.

## Actual behavior

Message can still be received even after it being deleted or entire queue purged.

# Steps to reproduce

## Command used to start LocalStack

docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Compose file:

```yml
version: "2.1"
services:

  localstack:
    image: localstack/localstack:0.11.6
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=true
      - SERVICES=s3,sns,sqs,dynamodb,secretsmanager
      - DEFAULT_REGION=us-west-2
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
        - "/tmp/localstack:/tmp/localstack"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
        interval: 10s
        timeout: 15s
        retries: 3

  blackbox:
    build:
      context: ./dev
    image: blackbox:latest
    container_name: blackbox
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - CLIENT_SECRET="${CLIENT_SECRET}"
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - PYTHONDONTWRITEBYTECODE=1
      - CORE_PLATFORM_SNS_TOPIC_ARN=arn:aws:sns:us-west-2:000000000000:CorePlatform
      - DYNAMODB_APP_CREDS_TABLE="stage-sync-app-secret"
    volumes:
      - ${PWD}/dev:/blackbox
    depends_on:
      - localstack

networks:
  default:
    name: blackbox
```

The relevant function that gets the "ghost" message is run inside `blackbox`:

```python
    LOCALSTACK_ENDPOINT = os.getenv("LOCALSTACK_ENDPOINT", "http://localhost:4566")
    boto3.resource = functools.partial(boto3.resource, endpoint_url=LOCALSTACK_ENDPOINT)
    SQS_HEALTH_REPORT_QUEUE_NAME = os.getenv(
        "SQS_HEALTH_REPORT_QUEUE_NAME", "health-report-queue"
    )

    sqs = boto3.resource("sqs", region_name=AWS_DEFAULT_REGION)
    queue = sqs.get_queue_by_name(QueueName=SQS_HEALTH_REPORT_QUEUE_NAME)
    messages = queue.receive_messages(
        MaxNumberOfMessages=1, VisibilityTimeout=60, WaitTimeSeconds=20
    )
    if messages:
        return messages[0]
```

## Environment details:

```
/blackbox # python --version
Python 3.8.6

/blackbox # pip freeze
appdirs==1.4.4
boto3==1.16.18
botocore==1.19.25
certifi==2020.11.8
chardet==3.0.4
distlib==0.3.1
filelock==3.0.12
idna==2.10
jmespath==0.10.0
pipenv==2018.11.26
pycryptodome==3.9.9
python-dateutil==2.8.1
requests==2.25.0
s3transfer==0.3.3
six==1.15.0
urllib3==1.26.2
virtualenv==20.2.1
virtualenv-clone==0.5.4

/blackbox # uname -a
Linux e960a535871b 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 Linux
```

Host machine: macOS 10.15.7
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.4, build 40524192
