### ISSUE TITLE
CloudFormation template substitution using !sub not working in latest

### ISSUE THREAD

**Issue by mcintyre94** [localstack/localstack#3293]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

CloudFormation templates are not having variables correctly substituted in `!Sub`. This is a regression in latest, from 0.12.2.

Somewhat speculative but based on our build logs I think this was introduced in the last 24 hours, so my guess is that it was introduced by https://github.com/localstack/localstack/pull/3286 

## Expected behavior

`!Sub` should allow substituting a variable in the form `${apiKey}`

## Actual behavior

No substitution takes place

# Steps to reproduce

Example CloudFormation template, template.yaml:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Some template

Parameters:
  ApiKey:
    Type: String
    Description: API key

Resources:
  # IAM role for running the step function
  StateMachineExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunction"
            Resource: "*"

  # Step function that executes the workflow
  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      RoleArn: !GetAtt StateMachineExecutionRole.Arn
      DefinitionString: 
        !Sub
        - |-
            {
              "Comment": "",
              "StartAt": "time-series-update",
              "States": {
                "time-series-update": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::lambda:invoke.waitForTaskToken",
                  "HeartbeatSeconds": 3600,
                  "Parameters": {
                    "FunctionName": "some-lambda",
                    "Payload": {
                      "key": "${apiKey}"
                    }
                  },
                  "ResultPath": "$.timeSeriesUpdateResult",
                  "End": true
                }
              }
            }
        - {
            apiKey: !Ref ApiKey
          }
```

Notice that we have a parameter ApiKey, which is substituted into the payload of a stage of the step function.

```bash
# deploy the template, setting ApiKey
$ awslocal cloudformation deploy --stack-name stepfn --template-file template.yaml --capabilities CAPABILITY_IAM --parameter-overrides ApiKey=test-api-key

# describe the created step function
$ arn=$(awslocal stepfunctions list-state-machines --query 'stateMachines[0].stateMachineArn' --output text)                                
$ awslocal stepfunctions describe-state-machine --state-machine-arn=$arn                                                                                  
{
    "stateMachineArn": "arn:aws:states:us-east-1:000000000000:stateMachine:stepfn-StateMachine-9d9ec8e9",
    "name": "stepfn-StateMachine-9d9ec8e9",
    "status": "ACTIVE",
    "definition": "{\n  \"Comment\": \"\",\n  \"StartAt\": \"time-series-update\",\n  \"States\": {\n    \"time-series-update\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:states:::lambda:invoke.waitForTaskToken\",\n      \"HeartbeatSeconds\": 3600,\n      \"Parameters\": {\n        \"FunctionName\": \"some-lambda\",\n        \"Payload\": {\n          \"key\": \"${apiKey}\"\n        }\n      },\n      \"ResultPath\": \"$.timeSeriesUpdateResult\",\n      \"End\": true\n    }\n  }\n}",
    "roleArn": "arn:aws:iam::000000000000:role/cf-stepfn-StateMachineExecutionRole",
    "type": "STANDARD",
    "creationDate": 1606756448.36
}
```

The payload has not been substituted: ` \"key\": \"${apiKey}\"`

If I run 0.12.2 (`IMAGE_NAME=localstack/localstack-light:0.12.2 localstack start`), then the substitution is performed correctly:

```bash
$ awslocal stepfunctions describe-state-machine --state-machine-arn=$arn                                                                                  
{
    "stateMachineArn": "arn:aws:states:us-east-1:000000000000:stateMachine:stepfn-StateMachine-KUN0YGNJ6QHN",
    "name": "stepfn-StateMachine-KUN0YGNJ6QHN",
    "status": "ACTIVE",
    "definition": "{\n  \"Comment\": \"\",\n  \"StartAt\": \"time-series-update\",\n  \"States\": {\n    \"time-series-update\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:states:::lambda:invoke.waitForTaskToken\",\n      \"HeartbeatSeconds\": 3600,\n      \"Parameters\": {\n        \"FunctionName\": \"some-lambda\",\n        \"Payload\": {\n          \"key\": \"test-api-key\"\n        }\n      },\n      \"ResultPath\": \"$.timeSeriesUpdateResult\",\n      \"End\": true\n    }\n  }\n}",
    "roleArn": "arn:aws:iam::000000000000:role/cf-stepfn-StateMachineExecutionRole",
    "type": "STANDARD",
    "creationDate": 1606756698.268
}
```

The payload has been substituted: `\"key\": \"test-api-key\"`

## Command used to start LocalStack

`localstack start`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
$ awslocal cloudformation deploy --stack-name stepfn --template-file template.yaml --capabilities CAPABILITY_IAM --parameter-overrides ApiKey=test-api-key
$ arn=$(awslocal stepfunctions list-state-machines --query 'stateMachines[0].stateMachineArn' --output text)
$ awslocal stepfunctions describe-state-machine --state-machine-arn=$arn
```
