### ISSUE TITLE
Terraform's latest aws_provider release crashes on localstack

### ISSUE THREAD

**Issue by rayjlinden** [localstack/localstack#3297]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

We use terraform to set up sns/sqs/lambdas.  The latest release 3.19 just broke on localstack.
I filed a bug with terraform - especially since it causes it to crash.  However, I suspect it is now wanting to use a feature you guys may not have implemented yet.  Here is where things go awry when doing the terraform apply:

```
aws_sqs_queue.extraction-fraud-events: Creating...
aws_lambda_function.rebilly_lambda: Creating...
aws_sqs_queue.extraction-payments-events-delay: Creating...
aws_sqs_queue.extraction-payout-events: Creating...
aws_sns_topic.sns-ecom-events: Creating...
aws_lambda_function.receipt_lambda: Creating...
aws_sqs_queue.extraction-payments-events: Creating...
aws_lambda_function.webhook_lambda: Creating...
aws_sns_topic.sns-ecom-events: Creation complete after 1s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox]
aws_sqs_queue.extraction-fraud-events: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-fraud-events]
aws_sns_topic_subscription.ecom-events-fraud-target: Creating...
aws_sqs_queue.extraction-payments-events: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-payments-events]
aws_sns_topic_subscription.ecom-events-payments-target: Creating...
aws_sqs_queue.extraction-payments-events-delay: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-payments-events-delay]
aws_sns_topic_subscription.ecom-events-payments-target-delay: Creating...
aws_sqs_queue.extraction-payout-events: Creation complete after 1s [id=http://localhost:4566/000000000000/extraction-payout-events]
aws_sns_topic_subscription.ecom-events-payout-target: Creating...
aws_sns_topic_subscription.ecom-events-fraud-target: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:76524a11-8f3c-4f14-b3fe-fe0b3d024131]
aws_sns_topic_subscription.ecom-events-payments-target: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:74655654-52b8-446a-b320-24960cc97545]
aws_sns_topic_subscription.ecom-events-payments-target-delay: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:88405d08-1c97-40f6-8cec-65c18e56beed]
aws_sns_topic_subscription.ecom-events-payout-target: Creation complete after 0s [id=arn:aws:sns:us-west-2:000000000000:ecom-events-sandbox:212f21b0-4e02-4f1d-8115-d8185f1622fc]

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: invalid memory address or nil pointer dereference
2020-12-02T06:46:59.013Z [DEBUG] plugin.terraform-provider-aws_v3.19.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4465b2e]
```

## Expected behavior

Things should work.

## Actual behavior

Terraform crashes.

# Steps to reproduce

I could send the terraform script if desired...

## Command used to start LocalStack

Relevant part of a large docker-compose:
```
localstack:
  image: docker.io/localstack/localstack
  environment:
    - SERVICES=sns,sqs,lambda,logs
    - DATA_DIR=/tmp/localstack/data
    - DOCKER_HOST=unix:///var/run/docker.sock
    - DEFAULT_REGION=us-west-2
    - LAMBDA_EXECUTOR=docker
    - AWS_REGION=us-west-2
    - AWS_ACCESS_KEY_ID=localstack
    - AWS_SECRET_ACCESS_KEY=localstack
  ports:
    - "8180:8080" # dashboard
    - "4566:4566" # std port
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A
