### ISSUE TITLE
CloudFormation Html Entity Encoding

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#3300]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
Special characters are not encoded as HTML Entities in the description element of each stack member in the describe-stacks api response.  
This results in < and > symbols breaking the XML structure of the response, rendering the response unparseable.

## Expected behavior
Stack's description in describe-stacks api response:
`<Description>Do something e.g. &lt;env&gt;.blah.net</Description>`.

## Actual behavior
Stack's description in describe-stacks api response:
`<Description>Do something e.g. <env>.blah.net</Description>`

# Steps to reproduce
1. Deploy the following CloudFormation template to localstack:
```yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Do something e.g. <env>.blah.net'
Resources:
  AnyResource:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: "100.0.0/20"
```
2.  Run `aws cloudformation describe-stacks --endpoint-url <localstack-endpoint>`
