### ISSUE TITLE
CloudFormation - Pseudo parameter AWS::Region doesn't work in function Fn::GetAZs

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#3331]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description
The pseudo parameter `AWS::Region` doesn't work when nested inside the function `Fn::GetAZs`

## Expected behavior
The pseudo parameter `AWS::Region` is resolved within the function `Fn::GetAZs`. 

## Actual behavior
2020-12-09T10:04:40:INFO:localstack.services.cloudformation.cloudformation_starter: Error on moto CF resource creation for PublicSubnetA. Ignoring, as should_be_created=False: 400 Bad Request:
```xml
<?xml version="1.0" encoding="UTF-8"?>
  <ErrorResponse>
    <Errors>
      <Error>
        <Code>InvalidParameterValue</Code>
        <Message>Value ({'Ref': 'AWS::Region'}a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: af-south-1a, af-south-1b, af-south-1c, ap-south-1a, ap-south-1b, eu-west-3a, eu-west-3b, eu-west-3c, eu-north-1a, eu-north-1b, eu-north-1c, eu-west-2a, eu-west-2b, eu-west-2c, eu-west-1a, eu-west-1b, eu-west-1c, ap-northeast-2a, ap-northeast-2a, ap-northeast-2c, ap-northeast-1a, ap-northeast-1c, ap-northeast-1d, ap-east-1a, ap-east-1b, ap-east-1c, sa-east-1a, sa-east-1c, ca-central-1a, ca-central-1b, ap-southeast-1a, ap-southeast-1b, ap-southeast-1c, ap-southeast-2a, ap-southeast-2b, ap-southeast-2c, eu-central-1a, eu-central-1b, eu-central-1c, eu-south-1a, eu-south-1b, eu-south-1c, us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e, us-east-1f, us-east-2a, us-east-2b, us-east-2c, us-west-1a, us-west-1b, us-west-2a, us-west-2b, us-west-2c, me-south-1a, me-south-1b, me-south-1c, cn-north-1a, cn-north-1b, cn-northwest-1a, cn-northwest-1b, cn-northwest-1c, us-gov-west-1a, us-gov-west-1b, us-gov-west-1c, us-gov-east-1a, us-gov-east-1b, us-gov-east-1c.</Message>
        
      </Error>
    </Errors>
  <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</ErrorResponse>
```

# Steps to reproduce
1. Deploy the following CloudFormation template to localstack:
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: "100.0.0.0/20"

  PublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId:
        Ref: VPC
  PermitAnyFromPublic:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      Egress: 'true'
      NetworkAclId:
        Ref: PublicNACL
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'
  PermitAnyToPublic:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: 0.0.0.0/0
      NetworkAclId:
        Ref: PublicNACL
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: '100'

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs:
            Ref: AWS::Region
      CidrBlock: "100.0.0.0/24"
      VpcId:
        Ref: VPC
  PublicSubnetANACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      NetworkAclId:
        Ref: PublicNACL
      SubnetId:
        Ref: PublicSubnetA
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTableA
      SubnetId:
        Ref: PublicSubnetA
  PublicRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC

Outputs:
  PublicSubnetA:
    Value:
      Ref: PublicSubnetA
    Export:
      Name: 'public-sn-a'
```
2. Run `aws cloudformation describe-stacks --endpoint-url http://localhost:4566 --region us-east-1`.
3. Output for "ExportName": "public-sn-a" have value of None, should be id of created subnet.
