### ISSUE TITLE
Fifo queue delivers duplicate message(s)

### ISSUE THREAD

**Issue by BeyondEvil** [localstack/localstack#3339]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Fifo queue delivers messages with the same message (body).

This used to work in `0.11.2` but is broken in both `0.12.2` and `latest`

It's broken regardless if you provide an explicit `MessageDeduplicationId` or not.

## Expected behavior

Queue should only deliver one of the duplicated messages.

## Actual behavior

Queue delivers all duplicated messages.

# Steps to reproduce

## Command used to start LocalStack

```bash
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```yml
version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
```

```sh
#!/usr/bin/env bash

set -e

ep="http://localhost:4566"
dedup_id="1"
group_id="1"

queue_url=$(
    awslocal sqs create-queue \
        --queue-name "queue.fifo" \
        --attributes "FifoQueue=true,ContentBasedDeduplication=true" \
        --query 'QueueUrl' \
        --endpoint-url "${ep}"
)

queue_url="${queue_url//\"/}"

awslocal sqs purge-queue --queue-url "${queue_url}" --endpoint-url "${ep}"

awslocal sqs send-message \
    --queue-url "${queue_url}" \
    --endpoint-url "${ep}" \
    --message-body "message one" \
    --message-group-id "${group_id}" \
    --message-deduplication-id "${dedup_id}"

awslocal sqs send-message \
    --queue-url "${queue_url}" \
    --endpoint-url "${ep}" \
    --message-body "message one" \
    --message-group-id "${group_id}" \
    --message-deduplication-id "${dedup_id}"

awslocal sqs receive-message \
    --queue-url "${queue_url}" \
    --endpoint-url "${ep}" \
    --max-number-of-messages 10 \
    --visibility-timeout 0
```
