### ISSUE TITLE
IAM/STS - API permission verification

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#3345]
# Type of request: This is a ...

[ ] bug report
[X] feature request

# Detailed description
Change localstack to verify that the calling identity has the appropriate IAM permissions when making an api call. If the request is made from an anonymous identity, or an identity which does not exist within the localstack instance (e.g. fake access key), api requests will always be permitted.  

Potential IAM identities which would be supported: 
* IAM user with programmatic access (access key id + secret access key) 
* Session for assumed IAM role (access key id + secret access key + session token)
* Lambda executions 

By enabling applications to be tested using the same IAM permissions they would have access to in AWS, insufficient IAM policies will be able to be found before code is deployed to a testing environment.

**Comment by Tobolov** [comment]
Hi whummer,
I have tired to get this functionality to work however I still haven't been successful (with pro API key). 
Perhaps I am doing something wrong? 

# Steps I am taking to test API permission verification
1. Deploy the following CloudFormation template:
```yaml
---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  TestTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: 'test-table'
      AttributeDefinitions: 
        - AttributeName: 'Key'
          AttributeType: 'S'
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: 'Key'
          KeyType: 'HASH'
  
  TestRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
```
2. Run `aws sts assume-role --role-arn 'arn:aws:iam::000000000000:role/cf-test-TestRole' --role-session-name 'test'`
3. $env:AWS_ACCESS_KEY_ID = "<AccessKeyId from output of command 2>" 
4. $env:AWS_SECRET_ACCESS_KEY = "<SecretAccessKey from output of command 2>"
5. Run `aws sts get-caller-identity` to verify usage we have assumed test role.
6. Run `aws dynamodb list-tables`. 

My understanding is that the command at step 6 should fail since the IAM role doesn't have the required permissions.
