### ISSUE TITLE
AWS SES

### ISSUE THREAD

**Issue by amirsaber** [localstack/localstack#339]
I am super excited about this amazing project. I am using it in one my projects. I am using the docker SES

The issue that I am facing is about SES. Three things I am facing:
1- SES does not remember verified domains and emails after I restart the container
2- SES does not send the actual email out

I am wondering if I am doing something wrong or this is how it should be or it will change in future.

Once again thanks for your amazing project

**Comment by monsonjeremy** [comment]
It's weird because I was able to get the email to send out one time, and then it never sent out again. Not sure if that is intended but would be really nice for testing.

**Comment by ozonni** [comment]
@amirsaber localstack uses [moto](https://github.com/spulec/moto) to mock SES service and it doesn't actually send email. It receives API call to send email and just stores it in memory and sends successful response back.

**Comment by amirsaber** [comment]
Thanks for your reply @ozonni . Yes i think it will be great to have that. Some inbox like mailinator inbox so users can see what is inside the email and maybe get links that have sent in the email

**Comment by unicron** [comment]
As an alternative to a UI for Inbox/Dashboard, is there any way to retrieve the information in the memory store?  Trying to write integration tests and need some way to verify that emails were sent.

**Comment by allentian** [comment]
I hope to do SES integration test as well. 
I am not sure how to get the information in the memory store and how to verify that the emails were sent.
If any one can provide me some solution, i will appreciate a lot.

**Comment by fzaffarana** [comment]
Hi!

I'm trying to use it for some test, but I get this error: `Email address not verified info@test.com`, how can I verify these mail with localstack?.

Thanks!

**Comment by pundurs** [comment]
@fzaffarana IIRC, you just use the regular API to verify an address.

Like, `aws ses verify-email-identity --email-address email@example.com --region your-region --profile your-profile --endpoint-url=http://localhost:4579`

**Comment by fzaffarana** [comment]
Thank you @pundurs 

I do it with node sdk, and it works perfectly.

**Comment by jchannon** [comment]
Was the features asked for ever implemented?

**Comment by Tasemu** [comment]
+1

**Comment by trubi** [comment]
+1

**Comment by joeyx22lm** [comment]
+1

**Comment by yjimk** [comment]
For those running localstack SES with docker-compose, I've been using this script to automate the verify command on initialisation. 

docker-entrypoint-extend.sh
```
#!/bin/bash
set -eo pipefail

# Run the main entrypoint script in background mode
docker-entrypoint.sh &

# Wait for the SES service to be available before executing any post-run scripts
while ! nc -z localhost 4579; do   
    echo "Waiting for SES to launch on port 4579..."
    sleep 2
done

echo 'Running AWS verify identity command. See: https://github.com/localstack/localstack/issues/339'
aws ses verify-email-identity --email-address support@ironstar.io --region ap-southeast-2 --endpoint-url=http://localhost:4579

# Keeps the container running, otherwise will take the exit code from the `aws` command and stop the container 
while :; do :; done & kill -STOP $! && wait $!
```

docker-compose.yml
```
  localstack:
    image: localstack/localstack
    ports:
      - "4579:4579"
    entrypoint: ["/opt/code/localstack/docker-entrypoint-extend.sh"]
    environment:
      - SERVICES=ses
      - PORT_WEB_UI=5555
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-southeast-2
      - HOSTNAME=localstack
      - AWS_ACCESS_KEY_ID=root
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - "./.tmp/localstack:/tmp/localstack"
      - "./scripts/localstack/docker-entrypoint-extend.sh:/opt/code/localstack/docker-entrypoint-extend.sh"
```

There is probably a more elegant way to achieve this, however it works for me!
