### ISSUE TITLE
RDS data does not persist in docker volume

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#3391]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description

RDS instances do not persist even when a volume is specified in the docker app. Especially egregious when the corresponding DynamoDB and S3 volume data DOES persist

## Expected behavior

RDS instances will persist if a volume is specified, along with the underlying postgresql database and data

## Actual behavior

Every time the Docker app is started, querying the RDS service instances returns: 
```
aws --endpoint-url=http://host.docker.internal:4566 rds describe-db-instances

{
    "DBInstances": []
}
```

# Steps to reproduce

## Command used to start LocalStack

Docker-compose. Please notice the volumes at the bottom. A volume is specified individually for each LocalStack service. Only the RDS volume fails to persist data.

```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRON: dev
    depends_on:
      - localstack
      - rabbitmq
      - redis
    environment:
      - AWS_ACCESS_KEY_ID='FakeAccessKey'
      - AWS_SECRET_ACCESS_KEY='FakeSecretAccessKey'
      - AWS_DEFAULT_REGION=us-east-1
      - WAIT_HOSTS=rabbitmq:4369, rabbitmq:5672, rabbitmq:25672, rabbitmq:15672, redis:6379, localstack:4566
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_BEFORE_HOSTS=30
    ports:
      - "8001:80"
    command: sh -c "/wait && circusd /srv/circus.ini --log-output /var/log/circusd.log"

  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:6.0.9"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "443:443"
      - "4510-4520:4510-4520"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,dynamodb,rds
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=########
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "s3data:/tmp/localstack/data/s3"
      - "dynamodata:/tmp/localstack/data/ddb"
      - "rdsdata:/tmp/localstack/data/rds"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"

volumes:
  dynamodata:
  rdsdata:
  s3data:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

```
