### ISSUE TITLE
PHP AWS SDK ListObjects and ListObjectsV2 methods doesn't yield results for S3 "folders" (works with 0.11.0)

### ISSUE THREAD

**Issue by marcelopm** [localstack/localstack#3392]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

PHP AWS SDK ListObjects and ListObjectsV2 methods doesn't yield results for S3 "folders" 

## Expected behavior

S3 "folders" to be listed

## Actual behavior

S3 "folders" are not listed

# Steps to reproduce

docker-compose.yml
```yml
services:
  localstack:
    container_name: api_localstack_1
    image: localstack/localstack
    #image: localstack/localstack:0.11.0
    ports:
      - "9090:9000"
    environment:
      - EDGE_PORT=9000
      - SERVICES=s3
      - DEFAULT_REGION=ap-southeast-2
      - AWS_DEFAULT_REGION=ap-southeast-2
      - USE_SSL=false
      - DEBUG=0
 ```

test script:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Aws\S3\S3Client;

$config = [
    'credentials' => [
        'key'    => 'test-id',
        'secret' => 'test-secret',
    ],
    'region' => '',
    'version' => 'latest',
    'endpoint' => 'http://localhost:9090',
    'use_path_style_endpoint' => true,
];
$s3client = new S3Client($config);
$s3client->createBucket([
    'Bucket' => 'test',
]);
$s3client->putObject([
    'Bucket' => 'test',
    'Key' => 'folder/subfolder/',
    'Body' => ''
]);
$result = $s3client->listObjects([
//$result = $s3client->listObjectsV2([
    'Bucket' => 'test',
    'MaxKeys' => 1,
    'Prefix' => 'folder'
]);
var_dump($result);
```

Results:
```bash
class Aws\Result#2888 (2) {
  private $data =>
  array(1) {
    '@metadata' =>
    array(4) {
      'statusCode' =>
      int(200)
      'effectiveUri' =>
      string(65) "http://localstack:9000/test?list-type=2&max-keys=1&prefix=folder"
      'headers' =>
      array(16) {
        ...
      }
      'transferStats' =>
      array(1) {
        ...
      }
    }
  }
  private $monitoringEvents =>
  array(0) {
  }
}
```

Results when using 0.11.0:
```bash
$ php test.php
class Aws\Result#3080 (2) {
  private $data =>
  array(7) {
    'IsTruncated' =>
    bool(false)
    'Contents' =>
    array(1) {
      [0] =>
      array(5) {
        ...
      }
    }
    'Name' =>
    string(5) "test3"
    'Prefix' =>
    string(6) "folder"
    'MaxKeys' =>
    int(1)
    'KeyCount' =>
    int(1)
    '@metadata' =>
    array(4) {
      'statusCode' =>
      int(200)
      'effectiveUri' =>
      string(65) "http://localstack:9000/test?list-type=2&max-keys=1&prefix=folder"
      'headers' =>
      array(9) {
        ...
      }
      'transferStats' =>
      array(1) {
        ...
      }
    }
  }
  private $monitoringEvents =>
  array(0) {
  }
}
```
