### ISSUE TITLE
Not able to invoke post restapi

### ISSUE THREAD

**Issue by ravithejappl** [localstack/localstack#3418]
I am not able to invoke post rest api in localstack
I am following these urls

```
curl --header "Content-Type: application/json”  --request POST  --data '{"text":"129"}' http://localhost:4566/restapis/hlrwfdyhlq/dev/_user_request_/todos
```

tried from postman as well using [http://localhost:4566/restapis/hlrwfdyhlq/dev/_user_request_/todos](url)

I cloud see list of api running on from aws-cli

In YML file method is like this
```
create:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
```
