### ISSUE TITLE
RequestParameters not working

### ISSUE THREAD

**Issue by benanderton** [localstack/localstack#3448]
# Type of request: This is a ...

[*] bug report
[ ] feature request

# Detailed description

**Update:** I've found a [similar issue](https://github.com/localstack/localstack/issues/229) which was closed because supposedly it was fixed, though it doesn't seem like it was.
**--End of update--**

I'm trying to configure an API Gateway method which uses a parameter as part of the path, so I can for instance hit `http://localhost:4566/restapis/[rest-api-id]/dev/_user_request_/person/[guid]` (for example `http://localhost:4566/restapis/gbydwvvvul/dev/_user_request_/person/63338c7f-1f90-4458-802f-ec6ddb2d5578`) and have the GUID passed as a parameter to the `HTTP_PROXY` integration of the method. However, when the request is proxied to the Uri specified under Integration it receives the parameter as a string of the parameter name instead:

See below, an excerpt from a Node.js service which handles the request

```
{personId}
GET /%7BpersonId%7D 400 42.657 ms - 87

```

If I inspect the API Gateway method using the AWS CLI I can see that `requestParameters` does not appear in the method definition. However, if I use the same CloudFormation configuration to set up an identical method on AWS and query that then I can see the `requestParameters` exists on the method.

**localstack**
```
{
    "httpMethod": "GET",
    "authorizationType": "NONE",
    "apiKeyRequired": false,
    "methodIntegration": {
        "type": "HTTP_PROXY",
        "httpMethod": "GET",
        "uri": "http://172.17.0.1:3333/{personId}",
        "passthroughBehavior": "WHEN_NO_MATCH",
        "cacheNamespace": "88d5d4f4",
        "cacheKeyParameters": [],
        "integrationResponses": {
            "200": {
                "statusCode": 200,
                "responseTemplates": {
                    "application/json": null
                }
            }
        }
    }
}
```
**AWS**

```
{
    "httpMethod": "GET",
    "authorizationType": "NONE",
    "apiKeyRequired": false,
    "requestParameters": {
        "method.request.path.personId": true
    },
    "methodIntegration": {
        "type": "HTTP_PROXY",
        "httpMethod": "GET",
        "uri": "http://172.17.0.1:3333/{personId}",
        "passthroughBehavior": "WHEN_NO_MATCH",
        "cacheNamespace": "4upg1p",
        "cacheKeyParameters": [],
        "integrationResponses": {
            "200": {
                "statusCode": "200",
                "responseTemplates": {
                    "application/json": null
                }
            }
        }
    }
}
```

## Expected behaviour
I would expect parity between the results borne of CloudFormation configuration between localstack and AWS.

## Actual behavior
localstack does not honour specified request parameters under the method of a CloudFormation `AWS::ApiGateway::Method` item.

# Steps to reproduce

## Command used to start LocalStack

I'm running localstack as part of a `docker-compose` configuration.

### docker-compose.yml
```
version: "3.3"

networks:
  devenv:
    driver: bridge

services:
  mailhog:
    restart: always
    image: mailhog/mailhog:v1.0.0
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - devenv
  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - "9090:9000"
    networks:
      - devenv
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  reverse-proxy:
    restart: always
    image: traefik:v2.0.0 # The official Traefik docker image
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    networks:
      - devenv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  errbit:
    restart: always
    image: errbit/errbit:latest
    depends_on:
      - mongo
    networks:
      - devenv
    environment:
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
      - ERRBIT_ADMIN_EMAIL=support@sortrefer.co.uk
      - ERRBIT_ADMIN_PASSWORD=s0rtr3f3r
      - ERRBIT_ADMIN_USER=admin
      - ERRBIT_HOST=127.0.0.1
      - ERRBIT_USER_HAS_USERNAME=true
      - GITHUB_AUTHENTICATION=false
      - GOOGLE_AUTHENTICATION=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.errbit.rule=Host(`errbit.localhost`)"
      - "traefik.http.routers.errbit.entrypoints=web"
  mongo:
    image: mongo:4.1
    restart: always
    ports:
      - "27017"
    networks:
      - devenv
    volumes:
      - mongo-datavolume:/bitnami
  percona:
    restart: always
    image: percona/percona-server:5.7
    networks:
      - devenv
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=devenv
    volumes:
      - percona-datavolume:/var/lib/mysql
  postgres:
    restart: always
    image: postgres:11-alpine
    networks:
      - devenv
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-datavolume:/var/lib/postgresql/data
  localstack:
    restart: always
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    networks:
      - devenv
    environment:
      - DEFAULT_REGION=eu-west-2
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack-datavolume:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  dynamodb-admin:
    restart: always
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    networks:
      - devenv
volumes:
  portainer_data:
  percona-datavolume:
  postgres-datavolume:
  mongo-datavolume:
  localstack-datavolume:

```

To run this I'm executing `docker-compose up -d`

### `localstack.yaml`
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Task definition for the Person HTTP microservice

Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: SortMove API Gateway
      EndpointConfiguration:
        Types:
          - REGIONAL
        Name: sortmove-api

  PersonRootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'person'
      RestApiId: !Ref ApiGateway

  PersonPersonIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref PersonRootResource
      PathPart: '{personId}'
      RestApiId: !Ref ApiGateway

  PersonPersonIdGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref PersonPersonIdResource
      RestApiId: !Ref ApiGateway
      RequestParameters:
        method.request.path.personId: true
      Integration:
        IntegrationHttpMethod: GET
        Type: HTTP_PROXY
        Uri: http://172.17.0.1:3333/{personId}
        RequestParameters:
          integration.request.path.personId: method.request.path.personId
```

I use this by calling the following:

`aws --endpoint-url http://localhost:4566 cloudformation create-stack --stack-name person --template-body file://localstack.yaml`
