### ISSUE TITLE
SNS subscription ARN changes on localstack restart

### ISSUE THREAD

**Issue by guillemtp** [localstack/localstack#3455]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When the localstack is restarted and the data is loaded through the recorded_api_calls.json, the SNS's subscription ARN changes. If you use a IaaC tool like Terraform, you loose the configuration because it saves this ARN to know the resources statuses.

For example, a HTTPS SNS subscription created in localstack have the subscription ARN *ac02f5a0-661e-4c9d-ac77-ec47188b0dd8*:

```
$ aws --endpoint-url http://localhost:4566 --region eu-west-1 sns list-subscriptions | more
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:local-item_item_changed:ac02f5a0-661e-4c9d-ac77-ec47188b0dd8",
            "Owner": "",
            "Protocol": "https",
            "Endpoint": "http://myatr-and-go/extra/notifications/item.changed.php",
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:local-item_item_changed"
        },
  (...)
```

When you restart the local stack, you get the same subscription with a different ARN:

```
$ aws --endpoint-url http://localhost:4566 --region eu-west-1 sns list-subscriptions | more
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:local-item_item_changed:126b84b4-061b-46f2-abd6-0615b854c013",
            "Owner": "",
            "Protocol": "https",
            "Endpoint": "http://myatr-and-go/extra/notifications/item.changed.php",
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:local-item_item_changed"
        },
(...)
```

## Expected behavior

The subscription ARN should preserve the same identifier value.

# Steps to reproduce

## Command used to start LocalStack

With the following 
```
version: '3.5'

services:
    localstack:
        image: localstack/localstack:0.12.4
        ports:
            - "4566:4566"
        environment:
            - SERVICES=s3,sns,sqs
            - HOST_TMP_FOLDER=/tmp/localstack
            - DATA_DIR=/tmp/localstack/data
            - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
            - ./var/localstack:/tmp/localstack
            - /var/run/docker.sock:/var/run/docker.sock
```

Execute:
`docker-compose up`

## Client code

Create the `sns-topic-testing` SNS topic queue:
```
$ aws --endpoint-url http://localhost:4566 --region eu-west-1 sns create-topic --name sns-topic-testing'

{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:sns-topic-testing"
}
```

Create a subscription to an http dummy endpoint:
```
$ aws --endpoint-url http://localhost:4566 --region eu-west-1 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:sns-topic-testing --protocol https --notification-endpoint "https://localhost"

{
    "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:sns-topic-testing:1fd12d59-1927-4016-93c6-7b082658dcd2"
}
```

List the subscriptions by topic to check the previous ARN. In this example the *1fd12d59-1927-4016-93c6-7b082658dcd2* coincides:
```
$ aws --endpoint-url http://localhost:4566 --region eu-west-1 sns list-subscriptions-by-topic --topic-arn arn:aws:sns:us-east-1:000000000000:sns-topic-testing
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:sns-topic-testing:1fd12d59-1927-4016-93c6-7b082658dcd2",
            "Owner": "",
            "Protocol": "https",
            "Endpoint": "https://localhost",
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:sns-topic-testing"
        }
    ]
}
``` 

Restart with docker-compose:
```
docker-compose restart
```

Check if the ARN has changed. You will see a new value. In this example, it changes to *c29fc8d6-e0ac-457e-acbd-6775944d3db0*

```
$ aws --endpoint-url http://localhost:4566 --region eu-west-1 sns list-subscriptions-by-topic --topic-arn arn:aws:sns:us-east-1:000000000000:sns-topic-testing
{
    "Subscriptions": [
        {
            "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:sns-topic-testing:c29fc8d6-e0ac-457e-acbd-6775944d3db0",
            "Owner": "",
            "Protocol": "https",
            "Endpoint": "https://localhost",
            "TopicArn": "arn:aws:sns:us-east-1:000000000000:sns-topic-testing"
        }
    ]
}
```
