### ISSUE TITLE
Creating S3 bucket on startup fails with regex error

### ISSUE THREAD

**Issue by joro550** [localstack/localstack#3462]
# Type of request: This is a ...
- [x] bug report

# Detailed description
Using the init script path to create s3 buckets gives regex errors.

Docker compose file:
```
version: '3.4'

services:
  skyrise.localstack:
    image: localstack/localstack:latest
    container_name: skyrise-localstack
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./setup-dev-env.sh:/docker-entrypoint-initaws.d/setup-dev-env.sh"
```
setup-dev-env.sh:

```
awslocal s3 mb s3://mybucket
```

Error recieved from docker-compose:
```
 /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initaws.d/setup-dev-env.sh
 Parameter validation failed:bucket failed: s3://mybucket
": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

If I do the same thing (outside of the init scripts) it actually works:
![awsfail](https://user-images.githubusercontent.com/1705979/104444372-9bf2d880-558f-11eb-9525-e37897770c56.png)

## Expected behavior
Bucket is created

## Actual behavior
Error message is given

# Steps to reproduce

Probably enough information in the description to help here :smile:

## Command used to start LocalStack
`docker-compose up`

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal s3 mb s3://mybucket
```
