### ISSUE TITLE
SNS MessageID is not being passed to Java lambda while invoking with SNS.

### ISSUE THREAD

**Issue by kinpatel** [localstack/localstack#3471]
# Type of request: bug report

# Detailed description
I am trying to invoke Java lambda with SNS, but SNS messageId is not being passed to the lambda while it does return the messageId in response. 
Using `"serverless-localstack": "^0.4.28"` for serverless plugin and latest docker image.

## Expected behavior
messageId should be included in the sns event
`{[{sns: {messageId: b3dbf283-a455-4a5c-b996-d4296c72196b, messageAttributes: {},message: Hello World ,type: Notification,timestamp: 2021-01-14T18:49:26.624Z,},}]}`

## Actual behavior
sns event doesn't contain messageId when its sent to Java lambda and below is the sample event that we get.
`{[{sns: {messageAttributes: {},message: Hello World ,type: Notification,timestamp: 2021-01-14T18:49:26.624Z,},}]}`

```
localstack_1  | Exception in thread "main" java.lang.IllegalArgumentException: messageId cannot be null
localstack_1  | 	at com.amazonaws.util.ValidationUtils.assertNotNull(ValidationUtils.java:37)
localstack_1  | 	at com.amazonaws.services.dynamodbv2.document.ItemUtils.checkInvalidAttribute(ItemUtils.java:597)
localstack_1  | 	at com.amazonaws.services.dynamodbv2.document.internal.InternalUtils.checkInvalidAttribute(InternalUtils.java:323)
localstack_1  | 	at com.amazonaws.services.dynamodbv2.document.Item.withString(Item.java:108)
localstack_1  | 	at com.example.DynamoDbClient.saveAuditData(DynamoDbClient.java:56)
localstack_1  | 	at com.example.EventProcessor.processMessage(EventProcessor.java:47)
localstack_1  | 	at com.example.EventApplication.handleRequest(EventApplication.java:22)
localstack_1  | 	at com.example.EventApplication.handleRequest(EventApplication.java:12)
localstack_1  | 	at cloud.localstack.LambdaExecutor.main(LambdaExecutor.java:94)
```
# Steps to reproduce

## Command used to start LocalStack
using docker image for LocalStack

```
localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4597:4566-4597"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
    volumes:
      - ./data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Java handle request function
```
public class EventApplication implements RequestHandler<SNSEvent, String> {
    private ApplicationContext applicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
    private Logger logger = LoggerFactory.getLogger(getClass());

    @Override
    public String handleRequest(SNSEvent snsEvent, Context context) {
        EventProcessor processor = applicationContext.getBean(EventProcessor.class);
        logger.info("snsEvent: " + snsEvent);
        return processor.processMessage(snsEvent.getRecords().get(0).getSNS());
    }
    public ApplicationContext getApplicationContext() {
        return applicationContext;
    }
}
```

Serverless.yml lambda function defination

```
functions:
  processEvent:
    handler: com.example.EventApplication::handleRequest
    reservedConcurrency: 5
    description: Service to process VCF events.
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:000000000000:services-local
          topicName: services-local
    deadLetter:
      sqs:
        queueName: services-failed-events-local
        visibilityTimeout: 60
```
