### ISSUE TITLE
lambda invoke failed, shell script not found

### ISSUE THREAD

**Issue by jpabbuehl** [localstack/localstack#3518]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

invoke lambda function (python) using local code as described in the [readme.md](https://github.com/localstack/localstack#using-local-code-with-lambda)

## Expected behavior

should get python response with print statement

## Actual behavior

lambda invoke fails to start
![image](https://user-images.githubusercontent.com/2730222/105891411-e9038f80-6010-11eb-96fc-77636391fad3.png)

But the file exists
![image](https://user-images.githubusercontent.com/2730222/105891592-17816a80-6011-11eb-9920-9ad3b6a081b3.png)

# Steps to reproduce

docker-compose up -d
aws --endpoint-url http://localhost:4566 lambda invoke --function-name test response.json

System is MacOS Catalina, version 10.15.7
docker version 20.10.2
docker-compose version 1.27.4

## Command used to start LocalStack

docker-compose up -d

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

docker-compose.yml

```yml
version: '3.9'
services:
  localstack:
    image: localstack/localstack:0.12.5
    container_name: localstack
    ports:
      - 8055:8080
      - 4566:4566
    environment:
      - SERVICES=s3,lambda
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-central-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=${PWD}/localstack_tmp
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_LOCAL=${PWD}/lambda
      - LOCALSTACK_API_KEY=1234
      - MAIN_CONTAINER_NAME=localstack
    volumes:
      - localstack_init:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - custom_network
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3api wait bucket-exists --bucket test-bucket

networks:
  custom_network:
    driver: bridge

volumes:
  localstack_init:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/localstack_init
      o: bind
```

lambda/app.py
```
import sys

def handler(event, context):
    return 'Hello from AWS Lambda using Python' + sys.version + '!'
```

localstack_init/lambda.sh
```
#!/bin/bash
set -x
awslocal lambda create-function \
    --function-name test \
    --region eu-central-1 \
    --code S3Bucket="__local__",S3Key="$LAMBDA_LOCAL" \
    --handler app.handler \
    --runtime python3.8 \
    --role whatever
set +x
```

localstack_init/s3.sh
```
#!/bin/bash
set -x
awslocal s3 mb s3://test-bucket
set +x
```
