### ISSUE TITLE
localstack elastic search endpoints return 500 with an empty json `{}` intermittently

### ISSUE THREAD

**Issue by DevipriyaSarkar** [localstack/localstack#3621]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

localstack elastic search returns 500 with a response `{}` intermittently.

...

## Expected behavior

Once localstack elastic search is up and running, going to http://0.0.0.0:4571/_search should always return a response like 
```
{
    "took": 22,
    "timed_out": false,
    "_shards": {
        "total": 0,
        "successful": 0,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 0,
            "relation": "eq"
        },
        "max_score": 0,
        "hits": []
    }
}
```
...

## Actual behavior

Once localstack elastic search is up and running, and has returned expected responses, is able to index, search. After it is working properly, suddenly intermittently any calls to elastic search returns 500 and an empty json `{}`.
eg.
```
org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Unable to parse response body; nested exception is ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [PUT], host [http://search-localstack:4571], URI [/xyz/_doc/36b62424-0034-3ffe-b99c-b6a5a3cc9f41?timeout=1m], status line [HTTP/1.1 500 ]
{}];
```
Every time I got this response, I went to check the `/_search` endpoint and that also returns 500 and an empty json `{}` as response.
...

# Steps to reproduce

Intermittent. Keep indexing a lot of objects. At one point, you may or may not face this. But I've been facing this a lot since last 1 month or so.

## Command used to start LocalStack

`docker-compose.yml`
```
version: "3.5"
services:
  search-localstack:
    container_name: search-localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "${PWD}/localstack/initaws:/docker-entrypoint-initaws.d"
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      HOSTNAME_EXTERNAL: search-localstack
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: 'dynamodb,dynamodbstreams,sqs,cloudwatch,es'
      DATA_DIR: /tmp/localstack/data
.
.
.
```

```
$ docker-compose up -d search-localstack && docker-compose logs -f search-localstack
# wait till everything is up before doing anything else
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`initaws.sh` that creates these AWS services
```
#!/usr/bin/env bash

# the running dir of this script
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Use awslocal if it exists, else use aws
if [ $(command -v awslocal) ]; then
  AWS=awslocal
else
  AWS=aws
fi
echo "USING $AWS as the AWS command"

ELASTICSEARCH_VERSION=7.9
ELASTICSEARCH_DOMAIN_NAME=my-domain

$AWS sqs create-queue --endpoint-url http://localhost:4566 --queue-name "abc-dead"
$AWS sqs create-queue --endpoint-url http://localhost:4566 --queue-name "abc" \
  --attributes '{"RedrivePolicy": "{\"deadLetterTargetArn\": \"arn:aws:sqs:us-east-1:000000000000:abc-dead\", \"maxReceiveCount\": \"3\"}" }'

$AWS sqs create-queue --endpoint-url http://localhost:4566 --queue-name "xyz-dead"
$AWS sqs create-queue --endpoint-url http://localhost:4566 --queue-name "xyz" \
  --attributes '{"RedrivePolicy": "{\"deadLetterTargetArn\": \"arn:aws:sqs:us-east-1:000000000000:xyz-dead\", \"maxReceiveCount\": \"3\"}", "VisibilityTimeout": "120" }'

$AWS dynamodb create-table --endpoint-url http://localhost:4566 --cli-input-json "file://${DIR}/ddb-t1-table.json"
$AWS dynamodb create-table --endpoint-url http://localhost:4566 --cli-input-json "file://${DIR}/ddb-t2-table.json"

$AWS es create-elasticsearch-domain --endpoint-url=http://localhost:4566 \
  --domain-name ${ELASTICSEARCH_DOMAIN_NAME} \
  --elasticsearch-version ${ELASTICSEARCH_VERSION}
```

The java code that indexes and intermittently gets 500 and `{}`

1. `Xyz.java`
```
package com.a.b.c.domain.entities;

import com.a.b.c.util.exceptions.PrimaryKeyNotFound;
import java.util.Map;

import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

@Document(indexName = "xyz")
public class Xyz extends HashMap<String, Object> {
    @Id
    private String id;

    public Xyz(Map<String, Object> map) {
        super(map);
        this.id = (String) map.get("id");
        if (this.id == null) {
            throw new PrimaryKeyNotFound("id", map);
        }
    }
}
```

2. `XyzRepository.java`
```
package com.a.b.c.repositories.elasticsearch;

import com.a.b.c.domain.entities.Xyz;

import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface XyzRepository extends ElasticsearchRepository<Xyz, String> {

}
```

3. `XyzService.java`
```
package com.a.b.c.domain.services;

import com.a.b.c.domain.entities.Xyz;
import com.a.b.c.repositories.elasticsearch.XyzRepository;

import org.springframework.stereotype.Service;

@Service
public class XyzService {
    private final XyzRepository xyzRepository;

    public XyzService(XyzRepository xyzRepository) {
        this.xyzRepository = xyzRepository;
    }

    public Iterable<Xyz> saveAllXyz(Iterable<Xyz> xyzList) {
        return xyzRepository.saveAll(xyzList);
    }
```

4. In the client - `MyClient.java`
```

@Component
public class MyClient {
    private final XyzService xyzService;

    public MyClient(XyzService xyzService) {
        this.xyzService = xyzService;
    }
    
    public void someMethod(List<Xyz> xyzList) {
        xyzService.saveAllXyz(xyzList);
    }
}
```

Calling the client's someMethod() fails intermittently with
```
org.springframework.data.elasticsearch.UncategorizedElasticsearchException: Unable to parse response body; nested exception is ElasticsearchStatusException[Unable to parse response body]; nested: ResponseException[method [PUT], host [http://search-localstack:4571], URI [/xyz/_doc/36b62424-0034-3ffe-b99c-b6a5a3cc9f41?timeout=1m], status line [HTTP/1.1 500 ]
{}];
```
...
