### ISSUE TITLE
API Gateway BinaryMediaTypes setting

### ISSUE THREAD

**Issue by andres-bayon** [localstack/localstack#3649]
# Type of request: This is a ...

- [x] bug report
- [x] feature request

# Detailed description

Using serverless framework, I try to create a REST API Gateway with the setting `BinaryMediaTypes: ['multipart/form-data']`, useful for a POST endpoint that receives and process a file with a lambda.

This generates the following CloudFormation template:
```json
{
  "ApiGW": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Name": "api",
        "EndpointConfiguration": {
          "Types": [
            "EDGE"
          ]
        },
        "BinaryMediaTypes": [
          "multipart/form-data"
        ]
    }
  }
}
```

When I call the POST method the error described at Actual behaviour ocurrs. Also, when I call `aws --endpoint-url=http://localhost:4566 apigateway get-rest-apis`, it returns the following:
```json
{
    "items": [
        {
            "id": "qvykexv39t",
            "name": "api",
            "description": "",
            "createdDate": "2021-02-26T09:16:04+01:00",
            "apiKeySource": "HEADER",
            "endpointConfiguration": {
                "types": [
                    "EDGE"
                ]
            },
            "tags": {}
        }
    ]
}
```

At AWS, it returns
```json
{
    "items": [
        {
            "id": "xxxxxx",
            "name": "api",
            "createdDate": "2021-02-12T10:57:48+01:00",
            "binaryMediaTypes": [
                "multipart/form-data"
            ],
            "apiKeySource": "HEADER",
            "endpointConfiguration": {
                "types": [
                    "EDGE"
                ]
            },
            "tags": {
                "STAGE": "qa2"
            }
        }
    ]
}
```

It works fine at AWS. Is the BinaryMediaTypes setting not supported or it is a bug?

## Expected behavior

Lambda execution.

## Actual behavior

```
localstack_main | 2021-02-26T08:28:52:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fca32037c10>(None) failed: 'utf-8' codec can't decode byte 0xf5 in position 214: invalid start byte Traceback (most recent call last):
localstack_main |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 521, in run
localstack_main |     result = self.func(self.params)
localstack_main |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_main |     return fn(*args, **kwargs)
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
localstack_main |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_main |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
localstack_main |     listener_result = listener.forward_request(method=method,
localstack_main |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 48, in forward_request
localstack_main |     return invoke_rest_api(api_id, stage, method, relative_path_w_query_params, data, headers, path=path)
localstack_main |   File "/opt/code/localstack/localstack/services/apigateway/apigateway_listener.py", line 253, in invoke_rest_api
localstack_main |     data_str = json.dumps(data) if isinstance(data, (dict, list)) else to_str(data)
localstack_main |   File "/opt/code/localstack/localstack/utils/common.py", line 801, in to_str
localstack_main |     return obj.decode(encoding, errors) if isinstance(obj, six.binary_type) else obj
localstack_main | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 214: invalid start byte
```

# Steps to reproduce

## Command used to start LocalStack

docker-compose.yml
```yml
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full:0.12.4
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-5000}:${PORT_WEB_UI-5000}"
    environment:
      - SERVICES=serverless, ssm
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=5000
      - LAMBDA_EXECUTOR=docker_reuse
      - LAMBDA_REMOTE_DOCKER=false
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

```bash
TMPDIR=/private$TMPDIR docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

N/A
