### ISSUE TITLE
Athena on Localstack PRO does not supported CREATE TABLE AS statement.

### ISSUE THREAD

**Issue by hirano00o** [localstack/localstack#3681]
# Type of request: This is a ...

[ ] bug report
[x] feature request

# Detailed description

I'm using Athena with Localstack PRO. When I tried to create table to using `CREATE TABLE ... AS ...` statement, I got an error, it is `NOT_SUPPORTED`.
As a use case, I'm thinking of creating a table (CREATE TABLE AS) by combining data from several tables in the DAG of apache airflow. Then, the created table is referenced and used from multiple DAGs.

## Expected behavior

`CREATE TABLE AS` statement can use with Athena.

## Actual behavior

The sql does not work, I get following error.

```console
localstack_1  | Unable to get result from Presto server after 10 retries: PrestoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Cannot create a non-managed Hive table using CREATE TABLE AS", query_id=20210304_104009_00000_b7m59) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/athena/athena_api.py", line 52, in _run_query
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/athena/athena_api.py", line 278, in execute_query
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/hadoop.py", line 270, in execute_presto_query
localstack_1  | Exception: Unable to get result from Presto server after 10 retries: PrestoUserError(type=USER_ERROR, name=NOT_SUPPORTED, message="Cannot create a non-managed Hive table using CREATE TABLE AS", query_id=20210304_104009_00000_b7m59)
```

# Steps to reproduce

## Command used to start LocalStack

```yaml
version: '3'
services:
  localstack:
    image: localstack/localstack:0.12.7
    environment:
      SERVICES: serverless,s3,athena
      DEFAULT_REGION: ap-northeast-1
      TZ: Asia/Tokyo
      HOSTNAME_EXTERNAL: localstack
      LOCALSTACK_API_KEY: <REPLACE_YOUR_API_KEY>
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
      DEBUG: 1
    volumes:
      - ./localstack/init.d:/docker-entrypoint-initaws.d
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "443:443"
      - "9900:8080"
      - "4566:4566"
```

```shell
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

After `docker-compose up`, I get an error when I execute following commands on another terminal.

```shell
awslocal s3 mb s3://test-athena-data

awslocal s3 mb s3://athena-query-results

echo "1,Alice,1\n2,Bob,4\n3,Charlie,2\n4,Dave,1" | aws s3 cp - s3://test-athena-data/person/person.csv --endpoint-url http://localhost:4566

echo "1,Newyork\n2,LosAngeles\n3,Chicago\n4,Philadelphia" | aws s3 cp - s3://test-athena-data/place/place.csv --endpoint-url http://localhost:4566

awslocal athena start-query-execution --query-string "CREATE EXTERNAL TABLE IF NOT EXISTS person (
  id INT,
  name STRING,
  birthplace INT
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'serialization.format' = ',',
  'field.delim' = ','
)
LOCATION 's3://test-athena-data/person/'
" --result-configuration OutputLocation=s3://athena-query-results

awslocal athena start-query-execution --query-string "CREATE EXTERNAL TABLE IF NOT EXISTS place (
  id INT,
  city STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'serialization.format' = ',',
  'field.delim' = ','
)
LOCATION 's3://test-athena-data/place/'
" --result-configuration OutputLocation=s3://athena-query-results

awslocal athena start-query-execution --query-string "CREATE TABLE IF NOT EXISTS people
WITH (
    external_location='s3://test-athena-data/people/',
    format = 'JSON',
    bucketed_by=ARRAY['id'],
    bucket_count=1
)
AS
SELECT
    person.id
    , person.name
    , place.city AS birthplace
FROM person
    LEFT JOIN place
        ON person.birthplace = place.id
ORDER BY
    id
" --result-configuration OutputLocation=s3://athena-query-results
```
