### ISSUE TITLE
CloudFormation - AWS::IAM::Role ManagedPolicyArns not working

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#3709]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description
When creating an IAM Role with Cloudformation, the ManagedPolicyArns are not applied to the resource as expected. 

The reason these attributes are required is that I wish to use them in conjunction with the `IAM Security Enforcement` feature of LocalStack. 

## Expected behavior
Creating an IAM Role with Cloudformation applies the ManagedPolicyArns to the resource. 

## Actual behavior
Creating an IAM Role with Cloudformation doesn't apply the ManagedPolicyArns to the resource. 

# Steps to reproduce
1. Deploy the following template with the stackname `test`.
```yml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  InstanceRole:
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
        - arn:aws:iam::aws:policy/AmazonMechanicalTurkFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies: 
        - PolicyName: "InstancePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                - ec2:GetPasswordData
    Type: AWS::IAM::Role
```
2. Run the command `aws iam list-attached-role-policies --role-name cf-test-InstanceRole`. Response is:
```json
{
    "AttachedPolicies": []
}
```
3.  Expected response:
```json
{
    "AttachedPolicies": [
        {
            "PolicyName": "AmazonEC2RoleforSSM",
            "PolicyArn": "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
        },
        {
            "PolicyName": "AmazonEC2ReadOnlyAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess"
        },
        {
            "PolicyName": "AmazonDynamoDBFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        },
        {
            "PolicyName": "AmazonSESFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonSESFullAccess"
        },
        {
            "PolicyName": "AmazonMechanicalTurkFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonMechanicalTurkFullAccess"
        },
        {
            "PolicyName": "AmazonSSMReadOnlyAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
        },
        {
            "PolicyName": "AmazonSNSFullAccess",
            "PolicyArn": "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
        }
    ]
}
```
