### ISSUE TITLE
S3 presign signature validation fails and tags are missing for multipart uploads

### ISSUE THREAD

**Issue by efenderbosch** [localstack/localstack#3713]
# Type of request:

This is a bug report.

# Detailed description
* S3 multipart presign signature validation fails using latest Docker image (as of 2021-03-12), works using 0.12.7
* multipart uploads do not have tags after upload has been completed

## Expected behavior
* S3 multipart presign signature validation should work the same as S3 (and previous versions of localstack)
* completed multipart uploads should have tags present

## Actual behavior
* S3 multipart presign signature validation fails using latest Docker image (as of 2021-03-12)
* multipart uploads do not have tags after upload has been completed

# Steps to reproduce
Minimally reproducible project here: https://github.com/efenderbosch/localstack-multipart-upload-test
Follow steps in readme.md.

## Command used to start LocalStack
docker-compose -f docker-compose.yml up
```yaml
version: '3'

services:
  localstack:
    image: localstack/localstack-light:latest
    # image: localstack/localstack-light:0.12.7
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
      DEBUG: 1

networks:
  default:
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Using AWS Java SDK 2.15 and 2.16 in Kotlin 1.4 project. See project above for full code.
