### ISSUE TITLE
Lambda fails while trying to open an image within the lambda source

### ISSUE THREAD

**Issue by BenRbtz** [localstack/localstack#3722]
[x ] bug report
[ ] feature request

# Detailed description
I've deployed a lambda to localstack (docker-mode) and tried to access an image within the lambda source. However, the lambda throws a permissions issue when trying to open it. I've also ran it within AWS and it's able to access the image without any permission issues. 

docker-compose.yaml
```yaml
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_SERVICES=s3,lambda
      - HOSTNAME_EXTERNAL=localstack
      - LOCALHOST_DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_DEBUG=1
    ports:
      - 4566:4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

```

lambda source
```python
from pathlib import Path

file_path = Path(__file__).parent / 'images' / 'test.png'

def lambda_handler(event, context):
    print(file_path)

    with open(file_path, mode='rb') as file:
        file.read()
        # print(file.read())

    return file_path
```

## Expected behavior
No errors thrown

## Actual behavior

[ERROR] PermissionError: [Errno 13] Permission denied: '/var/task/lambda_error_handler/images/test.png'

EDIT: Fixed docker-compose.yaml
