### ISSUE TITLE
[Cognito] [Pro] AWSCognitoIdentityProviderService.CreateUserPool creates schema attributes under the wrong key

### ISSUE THREAD

**Issue by richardkriesman** [localstack/localstack#3747]
# Type of request: This is a ...

[X ] bug report
[ ] feature request

# Detailed description

When creating a new user pool with custom attributes using `AWSCognitoIdentityProvider.CreateUserPool`, there is an option to define schema attributes with the `Schema` request key.  Afterward, subsequent calls to `AWSCognitoIdentityProvider.DescribeUserPool` return those schema attributes under the `SchemaAttributes` key. In LocalStack, however, they are incorrectly returned under the `Schema` key, thus preventing them from being considered part of the attribute schema.

We're currently using LocalStack with Terraform to create and destroy local environments quickly, and while we can still add custom attributes with a manual `AddCustomAttributes` call, this does prevent us from being able to manage local Cognito resources with Terraform since this issue causes it to recreate the user pool on each apply.

## Expected behavior

The user pool  is created with schema attributes stored under `SchemaAttributes`.

## Actual behavior

The user pool  is created with schema attributes still under `Schema`:
```json
{
  "UserPool":{
    "Id":"us-east-1_06432c1eeaa2401ca7bd4cd5b510fbe0",
    "Arn":"arn:aws:cognito-idp:us-east-1:000000000000:userpool/us-east-1_06432c1eeaa2401ca7bd4cd5b510fbe0",
    "Name":"Test pool",
    "Status":null,
    "CreationDate":1616023694.0,
    "LastModifiedDate":1616023694.0,
    "AdminCreateUserConfig":{
      "AllowAdminCreateUserOnly":true
    },
    "PoolName":"Test pool",
    "Schema":[
      {
        "AttributeDataType":"String",
        "DeveloperOnlyAttribute":false,
        "Mutable":false,
        "Name":"internalUserId",
        "Required":true
      }
    ],
    "UsernameAttributes":[
      "email"
    ]
  }
}
```

## Command used to start LocalStack

`docker-compose.yml`:
```yaml
version: '3.4'
services:
  localstack:
    container_name: laws_localstack
    image: localstack/localstack
    privileged: true
    ports:
      - 4566:4566
    environment:
      - SERVICES="cloudformation,cognito-idp,iam,lambda,s3,sns,sqs,ssm,sts"
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=local_link
      - HOST_TMP_FOLDER=/tmp/localstack
      - SMTP_HOST=host.docker.internal
      - SMTP_USER=username
      - SMTP_PASS=password
      - SMTP_EMAIL=no-reply@example.com
      - START_WEB=0 
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      link:
        ipv4_address: 172.28.1.2
networks:
  link:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

`POST http://localhost:4566`
```json
{
  "AdminCreateUserConfig": {
    "AllowAdminCreateUserOnly": true
  },
  "PoolName": "Test pool",
  "Schema": [{
      "AttributeDataType": "String",
      "DeveloperOnlyAttribute": false,
      "Mutable": false,
      "Name": "internalUserId",
      "Required": true
    }],
  "UsernameAttributes": ["email"]
}
```
