### ISSUE TITLE
Step functions with API Gateway returning  Could not resolve host

### ISSUE THREAD

**Issue by Vmacedo-Daitan** [localstack/localstack#3777]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
When deploying a step function with and API Gateway the URL created cannot be resolved.
...

## Expected behavior
Call the step functions by API Gateway
...

## Actual behavior
When try to CURL the step functions it returns the error "Could not resolve host"
...

# Steps to reproduce
Create a step function with an HTTP:
```
functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    helloMachine:
      name: hello-machine-step
      events:
        - http:
            path: hello
            method: GET
      definition:
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true
```

After deploying, I get the message below:
```
Service Information
service: stepf-by-api
stage: local
region: us-east-1
stack: stepf-by-api-dev
resources: 12
api keys:
  None
endpoints:
  http://localhost:4566/restapis/2fhrtughr0/local/_user_request_
functions:
  hello: stepf-by-api-local-hello
layers:
  None
Serverless StepFunctions OutPuts
endpoints:
  GET - https://2fhrtughr0.execute-api.us-east-1.localhost/local/hello
```

And when I curl, I get;
'''
> curl https://2fhrtughr0.execute-api.us-east-1.localhost/local/hello
curl: (6) Could not resolve host: 2fhrtughr0.execute-api.us-east-1.localhost
'''

## Command used to start LocalStack
docker-compose up
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...
