### ISSUE TITLE
Cannot use cloudformation package command

### ISSUE THREAD

**Issue by paul-uz** [localstack/localstack#3788]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
Trying to run `cloudformation package` to deploy a stack with nested stacks. Tried both `aws` and `awslocal`

```
aws --version
aws-cli/2.1.29 Python/3.9.2 Darwin/20.1.0 source/x86_64 prompt/off
```

```
awslocal --version
aws-cli/2.1.29 Python/3.9.2 Darwin/20.1.0 source/x86_64 prompt/off
```

...

## Expected behavior
Cloudformation package is created and dropped in local s3 bucket
...

## Actual behavior
Command errors out

Using AWS
`aws --endpoint-url http://localhost:4566 cloudformation package --template nested_stacks/media_library_v2.yml --s3-bucket deployment.localstack.gc.zone --output-template media-template-export.yml --profile localstack`

`Unable to upload artifact ../.dist/lambda/GCAdminMediaLibraryV2S3Notification/lambda.zip referenced by CodeUri parameter of GCAdminMediaLibraryV2S3Notification resource.
An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.`

Using AWSLocal

`awslocal --s3-endpoint-url=http://localhost:4566 cloudformation package --template nested_stacks/media_library_v2.yml --s3-bucket deployment.localstack.gc.zone --output-template media-template-export.yml`

`Unknown options: --s3-endpoint-url=http://localhost:4566,--s3-endpoint-url=http://localhost:4566`
...

# Steps to reproduce

## Command used to start LocalStack
`TMPDIR=/private$TMPDIR docker-compose up`

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by mgagliardo** [comment]
Hello @paul-uz, could you please hand me over the template YAML you are using so I can try to reproduce this? Thanks.

**Comment by paul-uz** [comment]
@mgagliardo I cannot pass you the exact template file, but you can literally use any Cloudformation template and you'll get the error I did, assuming you are using the same versions of the tools I used.

**Comment by rnjailamba** [comment]
@mgagliardo i am facing the same issue and can provide the template.yaml to test this out. CC @whummer 

create-package.sh

```
BUCKET_ID=$(dd if=/dev/random bs=8 count=1 2>/dev/null | od -An -tx1 | tr -d ' \t\n')
BUCKET_NAME_LOCAL=lambda-artifacts-$BUCKET_ID
echo $BUCKET_NAME_LOCAL > bucket-name-local.txt
aws s3 mb s3://$BUCKET_NAME_LOCAL --region us-east-1

awslocal cloudformation package \
--template template.yml \
--s3-endpoint-url=http://localhost:4566 \
--s3-bucket $BUCKET_NAME_LOCAL \
--output-template-file out.yml \
--region us-east-1
```

template.yml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: myATMapp
  
Globals:
  Function:
    Timeout: 50

Resources:
  atmProducerFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmProducer/
      Handler: handler.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - events:PutEvents      

  atmConsumerCase1Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmConsumer/
      Handler: handler.case1Handler
      Runtime: nodejs12.x

  atmConsumerCase2Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmConsumer/
      Handler: handler.case2Handler
      Runtime: nodejs12.x
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - custom.myATMapp
              detail-type:
                - transaction                
              detail:
                location:
                  - "prefix": "NY-"

  atmConsumerCase3Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmConsumer/
      Handler: handler.case3Handler
      Runtime: nodejs12.x
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - custom.myATMapp
              detail-type:
                - transaction                
              detail:
                result:
                  - "anything-but": "approved"

  EventRuleCase1: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "Approved transactions"
      EventPattern: 
        source: 
          - "custom.myATMapp"
        detail-type:
          - transaction   
        detail: 
          result: 
            - "approved"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "atmConsumerCase1Fn"
              - "Arn"
          Id: "atmConsumerTarget1"

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "atmConsumerCase1Fn"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "EventRuleCase1"
          - "Arn"
```
