### ISSUE TITLE
CloudFormation: Missing Support for KMS::Alias

### ISSUE THREAD

**Issue by niebaron** [localstack/localstack#3808]
# Type of request: This is a bug

[x] bug report
[ ] feature request

# Detailed description
I am trying to create KMS key and alias with cloud formation. Unfortunately support for ResourceType `AWS::KMS::Alias` seems to be missing.
 
## Expected behavior
Creating stack with following  CloudFormation template should create kms key and kms alias successfully.
```yaml 
AWSTemplateFormatVersion: 2010-09-09
Description: Test stack

Resources:
  KMSKeyDefinition:
    Type: AWS::KMS::Key
    Properties:
      Description: Sample KMS
      KeyPolicy:
        Version: '2012-10-17'
        Id: 'default'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: '*'

  KMSKeyAlias:
    Type: AWS::KMS::Alias
    DependsOn: KMSKeyDefinition
    Properties:
      AliasName: alias/sample-kms-alias
      TargetKeyId: !Ref KMSKeyDefinition
```

## Actual behavior
It returns following errors:
```log
2021-03-31T11:22:12:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type KMS::Alias when resolving references of resource KMSKeyAlias: {'Type': 'AWS::KMS::Alias', 'DependsOn': 'KMSKeyDefinition', 'Properties': {'AliasName': 'alias/sample-kms-alias', 'TargetKeyId': 'fabf502b-b696-4d25-90dd-fa11ad1dc07b'}, 'LogicalResourceId': 'KMSKeyAlias', 'PhysicalResourceId': None}
2021-03-31T11:22:12:WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "KMS::Alias": {'Type': 'AWS::KMS::Alias', 'DependsOn': 'KMSKeyDefinition', 'Properties': {'AliasName': 'alias/sample-kms-alias', 'TargetKeyId': 'fabf502b-b696-4d25-90dd-fa11ad1dc07b'}, 'LogicalResourceId': 'KMSKeyAlias', 'PhysicalResourceId': None}
```
KMS key is created but Alias is missing.
On the other hand creating KMS alias via cli is possible so I guess implementation is provided.

# Steps to reproduce

## Command used to start LocalStack

``` bash
docker run --rm -v `$(pwd)/test-stack.yml:/tmp/test-stack.yml:ro --name test-stack -e SERVICES="cloudformation,kms" localstack/localstack:0.12.9
```
Where `$(pwd)/test-stack.yml` is an absolute path to template mentioned above.

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

``` bash
docker exec test-stack awslocal cloudformation create-stack --stack-name test-stack --template-body file:///tmp/test-stack.yml
```
