### ISSUE TITLE
Node lambda cannot connect to container in same docker compose stack.

### ISSUE THREAD

**Issue by vangorra** [localstack/localstack#381]
I have a docker-compose file setup similar to this:
``` yml
version: '2'
services:
  mssql-local:
    container_name: mssql-local
    image: microsoft/mssql-server-linux:2017-GA
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: ${MSSQL_LOCAL_PASSWORD}
    ports:
      - 1533:1433
    volumes:
      - ./dist/mssql-data-local:/var/opt/mssql
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    user: ${USERID}:${USERID}

  localstack:
    container_name: localstack
    image: localstack/localstack:0.8.1
    ports:
      - 4567-4582:4567-4582
      - 8080:8080
    volumes:
      - ./dist/localstack/data:/tmp/localstack/data
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LAMBDA_EXECUTOR: docker
      DOCKER_HOST: unix:///var/run/docker.sock
    links:
      - mssql-local
    depends_on:
      - mssql-test
```

The problem:
I can create and invoke node based lambda just fine. When the lambda attempts to connect to a container mssql-local:1433, I get a connection error (getaddrinfo ENOTFOUND).

Work around
If I adjust the lambda to connect to my host's lan ip and forwarded port (192.168.1.103:1533), it works fine. Not particularly portable setup.

Since Node lambdas are run within a sub docker container. My suspicion is that new container is not getting access to the hostnames/network of the parent (localstack) container.

**Comment by whummer** [comment]
Thanks for reporting @vangorra . Note that we spawn a new container for each Lambda invocation, and these containers are not part of the docker-compose stack. Hence, it is the expected behavior that the Lambda containers cannot resolve the `mssql-local` hostname (this is a limitation of Docker/docker-compose rather than LocalStack).

I'm inclined to attach the `wontfix` label to this issue. I'm sure we would be able to find a solution to get this working (e.g., proxying the access to docker-compose containers through LocalStack), but at the end of the day any solution to the scenario you're describing would end up being some kind of hack or workaround.

I don't think portability is a very strong argument in this case. What we are trying to achieve in LocalStack is to provide portability to and compatibility with AWS - how does your example map to AWS, or in other words how would you take the code that connects to `mssql-local` and deploy it in the AWS environment? Does your deployment require Elastic Container Service (which is currently not yet supported in LocalStack)? I guess if we get a better understanding of how your application is deployed in AWS (and how your Lambda is supposed to access the container in AWS), then we can find a solution to make this work in LocalStack. Thanks

**Comment by vangorra** [comment]
Aside from the database, our environment is serverless. The database has a static url.

I'm using the host in docker compose as a form of DNS resolution to simulate that static URL. Perhaps that's a misuse of the hosts in docker compose?

**Comment by vangorra** [comment]
Summary: Some sort of name resolution would be good for services like S3.

In playing around a little bit. I noticed having a hostname is important for another reason. S3 bucket resolution. When creating a lambda (in node). The hostnames are not present. So when you set the endpoints of the S3 service to `${process.env['LOCALSTACK_HOSTNAME']}:4572`, you end up with you lambda attempting to connect to bucketName.172.10.0.2 in order to perform S3 actions.

In my docker compose setup, localstack is named, localstack. I've added an entry in the localstack containers hosts file that resolves bucketName.'localstack' to 172.10.0.2 and even hard-coded my lambda to use 'localstack:4572' as the endpoint. That doesn't, and probably shouldn't work considering the nature of lambdas being executed as sub docker containers.

**Comment by a88zach** [comment]
I solved this in a way where you don't have to worry about the host ip changing.

set up db in docker
```
$ docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 mynet
$ docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=password --restart=always -d postgres:10
```

docker compose for localstack
```
version: "3.5"
services:
  aws:
    container_name: aws
    image: localstack/localstack:0.8.7
    restart: always
    ports:
      - "4568:4568"
      - "4572:4572"
      - "4574:4574"
      - "4576:4576"
      - "8081:8081"
    environment:
      SERVICES: kinesis,s3,lambda,sqs
      DATA_DIR: /tmp/localstack/data
      PORT_WEB_UI: 8081
      LAMBDA_EXECUTOR: docker
    volumes:
      - "./aws:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - hostnet
networks:
  hostnet:
    external: true
    name: mynet

```

Now my lambdas can use `192.168.0.1` to access the database even when my host ip changes
