### ISSUE TITLE
Unable to find forwarding rule for host "localhost:4566", path "POST /", target header "secretsmanager.GetSecretValue"

### ISSUE THREAD

**Issue by AdamSLevy** [localstack/localstack#3819]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I am running the latest version of localstack 0.12.9 and I'm getting the following error when using the AWS golang API to call GetSecretValue.
```
2021-04-01T20:45:15:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "POST /", target header "secretsmanager.GetSecretValue", auth header "", data "b'{"SecretId":"REDACTED"}'"
```

## Expected behavior

GetSecretValue should return successfully.

## Actual behavior

HTTP status code 404

# Steps to reproduce

## Command used to start LocalStack

docker-compose snippet
```
  localstack:
    image: localstack/localstack:0.12.9
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,secretsmanager,route53,acm-pca,s3,kms
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./local-dev/localstack:/docker-entrypoint-initaws.d
      - localstack_data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```
```
docker-compose up -d localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
	secretOutput, err := s.smClient.GetSecretValue(&secretsmanager.GetSecretValueInput{
		SecretId: aws.String(secretID),
	})
```

where `s.smClient` is a `github.com/aws/aws-sdk-go/service/secretsmanager/secretsmanageriface.SecretsManagerAPI` with `github.com/aws/aws-sdk-go v1.32.8`.

Note that this same API succeeds when using the awslocal CLI.
