### ISSUE TITLE
EventBridge: Add support for kinesis target

### ISSUE THREAD

**Issue by Hrily** [localstack/localstack#3826]
# Type of request: This is a ...

- [ ] bug report
- [x] feature request

# Detailed description

Add support for kinesis while creating eventbridge targets

## Expected behavior

An event should be relayed to kinesis.

## Actual behavior

No records in kinesis stream. The following warning is printed in localstack docker logs:

```
2021-04-04T16:09:13:WARNING:localstack.utils.aws.aws_stack: Unsupported Events rule target ARN: "arn:aws:kinesis:us-east-1:000000000000:stream/mystream"
```

# Steps to reproduce

1. Start localstack container. I used following `docker-compose.yaml`

```yaml
version: '3'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=serverless,events
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

2. Create an event-bus

```bash
aws --endpoint http://localhost:4566  events create-event-bus \
                --name "mybus"
```

3. Create eventbridge rule

```bash
aws --endpoint http://localhost:4566  events put-rule \
                --name "myrule" \
                --event-bus-name "mybus"
```

4. Create kinesis stream

```bash
aws --endpoint http://localhost:4566  kinesis create-stream \
                --stream-name "mystream" \
                --shard-count 1
```

5. Create eventbridge target for rule

```bash
aws --endpoint http://localhost:4566  events put-targets \
                --rule "myrule" \
                --event-bus-name "mybus" \
                --targets '{
                        "Id": "9",
                        "Arn": "arn:aws:kinesis:us-east-1:000000000000:stream/mystream"
                }'
```

## Command used to start LocalStack

```bash
docker-compose up
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

See [Steps to reproduce](#steps-to-reproduce)
