### ISSUE TITLE
DynamoDB streams records seem to be always "NEW_AND_OLD_IMAGES" regardless the configuration

### ISSUE THREAD

**Issue by fredliporace** [localstack/localstack#3851]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Thanks for this awesome project!

It seems to me that the records generated by DynamoDB streams are always set to "NEW_AND_OLD_IMAGES" no matter how it is configured.

## Expected behavior

```StreamViewType``` and the remaining stream records should follow the configuration.

## Actual behavior

```StreamViewType``` from generated DynamoDB streams records are always ```NEW_AND_OLD_IMAGES``` regardless of the stream configuration.

# Steps to reproduce

## Command used to start LocalStack

Using docker-compose and localstack 0.12.9.1

```yaml
version: '2.1'

services:
  localstack:
    container_name: cbers04aonaws-localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs,s3,sns,lambda,cloudwatch,dynamodb
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```bash

# Table creation, StreamViewType reported as KEYS_ONLY as expected
$ awslocal dynamodb create-table --table-name BarkTable --attribute-definitions AttributeName=Username,AttributeType=S --key-schema AttributeName=Username,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --stream-specification StreamEnabled=true,StreamViewType=KEYS_ONLY
{
    "TableDescription": {
        "AttributeDefinitions": [
            {
                "AttributeName": "Username",
                "AttributeType": "S"
            }
        ],
        "TableName": "BarkTable",
        "KeySchema": [
            {
                "AttributeName": "Username",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": 1617920506.981,
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": 0.0,
            "LastDecreaseDateTime": 0.0,
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5
        },
        "TableSizeBytes": 0,
        "ItemCount": 0,
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable",
        "StreamSpecification": {
            "StreamEnabled": true,
            "StreamViewType": "KEYS_ONLY"
        },
        "LatestStreamLabel": "2021-04-08T22:21:46.981",
        "LatestStreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981"
    }
}

# Getting information required by get-records, ShardID...
$  awslocal dynamodbstreams describe-stream --stream-arn="arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981"
{
    "StreamDescription": {
        "StreamArn": "arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981",
        "StreamLabel": "2021-04-08T22:21:46.981",
        "StreamStatus": "ENABLED",
        "TableName": "BarkTable",
        "KeySchema": [
            {
                "AttributeName": "Username",
                "KeyType": "HASH"
            }
        ],
        "Shards": [
            {
                "ShardId": "shardId-00000001617900000000-000000000000",
                "SequenceNumberRange": {
                    "StartingSequenceNumber": "49617150634644171324284995361341429422745156736717422594"
                }
            }
        ]
    }
}

# ... and shard iterator
$ awslocal dynamodbstreams get-shard-iterator --stream-arn="arn:aws:dynamodb:us-east-1:000000000000:table/BarkTable/stream/2021-04-08T22:21:46.981" --shard-id="shardId-00000001617900000000-000000000000" --shard-iterator=TRIM_HORIZON
{
    "ShardIterator": "AAAAAAAAAAEPsmwF8Fvs/QhgJDRP15GeHp3/u7iiURU8nIyDMrMapgxLeTPURcS4x+w0gHLk0fZHukhfuOS4DXzDAOYxLKRdVX2NSY+f8Si6EnU1AomYwfJyOKvqUV2ZdHWl+5vezq4Q4HWCk97ACEyXSqr9PIHsg7Du/Z8RiVc/i99Jtc5I98diZ42qxVjiGsKTj2i+zOw2wUR1tZYrC2NnFD0fzgiq"
}

# Changing table to create event
$ awslocal dynamodb put-item --table-name="BarkTable" --item Username={S="Fred"}
{
    "ConsumedCapacity": {
        "TableName": "BarkTable",
        "CapacityUnits": 1.0
    }
}

# Getting records from stream. Note that StreamViewType is NEW_AND_OLD_IMAGES
$ awslocal dynamodbstreams get-records --shard-iterator="AAAAAAAAAAEPsmwF8Fvs/QhgJDRP15GeHp3/u7iiURU8nIyDMrMapgxLeTPURcS4x+w0gHLk0fZHukhfuOS4DXzDAOYxLKRdVX2NSY+f8Si6EnU1AomYwfJyOKvqUV2ZdHWl+5vezq4Q4HWCk97ACEyXSqr9PIHsg7Du/Z8RiVc/i99Jtc5I98diZ42qxVjiGsKTj2i+zOw2wUR1tZYrC2NnFD0fzgiq"
{
    "Records": [
        {
            "eventID": "1",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "us-east-1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1617921007.9894187,
                "Keys": {
                    "Username": {
                        "S": "Fred"
                    }
                },
                "NewImage": {
                    "Username": {
                        "S": "Fred"
                    }
                },
                "SequenceNumber": "49617150634644171324284995361341429422745191302614220802",
                "SizeBytes": 27,
                "StreamViewType": "NEW_AND_OLD_IMAGES"
            }
        }
    ],
    "NextShardIterator": "AAAAAAAAAAEUjdV11Z6RQmhn033hSccCMELdl5BP5YjBYrTFDQ+w5mY0EUknKqVut2rMCt7LaB0lwsPeQnshyaSDglDm2rNj98fwGfa2pdDomsMkWVOOzNiWE2k7QYNm7mYFna7uT7+hIjYLGYsPdytfdl46hieN5M73okNMskY6QIsf+HBX0are/gUx60sx+zl0ljkevoGpIFHar8CpBoLxXocbJSZG"
}





```
