### ISSUE TITLE
ECS service not starting

### ISSUE THREAD

**Issue by victorsmirnov** [localstack/localstack#3866]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

In short: What should I do to start ECS service in paid version.

Additional note: I managed to run ECS service sometimes ago. I saw it working and creating tasks. Now it is not working.

Run localstack in docker-compose. Below is extract from `docker-compose.yml` file:

```
  service-name:
    image: localstack/localstack:latest
    container_name: service-name
    privileged: true
    ports:
      - 4566:4566
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=carpetvista-localstack
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=cloudformation,cloudwatch,dynamodb,ecs,ecr,lambda,logs,s3,secretsmanager,ses,sns,sqs,ssm
      - VIRTUAL_HOST=localhost.localstack.cloud
      - VIRTUAL_PORT=4566
    volumes:
      - localstack:/tmp/localstack
      - ./docker-compose/carpetvista-localstack/docker-entrypoint-initaws.d:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
```

## Expected behaviour

ECS service should start and do something.

## Actual behaviour

ECS service is not started.

Here is health report

```
{
    services: {
        cloudwatch: "running",
        dynamodb: "running",
        dynamodbstreams: "running",
        kinesis: "running",
        lambda: "running",
        logs: "running",
        s3: "running",
        secretsmanager: "running",
        ses: "running",
        sns: "running",
        sqs: "running",
        ssm: "running",
        cloudformation: "running"
    },
    features: {
        persistence: "initialized",
        initScripts: "initializing"
    }
}
```

This is what I see in the log

```
...   | 2021-04-13T10:20:03:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 5541.5802001953125ms
...   | 2021-04-13T10:20:03:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 5556.618928909302ms
...   | 2021-04-13T10:20:05:INFO:botocore.credentials: Found credentials in environment variables.
...   | 2021-04-13T10:20:05:INFO:botocore.credentials: Found credentials in environment variables.
...   | Starting edge router (https port 4566)...
...   | Starting mock CloudFormation service on http port 4566 ...
...   | Starting mock CloudWatch service on http port 4566 ...
...   | [2021-04-13 10:20:05 +0000] [22] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
...   | 2021-04-13T10:20:05:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
...   | [2021-04-13 10:20:05 +0000] [22] [INFO] Running on http://0.0.0.0:48933 (CTRL + C to quit)
...   | 2021-04-13T10:20:05:INFO:hypercorn.error: Running on http://0.0.0.0:48933 (CTRL + C to quit)
...   | Starting mock DynamoDB service on http port 4566 ...
...   | Starting mock DynamoDB Streams service on http port 4566 ...
...   | Starting mock Kinesis service on http port 4566 ...
...   | Starting mock Lambda service on http port 4566 ...
...   | Starting mock CloudWatch Logs service on http port 4566 ...
...   | Starting mock S3 service on http port 4566 ...
...   | Starting mock Secrets Manager service on http port 4566 ...
...   | Starting mock SES service on http port 4566 ...
...   | Starting mock SNS service on http port 4566 ...
...   | Starting mock SQS service on http port 4566 ...
...   | Starting mock SSM service on http port 4566 ...
...   | Waiting for all LocalStack services to be ready
...   | 2021-04-13T10:20:11:INFO:botocore.credentials: Found credentials in environment variables.
...   | Waiting for all LocalStack services to be ready
...   | Ready.
```

There are no signs of any attempt to start ECS service. When I try to use it I get error in logs `Unable to find listener for service "ecs" - please make sure to include it in $SERVICES`
