### ISSUE TITLE
Lambda invocation via event sources does not trigger LAMBDA_FALLBACK_URL or LAMBDA_FORWARD_URL

### ISSUE THREAD

**Issue by vincentcrowe4airelogic** [localstack/localstack#3873]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

## Expected behavior

specified url (e.g. LAMBDA_FALLBAK_URL) is invoked because lambda in event source mapping does not exist

...

## Actual behavior

specified url is not invoked
localstack reports the following warning
2021-04-14T15:19:47:WARNING:localstack.services.awslambda.lambda_api: The resource specified in the request does not exist.

...

Localstack is running via docker-compose

```
localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,dynamodbstreams,lambda
      - DEFAULT_REGION=eu-west-2
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_FALLBACK_URL=http://api/lambda
      - LAMBDA_FORWARD_URL=http://api/lambda
```

I have I create a dynamo table with a stream, then create a event source mapping via the cli 

```
aws lambda create-event-source-mapping --function-name ProcessDynamoDBRecords --batch-size 100 
--starting-position LATEST --event-source arn:aws:dynamodb:eu-west-2:000000000000:table/stock-events/stream/2021-04-14T15:14:35.138 --endpoint-url http://localhost:4566
```

which results in

```
{
    "UUID": "3487d382-9b40-4aa7-8d6f-b4bc093aa508",
    "BatchSize": 100,
    "EventSourceArn": "arn:aws:dynamodb:eu-west-2:000000000000:table/stock-events/stream/2021-04-14T15:14:35.138",
    "FunctionArn": "arn:aws:lambda:eu-west-2:000000000000:function:ProcessDynamoDBRecords",
    "LastModified": "2021-04-14T16:19:09+01:00",
    "LastProcessingResult": "OK",
    "State": "Enabled",
    "StateTransitionReason": "User action"
}
```

I then add a record to dynamo via my application I receive the warning in localstack (indicating that it has found the event mapping and tried to do something, so streams is working)

There seems to be a difference between this and calling invoke on lambda directly (for a non existent lambda) as that does work as expected
...
