### ISSUE TITLE
awslocal cloudformation deploy not working with valid API key

### ISSUE THREAD

**Issue by rnjailamba** [localstack/localstack#3893]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
We are trying to make a producer-consumer eventbridge based system work on local machine. This is the exact example we are trying to get running.
We are trying to deploy the stack locally using the template.yml but it is not deploying.

## Expected behavior
Cloudformation deploy should work with localstack

## Actual behavior
We get this error `Unknown options: --s3-endpoint-url=http://localhost:4566` after running `awslocal cloudformation deploy --stack-name aws-eventbridge-producer-consumer --template-file template.yaml `
We can successfully deploy this stack to AWS using `sam deploy --guided`
<img width="1471" alt="Screen Shot 2021-04-19 at 11 03 54" src="https://user-images.githubusercontent.com/6762840/115282419-0ff8cb80-a0ff-11eb-8bd7-2ca36254b523.png">
The output of `http://localhost:4566/health` is
`{"services": {"cloudwatch": "running", "lambda": "running", "logs": "running", "sns": "running", "sqs": "running", "events": "running", "stepfunctions": "running", "apigateway": "running"}, "features": {"persistence": "initializing"}}
`
An additional test is running `awslocal cloudformation create-stack --stack-name test --template-body file://template.yaml --capabilities CAPABILITY_IAM` which gives `Read timeout on endpoint URL: "http://localhost:4566/"`.

# Steps to reproduce
Just run `awslocal cloudformation deploy --stack-name aws-eventbridge-producer-consumer --template-file template.yaml` in the root folder of this repository - https://github.com/aws-samples/amazon-eventbridge-producer-consumer-example

## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
docker-compose.yml
```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEFAULT_REGION=us-east-1
      - SERVICES=lambda, sqs, sns, events, stepfunctions, apigateway, cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


```

template.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: myATMapp
  
Globals:
  Function:
    Timeout: 50

Resources:
  atmProducerFn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmProducer/
      Handler: handler.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - events:PutEvents      

  atmConsumerCase1Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmConsumer/
      Handler: handler.case1Handler
      Runtime: nodejs12.x

  atmConsumerCase2Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmConsumer/
      Handler: handler.case2Handler
      Runtime: nodejs12.x
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - custom.myATMapp
              detail-type:
                - transaction                
              detail:
                location:
                  - "prefix": "NY-"

  atmConsumerCase3Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: atmConsumer/
      Handler: handler.case3Handler
      Runtime: nodejs12.x
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - custom.myATMapp
              detail-type:
                - transaction                
              detail:
                result:
                  - "anything-but": "approved"

  EventRuleCase1: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "Approved transactions"
      EventPattern: 
        source: 
          - "custom.myATMapp"
        detail-type:
          - transaction   
        detail: 
          result: 
            - "approved"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "atmConsumerCase1Fn"
              - "Arn"
          Id: "atmConsumerTarget1"

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "atmConsumerCase1Fn"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "EventRuleCase1"
          - "Arn"
```
