### ISSUE TITLE
HOSTNAME_EXTERNAL + S3 Presigned URL

### ISSUE THREAD

**Issue by zhoub** [localstack/localstack#3910]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

By definition the docker-compose service as this
```yaml
  localstack:
    image: localstack/localstack-light
    environment:
      EDGE_PORT: '54566'
      HOSTNAME: localhost
      HOSTNAME_EXTERNAL: localhost
      DEBUG: 1
      SERVICES: 's3'
    networks:
      multiverse_subnet:
        ipv4_address: 172.25.1.6
```
With override to define the port
``` yaml
  localstack:
    ports:
      - "54566:54566"
```

From another docker program, create the session
```go
awsSess = session.Must(session.NewSession(&aws.Config{
    Credentials:      credentials.NewStaticCredentials("test", "test", ""),
    S3ForcePathStyle: aws.Bool(true),
    Region:           aws.String(endpoints.UsWest2RegionID),
    Endpoint:         aws.String("http://localstack:54566"),
}))
```
It works with regular S3 operations.

But when creating a presigned url for an object such as
```go
		req, _ := a.s3.PutObjectRequest(&s3.PutObjectInput{
			Bucket: aws.String(a.bkt),
			Key:      aws.String(objFileKey),
		})
		url, err := req.Presign(15 * time.Minute)
		if err != nil {
			log.Print(err)
			return nil, err
		}
```

The URL starts with "http://localstack" not external host name "http://localhost"

## Expected behavior

It should generate presigned URL with `http://localhost:54566` instead of `http://localstack`

## Actual behavior

It still uses "http://localstack".

Any ideas ? Thanks in advance 1
