### ISSUE TITLE
Invoke lambda ends up with read timeout on 0.12.10 image

### ISSUE THREAD

**Issue by aandrzejewski** [localstack/localstack#3935]
# Type of request: This is a ...

[x ] bug report
[ ] feature request

# Detailed description
Invocation of lambda that was connecting to dynamodb fails on latest image, was working fine on 0.12.9 version

$ aws --endpoint-url=http://localhost:4566 lambda invoke --function-name test-lambda ./test/test-output.json

Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/test-lambda/invocations"

...

## Expected behavior
Lambda runs as previously
...

## Actual behavior
Invocation fails with read timeout
...

# Steps to reproduce
Try to invoke lambda that connects to dynamodb instance of localstack

## Command used to start LocalStack
docker-compose up
docker-compose.yaml
```
version: '3'
services:
  localstack:
    container_name: localstack_test_instance
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,lambda
      - DEFAULT_REGION=eu-west-1
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
echo "create lambda"
aws --endpoint-url=http://localhost:4566 lambda create-function \
    --function-name ${LAMBDA_NAME} \
    --zip-file fileb://${LAMBDADIR}/target/${LAMBDA_DIST_NAME}.zip\
    --role irrelevant \
    --runtime nodejs12.x \
    --handler index.handler \
    --environment Variables={INSTANCE_ID="${INSTANCE_ID}"} \
    --region eu-west-1 >/dev/null

echo "invoke lambda"
aws --endpoint-url=http://localhost:4566 lambda invoke --function-name ${LAMBDA_NAME} ./test/test-output.json
...
