### ISSUE TITLE
API gateway put-integration-response error: Invalid request input

### ISSUE THREAD

**Issue by kigawas** [localstack/localstack#3936]
## Docker compose file
```yaml
version: "3"

services:
  localstack:
    image: localstack/localstack
    network_mode: bridge # localhost rather than host.docker.internal
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=lambda,sqs,dynamodb,s3,apigateway
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ".data/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

## Commands
```bash
aws --endpoint-url=http://localhost:4566 apigateway create-rest-api --name "TEST"   #  REST_API_ID is in the result

aws --endpoint-url=http://localhost:4566 apigateway get-resources --rest-api-id $REST_API_ID  # PARENT_ID is in the result

aws --endpoint-url=http://localhost:4566 apigateway create-resource --rest-api-id $REST_API_ID --parent-id $PARENT_ID --path-part pets  # RESOURCE_ID is in the result

aws --endpoint-url=http://localhost:4566 apigateway put-method --rest-api-id $REST_API_ID \
       --resource-id $RESOURCE_ID \
       --http-method GET \
       --authorization-type "NONE"

aws --endpoint-url=http://localhost:4566 apigateway put-method-response --rest-api-id $REST_API_ID \
       --resource-id $RESOURCE_ID --http-method GET \
       --status-code 200

aws --endpoint-url=http://localhost:4566 apigateway put-integration --rest-api-id $REST_API_ID \
       --resource-id $RESOURCE_ID --http-method GET --type HTTP \
       --integration-http-method GET \
       --uri 'http://petstore-demo-endpoint.execute-api.com/petstore/pets'

aws --endpoint-url=http://localhost:4566 apigateway put-integration-response --rest-api-id $REST_API_ID \
       --resource-id $RESOURCE_ID --http-method GET \
       --status-code 200 --selection-pattern ""
```

At the last step, it complains:
```
An error occurred (BadRequestException) when calling the PutIntegrationResponse operation: Invalid request input
```
