### ISSUE TITLE
S3 Presigned POST returns 404

### ISSUE THREAD

**Issue by andres-bayon** [localstack/localstack#3946]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

Trying to use the S3 presigned POST file URL with multipart I get a 404 error. It works on AWS. The following issues seems related, but using the latest version it does not work:
- https://github.com/localstack/localstack/issues/2837
- https://github.com/localstack/localstack/issues/2948

## Expected behavior

Upload file and get a 204 HTTP code.

## Actual behavior

I get a 404 error.

# Steps to reproduce

## Command used to start LocalStack

```bash
docker compose up -d
```

```yaml
version: '2.1'

services:
  localstack:
    image: localstack/localstack-full:latest
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
    environment:
      - SERVICES=serverless,ssm,sts,ses
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=true
      - START_WEB=false
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```javascript
const s3 = new AWS.S3({ s3ForcePathStyle: true });
s3.createPresignedPost({
      Bucket: 'mybucket',
      Fields: {
        Key: 'mykey'
      },
}, (error, data) => {
      resolve(data);
});
```

With the data returned, I do the following call:
```bash
curl --location --request POST 'http://local.com:4566/mybucket' \
--form 'Key="mykey"' \
--form 'Policy="..."' \
--form 'X-Amz-Algorithm="AWS4-HMAC-SHA256"' \
--form 'X-Amz-Credential="test/20210429/eu-west-1/s3/aws4_request"' \
--form 'X-Amz-Date="20210429T140136Z"' \
--form 'X-Amz-Security-Token="null"' \
--form 'X-Amz-Signature="..."' \
--form 'file=@"fileroute"'
```

I get a 404 HTTP code with the following text: `{"status": "running"}`.
The localstack log returns the following:
```
2021-04-29T14:21:22:INFO:localstack.services.edge: Unable to find forwarding rule for host "local.com:4566", path "POST /mybucket", target header "", auth header "", data "b'------WebKitFormBoundaryN6VFn13rghiCptta\r\nContent-Disposition: form-data; name="Key"\r\n\r\n15tWon8OXQ/a'..."
```
