### ISSUE TITLE
Runtime.ImportModuleError: Unable to import module

### ISSUE THREAD

**Issue by weili11864** [localstack/localstack#3949]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

I tried to integrate localstack in my Jenkins pipeline so we can run integration test for a lambda service before we deploy it to AWS. The lambda service is written by Python and the localstack is started by Jenkins Kubernetes plugin. Within the localstack container, I create a zip package which includes the lambda handler file and then use aws cli to create a lambda service. The function is created successfully. However, when I use aws cli to invoke the lambda service, it returns error "{"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"Runtime.ImportModuleError\",\"errorMessage\":\"Unable to import module 'hello_python': No module named 'hello_python'\"}.". 

When I use docker to start the localstack in my local and follow the same steps, the lambda service is working as expected.

## Expected behavior

The lambda service should be invoked and return correct response.

## Actual behavior

The lambda service fails with error response
```
{
    "FunctionError": "Unhandled",
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST",
    "LogResult": ""
}
```

detailed error message:
```
{"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"Runtime.ImportModuleError\",\"errorMessage\":\"Unable to import module 'hello_python': No module named 'hello_python'\"}. Output:\n\u001b[32mSTART RequestId: 7df5de1f-e46d-1cb1-becb-a0108f30b919 Version: $LATEST\u001b[0m\n[ERROR] Runtime.ImportModuleError: Unable to import module 'hello_python': No module named 'hello_python'\n\u001b[32mEND RequestId: 7df5de1f-e46d-1cb1-becb-a0108f30b919\u001b[0m\n\u001b[32mREPORT RequestId: 7df5de1f-e46d-1cb1-becb-a0108f30b919\tInit Duration: 256.91 ms\tDuration: 3.23 ms\tBilled Duration: 4 ms\tMemory Size: 1536 MB\tMax Memory Used: 25 MB\t\u001b[0m","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 602, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 176, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 168, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 159, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 147, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 325, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 231, in run_lambda_executor\n    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}
```

# Steps to reproduce

- Create a Kubernetes cluster configuration KubernetesPods.yaml for Jenkins including localstack
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dev-dev-python-lambda-reference-typescript-starter-app
spec:
  containers:
    - name: localstack
      image: localstack/localstack
      ports:
        - name: http
          hostPort: 4566
          containerPort: 4566
      envVars:
        - envVar:
            key: SERVICES
            value: lambda,s3
        - envVar:
            key: LAMBDA_EXECUTOR
            value: docker
        - envVar:
            key: LAMBDA_REMOVE_CONTAINERS
            value: false
        - envVar:
            key: DOCKER_HOST
            value: unix:///var/run/docker.sock
      volumeMounts:
        - name: localstack
          mountPath: /tmp/localstack
        - name: docker-volume
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-volume
      hostPath:
        path: /var/run/docker.sock
    - name: localstack
      emptyDir: {}
```
- Create a python lambda handler hello_python.py
```python
import os
def my_handler(event, context): 
    message = '{} {} {}!'.format(os.environ['GREETING'],
                                 event['last_name'],
                                 event['first_name'])
    return {
        'message': message
    }
```
- Create a stage in a Jenkinsfile
```
pipeline {
gent {
        kubernetes {
            label "pod_label"
            yamlFile 'KubernetesPods.yaml'
        }
        stages {
stage('Integration Test') {
                    steps {
                        container('integration') {
                            script {
                                //
                                sh """
                                    aws configure set aws_access_key_id test
                                    aws configure set aws_secret_access_key test
                                    aws configure set default.region us-east-1
                                    
                                    zip service_name.zip hello_python.py
                                    
                                    echo "Create Lambda function..."
                                    aws lambda create-function --function-name lambda_service --zip-file fileb://service_name.zip --handler hello_python.my_handler --runtime python3.8 --role test --endpoint-url http://localhost:4566 --environment Variables={GREETING=Hello}

                                    echo "Invoke lambda function..."
                                    aws lambda invoke --function-name lambda_service --invocation-type RequestResponse --payload '{"first_name": "Frist", "last_name": "Last"}' --endpoint-url http://localhost:4566 response.json

                                    echo "Display lambda reponse: "
                                    cat response.json
                                """
                            }
                        }
                    }
                }
        }
}
```
## Command used to start LocalStack

Jenkins Kubernates plugin

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws lambda create-function --function-name lambda_service --zip-file fileb://service_name.zip --handler hello_python.my_handler --runtime python3.8 --role test --endpoint-url http://localhost:4566 --environment Variables={GREETING=Hello}
```

```
aws lambda invoke --function-name lambda_service --invocation-type RequestResponse --payload '{"first_name": "Frist", "last_name": "Last"}' --endpoint-url http://localhost:4566 response.json
```

**Comment by mgagliardo** [comment]
Hello @weili11864, would you please try setting `LAMBDA_REMOTE_DOCKER=false` on your YAML and make sure `HOST_TMP_FOLDER` is defined AND mounted on the pod? (This is already on localstack's readme). Thanks!

**Comment by weili11864** [comment]
@mgagliardo , actually I tried the two settings but still have the same issues. Here is my settings for localstack:
`    
- name: localstack
      image: localstack/localstack
      ports:
        - name: http
          hostPort: 4566
          containerPort: 4566
      envVars:
        - envVar:
            key: SERVICES
            value: lambda,s3
        - envVar:
            key: LAMBDA_EXECUTOR
            value: docker
        - envVar:
            key: LAMBDA_REMOVE_CONTAINERS
            value: false
        - envVar:
            key: DOCKER_HOST
            value: unix:///var/run/docker.sock
        - envVar:
            key: HOST_TMP_FOLDER
            value: /tmp/localstack
      volumeMounts:
        - name: localstack
          mountPath: /tmp/localstack
        - name: dind-volume
          mountPath: /var/run/docker.sock
`

Is there anything else I can try? Thanks.

**Comment by mgagliardo** [comment]
Sorry I am not seeing `LAMBDA_REMOTE_DOCKER` set to `false` there. 
But besides that, what happens if you run all these locally? Can you reproduce the issue locally? Or it just happens when running it on k8s? Have you tested it with a local runtime like minikube/microk8s/other?

**Comment by weili11864** [comment]
I can start localstack by docker in my local, and create and invoke the same lambda service within the container without any issue. It looks like it is an issue related to k8s. I have not tested it in K8s locally yet, but I will give it a try.

**Comment by weili11864** [comment]
@mgagliardo , I can reproduce the lambda service error in my local k8s runtime (minikube). Here is the pod configuration for localstack:
`
apiVersion: v1
kind: Pod
metadata:
  name: localstack-lambda
spec:
  containers:
    - name: localstack
      image: localstack/localstack
      ports:
        - containerPort: 4566
      env:
        - name: SERVICES
          value: lambda,s3
        - name: LAMBDA_EXECUTOR
          value: docker
        - name: LAMBDA_REMOVE_CONTAINERS
          value: "false"
        - name: LAMBDA_REMOTE_DOCKER
          value: "false"
        - name: HOST_TMP_FOLDER
          value: /tmp/localstack
      volumeMounts:
        - name: localstack
          mountPath: /tmp/localstack
        - name: dind-volume
          mountPath: /var/run/docker.sock
        - name: app
          mountPath: /tmp/app
  volumes:
    - name: dind-volume
      hostPath:
        path: /var/run/docker.sock
    - name: localstack
      emptyDir: {}
    - name: app
      hostPath:
        path: /Users/wli5/Projects/localstack-lambda/src
  hostNetwork: true
  dnsPolicy: Default
`
I did use LAMBDA_REMOTE_DOCKER and HOST_TMP_FOLDER, but it does not help. Please advise. Thanks. (sorry for the code format)

**Comment by weili11864** [comment]
Here is the detailed message from response. Hopefully it can provide you debug
`
{"errorMessage":"Lambda process returned error status code: 1. Result: {\"errorType\":\"Runtime.ImportModuleError\",\"errorMessage\":\"Unable to import module 'hello_python': No module named 'hello_python'\"}. Output:\nUnable to find image 'lambci/lambda:python3.8' locally\npython3.8: Pulling from lambci/lambda\nDigest: sha256:be943e04cfeda15e0ea141d84a914b12f500194a694e809bb3cd0d0dd187aa56\nStatus: Image is up to date for lambci/lambda:python3.8\n\u001b[32mSTART RequestId: 36ce8e29-d572-1420-f30d-ffc4900fdff9 Version: $LATEST\u001b[0m\n[ERROR] Runtime.ImportModuleError: Unable to import module 'hello_python': No module named 'hello_python'\n\u001b[32mEND RequestId: 36ce8e29-d572-1420-f30d-ffc4900fdff9\u001b[0m\n\u001b[32mREPORT RequestId: 36ce8e29-d572-1420-f30d-ffc4900fdff9\tInit Duration: 115.66 ms\tDuration: 3.43 ms\tBilled Duration: 4 ms\tMemory Size: 1536 MB\tMax Memory Used: 25 MB\t\u001b[0m","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 602, in run_lambda\n    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 176, in execute\n    return do_execute()\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 168, in do_execute\n    return _run(func_arn=func_arn)\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 149, in wrapped\n    raise e\n","  File \"/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py\", line 145, in wrapped\n    result = func(*args, **kwargs)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 159, in _run\n    raise e\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 147, in _run\n    result = self._execute(func_arn, func_details, event, context, version)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 325, in _execute\n    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 231, in run_lambda_executor\n    raise InvocationException('Lambda process returned error status code: %s. Result: %s. Output:\\n%s' %\n"]}

`

**Comment by pandomic** [comment]
@weili11864 pleae try explicitly setting `LAMBDA_REMOTE_DOCKER=true` in your configuration, could be that `in_docker()` function is not properly determining if we are in docker for this particular case (to be confirmed) . I was able to successfully run your example with the following setup:

hello_python.py
```python
import os


def my_handler(event, context): 
    message = '{} {} {}!'.format(os.environ['GREETING'],
                                 event['last_name'],
                                 event['first_name'])
    return {'message': message}
```

localstack-lambda.yml
```
apiVersion: v1
kind: Pod
metadata:
  name: localstack-lambda
spec:
  containers:
    - name: localstack
      image: localstack/localstack
      ports:
        - containerPort: 4566
      env:
        - name: SERVICES
          value: lambda,s3
        - name: LAMBDA_EXECUTOR
          value: docker
        - name: LAMBDA_REMOVE_CONTAINERS
          value: "false"
        - name: LAMBDA_REMOTE_DOCKER
          value: "true"
        - name: HOST_TMP_FOLDER
          value: /tmp/localstack
      volumeMounts:
        - name: localstack
          mountPath: /tmp/localstack
        - name: dind-volume
          mountPath: /var/run/docker.sock
#        - name: app
#          mountPath: /tmp/app
  volumes:
    - name: dind-volume
      hostPath:
        path: /var/run/docker.sock
    - name: localstack
      emptyDir: {}
#    - name: app
#      hostPath:
#        path: ...
  hostNetwork: true
  dnsPolicy: Default
```

```bash
kubectl apply -f ./localstack-lambda.yml
kubectl port-forward pods/localstack-lambda 4566:4566

zip service_name.zip hello_python.py

awslocal lambda create-function --function-name lambda_service --zip-file fileb://<absolute-path>/service_name.zip --handler hello_python.my_handler --runtime python3.8 --role test --environment Variables={GREETING=Hello}

awslocal lambda invoke --function-name lambda_service --invocation-type RequestResponse --payload '{"first_name": "Frist", "last_name": "Last"}' response.json

cat response.json

# => {"message":"Hello Last Frist!"}
```

If you wish to pass your lambda code by mounting, then you need to make sure you properly configured mounting points.
