### ISSUE TITLE
Getting error while deploy serverless stack 

### ISSUE THREAD

**Issue by pravin-raha** [localstack/localstack#3969]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
I am following serverless-localstack example to test my server-less app.

serverless.yml
```
service:
  name: aws-node-typescript-sqs-standard

plugins:
  - serverless-webpack
  - serverless-localstack

custom:
  localstack:
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost  # optional - LocalStack host to connect to
    edgePort: 4566  # optional - LocalStack edge port to connect to
    autostart: true  # optional - Start LocalStack in Docker on Serverless deploy
    lambda:
      # Enable this flag to improve performance
      mountCode: True
    docker:
      # Enable this

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  deploymentBucket:
    name: test-node-typescript-bucket
    serverSideEncryption: AES256
  # role: DefaultLambdaRole
  iam:
    role: arn:aws:iam::000000000000:policy/aws-node-typescript-sqs-standard-local-us-east-1-lambdaRole
    deploymentRole: arn:aws:iam::000000000000:policy/aws-node-typescript-sqs-standard-local-us-east-1-lambdaRole

functions:
  sender:
    handler: handler.sender
    events:
      - http:
          method: post
          path: sender

  receiver:
    handler: handler.receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: receiverQueue

```

###Error while executing: SLS_DEBUG=* sls deploy --stage local

```
  ServerlessError: An error occurred: aws-node-typescript-sqs-standard-local - undefined.
      at /home/pravin/.nvm/versions/node/v12.16.3/lib/node_modules/serverless/lib/plugins/aws/lib/monitorStack.js:94:23
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

###Localstack logs
```
2021-05-04T14:54:41:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.Lambda object at 0x7f96ca8e23d0>> with params: {'FunctionName': 'aws-node-typescript-sqs-standard-local-sender', 'Runtime': 'nodejs12.x', 'Role': 'arn:aws:iam::000000000000:policy/aws-node-typescript-sqs-standard-local-us-east-1-lambdaRole', 'Handler': 'handler.sender', 'Code': {'S3Bucket': '__local__', 'S3Key': '/mnt/e/project/codebase/serverless-examples/aws-node-typescript-sqs-standard'}, 'Timeout': 6, 'MemorySize': 1024} for resource: {'Type': 'AWS::Lambda::Function', 'Properties': {'Code': {'S3Bucket': '__local__', 'S3Key': '/mnt/e/project/codebase/serverless-examples/aws-node-typescript-sqs-standard'}, 'Handler': 'handler.sender', 'Runtime': 'nodejs12.x', 'FunctionName': 'aws-node-typescript-sqs-standard-local-sender', 'MemorySize': 1024, 'Timeout': 6, 'Role': 'arn:aws:iam::000000000000:policy/aws-node-typescript-sqs-standard-local-us-east-1-lambdaRole'}, 'DependsOn': ['SenderLogGroup'], 'LogicalResourceId': 'SenderLambdaFunction', 'PhysicalResourceId': None, '_state_': {}}
```
