### ISSUE TITLE
AWS SDK 2 ListObjects(BucketName) didn't not work with Localstack

### ISSUE THREAD

**Issue by DiesDasJenes** [localstack/localstack#4005]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

I was using localstack to test the AWS SDK2 for java with SpringBoot 2. I used the latest localstack version in a docker container. The goal was to list files in a bucket. This was not possible with AWS SDK 2 but with the AWS SDK 1.1 version. Does the AWS SDK2 work with localstack?
 
More details can be found here: https://github.com/aws/aws-sdk-java-v2/issues/2447

## Expected behavior

Localstack returns the list of objects to the AWS handler.

## Actual behavior

The AWS handler throws an exception.

# Steps to reproduce

Create basic SpringBoot app. 
Use this compose file: 
```
version: '3.3'

services:
  localstack:
    image: localstack/localstack
    container_name: 'localstack'
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-9000}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    healthcheck:
      test: "bash -c 'aws --endpoint-url=http://localhost:4566 --no-sign-request --region=eu-central-1 s3api list-buckets'"
      interval: 3s
      timeout: 10s
      retries: 20
```

Then create the files for the local configuration and try to list objects in the bucket. I put everything in the open issue here: https://github.com/aws/aws-sdk-java-v2/issues/2447

## Command used to start LocalStack
Here is the following script to start localstack with the compose file and a test tar.gz file
```
#!/usr/bin/env bash
set -e -o pipefail

function start_container() {
  local compose_file="local/localstack-compose.yml"
  if [ ! -z ${DOCKER_HOST} ]; then
    export LOCALSTACK_DOCKER_HOST=${DOCKER_HOST}
    export LOCALSTACK_HOST=docker
  fi
  docker-compose -p localstack --file ${compose_file} up --build --detach
}

function wait_for_localstack() {
  local container="localstack"
 # https://github.com/jordyv/wait-for-healthy-container
  ./local/wait-for-healthy-container.sh ${container}
}

function create_bucket() {
  aws s3 mb s3://"$1" \
            --endpoint="http://localhost:4566" \
            --no-sign-request \
            --no-cli-pager \
            --region eu-central-1
}

function upload_files() {
  aws s3 cp ./local/pizza_folder.tar.gz  s3://"$1" \
            --endpoint="http://localhost:4566" \
            --no-sign-request \
            --no-cli-pager  \
            --region eu-central-1
}

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../"
pushd "${PROJECT_DIR}" > /dev/null
  start_container
  wait_for_localstack
  bucket="test-local"
  create_bucket $bucket
  upload_files $bucket
popd > /dev/null
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

Everything can be found here: https://github.com/aws/aws-sdk-java-v2/issues/2447

```
ListObjectsRequest listObjectsRequest = ListObjectsRequest.builder().bucket(bucketName).build();
s3Client.listObjects(listObjectsRequest).contents();
```

Thanks for the support. :)

**Comment by rahulv84** [comment]
I am facing same issue. I am using sdk's listObjectsV2() method. This issue has been open for long, did you find any solution?
Any clue will be a great help.

Code:
`ListObjectsV2Request listObjectsV2Request = ListObjectsV2Request.builder().bucket("bucketName").build();
ListObjectsV2Response listObjectsResponse = s3Client.listObjectsV2(listObjectsV2Request);`

Exception:
`software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 404, Request ID: null)'

**Comment by DiesDasJenes** [comment]
Aloha,
No unfortunately i wasn't able to figure out the root cause and as I was under time pressure i moved to aws sdk1 which worked perfectly. 
Cheers :)

**Comment by Dylan-DutchAndBold** [comment]
Hi, I also have run into this issue while unit testing against localstack. I had actually been using adobe/s3mock on which it is working fine, but moved to localstack for the ACL support which I need to test other parts of the library.

From what I have determined the SDK fails when it gets a 404 when it tries to make this call below, which is initiated by the async enumerator.
```bash
curl --location --request GET 'http://127.0.0.1:4566/listing-contents-recursive' \
--header 'User-Agent:  aws-sdk-dotnet-coreclr/3.7.1.27 aws-sdk-dotnet-core/3.7.2.7 .NET_Core/5.0.9 OS/Darwin_20.6.0_Darwin_Kernel_Version_20.6.0:_Wed_Jun_23_00:26:31_PDT_2021;_root:xnu-7195.141.2~5/RELEASE_X86_64 ClientAsync Paginator' \
--header 'amz-sdk-invocation-id:  3be8f9ce-1092-49c8-aafc-ae28c98d6c49' \
--header 'amz-sdk-request:  attempt=1; max=5'
```

**My environment**
Language: C#9
Framework: .NET 5
AWSSDK.S3 version: 3.7.1.28
Localstack version: 0.12.17.3

docker-compose.yml:
```yaml
version: '3.3'
services:
  s3mock:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      SERVICES: s3
```

**Comment by pushplay** [comment]
I believe I had the same issue.  What worked for me was rolling back to localstack version 0.12.15.

Here's my take on steps to reproduce the problem.  I have a script that creates the bucket, adds an item and lists items a couple ways to prove that works, and then lists items in the JS SDK.

This has been tested with node v16.3.0 and v14.17.1.

docker-compose.yml
```yml
version: "3.3"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER="${TMPDIR:-/tmp}/localstack"
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

bugreport.sh
```sh
#!/usr/bin/env bash

aws s3api create-bucket --bucket bug-report --endpoint-url http://localhost:4566
aws s3 cp ./bugreport.sh s3://bug-report --endpoint-url http://localhost:4566
aws s3 ls s3://bug-report --endpoint-url http://localhost:4566
aws s3api list-objects-v2 --bucket bug-report --endpoint-url http://localhost:4566
```

package.json
```json
{
  "name": "bug_report",
  "version": "1.0.0",
  "description": "",
  "main": "bugreport.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-sdk": "^2.996.0"
  }
}
```

bugreport.js
```javascript
const aws = require("aws-sdk");

const s3 = new aws.S3({endpoint: "http://localhost:4566"});
s3.listObjectsV2({Bucket: "bug-report"})
    .promise()
    .then(console.log.bind(console), console.error.bind(console));
```

Set up dependencies:
```
npm i
docker-compose up
```

Expected output (this works in 0.12.15)
```
❯ ./bugreport.sh
{
    "Location": "/bug-report"
}
upload: ./bugreport.sh to s3://bug-report/bugreport.sh
2021-09-28 14:47:35        326 bugreport.sh
{
    "Contents": [
        {
            "Key": "bugreport.sh",
            "LastModified": "2021-09-28T21:47:35+00:00",
            "ETag": "\"db2039aaa37714b07d23f1db9faf9b9d\"",
            "Size": 326,
            "StorageClass": "STANDARD"
        }
    ]
}
❯ node bugreport.js
{
  IsTruncated: false,
  Contents: [
    {
      Key: 'bugreport.sh',
      LastModified: 2021-09-28T21:47:35.000Z,
      ETag: '"db2039aaa37714b07d23f1db9faf9b9d"',
      Size: 326,
      StorageClass: 'STANDARD'
    }
  ],
  Name: 'bug-report',
  Prefix: '',
  MaxKeys: 1000,
  CommonPrefixes: [],
  KeyCount: 1
}
```

Actual output (broken in 0.12.16 and later)
```
❯ ./bugreport.sh
{
    "Location": "/bug-report"
}
upload: ./bugreport.sh to s3://bug-report/bugreport.sh
2021-09-28 14:49:04        326 bugreport.sh
{
    "Contents": [
        {
            "Key": "bugreport.sh",
            "LastModified": "2021-09-28T21:49:04+00:00",
            "ETag": "\"db2039aaa37714b07d23f1db9faf9b9d\"",
            "Size": 326,
            "StorageClass": "STANDARD"
        }
    ]
}
❯ node bugreport.js
{ Contents: [], CommonPrefixes: [] }
```
