### ISSUE TITLE
Redshift + CloudFormation error

### ISSUE THREAD

**Issue by jleck** [localstack/localstack#4032]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

When deploying with Cloudformation (well, generated through CDK), it fails with an unexpected resource type for ClusterSubnetGroup.

## Expected behavior

Deploy

## Actual behavior

```
WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type Redshift::ClusterSubnetGroup when resolving references of resource AIOLocalstackCoreServiceWarehouseRedshiftSubnets0ABC9112: {'Type': 'AWS::Redshift::ClusterSubnetGroup', 'UpdateReplacePolicy': 'Delete', 'DeletionPolicy': 'Delete', 'Metadata': {'aws:cdk:path': 'AIO-Localstack-Core/AIO-Localstack-Core-ServiceWarehouse/Redshift/Subnets/Default'}, 'LogicalResourceId': 'AIOLocalstackCoreServiceWarehouseRedshiftSubnets0ABC9112', 'Properties': {'Description': 'Subnets for Redshift Redshift cluster', 'SubnetIds': ['subnet-1482e359', 'subnet-8f16f53d']}}
```

# Steps to reproduce

## Command used to start LocalStack

```
version: "3"
services:
  localstack:
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-2
      - HOST_TMP_FOLDER=/tmp/localstack
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=cloudformation,cloudwatch,ec2,events,logs,redshift,secretsmanager,serverless,sqs,sts
      - START_WEB=0
    image: localstack/localstack
    ports:
      - 443:443
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
"AIOLocalstackCoreServiceWarehouseRedshiftSubnets0ABC9112": {
      "Type": "AWS::Redshift::ClusterSubnetGroup",
      "Properties": {
        "Description": "Subnets for Redshift Redshift cluster",
        "SubnetIds": [
          {
            "Ref": "AIOLocalstackCoreServiceWarehouseVpcPrivateSubnet1SubnetF5FE5BF0"
          },
          {
            "Ref": "AIOLocalstackCoreServiceWarehouseVpcPrivateSubnet2SubnetD0A9D929"
          }
        ]
      },
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "AIO-Localstack-Core/AIO-Localstack-Core-ServiceWarehouse/Redshift/Subnets/Default"
      }
    },
```

Can be produced by doing the following in CDK:

```
const cluster = new Cluster(this, "Redshift", {
      clusterName: `${resourcePrefix}-ServiceWarehouse-Redshift`,
      clusterType: ClusterType.SINGLE_NODE,
      masterUser: {
        masterUsername: "admin",
      },
      vpc,
    });
 ```
