### ISSUE TITLE
Forwarding Lambda invocations fails if the invoked Lambda function does not exist in Localstack

### ISSUE THREAD

**Issue by damonmyers** [localstack/localstack#4052]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Whenever the `LAMBDA_FORWARD_URL` configuration option is set, Lambda invocations for functions that do not exist in the Localstack environment automatically fail with an error message.

## Expected behavior

Setting the `LAMBDA_FORWARD_URL` configuration option should forward Lambda invocations to the endpoint specified, regardless of whether a function with the same name exists in the Localstack environment.

## Actual behavior

Localstack first checks for a function with the name being invoked, and throws an error if the function is not found in its context.

The error message: `An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-east-1:000000000000:function:HelloWorldFunction`

# Steps to reproduce

## 1. Start Localstack using docker-compose to set some configuration options:
Create a docker-compose.yml:
``` yaml
version: "3.8"

services:
  localstack:
    container_name: "localstack-example"
    image: localstack/localstack:0.12.11
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_FORWARD_URL=http://host.docker.internal:3001
```

Then:

``` bash
docker-compose up
```

## 2. Create an AWS SAM project with a single function

See the attached [SAM-localstack-example.zip](https://github.com/localstack/localstack/files/6512139/SAM-localstack-example.zip)

## 3. Start hosting the Lambda function via SAM:

``` bash
cd <wherever-it-is-inflated>/SAM-localstack-example/
sam local start-lambda -p 3001 --docker-network localstack-bug-example_default
```

## 4. Attempt to invoke the SAM Lambda via Localstack:

``` bash
awslocal lambda invoke --function-name HelloWorldFunction --payload "{}" out.txt
```

Note that a `ResourceNotFoundException` is thrown

## 5. Create an empty function in Localstack that has the same name as the SAM function

Create a lambda_function.py:
``` python
def lambda_handler(event, context):
    return "hello from Localstack! :)"
```

Then:
```
zip lambda.zip lambda_function.py
awslocal lambda create-function --function-name HelloWorldFunction --role DummyRole --zip-file fileb://lambda.zip --runtime python3.8
```

## 6. Attempt to invoke the SAM Lambda via Localstack again:

``` bash
awslocal lambda invoke --function-name HelloWorldFunction --payload "{}" out.txt
```

Note that a `ResourceNotFoundException` is no longer thrown (but AWS SAM does return a 501 due to the log-type header being set to 'Tail')

**Comment by mgagliardo** [comment]
Hello @damonmyers, you are using it the wrong way and missing the `LAMBDA_FALLBACK_URL` parameter, from the docs:

```
LAMBDA_FALLBACK_URL: Fallback URL to use when a non-existing Lambda is invoked. Either records invocations in DynamoDB (value dynamodb://<table_name>) or forwards invocations as a POST request (value http(s)://...).
```

```
LAMBDA_FORWARD_URL: URL used to forward all Lambda invocations (useful to run Lambdas via an external service).
```

Now if you just use that argument with `LAMBDA_FALLBACK_URL=http://host.docker.internal:3001` it will work as expected, but still when you run `awslocal lambda invoke..` it will call the function but it will fail with a 404 as the function path is not clear (at least for me, also sam noob here):

DEBUG/TRACE logs:
```
Invoking arn: arn:aws:lambda:us-east-1:000000000000:function:HelloWorldFunction
content: {'Type': 'LocalService', 'Message': 'PathNotFoundException'}
Invocation result: {'Type': 'LocalService', 'Message': 'PathNotFoundException'}
```

SAM output:
```
$ sam local start-lambda -p 3001 --docker-network bridge
Starting the Local Lambda Service. You can now invoke your Lambda Functions defined in your template through the endpoint.
2021-06-04 13:18:04  * Running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
2021-06-04 13:18:45 127.0.0.1 - - [04/Jun/2021 13:18:45] "POST / HTTP/1.1" 404 -
2021-06-04 13:19:44 127.0.0.1 - - [04/Jun/2021 13:19:44] "POST / HTTP/1.1" 404 -
2021-06-04 13:19:49 127.0.0.1 - - [04/Jun/2021 13:19:49] "POST / HTTP/1.1" 404 -
2021-06-04 13:20:12 127.0.0.1 - - [04/Jun/2021 13:20:12] "POST / HTTP/1.1" 404 -
2021-06-04 13:20:19 127.0.0.1 - - [04/Jun/2021 13:20:19] "POST /HelloWorldFunction HTTP/1.1" 404 -
2021-06-04 13:20:27 127.0.0.1 - - [04/Jun/2021 13:20:27] "POST /HelloWorldFunction HTTP/1.1" 404 -
2021-06-04 13:22:26 127.0.0.1 - - [04/Jun/2021 13:22:26] "POST / HTTP/1.1" 404 -
2021-06-04 13:22:36 127.0.0.1 - - [04/Jun/2021 13:22:36] "POST / HTTP/1.1" 404 -
```

This should fix your issue without the need to add a lambda function, still the path is unclear to me.

**Comment by mgagliardo** [comment]
*I think* [this states the issue](https://github.com/aws/aws-sam-cli/issues/641#issuecomment-417537154), it should be an API path and not a lambda function per se, as `sam` already creates the lambda environment you can query with awscli. I'll dig into it a bit more and come back with a solution if possible.

**Comment by mgagliardo** [comment]
Ok, after some testing and some looking up on the AWS SAM docs/examples I have found the following setup to work:

```
version: "3.8"

services:
  localstack:
    network_mode: host
    container_name: "localstack_main"
    image: localstack/localstack:latest
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_FALLBACK_URL=http://localhost:3001
```
Please note I am using network mode `host` as I am testing this on linux, but the same should work for Mac (or you can change it back to use `host.docker.internal` which is a mac-only feature).

template.yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: localstack-example

Resources:
    HTTPAPIGateway:
        Type: AWS::Serverless::HttpApi

    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
          CodeUri: hello_world/
          Handler: app.lambda_handler
          Runtime: python3.8
          Events:
              HTTPMethodGET:
                  Type: HttpApi
                  Properties:
                      ApiId: !Ref HTTPAPIGateway
                      Path: /hello_world
                      Method: post
                      TimeoutInMillis: 3000

Outputs:
  HelloWorldFunctionArn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunction.Arn
```

You can see I just added a simple plain API in there. This will work but respond with 403, but that's on SAM's implementation. 

```
$ sam local start-api -p 3001 --docker-network host -s hello_world/
Mounting HelloWorldFunction at http://127.0.0.1:3001/hello_world [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2021-06-05 04:54:31  * Running on http://127.0.0.1:3001/ (Press CTRL+C to quit)
2021-06-05 04:54:34 127.0.0.1 - - [05/Jun/2021 04:54:34] "POST / HTTP/1.1" 403 -
2021-06-05 04:55:00 127.0.0.1 - - [05/Jun/2021 04:55:00] "POST / HTTP/1.1" 403 -
```

```
$ awslocal lambda invoke --function-name hello_world --payload "{}" out.txt
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

Note: even if you see "DEBUG" messages from localstack, the function call is made:
```
localstack_main | 2021-06-05T02:55:00:DEBUG:localstack.services.awslambda.lambda_api: Function not found: arn:aws:lambda:us-east-1:000000000000:function:hello_world
```

The rest is debugging, but this should be enough, I'll try to add some docs for an implementation like this. Cheers
