### ISSUE TITLE
Authorizer not called in API Gateway v2 websocket connection

### ISSUE THREAD

**Issue by tobias-zeptio** [localstack/localstack#4067]
# Type of request: This is a ...

[ x ] bug report
[ ] feature request

# Detailed description

I have a working websocket connection setup, with $connect and $default lambdas. Both connect and default lambda is called when I connect through wscat.

I'm then to a authorizer lambda like this:

```
awslocal apigatewayv2 create-authorizer \
    --name authorizer \
    --api-id ${API_ID} \
    --identity-source '$request.header.authorization' \
    --authorizer-type REQUEST \
    --authorizer-uri arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDA_ARN}/invocations
```
```
awslocal apigatewayv2 create-route \
    --api-id $API_ID \
    --route-key $ROUTE_KEY \
    --authorization-type CUSTOM \
    --authorizer-id $AUTHORIZER_ID \
    --target "/integrations/${INTEGRATION_ID}"
```

Looking at the defined resources with aws cli, the authorizer is connected to the route. But the authorizer lambda is never called, and the request goes through to the route directly.

## Expected behavior

Authorizer lambda is called before websocket lambda invoke.

## Actual behavior

Request goes directly to websocket lambda, without calling authorizer lambda.

# Steps to reproduce

## Command used to start LocalStack

Run in docker with the PRO trail key in the .secret file.

```
  localstack:
    container_name: localstack
    image: localstack/localstack
    networks:
      - local
    ports:
      - "4510-4519:4510-4519"
      - "4566:4566"
      - "4571:4571"
    env_file: .secret
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=dynamodb,kms,lambda,apigateway,apigatewayv2,s3,iam,sts
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=local
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=$PWD/tmp/localstack
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...
