### ISSUE TITLE
Looks like CloudFront::OriginRequestPolicy is not supported

### ISSUE THREAD

**Issue by chekalsky** [localstack/localstack#4085]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Getting exception on first deploy:

`Exception: Unable to extract attribute "PhysicalResourceId" from "CloudFront::OriginRequestPolicy" model class <class 'localstack.services.cloudformation.service_models.GenericBaseModel'>`

The same config works on real AWS.

The cloudformation config:
```
SaasFrontendDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
          DefaultCacheBehavior:
            OriginRequestPolicyId: !Ref FrontendOriginRequestPolicy
            ...
FrontendOriginRequestPolicy:
      Type: AWS::CloudFront::OriginRequestPolicy
      Properties:
        OriginRequestPolicyConfig:
          Name: FrontendOriginRequestPolicy
          QueryStringsConfig:
            QueryStringBehavior: none
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
```
