### ISSUE TITLE
Custom Authorizer function response causes exception on localstack

### ISSUE THREAD

**Issue by davidraviv** [localstack/localstack#4097]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
I'm deploying my serverless stack to localstack v0.12.7
I'm using serverless to define a custom authorizer function (`checks_registration_auth`)
The authorizer may respond with a policy to allow access, deny access, or throw an 'Unauthorized' exception.

The authorizer is invoked before the destination lambda and gets a proper event.
For all responses of the authorizer function I fail with localstack exception, the client receives HTTP 500, and the destination lambda (`checks_registration`) is never called.
...

## Expected behavior
When returning a policy to allow I expect the endpoint lambda (`checks_registration`) to be called.
When returning a policy to deny access, I expect the API Gateway to respond with HTTP 403.
When throwing an exception, I expect the API Gateway to respond with HTTP 401.
...

## Actual behavior
On all three possible responses the API Gateway responds with HTTP 500 and I get the same exception in the localstack log:
```
localstack_main | 2021-06-03T11:00:20:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://localhost:4566/restapis/klbxywnf8q/test/_user_request_/id/6032a5fe1ab8fe9b138f7bfcdd36e20881f6914d/register: 'InvocationResult' object has no attribute 'get' Traceback (most recent call last):

localstack_main | File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 117, in index

localstack_main | raise result

localstack_main | File "/opt/code/localstack/localstack/utils/bootstrap.py", line 644, in run

localstack_main | result = self.func(self.params)

localstack_main | File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run

localstack_main | return fn(*args, **kwargs)

localstack_main | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 607, in handler

localstack_main | response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 25, in modify_and_forward

localstack_main | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward

localstack_main | listener_result = listener.forward_request(method=method,

localstack_main | File "/opt/code/localstack/localstack/services/edge.py", line 105, in forward_request

localstack_main | return do_forward_request(api, method, path, data, headers, port=port)

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/edge.py", line 164, in do_forward_request

localstack_main | return do_forward_request_orig(api,method,path,data,headers,*args,**kwargs)

localstack_main | File "/opt/code/localstack/localstack/services/edge.py", line 116, in do_forward_request

localstack_main | result = do_forward_request_inmem(api, method, path, data, headers, port=port)

localstack_main | File "/opt/code/localstack/localstack/services/edge.py", line 136, in do_forward_request_inmem

localstack_main | response = modify_and_forward(method=method, path=path, data_bytes=data, headers=headers,

localstack_main | File "/opt/code/localstack/localstack/services/generic_proxy.py", line 373, in modify_and_forward

localstack_main | listener_result = listener.forward_request(method=method,

localstack_main | File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/apigateway/apigateway_extended.py", line 135, in forward_request

localstack_main | AttributeError: 'InvocationResult' object has no attribute 'get'

localstack_main |
```
...

# Steps to reproduce
1. Start localstack
2. Deploy serverless
3. call the endpoint `checks_registration` using:
3.1 Valid token
3.2 Expired token
3.3 No token

## Command used to start LocalStack
```bash
docker-compose up -d
serverless deploy
```
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
My functions part in the serverless yaml:
```yaml
functions:
  checks_registration:
    handler: checks_registration.handler
    events:
      - http:
          method: post
          path: /id/{id}/register
          authorizer: checks_registration_auth
  checks_registration_auth:
    handler: checks_registration_auth.handler
```
Allow policy sample:
```json
{
    "principalId": "arn:aws:execute-api:us-east-1:000000000000:test_api",
    "policyDocument":
    {
        "Version": "2012-10-17",
        "Statement":
        [
            {
                "Action": "execute-api:Invoke",
                "Effect": "Allow",
                "Resource": "arn:aws:execute-api:us-east-1:000000000000:test_api/*"
            }
        ]
    }
}
```
The custom authorizer function `checks_registration_auth.py`:
```python
def build_policy(resource: str, id: str, effect="Allow"):
    policy = {
        "principalId": id,
        "policyDocument": {
            "Version": "2012-10-17",
            "Statement": [{
                "Action": "execute-api:Invoke",
                "Effect": effect,
                "Resource": resource
            }]
        }
    }
    return policy

def handler(event, context):
    try:
        # Parse the event and enrich with id, may raise ValidationError
        request = EventRequest(**event)
        # Perform validation logic that may raise any exception
        validate_request(request)
        return build_policy(resource=request.methodArn, id=request.id)
    except ValidationError:
        # Unable to parse token (HTTP 401)
        raise Exception('Unauthorized')
    except AuthTokenExpired:
        # Token is expired (HTTP 403)
        return build_policy(resource=request.methodArn, id=request.id, effect="Deny")
    except Exception:
        # Any exception (HTTP 403)
        return build_policy(resource=request.methodArn, id=request.id, effect="Deny")
```
Sample event that the function was called with:
```json
{
  "type": "TOKEN",
  "authorizationToken": "Bearer d2851aaefbd44d9280707e0e186c973f",
  "methodArn": "arn:aws:execute-api:us-east-1:000000000000:test_api/*"
}
```
docker-compose file:
```yaml
version: '3.9'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-full:0.12.7
    ports:
      - "4566-4583:4566-4583"
      - "${PORT_WEB_UI-4666}:${PORT_WEB_UI-8080}"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES-iam,s3,lambda,apigateway,cloudwatch,events,cloudformation,sts,cognito,secretsmanager,dynamodb,ecr,sqs}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=8080
      - START_WEB=1
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=localstack-net
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - LS_LOG=info
      - DEBUG=0
    networks:
      - localstack-net

networks:
  localstack-net:
    external:
      name: localstack-net
```
...
