### ISSUE TITLE
Clouldformation Deploy Failing

### ISSUE THREAD

**Issue by antarr** [localstack/localstack#4114]
I'm getting an error when trying to deploy my a cloud formation stack using LocalStack. It works fine when deploying to AWS.

### error
```sh
2021-06-08T07:49:39:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "cross-account-access": string indices must be integers Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1838, in _run
    self.do_apply_changes_in_loop(changes, stack, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1889, in do_apply_changes_in_loop
    self.apply_change(change, stack, new_resources, stack_name=stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1942, in apply_change
    result = deploy_resource(resource_id, new_resources, stack_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 947, in deploy_resource
    return execute_resource_action(resource_id, resources, stack_name, ACTION_CREATE)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1051, in execute_resource_action
    result = configure_resource_via_sdk(resource_id, resources, resource_type, func, stack_name, action_name)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1177, in configure_resource_via_sdk
    run_post_create_actions(action_name, resource_id, resources, resource_type, stack_name, result)
  File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1286, in run_post_create_actions
    pol_name = policy['PolicyName']
TypeError: string indices must be integers
```

### entrypoint.sh
```
export KMS=$(awslocal kms describe-key --key-id alias/pipeline | jq -r '.KeyMetadata.Arn')
echo $KMS
awslocal cognito-idp create-user-pool --pool-name "LocalUsers"
export USER_POOL=$(awslocal cognito-idp list-user-pools --max-results 1 | jq -r '.UserPools[0].Id')
echo $USER_POOL

awslocal cloudformation deploy --stack-name "cross-account-access" \
							   --template-file ./cicd/cross-account-access.yml \
							   --capabilities CAPABILITY_IAM \
							   --region ${REGION} \
							   --parameter-overrides "CICDAccount=000000000000" \
							   				 	   	 "KMSKey=${KMS}" \
							   				 	   	 "UserPool=${USER_POOL}" \
													 "ArtifactBucket=pipeline-artifacts"
```

### failing portion of template
```yaml
  PipelineStatusReporter:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PipelineStatusReporter
      Policies:
        - !If
          - MissingPipelineStatusRole
          - !Ref AWS::NoValue
          - PolicyName: root
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - sts:AssumeRole
                  Resource:
                    - !If [
                        MissingPipelineStatusRole,
                        !Ref AWS::NoValue,
                        !Ref PipelineStatusRole,
                      ]
                - Effect: Allow
                  Action:
                    - codepipeline:PutJobFailureResult
                    - codepipeline:PutJobSuccessResult
                    - dynamodb:PutItem
                    - dynamodb:BatchWriteItem
                    - s3:*
                    - lambda:InvokeFunction
                  Resource: "*"
```

### full template
```yaml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ArtifactBucket:
    Description: S3 Bucket in CICD Account containing the artifacts from CodePipeline
    Type: String
  CICDAccount:
    Description: AWS AccountNumber for CICD
    Type: Number
  PipelineStatusRole:
    Description: The IAM role to report CodePipeline status
    Type: String
  KMSKey:
    Description: The CMK
    Type: String
  UserPool:
    Description: The User Pool ID
    Type: String

Conditions:
  MissingPipelineStatusRole: !Equals [!Ref PipelineStatusRole, ""]

Resources:
  CodePipelineCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineCrossAccountRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CICDAccount
            Action:
              - sts:AssumeRole
      Path: /

  CodePipelineCrossAccountPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CodePipelineCrossAccountPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - s3:Get*
              - s3:Put*
              - iam:PassRole
              - sts:AssumeRole
              - lambda:InvokeFunction
            Resource: "*"
          - Effect: Allow
            Action:
              - kms:*
            Resource: !Ref KMSKey
      Roles:
        - !Ref CodePipelineCrossAccountRole

  CloudFormationDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationDeployerRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  CloudFormationDeployerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudFormationDeployerPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - iam:*
              - s3:*
              - lambda:*
              - appsync:*
              - dynamodb:*
              - apigateway:*
              - states:*
              - ssm:*
              - codedeploy:*
              - events:*
              - qldb:*
              - sns:*
              - sqs:*
              - cloudwatch:*
              - route53:*
              - acm:*
              - schemas:*
              - ec2:Describe*
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub "arn:aws:s3:::${ArtifactBucket}"
              - !Sub "arn:aws:s3:::${ArtifactBucket}/*"
      Roles:
        - !Ref CloudFormationDeployerRole

  PipelineStatusReporter:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PipelineStatusReporter
      Policies:
        - !If
          - MissingPipelineStatusRole
          - !Ref AWS::NoValue
          - - PolicyName: root
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - Effect: Allow
                    Action:
                      - sts:AssumeRole
                    Resource:
                      - !If [
                          MissingPipelineStatusRole,
                          !Ref AWS::NoValue,
                          !Ref PipelineStatusRole,
                        ]
                  - Effect: Allow
                    Action:
                      - codepipeline:PutJobFailureResult
                      - codepipeline:PutJobSuccessResult
                      - dynamodb:PutItem
                      - dynamodb:BatchWriteItem
                      - s3:*
                      - lambda:InvokeFunction
                    Resource: "*" # TODO: Follow a naming convention with resources

      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  PipelineStatusRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /pipelines/roles/status
      Type: String
      Value: !If [MissingPipelineStatusRole, "", !Ref PipelineStatusRole]

  PipelineStatusReporterRoleParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /pipelines/roles/status-reporter
      Type: String
      Value: !GetAtt PipelineStatusReporter.Arn

  CognitoUserPoolParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /cognito/user/pool/id
      Type: String
      Value: !Ref UserPool
```
