### ISSUE TITLE
Missing handler for action Timestream_20181101.DescribeDatabase

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#4230]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

Unable to describe Timestream database.

```
2021-06-28T20:39:08:INFO:localstack_ext.services.timestream.timestream_api: Unable to find handler for action: Timestream_20181101.DescribeDatabase
```

# Steps to reproduce

## Command used to start LocalStack
```
version: "3.3"
services:
  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "s3,sts,iam,sqs,sns,lambda,firehose,timestream"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
awslocal timestream-write create-database --database-name ts_example
awslocal timestream-write describe-database --database-name ts_example
```

```
>>> awslocal timestream-write create-database --database-name ts_example
{
    "Database": {
        "Arn": "arn:aws:timestream:us-east-1:000000000000:database/ts_example",
        "DatabaseName": "ts_example"
    }
}
>>> awslocal timestream-write describe-database --database-name ts_example
An error occurred (InternalServiceError) when calling the DescribeDatabase operation: Error: Unable to find handler for action: Timestream_20181101.DescribeDatabase
```
