### ISSUE TITLE
bug: BucketNotFound error with image greater than localstack/localstack:0.12.8

### ISSUE THREAD

**Issue by Nasrin-Shiraly** [localstack/localstack#4254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With `image: localstack/localstack:0.12.8` if HOST_LOCAL=http://aws.localhost:4566 and in docker-compose.yml alias is set to - aws.localhost there will be no errors. With higher versions ( I tried  image: localstack/localstack:0.12.10 and latest ( 2 days ago) ) this will result in BucketNotFound error.

Note that with higher versions when I set `HOST_LOCAL=http://localhost.aws:4566` this problem will not occur. I think a longer string after the first dot ( in this example localhost in aws.localhost:4566 is causing it. ) 

### Expected Behavior

To locate the bucket successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
in docker compose file:

```yaml
  localstack:
    image: localstack/localstack:0.12.10
    container_name: someName
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      VIRTUAL_HOST: assets.SOMEDOMAIN.com
      VIRTUAL_PORT: 4566
      SERVICES: s3,sqs,lambda,sts,cloudwatch,ses,cloudformation,cloudwatchlog,eventbridge,secretsmanager, redshift
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      DEFAULT_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
      ES_HOST: ${ES_HOST_LOCAL}
      ES_PORT: ${ES_PORT_LOCAL}
      ES_AUTH: ${ES_AUTH_LOCAL}
      ES_SSL: ${ES_SSL_LOCAL}
      USE_SSL: 0
      #LAMBDA_EXECUTOR: docker-reuse
      #LAMBDA_DOCKER_NETWORK: dev_network
      SQS_ENDPOINT: ${SQS_HOST_LOCAL}
      CLOUDWATCH_ENDPOINT: ${CLOUDWATCH_ENDPOINT_LOCAL}
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      dev_network:
        aliases:
          - aws.localhost
```

there's also a `.env` file where we have:
```
SQS_HOST_LOCAL=http://aws.localhost:4566
S3_HOST_LOCAL=http://aws.localhost:4566
LAMBDA_HOST_LOCAL=http://aws.localhost:4566
SES_HOST_LOCAL=http://aws.localhost:4566
STS_ENDPOINT_LOCAL=http://aws.localhost:4566
CLOUDWATCH_ENDPOINT_LOCAL=http://aws.localhost:4566
SECRETS_ENDPOINT_LOCAL=http://aws.localhost:4566
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
inside one of the containers you can do:
`root@cec30a092077:/usr/src/app# alias ls3api='aws --endpoint-url http://aws.localhost:4566 --region us-west-2 s3api'
root@cec30a092077:/usr/src/app# ls3api list-buckets
An error occurred (NoSuchBucket) when calling the ListBuckets operation: The specified bucket does not exist`

or:

`root@cec30a092077:/usr/src/app# aws --endpoint-url http://aws.localhost:4566 --region us-west-2 s3 ls
An error occurred (NoSuchBucket) when calling the ListBuckets operation: The specified bucket does not exist`

bucket will be listed correctly with the following approaches:

- with the latest image: `root@cec30a092077:/usr/src/app# aws --endpoint-url http://localhost.aws:4566 --region us-west-2 s3 ls` ( using a smaller domain instead of a longer one)

- with the latest image: `root@cec30a092077:/usr/src/app# aws --endpoint-url http://localstack:4566 --region us-west-2 s3 ls` 

- when I revert the image to `image: localstack/localstack:0.12.8` with no other changes I see no issues with any of the above.

Inside my container with a `create_multipart_upload` I was getting `mpu = s3.create_multipart_upload(Bucket=s3bucket, Key=s3key, Metadata=s3metadata)\n', '  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 386, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n', '  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 705, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n', 'botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist\n']`

### Environment

```markdown
- OS: Ubuntu 20.04.2 LTS
- LocalStack: latest
```
