### ISSUE TITLE
question: Are APIGateway authorizers supported in free tier of localstack

### ISSUE THREAD

**Issue by LukaszTheProgrammer** [localstack/localstack#4261]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am using serverless together with serverless-localstack plugin in order to make a local environment for some of my lambda functions.
What I have so far works until I add authorizer section in the serverless.yml file.
```
service: 'apiLocal'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    excludeFiles: src/**/*.spec.js
  localstack:
    debug: true
    stages: ['local']
    endpointFile: 'localstack_endpoints.json'

provider:
  apiName: attempt-api
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

functions:
  auth:
    handler: src/functions/authorizer.handler
  createAttempt:
    handler: src/functions/report.handler
    events:
      - http:
          path: /report
          method: post
          authorizer:
            name: auth

plugins:
  - serverless-webpack
  - serverless-localstack

```

My localstack docker-compose.yml is like this:
```
version: "3.8"
services:
  localstack:
    image: localstack/localstack-full:latest
    network_mode: bridge
    environment:
      - SERVICES=s3,cloudformation,lambda,sts,apigateway,iam,secretsmanager,ssm
      - LAMBDA_EXECUTOR=docker
      - HOST_TMP_FOLDER=/tmp/localstack
      - LAMBDA_REMOTE_DOCKER=false
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - '/tmp/localstack:/tmp/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
```
When I deploy to localstack without authorizer section everything passes when I add the section then I see in the localstack the following error:

```
localstack_1  | 2021-07-05T15:45:38:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type ApiGateway::Authorizer when resolving references of resource AuthApiGatewayAuthorizer: {'Type': 'AWS::ApiGateway::Authorizer', 'LogicalResourceId': 'AuthApiGatewayAuthorizer', 'Properties': {'AuthorizerResultTtlInSeconds': 300, 'IdentitySource': 'method.request.header.Authorization', 'Name': 'auth', 'RestApiId': 'jz6wx7i3ag', 'AuthorizerUri': 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:apiLocal-local-auth/invocations', 'Type': 'TOKEN'}}
localstack_1  | 2021-07-05T15:45:38:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type ApiGateway::Authorizer when resolving references of resource AuthApiGatewayAuthorizer: {'Type': 'AWS::ApiGateway::Authorizer', 'LogicalResourceId': 'AuthApiGatewayAuthorizer', 'Properties': {'AuthorizerResultTtlInSeconds': 300, 'IdentitySource': 'method.request.header.Authorization', 'Name': 'auth', 'RestApiId': 'jz6wx7i3ag', 'AuthorizerUri': 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:apiLocal-local-auth/invocations', 'Type': 'TOKEN'}}
localstack_1  | 2021-07-05T15:45:38:WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "ApiGateway::Authorizer": {'Type': 'AWS::ApiGateway::Authorizer', 'LogicalResourceId': 'AuthApiGatewayAuthorizer', 'Properties': {'AuthorizerResultTtlInSeconds': 300, 'IdentitySource': 'method.request.header.Authorization', 'Name': 'auth', 'RestApiId': 'jz6wx7i3ag', 'AuthorizerUri': 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:apiLocal-local-auth/invocations', 'Type': 'TOKEN'}}
```

It says that ApiGateway::Authorizer is not supported. The question I have is whether it is unsupported because of the version of the localstack or my configuration ?
