### ISSUE TITLE
bug: s3 object delete does not return xml

### ISSUE THREAD

**Issue by miki725** [localstack/localstack#4324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

deleting an object from localstack s3 via node aws-sdk lib:

```typescript
const s3 = new AWS.S3(...);
const r = s3.deleteObject({
  Bucket: this.bucketName,
  Key: id,
});
r.on('httpDone', (response: any) => {
  console.log('DELETE HTTP Response', response.httpResponse.body.toString());
});
await r.promise();
```

raises and error:

```
Non-whitespace before first tag.
Line: 0
Column: 1
Char: {
```

the console log shows response from localstack as json:

```
DELETE HTTP Response {"status": "running"}
```

I also see same behavior in termshark (wireshark in cli):

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/932940/126216022-8def42ac-cf3a-4252-8196-66fc0adf319a.png">

### Expected Behavior

It should be able to delete an object from the bucket without error

### How are you starting LocalStack?

With a docker-compose file

#### run localstack with docker-compose:

```
version: "3.7"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      DATA_DIR: /tmp/localstack/data
      LOCALSTACK_API_KEY: test
      SERVICES: sqs,s3
      HOSTNAME_EXTERNAL: localstack
    ports:
      - 4566:4566
    volumes:
      - ./.localstack:/tmp/localstack
```

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker-compose up -d localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

using localstack from `aws-sdk` library in typescript/node (sample snippet above)

### Environment

```markdown
- OS: Linux
- LocalStack: latest docker image
```
