### ISSUE TITLE
question: How do I enable the web UI?

### ISSUE THREAD

**Issue by fagnercarvalho** [localstack/localstack#4360]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I created my Docker Compose like this:

```yml
version: '2.1'
services:
  localstack:
    image: localstack/localstack-full
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8050}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=secretsmanager
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

And after starting I get this output:
```
Starting localstack-test_localstack_1 ... done
Attaching to localstack-test_localstack_1
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2021-07-26 06:30:37,714 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2021-07-26 06:30:37,717 INFO supervisord started with pid 15
localstack_1  | 2021-07-26 06:30:38,720 INFO spawned: 'dashboard' with pid 21
localstack_1  | 2021-07-26 06:30:38,722 INFO spawned: 'infra' with pid 22
localstack_1  | make: *** No rule to make target 'web'.  Stop.***
localstack_1  | 2021-07-26 06:30:38,729 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2021-07-26 06:30:38,730 INFO exited: dashboard (exit status 2; not expected)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2021-07-26 06:30:40,483 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  |
localstack_1  | LocalStack version: 0.12.15
localstack_1  | LocalStack build date: 2021-07-25
localstack_1  | LocalStack build git hash: d8a5c247
localstack_1  |
localstack_1  | Starting edge router (https port 4566)...
localstack_1  | Starting mock Secrets Manager service on http port 4566 ...
localstack_1  | 2021-07-26T06:30:44:INFO:localstack.multiserver: Starting multi API server process on port 37985
localstack_1  | [2021-07-26 06:30:44 +0000] [24] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1  | 2021-07-26T06:30:44:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1  | [2021-07-26 06:30:44 +0000] [24] [INFO] Running on http://0.0.0.0:37985 (CTRL + C to quit)
localstack_1  | 2021-07-26T06:30:44:INFO:hypercorn.error: Running on http://0.0.0.0:37985 (CTRL + C to quit)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Ready.
localstack_1  | 2021-07-26T06:30:54:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 10342.83ms
```

It seems like there was an issue here:

```
localstack_1  | make: *** No rule to make target 'web'.  Stop.***
localstack_1  | 2021-07-26 06:30:38,729 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2021-07-26 06:30:38,730 INFO exited: dashboard (exit status 2; not expected)
```

Am I doing something wrong?

If I go to `localhost:8050` I get ERR_EMPTY_RESPONSE and at `http://localhost:4566/health`:

```json
{
   "services":{
      "secretsmanager":"running"
   },
   "features":{
      "persistence":"disabled",
      "initScripts":"initialized"
   }
}
```
