### ISSUE TITLE
bug: S3 Connection Timeout using python

### ISSUE THREAD

**Issue by Sarh** [localstack/localstack#4366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I am running into an issue that when running localstack 0.12.10 as a service during a gitlab job, that when I try to create a bucket I receive a TimeOut error. When I run localstack 0.12.10 locally on my development machine, the same code runs without any issue. 

When I upgraded localstack to 0.12.15 I encountered the same issue, when I downgraded to 0.12.2, the issue no longer occurred and the timeout was not experienced. I was able to test and see at which version we started experiencing that issue and it was 0.12.4. 

I’ve had to sanitize the code snippets. 

Error Log Snippet
```
self = <botocore.httpsession.URLLib3Session object at 0x7f00bda1a850>
request = <AWSPreparedRequest stream_output=False, method=PUT, url=https://localstack:4566/test-bucket, headers={'User-Agent': b...sha256;x-amz-date, Signature=3d0c8e882f87688567dee6745f1543f3c01dcee21398d803df5ad28530654dd4', 'Content-Length': '0'}>
    def send(self, request):
        try:
            proxy_url = self._proxy_config.proxy_url_for(request.url)
            manager = self._get_connection_manager(request.url, proxy_url)
            conn = manager.connection_from_url(request.url)
            self._setup_ssl_cert(conn, request.url, self._verify)
    
            request_target = self._get_request_target(request.url, proxy_url)
            urllib_response = conn.urlopen(
                method=request.method,
                url=request_target,
                body=request.body,
                headers=request.headers,
                retries=Retry(False),
                assert_same_host=False,
                preload_content=False,
                decode_content=False,
                chunked=self._chunked(request.headers),
            )
    
            http_response = botocore.awsrequest.AWSResponse(
                request.url,
                urllib_response.status,
                urllib_response.headers,
                urllib_response,
            )
    
            if not request.stream_output:
                # Cause the raw stream to be exhausted immediately. We do it
                # this way instead of using preload_content because
                # preload_content will never buffer chunked responses
                http_response.content
    
            return http_response
        except URLLib3SSLError as e:
            raise SSLError(endpoint_url=request.url, error=e)
        except (NewConnectionError, socket.gaierror) as e:
            raise EndpointConnectionError(endpoint_url=request.url, error=e)
        except ProxyError as e:
            raise ProxyConnectionError(proxy_url=proxy_url, error=e)
        except URLLib3ConnectTimeoutError as e:
            raise ConnectTimeoutError(endpoint_url=request.url, error=e)
        except URLLib3ReadTimeoutError as e:
>           raise ReadTimeoutError(endpoint_url=request.url, error=e)
E           botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://localstack:4566/test-bucket"
```

Additional Logs: 
[localstack_failed_output.txt](https://github.com/localstack/localstack/files/6879196/localstack_failed_output.txt)

### Expected Behavior

 Connection does not timeout, able to create buckets and add objects to those buckets

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    As a gitlab service

*gitlab-ci.yml*
 ```yaml 
variables:    
  SERVICES: s3

unit:
  variables:
    LOCALSTACK_HOSTNAME: "localstack"
    no_proxy: localstack,localhost
  services:
    - name: localstack/localstack:0.12.15
      alias: localstack
  script:    
    - export AWS_PROFILE=localstack    
    - pytest .   
 parallel: 2
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   1. Create a test.py file
 ```python
def test_here_is_my_test():
    environment = os.getenv("LOCALSTACK_HOSTNAME", "NA")
    env_var = os.getenv("ENV_VAR", "NA")

    environment = os.getenv("LOCALSTACK_HOSTNAME", "NA")
    S3 = boto3.resource('s3', endpoint_url='https://' + environment + ':4566', verify=False)

    S3.Bucket('test-bucket').create()

 ```

 2. Run the test via gitlab pipeline

### Environment

```markdown
- OS: amazonlinux:2.0.20200722.0
- LocalStack: 0.12.4 - 0.12.15
- Python 3.7.9
```

**Comment by pinzon** [comment]
could it be the usage of SSL? have you tried with just http?

**Comment by Sarh** [comment]
Hi @pinzon  I have just tried it with http, same code as above but http instead of https. Same error, I have attached a file w/ the readout if you'd like to review it. 
[localstack_http_timeout.txt](https://github.com/localstack/localstack/files/6917804/localstack_http_timeout.txt)

**Comment by pinzon** [comment]
Hi @Sarh it has been a long time since I used gitlab ci but after several tries I managed to have a passing [job]( https://gitlab.com/cristopherpinzon/issue-4366/-/pipelines/349370687) .

it looks to me it's config problem. Here are the files I wrote and this is the complete [project](https://gitlab.com/cristopherpinzon/issue-4366).

```python
import os
import boto3
from botocore import endpoint

def test_here_is_my_test():
   environment = os.getenv("LOCALSTACK_HOSTNAME", "localhost")
   endpoint = 'http://' + environment + ':4566'

   client = boto3.client('s3',aws_access_key_id='test',aws_secret_access_key='test', endpoint_url=endpoint )

   client.create_bucket(Bucket='test')
```
```yml

image: python:latest

variables:    
 SERVICES: s3
 LOCALSTACK_HOSTNAME: "localstack"

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install boto3 boto pytest

services:
   - name: localstack/localstack:0.12.15
     alias: localstack

run:
  script:
   - pytest test.py

```
