### ISSUE TITLE
bug: "Unable to get Cognito identity"

### ISSUE THREAD

**Issue by benwainwright** [localstack/localstack#4382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to call an API Gateway protected by a cognito authoriser, using curl and the correct access token, the connection hangs for a while (possibly 20-40 seconds?), then fails with the following log message in the debug log

```
localstack_main  | 2021-07-28 23:04:55,876:API: 127.0.0.1 - - [28/Jul/2021 23:04:55] "GET /restapis HTTP/1.1" 200 -
localstack_main  | 2021-07-28T23:06:49:DEBUG:localstack_ext.services.apigateway.authorizers: Authorization failed: Unable to get Cognito identity (408): b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>408 Request Timeout</title>\n<h1>Request Timeout</h1>\n<p>The server closed the network connection because the browser didn&#x27;t finish the request within the specified time.</p>\n' - Traceback (most recent call last):
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/authorizers.py", line 152, in check_request_authorization
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/authorizers.py", line 31, in authorize
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/authorizers.py", line 37, in _lookup_user
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/authorizers.py", line 48, in _get_identity
localstack_main  |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/authorizers.py", line 62, in _get_identity_from_identity_header
localstack_main  | Exception: Unable to get Cognito identity (408): b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>408 Request Timeout</title>\n<h1>Request Timeout</h1>\n<p>The server closed the network connection because the browser didn&#x27;t finish the request within the specified time.</p>\n'
```

### Expected Behavior

Calls lambda and returns response

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Call to local API Gateway protected by a Cognito User Pool results in the following logs in the terminal.

* bootstrap cdklocal
* Create a CDK stap with a lambda, attached to a rest api that is protected by a cognito user pool authoriser
* Call awslocal apigateway get-rest-apis to get the api id
* Seed cognito by creating a user and confirming, then use admininitiateauth to get the token
* curl `curl -vvv --header "Authorization: <token>" --header 'Content-Type: application/json' --data '<some data>' http://localhost:4566/restapis/<apiId>/prod/_user_request_/`

### Environment

```markdown
- OS: MacOS 11.3
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @benwainwright . Looks like we're hitting a timeout on one of the APIs here. Can you please share your full `docker-compose.yml` config file? We'll be happy to look into it in more detail. Thanks!

**Comment by benwainwright** [comment]
Sure: 

```
version: "2.1"

services:
  localstack:
    container_name: tnm-admin-localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=appsync,route53,cloudformation,cloudfront,s3,dynamodb,lambda,iam
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 ```
