### ISSUE TITLE
bug: High CPU usage when long polling for many SQS queues

### ISSUE THREAD

**Issue by alechirsch** [localstack/localstack#4386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have 12 SQS queues set up for long polling (ReceiveMessageWaitTimeSeconds=20), which is fine and the long polling works. However when I have a consumer for each of those queues running, I see localstack CPU shooting up to 100% until I stop the consumers. I am using `docker stats` to see this info. All of my consumer containers are always hovering around 0-1% CPU.

CONTAINER ID   NAME                CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
81de5c5bf519   localstack          101.52%   192.9MiB / 3.844GiB   4.90%     6.64MB / 6.54MB   95MB / 0B         59

This issue has been causing my laptop to freeze up constantly when using localstack for this purpose.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8081:8080"
    environment:
      - SERVICES=sqs,sns,kms,s3,secretsmanager,events
      - DEFAULT_REGION=us-west-2
      - HOST_TMP_FOLDER=/tmp/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-scripts:/docker-entrypoint-initaws.d
      - ./config/aws:/root/.aws
      - ./config/kms/seed.yaml:/init/seed.yaml
      - ./kms-data:/tmp/local-kms
```

Init scripts with a bunch of queue creation and various other services (s3, kms, etc..)
```
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name queue1 --attributes VisibilityTimeout=14400,DelaySeconds=0,ReceiveMessageWaitTimeSeconds=20
```

Create a dozen or so queues with long polling enabled (ReceiveMessageWaitTimeSeconds=20), and run a consumer for each one.

### Environment

```markdown
- OS: MacOS 10.14.6
- LocalStack: latest
- Processor 2.7 GHz Intel i7 quadcore
- Memory: 16GB
```
