### ISSUE TITLE
bug: [PRO] Localstack QLDB returns 'null' when  selecting indexes

### ISSUE THREAD

**Issue by richardkabiling** [localstack/localstack#4399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### via QldbDriver
```
var indexQueryResult = txn.execute("""
            SELECT VALUE indexes
            FROM information_schema.user_tables info, info.indexes indexes
            i
            """, mapper.writeValueAsIonValue(table));
        return StreamSupport.stream(indexQueryResult.spliterator(), false)
            .map(v -> (IonStruct) v)
            .map(s -> s.get("expr").toString())
            .collect(Collectors.toSet());
```

yields the following Exception

```
java.lang.ClassCastException: class com.amazon.ion.impl.lite.IonNullLite cannot be cast to class com.amazon.ion.IonStruct (com.amazon.ion.impl.lite.IonNullLite and com.amazon.ion.IonStruct are in unnamed module of loader 'app')
```

#### via QLDB Shell

```
SELECT VALUE indexes FROM information_schema.user_tables info, info.indexes indexes WHERE info.name = 'A'; 
```

returns the following:

```
INFO: 
null
INFO: (1.2679s)
```

### Expected Behavior

Index structs will be returned as documented here:
https://docs.aws.amazon.com/qldb/latest/developerguide/working.manage-indexes.html

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

Using the following compose

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      SERVICES: "qldb"
      START_WEB: "0"
      DEFAULT_REGION: "eu-west-1"
      LOCALSTACK_API_KEY: "..."
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./init.d:/docker-entrypoint-initaws.d"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    SELECT VALUE indexes FROM information_schema.user_tables info, info.indexes indexes WHERE info.name = 'A';

qldbshell and QLDB driver both fails

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: 0.12.16 (latest)
- Language: Java
- QldbDriver: 2.3.1
```
