### ISSUE TITLE
bug: [PRO] Delete ledger fails even with --no-deletion-protection on localstack QLDB

### ISSUE THREAD

**Issue by richardkabiling** [localstack/localstack#4400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deleting a ledger without deletion protection on localstack QLDB, consistently fails with 405 both on SDK2 and aws cli

### Expected Behavior

Deletion proceeds

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

using the following compose file

```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      SERVICES: "qldb"
      START_WEB: "0"
      DEFAULT_REGION: "eu-west-1"
      LOCALSTACK_API_KEY: "..."
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./init.d:/docker-entrypoint-initaws.d"
```

##### via AWS SDK 2
```
client.createLedger(CreateLedgerRequest.builder()
        .name(props.getLedger())
        .permissionsMode("ALLOW_ALL")
        .deletionProtection(false)
        .build());
awaitState("active")
client.deleteLedger(DeleteLedgerRequest.builder()
          .name(props.getLedger())
          .build());
```

this throws Exception with status 405

##### via CLI
```
$ aws qldb create-ledger --name=point-wallet2 --no-deletion-protection --permissions-mode=STANDARD --profile=local --region=eu-west-1 --endpoint-url=http://localhost:4566
{
    "Name": "point-wallet2",
    "Arn": "arn:aws:qldb:eu-west-1:000000000000:ledger/point-wallet2",
    "State": "ACTIVE",
    "CreationDateTime": 1627865375.48389,
    "PermissionsMode": "STANDARD",
    "DeletionProtection": false
}
$ aws qldb delete-ledger --name=point-wallet2 --profile=local --region=eu-west-1 --endpoint-url=http://localhost:4566
An error occurred (405) when calling the DeleteLedger operation: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: 0.12.16 (latest)
- Language: Java
- AWS SDK (QLDB): 2.17.2
```
