### ISSUE TITLE
bug: SecretsManager 'GenerateSecretString' seems to create an invalid secret

### ISSUE THREAD

**Issue by redterror** [localstack/localstack#4401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using secretsmanager + the `GenerateSecretString` parameter via cloudformation, the secret gets created but the value is not available via `awslocal secretsmanager get-secret-value`.  The error thrown is:

```
An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret value for staging label: AWSCURRENT
```

### Expected Behavior

I expect to be able to retrieve the secret's value.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Cloudformation template:

```
AWSTemplateFormatVersion: 2010-09-09

Description: >
  Localstack bugged secret demo

Resources:
  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Description: Aurora Password
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${Username}"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        IncludeSpace: false
        ExcludePunctuation: true

Outputs:
  Secret:
    Description: Server Secret Store
    Value: !Ref Secret
```

We are applying it via an internal tool.

Then:

```
$ awslocal secretsmanager list-secrets
{
    [
        {
            "ARN": "arn:aws:secretsmanager:us-east-1:000000000000:secret:secrets-bug-demo-None-6f1e3dd9-ntJWsx",
            "Name": "secrets-bug-demo-None-6f1e3dd9",
            "Description": "Aurora Password",
            "KmsKeyId": "",
            "RotationEnabled": false,
            "RotationLambdaARN": "",
            "RotationRules": {
                "AutomaticallyAfterDays": 0
            },
            "Tags": [],
            "SecretVersionsToStages": {
                "dcedc041-c277-4efd-83f5-b4ea62c06ae8": [
                    "AWSCURRENT"
                ]
            }
        }
    ]
}

$ awslocal secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:000000000000:secret:secrets-bug-demo-None-6f1e3dd9

An error occurred (ResourceNotFoundException) when calling the GetSecretValue operation: Secrets Manager can't find the specified secret value for staging label: AWSCURRENT
```

### Environment

```markdown
- OS: Ubuntu 18.04
- LocalStack: latest, docker image id: `565dfd1756e5`
- docker-compose.yml:


version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY
      - DEBUG=1
      - LAMBDA_REMOTE_DOCKER=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
```


### Anything else?

Creating a secret and instead using `SecretValue` (e.g. to make a fixed / static secret) works as expected.
