### ISSUE TITLE
bug: [PRO] QLDB does not drop tables when running DROP TABLE from QldbDriver

### ISSUE THREAD

**Issue by richardkabiling** [localstack/localstack#4402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

QLDB does not drop tables when running DROP TABLE from AWS SDK.

### Expected Behavior

QLDB drops the tables

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

docker-compose.yml
```
version: '2.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "443:443"
    environment:
      SERVICES: "qldb"
      START_WEB: "0"
      DEFAULT_REGION: "eu-west-1"
      LOCALSTACK_API_KEY: "..."
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./init.d:/docker-entrypoint-initaws.d"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

The following test fails
```
    @Test
    void testDropTable() {
      driver.execute(txn -> {
        txn.execute("CREATE TABLE A");
      });

      driver.execute(txn -> {
        txn.execute("DROP TABLE A");
      });

      var tableNames = StreamSupport.stream(driver.getTableNames().spliterator(), false)
          .collect(Collectors.toSet());

      assertThat(tableNames).isEmpty();
    }
```
```
java.lang.AssertionError: 
Expecting empty but was: ["A"]
```

### Environment

```markdown
- OS: MacOS Big Sur
- LocalStack: latest (not yet tagged -- 0.12.17 maybe?)
- Language: Java
- QldbDriver: 2.3.1
```
