### ISSUE TITLE
Custom SSL domain doesnt work

### ISSUE THREAD

**Issue by therepo90** [localstack/localstack#4412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im following example on github page to use custom domain(with docker compose up)
When running docker im getting

WARNING:localstack.utils.server.http2_server: Unable to create SSL context. Cert files exist: /tmp/localstack/server.test.pem.crt True (1199B), /tmp/localstack/server.test.pem.key True (1670B)

### Expected Behavior

Bug not present

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      - "127.0.0.1:${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${PWD}/ls_tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

TMPDIR=/private$TMPDIR docker-compose up

### Environment

```markdown
- OS: mac
- LocalStack: latest
```
