### ISSUE TITLE
bug: SAM or CloudFormation deploy never finishes

### ISSUE THREAD

**Issue by danw-mpl** [localstack/localstack#4464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `samlocal deploy {...}` or `aws cloudformation deploy {...}`, the operation seems to just 'stop' or 'hang' with no obvious reason why.

I have a feeling it's to do with a bad SAM/CloudFormation template but the problem is there's no clear indication of the cause even with debug enabled.

The localstack debug output ends up just looking like this which I assume is the `samlocal deploy` trying to get the status.

```
localstack_main    | 2021-08-18 10:14:58,996:API: 127.0.0.1 - - [18/Aug/2021 10:14:58] "POST / HTTP/1.1" 200 -
localstack_main    | 2021-08-18 10:14:59,190:API: 127.0.0.1 - - [18/Aug/2021 10:14:59] "POST / HTTP/1.1" 200 -
localstack_main    | 2021-08-18 10:14:59,214:API: 127.0.0.1 - - [18/Aug/2021 10:14:59] "POST / HTTP/1.1" 200 -
localstack_main    | 2021-08-18 10:14:59,256:API: 127.0.0.1 - - [18/Aug/2021 10:14:59] "POST / HTTP/1.1" 200 -
localstack_main    | 2021-08-18 10:15:29,289:API: 127.0.0.1 - - [18/Aug/2021 10:15:29] "POST / HTTP/1.1" 200 -
```

The `samlocal deploy` output at this point will generally look like this:

```
ResourceStatus
-----------------
UPDATE_COMPLETE
UPDATE_COMPLETE
...etc.
```

And sometimes there can be a CREATE_FAILED for the stack LogicalResourceId but again, no indication in the debug logs.

I should note deployment of resources normally goes smoothly.

### Expected Behavior

There should be at least some kind of suggestion as to what the problem is.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up
    (using slightly modified template from this repo)

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
echo "creating s3 build bucket"
awslocal s3 mb s3://$CF_S3_BUCKET

samlocal build --template "dev-env/infrastructure.local.yaml" --use-container --build-dir "/tmp/.aws-sam"

samlocal package \
   --template-file "/tmp/.aws-sam/template.yaml" \
   --s3-bucket $CF_S3_BUCKET \
   --output-template-file "/tmp/.aws-sam/infrastructure.local-packaged.yaml"

samlocal --debug deploy \
    --no-fail-on-empty-changeset \
    --stack-name XXXXXXXXXXXX-$ENV_TYPE \
    --template "/tmp/.aws-sam/infrastructure.local-packaged.yaml" \
    --parameter-overrides \
        {...}
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
```

#### Example CloudFormation that seems to cause this

_Note that I've experienced the same problem just modifying existing resources.

```yaml
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.8
      CodeUri: ./dev-env/sample_lambda
```

### Environment

```markdown
- OS: Ubuntu 20.04 on WSL2
- LocalStack: 0.12.16
```

**Comment by danw-mpl** [comment]
I just happened to run again with no code changes and I got this back:

`Error: Failed to create/update the stack: XXXXXXXXXXX, Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state: Matched expected service error code: ValidationError`.

This is what I'd expect to see immediately but it's clearly random in it's response time.

**Comment by danw-mpl** [comment]
Just ran again with no code changes and I immediately got:

`Successfully created/updated stack - XXXXXXXXXXXXXX in None`

Ran the same deploy again right after and it has hung.

**Comment by danw-mpl** [comment]
Example debug response from localstack:

```
localstack_main    | 2021-08-18T11:04:07:DEBUG:localstack.services.edge: OUT(cloudformation): "POST /" - status: 200 - response headers: {'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '1406', 'Access-Control-Allow-Origin': '*', 'Server': 'Werkzeug/2.0.1 Python/3.7.10', 'Date': 'Wed, 18 Aug 2021 11:04:07 GMT', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'x-amz-version-id'} - response:
```

```xml
<DescribeStacksResult>
	<Stacks>
		<member>
			<StackName>XXXXXXXXXXX</StackName>
			<Description>Created by SAM CLI at 2021-08-18T11:00:18.185254 UTC</Description>
			<StackId>arn:aws:cloudformation:us-east-1:000000000000:stack/XXXXXXXXXXXX/28833e29</StackId>
			<StackStatus>CREATE_COMPLETE</StackStatus>
			<CreationTime>2021-08-18T11:00:18.393Z</CreationTime>
			<StackStatusReason>Deployment succeeded</StackStatusReason>
			<ChangeSetId>arn:aws:cloudformation:us-east-1:000000000000:changeSet/samcli-deploy1629284524/0cba5ab5</ChangeSetId>
			<Tags />
			<Outputs />
			<Parameters>
				<member>
					<ParameterKey>MetadataTableName</ParameterKey>
					<ParameterValue>XXXXXXXX-metadata</ParameterValue>
				</member>
				<member>
					<ParameterKey>IndexTableName</ParameterKey>
					<ParameterValue>XXXXXXXX-index</ParameterValue>
				</member>
				<member>
					<ParameterKey>QueryJobTableName</ParameterKey>
					<ParameterValue>XXXXXX_query_job_table_name</ParameterValue>
				</member>
				<member>
					<ParameterKey>MetaflowClusterName</ParameterKey>
					<ParameterValue>XXXXXXX-metaflow-cluster</ParameterValue>
				</member>
				<member>
					<ParameterKey>EnvType</ParameterKey>
					<ParameterValue>dev</ParameterValue>
				</member>
				<member>
					<ParameterKey>DataBucket</ParameterKey>
					<ParameterValue>athena_bucket</ParameterValue>
				</member>
			</Parameters>
			<Capabilities />
		</member>
	</Stacks>
</DescribeStacksResult>\n        undefined</DescribeStacksResponse>
```

**Comment by hrmstockdale** [comment]
Hi, 

So I am experiencing what I believe is the same bug and somewhat regretfully will be making a similar ticket (I am experiencing it using some gitlab features when using a localstack version > 0.12.11 (which is when I _believe_ the python version of the image was changed to 3.7?)

Could you share your docker-compose.yml so I can understand your issue a bit more

**Comment by danw-mpl** [comment]
Sure thing:

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.17
    networks:
      - default
      - localstack
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 # Required to prevent 403 from Commandeer
      - DISABLE_EVENTS=1 # Disable Localstack telemetry
      - DATA_DIR=/tmp/localstack/data
      - LS_LOG=info
    volumes:
      - "localstack_data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  setup-resources:
    image: python:3.8.11-slim-buster
    container_name: localstack_setup_resources
    environment:
      - LOCALSTACK_HOST=localstack # For awslocal CLI
      - LOCALSTACK_HOSTNAME=localstack # For samlocal CLI
      - SAM_CLI_TELEMETRY=0
    networks:
      - localstack
    volumes:
      - .:/src
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /src
    entrypoint: ["dev-env/setup_resources.sh"]
    depends_on:
      - localstack

networks:
  localstack:
    driver: bridge
    name: localstack

volumes:
  localstack_data:
```

Note that `setup-resources` just runs the SAM cli in the `setup_resources.sh` entrypoint.

**However, I can replicate this without Docker, using `localstack start`.**.  A different issue but the hang is reproducible: https://github.com/localstack/localstack/issues/4543
