### ISSUE TITLE
bug: CloudFormation fails to create type AWS::Events::Connection

### ISSUE THREAD

**Issue by Leo-Mepham** [localstack/localstack#4467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying a CloudFormation template with a single item, a resource of type AWS::Events::Connection fails.

This template succeeds when run in AWS.

Looking at the Docker window, I see the following:

WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type Events::Connection when resolving references of resource ApiDestinationConnection: {'Type': 'AWS::Events::Connection', 'Properties': {'AuthorizationType': 'API_KEY', 'AuthParameters': {'ApiKeyAuthParameters': {'ApiKeyName': 'no_auth_needed', 'ApiKeyValue': 'no_auth_needed'}}}, 'LogicalResourceId': 'ApiDestinationConnection', 'PhysicalResourceId': None}

WARNING:localstack.utils.cloudformation.template_deployer: Unable to deploy resource type "Events::Connection": {'Type': 'AWS::Events::Connection', 'Properties': {'AuthorizationType': 'API_KEY', 'AuthParameters': {'ApiKeyAuthParameters': {'ApiKeyName': 'no_auth_needed', 'ApiKeyValue': 'no_auth_needed'}}}, 'LogicalResourceId': 'ApiDestinationConnection', 'PhysicalResourceId': None}

### Expected Behavior

The resource of type AWS::Events::Connection should be created

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up:

```
version: '2.1'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566-4620:4566-4620"
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

CloudFormation.yml file:

```
Resources:
  ApiDestinationConnection:
    Type: AWS::Events::Connection
    Properties: 
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: no_auth_needed
          ApiKeyValue: no_auth_needed

Outputs:
  ConnectionArn:
    Description: The Arn for the Connection
    Value: !GetAtt ApiDestinationConnection.Arn
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws --endpoint-url=http://localhost:4566 cloudformation create-stack --template-body file://cloudformation.yml --stack-name localevents

aws --endpoint-url=http://localhost:4566 cloudformation describe-stacks

### Environment

```markdown
- OS: Windows 10 Professional
- LocalStack: latest
```
