### ISSUE TITLE
bug: Incorrect content-type for files from an s3 website bucket

### ISSUE THREAD

**Issue by qubyte** [localstack/localstack#4487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a website request to an s3 bucket, the content-type response header is incorrent.

### Expected Behavior

The `content-type` header in the response from the s3 website endpoint for an object should be the same as the `ContentType` of the object.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack

A reduced compose file:

```yaml
version: "3.9"
services:
  s3:
    image: localstack/localstack:latest
    ports:
      - "4566-4583:4566-4583"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - S3_SKIP_SIGNATURE_VALIDATION=0
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands

```shell
# bucket setup
awslocal s3api create-bucket --bucket public
awslocal s3api put-bucket-acl --bucket public --acl public-read
awslocal s3 website s3://public --index-document index.html

# sample object
echo  "'use strict;'" > script.js
awslocal s3api put-object --bucket public --body script.js --content-type "application/javascript; charset=utf-8" --key script.js
```

Confirm the metadata of the object has the expected `ContentType` metadata:

```shell
awslocal s3api head-object --bucket public --key script.js
```

The result will look like:

```json
{
    "LastModified": "Wed, 25 Aug 2021 13:36:20 GMT",
    "ContentLength": 14,
    "ETag": "\"63a55f759bd133b92f61ae079fd2cc73\"",
    "ContentType": "application/javascript; charset=utf-8",
    "Metadata": {}
}
```

A curl (either on the host machine or in the container) to the website endpoint for the object results in an incorrect content-type header (`text/html; charset=utf-8`):

```shell
curl --resolve public.s3-website.localhost.localstack.cloud:4566:127.0.0.1 public.s3-website.localhost.localstack.cloud:4566/script.js -v
```

The output:

```
* Added public.s3-website.localhost.localstack.cloud:4566:127.0.0.1 to DNS cache
* Hostname public.s3-website.localhost.localstack.cloud was found in DNS cache
*   Trying 127.0.0.1:4566...
* TCP_NODELAY set
* Connected to public.s3-website.localhost.localstack.cloud (127.0.0.1) port 4566 (#0)
> GET /script.js HTTP/1.1
> Host: public.s3-website.localhost.localstack.cloud:4566
> User-Agent: curl/7.67.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 
< content-type: text/html; charset=utf-8
< content-length: 14
< last-modified: Wed, 25 Aug 2021 13:36:43 GMT
< x-amz-request-id: 2E0649A71F21ACAC
< x-amz-id-2: MzRISOwyjmnup2E0649A71F21ACAC7/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp
< accept-ranges: bytes
< content-language: en-US
< access-control-allow-origin: *
< access-control-allow-methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
< access-control-allow-headers: authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request
< access-control-expose-headers: x-amz-version-id
< connection: close
< date: Wed, 25 Aug 2021 13:36:43 GMT
< server: hypercorn-h11
< 
'use strict;'
* Closing connection 0
```

### Environment

```markdown
- Host OS: macos big-sur 11.5.1
- LocalStack: latest
```
