### ISSUE TITLE
bug: Unable to seed KMS after upgrading, downgrading to 0.12.16 works

### ISSUE THREAD

**Issue by alechirsch** [localstack/localstack#4492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading to latest localstack, this is the output of list-aliases command
```
> aws --endpoint-url=http://localhost:4566 kms list-aliases
{
    "Aliases": [
        {
            "AliasName": "alias/aws/ebs",
            "AliasArn": "arn:aws:kms:us-west-2:012345678912:alias/aws/ebs"
        },
        {
            "AliasName": "alias/aws/s3",
            "AliasArn": "arn:aws:kms:us-west-2:012345678912:alias/aws/s3"
        },
        {
            "AliasName": "alias/aws/redshift",
            "AliasArn": "arn:aws:kms:us-west-2:012345678912:alias/aws/redshift"
        },
        {
            "AliasName": "alias/aws/rds",
            "AliasArn": "arn:aws:kms:us-west-2:012345678912:alias/aws/rds"
        }
    ]
}
```

### Expected Behavior

After downgrading to 0.12.16, this is the output
```
> aws --endpoint-url=http://localhost:4566 kms list-aliases
{
    "Aliases": [
        {
            "AliasName": "alias/development/service-one",
            "AliasArn": "arn:aws:kms:us-west-2:000000000000:alias/development/service-one",
            "TargetKeyId": "2e0364ad-cbc9-4950-b7cd-21dc084bd763"
        },
        {
            "AliasName": "alias/development/service-two",
            "AliasArn": "arn:aws:kms:us-west-2:000000000000:alias/development/service-two",
            "TargetKeyId": "2e0364ad-cbc9-4950-b7cd-21dc084bd763"
        }
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
 
Using docker-compose.yml and this seed file in a volume
```
Keys:
  Symmetric:
    Aes:
      - Metadata:
          KeyId: 2e0364ad-cbc9-4950-b7cd-21dc084bd763
        BackingKeys:
          - <our key>
Aliases:
  - AliasName: alias/development/service-one
    TargetKeyId: 2e0364ad-cbc9-4950-b7cd-21dc084bd763
  - AliasName: alias/development/service-two
    TargetKeyId: 2e0364ad-cbc9-4950-b7cd-21dc084bd763
```

### Environment

```markdown
- OS: Mac (but using docker)
- LocalStack: 0.12.17 and latest
```
