### ISSUE TITLE
bug: CloudFormation stack creation always CREATE_FAILED

### ISSUE THREAD

**Issue by wantdrink** [localstack/localstack#4528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there,

I'm trying to create a stack but always get CREATE_FAILED result.
I deleted most of the resource in stack template to make it simple:

```
Metadata: 
  License: Apache-2.0
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t3.small"
      ImageId: "ami-c6f321bf"

```

The stack result:
```
{
    "StackSummaries": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/EIP_With_Association.yaml1/11e09c7e",
            "StackName": "EIP_With_Association.yaml1",
            "CreationTime": "2021-09-02T06:32:39.457Z",
            "StackStatus": "CREATE_FAILED",
            "StackStatusReason": "Deployment failed"
        }
    ]
}
```

The services in docker-compose.yml is :
```
    environment:
      - SERVICES=serverless,sqs,sns,cloudformation,ec2,s3,ebs,lambda,sts,iam,apigateway,cloudwatch

```
Image info:

> image localstack/localstack            latest                    8181ed740500        8 days ago

Thanks a lot.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

create stack with boto3

### Environment

```markdown
- OS: CentOS 7.7
- LocalStack: latest (image localstack/localstack            latest                    8181ed740500        8 days ago)
```
