### ISSUE TITLE
Docker-compose dashboard start_web not working - in localstack-full image

### ISSUE THREAD

**Issue by insomenia-seongjun** [localstack/localstack#4535]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Access to localhost:8080 to turn on the dashboard has no response.

I am using the localstack-full image,

I've even set up all the env.

```
version: "3"

services:
  localstack:
    image: localstack/localstack-full:latest
    container_name: localstack
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,cognito,amplify,lambda,iam,cloudwatch,cloudformation,sts
      - DEFAULT_REGION=ap-northeast-2
      - HOSTNAME=localhost
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - START_WEB=1

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
