### ISSUE TITLE
question: Does Lambda Function with correct IAM Role require endpoint to be specified? [InvalidAccessKeyId]

### ISSUE THREAD

**Issue by paritoshcm** [localstack/localstack#4536]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I'm working on a simple Express/TS application that I'm hoping to deploy using [`sam`](https://aws.amazon.com/serverless/sam/), being able to use the same setup to test locally by deploying to localstack, and (once everything looks good) deploy actually to AWS.

The application is intended to be a Lambda function, accessed through an API Gateway rest API, that will interact with S3.

But, when the application tries to access S3, I'm seeing an `InvalidAccessKeyId` error:
```
2021-09-03T07:42:52.446000+00:00 2021/09/03/[LATEST]60277125 2021-09-03T07:42:50.773Z	b07969c3-feb2-14cd-14ae-fddb338a3d16	ERROR	InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
2021-09-03T07:42:52.447000+00:00 2021/09/03/[LATEST]60277125     at deserializeAws_restXmlListBucketsCommandError (/var/task/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:7060:41)
2021-09-03T07:42:52.447000+00:00 2021/09/03/[LATEST]60277125     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-09-03T07:42:52.448000+00:00 2021/09/03/[LATEST]60277125     at async /var/task/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
2021-09-03T07:42:52.449000+00:00 2021/09/03/[LATEST]60277125     at async /var/task/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:11:20
2021-09-03T07:42:52.450000+00:00 2021/09/03/[LATEST]60277125     at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
2021-09-03T07:42:52.451000+00:00 2021/09/03/[LATEST]60277125     at async /var/task/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22

```

Looking at a few issues, I saw that the endpoint needs to be configured in the [`S3Client`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/classes/s3client.html) for it to work. But, I assumed that with the correct IAM Role assigned to the Lambda, it would be able to access S3.

Because, otherwise, it's difficult to use the same code to both test locally and actually deploy. I'd have to use a hacky way of checking some environment variable to decide whether to use the endpoint or not, which I don't want to.

The question is, is my assumption wrong? Will deploying a Lambda to localstack with the correct IAM role still not be able to access S3 as it would be (and is) on AWS?

Here is my `docker-compose.yml`:
```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=serverless
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "./setup:/docker-entrypoint-initaws.d"
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
I saw quite a few issues pointing out that the latest image should be used, but sadly it did not resolve this issue for me.

Also, here's a part of sam `template.yaml`:
```yaml
MyBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: !Ref MyBucketName # From a Parameter

MyRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Policies:
      - PolicyName: MyS3Buckets
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:CreateBucket
              Resource: '*'
      - PolicyName: MyS3Objects
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${MyBucket}/*

MyApi:
  Type: AWS::Serverless::Api
  Properties:
    Name: !Sub ${AWS::StackName}-api
    StageName: !Ref StageName # From a Parameter

MyFunction:
  Type: AWS::Serverless::Function
  Metadata:
    BuildMethod: makefile
  Properties:
    Handler: lambda.handler
    Description: My humble application.
    Runtime: nodejs14.x
    Environment:
      Variables:
        AWS_S3_BUCKET: !Ref MyBucketName
    Events:
      BaseEvent:
        Type: Api
        Properties:
          RestApiId: !Ref MyApi
          Path: /
          Method: GET # Because ANY does NOT work on localstack :(
      GetEvent:
        Type: Api
        Properties:
          RestApiId: !Ref MyApi
          Path: /{proxy+}
          Method: GET # Because ANY does NOT work on localstack :(
      PostEvent:
        Type: Api
        Properties:
          RestApiId: !Ref MyApi
          Path: /{proxy+}
          Method: POST # Because ANY does NOT work on localstack :(
    Role: !GetAtt MyRole.Arn
```
Ignoring the fact that `Method: ANY` does not work for the events (though it should from [this issue](https://github.com/localstack/localstack/issues/667)), I'm not sure where I'm going wrong with this setup.

I did find an [interesting issue](https://github.com/localstack/localstack/issues/1568) that seems to have encountered the same problem, but they did the ol' ["Figured it out!" and disappear](https://xkcd.com/979/) trick.

I would really appreciate any help!

**Comment by whummer** [comment]
Thanks for reporting @paritoshcm 

There have been some long-standing open issues with AWS to support setting the endpoint for all client SDKs via environment variables (e.g., see [here](https://github.com/aws/aws-cli/issues/4454) for the AWS CLI). However, currently the only easy way to customize the endpoint is via code, using `S3Client` as you mentioned.

We have an ongoing workstream where we're working on patching the Lambda runtime Docker image, to bake the `EndpointUrl=...` change for the AWS SDKs into the Docker image itself, which should make things a bit easier. 

For now, the recommended pattern is to introduce a light-weight environment concept (e.g., `dev`/`prod`) and contruct AWS SDK clients with `EndpointUrl` for dev mode (reading `LOCALSTACK_HOSTNAME` from the environment, e.g., `http://$LOCALSTACK_HOSTNAME:4566`). Hope that helps - please keep us posted how it goes. Thanks!

**Comment by paritoshcm** [comment]
Thanks so much for the response, @whummer!

I was able to make it work using a different configuration for `S3Client` when using localstack! And it also works deployed to AWS!

In the `template.yaml` I shared above, I am using a `StageName` parameter obtained from the `samconfig.toml`:
```toml
[localstack]
[localstack.deploy]
[localstack.deploy.parameters]
# There is other stuff here
parameter_overrides="StageName=\"Local\" MyBucketName=\"localstack-myapp\""
```
Then, in the `template.yaml`, I added `Mappings` to determine the environment:
```yaml
Parameters:
  StageName:
    Type: String
    Description: "REQUIRED: Stage for the build."
    Default: Dev
    AllowedValues:
      - Local
      - Dev
      - Prod

Mappings:
  StageMap:
    Local:
      Env: local
    Dev:
      Env: development
    Prod:
      Env: production

Resources:
  # There's other stuff here, just not relevant

  MyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: lambda.handler
      Description: My humble application.
      Runtime: nodejs14.x
      Environment:
        Variables:
          # The main change, use StageName to determine environment
          NODE_ENV: !FindInMap [StageMap, !Ref StageName, Env]
          AWS_S3_BUCKET: !Ref MyBucketName
      Events:
        BaseEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET # Because ANY does NOT work on localstack :(
        GetEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: GET # Because ANY does NOT work on localstack :(
        PostEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: POST # Because ANY does NOT work on localstack :(
      Role: !GetAtt MyRole.Arn
```
> _Aside_: I want to point out again that `Method: ANY` is not working on localstack with Event `Type: Api`, I don't know if it's a known issue or not, but I had to explicitly specify the method, otherwise I was getting `Unable to find integration for path`.

This setup properly sets `NODE_ENV` when deploying the function, which I can check in my application and configure `S3Client` accordingly:
```ts
const localConfig: S3ClientConfig = {
    endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:${process.env.EDGE_PORT}`,
    forcePathStyle: true,
};

export const s3Client: S3Client = new S3Client(isLocal() ? localConfig : {});
```
Do note that `forcePathStyle` **IS** required in addition to `endpoint`; it did not work without `forcePathStyle: true`.

Maybe it was obvious, but in case it wasn't, I hope this helped someone. Here's hoping that in the future localstack becomes more seamless!
