### ISSUE TITLE
CloudFormation Mapping with same name as Parameter raises error (minor)

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a minor issue but figured it was worth reporting.

Please excuse the trivial nature of the template, it's purely for example. I understand that !FindInMap is pointless in my example.

The template below does not work, as the mapping "Environment" has the same name as the CloudFormation parameter "Environment".

```
---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Which environment the resources will be deployed in
    Type: String
    Default: dev
Mappings:
  Environment:
    dev: 
      BucketName: dev-bucket
    prod: 
      BucketName: prod-bucket
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !FindInMap [ Environment, !Ref Environment, BucketName ]
```

Changing the template to the following DOES work:

```
---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Which environment the resources will be deployed in
    Type: String
    Default: dev
Mappings:
  EnvironmentMap:
    dev: 
      BucketName: dev-bucket
    prod: 
      BucketName: prod-bucket
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !FindInMap [ EnvironmentMap, !Ref Environment, BucketName ]
```

### Expected Behavior

AWS does not have this limitation, you're able to have parameters and mappings with the same names. Ideally, Localstack would support this same functionality.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Start localstack (however you like).
Deploy CloudFormation template to localstack (however you like).

### Environment

```markdown
- OS: Windows
- LocalStack: latest  sha256:4509c5e014a7412c58b59029a2ab7e1b5ca7312f5ba1139e546040a07ed06120
```
