### ISSUE TITLE
PRO_Getting SnsException: null (Service: Sns, Status Code: 404, Request ID: null, Extended Request ID: null) when lambda is trying to publish a message to an SNS topic

### ISSUE THREAD

**Issue by ambreenshamim** [localstack/localstack#4556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting error when my lambda is triggered and trying to publish a message to an SNS topic. 
Error sending message { "message here"} to topic "arn"

![image](https://user-images.githubusercontent.com/89807574/132412830-b7affa69-d4b4-4368-a806-3337f56d7ac8.png)

### Expected Behavior

Lambda Should be able to send/publish message to sns topic

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up -d

```yaml
version: '2.2'

services:

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch6-8/data
    ports:
      - 9200:9200

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      - AWS_REGION=us-east-1
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      #- LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse}
      - LAMBDA_EXECUTOR=docker
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    # - LAMBDA_DOCKER_NETWORK=localstack_default
      - LAMBDA_DOCKER_NETWORK=ecare-localstackdemoallservices_default
      - HOST_TMP_FOLDER=${TEMP_LOCALSTACK_DIR}
    volumes:
      - "${TEMP_LOCALSTACK_DIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  data01:
    driver: local
  data02:
    driver: local
```

Steps:
Create queue
create function
source map queue and lambda
create topic
subscribe lambda to topic
send message to queue to trigger lambda which should publish a msg to SNS topic

### Environment

```markdown
- OS: Windows
- LocalStack version: 0.12.17.5
```
