### ISSUE TITLE
AWS::KMS::Key KeyUsage ignored when created by CloudFormation [kms-local]

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

N.B. I'm using kms-local as the [moto implementation doesn't seem to support the Sign operation](https://github.com/localstack/localstack/issues/4419).

Deploying the following template results in a key with KeyUsage: ENCRYPT_DECRYPT, not SIGN_VERIFY.

```
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Key:
    Type: AWS::KMS::Key
    Properties: 
      Description: Example key
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy: 
        Version: "2012-10-17"
        Id: root
        Statement:
          - Sid: Enable IAM User Permissions,
            Effect: Allow
            Principal: 
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
      KeySpec: RSA_2048
      KeyUsage: SIGN_VERIFY
```

```
awslocal kms list-keys
{
    "Keys": [
        {
            "KeyId": "301daea8-22f4-4705-9e72-31634217012a",
            "KeyArn": "arn:aws:kms:us-east-1:000000000000:key/301daea8-22f4-4705-9e72-31634217012a"
        }
    ]
}
```

```
awslocal kms describe-key --key-id 301daea8-22f4-4705-9e72-31634217012a
{
    "KeyMetadata": {
        "AWSAccountId": "000000000000",
        "KeyId": "301daea8-22f4-4705-9e72-31634217012a",
        "Arn": "arn:aws:kms:us-east-1:000000000000:key/301daea8-22f4-4705-9e72-31634217012a",
        "CreationDate": 1631079978,
        "Enabled": true,
        "KeyUsage": "ENCRYPT_DECRYPT",
        "KeyState": "Enabled",
        "Origin": "AWS_KMS",
        "KeyManager": "CUSTOMER",
        "CustomerMasterKeySpec": "SYMMETRIC_DEFAULT",
        "EncryptionAlgorithms": [
            "SYMMETRIC_DEFAULT"
        ]
    }
}
```

### Expected Behavior

The key should be created with usage SIGN_VERIFY.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Start localstack (however you like, ensure kms service is enabled).
2. Deploy template in above example.

### Environment

```markdown
- OS: Windows
- LocalStack: latest  sha256:4509c5e014a7412c58b59029a2ab7e1b5ca7312f5ba1139e546040a07ed06120
```
