### ISSUE TITLE
AWS::Serverless::Authorizer not invoked (maybe not even deployed?)

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following template deploys a simple function with a default authorizer. The authorizer function code is flawed and will result in an error when invoked but this is not the point. The authorizer is not invoked at all. As far as I can tell from the CLI, the authorizer is not even deployed.

Note that I've tried with/without `OpenApiVersion` specified below. If omitted, `securityDefinitions` appears instead of `securitySchemes`. I wondered if only `securitySchemes` is supported as per [this issue](https://github.com/localstack/localstack/issues/4376). Regardless of the omitting / including OpenApiVersion, the authorizer doesn't work.

```
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: "test-rest-api"
      StageName: Prod
      OpenApiVersion: "3.0.3"
      Auth:
        DefaultAuthorizer: TokenAuthorizer
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt TokenAuthorizer.Arn
            FunctionPayloadType: TOKEN
            Identity:
              ReauthorizeEvery: 300
  TokenAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Description: Token authorizer
      Policies:
      FunctionName: test-rest-api-token-authorizer
      Timeout: 30
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print('hello world')
      PackageType: Zip
  DummyMethod:
    Type: AWS::Serverless::Function
    Properties:
      Description: Dummy function
      FunctionName: test-rest-api-dummy-function
      Timeout: 30
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print('hello world')
      PackageType: Zip
      Events: 
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /dummy-path
            RestApiId: !Ref Api
Outputs:
  RestApiId:
    Description: ID of the REST API.
    Value: !Ref Api
```

### Expected Behavior

The authorizer should be invoked. Calling the `/dummy-path` endpoint should result in a 500 (as the authorizer function is not written properly) to the client and associated logs in the localstack docker container. Instead, the client recieves a 200 and the authorizer is not invoked.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml

Sorry, lots of extra fluff i use for testing.

```
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510:4510"
      - "4513:4513"
      - "4514:4514"
      - "4571:4571"
      - "4572:4572"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=serverless,sns,sqs,kms,route53,acm
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=...
      - DEBUG=true
      - KMS_PROVIDER=local-kms
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tmpfs:
      - /tmp/localstack:exec,mode=600
    network_mode: bridge
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

1. docker-compose up
2. samlocal deploy --stack-name authorizer-not-deployed -t authorizer-not-deployed.yml
3. Note the RestApiId output of the CloudFormation template.
4. Invoke the "dummy-path" endpoint [GET]: http://localhost:4566/restapis/{{REST_API_ID}}/Prod/_user_request_/dummy-path
5. The function incorrectly returns 200 (as the authorizer was not invoked), the logs show that the authorizer function was not invoked.

### Environment

```markdown
- OS: Windows
- LocalStack: latest  sha256:4509c5e014a7412c58b59029a2ab7e1b5ca7312f5ba1139e546040a07ed06120
```
