### ISSUE TITLE
LocalStack does not seem to translate --self-managed-event-source by serverless

### ISSUE THREAD

**Issue by abbaseya** [localstack/localstack#4569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using `serverless` to configure `SelfManagedEventSource`, LocalStack throws an error `KeyError: EventSourceArn` during Lambda creation.

### Expected Behavior

LocalStack should map self-managed event sources from `serverless` 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

> A test case available at [GitHub](https://github.com/abbaseya/localstack-msk-lambda-test) - test command `./localstack.sh --use-kafka`

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`.env`
```
HOST_IP=10.254.254.254
LAMBDA_TOPIC_PREFIX=lambda_data
```

`docker-compose.yml`
```yml
version: '3.9'

services:
    localstack:
        container_name: localstack
        image: localstack/localstack-full:0.12.17.5
        ports:
            - 443:443
            - 4510-4530:4510-4530
            - 4566:4566
            - 4571:4571
        environment:
            - LOCALSTACK_API_KEY=${LOCALSTACK_LICENSE}
            - USE_LIGHT_IMAGE=0
            - IMAGE_NAME=localstack/localstack-full:0.12.17.5
            - MAIN_CONTAINER_NAME=localstack
            - SERVICES=cloudformation,cloudfront,apigateway,apigatewayv2,iam,secretsmanager,lambda,s3,sqs,sts,ec2,kafka,elb,elbv2
            - DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - S3_SKIP_SIGNATURE_VALIDATION=1
            - DEBUG=1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: bridge
    kafka:
        container_name: kafka
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=${HOST_IP}
            - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
            - KAFKA_DELETE_TOPIC_ENABLE=true
            - KAFKA_CREATE_TOPICS=${LAMBDA_TOPIC_PREFIX}:1:1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        volumes:
            -kafka-data:/kafka
            - /var/run/docker.sock:/var/run/docker.sock
        healthcheck:
            test: ["CMD", "bash", "-c", "unset", "JMX_PORT", ";", "kafka-topics.sh", "--zookeeper", "zookeeper:2181", "--list"]
        depends_on:
            - zookeeper
        networks:
            - default
    
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        volumes:
            - test-zookeeper-conf:/opt/zookeeper-3.4.13/conf
            - test-zookeeper-data:/opt/zookeeper-3.4.13/data
        networks:
            - default
         
volumes:
    kafka-data:
        name:kafka-data
    zookeeper-conf:
        name: zookeeper-conf
    zookeeper-data:
        name: zookeeper-data

networks:
    default:
        name: test
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.238.0/24
```

`.env.local`
```
REGION=us-east-2
SECURITY_GROUP1=sg-903b35b0
SECURITY_GROUP2=sg-b119e4ba
VPC_SUBNET1=subnet-a466a5ec
VPC_SUBNET2=subnet-9c81e5d3
VPC_SUBNET3=subnet-41740216
VPC_SUBNET4=subnet-886e468f
VPC_SUBNET5=subnet-a90598fe
VPC_SUBNET6=subnet-24721cb7
LAMBDA_TOPIC_PREFIX=lambda_data
LAMBDA_TOPIC=lambda_data_0
KAFKA_BROKER=10.254.254.254:9092
SECRET_ARN=arn:aws:secretsmanager:us-east-2:000000000000:secret:test-PvfKuL
```

`serverless.yml`
```yml
service: lambda-process
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  apiName: ${self:service}-${self:provider.stage}
  apiGateway:
    minimumCompressionSize: 1024
    metrics: false
    description: "Serverless ${self:service} Deployment"
  stage: ${opt:stage, self:provider.environment.version}
  region: ${env:REGION}
  deploymentPrefix: deploy-serverless
  endpointType: EDGE
  deploymentBucket:
    name: lambda-bucket
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    tags:
      Name: ${self:service}
      env: ${self:provider.stage}
      app: ${self:service}
  timeout: 600
  memorySize: 128
  lambdaHashingVersion: 20201221
  tags:
    Name: ${self:service}
    env: ${self:provider.stage}
    app: ${self:service}
  stackTags:
    Name: ${self:service}
    env: ${self:provider.stage}
    app: ${self:service}
  environment:
    NODE_ENV: ${self:provider.stage}
    version: "v1"
    stage: ${self:provider.stage}
    AWS_CUSTOM_ACCESSID: "test"
    AWS_CUSTOM_SECRETACCESSKEY: "test"
    AWS_CUSTOM_AWS_REGION: "us-east-1"
    AWS_S3_MAX_AGE: "3153600"
    AWS_S3_HTML_DOCUMENT_TYPE: "text/html"
    AWS_S3_CSS_DOCUMENT_TYPE: "text/css"
    AWS_S3_JSON_DOCUMENT_TYPE: "application/json"
    KAFKA_BROKER: ${env:KAFKA_BROKER}
    KAFKA_DATA_TOPIC_PREFIX: ${env:LAMBDA_TOPIC_PREFIX}
  tracing:
    apiGateway: ${self:custom.debugLogging.${self:provider.stage}}
    lambda: ${self:custom.debugLogging.${self:provider.stage}}
  logs:
    restApi:
      executionLogging: ${self:custom.debugLogging.${self:provider.stage}}
      enableAccessLogging: ${self:custom.debugLogging.${self:provider.stage}}
      accessLogging: ${self:custom.debugLogging.${self:provider.stage}}
      level: ERROR
    httpApi: ${self:custom.debugLogging.${self:provider.stage}}
    lambda: ${self:custom.debugLogging.${self:provider.stage}}
    websocket: ${self:custom.debugLogging.${self:provider.stage}}
    frameworkLambda: ${self:custom.debugLogging.${self:provider.stage}}
  logRetentionInDays: ${self:custom.logRetentionInDays.${self:provider.stage}}

plugins:
  - serverless-localstack

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - 'lambda-process/**'
  exclude:
    - 'node_modules/**'
    - 'serverless*.yml'

layers:
  layerBasicNodeModule:
    path: layer-basic
    name: layerBasic-${self:provider.stage}
    description: "basic node_module"
    compatibleRuntimes:
      - nodejs12.x
    package:
      include:
        - nodejs/node_modules/**
      exclude:
        - 'node_modules/**/README.*'
        - 'node_modules/**/test/**'

functions:
  
  processDataTopic0:
    handler: lambda-process/handlers.processDataTopic
    runtime: nodejs12.x
    timeout: 600
    memorySize: 1024
    tags:
      env: ${self:provider.stage}
      app: ${self:service}-processDataTopic
    layers:
      - { Ref: LayerBasicNodeModuleLambdaLayer }
    events:
      - kafka:
          topic: ${env:LAMBDA_TOPIC}
          accessConfigurations:
            saslScram512Auth: ${env:SECRET_ARN}
            vpcSubnet:
              - ${env:VPC_SUBNET1}
              - ${env:VPC_SUBNET2}
              - ${env:VPC_SUBNET3}
              - ${env:VPC_SUBNET4}
              - ${env:VPC_SUBNET5}
              - ${env:VPC_SUBNET6}
            vpcSecurityGroup:
              - ${env:SECURITY_GROUP1}
              - ${env:SECURITY_GROUP2}
          bootstrapServers:
            - ${env:KAFKA_BROKER}
          enabled: true

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode: False
    docker:
      sudo: False
  serverless-iam-roles-per-function:
    defaultInherit: true
  logRetentionInDays:
    local: 14
  debugLogging:
    local: true
  disableFunctionLogging:
    local: false
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    serverless deploy --stage local

LocalStack logs:
```
2021-09-09 08:07:07,223:API: 127.0.0.1 - - [09/Sep/2021 08:07:07] "POST /2015-03-31/event-source-mappings/ HTTP/1.1" 500 -
2021-09-09 08:07:09,868:API: 127.0.0.1 - - [09/Sep/2021 08:07:09] "POST / HTTP/1.1" 200 -
2021-09-09T08:07:10:ERROR:lambda_api: Exception on /2015-03-31/event-source-mappings/ [POST]
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 1853, in create_event_source_mapping
    mapping = add_event_source(data)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 272, in add_event_source
    mapping = build_mapping_obj(data)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 252, in build_mapping_obj
    source_arn = data["EventSourceArn"]
KeyError: 'EventSourceArn'
```

### Environment

```markdown
- OS: macOS 11.5.2
- LocalStack: latest
- AWS CLI: 2.2.35
- Serverless: 2.57.0
```
