### ISSUE TITLE
AWS::ApiGatewayV2::IntegrationResponse deployment issue (says IntegrationId is not provided, but the logs suggest it has a value)

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to deploy AWS::ApiGatewayV2::IntegrationResponse resource. Unsure if this is specific to mocked integration responses.

The final resource in the below template fails to deploy:

```
---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: websockets-api
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  PingRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: ping
      AuthorizationType: NONE
      OperationName: Ping Route
      RouteResponseSelectionExpression: $default
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref PingIntegration
  PingRouteResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties: 
      ApiId: !Ref Api
      RouteId: !Ref PingRoute
      RouteResponseKey: $default
  PingIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Api
      Description: Ping Integration
      IntegrationType: MOCK
      TemplateSelectionExpression: '200'
      RequestTemplates:
        "200": "{\"statusCode\":200}"
  PingIntegrationResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties: 
      ApiId: !Ref Api
      IntegrationId: !Ref PingIntegration
      IntegrationResponseKey: $default
      ResponseTemplates:      
        "200": "{\"\\$type\":\"Pong\"}"
      TemplateSelectionExpression: '200'
```

Notable log entries suggest that the IntegrationId is not being provided to the IntegrationResponse resource creation, but it clearly seems to have a value:

```
localstack_main   | 2021-09-10T04:35:49:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected error retrieving details for resource type AWS::ApiGatewayV2::IntegrationResponse: Exception: Parameter validation failed:
localstack_main   | Missing required parameter in input: "IntegrationId" - {'ApiId': 'f0203a26', 'IntegrationId': 'cd127dde', 'IntegrationResponseKey': '$default', 'ResponseTemplates': {'200': '{"\\$type":"Pong"}'}, 'TemplateSelectionExpression': '200'} - status: None      
```

### Expected Behavior

For the `AWS::ApiGatewayV2::IntegrationResponse` resource to deploy successfully.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml:

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=serverless,acm,route53,apigateway,apigatewayv2,kms,sqs
      - DEBUG=true
      - DATA_DIR=/tmp/localstack-data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=<masked>
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/tmp/localstack-data:/tmp/localstack-data"
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

1. Start with docker compose file above.
2. Save example template as `integration-id-example.yml`.
3. Attempt to deploy to localstack: `awslocal cloudformation create-stack --stack-name integration-id-example --template-body file://Cloudformation/alerts-websockets-api/integration-id-example.yml`
4. Observe errors in docker logs.

### Environment

```markdown
- OS: Windows
- LocalStack: 
LocalStack version: 0.12.17.5
LocalStack Docker container id: 0f13e636b5c0
LocalStack build date: 2021-09-09
LocalStack build git hash: b769810a
```

### Anything else?

[logs.txt](https://github.com/localstack/localstack/files/7141310/integration-id-example.txt)
