### ISSUE TITLE
bug: Unexpected resource type Athena::WorkGroup when deploying from CloudFormation/SAM template

### ISSUE THREAD

**Issue by danw-mpl** [localstack/localstack#4591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm unable to deploy an AWS::Athena::WorkGroup from CloudFormation.

The first run of `samlocal deploy` results in:

```
localstack_main    | 2021-09-14T09:31:12:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type Athena::WorkGroup when resolving references of resource MyAthenaWorkGroup: {'Type': 'AWS::Athena::WorkGroup', 'LogicalResourceId': 'MyAthenaWorkGroup', 'Properties': {'Name': 'Data_Analyst_Group', 'Description': 'Workgroup for data analysts', 'State': 'ENABLED', 'Tags': [{'Key': 'Division', 'Value': 'West'}, {'Key': 'Location', 'Value': 'Seattle'}, {'Key': 'Team', 'Value': 'Big Data'}], 'WorkGroupConfiguration': {'EnforceWorkGroupConfiguration': True, 'PublishCloudWatchMetricsEnabled': True, 'ResultConfiguration': {'OutputLocation': 's3://sam-bucket'}}}}
```

The second run of `samlocal deploy` results in:

```
localstack_main    | 2021-09-14T09:31:46:ERROR:cloudformation_api: Exception on / [POST]
localstack_main    | Traceback (most recent call last):
localstack_main    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
localstack_main    |     response = self.full_dispatch_request()
localstack_main    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
localstack_main    |     rv = self.handle_user_exception(e)
localstack_main    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
localstack_main    |     return cors_after_request(app.make_response(f(*args, **kwargs)))
localstack_main    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
localstack_main    |     rv = self.dispatch_request()
localstack_main    |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
localstack_main    |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
localstack_main    |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 978, in handle_request
localstack_main    |     result = func(req_params)
localstack_main    |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_api.py", line 804, in execute_change_set
localstack_main    |     deployer.apply_change_set(change_set)
localstack_main    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1531, in apply_change_set
localstack_main    |     action=action,
localstack_main    |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1823, in apply_changes
localstack_main    |     raise NoStackUpdates("No updates are to be performed.")
localstack_main    | localstack.utils.cloudformation.template_deployer.NoStackUpdates: No updates are to be performed.
```

`awslocal athena list-work-groups` returns an empty array.

**Note, the same WorkGroup configuration can be created using the `awslocal` CLI without a problem.**:

```bash
awslocal athena create-work-group --name Data_Analyst_Group --configuration ResultConfiguration={OutputLocation="s3://sam-bucket"},EnforceWorkGroupConfiguration="true",PublishCloudWatchMetricsEnabled="true"     --description "Workgroup for data analysts"     --tags Key=Division,Value=West Key=Location,Value=Seattle Key=Team,Value="Big Data"
```

### Expected Behavior

The WorkGroup should deploy as expected.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml:

_Note we're using a custom Dockerfile which copies a CA cert and runs update-ca-certificates - have also tested on a device without this and directly used localstack:latest._

```yaml
version: "3.8"

services:
  localstack:
    container_name: "localstack_main"
    build:
      dockerfile: dev-env/Dockerfile.localstack
      context: .
    networks:
      - default
      - localstack
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - LOCALSTACK_API_KEY=**************
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 # Required to prevent 403 from Commandeer
      - DISABLE_EVENTS=1 # Disable Localstack telemetry
      - DATA_DIR=/tmp/localstack/data
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt # See Dockerfile.localstack
    volumes:
      - "localstack_data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
export AWS_DEFAULT_REGION=eu-west-1

awslocal s3 mb "s3://sam-bucket"

samlocal build --template "MyTemplate.yaml" --build-dir "/tmp/.aws-sam" --use-container

samlocal package \
    --template-file "/tmp/.aws-sam/template.yaml" \
    --s3-bucket "sam-bucket" \
    --output-template-file "/tmp/.aws-sam/MyTemplate.yaml"

samlocal deploy \
    --no-fail-on-empty-changeset \
    --stack-name "MyStack" \
    --template "/tmp/.aws-sam/MyTemplate.yaml" \
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
```

#### MyTemplate.yaml

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: "My Template"

Resources:
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: Data_Analyst_Group
      Description: Workgroup for data analysts
      State: ENABLED
      Tags:
        - Key: "Division"
          Value: "West"
        - Key: "Location"
          Value: "Seattle"
        - Key: "Team"
          Value: "Big Data"
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: s3://sam-bucket
```

### Environment

```markdown
- OS: Ubuntu 20.04 (WSL2), also tested on latest macOS
- LocalStack: 0.12.17.5 (ceb64387)
```
