### ISSUE TITLE
Event source mapping on MSK does not meet AWS message structure

### ISSUE THREAD

**Issue by abbaseya** [localstack/localstack#4606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After implementing MSK source mapping as per Issue [#4544](https://github.com/localstack/localstack/issues/4544). Events are getting emitted yes, but the event structure does not meet AWS messages as described at https://aws.amazon.com/blogs/compute/using-amazon-msk-as-an-event-source-for-aws-lambda/

### Expected Behavior

MSK emitted events should meet AWS message structure:
```json
{
  "eventSource": "aws:kafka",
  "eventSourceArn": "aws:aws:kafka:us-east-1:000000000000:cluster/XXXXXXXX",
  "records": {
    "mytopic-1": [
      {
        "topic": "mytopic",
        "partition": 0,
        "offset": 15,
        "timestamp": 1631782944619,
        "timestampType": "CREATE_TIME",
        "value": "ewogICJhY2NvdW50X2lkIjogIjEiLAogICJkb21haW..."
      }
    ]
  }
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
version: '3.9'

services:
    localstack:
        container_name: localstack
        image: localstack/localstack-full
        ports:
            - 443:443
            - 4510-4530:4510-4530
            - 4566:4566
            - 4571:4571
        environment:
            - LOCALSTACK_API_KEY=${LOCALSTACK_LICENSE}
            - USE_LIGHT_IMAGE=0
            - IMAGE_NAME=localstack/localstack-full
            - MAIN_CONTAINER_NAME=localstack
            - SERVICES=cloudformation,cloudfront,apigateway,apigatewayv2,iam,secretsmanager,lambda,s3,sqs,sts,ec2,kafka,elb,elbv2
            - DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - DEBUG=1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: bridge
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

A test case available at [GitHub](https://github.com/abbaseya/localstack-msk-lambda-test) - test command `./localstack.sh --use-hostname`

### Environment

```markdown
- OS: macOS 11.5.2
- LocalStack: latest
- AWS CLI: 2.2.35
```
