### ISSUE TITLE
WebSockets API does not work after container restart (persistent data)

### ISSUE THREAD

**Issue by m-chandler** [localstack/localstack#4650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When stopping and starting a localstack container with persistent storage, successfully deployed websocket API's fail to work after the restart with the following errors after connecting:

* Unable to find API entity for ID "71a3bfce" in region "None"
* 'NoneType' object has no attribute 'routes'

### Expected Behavior

It should be possible to restart the container when persistent storage is used, and have all services come back successfully.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

The following docker-compose.yml file has been used (with API key masked).

docker-compose.yml
```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510:4510" # Websocket API
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=serverless,acm,route53,kms,sqs,cloudfront
      - DEBUG=true
      - DATA_DIR=/tmp/localstack-data
      - LAMBDA_EXECUTOR=docker-reuse
      - LOCALSTACK_API_KEY=...
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      # - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/tmp/localstack:/tmp/localstack"
      - "/c/tmp/localstack-data:/tmp/localstack-data"
  dynamodb-admin:
    depends_on:
      - localstack
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - localstack
    network_mode: bridge
```

The following AWS SAM CFN template is being deployed:

ws-api.yml
```
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ws-api
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref Api
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    Properties:
      ApiId: !Ref Api
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: $connect
      OperationName: Connect Route
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectIntegration
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Api
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectFunction.Arn}/invocations
  ConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 2048
      Timeout: 15
      Handler: index.handler
      Runtime: python3.8
      PackageType: Zip
      InlineCode: |
        def handler(event, context):
          print("In Connect!")
  ConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - Api
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ConnectFunction
      Principal: apigateway.amazonaws.com
```

Steps:
1. Start localstack `docker-compose up`
2. Create bucket for AWS SAM deploy: `awslocal s3api create-bucket --bucket test`
3. Deploy SAM template: `samlocal deploy --stack-name ws-api --template-file ws-api.yml --s3-bucket test`
4. Wait until template deploys successfully.
5. Connect to websocket, it should work fine: `wscat -c localhost:4510`.
6. Stop localstack (CTRL+C in window running docker-compose).
7. Wait until localstack gracefully stopped.
8. Start localstack (again) `docker-compose up`
9. Wait until localstack successfully started.
10. Connect to websocket (again), it will immediately disconnect and show the below error in the logs.

Logs highlighting error:
```
localstack_main   | 2021-09-27T07:44:14:INFO:websockets.server: connection open
localstack_main   | 2021-09-27T07:44:14:DEBUG:localstack_ext.services.apigateway.authorizers: Unable to find API entity for ID "71a3bfce" in region "None"
localstack_main   | 2021-09-27T07:44:14:DEBUG:localstack_ext.utils.websockets: Received error on $connect event handler - denying WebSocket connection: 'NoneType' object has no attribute 'routes'
localstack_main   | 2021-09-27T07:44:14:INFO:localstack.utils.run: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fe348659710>(None) failed: 'NoneType' object has no attribute 'routes' Traceback (most recent call last):
localstack_main   |   File "/opt/code/localstack/localstack/utils/run.py", line 150, in run
localstack_main   |     result = self.func(self.params, **kwargs)
localstack_main   |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 31, in _run
localstack_main   |     return fn(*args, **kwargs)
localstack_main   |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/invocations.py", line 55, in handle_message
localstack_main   |   File "/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_ext/services/apigateway/invocations.py", line 139, in v2_invoke_action
localstack_main   | AttributeError: 'NoneType' object has no attribute 'routes'
localstack_main   |
localstack_main   | 2021-09-27T07:44:14:ERROR:asyncio: Exception in callback _chain_future.<locals>._set_state(<Future finis...te 'routes'")>, <Future at 0x...ttributeError>) at /usr/lib/python3.7/asyncio/futures.py:345
localstack_main   | handle: <Handle _chain_future.<locals>._set_state(<Future finis...te 'routes'")>, <Future at 0x...ttributeError>) at /usr/lib/python3.7/asyncio/futures.py:345>
localstack_main   | Traceback (most recent call last):
localstack_main   |   File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
localstack_main   |     self._context.run(self._callback, *self._args)
localstack_main   |   File "/usr/lib/python3.7/asyncio/futures.py", line 347, in _set_state
localstack_main   |     _copy_future_state(other, future)
localstack_main   |   File "/usr/lib/python3.7/asyncio/futures.py", line 317, in _copy_future_state
localstack_main   |     assert not dest.done()
localstack_main   | AssertionError
localstack_main   | 2021-09-27T07:44:14:INFO:websockets.server: connection closed
```

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest

LocalStack version: 0.12.18
LocalStack Docker container id: ced725ad58f0
LocalStack build date: 2021-09-26
LocalStack build git hash: ce67efee
```
