### ISSUE TITLE
bug: LAMBDA_DOCKER_FLAGS doesn't work with -e

### ISSUE THREAD

**Issue by Tobolov** [localstack/localstack#4652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to add environment variables to containers created to service lambda requests no longer works in the latest version of localstack. This works in localStack version 0.12.16

### Expected Behavior

Setting the environment variable `LAMBDA_DOCKER_FLAGS=-e TEST_VAL=True` on localstack's docker container will result in spawned containers created for serving lambda functions having the environment variable TEST_VAL set to True.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Run `docker-compose up -d` with the following docker-compose.yml
```yaml
version: '2.1'

services:
  localstack_ltest:
    container_name: "ltest"
    image: localstack/localstack:0.12.18
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=<removed>
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_FLAGS=-e TEST_VAL=True
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
```
2. Create the file logs-template.yml
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:  
  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 60
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref LambdaFunction]]
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaRolePolicy
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
              - 'logs:*'
              Resource: 'arn:aws:logs:*:*:*'
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "test-function"
      Role: !GetAtt LambdaFunctionRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.8
      Code:
        ZipFile: |
          import os
          def lambda_handler(event, context):
              print("environ: " + str(os.environ))


```
3. Run ` aws cloudformation deploy --stack-name test --template-file .\logs-template.yml --endpoint-url http://127.0.0.1:4566 --region us-east-1`
4. Run `aws --endpoint-url http://127.0.0.1:4566 --region us-east-1 lambda invoke --function-name test-function out.txt`
5. Run `aws --endpoint-url=http://localhost:4566 --region us-east-1 logs tail /aws/lambda/test-function`
6. Check for `"TEST_VAL": "True",`  being in the output of the above command.

### Environment

```markdown
Current configuration (broken)
- OS: Ubuntu 20.04
- LocalStack version: 0.12.18
- LocalStack build date: 2021-09-27
- LocalStack build git hash: 00797f9e

Working configuration
- OS: Ubuntu 20.04
- LocalStack version: 0.12.16
- LocalStack Docker container id: b0137bad2045
- LocalStack build date: 2021-07-31
- LocalStack build git hash: f1262f74
```
