### ISSUE TITLE
bug: <title>Failed Execution Event in a Step Function when calling SQS 

### ISSUE THREAD

**Issue by taramclean** [localstack/localstack#4665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a Step Function state calls a SQS queue an 'Executionfailed' event is thrown by the step function. The queue does work and the lambda that is connected to runs correctly.   get-execution-history on the step function shows the following events in order

- ExecutionStarted id: 1, previousEventId: 0
- TaskStateEntered id: 2, previousEventId: 1
- TaskScheduled id: 3, previousEventId: 2
- TaskStarted id: 4, previousEventId: 3
- ExecutionFailed id: 5, previousEventId: 2

### Execution Failed Event Details

```
"error": "States.ReferencePathConflict",
"cause": "Can't parse input, message=Unexpected character ('M' (code 77)): was expecting double-quote to start field name\n at [Source: (String)\"{MD5OfMessageBody: 6d86560a1fa844118cc15af69e8b7086,MessageId: cdd39952-13f5-d356-f658-27ee82df07aa,}\"; line: 1, column: 3] input={MD5OfMessageBody: 6d86560a1fa844118cc15af69e8b7086,MessageId: cdd39952-13f5-d356-f658-27ee82df07aa,}"
```
The error means that the step function stops and never gets past the step that call the SQS. Attached is an example of the step function json config.
[step-function-config.txt](https://github.com/localstack/localstack/files/7251925/step-function-config.txt)

### Behavior of Step Function in AWS
The same setup of the Step Function, SQS and Lambda works in AWS 

### Expected Behavior

Step function goes through each state successfully and completes without any errors being thrown

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   Using a tye file with the following command `tye run tye.yaml`
   
Tye config as below
```
- name: localstack
  image: localstack/localstack
  bindings:
    - port: 4566
      connectionString: "${host}:${port}"
  env:
    - SERVICES="apigateway, route53, stepfunctions, lambda, iam, sqs, sns, s3, ec2, logs, dynamodb" # only start selective services
    - LAMBDA_EXECUTOR="docker-reuse"
    - DOCKER_FLAGS="privileged"
    - LAMBDA_DOCKER_NETWORK="bridge"
    - LOCALSTACK_HOSTNAME="localstack
  volumes:
    - source: ./localstack
      target: /docker-entrypoint-initaws.d
    - source: /var/run/docker.sock
      target: /var/run/docker.sock
```

#### Start the step function

`awslocal stepfunctions --endpoint http://localhost:4566 start-execution --state-machine arn:aws:states:us-east-1:000000000000:stateMachine:StateMachine --name test --input  '{"CorrelationId" : "70a67138-f2ca-4136-b0d7-051a64dae759"}'`

#### Get execution history of the step function

`awslocal stepfunctions --endpoint http://localhost:4566 get-execution-history --execution-arn arn:aws:states:us-east-1:000000000000:execution:StateMachine`

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```
