### ISSUE TITLE
bug: ECS doesn't pass environment variables from containerOverrides

### ISSUE THREAD

**Issue by danw-mpl** [localstack/localstack#4666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running an ECS task with Boto3, the environment variables set in `containerOverrides` are not passed to the task:

```
run_task_response = ecs.run_task(
    launchType="FARGATE",
    cluster="MyCluster",
    count=1,
    taskDefinition="arn:aws:ecs:eu-west-1:000000000000:task-definition/my-family:1",
    networkConfiguration={
        "awsvpcConfiguration": {
            "subnets": ["subnet-0d2b94a8c9225222c"],
            "securityGroups": ["sg-936968c66553602c7"],
        }
    },
    overrides={
        "containerOverrides": [
            {
                "name": "my-container",
                "environment": [
                    {
                        "name": "S3_PATH",
                        "value": "path/to/file.txt"
                    }
                ]
            }
        ]
    }
)
```

Debug output (heavily stripped):

```
localstack         | 2021-09-29T13:39:38:DEBUG:localstack.services.edge: IN(ecs): "POST /" - headers: {
"overrides": {
    "containerOverrides": [
        {"name": "my-container",
         "environment": [
             {"name": "S3_PATH", "value": "path/to/file.txt"}]}]}}'

localstack         | 2021-09-29T13:39:38:INFO:localstack_ext.services.ecs.ecs_listener: Starting ECS task in Docker: ...

localstack         | 2021-09-29T13:39:38:DEBUG:localstack.services.edge: OUT(ecs): "POST /" - status: 200...

response: {"tasks": [{"overrides": {"containerOverrides": [{"name": "my-container", "environment": [{"name": "S3_PATH", "value": "path/to/file.txt"}]}]}

localstack         | 2021-09-29T13:39:38:DEBUG:localstack.utils.docker: Running container with image: 000000000000.dkr.ecr.eu-west-1.amazonaws.com/************:dev
localstack         | 2021-09-29T13:39:38:DEBUG:localstack.utils.docker: Creating container with image 000000000000.dkr.ecr.eu-west-1.amazonaws.com/************:dev,

... env vars {'S3_PATH': '', ... 'AWS_DEFAULT_REGION': 'eu-west-1', 'LOCALSTACK_HOSTNAME': '172.28.0.2', 'AWS_REGION': 'eu-west-1', 'AWS_ACCESS_KEY_ID': 'test', 'AWS_SECRET_ACCESS_KEY': 'test'}
```

Notice the last line has value "" for S3_PATH.  That's what is set in the task definition.

### Expected Behavior

containerOverrides should override task definition environment variables.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Note, I've left most bits out since there's a lot which will go into the reproduction.  I'm hoping you could look at the code and identify what's up.  If you absolutely need full reproduction code I can do that.

```yaml
version: "3.8"

services:
  localstack:
    container_name: "localstack"
    build:
      dockerfile: dev-env/Dockerfile.localstack
      context: .
    networks:
      - default
      - localstack
    ports:
      # Default LocalStack port
      - "4566:4566"
      # Map to the ECR Docker registry because SAM doesn't support ECR URIs with :PORT.
      # Also requires "127.0.0.1 000000000000.dkr.ecr.eu-west-1.amazonaws.com" in your hosts file
      - "80:4513"
      # Also map the ECR Docker registry port. SAM seems to automatically login using this port.
      - "4513:4513"
    env_file: .env
    environment:
      - LS_LOG=trace
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- } # Normally provided by .env file - kept for test.sh
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1 # Required to prevent 403 from Commandeer
      - DISABLE_EVENTS=1 # Disable Localstack telemetry
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt # See Dockerfile.localstack
      - LAMBDA_REMOTE_DOCKER=false
      - HOST_TMP_FOLDER=/tmp/localstack
      - DATA_DIR=${DATA_DIR:-/tmp/localstack/data} # Default persistence for some services
      - LAMBDA_DOCKER_NETWORK=localstack # Fix DNS name resolution in spawned Lambda function containers
    volumes:
      - "localstack_data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.12.18

localstack         | LocalStack version: 0.12.18
localstack         | LocalStack Docker container id: 80085d503bd5
localstack         | LocalStack build date: 2021-09-23
localstack         | LocalStack build git hash: 2c436bad
```
