### ISSUE TITLE
bug: Unable to find Parameter Group: []*rds.DBParameterGroup(nil)

### ISSUE THREAD

**Issue by lefnire** [localstack/localstack#4779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `docker-compose.yml`:

```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro
      - "127.0.0.1:53:53/udp"            # only required for Pro
      - "127.0.0.1:443:443"              # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=acm,iam,lambda,rds,apigateway,apigatewayv2,cloudwatch,secretsmanager,edge,sts
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Relevant [rds.tf file](https://github.com/lefnire/gnothi/blob/terraform/terraform/rds.tf) (adapted from [terraform-aws-modules/examples/postgresql](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/blob/master/examples/postgresql/main.tf)). Relevant sections:

```
module "aurora" {
  ...
  db_parameter_group_name         = aws_db_parameter_group.example.id
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.example.id
  ...
}

resource "aws_db_parameter_group" "example" {
  name        = "${local.name}-aurora-db-postgres11-parameter-group"
  family      = "aurora-postgresql11"
  description = "${local.name}-aurora-db-postgres11-parameter-group"
  tags        = local.tags
}

resource "aws_rds_cluster_parameter_group" "aurora_db_postgres11_parameter_group" {
  name        = "${local.name}-aurora-postgres11-cluster-parameter-group"
  family      = "aurora-postgresql11"
  description = "${local.name}-aurora-postgres11-cluster-parameter-group"
  tags        = local.tags
}
```

```shell
│ Error: Unable to find Parameter Group: []*rds.DBParameterGroup(nil)
│ 
│   with aws_db_parameter_group.aurora_db_postgres11_parameter_group,
│   on rds.tf line 61, in resource "aws_db_parameter_group" "aurora_db_postgres11_parameter_group":
│   61: resource "aws_db_parameter_group" "aurora_db_postgres11_parameter_group" {
```
This works fine against AWS live (creates the parameter-groups and RDS). Honestly I'm newb and don't even know what param groups are for, I tried setting them to "default" "default" but got other errors.

A hunch I haven't tried: using posgres10, in case localstack doesn't support 11?

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d (or SERVICES=rds localstack start)

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    N/A

### Environment

```markdown
- OS: MacOS 11.6
- LocalStack: 0.12.19.1
```

### Anything else?

My first instinct is user error, but I got a bunch of other localstack issues pegged by seeing which services weren't running (localstack's error output); Googling other errors (eg, Lambda Layers fixed via `docker pull localstack/localstack`). I can't find this error anywhere on Github/StackOverflow
