### ISSUE TITLE
bug: Invalid XML response for STS GetFederationToken

### ISSUE THREAD

**Issue by robertam3** [localstack/localstack#4807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm seeing an XML parsing error when I try to use `GetFederationToken` with Localstack:
```
Aws::Xml::Parser::ParsingError: xmlns: 'https://sts.amazonaws.com/doc/ 2011-06-15/' is not a valid URI
```

I dug into the xml response and there is a newline character in that URL:

```
<GetFederationTokenResponse xmlns=\"https://sts.amazonaws.com/doc/\n2011-06-15/\">
```

Other STS actions (e.g. `GetSessionToken`) seem to be working as expected.

Note this issue was reported in the past, but was closed out without confirmation that it was actually fixed. Please see https://github.com/localstack/localstack/issues/1409 for more context.

### Expected Behavior

The URL in the XML response should be valid: `https://sts.amazonaws.com/doc/2011-06-15/`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
# docker-compose.yml
version: '3.3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sns,sqs,sts
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

```
docker-compose up
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I'm using the [Ruby AWS SDK v3](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/STS/Client.html#get_federation_token-instance_method):

```ruby
client = Aws::STS::Client.new(endpoint: 'http://host.docker.internal:4566')
client.get_federation_token(name: "test")
# Aws::Xml::Parser::ParsingError: xmlns: 'https://sts.amazonaws.com/doc/ 2011-06-15/' is not a valid URI
```

### Environment

```markdown
- LocalStack: latest
- aws-sdk-core: 3.121.2
- ruby-version: 3.0.2
```
