### ISSUE TITLE
bug: API-Gateway-v2 creates APIs in unreachable domain

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#4825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `awslocal apigatewayv2 create-api` command creates an API-endpoint under `<generated>.execute-api.localhost.localstack.cloud:4566`, which is an unresolved domain name, effectively making the API unusable.

```bash
$ ping -c1 6d7e3525.execute-api.localhost.localstack.cloud  # the URL given to my Localstack API-Gateway
ping: 6d7e3525.execute-api.localhost.localstack.cloud: No address associated with hostname
$ ping -c1 execute-api.localhost.localstack.cloud
ping: execute-api.localhost.localstack.cloud: No address associated with hostname
$ ping -c1 localhost.localstack.cloud
ping: localhost.localstack.cloud: No address associated with hostname
$ ping -c1 localstack.cloud  # the real website
PING localstack.cloud (185.199.111.153) 56(84) bytes of data.
64 bytes from cdn-185-199-111-153.github.com (185.199.111.153): icmp_seq=1 ttl=56 time=36.6 ms

--- localstack.cloud ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 36.640/36.640/36.640/0.000 ms
```

I cannot add it to `/etc/hosts` since the file does not allow for wildcards and the API-id is generated at creation time.

I also tried to use `awslocal apigatewayv2 create-domain-name` to get a static domain but `create-api` seems to ignore this. After creating the domain and adding it to my `/etc/hosts`, Localstack seems to find the wrong service under the URL --> HTTP-Status 404 and this body:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>test-api</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

### Expected Behavior

The `awslocal apigatewayv2 create-api` creates an API-endpoint under a domain the user can control. The traffic should not leave the machine where Localstack is being run.

From a user perspective, a predictable subdomain of `localhost` would be best, especially if we can get rid of the generated API-id. For example: `<api-name>.api.localhost` (no idea if this is technically viable, though).

I remember seeing it work once with the `<generated>.execute-api.localhost.localstack.cloud:4566` but I have absolutely no idea why and this behavior disappeared after a computer restart.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:0.12.16  # also tested with 0.12.19
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of `localstack.env`:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEBUG=1
KMS_SEED_PATH=/init/seed.yaml
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=docker
```

The file `localstack_api_key.env` contains my Localstack Pro API-key.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal apigatewayv2 create-domain-name --domain-name=apigateway.my-machine.local:4566
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP
```

Routes and integrations are irrelevant at this point.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.12.16 and 0.12.19
```

### Anything else?

Probably doing something wrong but I have absolutely no clue how this is supposed to work and the AWS-CLI docs are not helpful.

Hopefully this is the right place to post even if it is a Pro feature. Please redirect me otherwise.
