### ISSUE TITLE
bug: Cannot authorize requests using Lambda-Authorizer for HTTP-API

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#4848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to use a lambda function as an authorizer on HTTP-requests in API-Gateway-v2. According to multiple [online docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html), this should be possible, however I always get a HTTP-400 error back and the following response body, which Google does not seem to know:

```json
{
    "Type": "User",
    "message": "Authorization failed: 'id'",
    "__type": "InvalidResourceSpecification"
}
```

Full setup and steps to reproduce below.

### Expected Behavior

My (naive?) expectation would be that whichever token is included in my Authorization-header gets sent to the lambda function, which sends back a payload (version 2.0) indicating if the request is authorized and then the API-Gateway-v2 can send the request to the defined integration.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:0.12.19
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of localstack.env:

```
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEBUG=1
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=docker
```

The file `localstack_api_key.env` contains my Localstack Pro API-key.

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the `awslocal` commands below, `lambda-authorizer.zip` contains a `main.py` file with the following code:

```python
def handler(event, context):
    print("Hello, World! -- Lambda Authorizer")
    print(f"Event: {event}, Context: {context}")
    return {
        "isAuthorized": True,
        "context": {
            "exampleKey": "exampleValue"
        }
    }
```

And `backend-service` is the container name of my backend service which serves the actual API under port 9010.

What the initialization script does can be summarized in the following commands (executed withing Localstack container):

```bash
# Create the lambda function that will be our authorizer
awslocal lambda create-function --function-name=my-authorizer --zip-file=fileb:///opt/code/lambda_import/lambda-authorizer.zip --role=test-role --handler=main.handler --runtime=python3.8
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create an authorizer from the lambda function -- write down authorizer ID for route creation
awslocal apigatewayv2 create-authorizer --api-id=my-api --authorizer-type=REQUEST --authorizer-uri=arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:000000000000:function:my-authorizer/invocations --authorizer-payload-format-version=2.0 --enable-simple-responses --identity-source '$request.header.Authorization' --name=LambdaAuthorizer
# Create an integration to some endpoint (here /health for the example, could be any existing endpoint) -- write down integration ID for route creation
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --payload-format-version=1.0 --integration-method=GET --integration-uri=http://backend-service:9010/health
# Finally, create the route for the endpoint using the defined lambda authorizer and integration
awslocal apigatewayv2 create-route --api-id=my-api --route-key="GET /health" --authorization-type=CUSTOM --authorizer-id=86454fa3 --target=integrations/ef864e7d  # replace IDs here
```

The route can then be called (provided the DNS config is correct, see #4825) using `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/health` and triggers the above-mentioned error.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.12.19
```

### Anything else?

I am probably configuring it wrong but I have no clue what it is; tweaking the parameters in the example above never made it better. Removing the authorizer in the route declaration, all works fine.
