### ISSUE TITLE
bug: LAMBDA_DOCKER_FLAGS not passed to lambda functions using a container runtime

### ISSUE THREAD

**Issue by JacobReynolds** [localstack/localstack#4888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the `LAMBDA_DOCKER_FLAGS` environment variable, flags are not passed to lambda functions that use a PackageType of Image.

### Expected Behavior

`LAMBDA_DOCKER_FLAGS` is passed to lambda functions with container runtimes.

### How are you starting LocalStack?

With the `localstack` script

# Steps To Reproduce

## Setup
The below creates a cloudformation stack utilizing a lambda function with an ECR image. The lambda function prints `process.env` to stdout and can be viewed through the cloudwatch logs. Thanks to #4652 for the helpful cloudwatch template.

Copy the following files to a `/tmp` directory somewhere on your machine:
### test.yml
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:  
  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 60
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref LambdaFunction]]
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaRolePolicy
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
              - 'logs:*'
              Resource: 'arn:aws:logs:*:*:*'
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "test-function"
      Role: !GetAtt LambdaFunctionRole.Arn
      Handler: index.handler
      Runtime: node14
      PackageType: Image
      Timeout: 900
      Code:
        ImageUri: localhost:4513/test
```

### index.js
```javascript
exports.handler = () => {
  console.log(JSON.stringify(process.env, null, 2));
};
```
### Dockerfile
```docker
FROM public.ecr.aws/lambda/nodejs:14 AS RUNTIME

COPY index.js .

CMD ["index.handler"]
```

Pull version 0.12.20, the latest version has issues with deploying cloudwatch templates
```console
local@host:~$ docker pull localstack/localstack:0.12.20
local@host:~$ docker tag localstack/localstack:0.12.20 localstack/localstack:latest
```

Run the below commands to create the necessary components
```console
local@host:~$ LOCALSTACK_API_KEY=[api_key] LAMBDA_DOCKER_FLAGS="-e TEST123=VALUE" localstack start
local@host:~$ aws --endpoint-url http://127.0.0.1:4566 ecr create-repository --repository-name test --region us-east-1
local@host:~$ docker build . --tag localhost:4513/test
local@host:~$ docker push localhost:4513/test
local@host:~$ aws cloudformation deploy --stack-name test --template-file test.yml --endpoint-url http://127.0.0.1:4566 --region us-east-1
```

## Execution
```console
local@host:~$ aws --endpoint-url http://127.0.0.1:4566 --region us-east-1 lambda invoke --function-name test-function /dev/stdout
```

## Results
```console
local@host:~$ aws --endpoint-url=http://127.0.0.1:4566 --region us-east-1 logs tail /aws/lambda/test-function
```

Notice the env variable `TEST123` that was supplied through `LAMBDA_DOCKER_FLAGS` is not present.

### Environment

```markdown
- OS: MacOS Big Sur 11.1 
- LocalStack: 0.12.20
```
