### ISSUE TITLE
`latest` breaks healthcheck in Github Actions

### ISSUE THREAD

**Issue by wilsonpage** [localstack/localstack#4904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using the following code to start localstack in Github Actions. Since upgrading to [`latest`](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-e40ebe8c089fe19c6400bfdd248d57446566c193f9b6a9f1df2b6655f6884bf8?context=explore) my loop checking for `\"dynamodb\": \"running\"` never resolves and it hangs forever.

### docker-compose.yml

```yml
version: '2.1'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
```

### start-localstack.sh

```sh
# start in detached/background mode
SERVICES=dynamodb,sns docker-compose -f $DIR/docker-compose.yml up -d

#!/bin/bash
echo "waiting for dynamodb at ${AWS_ENDPOINT}/health"

# ping the localstack /health endpoint until it shows dynamo is running
until (curl --silent ${AWS_ENDPOINT}/health | grep "\"dynamodb\": \"running\"" > /dev/null); do
  printf '.'
  sleep 5
done
```

### Expected Behavior

Once started `/health` response should contain `\"dynamodb\": \"running\"`

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Detail above

### Environment

```markdown
- OS: `ubuntu-latest`
- LocalStack: [`lastest`](https://hub.docker.com/layers/localstack/localstack/latest/images/sha256-e40ebe8c089fe19c6400bfdd248d57446566c193f9b6a9f1df2b6655f6884bf8?context=explore)
```

### Anything else?

May be related to https://github.com/localstack/localstack/issues/4720
