### ISSUE TITLE
bug: lambda function alias created via cloudwatch has malformed FunctionVersion

### ISSUE THREAD

**Issue by navels** [localstack/localstack#4910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a lambda function with alias is created via a cloudwatch template, the FunctionVersion field of the alias is malformed, it has the function arn in it:
```
awslocal lambda get-alias --function-name foo --name bar
{
    "AliasArn": "arn:aws:lambda:us-east-1:000000000000:function:foo:bar",
    "Name": "bar",
    "FunctionVersion": "arn:aws:lambda:us-east-1:000000000000:function:foo:$LATEST:$LATEST",
    "Description": "",
    "RevisionId": "dff0c70b-6e76-4efa-ab13-934cf364354d"
}
```
which makes it impossible to invoke the function.

### Expected Behavior

The alias should look like this:
```
{
    "AliasArn": "arn:aws:lambda:us-east-1:000000000000:function:foo:bar",
    "Name": "bar",
    "FunctionVersion": "$LATEST",
    "Description": "",
    "RevisionId": "dff0c70b-6e76-4efa-ab13-934cf364354d"
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    samlocal deploy -g

SAM template file looks like this:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: [arm64]
      AutoPublishAlias: bar
      CodeUri: code/
      FunctionName: foo
      Handler: lambda.handler
      PackageType: Zip
      Runtime: python3.9
```

and the lambda file is `code/lambda.py` and is a NOOP:
```
def handler(event, context):
    pass
```

### Environment

```markdown
- OS: Mac OS
- LocalStack version: 0.12.20
- LocalStack Docker container id: d30f27d8af59
- LocalStack build date: 2021-11-11
- LocalStack build git hash: ab8d5597
```

### Anything else?

Creating the lamba and alias via the CLI works fine:
```
awslocal lambda create-function --function-name foo --runtime python3.9 --handler lambda.handler --role test --zip-file fileb://lambda.zip
awslocal lambda create-alias --function-name foo --name bar --function-version "\$LATEST"
```
