### ISSUE TITLE
bug: real s3 fails SSL validation in Pro

### ISSUE THREAD

**Issue by navels** [localstack/localstack#4925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This occurs with the multi-arch release (0.13.0) on an M1 Mac but not with the 0.12.20 release.  I don't have my Intel Mac handy or else I would try it there.  This only happens with the pro version of localstack.

When started with docker compose and with a pro api key, this command in the localstack container:
```
aws --profile prod s3 ls
```
results in
```
SSL validation failed for https://s3.amazonaws.com/ ("hostname 's3.amazonaws.com' doesn't match either of '*.cloudfront.localhost.localstack.cloud', '*.execute-api.localhost.localstack.cloud', '*.localhost.localstack.cloud', '*.s3.localhost.localstack.cloud', '*.scm.localhost.localstack.cloud', 'localhost.localstack.cloud'",)
```

(Note: I have mounted my host's aws profile directory into the localstack container and `--profile prod` has credentials for accessing real S3.)

### Expected Behavior

The `aws s3 ls` command should return a listing of the buckets in my s3 account, with no SSL errors.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack:

    docker compose up localstack

#### docker-compose.yml file:

```
version: "3.9"

services:
  localstack:
    image: localstack/localstack:0.13.0
    ports:
      - "4566:4566"
    environment:
      LOCALSTACK_API_KEY: <here_is_my_api_key>
      SERVICES: s3
    volumes:
      - ~/.aws:/root/.aws
```

#### Client commands
First open a shell in the localstack container:

    docker compose exec bash

and then do an s3 listing:

    aws --profile prod s3 ls

### Environment

```markdown
- OS: Mac M1
- LocalStack version: 0.13.0
- LocalStack build date: 2021-11-15
- LocalStack build git hash: 595eaef0
```
