### ISSUE TITLE
bug: Cannot overwrite or append request-headers in API-Gateway-v2

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#4928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to append headers to my HTTP request before sending it to the integration, using information from the Lambda Authorizer payload as well as static information. None of these headers get to the application.

I've configured the integration using the `awslocal` command and following the examples of the [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html).

Full setup and steps to reproduce below.

### Expected Behavior

I would expect the HTTP-headers to be received by the endpoint of my application.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:0.12.20  # 0.13 and latest break too much stuff
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of `localstack.env`:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=0
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

The following minimal reproducible example creates a route where 2 simple headers should be added -- I did not include the authorizer (even though the relevant headers for me are from its payload) because it only adds complexity and the problem is reproducible wihtout it.

The `backend-service` is a Spring-Boot application running on port 9010 in a container on the same network as Localstack.

Localstack setup:

```bash
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create an integration to some endpoint (here /health for the example, could be any existing endpoint) -- write down integration ID for route creation
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --payload-format-version=2.0 --integration-method=GET --integration-uri=http://backend-service:9010/test --request-parameters '{ "append:header.header1": "$context.requestId", "append:header.header2": "test" }'
# Finally, create the route for the endpoint using the defined integration
awslocal apigatewayv2 create-route --api-id=my-api --route-key="GET /test" --target=integrations/4f887842  # replace ID here
```

Test endpoint implementation (from [Baeldung](https://www.baeldung.com/spring-rest-http-headers#2-all-at-once)):

```java
@GetMapping("/test")
public ResponseEntity<Void> test(@RequestHeader Map<String, String> headers) {
    // Log each header and return OK
    headers.forEach((key, value) -> {
        log.info(String.format("Header '%s' = %s", key, value));
    });
    return ResponseEntity.ok().build();
}
```

The route can then be called (provided the DNS config is correct, see #4825) using `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test` and the backend service logs all received headers, from which `header1` and `header2` are not to be seen.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.12.20
```

### Anything else?

Maybe I am configuring this wrong, or Localstack has a special syntax. It looks like it works in "real" AWS with the same config. Thanks in advance for your help!
