### ISSUE TITLE
bug: API-Gateway-v2 does not recognize {proxy} and {proxy+} placeholders

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#4954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When configuring a route and integration for my local setup, I am unable to use the variables `{proxy}` and `{proxy+}`. The API-Gateway seems unable to reach the application with the correct path and I get back the following response, which looks like a Spring-Boot default response for undefined endpoints:

```json
{
    "timestamp": "2021-11-18T14:41:42.157+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/%7Bproxy%7D"
}
```

The following log-entry also shows up:

```
2021-11-18T14:41:42.073:WARNING:localstack_ext.services.apigateway.invocations: Unexpected mismatch of API GW invocation path '/' and routeKey path '/{proxy+}'
```

See steps to reproduce below

### Expected Behavior

I would expect Localstack to correctly route every call to the corresponding path according to the defined behavior of the greedy path variable (see docs [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html) and [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html)).

When using the "real" AWS in a Terraform setup, this works without problems:
* the route-key is `ANY /{proxy+}`
* the integration-URI is `https://backend-service.example/{proxy}`
* every request to the API-Gateway is redirected to `backend-service.example` with the same resource path

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:latest  # sha256:7ce018759cab08645cef064c7a694f36d6b5a1d71dd33fbcf9915196d631ca1f 
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of localstack.env:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=0
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
EAGER_SERVICE_LOADING=1
DNS_SERVER=127.0.0.11
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following setup, `backend-service` is a Spring-Boot application running in a container on the same Docker-Compose setup that exposes multiple endpoints, from which `GET /test` just returns a HTTP-200 response.

Locastack setup:

```bash
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create the integration for all endpoints, save ID for route creation
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --payload-format-version=2.0 --integration-method=GET --integration-uri=http://backend-service:9010/{proxy}
# Add route using the greedy path variable
awslocal apigatewayv2 create-route --api-id=my-api --route-key="ANY /{proxy+}" --target=integrations/005f9269  # replace ID here
```

Calling `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test` triggers the above-mentioned bug.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest (published Nov. 18, 14:20 UTC)
```

### Anything else?

Maybe I'm using the API wrong, or I missed an explanation somewhere in the docs or perhaps Localstack does not support this at all? Either way, thanks in advance for the help.
