### ISSUE TITLE
bug: API-Gateway-v2 returns wrong HTTP status codes

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#4990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When making a request to an endpoint in my local setup, I get HTTP status codes that don't match the ones that the backend service actually returned. A few examples:
* 404 --> 200, the response body is correct (the JSON I configured for 404 responses) but the status is wrong
* 400 --> 200, the response body is correct (the JSON I configured for bad requests) but the status is wrong
* 200 --> 503, I have a case with a big (>500KB) response body, and the response body gets lost in addition to the wrong status

Also, the manual overwriting of HTTP status codes using `--response-parameters` when creating the integration does not seem to work; all my tries have resulted in these parameters being ignored.

See steps to reproduce below

### Expected Behavior

I would expect the API-Gateway-v2 to transmit the HTTP-status codes correctly and (when defined) the response-parameters to work (as per AWS docs [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html) and [here](https://docs.aws.amazon.com/cli/latest/reference/apigatewayv2/create-integration.html).

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:latest  # sha256:777fe6d04edb081b3234b2eb613c473c3f64e39324419188fb4cb61f733e40c4
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of `localstack.env`:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=1
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
EAGER_SERVICE_LOADING=1
DNS_SERVER=127.0.0.11
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following setup, `backend-service` is a Spring-Boot application running in a container on the same Docker-Compose setup that exposes multiple endpoints, that can give diverse responses with diverging HTTP-status.

Localstack setup:

```bash
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create the integration for all endpoints, save ID for route creation
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --payload-format-version=2.0 --integration-method=GET --integration-uri=http://backend-service:9010/{proxy}
# Add route using the greedy path variable
awslocal apigatewayv2 create-route --api-id=my-api --route-key="ANY /{proxy+}" --target=integrations/06c7f8b4  # replace ID here
```

When we call a non-existing endpoint, for example `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test`, we get the same body as if we called the backend service directly:

```json
{
    "timestamp": "2021-11-23T14:27:17.939+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/test"
}
```

but the HTTP status of the response is **200**, whereas it should be **404** (when calling the service directly). Other mismatches and errors appear as mentioned in the first paragraph.

Also, the parameter `--response-parameters` in `create-integration` seems to have no effect: I tried adding things like: `'{"200": {"overwrite:statuscode": "201"}, "404": {"overwrite:statuscode": "418"}}'` but it makes absolutely no difference.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: Docker Hub latest (Nov 23)
```

### Anything else?

Thanks for the support!
