### ISSUE TITLE
bug: list-metrics returns only first record

### ISSUE THREAD

**Issue by ondrejkouril** [localstack/localstack#5000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

list-metrics doesn't list multiple metrics within the same instance

### Expected Behavior

`aws --endpoint-url=http://localhost:4566 cloudwatch list-metrics` should list all metrics from all instances

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Create ec2 instance `aws --endpoint-url=http://localhost:4566 ec2 run-instances --region us-east-1`
Create 2 metrics
`aws --endpoint-url=http://localhost:4566 cloudwatch put-metric-data --namespace "AWS/EC2" --metric-name "CPUUtilization" --dimensions InstanceId=i-46cdcd06a11207ab3 --value 15`
`aws --endpoint-url=http://localhost:4566 cloudwatch put-metric-data --namespace "AWS/EC2" --metric-name "Memory" --dimensions InstanceId=i-46cdcd06a11207ab3 --value 30`
List metrics `aws --endpoint-url=http://localhost:4566 cloudwatch list-metrics`

docker-compose.yml
```
version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=ec2,cloudwatch,lambda,s3
      - AWS_DEFAULT_REGION=us-east-1
      - PORT_WEB_UI=9080
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
```

### Environment

```markdown
- OS: Windows 20H2 19042.1237
- LocalStack: 0.12.20
```
