### ISSUE TITLE
bug: API-Gateway-v2 ignores Authorizer when using {proxy} in Route

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#5040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using API-Gateway-v2 to forward HTTP-Calls to a backend service. It uses a lambda authorizer that provides some information to extend the request headers before forwarding to the service.

When using `{proxy}` in the route definition (as opposed to explicitly mapping one path, like `GET /test`), the authorizer gets skipped and the request is directly sent to the backend service. This is problematic because the service is lacking necessary information that would have been added using the authorizer response.

For example, with a simple lambda function as authorizer that always says yes, like such:

```python
def lambda_handler(event, context):
    return json.dumps({"isAuthorized": True, "context": {"someKey": "someValue"}})
```

If I configure the integration with the following argument:

```
--request-parameters '{ "overwrite:header.myHeader": "$context.authorizer.someKey" }'
```

Then the header `myHeader` arrives to the backend service as `$.context..authorizer.someKey` instead of `someValue`.

Furthermore, if the authorizer is changed to always saying no, nothing changes.

Full setup and steps to reproduce below.

### Expected Behavior

The API-Gateway should never just "skip" the authorizer if one is configured.

It works in the "real" AWS and it also works in Localstack when an explicit route is set (like `GET /test` and integration to `/test` instead of `GET /proxy` and integration to `/{proxy+}`). Unfortunately, setting the route without those variables is not an option for my use-case.

Also, I remember this having worked in the past week or so.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:latest  # sha256:147c0885d14be21af0b147f245b790ae5e2f9a7fbf41a6f1e11d660732a4db47
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of `localstack.env`:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=1
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
EAGER_SERVICE_LOADING=1
DNS_SERVER=127.0.0.11
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following steps, a valid ZIP-file for a lambda function (see example in first paragraph) has been mounted to `/opt/code/lambda_import/my-function.zip` in the Localstack container.

The container `backend-service` is a Spring-Boot web server that exposes diverse endpoints, including a `/test` endpoint which is used to print the received headers to the console, like such:

```java
@GetMapping("/test")
public ResponseEntity<Void> test(@RequestHeader Map<String, String> headers) {
    // Log each header and return OK
    headers.forEach((key, value) -> {
        log.info(String.format("Header '%s' = %s", key, value));
    });
    return ResponseEntity.ok().build();
}
```

Localstack setup:

```bash
# Create API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create Stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create the integration to our backend service (remember ID for later)
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --payload-format-version=2.0 --integration-method=GET --integration-uri=http://backend-service:9010/{proxy} --request-parameters '{ "overwrite:header.myHeader": "$context.authorizer.someKey" }'
# Create a lambda function that will be our authorizer
awslocal lambda create-function --function-name=my-authorizer --zip-file=fileb:///opt/code/lambda_import/my-function.zip --role=test-role --handler=handler.lambda_handler --runtime=python3.8
# Create authorizer from the lambda function (remember ID for later)
awslocal apigatewayv2 create-authorizer --api-id=my-api --authorizer-type=REQUEST --authorizer-uri=arn:aws:lambda:eu-central-1:000000000000:function:my-authorizer --authorizer-payload-format-version=2.0 --enable-simple-responses --identity-source '$request.header.Authorization' --name=LambdaAuthorizer
# Finally, create the route to the integration over the authorizer
awslocal apigatewayv2 create-route --api-id=my-api --route-key="GET /{proxy+}" --authorization-type=CUSTOM --authorizer-id=c9ab2c48 --target=integrations/38bf9355 # replace IDs here
```

Calling the test endpoint with `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test` triggers the above-mentioned problem.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest (Nov 30)
```

### Anything else?

Thanks for the support!
