### ISSUE TITLE
Bug: Unable to add user defined environment variables using compose file

### ISSUE THREAD

**Issue by santoshpavan** [localstack/localstack#5043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to add extra user defined environment variables in the compose file under the `environment` section, they do not seem to get added.

I am printing the os environment variables in the lambda that is running through the localstack.

Specifically, I am trying to use a variable called `IS_JENKINS` (mentioned in the Steps to reproduce section) to determine which environment it is running in, but when I print the environment variables, it does not show up.

**Note**: One important thing to note here is that I have other services as part of the docker compose file which have the environment section populated. For these services, when I print the os environment variables, I can see these variables.

### Expected Behavior

When I print the environment variables in the services, the environment variables set in the docker compose file under the localstack service should be showing up.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. The command that I am using to run the compose - ```
docker-compose -f docker-compose.prod.yml up --abort-on-container-exit --exit-code-from integration_test```
2. The docker compose prod file contains the below -
```yaml
version: '3'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=${DATA_DIR- }
      - SERVICES=serverless, sqs, events, lamda, cloudformation, s3
      - LAMBDA_EXECUTOR=docker
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - HOST_TMP_FOLDER=${TMPDIR}
      - HOSTNAME_EXTERNAL=localstack
      - IS_JENKINS=True
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
The `IS_JENKINS` is the user defined env variable.
The `integration_test` service (not included in the compose file) just runs the pytest with the `environment` section that includes `IS_JENKINS` variable, which successfully does show up when I print the environment variables.

### Environment

```markdown
- OS: MacOS Big Sur v11.6
- LocalStack: latest
```

### Anything else?

**Context**
I am using Localstack for integration tests to run locally and as part of the Jenkins pipeline.

I use boto3 client in a lambda. So, I am looking to use custom environment variables as part of the `environment` section in the localstack service to determine which environment the lambda is running in and to use the appropriate end_point parameter in the boto3 client.

The docker-compose code is as below
```yaml
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=${DATA_DIR- }
      - SERVICES=serverless, sqs, events, lamda, cloudformation, s3
      - LAMBDA_EXECUTOR=docker
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - HOST_TMP_FOLDER=${TMPDIR}
      - HOSTNAME_EXTERNAL=localstack
      - IS_JENKINS=True
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
The user defined env variable here is `IS_JENKINS=True`.

I am printing the environment variables in the lambda to see if the variables show up.
