### ISSUE TITLE
Java KPL can not publish events to Kinesis

### ISSUE THREAD

**Issue by roek5803** [localstack/localstack#507]
Hi! 
I just started to use localstack and faced a problem when publishing events with Java kinesis producer library.
Consuming events works fine and publishing events through nodejs kinesis producer library works fine.

I start localstack with docker-compose with the following code:

```
aws:
    image: localstack/localstack:latest
    ports:
      - "4569:4569"
      - "4568:4568"
      - "4582:4582"
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev
      DEFAULT_REGION: eu-central-1
```

This is how i create the KinesisProducer in Java
```
KinesisProducerConfiguration producerConfig = new KinesisProducerConfiguration()
                .setRegion("eu-central-1")
                .setKinesisEndpoint("localhost")
                .setKinesisPort(4568)
                .setCloudwatchEndpoint("localhost")
                .setCloudwatchPort(4582)
                .setVerifyCertificate(false)
                .setCredentialsProvider(credentialsProvider)
                .setMaxConnections(1)
                .setRequestTimeout(60000)
                .setRecordMaxBufferedTime(15000);

producer = new KinesisProducer(producerConfig);
```

Then i set some environment variables when starting the JVM:
```
AWS_ACCESS_KEY_ID=dev;
AWS_SECRET_ACCESS_KEY=dev;
AWS_CBOR_DISABLE=true
```

And here is the output:
```
INFO  [2017-12-12 12:35:10,828] com.amazonaws.services.kinesis.producer.LogInputStreamReader: [2017-12-12 13:35:10.828402] [0x00002554][0x00007f63963d1700] [info] [kinesis_producer.cc:197] Created pipeline for stream "test_stream"
INFO  [2017-12-12 12:35:10,828] com.amazonaws.services.kinesis.producer.LogInputStreamReader: [2017-12-12 13:35:10.828512] [0x00002554][0x00007f63963d1700] [info] [shard_map.cc:79] Updating shard map for stream "test_stream"
ERROR [2017-12-12 12:35:10,835] com.amazonaws.services.kinesis.producer.LogInputStreamReader: [2017-12-12 13:35:10.834866] [0x00002554][0x00007f63923c8700] [error] [AWS Log: ERROR](CurlHttpClient)Curl returned error code 35
ERROR [2017-12-12 12:35:10,835] com.amazonaws.services.kinesis.producer.LogInputStreamReader: [2017-12-12 13:35:10.834976] [0x00002554][0x00007f63923c8700] [error] [shard_map.cc:150] Shard map update for stream "test_stream" failed. Code:  Message: Unable to connect to endpoint; retrying in 1000 ms
```

This code is tested on AWS and should work, but not with localstack unfortunately.
Any ideas what it could be?

**Comment by whummer** [comment]
Thanks for reporting @roek5803 . My assumption would be that the KPL is trying to connect via TLS, whereas LocalStack by default starts up the services in plain HTTP.

Apparently there is no way to disable TLS: https://github.com/awslabs/amazon-kinesis-producer/blob/master/java/amazon-kinesis-producer/src/main/java/com/amazonaws/services/kinesis/producer/KinesisProducerConfiguration.java#L978-L979
```
     * Note this does not accept protocols or paths, only host names or ip addresses. There is no
     * way to disable TLS. The KPL always connects with TLS.
```

Which means that you will need to start LocalStack with the `USE_SSL` option:
```
    environment:
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev
      DEFAULT_REGION: eu-central-1
      USE_SSL: true
```
... and then disable certificate verification (because the certs are generated locally for testing)
```
                ...
                .setRecordMaxBufferedTime(15000)
                .setVerifyCertificate(false);
```

Hope that helps

**Comment by roek5803** [comment]
Thanks for the fast respond @whummer 

I added the "USE_SSL" environment to my docker-compose file like this:
```
  aws:
    image: localstack/localstack:latest
    ports:
      - "4569:4569"
      - "4568:4568"
      - "4582:4582"
      - "9000:8080"
    environment:
      AWS_ACCESS_KEY_ID: dev
      AWS_SECRET_ACCESS_KEY: dev
      DEFAULT_REGION: eu-central-1
      USE_SSL: "true"
```

But then i get another error. Now it seems like i can't talk to dynamo instead. 

Output:
```
! org.apache.http.NoHttpResponseException: The target server failed to respond
...
! Causing: com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
```

This happens when i try to create a dynamoDB table.

This is how i create the AmazonDynamoDB client:
```
client = AmazonDynamoDBClientBuilder.standard()
                .withEndpointConfiguration(
                        new AwsClientBuilder.EndpointConfiguration("http://localhost:4569", "eu-central-1")
                )
                .build();
```

And here i send the request with the client
```
client.createTable(createTableRequest);
```

Am i missing something?

**Comment by roek5803** [comment]
I got this to work by starting kinesalite and dynalite locally

```
kinesalite --ssl true --port 4567
dynalite --port 4568
```

added ```127.0.0.1 kinesalite``` to my /etc/hosts file

disable CBOR with environment variable:
```
AWS_CBOR_DISABLE: true
```

And when i starting the application i do it with 
```
java -Dcom.amazonaws.sdk.disableCertChecking
```
This makes the AWS KCL to not verify the SSL certificate

This also works with localstack.

**Comment by apurvajoshi** [comment]
I got this to work without needing to update /etc/hosts file. For future folks:
I am using KCL version 1.8.8 and KPL version 0.12.8
My docker-compose file looks like following: 
```
aws:
    image: localstack/localstack:latest
    ports:
      - "3569:4569"
      - "3568:4568"
      - "9000:8080"
    environment:
      - AWS_ACCESS_KEY_ID=dev
      - AWS_SECRET_ACCESS_KEY=dev
      - DEFAULT_REGION=us-east-1
      - AWS_CBOR_DISABLE=true
      - USE_SSL=true
```
I am starting the consumer and producer by passing in the JVM option 
```-Dcom.amazonaws.sdk.disableCertChecking``` as @roek5803 mentioned above

KPL configuration:
```
KinesisProducerConfiguration producerConfig = new KinesisProducerConfiguration()
                .setCredentialsProvider(config.getAWSCredentials())
                .setKinesisEndpoint("localhost")
                .setKinesisPort(3568)
                .setVerifyCertificate(false)
                .setRegion(config.getAwsRegion());
```
(KPL does not allow specifying port as part of the Kinesis endpoint) 

KCL configuration:
```
KinesisClientLibConfiguration clientConfig =
                new KinesisClientLibConfiguration(
                        "test-consumer",
                        "mystream",
                        config.getAWSCredentials(),
                        workerId)
                        .withInitialPositionInStream(config.getInitialPositionInStream())
                        .withKinesisEndpoint("localhost:3568");
```
Hope that helps!
