### ISSUE TITLE
bug: Failing to deploy CloudFormation stack using AWS CLI with "No updates are to be performed" on localstack even when using --no-fail-on-empty-changeset

### ISSUE THREAD

**Issue by EvrenJG** [localstack/localstack#5104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to use the AWS CLI to deploy a CloudFormation stack on a local docker-hosted instance of localstack:

```aws cloudformation deploy --endpoint http://localhost:4566 --stack-name localBootstrap --template-file localstack-bootstrap-cf.yaml --no-fail-on-empty-changeset```

I would like this to be repeatable, i.e:

 - Create the stack if it doesn't exist
 - update it if I modify the yaml file
 - Do nothing if the stack exists and the file hasn't changed

The last scenario fails me, i.e. I'd expect the `--no-fail-on-empty-changeset` to cater for this case, but if I recreate my docker image then run the above command **twice** in a row, the first run works as expected but on the second run I get the following failure in the docker logs:

```
2021-12-09T13:29:03.362:DEBUG:localstack.services.cloudformation.cloudformation_api: Executing change set "arn:aws:cloudformation:eu-west-1:000000000000:changeSet/awscli-cloudformation-package-deploy-1639056542/ee700101" for stack "localBootstrap" with 2 resources ...

2021-12-09T13:29:03.363:INFO:localstack.utils.cloudformation.template_deployer: Unable to apply change set awscli-cloudformation-package-deploy-1639056542: No updates are to be performed.
```

And the following error on my CLI:
```
Unable to parse response (syntax error: line 1, column 54), invalid XML received. Further retries may succeed:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the ser
ver is overloaded or there is an error in the application.</p>\n'
```

On the localstack side of things, this seems like an issue that was previously raised and apparently fixed: https://github.com/localstack/localstack/issues/2444 ?

Is this expected behaviour?

### Expected Behavior

Expecting a cloudformation yaml template to be deployed in an idempotent manner when using --no-fail-on-empty-changeset

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose:

```
version: '3.9'

services:
  localstack:
    container_name: ${COMPOSE_PROJECT_NAME?}-localstack
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=cloudformation,s3,secretsmanager,dynamodb,sts,kms
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws cloudformation deploy --endpoint http://localhost:4566 --stack-name localBootstrap --template-file localstack-bootstrap-cf.yaml --no-fail-on-empty-changeset
aws cloudformation deploy --endpoint http://localhost:4566 --stack-name localBootstrap --template-file localstack-bootstrap-cf.yaml --no-fail-on-empty-changeset

This is the template file:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bootstrapper to deploy DynamoDB and State Bucket for Terraform, State bucket for serverless app deployment.'
Parameters:
  Environment:
    Type: String
    Default: localstack
    Description: 'The Environment to deploy to - will be used as a prefix for resources created.'
    AllowedValues:
      - 'local'
      - 'localstack'
  ProjectName:
    Type: String
    Default: myprojectname
    Description: 'The project name to prefix all resources with.'
Resources:
  TerraformStateS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'terraform-state'
      VersioningConfiguration:
        Status: 'Enabled'
  TerraformStateDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: terraform-locks
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
```

### Environment

```markdown
- OS: Windows 10 20H2
- LocalStack:
LocalStack version: 0.13.1
LocalStack Docker container id: 00c2c23f3b21
LocalStack build date: 2021-12-09
LocalStack build git hash: 15d20e1c
- AWS CLI: 2.4.5.0 (latest as of 2021-12-09)
```
