### ISSUE TITLE
Terraform EKS module not working with Local Stack Pro

### ISSUE THREAD

**Issue by nmofonseca** [localstack/localstack#5126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using terragrunt/terraform with Local Stack Pro trial to test an EKS cluster with managed node groups but it always fails when creating the node group.

My code is using Terraform EKS module:  https://github.com/terraform-aws-modules/terraform-aws-eks 

Local Stack is running on a "remote" server, not in my local laptop/desktop

```log
module.eks.module.node_groups.aws_eks_node_group.workers["workers"]: Creating...
module.eks.module.node_groups.aws_eks_node_group.workers["workers"]: Creation complete after 0s [id=wtw-devops-cluster:wtw-devops-cluster-workers20211214163943755100000011]
╷
│ Error: "url" has to use HTTPS scheme (i.e. begin with https://)
│ 
│   with module.eks.aws_iam_openid_connect_provider.oidc_provider[0],
│   on .terraform/modules/eks/irsa.tf line 15, in resource "aws_iam_openid_connect_provider" "oidc_provider":
│   15:   url             = local.cluster_oidc_issuer_url
│ 
╵
╷
│ Error: couldn't find resource
│ 
```

### Expected Behavior

EKS cluster  to be successfully applied.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml:

```yaml
---
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"                # only required for Pro
      - "53:53/udp"            # only required for Pro
      - "443:443"              # only required for Pro
      - "4510-4530:4510-4530"  # only required for Pro
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - EDGE_BIND_HOST=${EDGE_BIND_HOST:-0.0.0.0}
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

DEBUG=1
EDGE_BIND_HOST= 0.0.0.0

#### Terragrunt/ Terraform config ###

```hcl
generate "provider.tf" {
  path = "provider.tf"
  if_exists = "overwrite"
  contents = <<EOF
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  access_key = "test"
  secret_key = "test"
  region  = "us-east-1"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {

    acm            = "http://myservername:4566"
    eks            = "http://myservername:4566"  
    apigateway     = "http://myservername:4566"
    cloudformation = "http://myservername:4566"
    cloudwatch     = "http://myservername:4566"
    dynamodb       = "http://myservername:4566"
    es             = "http://myservername:4566"
    firehose       = "http://myservername:4566"
    iam            = "http://myservername:4566"
    kinesis        = "http://myservername:4566"
    lambda         = "http://myservername:4566"
    route53        = "http://myservername:4566"
    redshift       = "http://myservername:4566"
    s3             = "http://myservername:4566"
    secretsmanager = "http://myservername:4566"
    ses            = "http://myservername:4566"
    sns            = "http://myservername:4566"
    sqs            = "http://myservername:4566"
    ssm            = "http://myservername:4566"
    stepfunctions  = "http://myservername:4566"
    sts            = "http://myservername:4566"
    ec2            = "http://myservername:4566"
  }  

}
EOF
}
```

### Environment

```markdown
- OS: Ubuntu 18.04.6 LTS
- LocalStack: 0.13.0.10
- Docker version: 20.10.7
- Docker Compose v2: v2.0.1
```

### Anything else?

Docker compose logs:

```log
localstack_main  | 2021-12-14T16:38:17.085:DEBUG:localstack.utils.run: Executing command: ['/tmp/localstack/k3d.linux.bin', 'cluster', 'create', 'mycluster', '--api-port', '6443', '-p', '8081:80@loadbalancer']
localstack_main  | 2021-12-14T16:38:37.528:DEBUG:localstack.utils.run: Executing command: ['/tmp/localstack/k3d.linux.bin', 'kubeconfig', 'write', 'mycluster', '-o', '-']
localstack_main  | 2021-12-14T16:38:38.416:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /var/lib/localstack/cache/server.test.pem (5159 bytes)
localstack_main  | 2021-12-14T16:38:38.420:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total bytes 7571
localstack_main  | [2021-12-14 16:38:38 +0000] [22] [INFO] Running on https://0.0.0.0:4512 (CTRL + C to quit)
localstack_main  | 2021-12-14T16:38:38.429:INFO:hypercorn.error: Running on https://0.0.0.0:4512 (CTRL + C to quit)
localstack_main  | 2021-12-14T16:38:38.931:DEBUG:localstack_ext.services.eks.k8s_utils: Waiting for connectivity on EKS load balancer from container: https://172.17.0.1:8081
localstack_main  | 2021-12-14T16:39:31.961:WARNING:localstack_ext.services.eks.eks_api: Node group "mycluster-workers20211214163943755100000011" for cluster mycluster not found
localstack_main  | 2021-12-14T16:39:32.001:WARNING:localstack_ext.services.eks.eks_api: Node group "mycluster-workers20211214163943755100000011" for cluster mycluster not found
```
