### ISSUE TITLE
bug: Error when calling aws cloudwatch get-metric-statistics

### ISSUE THREAD

**Issue by sergey-morenets** [localstack/localstack#5134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to get metrics statistics I receive the following response:

`An error occurred (InternalFailure) when calling the GetMetricStatistics operation: API action 'POST /' for service 'monitoring' not yet implemented`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

docker-compose.yml:

```
version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,s3,sns,sqs,kms,lambda,cloudformation,cloudwatch
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   aws s3 mb s3://items --endpoint-url=http://localhost:4566
  aws cloudwatch get-metric-statistics --namespace AWS/S3 --metric-name NumberOfObjects --start-time 2021-06-19T04:00:00Z --end-time 2022-06-19T04:30:00Z --period 60 --endpoint-url=http://localhost:4566

### Environment

```markdown
- OS: Windows 10
- LocalStack: 0.13.1
```
