### ISSUE TITLE
bug: docker version hangs on creation of lambda container in macOS

### ISSUE THREAD

**Issue by vittoriozamboni** [localstack/localstack#5140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the cluster has been setup with `docker-compose up`, I try to invocate one (typescript) lambda function but the creation of the container is blocked. Sometimes it takes around 3/4 minutes to create the container and sometimes it hangs forever. 
Whenever it succeed, I get `listen tcp :9001: bind: address already in use`.

```log
localstack_1  | 2021-12-17T09:19:22.624:INFO:localstack.services.awslambda.lambda_executors: Running lambda: arn:aws:lambda:eu-west-1:000000000000:function:local_get_products
localstack_1  | 2021-12-17T09:19:22.624:DEBUG:localstack_ext.services.awslambda.lambda_launcher: Executing docker-reuse Lambda container invocation
localstack_1  | 2021-12-17T09:19:22.624:DEBUG:localstack_ext.services.awslambda.lambda_launcher: Executing docker-reuse Lambda container invocation
localstack_1  | 2021-12-17T09:19:23.846:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:local_get_products: Lambda process returned with error. Result: . Output:
localstack_1  | 2021/12/17 09:19:23 listen tcp :9001: bind: address already in use Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 610, in run_lambda_executor
localstack_1  |     result, log_output = self.execute_in_container(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_launcher.py.enc", line 348, in docker_reuse_execute_in_container
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_launcher.py.enc", line 348, in docker_reuse_execute_in_container
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 807, in execute_in_container
localstack_1  |     return DOCKER_CLIENT.exec_in_container(
localstack_1  |   File "/opt/code/localstack/localstack/utils/docker_utils.py", line 1598, in exec_in_container
localstack_1  |     raise ContainerException(
localstack_1  | localstack.utils.docker_utils.ContainerException: ('Exec command returned with exit code 1', None, b'2021/12/17 09:19:23 listen tcp :9001: bind: address already in use\n')
localstack_1  |
localstack_1  | The above exception was the direct cause of the following exception:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 782, in run_lambda
localstack_1  |     result = LAMBDA_EXECUTOR.execute(
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 443, in execute
localstack_1  |     return do_execute()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 433, in do_execute
localstack_1  |     return _run(func_arn=func_arn)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 158, in wrapped
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 154, in wrapped
localstack_1  |     result = func(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 420, in _run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 416, in _run
localstack_1  |     result = self._execute(lambda_function, inv_context)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 869, in _execute
localstack_1  |     return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 725, in _execute
localstack_1  |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/awslambda/lambda_extended.py.enc", line 549, in run_lambda_executor
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 648, in run_lambda_executor
localstack_1  |     raise InvocationException(
localstack_1  | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: . Output:
localstack_1  | 2021/12/17 09:19:23 listen tcp :9001: bind: address already in use
```

### Expected Behavior

It should start the lambda docker container and run the lambda function.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

My `docker-compose.yml` file looks like this:

```yml
version: "3.8"

services:
  localstack:
    image: localstack/localstack
    networks:
      - localstack-catalog-sls
    ports:
      - "53:53" # only required for Pro
      - "53:53/udp" # only required for Pro
      - "443:443" # only required for Pro
      - "4510-4530:4510-4530" # only required for Pro
      - "4566:4566"
      - "4571:4571"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=iam,dynamodb,lambda,s3,cloudformation,appsync,secretsmanager,sts,cloudwatch,route53
      - MAIN_CONTAINER_NAME=localstack_ecommerce_catalog_sls
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LS_LOG=${LS_LOG- info}
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID- dev}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY- dev}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - REQUIRE_PRO=1
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - "${TMPDIR:-/tmp/}localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  localstack-catalog-sls:
    external: true
    name: localstack-catalog-sls
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

I am deploying with serverless: 

```yml
service: tc-catalog

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage,'local'}
  region: eu-west-1
  memorySize: 128
  timeout: 40
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: tc-deployment-bucket

package:
  excludeDevDependencies: true
  individually: true
  exclude:
    - ./**

functions:
  getProducts: ${file(src/resolvers/queries/getProducts/setting.yml):function}

custom:
  appSync:
    name: tc-api
    schema: schema.graphql
    authenticationType: API_KEY
    dataSources: ${file(src/resources/data-sources.yml)}
    mappingTemplatesLocation: src/resolvers
    mappingTemplates: ${file(src/resources/resolvers.yml)}
  localstack:
    stages:
      - local
    lambda:
      mountCode: false
    autostart: false
    networks:
      - host
      - overlay
    endpoints:
      AppSync: http://localhost:4605

plugins:
  - serverless-localstack
  - serverless-appsync-plugin
  - serverless-deployment-bucket
```

This are the commands I run:

```bash
export AWS_DEFAULT_REGION=eu-west-1
export LOCALSTACK_URL = http://localhost:4566
export APPSYNC_URL = $(LOCALSTACK_URL)/graphql

npm run build && sls deploy --stage local 

api_id=$$(aws --endpoint-url=$(LOCALSTACK_URL) appsync list-graphql-apis | jq -r '(.graphqlApis[] | select(.name=="tc-api")).apiId')
api_key=$$(aws --endpoint-url=$(LOCALSTACK_URL)  appsync create-api-key --api-id $$api_id | jq -r .apiKey.id)
curl -H "x-api-key: $$api_key" -d '{"query":"query {getProducts(query: {ids: [\"123)\"] }){id}}"}' $(APPSYNC_URL)/$$api_id 
```

### Environment

```markdown
- OS: macOS Big Sur 11.2.3
- LocalStack: 

localstack/localstack          latest       24c3aa835c44   19 hours ago   1.5GB
localstack/lambda              nodejs12.x   56164d99a509   6 days ago     401MB
```
```


### Anything else?

I tried the following, suggested by other issues:
- changing `LAMBDA_EXECUTOR` to `docker`
- restarting host container, docker server, the entire machine (multiple times)
- deleting the containers and the images and pull them again
- enabling and disabling mountCode
- enabling and disabling temp folder (and deleting old files in it)
- switching `Use gRPC FUSE for file sharing`
- bumping RAM for docker (i.e. 6Gb)
- using node14 instead of node12
- use "latest" tag (I installed all a week ago so I am not using an old version)
- use localstack-full
