### ISSUE TITLE
When I trigger an alarm, the message is not sent to an sns-topic

### ISSUE THREAD

**Issue by cnuval-itrs** [localstack/localstack#5150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behavior, I am not receiving any alarms triggered from the cloudwatch alarms. 

### Expected Behavior

Upon triggering an alarm, cloudwatch alarms should trigger an alarm and send in the SNS topic.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    TMPDIR=/private$TMPDIR docker-compose -f localstack-geneos.yml up

compose files looks like this
```
version: "3.9"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    networks:
      - frontend
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
      
    environment:
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/Users/cnuval/Work/localstacktemp
      - PORT_WEB_UI=9000
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/Users/cnuval/Work/s3local:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  linux:
    image: azure:1.0
    container_name: azure
    networks:
      - frontend
    volumes:
      - /Users/cnuval/Work/:/home/jenkins/Work
    ports: 
      - "15000-15100:15000-15100"
      - "20000:20000"
      - "8080:8080"
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1.  Create a topic
```awslocal sns create-topic --name webhooks-site-1 --region=us-east-1
{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:webhooks-site-1”
}
```
2. Create a subscription. I have used webhooks site to check the payloads
```awslocal --region=us-east-1 sns subscribe --topic-arn=arn:aws:sns:us-east-1:000000000000:webhooks-site-1 --protocol=https --notification-endpoint https://webhook.site/02f44e3f-138d-493f-95d6-b12bc835608a```

3. Create an alarm based on the topic created in step 1
```awslocal cloudwatch put-metric-alarm --region=us-east-1 --alarm-name webhooks-site-1-alarm --alarm-description "Alarm when CPU exceeds 50 percent" --metric-name CPUUtilization --namespace AWS/EC2 --statistic Average --period 300 --threshold 50 --comparison-operator GreaterThanThreshold --dimensions "Name=InstanceId,Value=i-0317828c84edbe100" --evaluation-periods 1 --alarm-actions arn:aws:sns:us-east-1:000000000000:webhooks-site-1  --ok-actions arn:aws:sns:us-east-1:000000000000:webhooks-site-1  --unit Percent --actions-enabled```

4. Set an alarm.
```awslocal cloudwatch set-alarm-state --state-reason "Threshold crossed" --alarm-name webhooks-site-1-alarm --state-value ALARM
awslocal cloudwatch set-alarm-state --state-reason "Threshold crossed" --alarm-name webhooks-site-1-alarm --state-value ALARM```

### Environment

```markdown
- OS: MacOS Monterey 12.0.1
- LocalStack: 
localstack_main | LocalStack version: 0.13.1
localstack_main | LocalStack Docker container id: 3edcbb735ef4
localstack_main | LocalStack build date: 2021-12-19
localstack_main | LocalStack build git hash: eaba2be8
```

### Anything else?

Also, I've also tested publishing message , which is successful 
```awslocal sns publish --message "test message - nuvs" --topic-arn arn:aws:sns:us-east-1:000000000000:webhooks-site-1```

Which results into:
```
{
  "Type": "Notification",
  "MessageId": "d93a45b1-50a2-43be-bb54-b01ec46cbf38",
  "TopicArn": "arn:aws:sns:us-east-1:000000000000:webhooks-site-1",
  "Message": "test message - nuvs",
  "Timestamp": "2021-12-20T10:50:09.356Z",
  "SignatureVersion": "1",
  "Signature": "EXAMPLEpH+..",
  "SigningCertURL": "https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem",
  "UnsubscribeURL": "http://localhost:4566/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:000000000000:webhooks-site-1:db23421a-7882-4a07-b7f2-9a1aaac2ee01"
}
```
