### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by dtelaroli** [localstack/localstack#5264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Trying enable secrets rotation**

```bash
awslocal secretsmanager rotate-secret \
    --secret-id arn:aws:secretsmanager:sa-east-1:000000000000:secret:my-secret-mrUQmq \
    --rotation-lambda-arn arn:aws:lambda:sa-east-1:000000000000:function:my-function \
    --rotation-rules AutomaticallyAfterDays=10
```
I get this error:
`An error occurred (ResourceNotFoundException) when calling the RotateSecret operation: Resource not found for ARN 'arn:aws:lambda:sa-east-1:000000000000:function:my-function'.`

**But the rotation looks enabled**

```bash
awslocal secretsmanager describe-secret --secret-id my-secret
```

```json
{
    "ARN": "arn:aws:secretsmanager:sa-east-1:000000000000:secret:my-secret-mrUQmq",
    "Name": "my-secret",
    "Description": "",
    "RotationEnabled": true,
    "RotationLambdaARN": "arn:aws:lambda:sa-east-1:000000000000:function:my-function",
    "RotationRules": {
        "AutomaticallyAfterDays": 10
    },
    "Tags": [],
    "VersionIdsToStages": {
        "e3815589-280c-49de-9c04-61ea475ce3a7": [
            "AWSCURRENT"
        ],
        "a9be99c5-6a54-401d-a3d1-d46915b38bdf": [
            "AWSPENDING"
        ]
    }
}
```

### Expected Behavior

No error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
# DEBUG=1 docker-compose up

version: '3.1'

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    restart: on-failure
    ports:
      # - "127.0.0.1:53:53"                # only required for Pro
      # - "127.0.0.1:53:53/udp"            # only required for Pro
      # - "127.0.0.1:443:443"              # only required for Pro
      # - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=secretsmanager,ec2,sts,lambda,iam
      - DEBUG=${DEBUG-}
      # - DATA_DIR=${DATA_DIR-}
      - DATA_DIR=/private/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
awslocal secretsmanager create-secret \
--name my-secret \
--secret-string '{"key":"value"}'
```

```json
{
    "ARN": "arn:aws:secretsmanager:sa-east-1:000000000000:secret:my-secret-mrUQmq",
    "Name": "my-secret",
    "VersionId": "e3815589-280c-49de-9c04-61ea475ce3a7"
}
```

```bash
awslocal iam create-role \
--role-name role \
--assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Action":"sts:AssumeRole","Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"}}]}'
```

```json
{
    "Role": {
        "Path": "/",
        "RoleName": "role",
        "RoleId": "jboz4veok8wsqaj05n69",
        "Arn": "arn:aws:iam::000000000000:role/role",
        "CreateDate": "2022-01-12T19:19:49.606000+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "lambda.amazonaws.com"
                    }
                }
            ]
        },
        "MaxSessionDuration": 3600
    }
}
```

```bash
awslocal lambda create-function \
--function-name my-function \
--runtime nodejs12.x \
--role role \
--handler 'index.test' \
--zip-file fileb://lambda.zip
```

```json
{
    "FunctionName": "my-function",
    "FunctionArn": "arn:aws:lambda:sa-east-1:000000000000:function:my-function",
    "Runtime": "nodejs12.x",
    "Role": "role",
    "Handler": "index.test",
    "CodeSize": 337,
    "Description": "",
    "Timeout": 3,
    "LastModified": "2022-01-12T19:24:13.653+0000",
    "CodeSha256": "4Jp/nMvWr9wBA7U2EKjrvvlLyqnMNbf8HnDOXQY8Fkk=",
    "Version": "$LATEST",
    "VpcConfig": {},
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "1db55c64-f593-42e6-aeac-1f8bde9722f9",
    "State": "Active",
    "LastUpdateStatus": "Successful",
    "PackageType": "Zip"
}
```

```bash
awslocal lambda add-permission \
--function-name "my-function" \
--statement-id "allow-secrets-manager" \
--action "lambda:InvokeFunction" \
--principal "secretsmanager.amazonaws.com" \
--source-arn "arn:aws:secretsmanager:sa-east-1:000000000000:secret:my-secret-mrUQmq"
``` 

```json
{
    "Statement": "{\"Sid\": \"allow-secrets-manager\", \"Effect\": \"Allow\", \"Action\": \"lambda:InvokeFunction\", \"Resource\": \"arn:aws:lambda:sa-east-1:000000000000:function:my-function\", \"Condition\": {\"ArnLike\": {\"AWS:SourceArn\": \"arn:aws:secretsmanager:sa-east-1:000000000000:secret:my-secret-mrUQmq\"}}, \"Principal\": {\"Service\": \"secretsmanager.amazonaws.com\"}}"
}
```

```bash
awslocal secretsmanager rotate-secret \
    --secret-id arn:aws:secretsmanager:sa-east-1:000000000000:secret:my-secret-mrUQmq \
    --rotation-lambda-arn arn:aws:lambda:sa-east-1:000000000000:function:my-function \
    --rotation-rules AutomaticallyAfterDays=10
```

```bash
An error occurred (ResourceNotFoundException) when calling the RotateSecret operation: Resource not found for ARN 'arn:aws:lambda:sa-east-1:000000000000:function:my-function'.
```

### Environment

```markdown
- OS:ubuntu 20.04
- LocalStack: docker tag latest
```
