### ISSUE TITLE
How do I specify LOCATION in Athena  CREATE TABLE query?

### ISSUE THREAD

**Issue by mktktmr** [localstack/localstack#5267]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I'd like to create Athena table with a below query.

```sql
        CREATE EXTERNAL TABLE IF NOT EXISTS `database_name.table_name` (
          `column_name` varchar(255)
        )
        PARTITIONED BY (
          `partition_name` string
        )
        ROW FORMAT DELIMITED
          FIELDS TERMINATED BY '\t'
        STORED AS INPUTFORMAT
          'org.apache.hadoop.mapred.TextInputFormat'
        OUTPUTFORMAT
          'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
        LOCATION
          's3://bucket_name/table_name/'
        TBLPROPERTIES (
          'has_encrypted_data'='false',
          'skip.header.line.count'='1',
          'transient_lastDdlTime'='1635321440'
        )
```
However, LocalStack raises an error like below.

```
localstack_1  | TExecuteStatementResp(status=TStatus(statusCode=3,
 infoMessages=['*org.apache.hive.service.cli.HiveSQLException:Error while processing statement: FAILED: Execution Error,
 return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:Got exception: java.io.InterruptedIOException doesBucketExist on bucket_name: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 172.29.0.6:4566 [/172.29.0.6] failed: connect timed out):17:16',
 'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:380',
 'org.apache.hive.service.cli.operation.SQLOperation:runQuery:SQLOperation.java:257',
 'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:293',
 'org.apache.hive.service.cli.operation.Operation:run:Operation.java:320',
 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:530',
 'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:506',
 'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:280',
 'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:531',
 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1437',
 'org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1422',
 'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39',
 'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39',
 'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56',
 'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286',
 'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149',
 'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624',
 'java.lang.Thread:run:Thread.java:748',
 '*org.apache.hadoop.hive.ql.metadata.HiveException:MetaException(message:Got exception: java.io.InterruptedIOException doesBucketExist on ida-datalake-advertising-flow-test: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to 172.29.0.6:4566 [/172.29.0.6
] failed: connect timed out):27:11',
```

On the other hand, It is succeeded if I remove LOCATION statement from this query.

|'ve using LocalStack Pro (trial) with docker-compose and my doceker-compose.yml is like below.

```yaml
version: "3"
services:
  api:
    volumes:
      - "./:/usr/src:cached"
    depends_on:
      - mailer
      - gcs
      - localstack
    environment:
      SMTP_HOST: mailer
      SMTP_PORT: 1025
    env_file:
      - .env.develop
    privileged: true

  sidekiq:
    volumes:
      - "./:/usr/src:cached"
    depends_on:
      - mailer
    environment:
      SMTP_HOST: mailer
      SMTP_PORT: 1025
    env_file:
      - .env.develop

  mysql:
    ports:
      - ${EXPOSE_DB_PORT}:3306
    env_file:
      - .env.develop

  redis:
    env_file:
      - .env.develop

  web:
    volumes:
      - "./frontend:/usr/src:cached"
    env_file:
      - .env.develop
    environment:
      - "SERVER_API_URL=${SERVER_API_URL}"
    command: [sh, -c, "yarn && yarn run dev"]

  mailer:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

  localstack:
    image: localstack/localstack-full:latest
    ports:
      - "127.0.0.1:53:53"                # only required for Pro
      - "127.0.0.1:53:53/udp"            # only required for Pro
      - "127.0.0.1:443:443"              # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3,athena,glue
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  gcs:
    image: badturkey/fake-gcs-server-local:0.0.1
    ports:
      - 4443:4443

volumes:
  maildir: {}
```

I confirm existing the bucket.

```
$ awslocal s3 ls
2022-01-11 19:25:35 bucket_name
```

What is lack to specify s3 location?

If LocalStack does not support LOCATION statement to S3, how does LocalStack work with buckets?
