### ISSUE TITLE
Localstack sometimes fail to start

### ISSUE THREAD

**Issue by sebastien-roche-cko** [localstack/localstack#5278]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi guys,

My team and I we are facing an interesting problems. Some time to time, localstack failed to start and as a result we cannot contact `http://localhost:4566/health`

I have attached the full debut to this issue. It contains a `docker inspect` + `docker network ls`

Below is our simplified configuration

docker-compose-local.yml
```
  localstack:
    ports:
      - "4566:4566"
      # - "4571:4571"
    environment:
      # to add es
      - SERVICES=sqs,sns,dynamodb,lambda,s3,dynamodbstreams,iam
      - EDGE_BIND_HOST=0.0.0.0
      - EDGE_PORT=4566
      - DOCKER_BRIDGE_IP=172.23.0.1
      #- HOSTNAME=localstack           # required for AWS Lambda
      #- HOSTNAME_EXTERNAL=localstack  # required for overall networking (since default is localhost)
      - DEBUG=1
      #- SKIP_SSL_CERT_DOWNLOAD=1     # Issue after 0.12.8
      - LEGACY_PERSISTENCE=0
      # - DOCKER_HOST=unix:///var/run/docker.sock
      # ES
      # - ES_ENDPOINT_STRATEGY=off     # To support multi clusters, read this post: https://github.com/localstack/localstack/issues/4941
      # - ES_MULTI_CLUSTER=0
      # Lambda
      # - LAMBDA_EXECUTOR=docker-reuse
      # - LAMBDA_REMOVE_CONTAINERS=1
      # - LAMBDA_REMOTE_DOCKER=true
      # - LAMBDA_DOCKER_NETWORK=internal  # required for lambda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCALSTACK_SHARED_FOLDER}/localstack-data:/tmp/localstack-data
```
and docker-compose.yml
```
  localstack:
    build:
      context: ./docker-setup/localstack
    container_name: localstack
    networks:
      - internal

# NETWORK

networks:
  internal:
    name: internal
    ipam:
      config:
        - subnet: 172.23.0.0/16
```

From the logs I see the following issue
```
[16:46:34] :	 [Step 4/5] localstack  | Error starting infrastructure: gave up waiting for edge server on 0.0.0.0:4566 Traceback (most recent call last):
```

Setting `SKIP_SSL_CERT_DOWNLOAD=1` only hides the error but the container is still unavailable. 

Would have any idea what could be the root cause?

[debug.txt](https://github.com/localstack/localstack/files/7871957/debug.txt)

Thx
Seb
