### ISSUE TITLE
bug: API-Gateway-v2 refuses to map response parameters

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#5289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using an AWS-type integration (Lambda function) in API-Gateway-v2 (Pro Version), I cannot use the `$response.body` or `$response.headers` keys to define response parameter mapping. I've tried the following plausible variants from the [AWS-docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-parameter-mapping.html):
* `${response.body.some_key}` --> does not get interpreted (I get this exact text as mapped value)
* `$response.body.some_key` --> does not get interpreted, gets mapped to `$.response..body.some_key`
* `$response.headers.some_header` --> does not get interpreted, gets mapped to  `$.response..headers.some_header`

Interestingly, some `$context` keys seem to work. For example, `$context.requestId` or `$context.path` get mapped correctly to their respective values.

More details in the "Steps To Reproduce" section below.

### Expected Behavior

I would expect the `$response.body` or `$response.headers` keys to get mapped to their actual value, as they do in the "real" AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:0.13.3  # sha256:0f2acb9c21fa9181c9ccd0f02c6912a772fbf286171aa39e57bd4518b0fc4dbb
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of `localstack.env`:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=1
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
EAGER_SERVICE_LOADING=1
DNS_SERVER=127.0.0.11
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following setup, a valid ZIP-file for a Python lambda function has been mounted to /opt/code/lambda_import/my-function.zip in the Localstack container. The code of the lambda sums up to the following:

```python
def lambda_handler(event, context):
    return {
        "statusCode": 401,
        'headers': {'Content-Type': 'application/json', 'some_header': 'some_header_value'},
        "body": json.dumps({'some_key': 'some_value'})
    }
```

Localstack setup:

```bash
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
awslocal lambda create-function --function-name="my-function" --zip-file="fileb:///opt/code/lambda_import/my-function.zip" --role="test-role" --handler="handler.lambda_handler" --runtime="python3.8"
awslocal apigatewayv2 create-integration --api-id="my-api" --integration-type="AWS" --integration-uri="arn:aws:lambda:eu-central-1:000000000000:function:my-function" --response-parameters '{"401": {"overwrite:statuscode": "200", "overwrite:header.new_key": "$response.body.some_key"}}'
awslocal apigatewayv2 create-route --api-id="my-api" --route-key="GET /test" --target="integrations/19ee7ca1"
```

When calling `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test`, I get the wrong mapping mentioned above.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.13.3
```

### Anything else?

I could be using this just wrong, however it works with some mappings, so I have absolutely no idea where the problem lies.
