### ISSUE TITLE
bug: In S3 of localstack, PutObjectCommand generated by getSignedUrl becomes `Signatures do not match`

### ISSUE THREAD

**Issue by minakawa-daiki** [localstack/localstack#5320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```js
const {
    PutObjectCommand,
    S3Client,
} = require("@aws-sdk/client-s3");
const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

const main = async () => {
    const s3Client = new S3Client({
        endpoint: 'http://s3.localhost:4566/',
        credentials: {
            accessKeyId: 'test',
            secretAccessKey: 'test',
        },
    });

    const bucketParams = {
        Bucket: 'test-bucket',
        Key: 'test',
    };
    const command = new PutObjectCommand(bucketParams);
    const signedUrl = await getSignedUrl(s3Client, command, {
        expiresIn: 600, // 10min
    });

    console.log(signedUrl);
};

main().then().catch();
```

If you run the following curl with the `signedUrl` generated in the above code, `Signatures do not match, but not raising an error, as S3_SKIP_SIGNATURE_VALIDATION=1` will be thrown out as a log.

```sh
curl -X PUT -T "<file-path>" "http://test-bucket.s3.localhost:4566/test?<signdUrl-params>"
```

### Expected Behavior

Signatures does match.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4530:4510-4530"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

 aws s3 mb s3://test-bucket --endpoint-url=http://localhost:4566

### Environment

```markdown
- OS: macOS 12.1
- LocalStack: latest
```

### Anything else?

A signedUrl created using `GetObjectCommand` works fine.
