### ISSUE TITLE
bug: sqs initialization script doesn't work beyond localstack version 0.12.16

### ISSUE THREAD

**Issue by hhc97** [localstack/localstack#5352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For any localstack version >= `0.12.17`, the sqs queues are not available after the container starts up and runs the initialization script.

After starting the container, the following output occurs:
```
$ aws --endpoint-url=http://localhost:4566 sqs list-queues
$
```
Note that there is no queue url

### Expected Behavior

I expect that after starting my container, the queues show up when I list the queues:

```
$ aws --endpoint-url=http://localhost:4566 sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/test"
    ]
}
$
```
Note that this is what happens on `0.12.16`.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yml`

Using the Dockerfile:
```
services:
  local-sqs:
    container_name: localstack
    image: localstack/localstack:0.12.17
    environment:
      SERVICES: "sqs"
      AWS_DEFAULT_REGION: "us-east-1"
    ports:
      - '4566:4566'
    volumes:
      - ./local-sqs:/docker-entrypoint-initaws.d
```

Inside `local-sqs` I have the file `queues.sh` which has the following contents:
```
awslocal --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test

```

After starting up the container, running `aws --endpoint-url=http://localhost:4566 sqs list-queues` does not show me a list of urls of queues that have been created (see expected vs current above).

### Environment

```markdown
- OS: macOS Catalina 10.15.7
- LocalStack: the issue seems to be with localstack => 0.12.17
```
