### ISSUE TITLE
bug: IoT MQTT Broker fails when it receives binary messages

### ISSUE THREAD

**Issue by ccatterina** [localstack/localstack#5423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Send a binary message to the IoT MQTT Broker results in the following message:
```
2022-02-03T15:34:59.928:INFO:localstack_ext.services.iot.mqtt_utils: Unable to handle message from IoT MQTT topic "/foo/bar": 'utf-8' codec can't decode byte 0x8a in position 0: invalid start byte
```

### Expected Behavior

Binary messages should be handled by the MQTT Broker without errors.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
Docker compose file:
```yaml
version: '3.8'

services:
  localstack:
    container_name: 'localstack-test'
    image: localstack/localstack
    network_mode: bridge
    ports:
      - '127.0.0.1:443:443' # only required for Pro
      - '127.0.0.1:4510-4530:4510-4530'
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4571:4571'
    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-} # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DNS_ADDRESS=0
      - LOCALSTACK_HOSTNAME=127.0.0.1
    volumes:
      - 'localstack-data:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  localstack-data:
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
Send the following message using an mqtt client:
```
\x8a\xb5almost_full_indicator\xc2\xa9engine_on\xc2\xaefull_indicator\xc2\xadgeneric_alarm\xc2\xa8fullness\n\xa8position\xb345.547798;10.163617\xa8power_on\xc2\xa5speed\xc0\xb5working_hours_counter\n\xa4time\xcbBw\xec\x04\x905\xc21
```

### Environment

```markdown
- OS: MacOs Monterey
- LocalStack: latest
```
