### ISSUE TITLE
bug: Cannot verify SNS message signature

### ISSUE THREAD

**Issue by mahmoud-syr** [localstack/localstack#5454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Call `SubscribeAsync` within the service that is going to listen for SNS messages on an http-endpoint
2. Publish a message from another service
3. Call `Amazon.SimpleNotificationService.Util.Message.ParseMessage(content).IsMessageSignatureValid()`
4. An exception is thrown that certificate cannot be downloaded after three tries

Certificate Url provided is: `https://sns.us-east-1.amazonaws.com/SimpleNotificationService-0000000000000000000000.pem` despite the fact that the region locally configured is `eu-west-1`. 

Also visiting the link provided yield `<UnknownOperationException/>`

### Expected Behavior

Running localstack latest version with AWS SDK .NET latest version

1. Call `SubscribeAsync` within the service that is going to listen for SNS messages on an http-endpoint
2. Publish a message from another service
3. Call `Amazon.SimpleNotificationService.Util.Message.ParseMessage(content).IsMessageSignatureValid()`
4. Signature should be valid

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`docker-compose.yml`

```
  aws:
    image: localstack/localstack:latest
    restart: always
    volumes:
      - ./docker-mounts/localstack:/docker-entrypoint-initaws.d
    environment:
      - SERVICES=sqs:4566,s3,ses,sns
      - DEFAULT_REGION=eu-west-1
      - HOSTNAME_EXTERNAL=aws.localtest.local
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_DEFAULT_REGION=eu-west-1
    networks:
      localtest-front:
        aliases:
          - aws.localtest.local
      localtest-back:
        aliases:
          - aws.localtest.local

```

`docker-compose.override.yml`

```
  aws:
    mem_limit: 1024MB
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
      - "4574:4574"
```

Initialization file: 

`01-init_sns.sh`

```

#!/bin/sh

aws sns create-topic --name webhook-delivery-topic --endpoint-url=http://aws.localtest.local:4566
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Startup file -> ConfigureServices method:

```
var awsOptions = Configuration.GetAWSOptions();
if (Environment.IsDevelopment())
{
    awsOptions.Credentials = new BasicAWSCredentials("foo", "bar");
    awsOptions.DefaultClientConfig.AuthenticationRegion = "eu-west-1";
    awsOptions.DefaultClientConfig.ServiceURL = "http://aws.localtest.local:4566";
}

services.AddDefaultAWSOptions(awsOptions);
services.AddAWSService<IAmazonSimpleNotificationService>();
```

Startup file -> Configure method to initialize subscription:

```
using (var scope = app.ApplicationServices.CreateScope())
{
    var snsSrevice = scope.ServiceProvider.GetRequiredService<IAmazonSimpleNotificationService>();
    var notificationConfig = app.ApplicationServices.GetRequiredService<IOptions<NotificationConfiguration>>();
    var response = await snsSrevice.SubscribeAsync(notificationConfig.Value.Topic, notificationConfig.Value.NotificationProtocol, notificationConfig.Value.NotificationEndPoint);
    if (response.HttpStatusCode != System.Net.HttpStatusCode.OK)
    {
        logger.LogError("Could not subscribe to the notification topic {topic} received response {responseStatusCode}", notificationConfig.Value.Topic, response.HttpStatusCode);
        throw new Exception("Could not subscribe to notification topic");
    }
}
```

### Environment

```markdown
- OS: Windows 10 running localstack latest version within a docker container
- LocalStack: latest version `localstack:latest`
```
