### ISSUE TITLE
Elasticsearch cannot be accessed via Docker network

### ISSUE THREAD

**Issue by sidprak** [localstack/localstack#5476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I am trying to migrate away from the deprecated single port Elasticsearch behavior. I tried to start localstack with Elasticsearch using `ES_ENDPOINT_STRATEGY: path`.  Elasticsearch starts up successfully and is accessible via `http://localhost:4566/es/us-west-2/test-domain`. We run our application in a separate container and when I attempt to access Elasticsearch from that container using Docker networking, I get an S3 error message:

```
# curl 'http://localstack:4566/es/us-west-2/test-domain'

<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>es</BucketName>
    <RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```

It seems like the ES path only works from localhost which means we cannot access it using Docker networking. Can we allow ES to be accessed externally? Is there a workaround for this?

### Anything else?

My configuration:
```yaml
version: "3.6"
services:
  localstack:
    environment:
      SERVICES: cloudwatch,s3,sqs,lambda,dynamodb,kinesis,elasticsearch,es,sns,apigateway
      DATA_DIR: /tmp/localstack/data
      LAMBDA_EXECUTOR: docker
      LAMBDA_DOCKER_NETWORK: host
      DOCKER_HOST: unix:///var/run/docker.sock
      HOSTNAME_EXTERNAL: localstack
      HOSTNAME: localstack
      ES_ENDPOINT_STRATEGY: path
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # allow lambda to start docker containers
```
