### ISSUE TITLE
bug: pre-signed POST to s3 does not trigger s3 object created event for lambda trigger

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#5554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using pre-signed POST to s3 does not trigger s3 object created event for lambda trigger. 

### Expected Behavior

Using pre-signed POST to s3 should trigger s3 object created event for lambda trigger. 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Pulumi typescript:

export const uploadObjectCreateEvent = bucket.onObjectCreated(
  'uploadObjectCreateEvent',
  fuelUploadLambda,
  {
    event: '*',
    filterPrefix: 'uploads/'
  },
  { provider: PulumiUtil.awsProvider }
);

### Environment

```markdown
- OS: OSX and Windows 11
- LocalStack: latest
```

### Anything else?

Event does trigger if I use cli s3 cp. 
Maybe related to https://github.com/localstack/localstack/pull/4809 ?

**Comment by pinzon** [comment]
Hi @paulrobello, thank you for your patience. After triaging your issue it seems to be an usage error, I'm guessing because you're using POST instead of PUT as aws specifies [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html). 

I took me some time to validate this due to Pulumi behaving very irrational some of the times with Localstack. Either way I'm attaching my stack config file, stack file and lambda code so you can validate my results.  

index.ts
```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { rootPulumiStackTypeName } from "@pulumi/pulumi/runtime";

const bucket = new aws.s3.Bucket("my-bucket");

const lambda = new aws.lambda.Function("lambda", {
	code: new pulumi.asset.FileArchive('function.zip'),
	runtime: "nodejs14.x",
	handler: "index.handler",
	role: "no-real-role"
})

const createdObjectEvent = bucket.onObjectCreated("uploadEvent", lambda, {
	event: '*',
	filterPrefix: 'uploads/'
});
```
Pulumi.pinzon.yaml
```
config:
  aws:accessKey: test
  aws:endpoints:
  - acm: http://localhost:4566
    amplify: http://localhost:4566
    apigateway: http://localhost:4566
    apigatewayv2: http://localhost:4566
    applicationautoscaling: http://localhost:4566
    appsync: http://localhost:4566
    athena: http://localhost:4566
    autoscaling: http://localhost:4566
    batch: http://localhost:4566
    cloudformation: http://localhost:4566
    cloudfront: http://localhost:4566
    cloudsearch: http://localhost:4566
    cloudtrail: http://localhost:4566
    cloudwatch: http://localhost:4566
    cloudwatchevents: http://localhost:4566
    cloudwatchlogs: http://localhost:4566
    codecommit: http://localhost:4566
    cognitoidentity: http://localhost:4566
    cognitoidp: http://localhost:4566
    docdb: http://localhost:4566
    dynamodb: http://localhost:4566
    ec2: http://localhost:4566
    ecr: http://localhost:4566
    ecs: http://localhost:4566
    eks: http://localhost:4566
    elasticache: http://localhost:4566
    elasticbeanstalk: http://localhost:4566
    elb: http://localhost:4566
    emr: http://localhost:4566
    es: http://localhost:4566
    firehose: http://localhost:4566
    glacier: http://localhost:4566
    glue: http://localhost:4566
    iam: http://localhost:4566
    iot: http://localhost:4566
    kafka: http://localhost:4566
    kinesis: http://localhost:4566
    kinesisanalytics: http://localhost:4566
    kms: http://localhost:4566
    lambda: http://localhost:4566
    mediastore: http://localhost:4566
    neptune: http://localhost:4566
    organizations: http://localhost:4566
    qldb: http://localhost:4566
    rds: http://localhost:4566
    redshift: http://localhost:4566
    route53: http://localhost:4566
    s3: http://localhost:4566
    sagemaker: http://localhost:4566
    secretsmanager: http://localhost:4566
    servicediscovery: http://localhost:4566
    ses: http://localhost:4566
    sns: http://localhost:4566
    sqs: http://localhost:4566
    ssm: http://localhost:4566
    stepfunctions: http://localhost:4566
    sts: http://localhost:4566
    swf: http://localhost:4566
    transfer: http://localhost:4566
    xray: http://localhost:4566
  aws:region: us-east-1
  aws:s3ForcePathStyle: 'true'
  aws:secretKey: test
  aws:skipCredentialsValidation: 'true'
  aws:skipRequestingAccountId: 'true'
```

lambda code
```
const https = require('https')
const url = 'https://webhook.site/043b22e6-8656-455e-b7cc-3420ee4d1221'
exports.handler = function (event, context, callback) {
	const promise = new Promise(function (resolve, reject) {
		https.get(url, (res) => {
			callback(null, res.statusCode)
		}).on('error', (e) => {
			callback(Error(e))
		})
	})
}
```
I'm closing this issue but if you feel that this is not the case please comment with more info about the error logs and your exact setup/stack-code. 
Thank you.
