### ISSUE TITLE
bug: can't create db instance with anything other than `test` or `postgres` for default database name

### ISSUE THREAD

**Issue by iiian** [localstack/localstack#5597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to create a database, pretty much via any medium (`awslocal`, `SAM`, `cloudformation`), it _seems_ like I can only specify either `postgres` or `test` as the initial database name. The system I am building must operate in a multi-tenant environment where schema is replicated across several databases partitioned by a customer identifier. Not a _huge_ deal but it's sort of impeding the ability to write integration tests the way I want to.

### Expected Behavior

The specific database is created as requested, and `psql postgresql://postgres:password@localhost:4510/testcustomer` logs me in.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Cloud Formation template:
```yml
# file name = cf.template.yml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MasterUserPassword:
    Type: String
    Default: password
    NoEcho: true
Resources:
  DocsDb:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t1.micro
      DBInstanceIdentifier: document_service_database
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: !Ref MasterUserPassword
      DBName: testcustomer
  DocsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: testcustomer
```

docker-compose.yml
```yml
# file name = docker-compose.yml
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=0
      - SERVICES=rds,vpc,lambda,dynamodb,cloudformation,s3,sts,iam,apigateway,ecr,ec2
      - HOST_TMP_FOLDER="${TMPDIR:-/tmp}/localstack"
      - DEFAULT_REGION=us-west-1
      - PORT_WEB_UI=8080
    ports:
      - '4510:4510'
      - '4566:4566'
      - '8080:8080'
    volumes:
      # - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
```

## Steps:
1. `docker-compose up`
2. wait for it to be live
3. In a separate terminal, run `awslocal cloudformation create-stack --stack-name test --template-body file://./cf.template.yml`
4. Back in the localstack container, the following log:
```log
localstack_1  | 2022-03-03T04:16:40.332:INFO:localstack_ext.utils.postgresql: Starting PostgreSQL query listener/rewriter on port 4510->49095       
localstack_1  | 2022-03-03T04:16:41.334:INFO:localstack_ext.services.rds.db_utils: Starting RDS server on port 4510 (backend port 49095) - database 
"testcustomer", user "postgres" - data dir /tmp/localstack/rds-data/us-east-1/document_service_database-485eb4fb
localstack_1  | 2022-03-03T04:16:43.796:WARNING:localstack_ext.services.rds.db_utils: Unable to startup DB instance: {'S': 'FATAL', 'V': 'FATAL', 'C': '3D000', 'M': 'database "testcustomer" does not exist', 'F': 'postinit.c', 'L': '855', 'R': 'InitPostgres'} Traceback (most recent call last):   
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/pg8000/legacy.py", line 442, in __init__
localstack_1  |     super().__init__(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/pg8000/core.py", line 342, in __init__
localstack_1  |     raise self.error
localstack_1  | pg8000.exceptions.DatabaseError: {'S': 'FATAL', 'V': 'FATAL', 'C': '3D000', 'M': 'database "testcustomer" does not exist', 'F': 'postinit.c', 'L': '855', 'R': 'InitPostgres'}
localstack_1  | During handling of the above exception, another exception occu
occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagesages/localstack_ext/services/rds/db_utils.py.enc", line 52, in do_startup   
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagesages/localstack_ext/services/rds/db_utils.py.enc", line 115, in start_db_isae nstance                                                                     es
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagexages/localstack_ext/services/rds/db_utils.py.enc", line 220, in define_posgetgres_extensions                                                            es
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagages/localstack_ext/utils/postgresql.py.enc", line 167, in run_query        es
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagages/localstack_ext/utils/postgresql.py.enc", line 177, in connect          es
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagages/pg8000/__init__.py", line 117, in connect
localstack_1  |     return Connection(                                      es
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packagages/pg8000/legacy.py", line 455, in __init__
localstack_1  |     raise cls(msg)                                          'C
localstack_1  | pg8000.dbapi.ProgrammingError: {'S': 'FATAL', 'V': 'FATAL', , , 'C': '3D000', 'M': 'database "testcustomer" does not exist', 'F': 'postii.nit.c', 'L': '855', 'R': 'InitPostgres'}
localstack_1  |
```

`psql postgresql://postgres:password@localhost:4510/testcustomer` _fails_.
`psql postgresql://postgres:password@localhost:4510/postgres` **passes**

Once inside I can of course manually `CREATE DATABASE testcustomer` and `\c testcustomer` as normal.

### Environment

```markdown
- OS: Ubuntu 20.04 via WSL (Windows 10)
- LocalStack: latest
```

### Anything else?

You guys are awesome.
