### ISSUE TITLE
bug: Cannot create KMS alias

### ISSUE THREAD

**Issue by kuwv** [localstack/localstack#5607]
### Is there an existing issue for this? No

- [X] I have searched the existing issues

### Current Behavior

KMS keys are created but Alias is not.

### Expected Behavior

Alias should be created for KMS keys as this is the preferred way to access keys.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
export LOCALSTACK_SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,ec2,es,firehose,iam,kinesis,kms,lambda,route53,redshift,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
docker run \
  --rm \
  -d \
  -e SERVICES="$LOCALSTACK_SERVICES" \
  -p 4566:4566 \
  -p 4571:4571 \
  localstack/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
aws kms create-alias \
--endpoint=http://localhost:4566 \
--alias-name sops-example \
--target-key-id 5ddb7d9f-7e7c-4f0d-878b-5c357bdb5c87
```

```
An error occurred (ValidationException) when calling the CreateAlias operation: Invalid identifier
```

 Ansible:

```yaml
- name: Execute localstack
  hosts: localhost
  connection: local

  tasks:
    - name: Mange KMS keys
      community.aws.aws_kms:
        aws_access_key: localkey
        aws_secret_key: localsecret
        ec2_url: http://localhost:4566
        region: us-east-1

        alias: sops-example
        description: KMS example
      register: __kms_key_info

    - debug:
        var: __kms_key_info
```

__kms_key_info:

```json
{
    "invocation": {
        "module_args": {
            "alias": "sops-example",
            "aws_access_key": "localkey",
            "aws_ca_bundle": null,
            "aws_config": null,
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "debug_botocore_endpoint_logs": false,
            "ec2_url": "http://localhost:4566",
            "filters": null,
            "key_id": null,
            "keys_attr": true,
            "pending_deletion": false,
            "profile": null,
            "region": "us-east-1",
            "security_token": null,
            "validate_certs": true
        }
    }
}
```

```yaml
- name: Execute localstack
  hosts: localhost
  connection: local

  tasks:
    - name: Lookup KMS key
      community.aws.aws_kms_info:
        aws_access_key: localstack
        aws_secret_key: localstack
        ec2_url: http://localhost:4566
        region: us-east-1

        alias: sops-example
      register: __kms_key_info

    - debug:
        var: __kms_key_info
```

Just dumps all keys: (output abbreviated)

```json
{
    "aliases": [],
    "aws_account_id": "000000000000",
    "creation_date": "2022-03-03T14:54:29.673019-05:00",
    "customer_master_key_spec": "SYMMETRIC_DEFAULT",
    "description": "KMS example",
    "enable_key_rotation": false,
    "enabled": true,
    "encryption_algorithms": [
        "SYMMETRIC_DEFAULT"
    ],
    "grants": [],
    "key_arn": "arn:aws:kms:us-east-1:000000000000:key/5ddb7d9f-7e7c-4f0d-878b-5c357bdb5c87",
    "key_id": "5ddb7d9f-7e7c-4f0d-878b-5c357bdb5c87",
    "key_manager": "CUSTOMER",
    "key_state": "Enabled",
    "key_usage": "ENCRYPT_DECRYPT",
    "origin": "AWS_KMS",
    "policies": [
        "{\"Version\": \"2012-10-17\", \"Id\": \"key-default-1\", \"Statement\": [{\"Sid\": \"Enable IAM User Permissions\", \"Effect\": \"Allow\", \"Principal\": {\"AWS\": \"arn:aws:iam::000000000000:root\"}, \"Action\": \"kms:*\", \"Resource\": \"*\"}]}"
    ],
    "tags": {}
}
```

Terraform is the same but if you need a reference: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kms_key

### Environment

```markdown
- OS: MacOS Monterey
- LocalStack: latest    099d4edd0105
```

### Anything else?

Thank you guys for this awesome project.
