### ISSUE TITLE
issue: can not assume role with localStack

### ISSUE THREAD

**Issue by ntthaibk** [localstack/localstack#5636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've created role with aws cli like below

`aws --endpoint-url=http://127.0.0.1:50024 iam create-role --role-name admin --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Action":"*","Resource":"*"}]}'`

the endpoint URL is where I start localStack since I'm using testContainer to pull up localStack so it bind port 4566 to a random port on my machine.

And I successfully created a role
![image](https://user-images.githubusercontent.com/62538035/157416732-572be73e-614d-4506-a831-c1d5d0c223e8.png)

And put it in my terraform file as this
`"provider": {
    "aws": [
      {
        "access_key": "test",
        "secret_key": "test",
        "region": "us-east-1",
        "skip_credentials_validation": "true",
        "skip_metadata_api_check": "true",
        "skip_requesting_account_id": "true",
        "endpoints": {
          "lambda": "http://127.0.0.1:50024",
          "apigateway": "http://127.0.0.1:50024",
          "cloudformation": "http://127.0.0.1:50024",
          "cloudwatch": "http://127.0.0.1:50024",
          "dynamodb": "http://127.0.0.1:50024",
          "ec2": "http://127.0.0.1:50024",
          "iam": "http://127.0.0.1:50024",
          "route53": "http://127.0.0.1:50024",
          "s3": "http://127.0.0.1:50024",
          "sts": "http://127.0.0.1:50024",
          "secretsmanager": "http://127.0.0.1:50024",
          "kms": "http://127.0.0.1:50024"
        },
        "s3_force_path_style": "true",
        "max_retries": "3",
        "assume_role": {
          "role_arn": "${var.aws_role_arn}"
        }
      }
    ]`

the var.aws_role_arn looks like this variable 

`"aws_role_arn" {
  description = "Role to be assumed"
  default     = "arn:aws:iam::000000000000:role/admin"
}`

don't know why when trying to apply terraform plan, I caught this issue

`│ Error: error configuring Terraform AWS Provider: IAM Role (arn:aws:iam::000000000000:role/admin) cannot be assumed.
│
│ There are a number of possible causes of this - the most common are:
│   * The credentials used in order to assume the role are invalid
│   * The credentials do not have appropriate permission to assume the role
│   * The role ARN is not valid
│
│ Error: operation error STS: AssumeRole, https response error StatusCode: 500, RequestID: , api error UnknownError: UnknownError
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf.json line 30, in provider.aws[0]:
│   30:       }`

### Expected Behavior

should be able to apply terraform normally

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

mentioned

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

**Comment by whummer** [comment]
Thanks for reporting @ntthaibk . Can you please help us reproduce this issue by providing a small snippet (minimum working example) of your Terraform script? That would be much appreciated, thanks!

**Comment by ntthaibk** [comment]
I can share the whole tf script since I'm doing POC with it.

Basically what I'm trying to do is to reuse my company's real tf for dev environment and apply it for localStack with minimum changes

Here's my main.tf.json file
```yaml
{
  "provider": {
    "aws": [
      {
        "access_key": "test",
        "secret_key": "test",
        "region": "us-east-1",
        "skip_credentials_validation": "true",
        "skip_metadata_api_check": "true",
        "skip_requesting_account_id": "true",
        "endpoints": {
          "lambda": "http://127.0.0.1:50024",
          "apigateway": "http://127.0.0.1:50024",
          "cloudformation": "http://127.0.0.1:50024",
          "cloudwatch": "http://127.0.0.1:50024",
          "dynamodb": "http://127.0.0.1:50024",
          "ec2": "http://127.0.0.1:50024",
          "iam": "http://127.0.0.1:50024",
          "route53": "http://127.0.0.1:50024",
          "s3": "http://127.0.0.1:50024",
          "sts": "http://127.0.0.1:50024",
          "secretsmanager": "http://127.0.0.1:50024",
          "kms": "http://127.0.0.1:50024"
        },
        "s3_force_path_style": "true",
        "max_retries": "3",
        "assume_role": {
          "role_arn": "${var.aws_role_arn}"
        }
      }
    ]
  },
  "terraform": {
    "backend": {
      "local": {
        "path": "src/test/resources/terraform/test-each-tf"
      }
    }
  }
}
```

Here is my variables file

```yaml
variable "account_id_nonprod" {
  description = "AWS account for infra changes"
  default     = "000000000000"
}

variable "aws_region" {
  description = "Region where this is deployed"
  default     = "us-east-1"
}

variable "aws_role_arn" {
  description = "Role to be assumed"
  default     = "arn:aws:iam::000000000000:role/admin"
}

variable "aws_root_arn" {
  description = "Role to be assumed"
  default     = "arn:aws:iam::000000000000:root"
}

variable "env" {
  description = "Environment Name"
  default     = "dev"
}
```
