### ISSUE TITLE
bug: ApproximateCreationDateTime from dynamo stream record doesn't round down to the second

### ISSUE THREAD

**Issue by GroovySmoothie** [localstack/localstack#5656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im using a dynamo stream event source to lambda setup and the property ApproximateCreationDateTime is a float which I don't think is expected.

According to the [AWS docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_StreamRecord.html) it says
> The approximate date and time when the stream record was created, in [UNIX epoch time](http://www.epochconverter.com/) format and rounded down to the closest second.

Also, because it's a float there are issues with the [RecordObjectMapper](https://github.com/awslabs/dynamodb-streams-kinesis-adapter/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/streamsadapter/model/RecordObjectMapper.java) provided by the ddb stream to kinesis adapter. It fails to deserialise the float to a Date.

Example:
StreamRecord:
{
  ApproximateCreationDateTime: 1646887668.348366,
  ...
}

### Expected Behavior

StreamRecord:
{
  ApproximateCreationDateTime: 1646887668,
  ...
}

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yml
```
version: "3.5"
services:
  my-localstack:
    container_name: "my-localstack"
    image: localstack/localstack
    ports:
      - "4566:4566" # Edge
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodbstreams,dynamodb,lambda
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

lambda.ts
```
import {Callback, Context, DynamoDBStreamEvent, StreamRecord} from "aws-lambda";

export const handler: (event: DynamoDBStreamEvent, context: Context, callback: Callback) => Promise<void> = async (
    event,
    context,
    callback
) => {
  const queueUrl = await sqsClient.getQueueUrl();
  event.Records
      .forEach(x => {
    console.log(x.dynamodb); // Shows ApproximateCreationDateTime as float
    callback(null, `processed one record ${x.eventID}`);
  });
};
```

After writing anything to dynamodb the lambda will receive the StreamRecord and print the contents, show the timestamp as a float.

### Environment

```markdown
- OS: macOS 12.2.1
- LocalStack: latest
```
