### ISSUE TITLE
APIGateway v2 -> Lambda authorizer (Proxy)

### ISSUE THREAD

**Issue by nr-96** [localstack/localstack#5657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

As of now, the lambda authorizer is not being invoked for `httpApi` events - method `ANY`
Example `serverless.yml`

```
functions:
  authorizerFunc:
    handler: src/handler.auth
  routes:
    handler: src/handler.run
    description: Routing event to correct internal function
    events:
      - httpApi:
          path: /{proxy+}
          method: any
          authorizer:
            name: authorizerFunc
            type: request
```

Please find the sample repo: https://github.com/nr-96/lambda-authorizer
