### ISSUE TITLE
bug: Creating a security group results in "Error revoking default egress rule for Security Group ... InvalidPermission.NotFound: The specified rule does not exist in this security group"

### ISSUE THREAD

**Issue by dmusicant-dk** [localstack/localstack#5659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do a `terraform apply`, it results in the error:

```plaintext
aws_security_group.mysg: Creating...
╷
│ Error: Error revoking default egress rule for Security Group (sg-7f18216d7358db543): InvalidPermission.NotFound: The specified rule does not exist in this security group
│ 	status code: 400, request id: 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE
│ 
│   with aws_security_group.mysg,
│   on main.tf line 17, in resource "aws_security_group" "mysg":
│   17: resource "aws_security_group" "mysg" {
```

### Expected Behavior

It would create the security group without issue.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose -f localstack.yml up

##### Localstack Compose File
```yaml
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,dynamodb,cloudformation,ec2,iam
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Terraform Files

**main.tf**
```terraform
provider "aws" {
  region                      = "us-east-1"
  access_key                  = "localstacktest"
  secret_key                  = "localstacktestkey"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  s3_use_path_style           = true
  endpoints {
    ec2 = "http://localhost:4566"
    iam = "http://localhost:4566"
  }
}

# Setup our security group
resource "aws_security_group" "mysg" {
  name   = "allow_ssh"
  vpc_id = var.vpc_id

  ingress {
    description = "Allow inbound ssh traffic"
    cidr_blocks = [var.cidr_block]
    from_port   = var.port
    protocol    = "tcp"
    to_port     = var.port
  }

  tags = {
    name = "allow_ssh"
  }
}
```
**variables.tf**
```terraform
variable "vpc_id" {
  default = "vpc-bc102dc4"
}

variable "port" {
  default = 22
}

variable "cidr_block" {
  default = "0.0.0.0/0"
}
```
**outputs.tf**
```terraform
output "security_group" {
  value = aws_security_group.mysg.id
}
```
#### Commands Run

```bash
terraform init
terraform fmt
terraform validate
terraform apply
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.0.9
```
