### ISSUE TITLE
API Gateway v2 - Websocket API HTTP integration request template not applied properly 

### ISSUE THREAD

**Issue by megraby** [localstack/localstack#5670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm recreating the following resources which work correctly after being created via the AWS Management Console. 

For the sake of simplicity I removed an authorizer Lamda and ran the setup in AWS again, verifying it works and then applied the same configuration locally  with Terraform (compared the results using the AWS CLI, everything matches).

API:
```
        {
            "ApiEndpoint": "wss://xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com",
            "ApiId": "xxxxxxxxxx",
            "ApiKeySelectionExpression": "$request.header.x-api-key",
            "CreatedDate": "2022-03-07T10:11:25+00:00",
            "DisableExecuteApiEndpoint": false,
            "Name": "xxxxxxxxxx",
            "ProtocolType": "WEBSOCKET",
            "RouteSelectionExpression": "$request.body.action",
            "Tags": {}
        } 
```
The connect route definition:
```
        {
            "ApiKeyRequired": false,
            "AuthorizationType": "NONE",
            "RouteId": "xxxxxxxx",
            "RouteKey": "$connect",
            "RouteResponseSelectionExpression": "$default",
            "Target": "integrations/xxxxxx"
        }
```

HTTP integration: 
```
    {
            "ConnectionType": "INTERNET",
            "ContentHandlingStrategy": "CONVERT_TO_TEXT",
            "IntegrationId": "xxxxxxxxxx",
            "IntegrationMethod": "POST",
            "IntegrationResponseSelectionExpression": "${integration.response.statuscode}",
            "IntegrationType": "HTTP",
            "IntegrationUri": "http://xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "PassthroughBehavior": "WHEN_NO_MATCH",
            "PayloadFormatVersion": "1.0",
            "RequestTemplates": {
                "$default": "{\n\"userId\": \"123\",\n\"connectionId\": \"$context.connectionId\"\n}"
            },
            "TemplateSelectionExpression": "\\$default",
            "TimeoutInMillis": 29000
        }
```
When running on AWS each successful connection produces a POST request to the specified URL in the HTTP integration with the format specified in the default request template.
 
Using Localstack  the request received at the endpoint has a body of:
`{"action": "$connect"}`

Trying to bypass the issue by setting the request template with a key of _application/json_ does trigger the template, but sets the request's Content-Type header to _application/octet-stream_. Either way, the behavior differs from the actual service provided by AWS.

### Expected Behavior

Expected to send a POST request to the HTTP integration with the body such as 

```
{
    "userId": "123",
    "connectionId": "xxxxxxxxxxxxx"
}
```

The result is achieved using the actual AWS service.

### How are you starting LocalStack?

With a docker-compose file

### Trimmed down version of the docker-compose file used
```
version: '3'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=sqs,s3,lambda,apigateway
      - LOCALSTACK_API_KEY=xxxxxxxxxxx
    ports:
      - "4566:4566"
      - "4510:4510"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/.aws:/root/.aws"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```
