### ISSUE TITLE
bug: slowness and 500 errors when there is 10k msgs in queue and ~30 consumers

### ISSUE THREAD

**Issue by ucarbehlul** [localstack/localstack#5690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Slowness and 500 errors when there is 10k msgs in queue and ~30 consumers

A receive-message call takes 15-20 seconds and fails with 500 80% of the time.

### Expected Behavior

SQS should be fast enough, at most 1-2 seconds time to receive messages not 500s.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up`

docker-compose.yml:
```
version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "8000:8080"
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - HOSTNAME=192.168.57.100
      - DEFAULT_REGION=us-west-1
    volumes:
      - ./bootstrap:/docker-entrypoint-initaws.d
```

### Environment

```markdown
- OS: ubuntu
Linux behlul-raspberrypi400 5.13.0-1020-raspi #22-Ubuntu SMP PREEMPT Mon Mar 7 13:09:05 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- LocalStack: 
I put localstack details in the docker-compose.yml file.
```

### Anything else?

I got same behavior on mac os too. CPU is always close to 100% and with 10k messages in the queue, it starts becoming super slow.
