### ISSUE TITLE
bug: `cdklocal` doesn't generate a database

### ISSUE THREAD

**Issue by iiian** [localstack/localstack#5720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to create a `postgres` instance via `cdklocal`, `cdklocal` _acts_ like it succeeded, but `awslocal rds describe-db-instances` shows nothing and I can't `psql` into it.

For instance, `cdklocal` outputs:

```shell
 ✅  local-env-stack

✨  Deployment time: 10.53s

Stack ARN:
arn:aws:cloudformation:us-west-1:000000000000:stack/local-env-stack/dd15f61e

✨  Total time: 70s
```

but upon running `awslocal rds describe-db-instances`:

```
{
    "DBInstances": []
}
```
and `psql`:
```bash
$ psql postgresql://postgres:password@localhost:4510/
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### Expected Behavior

locally stacked tables

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yml
#docker-compose.yml
version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - LOCALSTACK_API_KEY=#########
      - DEBUG=1
      - LS_LOG=trace
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '4510-4583:4510-4583'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/localstack:/tmp/locastack'
    privileged: true
```

```typescript
// Db definition
    new Vpc(this, `local-vpc`, {
      vpcName: `local-vpc`,
      cidr: '10.0.0.0/16',
      maxAzs: 2,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: `local-subnet`,
          subnetType: SubnetType.PUBLIC,
        }
      ],
    });
    this.default_security_group = SecurityGroup.fromSecurityGroupId(
      this,
      `local-sg`,
      this.vpc.vpcDefaultSecurityGroup
    );
    const engine = DatabaseInstanceEngine.postgres({
      version: PostgresEngineVersion.VER_13_4
    });
    this.db = new DatabaseInstance(this, 'db', {
      engine,
      databaseName: 'postgres',
      credentials: Credentials.fromPassword('postgres1', SecretValue.plainText('password')),
      instanceType: InstanceType.of(InstanceClass.BURSTABLE4_GRAVITON, InstanceSize.MICRO),
      storageType: StorageType.GP2,
      allocatedStorage: 20,
      multiAz: true,
      vpc: this.vpc,
      vpcSubnets: { subnetType: SubnetType.PUBLIC },
      securityGroups: [this.default_security_group],
      port: 5432,
      parameterGroup: ParameterGroup.fromParameterGroupName(this, `default-param-group`, 'default.postgres13'),
      backupRetention: Duration.days(0),
      autoMinorVersionUpgrade: true,
      enablePerformanceInsights: false,
      instanceIdentifier: 'main-db',
      publiclyAccessible: true,
      deletionProtection: false, // needs to be set to true in a prod context i think
      removalPolicy: RemovalPolicy.SNAPSHOT,
    });
    this.db.connections.allowDefaultPortFromAnyIpv4();
```

```yml
# cdklocal-synth-output.yml
Resources:
  localmainvpcconstructlocalvpcC645BC79:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: local-vpc
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/Resource
  localmainvpcconstructlocalvpclocalsubnetSubnet1Subnet7CCB565C:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId:
        Ref: localmainvpcconstructlocalvpcC645BC79
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: local-subnet
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet1
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet1/Subnet
  localmainvpcconstructlocalvpclocalsubnetSubnet1RouteTable836BCFE0:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: localmainvpcconstructlocalvpcC645BC79
      Tags:
        - Key: Name
          Value: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet1
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet1/RouteTable
  localmainvpcconstructlocalvpclocalsubnetSubnet1RouteTableAssociation3B5CB13E:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: localmainvpcconstructlocalvpclocalsubnetSubnet1RouteTable836BCFE0
      SubnetId:
        Ref: localmainvpcconstructlocalvpclocalsubnetSubnet1Subnet7CCB565C
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet1/RouteTableAssociation
  localmainvpcconstructlocalvpclocalsubnetSubnet1DefaultRoute0B902144:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: localmainvpcconstructlocalvpclocalsubnetSubnet1RouteTable836BCFE0
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: localmainvpcconstructlocalvpcIGW22AFCB2F
    DependsOn:
      - localmainvpcconstructlocalvpcVPCGWB4723078
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet1/DefaultRoute
  localmainvpcconstructlocalvpclocalsubnetSubnet2Subnet58B5EF8F:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId:
        Ref: localmainvpcconstructlocalvpcC645BC79
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: aws-cdk:subnet-name
          Value: local-subnet
        - Key: aws-cdk:subnet-type
          Value: Public
        - Key: Name
          Value: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet2
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet2/Subnet
  localmainvpcconstructlocalvpclocalsubnetSubnet2RouteTableA3CF9635:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: localmainvpcconstructlocalvpcC645BC79
      Tags:
        - Key: Name
          Value: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet2
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet2/RouteTable
  localmainvpcconstructlocalvpclocalsubnetSubnet2RouteTableAssociation5E4FDFDC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: localmainvpcconstructlocalvpclocalsubnetSubnet2RouteTableA3CF9635
      SubnetId:
        Ref: localmainvpcconstructlocalvpclocalsubnetSubnet2Subnet58B5EF8F
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet2/RouteTableAssociation
  localmainvpcconstructlocalvpclocalsubnetSubnet2DefaultRoute178CDCE7:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: localmainvpcconstructlocalvpclocalsubnetSubnet2RouteTableA3CF9635
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: localmainvpcconstructlocalvpcIGW22AFCB2F
    DependsOn:
      - localmainvpcconstructlocalvpcVPCGWB4723078
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/local-subnetSubnet2/DefaultRoute
  localmainvpcconstructlocalvpcIGW22AFCB2F:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: local-vpc
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/IGW
  localmainvpcconstructlocalvpcVPCGWB4723078:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: localmainvpcconstructlocalvpcC645BC79
      InternetGatewayId:
        Ref: localmainvpcconstructlocalvpcIGW22AFCB2F
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-vpc/VPCGW
  localmainvpcconstructlocalsgfrom00000IndirectPort8BF10744:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      CidrIp: 0.0.0.0/0
      Description: from 0.0.0.0/0:{IndirectPort}
      FromPort:
        Fn::GetAtt:
          - localmainvpcconstructdb86A2C82E
          - Endpoint.Port
      GroupId:
        Fn::GetAtt:
          - localmainvpcconstructlocalvpcC645BC79
          - DefaultSecurityGroup
      ToPort:
        Fn::GetAtt:
          - localmainvpcconstructdb86A2C82E
          - Endpoint.Port
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/local-sg/from 0.0.0.0_0:{IndirectPort}
  localmainvpcconstructdbSubnetGroupD8A47718:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for db database
      SubnetIds:
        - Ref: localmainvpcconstructlocalvpclocalsubnetSubnet1Subnet7CCB565C
        - Ref: localmainvpcconstructlocalvpclocalsubnetSubnet2Subnet58B5EF8F
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/db/SubnetGroup/Default
  localmainvpcconstructdb86A2C82E:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: "20"
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 0
      CopyTagsToSnapshot: true
      DBInstanceIdentifier: main-db
      DBName: postgres
      DBParameterGroupName: default.postgres13
      DBSubnetGroupName:
        Ref: localmainvpcconstructdbSubnetGroupD8A47718
      DeletionProtection: false
      EnablePerformanceInsights: false
      Engine: postgres
      EngineVersion: "13.4"
      MasterUsername: postgres
      MasterUserPassword: password
      MultiAZ: true
      Port: "5432"
      PubliclyAccessible: true
      StorageType: gp2
      VPCSecurityGroups:
        - Fn::GetAtt:
            - localmainvpcconstructlocalvpcC645BC79
            - DefaultSecurityGroup
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
    Metadata:
      aws:cdk:path: local-stack/local-main-vpc-construct/db/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WQwW7CQAxEv6X3zVIQfAANEsoNBcQVeTduawhetPaCUJR/JyG0qdSTx09jzcgzO13Y9ze4SearU1aTs81WwZ9Mhw4N+plt9hdv8k/eb3KzSa4mv02OUXs2qjIkxR24Gkc+sqVI8ARKgX/NvShYMXbONSje4P6KeW1L7Yp8n5GHKPQpkt7XMaRLwV8RRVoTK7HNChQcCBYsCuzRDPFPZ3+6+vgHfqxta0qUkKJ/9vmr88AV9Y1bw6FCe5TJdTof/nUUoiwmVjqjLYf5ALckc6pLAQAA
    Metadata:
      aws:cdk:path: local-stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

### Environment

```markdown
- OS: Ubuntu 20.04 on Windows10+WSL2
- LocalStack: latest (0.14.1.1)
```
