### ISSUE TITLE
Not able to visualize tables of Localstack dynamo db in UI provider

### ISSUE THREAD

**Issue by ByteProgramming** [localstack/localstack#5737]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I am running localstack as docker container with latest image.
I am able to communicate to Localstack db but not able to visualize tables.

**What i want to achieve**: Visualization of Localstack dynamo db

Issue:
I created a Localstack dynamo table. From logs i can see, table is created
```
localstack_main | 2022-03-22T16:51:33.107:INFO:localstack.services.dynamodb.server: Initializing DynamoDB Local with the following configuration:
localstack_main | 2022-03-22T16:51:33.107:INFO:localstack.services.dynamodb.server: Port:	37617
localstack_main | 2022-03-22T16:51:33.107:INFO:localstack.services.dynamodb.server: InMemory:	true
localstack_main | 2022-03-22T16:51:33.107:INFO:localstack.services.dynamodb.server: DbPath:	null
localstack_main | 2022-03-22T16:51:33.107:INFO:localstack.services.dynamodb.server: SharedDb:	false
localstack_main | 2022-03-22T16:51:33.108:INFO:localstack.services.dynamodb.server: shouldDelayTransientStatuses:	false
localstack_main | 2022-03-22T16:51:33.108:INFO:localstack.services.dynamodb.server: CorsParams:	*
localstack_main | 2022-03-22T16:51:33.117:INFO:localstack.services.dynamodb.server: 
```
I want to see the tables, i created in the Localstack dynamo db. For visualizing, i tried to connect with NoSQLWorkbench.
I am providing Host = localhost and port= 4566 in "DynamoDB Local" of NoSqlWorkbench
I can see connection happens successful. but i do not see the tables of Localstack dynamo db in NoSqlWorkbench
**So, i would like to understand** : 
  1. is it possible to visualize the localstack dynamo db in NoSqlWorkbench?
  2. If yes, How i can do ?

**Comment by kevinschaffter** [comment]
This is a killer.... 🙃

**Comment by mgreg90** [comment]
Affecting me as well 😞

**Comment by ByteProgramming** [comment]
@silv-io  any view/suggestion on how we can visualize properly?

**Comment by MarcelStranak** [comment]
Hi @ByteProgramming , currently, you can use the 3rd party tool Dynobase which enables to fake the region you are connecting to.

Seems there is a mismatch between LocalStack and NoSQL Workbench. 
NoSQL Workbench does not allow to change the region when using local connection. Because of this LS does not return any tables with ListTables call.

Difference in the calls:
/us-east-1/ vs /localhost/

aws-cli
```
 'Authorization': 'AWS4-HMAC-SHA256 Credential=test/20220404/us-east-1/dynamodb/aws4_request
```
NoSQL Workbench
```
 'Authorization': 'AWS4-HMAC-SHA256 Credential=gooxb/20220404/localhost/dynamodb/aws4_request
```

**Comment by whummer** [comment]
Thanks for reporting @ByteProgramming @kevinschaffter @mgreg90 @jonrose-dev . Can you please pull the `latest` Docker image, then configure the following environment variables in your LocalStack Docker container: 
```
DISABLE_CORS_CHECKS=1
DEBUG=1
LS_LOG=trace
```
Please note that due to limitations in the NoSQLWorkbench, your DynamoDB tables need to  be created in the default region that LocalStack was started with, typically `us-east-1`. Please let us know if that works - if not, then please share any logs/error messages you are seeing (with detailed logging enabled via `LS_LOG=trace`). Thanks!

**Comment by vgorloff** [comment]
Seems, soon, it will be possible to specify `--endpoint-url` in AWS config file (see links below). After that the WebStorm/IDEA plug-in "AWS Toolkit" might be also an option.

References:

- Ability to specify endpoint-url in profile · Issue #1270 · aws/aws-cli: https://github.com/aws/aws-cli/issues/1270
- Add proposal for configuring endpoints per service by kdaily · Pull Request #230 · aws/aws-sdk: https://github.com/aws/aws-sdk/pull/230
- aws-sdk/configure-endpoint-url.md at endpoint-url-configuration-proposal · kdaily/aws-sdk: https://github.com/kdaily/aws-sdk/blob/endpoint-url-configuration-proposal/proposals/configure-endpoint-url.md
- amazon web services - Is there any way to specify --endpoint-url in aws cli config file - Stack Overflow: https://stackoverflow.com/questions/52494196/is-there-any-way-to-specify-endpoint-url-in-aws-cli-config-file

**Comment by vgorloff** [comment]
Ended up by setting `DYNAMODB_SHARE_DB=1` in `docker-compose.yml`. Now I can see tables from default region (eu-central-1) set in `serverless.yml` when using NoSQLWorkbench connected to LocalStack. Here is how `docker-compose.yml` looks on my side:

```yaml
version: "3.8"

services:
  localstack:
    restart: unless-stopped # See: compose-spec/compose-spec: https://github.com/compose-spec/compose-spec/blob/master/spec.md#restart
    container_name: "mca_aws"
    image: localstack/localstack:1.2.0
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4513:4510-4513" # External services port range. See also environment variables below.
    environment:
      - DEBUG=1
      - LS_LOG=trace

      # See: Persistence Mechanism | Docs: https://docs.localstack.cloud/localstack/persistence-mechanism/
      - PERSISTENCE=0 # If you changed this to "1", then you may wish to set volume (see "volumes" key below).

      - DOCKER_HOST=unix:///var/run/docker.sock # See: Use the Docker command line: https://docs.docker.com/engine/reference/commandline/cli/
      # See: External Service Port Range | Docs: https://docs.localstack.cloud/localstack/external-ports/
      - EXTERNAL_SERVICE_PORTS_START=4510 # (Range is included)
      - EXTERNAL_SERVICE_PORTS_END=4514 # (Range is excluded)

      - DISABLE_CORS_CHECKS=1
      - DYNAMODB_SHARE_DB=1 # When activated, DynamodDB will use a single database instead of separate databases for each credential and region.

      # See: Configuration | Docs: https://docs.localstack.cloud/localstack/configuration/
      - LAMBDA_REMOTE_DOCKER=0 # Keep In sync with `localstack.lambda.mountCode` in `serverless.yml`. When this value is 0, then value in `serverless.yml` expected to be "true".
    volumes:
      # You can disable (not in all cases) due performance issues.
      # See:
      # - on MacOS, mounting /tmp/localstack makes lambdas slow · Issue #2515 · localstack/localstack: https://github.com/localstack/localstack/issues/2515
      # - localstack/doc/troubleshoot at master · localstack/localstack: https://github.com/localstack/localstack/tree/master/doc/troubleshoot
      # See also: Persistence Mechanism | Docs: https://docs.localstack.cloud/localstack/persistence-mechanism/
      #
      # - "./volume:/var/lib/localstack"
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
