### ISSUE TITLE
bug: SQS queues not getting created during entrypoint

### ISSUE THREAD

**Issue by mjod** [localstack/localstack#5767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In localstack entrypoint script when trying to create a queue localstack says the queue was created successfully. On further investigating when running an `awslocal sqs list-queues` the queue does not show at all. Other services can not connect to the queue as well since it does not exist. For example: 
```
awslocal sqs create-queue --queue-name test-queue
echo "listing queues:"
awslocal sqs list-queues
echo "-------"
```
produces:
```
{
    "QueueUrl": "http://localhost:4566/000000000000/test-queue"
}
listing queues:
--------
```

### Expected Behavior

When listing queues the result should look like this:
```
# awslocal sqs list-queues
{
    "QueueUrls": [
        "http://localhost:4566/000000000000/test-queue"
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Docker-compose file:
```
version: '3.3'
services:
  localstack:
    image: localstack/localstack:0.14.1
    container_name: localstack
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-test_access_key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-test_secret_access_key}
      AWS_DEFAULT_REGION: us-east-1
      SERVICES: sqs,s3
    volumes:
      - ./localstack/entrypoints:/docker-entrypoint-initaws.d
 ```

entrypoint file[`entrypoint.sh`](put this in a the folder `./localstack/entrypoints`):
```
aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set default.region $AWS_DEFAULT_REGION
aws configure set default.output json

awslocal sqs create-queue --queue-name test-queue
echo "listing queues:"
awslocal sqs list-queues
echo "-------"
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.1
```
