### ISSUE TITLE
bug: NotFound: null when using copyObject

### ISSUE THREAD

**Issue by daelmaak** [localstack/localstack#5772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following typescript code

```typescript
const params: S3.Types.CopyObjectRequest = {
      Bucket: MediaS3Utils.BUCKET,
      CopySource: encodeURI(`${MediaS3Utils.BUCKET}/${srcKey}`),
      Key: dstKey,
      ACL: 'private',
      CacheControl: 'max-age=2629746' // 1 month
    };

    try {
      return await SYSTEM.aws.s3.copyObject(params).promise();
    }  catch (e) {
      throw new BugError(`Error copying S3 object ${srcKey} -> ${dstKey}. Error: ${e.message}`);
    }
```

ends up with 

```
NotFound: null
    at Request.extractError (***/node_modules/aws-sdk/lib/services/s3.js:690:35)
```

using localstack. This is not the case with real S3 though.

Note: `dstKey` and `srcKey` look like this `media/event/504c11b2-0e80-4a2d-a351-99ca9db2bed3/image/fd0216ed-9d56-4b44-8bc7-f5e135d97374/large.jpeg`

### Expected Behavior

The copy operation succeeds.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```
services:
  localstack:
    image: localstack/localstack:0.12.6
    ports:
      - "${API_IP:-0.0.0.0}:4566-4584:4566-4584"
    environment:
      - SERVICES=sqs,sns,s3,lambda,dynamodb,kinesis
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=api.local.***-staging.com
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

not sure what to include here

### Environment

```markdown
- OS: macOS 12.3
- LocalStack: 0.12.6
```
