### ISSUE TITLE
bug: LocalStack constantly timing out after under 3 minutes while starting up inside GitHub Actions

### ISSUE THREAD

**Issue by posita** [localstack/localstack#5813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Relevant GH Actions config:

``` yml
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
      - name: Initialize Submodules and Python Packages
        run: |
          git submodule update --init --recursive
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --requirement requirements-test.txt
      - name: Start LocalStack
        # See <https://docs.localstack.cloud/ci/github-actions/>
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          LOCALSTACK_SERVICES: cognito,s3,secretsmanager
        run: |
          # Install LocalStack CLI and awslocal command
          pip install localstack awscli-local
          docker pull localstack/localstack:0.14.2
          localstack start -d
          localstack wait -t 60  # wait up to one minute
          echo 'LocalStack started'
          localstack status services
          awslocal s3 ls
```

Result (reliably experienced on every build):

```
…
Digest: sha256:7a30cae7e98e3e1aec544533979b7c5ed09aceb2eb06d6e1386ef94e4f067f29
Status: Downloaded newer image for localstack/localstack:0.14.2
docker.io/localstack/localstack:0.14.2

     __                     _______ __             __
    / /   ____  _________ _/ / ___// /_____ ______/ /__
   / /   / __ \/ ___/ __ `/ /\__ \/ __/ __ `/ ___/ //_/
  / /___/ /_/ / /__/ /_/ / /___/ / /_/ /_/ / /__/ ,<
 /_____/\____/\___/\__,_/_//____/\__/\__,_/\___/_/|_|

 💻 LocalStack CLI 0.14.1.3

[18:47:42] starting LocalStack in Docker mode 🐳               localstack.py:131
           preparing environment                                bootstrap.py:743
           configuring container                                bootstrap.py:751
           starting container                                   bootstrap.py:757
[18:48:17] detaching                                            bootstrap.py:761
Error: timeout
Error: Process completed with exit code 1.

…
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

See above.

### Environment

```markdown
- OS: Ubuntu (on GH Actions)
- LocalStack: Tested with both 0.14.0 and 0.14.2
```

### Anything else?

I have also tried setting `timeout-minutes: 15`, but that doesn't work either. The build fails with LocalStack timing out on its own after just under 3 minutes.
