### ISSUE TITLE
bug: DynamoDb local secondary index not found

### ISSUE THREAD

**Issue by kzbt** [localstack/localstack#5831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the latest docker image, if we define a local secondary index for a dynamodb table and query it, localstack fails with `Index Not Found`

This behaviour is not seen in the previous version of the docker image 0.14.2. I believe this was introduced in a recent change from https://github.com/localstack/localstack/pull/5799

### Expected Behavior

Querying local secondary index should be supported like it previously was

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml
```
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb,cloudformation
      - DEFAULT_REGION=eu-west-1
      - START_WEB=false
```

cloudformation-template.yml
```
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  DomainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        - AttributeName: "LSI1SK"
          AttributeType: "N"
      BillingMode: "PAY_PER_REQUEST"
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      LocalSecondaryIndexes:
        - IndexName: "LSI1"
          KeySchema:
            - AttributeName: "PK"
              KeyType: "HASH"
            - AttributeName: "LSI1SK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      TableName: "<omitted>"
      Tags:
        - Key: "Name"
          Value: "<omitted>"
      TimeToLiveSpecification:
        AttributeName: "LastTimestamp"
        Enabled: true
```

    docker compose up

### Environment

```markdown
- OS: docker
- LocalStack: latest
```
