### ISSUE TITLE
bug: 500 Server Error trying to import or overwrite an API Gateway v1 REST API using YAML

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack's API Gateway v1 API is able to handle OpenAPI 3.x specs in JSON format, but returns an HTTP 500 error when given the exact same spec formatted as YAML.

### Expected Behavior

API Gateway v1 should be able to properly import/put valid OpenAPI 3.0 specs formatted as either JSON or YAML.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
---
version: '3.4'
services:
  localstack:
    image: localstack/localstack
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:443:443
      - 127.0.0.1:4510-4559:4510-4559
      - 127.0.0.1:4566:4566
    environment:
      DATA_DIR: /data
      DEBUG: 1
      DISABLE_CORS_CHECKS: 1
      DNS_ADDRESS: 127.0.0.1
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY:-}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
$ awslocal apigateway import-rest-api --body fileb://./mocked_api.yaml

An error occurred (500) when calling the ImportRestApi operation (reached max retries: 2):

$ awslocal apigateway import-rest-api --body fileb://./mocked_api.json
{
    "id": "te7c2uzptb",
    "createdDate": "2022-04-12T21:44:42-05:00",
    "version": "V1",
    "binaryMediaTypes": [],
    "apiKeySource": "HEADER",
    "endpointConfiguration": {
        "types": [
            "EDGE"
        ]
    },
    "tags": {},
    "disableExecuteApiEndpoint": false
}

$ awslocal apigateway put-rest-api --rest-api-id te7c2uzptb --mode overwrite --body fileb://./mocked_api.json
{
    "id": "te7c2uzptb",
    "createdDate": "2022-04-12T21:44:42-05:00",
    "version": "V1",
    "binaryMediaTypes": [],
    "apiKeySource": "HEADER",
    "endpointConfiguration": {
        "types": [
            "EDGE"
        ]
    },
    "tags": {},
    "disableExecuteApiEndpoint": false
}

$ awslocal apigateway put-rest-api --rest-api-id te7c2uzptb --mode overwrite --body fileb://./mocked_api.yaml

An error occurred (500) when calling the PutRestApi operation (reached max retries: 2):
```

### Environment

```markdown
- OS: MacOS 12.3
- LocalStack: 0.14.2
```

### Anything else?

mocked_api.json

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "echo",
    "description": "Simple mocked REST API",
    "version": "2022-04-12T15:36:55Z"
  },
  "paths": {
    "/echo/{data}": {
      "x-amazon-apigateway-any-method": {
        "responses": {
          "200": {
            "description": "200 response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Empty"
                }
              }
            }
          }
        },
        "x-amazon-apigateway-integration": {
          "type": "mock",
          "responses": {
            "default": {
              "statusCode": "200",
              "responseTemplates": {
                "application/json": "{\"data\": $input.params(\\\"data\\\"), \"response\": \"mocked\"}\n"
              }
            }
          },
          "requestTemplates": {
            "application/json": "{\"data\", $input.params(\\\"data\\\"), \"statusCode\": 200}"
          },
          "passthroughBehavior": "when_no_templates"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Empty": {
        "title": "Empty Schema",
        "type": "object"
      }
    }
  }
}
```

mocked_api.yaml

```yaml
openapi: 3.0.1
info:
  title: echo
  description: Simple mocked REST API
  version: 2022-04-12T15:36:55Z
paths:
  "/echo/{data}":
    x-amazon-apigateway-any-method:
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        type: mock
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: |
                {"data": $input.params(\"data\"), "response": "mocked"}
        requestTemplates:
          application/json: '{"data", $input.params(\"data\"), "statusCode": 200}'
        passthroughBehavior: when_no_templates
components:
  schemas:
    Empty:
      title: Empty Schema
      type: object
```
