### ISSUE TITLE
bug: CloudWatch log groups gone after container restart

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Even with a persistent data volume, CloudWatch log groups are deleted when the container stops.

### Expected Behavior

CloudWatch log groups reload after restart the same way other resources do.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
---
version: '3.4'
volumes:
  localstack:
services:
  localstack:
    image: localstack/localstack
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - localstack:/data
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:443:443
      - 127.0.0.1:4510-4559:4510-4559
      - 127.0.0.1:4566:4566
    environment:
      DATA_DIR: /data
      DEBUG: 1
      DISABLE_CORS_CHECKS: 1
      DNS_ADDRESS: 127.0.0.1
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY:-}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
$ docker compose up -d
[+] Running 3/3
 ⠿ Network localstack_test_default         Created
 ⠿ Volume "localstack_test_localstack"     Created
 ⠿ Container localstack_test-localstack-1  Started

$ awslocal logs describe-log-groups
{
    "logGroups": []
}

$ awslocal logs create-log-group --log-group-name /my/log/group

$ awslocal logs describe-log-groups
{
    "logGroups": [
        {
            "logGroupName": "/my/log/group",
            "creationTime": 1649829971374,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/my/log/group",
            "storedBytes": 0
        }
    ]
}

$ docker compose restart localstack
[+] Running 1/1
 ⠿ Container localstack_test-localstack-1  Started

$ awslocal logs describe-log-groups
{
    "logGroups": []
}
```

### Environment

```markdown
- OS: MacOS 12.3
- LocalStack: 0.1.4
```
