### ISSUE TITLE
bug: Some SSM actions return 500 errors after container restart

### ISSUE THREAD

**Issue by mbklein** [localstack/localstack#5854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting a new LocalStack container with a persistent data volume:

- `put-parameter` works as expected
- `get-parameter` works as expected
- `get-parameters-by-path` works as expected
- `describe-parameters` works as expected

After restarting the container:

- `put-parameter` works as expected
- `get-parameter` works as expected
- `get-parameters-by-path` returns an HTTP 500 error
- `describe-parameters` returns an HTTP 500 error

### Expected Behavior

All API actions continue to work after container restart

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
---
version: '3.4'
volumes:
  localstack:
services:
  localstack:
    image: localstack/localstack
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - localstack:/data
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:443:443
      - 127.0.0.1:4510-4559:4510-4559
      - 127.0.0.1:4566:4566
    environment:
      DATA_DIR: /data
      DEBUG: 1
      DISABLE_CORS_CHECKS: 1
      DNS_ADDRESS: 127.0.0.1
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY:-}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
$ docker compose up -d
[+] Running 3/3
 ⠿ Network localstack_test_default         Created
 ⠿ Volume "localstack_test_localstack"     Created
 ⠿ Container localstack_test-localstack-1  Started

$ awslocal ssm put-parameter --name /my-parameters/localstack-url --value https://localhost.localstack.cloud:4566/ --type String
{
    "Version": 1
}

$ awslocal ssm describe-parameters
{
    "Parameters": [
        {
            "Name": "/my-parameters/localstack-url",
            "Type": "String",
            "LastModifiedDate": "2022-04-13T01:20:21.992000-05:00",
            "LastModifiedUser": "N/A",
            "Version": 1,
            "DataType": "text"
        }
    ]
}

$ awslocal ssm get-parameter --name /my-parameters/localstack-url
{
    "Parameter": {
        "Name": "/my-parameters/localstack-url",
        "Type": "String",
        "Value": "https://localhost.localstack.cloud:4566/",
        "Version": 1,
        "LastModifiedDate": "2022-04-13T01:20:21.992000-05:00",
        "ARN": "arn:aws:ssm:us-east-1:000000000000:parameter/my-parameters/localstack-url",
        "DataType": "text"
    }
}

$ awslocal ssm get-parameters-by-path --recursive --path /
{
    "Parameters": [
        {
            "Name": "/my-parameters/localstack-url",
            "Type": "String",
            "Value": "https://localhost.localstack.cloud:4566/",
            "Version": 1,
            "LastModifiedDate": "2022-04-13T01:20:21.992000-05:00",
            "ARN": "arn:aws:ssm:us-east-1:000000000000:parameter/my-parameters/localstack-url",
            "DataType": "text"
        }
    ]
}

$ docker compose restart localstack
[+] Running 1/1
 ⠿ Container localstack_test-localstack-1  Started

$ awslocal ssm describe-parameters

An error occurred (500) when calling the DescribeParameters operation (reached max retries: 2):

$ awslocal ssm get-parameter --name /my-parameters/localstack-url
{
    "Parameter": {
        "Name": "/my-parameters/localstack-url",
        "Type": "String",
        "Value": "https://localhost.localstack.cloud:4566/",
        "Version": 1,
        "LastModifiedDate": "2022-04-13T01:20:21.992000-05:00",
        "ARN": "arn:aws:ssm:us-east-1:000000000000:parameter/my-parameters/localstack-url",
        "DataType": "text"
    }
}

$ awslocal ssm get-parameters-by-path --recursive --path /

An error occurred (500) when calling the GetParametersByPath operation (reached max retries: 2):
```

### Environment

```markdown
- OS: MacOS 12.3
- LocalStack: 0.14.2
```
