### ISSUE TITLE
bug: SQS Fifo does not work (version 0.14.2)

### ISSUE THREAD

**Issue by seanmajorpayne** [localstack/localstack#5890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm on an M1 mac. I had a queue with the same name as the following, but it was not a FIFO queue, so I deleted it and recreated. Although it let me create the queue, it didn't exist when I went to the URL.

So I upgraded from an older version of localstack thinking that might be the problem, however this still doesn't work.

```
awslocal sqs create-queue --queue-name us-east-1-dev-recorder-request.fifo --attributes FifoQueue=true
{
    "QueueUrl": "http://localhost:4566/000000000000/us-east-1-dev-recorder-request.fifo"
}
```

This appears to work and the url shows up when running list-queues, however going to the URL shows "no such bucket"

```
awslocal --endpoint-url=http://localhost:4566 sqs create-queue --queue-name bleebloo
```

This does work however without making a Fifo queue. Am I doing something wrong? This seems like it should work fine. I've tried using different names, but no fifo queues work.

### Expected Behavior

`awslocal sqs create-queue --queue-name us-east-1-dev-recorder-request.fifo --attributes FifoQueue=true`

This should create a queue that can be accessed at the returned URL.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```
services:
  localstack:
    image: localstack/localstack:0.14.2
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
   volumes:
         - "./tmp/localstack:/tmp/localstack"
         - "/var/run/docker.sock:/var/run/docker.sock"
         
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

`awslocal sqs create-queue --queue-name us-east-1-dev-recorder-request.fifo --attributes FifoQueue=true`


### Environment

```markdown
- OS: macOS Monteray 12.0.1
- LocalStack: 0.14.2
```

### Anything else?

http://localhost:4566/000000000000/test.fifo

For example after creating a test.fifo queue:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>000000000000</BucketName>
<RequestID>7a62c49f-347e-4fc4-9331-6e8eEXAMPLE</RequestID>
</Error>
```
