### ISSUE TITLE
bug: DynamoDB TransactGetItems always returns ResourceNotFoundException

### ISSUE THREAD

**Issue by ryan-ju** [localstack/localstack#5908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

* Create any table with any records
* Do a TransactGetItems on the table
* Localstack returns 
```
ResourceNotFoundException: Cannot do operations on a non-existent table
```

### Expected Behavior

TransactGetItems should succeed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker-compose up
```

`docker-compose.yml`
```
version: '3'

services:
  localstack:
    image: localstack/localstack
    environment:
      - DEFAULT_REGION=eu-west-2
      - SERVICES=dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 4566:4566
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#! /bin/bash
aws --endpoint-url=http://localhost:4566 dynamodb create-table --attribute-definitions AttributeName=forumId,AttributeType=S --table-name forum --key-schema AttributeName=forumId,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 > /dev/null
aws --endpoint-url=http://localhost:4566 dynamodb put-item --table-name forum --item '{"forumId": {"S": "forum001"}, "data": {"S": "helloworld"}}' > /dev/null
aws --endpoint-url=http://localhost:4566 dynamodb get-item --table-name forum --key '{"forumId": {"S": "forum001"}}' > /dev/null
# This one fails
aws --endpoint-url=http://localhost:4566 dynamodb transact-get-items --transact-items '[{"Get": {"Key":{"forumId": {"S": "forum001"}}, "TableName": "forum"}}]' > /dev/null
```

### Environment

```markdown
- OS: MacOS 10.15.7
- LocalStack: latest, digest 843db39ff1df83fd537e15b30e39d6fb8c3590efd6bf3f6f96b1734418fbd19f
```

### Anything else?

This works in `localstack/localstack:0.14.1`
