### ISSUE TITLE
bug: Creating an EFS File System fails with 'PutLifecycleConfiguration' for service 'efs' not yet implemented (using Pro License)

### ISSUE THREAD

**Issue by donrhummy** [localstack/localstack#5934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The creation fails with error:

> │ Error: error creating EFS file system (fs-935281b9588d0313) lifecycle configuration: : API action 
> │ 'PutLifecycleConfiguration' for service 'efs' not yet implemented
> │       status code: 501, request id: 9UNUWRUN4INEAL9I6GV3O91SJWEETM3E5CWX6A0P6BBBQQV7NJR5
> │ 
> │   with aws_efs_file_system.efs_volume,
> │   on ebs.tf line 36, in resource "aws_efs_file_system" "efs_volume":
> │   36: resource "aws_efs_file_system" "efs_volume" {

### Expected Behavior

It would create the EFS File System as it says it's supported: https://docs.localstack.cloud/aws/feature-coverage/

### How are you starting LocalStack?

With a docker-compose file

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose

```yaml
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-full
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
```shell
export LOCALSTACK_API_KEY=<hidden_key>
docker-compose -f localstack.yaml up
```
#### Terraform
```terraform
# Terraform configuration

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"

  # Notice this uses a diff syntax to refer to the
  # variable. Either is allowed, but the first one
  # guarantees it's a string
  access_key                  = "localstacktest"
  secret_key                  = "localstacktestkey"
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true
  s3_use_path_style           = true

  endpoints {
    # These are always this port in LocalStack
    ec2 = "http://localhost:4566"
    efs = "http://localhost:4566"
    iam = "http://localhost:4566"
    s3  = "http://localhost:4566"
    glacier = "http://localhost:4566"
    sns = "http://localhost:4566"
  }
}

resource "aws_efs_file_system" "efs" {

  creation_token   = "efs-unique"
  performance_mode = "generalPurpose"
  encrypted        = true
  lifecycle_policy {
    transition_to_ia = "AFTER_30_DAYS"
  }
  tags = {
    "Name" = "EFS Volume"
  }
}
```

You can also reproduce it following this tutorial guide which also fails: https://medium.com/avmconsulting-blog/creating-efs-file-system-and-mount-targets-using-terraform-6f8890201b13

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.2.3
```

### Anything else?

If I **don't** put in the lifecycle, then it fails with `Error: error reading EFS file system (fs-c40fb1d9f050a142) lifecycle configuration: : API action 'DescribeLifecycleConfiguration' for service 'efs' not yet implemented`

I am using a Pro license which it says was valid.
