### ISSUE TITLE
bug: DynamoDB Stream record missing event_id

### ISSUE THREAD

**Issue by ShedPlant** [localstack/localstack#5957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create:
- DynamoDB table
- DynamoDB table has stream
- Create lambda
- Create event source mapping between the DynamoDB stream and the lambda
- Create a SQS Queue

My lambda uses the aws powertools library to look at the record and send to a SQS.

This was working perfectly until today I ran `docker pull localstack/localstack.`
I think I was using a localstack version about a month old before, which worked.

Now, the event id from the DynamoDB Stream record is null:
This causes my lambda to crash later, and I can't test my workflow.

### Expected Behavior

DynamoDB Stream Record Event ID to be populated

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

With docker compose

```yaml
version: '3.8'

services:

  localstack:
    privileged: true
    image: localstack/localstack
    ports:
      - "${LOCALSTACK_PORT-4566}:4566"
    environment:
      - LOCALSTACK_SERVICES=${LOCALSTACK_SERVICES-sqs,ssm,kms,lambda,dynamodb}
      - LOCALSTACK_HOSTNAME=localstack
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=myproject_default
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Sample lambda

This is simplified but shows the essential problem

```python
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.utilities.batch import (
    BatchProcessor,
    EventType,
    batch_processor,
)
from aws_lambda_powertools.utilities.data_classes.dynamo_db_stream_event import (
    DynamoDBRecord,
)

logger = Logger(sampling_rate=0.1)

processor = BatchProcessor(event_type=EventType.DynamoDBStreams)
tracer = Tracer()


@tracer.capture_method
def record_handler(record: DynamoDBRecord):
    logger.info({"event_id": record.event_id})


@logger.inject_lambda_context
@tracer.capture_lambda_handler
@batch_processor(record_handler=record_handler, processor=processor)
def lambda_handler(event, context) -> None:
    return processor.response()

```

Logs:
```
{"level":"INFO","location":"record_handler:19","message":{"event_id":null},"timestamp":"2022-04-29 14:14:52,905+0000","service":"service_undefined","sampling_rate":0.1,"cold_start":true,"function_name":"users-vehicles-stream-forwarder","function_memory_size":"1536","function_arn":"arn:aws:lambda:eu-west-1:000000000000:function:users-vehicles-stream-forwarder","function_request_id":"2c11030f-090f-14b4-06d5-90e0b330521e","xray_trace_id":"1-dc99d00f-c079a84d433534434534ef0d"}
```

#### Other Setup

I have another python script using `boto3` to create the dynamodb table, lambda, event source mapping. It hasn't changed since this was working.

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```
