### ISSUE TITLE
question: How can I filter the services to be load? SERVICES env var does not seem to do it now

### ISSUE THREAD

**Issue by mromagnoli** [localstack/localstack#6007]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

Hi everyone, I'm using version `0.14.2` and I'm trying to only enable 2 services but when starting it enables all the services.
I also tried to use the `./localstack/default.env` file to set env vars but it doesn't seem to be read.

This is my config in my `docker-compose.yml` based on [repo's one](https://github.com/localstack/localstack/blob/master/docker-compose.yml)

```
localstack:
    image: localstack/localstack:0.14.2
    container_name: localstack_main
    ports:
      - "127.0.0.1:14510-14559:4510-4559"  # external service port range
      - "127.0.0.1:6645:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=dynamodb,s3
      - TMPDIR=/tmp/localstack
      - CONFIG_PROFILE=default    # <--- this should read the host's `.localstack/default.env` AFAIK
      - LAMBDA_REMOTE_DOCKER=false
      - DATA_DIR=${TMPDIR}/data
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - my-net
```
The host `ports` have been changed from the suggested ones to no conflict with other services using them.

`SERVICES` env was removed from the example `docker-compose.yml` file but I don't know what to use now.

Thanks in advance.

### Anything else?

If I query `localhost:6645/health`
All services appear as `available`
```
{
    "features": {
        "initScripts": "initialized"
    },
    "services": {
        "acm": "available",
        "apigateway": "available",
        "cloudformation": "available",
        "cloudwatch": "available",
        "config": "available",
        "dynamodb": "available",
        "dynamodbstreams": "available",
        "ec2": "available",
        "es": "available",
        "events": "available",
        "firehose": "available",
        "iam": "available",
        "kinesis": "available",
        "kms": "available",
        "lambda": "available",
        "logs": "available",
        "opensearch": "available",
        "redshift": "available",
        "resource-groups": "available",
        "resourcegroupstaggingapi": "available",
        "route53": "available",
        "route53resolver": "available",
        "s3": "available",
        "s3control": "available",
        "secretsmanager": "available",
        "ses": "available",
        "sns": "available",
        "sqs": "available",
        "ssm": "available",
        "stepfunctions": "available",
        "sts": "available",
        "support": "available",
        "swf": "available"
    },
    "version": "0.14.2"
}
```
