### ISSUE TITLE
Permissions denied while invoking lambda in docker

### ISSUE THREAD

**Issue by jitesh-prajapati** [localstack/localstack#603]
Permissions denied while invoking lambda in docker
```
[root@icpl10379 ~]# docker run -v "/tmp/localstack/zipfile.6120977d":/var/task -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME"  --rm "lambci/lambda:nodejs6.10" "users.handler"
START RequestId: cb93374a-f4bf-1bec-fd69-b53256b53704 Version: $LATEST
module initialization error: Error
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.Module._extensions..js (module.js:578:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
END RequestId: cb93374a-f4bf-1bec-fd69-b53256b53704
REPORT RequestId: cb93374a-f4bf-1bec-fd69-b53256b53704  Duration: 8.82 ms      B                                                                                        illed Duration: 100 ms  Memory Size: 1536 MB    Max Memory Used: 21 MB

{"errorMessage":"EACCES: permission denied, open '/var/task/users.js'","errorTyp                                                                                        e":"Error","stackTrace":["Object.fs.openSync (fs.js:641:18)","Object.fs.readFile                                                                                        Sync (fs.js:509:33)","Object.Module._extensions..js (module.js:578:20)","Module.                                                                                        load (module.js:487:32)","tryModuleLoad (module.js:446:12)","Function.Module._lo                                                                                        ad (module.js:438:3)","Module.require (module.js:497:17)","require (internal/mod                                                                                        ule.js:20:19)"]}
```

**Comment by whummer** [comment]
Potential duplicate of #600

**Comment by GeoffreyBooth** [comment]
I have the same issue. I downgraded to 0.8.5 and it started working for me. (Latest, 0.8.7 and 0.8.6 all demonstrated the issue.)

Here’s the error I see:

```
START RequestId: 62bdddb7-9147-14c7-0ac2-74d15f78613e Version: $LATEST
module initialization error: Error
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..js (module.js:662:20)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
2018-08-03T04:07:09.559802200Z 
{"errorMessage":"EACCES: permission denied, open '/var/task/exports.js'","errorType":"Error","stackTrace":["Object.fs.readFileSync (fs.js:551:33)","Object.Module._extensions..js (module.js:662:20)","Module.load (module.js:565:32)","tryModuleLoad (module.js:505:12)","Function.Module._load (module.js:497:3)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}
END RequestId: 62bdddb7-9147-14c7-0ac2-74d15f78613e
REPORT RequestId: 62bdddb7-9147-14c7-0ac2-74d15f78613e	Duration: 11.47 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 33 MB
```

I’m running LocalStack via `docker-compose`:

```yaml
version: "3"

services:
  localstack:
    image: localstack/localstack:0.8.5
    container_name: localstack
    hostname: localstack
    ports:
      - '4567-4582:4567-4582'
      - '8080:8080'
    restart: always
    environment:
      DEBUG: '1'
      SERVICES: apigateway,lambda,s3
      DEFAULT_REGION: us-east-1
      LAMBDA_EXECUTOR: docker
    volumes:
      - localstack_temp:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_temp:
```

Change the 0.8.5 to 0.8.6 and the issue appears.

**Comment by whummer** [comment]
Closing this issue as outdated/fixed. Please open a follow-up issue if the problem persists. Thanks

**Comment by orionstudt** [comment]
hey @whummer ! I'm currently experiencing this issue trying to run a javascript lambda in an azure devops pipeline. 

Specifically the:
```
Exception: Lambda process returned error status code: 1. Result: {"errorType":"Error","errorMessage":"EACCES: permission denied, open '/var/task/eventBroadcast.js'"}.
```

I am using the azure devops service containers in my pipeline to run localstack among other things, detailed here: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml

So my composition isn't exactly docker-compose syntax but it is close, and looks like this:
```
- container: localstack
      image: localstack/localstack:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        DEFAULT_REGION: us-east-1
        HOSTNAME: localstack
        HOSTNAME_EXTERNAL: localstack
        LAMBDA_EXECUTOR: docker
        SERVICES: 'dynamodb,kinesis,lambda,s3,sns,sqs'
        START_WEB: 0
```

Localstack has been working great in all other regards - just this issue trying to run a JS lambda. I can get you whatever log info you need.
