### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by n-erwen** [localstack/localstack#6058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I send a request to an endpoint with a Lambda request authorizer attached in API Gateway V2 , I receive the following error:

```
2022-05-12T15:45:11.586Z 81dd0f74-0cb9-1b04-c222-282c3fa1d6c0 ERROR Invoke Error  
{"errorType":"TypeError",
"errorMessage":"Cannot destructure property 'method' of 'authorizerEvent.requestContext.http' as it is undefined.",
"stack":["TypeError: Cannot destructure property 'method' of 'authorizerEvent.requestContext.http' as it is undefined."," 
   at validateRequestAndGenerateIAMPolicy (/var/task/src/handlers/apiKeyValidatorHandler.js:64001:5)"," 
       -> /var/task/src/handlers/webpack:/api/src/handlers/apiKeyValidatorHandler.ts:45:13","
    at handler (/var/task/src/handlers/apiKeyValidatorHandler.js:64047:12)","
        -> /var/task/src/handlers/webpack:/api/src/handlers/apiKeyValidatorHandler.ts:78:16","
    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]}
```

This is due to an API Gateway V1 Authorizer event being sent to the authorizer when a request is made, hence `requestContext.http` is undefined:

 ```
{
    "version": "1.0",
    "type": "REQUEST",
    "methodArn": "\"arn:aws:execute-api:{self.invocation_context.region_name}:{account_id}:\"\"{self.invocation_context.api_id}/{self.invocation_context.stage}/\"\"{self.invocation_context.method}{relative_path}\"",
    "identitySource": "",
    "authorizationToken": "",
    "resource": "/events",
    "path": "/events",
    "httpMethod": "POST",
    "headers": {
        ...
    },
    "queryStringParameters": {},
    "pathParameters": {},
    "stageVariables": null,
    "requestContext": {
        "path": "/events",
        "accountId": "000000000000",
        "apiId": "1ad30a26",
        "resourcePath": "/events",
        ...
    }
}
```

### Expected Behavior

The Lambda authorizer receives API Gateway V2 Authorizer events and can destructure properties (i.e. `method`) from `event.requestContext.http` without failing.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

- Create an API Gateway V2 with a custom lambda authorizer configured to authenticate incoming requests

- Paste the following line in the authorizer function's source code:

```
const { method, path } = authorizerEvent.requestContext.http
```

### Environment

```markdown
- OS: MacOS 11.6
- LocalStack: latest
```

**Comment by calvernaz** [comment]
Hi @n-erwen, thanks for reporting this! I just want to double check one thing before I start looking at this, are you specifying the authorizer payload format version?

**Comment by n-erwen** [comment]
I'm not specifying the authorizer payload format version, I assumed as I am using API Gateway V2 with the Lambda authorizer it would automatically use the V2 authorizer payload.

This is the serverless code I'm using to deploy the authorizer:

```
provider:
    ...
    httpApi:
        disableDefaultEndpoint: true
        authorizers:
            apiKeyValidatorAuthorizer:
                type: request
                    functionArn: arn:aws:lambda:eu-west-1:#{AWS::AccountId}:function:api-${self:provider.stage}-apiKeyValidator
                    identitySource: '$request.header.x-api-key'
```
