### ISSUE TITLE
InvalidParameterValues error when sending a message to FIFO queue with ContentBasedDeduplication

### ISSUE THREAD

**Issue by eyalroth** [localstack/localstack#6081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With AWS SDK for javascript:
1. Create FIFO queue with `ContentBasedDeduplication=true`.
2. Send a message to the queue with a group ID.
3. Receive error: `InvalidParameterValues: The Queue should either have ContentBasedDeduplication enabled or MessageDeduplicationId provided explicitly`.

### Expected Behavior

Message should be sent without an issue.

### How are you starting LocalStack?

With a docker-compose file

##### Local

```yml
version: "3.8"

services:
  localstack:
    container_name: "my_localstack"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:${LOCALSTACK_PORT}:4566"
    environment:
      - SERVICES=s3,sqs
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=${DEBUG- }
    volumes:
      - "../../../out/localstack/tmp:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

##### CircleCI

```yml
executors:
      - image: localstack/localstack
        environment:
          DEBUG: 1
          SERVICES: s3,sqs
          DATA_DIR: /tmp/localstack/data
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands).

```js
const sqs = new AWS.SQS(configuration);

const { QueueUrl } = await sqs.createQueue({
  QueueName: 'foo',
  Attributes: {
    VisibilityTimeout: '5',
    FifoQueue: 'true',
    ContentBasedDeduplication: 'true',
  },
})
  .promise();

// fails
await this.sqs.sendMessage({
  QueueUrl,
  MessageBody: '{}',
  MessageGroupId: 'bar',
})
  .promise();
```

### Environment

```markdown
- OS 1 (local): MacOS 11.3 (MBP 2019)
- OS 2 (CircleCI): 
- LocalStack: "latest" (`using image localstack/localstack@sha256:a761dde37766be8381db78b51b316965cf6ff7930ad7a54ca05791b04ba2d1b2`)
```

### Anything else?

The code worked last week (`using image localstack/localstack@sha256:c75e7020497ad8cad4a9c62ed8156cfc70a576109a8ce157e8a9f1d9ff9e43ba`).

Looks like [a new version](https://hub.docker.com/layers/localstack/localstack/localstack/latest/images/sha256-80ada4318a6f0b23bdfc2c8fb22f84502ff8dab4a93d523cd20377d41c2e808f?context=explore) was pushed to [docker hub](https://hub.docker.com/r/localstack/localstack/tags) "2 hours ago", and it seems to be causing the issue.
