### ISSUE TITLE
bug: SQS reports that "MessageGroupId" is required when it is not

### ISSUE THREAD

**Issue by shadowhand** [localstack/localstack#6107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling `ReceiveMessage` on a FIFO queue, I _sometimes_ get HTTP 400 with the message: 

```
  [Aws\Sqs\Exception\SqsException]                                                                                                    
  Error executing "ReceiveMessage" on "http://localhost:4566/queue/us-west-2/000000000000/commands.fifo"; AWS HTTP error: Client er   
  ror: `POST http://localhost:4566/queue/us-west-2/000000000000/commands.fifo` resulted in a `400 Bad Request` response:              
  <?xml version='1.0' encoding='utf-8'?>                                                                                              
  <ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>Mi (truncated...)                                    
   MissingParameter (client): The request must contain the parameter MessageGroupId. - <?xml version='1.0' encoding='utf-8'?>         
  <ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Code>MissingParameter</Code><Message>The request must c   
  ontain the parameter MessageGroupId.</Message><Type>Sender</Type></Error><RequestId>88L3LXATEGVS0JF5S9BZDEQA95ELASZCKL4EJM5NCX9Y3   
  DHMP2RK</RequestId></ErrorResponse>  
```

There doesn't seem to be a particular pattern to it, and restarting localstack makes it go away. 

### Expected Behavior

`RecieveMessage` should never require a `MessageGroupId` parameter, because such a parameter [does not exist][1].

[1]: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker compose up -d
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

My calling code is (PHP SDK):

```php
        $options = [
            'QueueUrl' => $this->config->url,
            'WaitTimeSeconds' => 4,
            'MaxNumberOfMessages' => 10,
            'VisibilityTimeout' => 10,
        ];

        $result = $this->client->receiveMessage($options);
```

### Environment

```markdown
- OS: Mac OS 12.3
- LocalStack: 0.14.3
```

**Comment by thrau** [comment]
Hey Woody @shadowhand, thanks for reporting. Could you please share the code you use to create the queue and to send the messages?

If you could reproduce it with `awslocal sqs` cli commands that would be extremely helpful, or at least the SDK invocations.

Moreover: what version of the PHP SDK are you using?

For now you can start localstack with `PROVIDER_OVERRIDE_SQS=legacy` to use the old (deprecated) provider to make it work again.

**Comment by shadowhand** [comment]
AWS SDK version 3.222.15

I can't really provide the info that we are using to create the queue, because we are reading the values directly out of `serverless.yml` and then manipulating the data to create the queue parameters. This particular queue has the following config:

```yml
    CommandsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: commands.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 60
        KmsMasterKeyId: ${self:custom.config.QueueKms}
        RedrivePolicy:
          maxReceiveCount: 3
          deadLetterTargetArn: !GetAtt CommandsFailedQueue.Arn
```

**Comment by shadowhand** [comment]
```
docker exec -it localstack awslocal --region=us-west-2 sqs receive-message --queue-url "http://localhost:4566/queue/us-west-2/000000000000/commands.fifo" --wait-time-seconds 4 --max-number-of-messages 1 --visibility-timeout 4

An error occurred (MissingParameter) when calling the ReceiveMessage operation: The request must contain the parameter MessageGroupId.
```

**Comment by shadowhand** [comment]
And then after about 3-4 tries:

```
docker exec -it localstack awslocal --region=us-west-2 sqs receive-message --queue-url "http://localhost:4566/queue/us-west-2/000000000000/commands.fifo" --wait-time-seconds 4 --max-number-of-messages 1 --visibility-timeout 4
{
    "Messages": [
        {
            "MessageId": "3bd25bf4-8e1f-4491-84e4-577949b69e8c",
            "ReceiptHandle": "oN4dKWyfod9HXzeLtjUbzEFfxU1QNQ5dxMm7FjbnVR91LPM0kDUpK6skPMmDahns3NN8ROIDzKoeh2KSgByl4pdyArTDyWlw87SQAIXFxs3zZTQxYJKnYxmpDzLn4rqfPzEACC8rkmtevhGVCSxS79Eodi8xLkJ4RPOtKugLuGBv=",
            "MD5OfBody": "f39fbc626e4b8d4cd97b2c4404a91105",
            "Body": "/* snip */"
        }
    ]
}
```

**Comment by shadowhand** [comment]
Is it possible that the new SQS backend is not multi-thread safe? Because we have a cron job operating in the background that performs the ReceiveMessage every minute.

**Comment by thrau** [comment]
i'll start some investigations. since the `MissingParameter` on `MessageGroupId` is only raised on `send_message` events, and you are having the issues on `receive_message`, i'm assuming it has something to do with the combination of fifo content-based dedup and the redrive policy.

**Comment by shadowhand** [comment]
@thrau I looked through the SQS API and didn't see anything obvious that would have caused this error. Is it possible that it is being raised when the visibility timeout causes a FIFO message to be returned to the queue? It just seems like an impossible error to encounter with a ReceiveMessage operation.

**Comment by thrau** [comment]
@shadowhand could you also provide the config of the `CommandsFailedQueue` DLQ?

**Comment by shadowhand** [comment]
```yml
    CommandsFailedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: commands-failed.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        MessageRetentionPeriod: 1209600 # 14 days
        KmsMasterKeyId: ${self:custom.config.QueueKms}
```
