### ISSUE TITLE
bug: redshift connector isn't working on localstack's implementation on the latest version

### ISSUE THREAD

**Issue by RobertLucian** [localstack/localstack#6131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The redshift connector isn't working on localstack, although redshift clusters can be deployed. For the following code block, I'm getting the following error.

```python
>> conn = redshift_connector.connect(host="localhost.localstack.cloud", port=4512, database="default_db", user="awsuser", password="H7:<_-~E=W3L:nx9&7QEv!sxKCXsMEyB", ssl=False)

redshift_connector.error.ProgrammingError: {'S': 'FATAL', 'V': 'FATAL', 'C': '42704', 'M': 'unrecognized configuration parameter "client_protocol_version"', 'F': 'guc.c', 'L': '6213', 'R': 'set_config_option'}
```

### Expected Behavior

Expected behavior is for the connection to the redshift cluster to work (`redshift_connector.connect`).

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
version: "3.8"

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack-full@sha256:f4592933b3237b6d147e2852cfdc7cc1197514ad4e544efc2a490300d9899565
    networks:
      - default
    ports:
      - "127.0.0.1:53:53"                         # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"                     # only required for Pro (DNS)
      - "443:443"                       # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "4510-4559:4510-4559"           # external service port range
      - "4566-4584:4566-4584"           # LocalStack Edge Proxy 
    environment:
      - DATA_DIR=${DATA_DIR-}
      - DEBUG=${DEBUG-1}
      - DISABLE_CORS_CHECKS=1 # Whether to disable all CSRF mitigations. 1 for yes, 0 for no.
      - DNS_ADDRESS=127.0.0.1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EC2_VM_MANAGER=docker
      - HOSTNAME=localhost # Name of the host to expose the services internally. For framework-internal communication, e.g., services are started in different containers using docker-compose
      - HOSTNAME_EXTERNAL=localhost # Name of the host to expose the services externally. This host is used, e.g., when returning queue URLs from the SQS service to the client.
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=0
      - LAMBDA_DOCKER_NETWORK=host # lambdas need access to localstack & rds
      - LAMBDA_DOCKER_FLAGS=-v /var/run/docker.sock:/var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - LOG_LICENSE_ISSUES=${LOG_LICENSE_ISSUES-1}
      - LS_LOG=debug
      - USE_LIGHT_IMAGE=0
      - ENFORCE_IAM=0
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: "sleep 100000000"
networks:
  default:
    name: localstack
    driver: bridge
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```python
role = iam.Role(
    self,
    "RedshiftOfflineStoreRole",
    assumed_by=iam.ServicePrincipal("redshift.amazonaws.com"),
    managed_policies=[
        iam.ManagedPolicy.from_aws_managed_policy_name("AmazonS3FullAccess"),
        iam.ManagedPolicy.from_aws_managed_policy_name(
            "AmazonRedshiftFullAccess"
        ),
    ],
)

cluster_secret = sm.Secret(
    self,
    f"{REDSHIFT_OFFLINE_STORE}Secret",
    secret_name=REDSHIFT_OFFLINE_STORE_CLUSTER_MASTER_SECRET_NAME,
    removal_policy=RemovalPolicy.DESTROY,
    generate_secret_string=sm.SecretStringGenerator(
        exclude_characters="/@\"\ '"  # not allowed in Redshift passwords
    ),
)

cluster_subnet_group = redshift.ClusterSubnetGroup(
    self,
    REDSHIFT_OFFLINE_STORE_CLUSTER_SUBNET_GROUP,
    description=REDSHIFT_OFFLINE_STORE_CLUSTER_SUBNET_GROUP,
    removal_policy=RemovalPolicy.DESTROY,
    vpc=vpc.instance,
    vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PUBLIC),
)
cluster = redshift.Cluster(
    self,
    REDSHIFT_OFFLINE_STORE_CLUSTER,
    master_user=redshift.Login(
        master_username=REDSHIFT_OFFLINE_STORE_CLUSTER_MASTER_USERNAME,
        master_password=cluster_secret.secret_value,
    ),
    roles=[role],
    vpc=vpc.instance,
    cluster_type=redshift.ClusterType.SINGLE_NODE,
    subnet_group=cluster_subnet_group,
    security_groups=[vpc.redshift_offline_store_cluster_sg],
    publicly_accessible=True,
)
```

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS
- LocalStack: latest (more specifically, this Docker version `localstack/localstack-full@sha256:f4592933b3237b6d147e2852cfdc7cc1197514ad4e544efc2a490300d9899565`, which is from about 2 weeks ago).
- `redshift-connector` library: 2.0.906
```

### Anything else?

A describe of the Redshift cluster on Localstack:

```bash
(stack) ubuntu@ip-172-31-1-88:~/github/magnus/backend$ awslocal redshift describe-clusters
{
    "Clusters": [
        {
            "ClusterIdentifier": "MagnusStackdevRankingServiceR-RedshiftOfflineStoreClus-eafd9d45",
            "NodeType": "dc2.large",
            "ClusterStatus": "available",
            "MasterUsername": "awsuser",
            "DBName": "default_db",
            "Endpoint": {
                "Address": "localhost.localstack.cloud",
                "Port": 4512
            },
            "ClusterCreateTime": "2022-05-05T17:14:50.857000+00:00",
            "AutomatedSnapshotRetentionPeriod": 1,
            "ClusterSecurityGroups": [
                {
                    "ClusterSecurityGroupName": "Default",
                    "Status": "active"
                }
            ],
            "VpcSecurityGroups": [
                {
                    "VpcSecurityGroupId": "sg-4e113409d367d11a0",
                    "Status": "active"
                }
            ],
            "ClusterParameterGroups": [
                {
                    "ParameterGroupName": "default.redshift-1.0",
                    "ParameterApplyStatus": "in-sync"
                }
            ],
            "ClusterSubnetGroupName": "subnet-805061a2-subnet-35af9225",
            "AvailabilityZone": "us-east-2a",
            "PreferredMaintenanceWindow": "Mon:03:00-Mon:03:30",
            "PendingModifiedValues": {},
            "ClusterVersion": "1.0",
            "AllowVersionUpgrade": true,
            "NumberOfNodes": 1,
            "PubliclyAccessible": true,
            "Encrypted": true,
            "Tags": [],
            "KmsKeyId": "",
            "EnhancedVpcRouting": false,
            "IamRoles": [
                {
                    "IamRoleArn": "arn:aws:iam::000000000000:role/MagnusStackdevRankingServiceR-RedshiftOfflineStoreRole-dcdcfe7b",
                    "ApplyStatus": "in-sync"
                }
            ]
        }
    ]
}
```

Also talked to the Localstack team through the Pro channel and they've also mentioned that a temporarily fix could be removing the following 3 lines from the redshift connector library: https://github.com/aws/amazon-redshift-python-driver/blob/3906211974c00d2d36a470eb0536b8f96681c158/redshift_connector/core.py#L534-L536
