### ISSUE TITLE
bug: Received SQS message attribute ApproximateFirstReceiveTimestamp is a floating point value instead of an integer timestamp

### ISSUE THREAD

**Issue by MSPigl** [localstack/localstack#6146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SQS message attribute `ApproximateFirstReceiveTimestamp` has a decimal value in addition to the timestamp integer. Example response payload from a `sqs receive-message` request:

```
{
    "Messages": [
        {
            "MessageId": "4392033b-e522-4f76-bd93-f9ea24acecec",
            "ReceiptHandle": "MmJiYmI1YzUtMWFkYy00YWMzLTlmNGUtMjA4ZjM2MGNlNzRlIGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6dGVzdC1xdWV1ZSA0MzkyMDMzYi1lNTIyLTRmNzYtYmQ5My1mOWVhMjRhY2VjZWMgMTY1MzQ5OTMyOS44MzI4NzAy",
            "MD5OfBody": "4e121647549e21089f8d89c271f2e344",
            "Body": "this is a test",
            "Attributes": {
                "SenderId": "000000000000",
                "SentTimestamp": "1653499304",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1653499329.8328702"
            }
        }
    ]
}
```

This is troublesome when attempting to parse the attribute string value, as libraries such as [amazon-sqs-java-temporary-queues-client](https://github.com/awslabs/amazon-sqs-java-temporary-queues-client) perform a direct `Long.parseLong(string)` on the attribute value, which results in an exception being thrown since the input string contains a decimal value.

### Expected Behavior

The SQS message attribute `ApproximateFirstReceiveTimestamp` value should be an integer timestamp, just like the `SentTimestamp` attribute value. Example expected response payload from a `sqs receive-message` request:

```
{
    "Messages": [
        {
            "MessageId": "4392033b-e522-4f76-bd93-f9ea24acecec",
            "ReceiptHandle": "MmJiYmI1YzUtMWFkYy00YWMzLTlmNGUtMjA4ZjM2MGNlNzRlIGFybjphd3M6c3FzOnVzLWVhc3QtMTowMDAwMDAwMDAwMDA6dGVzdC1xdWV1ZSA0MzkyMDMzYi1lNTIyLTRmNzYtYmQ5My1mOWVhMjRhY2VjZWMgMTY1MzQ5OTMyOS44MzI4NzAy",
            "MD5OfBody": "4e121647549e21089f8d89c271f2e344",
            "Body": "this is a test",
            "Attributes": {
                "SenderId": "000000000000",
                "SentTimestamp": "1653499304",
                "ApproximateReceiveCount": "1",
                "ApproximateFirstReceiveTimestamp": "1653499329"
            }
        }
    ]
}
```

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
I am deploying LocalStack in a local Kubernetes cluster via Minikube.

##### localstack.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
data:
  init.sh: |
    #!bin/bash
    set -e

    echo "Creating AWS profile."
    aws configure set aws_access_key_id test
    aws configure set aws_secret_access_key test
    aws configure set region us-east-1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "sqs"
          volumeMounts:
            - name: localstack-init-volume
              mountPath: /docker-entrypoint-initaws.d
      volumes:
        - name: localstack-init-volume
          configMap:
            name: localstack-config
  serviceName: localstack-service
---
apiVersion: v1
kind: Service
metadata:
  name: localstack-service
  labels:
    app: localstack
spec:
  selector:
    app: localstack
  ports:
    - port: 4566
      protocol: TCP
```    
`kubectl apply -f kubernetes/localstack.yaml`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    kubectl exec localstack-0 -- awslocal sqs create-queue --queue-name test-queue
    kubectl exec localstack-0 -- awslocal sqs send-message --queue-url "http://localhost:4566/000000000000/test-queue" --message-body "this is a test"
    kubectl exec localstack-0 -- awslocal sqs receive-message --queue-url "http://localhost:4566/000000000000/test-queue" --attribute-names All

I haven't tried this on docker-compose as I don't use that, but given the nature of this bug I'd suspect that the same issue would exist there regardless of how LocalStack is started.

### Environment

```markdown
- OS: macOS Monterey 12.4
- LocalStack: latest
```
