### ISSUE TITLE
question: Hot swapping for Lambda container image with Python dependencies

### ISSUE THREAD

**Issue by ptrhck** [localstack/localstack#6181]
### Is there an existing issue for this?

- [X] I have searched the existing issues and read the documentation

### Question

I have been following the serverless example and added the [local code mounting](https://docs.localstack.cloud/integrations/serverless-framework/#local-code-mounting-for-lambda-functions). Then I tried switching to use a custom container image for the Lambda function. The following problem should be the same for a container image using an AWS-provided base image.

Imagine the following custom image for Python:

```Dockerfile
# Define global args
ARG FUNCTION_DIR="/home/app/"
ARG RUNTIME_VERSION="3.9"
ARG DISTRO_VERSION="3.12"

# Stage 1 - bundle base image + runtime
# Grab a fresh copy of the image and install GCC
FROM python:${RUNTIME_VERSION}-alpine${DISTRO_VERSION} AS python-alpine
# Install GCC (Alpine uses musl but we compile and link dependencies with GCC)
RUN apk add --no-cache \
    libstdc++

# Stage 2 - build function and dependencies
FROM python-alpine AS build-image
# Install aws-lambda-cpp build dependencies
RUN apk add --no-cache \
    build-base \
    libtool \
    autoconf \
    automake \
    libexecinfo-dev \
    make \
    cmake \
    libcurl
# Include global args in this stage of the build
ARG FUNCTION_DIR
ARG RUNTIME_VERSION
# Create function directory
RUN mkdir -p ${FUNCTION_DIR}
# Copy handler function
COPY app/* ${FUNCTION_DIR}
# Optional – Install the function's dependencies
# RUN python${RUNTIME_VERSION} -m pip install -r requirements.txt --target ${FUNCTION_DIR}
# Install Lambda Runtime Interface Client for Python
RUN python${RUNTIME_VERSION} -m pip install awslambdaric --target ${FUNCTION_DIR}

# Stage 3 - final runtime image
# Grab a fresh copy of the Python image
FROM python-alpine
# Include global arg in this stage of the build
ARG FUNCTION_DIR
# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}
# Copy in the built dependencies
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}
# (Optional) Add Lambda Runtime Interface Emulator and use a script in the ENTRYPOINT for simpler local runs
ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/bin/aws-lambda-rie
COPY entry.sh /
RUN chmod 755 /usr/bin/aws-lambda-rie /entry.sh
ENTRYPOINT [ "/entry.sh" ]
CMD [ "app.handler" ]
```
And this `entry.sh`:

```sh
#!/bin/sh
if [ -z "${AWS_LAMBDA_RUNTIME_API}" ]; then
    exec /usr/bin/aws-lambda-rie /usr/local/bin/python -m awslambdaric $1
else
    exec /usr/local/bin/python -m awslambdaric $1
fi
```

Now, to enable hot swapping I have set the following in the `docker-compose.yaml`:

```yaml
services:
  localstack:
    # ...
    environment:
      DEBUG: 1
      HOST_TMP_FOLDER: ${TMPDIR:-/tmp/}localstack
      DOCKER_HOST: unix:///var/run/docker.sock
      LAMBDA_EXECUTOR: docker-reuse
      LAMBDA_REMOTE_DOCKER: 0
      LAMBDA_STAY_OPEN_MODE: 0
      LAMBDA_DOCKER_FLAGS: -p 19891:19891
      LAMBDA_DOCKER_NETWORK: example_project_default
      # ...
    volumes:
      # ...
      - "/absolute/path/to/code:/absolute/path/to/code"
```

Now I deploy the application with `LAMBDA_EXECUTOR=docker-reuse && LAMBDA_MOUNT_CWD:/absolute/path/to/code && sls deploy -s local`. The application works fine, but code reloading is not. The reason is that localstack always mounts to `/var/task` as seen [here](https://github.com/localstack/localstack/blob/1adfeb2e9f54f448442dffba39d244024bba71cf/localstack/services/awslambda/lambda_executors.py#L1235), whereas the function code lives in `FUNCTION_DIR="/home/app/"`. Of course, I could change this to `/var/task`, but now the mount will override the whole folder on the Lambda docker container, including the installed Python dependencies. Any idea how this can be resolved/worked around?
