### ISSUE TITLE
bug: KMS ListAliases does not honor the KeyId parameter

### ISSUE THREAD

**Issue by e-nikolov** [localstack/localstack#6193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I specify a KeyId, it still lists all aliases

### Expected Behavior

Only the aliases of the specified key should be returned

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4510-4559:4510-4559" # external service port range
      - "4566:4566" # LocalStack Edge Proxy
    environment:
      - DEBUG=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS: Ubuntu 20.04 on WSL2
- LocalStack: latest
```

### Anything else?

It works correctly with `KMS_PROVIDER=local-kms`, so it is probably an issue with moto
