### ISSUE TITLE
bug: 0.14 not honoring `hostPort` when starting containers in task definitions

### ISSUE THREAD

**Issue by j-sv** [localstack/localstack#6225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Version 0.13 of Localstack correctly used the defined `hostPort` of a task definition to bind the corresponding port on the host when starting a container. 0.14 seems to use a random port number instead.

```bash
$ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_ecs_cluster.cluster will be created
  + resource "aws_ecs_cluster" "cluster" {
      + arn                = (known after apply)
      + capacity_providers = (known after apply)
      + id                 = (known after apply)
      + name               = "cluster"
      + tags_all           = (known after apply)

      + default_capacity_provider_strategy {
          + base              = (known after apply)
          + capacity_provider = (known after apply)
          + weight            = (known after apply)
        }

      + setting {
          + name  = (known after apply)
          + value = (known after apply)
        }
    }

  # aws_ecs_service.service will be created
  + resource "aws_ecs_service" "service" {
      + cluster                            = (known after apply)
      + deployment_maximum_percent         = 200
      + deployment_minimum_healthy_percent = 100
      + desired_count                      = 1
      + enable_ecs_managed_tags            = false
      + enable_execute_command             = false
      + iam_role                           = (known after apply)
      + id                                 = (known after apply)
      + launch_type                        = "FARGATE"
      + name                               = "service"
      + platform_version                   = (known after apply)
      + scheduling_strategy                = "REPLICA"
    }

  # aws_ecs_task_definition.service will be created
  + resource "aws_ecs_task_definition" "service" {
      + arn                   = (known after apply)
      + container_definitions = jsonencode(
            [
              + {
                  + cpu          = 512
                  + essential    = true
                  + image        = "nginx:1.22-alpine"
                  + memory       = 512
                  + name         = "nginx"
                  + portMappings = [
                      + {
                          + containerPort = 80
                          + hostPort      = 8080
                        },
                    ]
                },
            ]
        )
      + family                = "service"
      + id                    = (known after apply)
      + network_mode          = (known after apply)
      + revision              = (known after apply)
      + skip_destroy          = false
      + tags_all              = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.
aws_ecs_cluster.cluster: Creating...
aws_ecs_task_definition.service: Creating...
aws_ecs_task_definition.service: Creation complete after 0s [id=service]
aws_ecs_cluster.cluster: Still creating... [10s elapsed]
aws_ecs_cluster.cluster: Creation complete after 10s [id=arn:aws:ecs:us-east-1:000000000000:cluster/cluster]
aws_ecs_service.service: Creating...
aws_ecs_service.service: Creation complete after 0s [id=arn:aws:ecs:us-east-1:000000000000:service/cluster/service]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

I expect the `nginx` container to bind port `8080` and forward it to `80`, instead I get `58719`.

```bash
$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                                                                                            NAMES
a1e7ae510b5b        nginx:1.22-alpine              "/docker-entrypoint.…"   4 seconds ago       Up 2 seconds        0.0.0.0:58719->80/tcp                                                                                                                            localstack_service_1_0_04664c18
f9f7e3dc4d29        localstack/localstack:0.14.3   "docker-entrypoint.sh"   48 seconds ago      Up 45 seconds       127.0.0.1:53->53/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:4510-4559->4510-4559/tcp, 127.0.0.1:4566->4566/tcp, 127.0.0.1:5432->5432/tcp, 5678/tcp   example_localstack_1
```

### Expected Behavior

The same Terraform code deployed using 0.13.3 gives the following (i.e., binding `hostPort` `8080`).

```bash
$ docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                      NAMES
35d8b7a7fc62        nginx:1.22-alpine              "/docker-entrypoint.…"   4 seconds ago       Up 2 seconds        0.0.0.0:8080->80/tcp                                                                                                                                       localstack_service_1_0
7e8ff1e2df35        localstack/localstack:0.13.3   "docker-entrypoint.sh"   2 minutes ago       Up 2 minutes        127.0.0.1:53->53/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:4510-4559->4510-4559/tcp, 127.0.0.1:4566->4566/tcp, 4571/tcp, 127.0.0.1:5432->5432/tcp, 5678/tcp   example_localstack_1
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`main.tf`
```terraform
resource "aws_ecs_cluster" "cluster" {
  name = "cluster"
}

resource "aws_ecs_task_definition" "service" {
  family = "service"
  container_definitions = jsonencode([
    {
      name      = "nginx"
      image     = "nginx:1.22-alpine"
      cpu       = 512
      memory    = 512
      essential = true
      portMappings = [
        {
          containerPort = 80
          hostPort      = 8080
        }
      ]
    },
  ])
}

resource "aws_ecs_service" "service" {
  name            = "service"
  cluster         = aws_ecs_cluster.cluster.id
  desired_count   = 1
  launch_type     = "FARGATE"
  task_definition = aws_ecs_task_definition.service.arn
}
```

`docker-compose.yml`
```yaml
version: '3'
services:
  localstack:
    image: localstack/localstack:0.14.3
    privileged: true
    environment:
      - SERVICES=ec2,ecs,events
      - TEST_AWS_ACCOUNT_ID=000000000000
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - HOSTNAME_FROM_LAMBDA=localstack
      - LAMBDA_DOCKER_NETWORK=example_default
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DNS_ADDRESS=127.0.0.1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - HOST_TMP_FOLDER="/tmp/localstack"
      - ENFORCE_IAM=0
      - DEBUG=0
      - LS_LOG=warn
      - EAGER_SERVICE_LOADING=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:5432:5432"
    restart: on-failure
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 0.14.3
```
