### ISSUE TITLE
The Locastack connection broken on Kubernetes in M1 Mac.

### ISSUE THREAD

**Issue by opsmilesum** [localstack/localstack#6253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi team, when I try to build the localstack at the Kubernetes as below by running `kubectl apply -f my-localstack.yaml`
```yaml
# my-localstack.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack
        resources:
          limits:
            memory: 500Mi
        livenessProbe:
          tcpSocket:
            port: 4566
        readinessProbe:
          exec:
            command:
              - /usr/bin/awslocal
              - sts
              - get-caller-identity
        ports:
        - containerPort: 4566
          name: edge
        env:
          - name: SERVICES
            value: "kinesis"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: localstack
  ports:
  - port: 80
    targetPort: edge
---
```
I checked the pod log and seems it already start now:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/96011359/173190909-e38e28d4-5955-46b9-a20d-00a794203ff0.png">

But when I run the `kubectl exec` into the container, and try to run `awslocal kinesis list-streams`,  I found the connection is broken.
```shell
root@localstack-78c598d56c-6rwhk:/opt/code/localstack# awslocal kinesis list-streams


Connection was closed before we received a valid response from endpoint URL: "http://localhost:4566/".
root@localstack-78c598d56c-6rwhk:/opt/code/localstack#
```

So although the log said it starts but the real connection is broken, seems a bug, I'm not know whether it's related to my machine.

My environment:
MacOS: M1 Monterey Version 12.2.1

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Above

### Environment

```markdown
- OS: 
- LocalStack:
```
