### ISSUE TITLE
persistence does not work

### ISSUE THREAD

**Issue by biergit** [localstack/localstack#6281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running `DATA_DIR=/tmp/localstack/data SERVICES=sqs DEBUG=1 localstack start` followed by `awslocal sqs create-queue --queue-name InboundQueue`. The queue is successfully created but gone after restart of localstack. 
`/tmp/localstack/data/recorded_api_calls.json` is empty.

### Expected Behavior

Persistence works

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    DATA_DIR=/tmp/localstack/data SERVICES=sqs DEBUG=1 localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal sqs create-queue --queue-name InboundQueue

### Environment

```markdown
- OS: Ubuntu 20.04 on WSL Docker Desktop 4.9.0
- LocalStack: 0.14.3.2
```

**Comment by giograno** [comment]
Dear @biergit, thanks for reporting the issue.

In order to use our persistence mechanism, you should be a LocalStack Pro user and start LocalStack with a `LOCALSTACK_API_KEY=...` option.

Your `/tmp/localstack/data/recorded_api_calls.json` is empty because we discontinued the persistence mechanism implemented in the community version in [0.13.1](https://github.com/localstack/localstack/releases/tag/v0.13.1). You can find a detailed explanation of our reasoning in this comment: https://github.com/localstack/localstack/issues/3881#issuecomment-1004009450.
The record/replay-based persistence mechanism will be in fact soon removed completely.

Please let us know in case you have further questions 🙏

**Comment by biergit** [comment]
Hi @giograno I then suggest you make this much clearer in your docs. https://docs.localstack.cloud/localstack/persistence-mechanism/ suggests there is at least some kind of persistence mechanism working in the community edition. Thanks :)

**Comment by y-ohno-p** [comment]
Documents says that the community edition can use persistence, but is it correct that the latest version cannot?

**Comment by giograno** [comment]
Hi @y-ohno-p, as mentioned above, persistence in community as been deprecated since a while now and it's not really working/supported anymore. It will be completely removed in the next release. You are very right, our documentation for persistence is not up-to-date unfortunately. We are currently re-working it. Sorry for the inconvenience 🙏

**Comment by krystof-k** [comment]
Indeed very confusing. I understood the [release notes](https://github.com/localstack/localstack/releases/tag/v1.0.1) in the way that if I set `LEGACY_DIRECTORIES` variable or mount a volume into `/tmp/localstack`, everything would work as before (including persistence).

That is quite a hit – as the only thing I need LocalStack for is to persist S3 data for local development. This will probably force us to look for another way to do it as $30 per month is quite a lot for just this one feature. Please consider more granular pricing. Something like $ per AWS service sounds good to me.

**Comment by trevorr** [comment]
+1 on this being barely/inconsistently documented and also not the sort of basic feature I'd expect to pay $30/mo for. Having all of my local S3 objects disappear if Docker or my computer needs to restart disrupts my ability to debug issues to the point of making the free version of localstack unusable. (My use case relies on lots of aggregated data.)

@giograno Please ask your team to reconsider whether this should be a "pro" feature. I'm happy to pay for enterprise-y features (SSO, BI, etc.) when my bootstrapped startup starts generating revenue, but this doesn't meet my bar of being worth managing developer licenses for. For now, we have to go back to our mock implementations.

**Comment by giograno** [comment]
Hi @trevorr, we actually have some good news in that regard. We opened our Cloud Pod feature to all community users with the latest [1.3](https://github.com/localstack/localstack/releases/tag/v1.3.0) minor release. You can basically now save and load LocalState state with the following commands:
```
localstack pod save file://<some_path>/<pod_name>
localstack pod load file://<some_path>/<pod_name>
```
You can read more about it in our [docs](https://docs.localstack.cloud/user-guide/tools/cloud-pods/community/). 
Feel free to try it out and to report feedback and/or problems.

**Comment by trevorr** [comment]
@giograno Thanks for the follow-up. That's not actually something I would use though, as I don't want to micro-manage the persistence. Anything more complicated that each file being persistent after uploaded motivates me to use something else that provides that simplicity.

Perhaps the disconnect between my expectation (S3 files are simply written to the file system) and reality (complex and non-free persistence mechanism) is that localstack is based on moto, which seems to have an in-memory, state-transition architecture. If so, I guess that means that certain easy things become hard (persistence) and vice versa (mocking lots of services).

**Comment by MichielDeMey** [comment]
While I do agree with @trevorr on the topic of micro-managing persistence, I did find an easy way to deal with this using [Initialization Hooks](https://docs.localstack.cloud/references/init-hooks/) together with the [Community Cloud Pods](https://docs.localstack.cloud/user-guide/tools/cloud-pods/community/).

Simply load the pod state on `ready` and save the pods state on `shutdown`.

In your `ready.d` directory:
```bash
#!/bin/bash

echo "Restoring from pod"
FILE=/pods/main
if test -f "$FILE"; then
  localstack pod load file://${FILE}
else
  echo "No pod state found"
fi
```

In your `shutdown.d` directory:
```bash
#!/bin/bash

echo "Saving to pod"
localstack pod save file:///pods/main
```

If you use Docker Compose, simply mount the init scripts and make sure the pods have a persistent volume:

```yaml
localstack:
    [...]
    volumes:
      - "localstack-pods:/pods"
      - "./docker/localstack/init.sh:/etc/localstack/init/ready.d/init.sh"
      - "./docker/localstack/shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh"
      [...]

volumes:
  localstack-pods:
  [...]
```

This basically mimics the `ON_SHUTDOWN` save strategy and `ON_STARTUP` load strategy.

Hope this helps!

**Comment by dkliemsch** [comment]
@MichielDeMey that looks promising! Unfortunately it doesn't work with the Docker Compose setup as the pod command is not available inside the docker container.

I have a very basic setup:

```yml
localstack:
  image: localstack/localstack:2.1
  container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  ports:
    - "127.0.0.1:4566:4566"            # LocalStack Gateway
    - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  environment:
    - DEBUG=${DEBUG-}
    - DOCKER_HOST=unix:///var/run/docker.sock
  volumes:
    - localstack-pods:/pods
    - ./docker/localstack/ready.d/init.sh:/etc/localstack/init/ready.d/init.sh
    - ./docker/localstack/shutdown.d/shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh
```

with the following init.sh (just for testing)

```bash
#!/bin/bash

localstack --version
localstack pod save file:///pods/main
```

and the following log on startup

```
localstack_main  |
localstack_main  | LocalStack version: 2.1.0
localstack_main  | LocalStack build date: 2023-05-25
localstack_main  | LocalStack build git hash: 67b55096
localstack_main  |
localstack_main  | 2023-06-29T11:37:30.816  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | 2023-06-29T11:37:30.816  INFO --- [-functhread3] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_main  | Ready.
localstack_main  | 2.1.0
localstack_main  | Usage: localstack [OPTIONS] COMMAND [ARGS]...
localstack_main  | Try 'localstack --help' for help.
localstack_main  |
localstack_main  | Error: No such command 'pod'.
localstack_main  | 2023-06-29T11:37:31.427 ERROR --- [  MainThread] localstack.runtime.init    : Error while running script Script(path='/etc/localstack/init/ready.d/init.sh', stage=READY, state=ERROR): Script /etc/localstack/init/ready.d/init.sh returned a non-zero exit code 2
```

So I'm curious: How did you get this to work? Are you using Docker Compose?

**Comment by MichielDeMey** [comment]
@dkliemsch We had the same issue, not sure what the underlying issue is (outdated CLI?) but we fixed it by creating our own `Dockerfile` where we install the latest CLI versions.

Note: We currently install the gcc compiler because some native dependencies are not pre-compiled for ARM64 (Apple M2) and need to be compiled on-demand.

```Dockerfile
FROM localstack/localstack:latest

RUN echo "Upgrading to the latest localstack CLI..."
RUN apt-get update && apt-get install -y gcc \
	&& rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade localstack localstack-ext
```

**Comment by dkliemsch** [comment]
@MichielDeMey Hell yeah, that works - thanks! I didn't even think of trying an update because it was already claiming to be version 2.1.0 anyway.

**Comment by theogravity** [comment]
> @dkliemsch We had the same issue, not sure what the underlying issue is (outdated CLI?) but we fixed it by creating our own `Dockerfile` where we install the latest CLI versions.
> 
> Note: We currently install the gcc compiler because some native dependencies are not pre-compiled for ARM64 (Apple M2) and need to be compiled on-demand.
> 
> ```dockerfile
> FROM localstack/localstack:latest
> 
> RUN echo "Upgrading to the latest localstack CLI..."
> RUN apt-get update && apt-get install -y gcc \
> 	&& rm -rf /var/lib/apt/lists/*
> RUN pip install --upgrade localstack localstack-ext
> ```

I think this is slightly incorrect. `localstack` runs in a `venv`, so if you do `which localstack` in the script, you'll get an output of:

`/opt/code/localstack/.venv/bin/localstack`

where you actually want the upgraded one at:

`/usr/local/bin/localstack`

so what you actually need to do is change the `localstack` reference in the `ready.d` and `shutdown.d` script to `/usr/local/bin/localstack`

**Comment by lainosantos** [comment]
It`s works for community edition:

```yaml
version: "3.0"
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:2.2.0
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
      - DEBUG=0
      - PERSISTENCE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./boot.sh:/etc/localstack/init/boot.d/boot.sh
      - ./ready.sh:/etc/localstack/init/ready.d/ready.sh
      - ./shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh
      - localstack_pods:/pods

volumes:
  localstack_pods:
``` 

./boot.sh
```sh
#!/bin/bash

set -euo pipefail

if ! test -f /opt/code/localstack/bin/localstack-cli; then
  echo "Installing global localstack cli"

  tmp_dir=$(mktemp -d)

  curl -s -L https://github.com/localstack/localstack-cli/releases/download/v2.2.0/localstack-cli-2.2.0-linux-amd64-onefile.tar.gz | tar xvzf - -C "$tmp_dir"
  mv "$tmp_dir/localstack" /opt/code/localstack/bin/localstack-cli

  rm -rf "$tmp_dir"
fi
```

./ready.sh
```sh
#!/bin/bash

set -euo pipefail

FILE="/pods/main"

if [[ -f "$FILE" && "${PERSISTENCE:-0}" == 1 ]]; then
  echo "Restoring from pod"

  /opt/code/localstack/bin/localstack-cli pod load file://${FILE}
else
  echo "No pod state found"
fi
```

./shutdown.sh
```sh
#!/bin/bash

set -euo pipefail

if [[ "${PERSISTENCE:-0}" == 1 ]]; then
  echo "Saving to pod"

  /opt/code/localstack/bin/localstack-cli pod save file:///pods/main
fi
```
