### ISSUE TITLE
bug: SQS Queue Url's do not respect HOSTNAME_EXTERNAL unless SQS_PORT_EXTERNAL is also defined

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#6285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`docker-compose.yaml`
```yaml
version: "3.5"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "433:433"
      - "4566:4566"
      - "4567:4567"
      - "4571:4571"
      - "9001:9001"
    environment:
      - SERVICES=sqs, lambda, apigateway, s3, sts, ssm, sns, ses, cloudformation, iam, ec2, kms, cloudfront
      - LOCALSTACK_HOSTNAME=172.26.0.2
      - HOSTNAME=172.26.0.2
      - HOSTNAME_EXTERNAL=172.26.0.2
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - TEST_AWS_ACCOUNT_ID=000000000000
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Expectation:
```
$ awslocal sqs create-queue --queue-name test
{
    "QueueUrl": "http://172.26.0.2:4566/000000000000/test"
}
```

### Expected Behavior

Current outcome:

```
$ awslocal sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/000000000000/test"
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```

### Anything else?

I believe the problem lies in [`sqs/provider.py::url`](https://github.com/localstack/localstack/blob/master/localstack/services/sqs/provider.py#L316). It only fetches the host if `config.SQS_PORT_EXTERNAL` is defined, whereas you shouldn't need to define `config.SQS_PORT_EXTERNAL` in order for `HOSTNAME_EXTERNAL` to take effect. Taking a look at the [config page for localstack](https://docs.localstack.cloud/localstack/configuration/), `HOSTNAME_EXTERNAL` is even documented as being used for SQS Queue URL's without mention of having to set `SQS_PORT_EXTERNAL` as well.
