### ISSUE TITLE
bitbucket pipeline can't find localstack service

### ISSUE THREAD

**Issue by stonebat** [localstack/localstack#629]
I added localstack:localstack docker image for a service in my bitbucket pipeline.

The pipeline was triggered, and it launched the docker container with dynamodb service enabled.  Then it ran my branch's build steps:

- apt-get update
- apt-get install -y netcat
- nc -zv 127.0.0.1 4569

The netcat command isn't printing out anything.  I presume 127.0.0.1 is not the correct address :(

**Comment by whummer** [comment]
Thanks for reporting @stonebat . I'm not too familiar with the Bitbucket Pipelines network setup - does it work with `localhost` instead of `127.0.0.1`?

**Comment by stonebat** [comment]
I tried both.  Neither worked :(

I defined localstack:localstack docker container as a service in my bitbucket-pipelines.yml.

  services:
    localstack:
      image: localstack/localstack:latest
      environment:
        DEBUG: 1
        SERVICES: dynamodb
      ports:
        - "4567-4583:4567-4583"
        - "8080:8080"

Then I used the service "localstack" in my pipeline definition.
pipelines:
  branches:
    master:
      - step:
           services:
            - localstack

**Comment by lionelfarr** [comment]
Hello @stonebat.  Running into similar challenges.  Did you ever get this to work?

**Comment by stonebat** [comment]
@lionelfarr I ended up calling docker commands directly from build pipleline steps.

- docker pull localstack/localstack:latest
- docker run -p 4567-4578:4567-4578 -p 8080:8080 -e "SERVICES=dynamodb,s3,dynamodbstreams" localstack/localstack:latest &

**Comment by whummer** [comment]
Closing this issue, as a workaround has been found. Thanks for following up on this issue.

**Comment by fzaffarana** [comment]
Just in case.

In my case, It's worked setting de `LOCALSTACK_HOSTNAME = localhost` and using it in aws endpoints:

```
image: node:8.10-alpine

pipelines: 
  default: 
    - step: 
        script:
          - export ENVIRONMENT=docker
          - export AWS_REGION=us-east-1
          - export LOCALSTACK_HOSTNAME=localhost
          - export HOSTNAME=localhost
          - export AWS_ACCESS_KEY_ID=test
          - export AWS_SECRET_ACCESS_KEY=test
          - npm install
          - npx fly test:local
        services:
          - localstack 

definitions: 
  services:
    localstack:
      image: localstack/localstack
      environment:
        SERVICES: ses
        LOCALSTACK_HOSTNAME: localhost
        HOSTNAME: localhost
      ports:
        - "4567-4583:4567-4583"
        - "8080:8080"
```
