### ISSUE TITLE
Error when invoking localstack: "fork/exec /var/task/main: no such file or directory"

### ISSUE THREAD

**Issue by fdsmora** [localstack/localstack#6293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After deploying my lambda in localstack and then invoke it I get this error: 

```
{"errorMessage":"RequestId: xxxxxxx Error: fork/exec /var/task/main: no such file or directory","errorType":"exitError"}
```
I have created a [simple repo](https://github.com/fdsmora/vartaskerror-lambda/blob/main/README.md) that shows this issue. 

### Expected Behavior

The lambda should work. 

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create a simple lambda project with this content for `main.go`:
```
package main

import (
	"os"

	"github.com/aws/aws-lambda-go/lambda"
)

func HandleRequest() string {
	foo := os.Getenv("FOO")
	return foo
}

func main() {
	lambda.Start(HandleRequest)
}
```
2. `docker-compose.yml`:
```
version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_test
    ports:
      - "4563-4599:4563-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,lambda,iam
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=sample-lambda_default-network
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - './localstack_setup:/docker-entrypoint-initaws.d/'
    networks:
      - default-network
networks:
  default-network:
```
3. `docker compose up`
4. Build the lambda: `GOOS=linux go build -o main`
5. Create deployment package: `zip function.zip main`
6. Deploy the lambda: `aws --endpoint-url=http://localhost:4566 lambda create-function --function-name sample-lambda --handler main --runtime go1.x --role anyrole --zip-file fileb://function.zip` 
7. Invoke the lambda: `aws --endpoint-url=http://localhost:4566 lambda invoke --function-name sample-lambda /dev/stdout`. The error is returned:
```
{"errorMessage":"RequestId: d46ef559-68f4-1719-76e0-25b0cd4d72a6 Error: fork/exec /var/task/main: no such file or directory","errorType":"exitError"}
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

### Environment

```markdown
- OS: MacOS Monterey 12.2.1
- LocalStack: 0.14.3.2
- Docker: 20.10.14, build a224086
```

### Anything else?

I have created a [simple repo](https://github.com/fdsmora/vartaskerror-lambda/blob/main/README.md) that shows this issue.
