### ISSUE TITLE
bug: S3 presigned URL ignores HOSTNAME_EXTERNAL

### ISSUE THREAD

**Issue by cabeaulac** [localstack/localstack#6301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My `docker-compose.yml` has HOSTNAME_EXTERNAL set. My web app hits an APIGW REST endpoint to create an S3 presigned post URL like this
```
        data = s3_client.generate_presigned_post(
            bucket_name,
            key,
            Fields=additional_fields,
            Conditions=None,
            ExpiresIn=expires_in,
        )
        return data
```
My docker-compose.yml looks like this
```
version: '3.8'

services:
  localstack:
    # Rolled back from version 0.14.0 to get lambda functions to work
    # see https://github.com/localstack/localstack/issues/5432
    # image: "localstack/localstack:0.14.2"
    #image: "localstack/localstack:0.14.3.1"
    image: "localstack/localstack:latest"
    # @sha256:9fe2eb9c1d86e728a3cd5dd4f184cd50b6ab399b091ef1933b5bb82ebaa6898e
    networks:
      devnet:
#        ipv4_address: 169.254.170.3
    ports:
      - "8001:8080"            # only required for Pro
      - "53:53"                # only required for Pro
      - "53:53/udp"            # only required for Pro
      - "443:443"              # only required for Pro
      - "4510-4560:4510-4560"  # only required for Pro
      - "4566:4566"
      - "4571:4571"
    environment:
      # - SERVICES=s3,secretsmanager,apigateway,lambda,iam,dynamodb,stepfunctions,route53,cloudfront,sts
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- docker-reuse}
      # Tell Localstack to put Lambda containers on the same shared network
      - LAMBDA_DOCKER_NETWORK=devnet
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      # - HOSTNAME=localstack
      - MAIN_CONTAINER_NAME=localstack
      - HOSTNAME_EXTERNAL=host.docker.internal
      #      - USE_SSL=false
      # - DNS_ADDRESS=127.0.0.11
      # - HOSTNAME=localstack
      # - HOSTNAME_EXTERNAL=localstack
      # - DNS_RESOLVE_IP=169.254.170.3
      # - DOCKER_BRIDGE_IP=169.254.170.1
      # - LOCALSTACK_HOSTNAME=host.docker.internal
      # - CLOUDFRONT_STATIC_PORTS=1

    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

The returned URL to the web app look like this:
```
url: "http://169.254.170.4:4566/fp-chad-local-bucket-us-east-1"
```

### Expected Behavior

The returned URL to the web app should look like this:
```
url: "http://host.docker.internal:4566/fp-chad-local-bucket-us-east-1"
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose -f auto_tests/docker-compose.yml up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Using the CLI to call presign does not reproduce the error. You have to run a boto3 client to call `s3client.generate_presigned_post(...)`

For example, this does not reproduce the problem.
```
$ aws --endpoint-url=http://host.docker.internal:4566 s3 presign s3://fp-chad-local-bucket-us-east-1/stuff.txt
```

### Environment

```markdown
- OS: ubuntu:latest
- LocalStack: latest PRO
```

**Comment by MarcelStranak** [comment]
I have tried  it with this simple script and I could not reproduce your issue. 

```python
import boto3

endpoint_url = "http://localhost:4566"

bucket_name = "my-bucket"
key = "test/a1"

expires_in = 24*60*60

s3_client = boto3.client('s3') 

response = s3_client.generate_presigned_post(bucket_name, key, ExpiresIn=expires_in)

print(response['url'])
print(response['fields'])
```

**docker-compose.yml**

```docker
---
version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - '8001:8080'
      - '53:53'
      - 53:53/udp
      - '443:443'
      - 4510-4560:4510-4560
      - '4566:4566'
      - '4571:4571'
    environment:
      - DEBUG=${DEBUG-1 }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=123_REAL_LOCALSTACK_API_KEY
      - MAIN_CONTAINER_NAME=localstack
      - HOSTNAME_EXTERNAL=host.docker.internal
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

output:
```json
{
    "url": "https: //my-bucket.s3.amazonaws.com/",
    "fields": {
        "key": "test/a1",
        "AWSAccessKeyId": "None",
        "policy": "XXX",
        "signature": "XXX"
    }
}
```

**Comment by sergolius** [comment]
Upd: Presigned URL generated via CLI has `localhost` as host, but URL generated via SDK(AWS) request has `Endpoint`(`aws.Config{}.Endpoint`) as host.

**Comment by sergolius** [comment]
@macnev2013  `HOSTNAME_FROM_LAMBDA=localhost` has no impact. URL still referenced to `localstack:4566`

**Comment by macnev2013** [comment]
Hi @sergolius, Thanks for responding.

Would it be possible to share detailed steps (localstack version, commands, code snippets) that you use for this task?

**Comment by sergolius** [comment]
@macnev2013 I use free version of LocalStack and the latests docker image.

`docker-compose.localstack.yml`

```yaml
version: "3.9"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - volume:/var/lib/localstack
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  volume:
```

Connection:
```go
sess, err := session.NewSession(&aws.Config{
	Credentials:      credentials.NewStaticCredentials(cfg.AccessKey, cfg.SecretKey, ""),
	Endpoint:         aws.String(endpoint),
	Region:            aws.String(cfg.Region),
	S3ForcePathStyle: aws.Bool(true),
})

s3svc := s3.New(sess)
s3uploader := s3manager.NewUploader(sess)
```

Utilization:
```go
req, _ := s3svc.GetObjectRequest(&s3.GetObjectInput{
	Bucket: aws.String(cfg.Bucket),
	Key:    aws.String(key),
})
return req.Presign(time.Hour)
```

`s3svc` used for managing objects. `s3uploader` used to upload files.

Default configuration via ENV:
```
ACCESS_KEY=test
SECRET_KEY=test
REGION=us-east-1
BUCKET=test
ENDPOINT=http://localstack:4566
```

Bucket for region created manually.
