### ISSUE TITLE
bug: DynamoDB Streams are not working

### ISSUE THREAD

**Issue by anekar3416** [localstack/localstack#6306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am currently using localstack 0.14.2 to create a dynamodb table and enable dynamodb stream for the same to capture table changes.
Whenever I try to instantiate a KCL worker I am getting the following error:

```
localstack    | 2022-06-21T04:19:32.648:ERROR:localstack.aws.protocol.serializer: Response object contains a member which is not specified: HashKeyRange
localstack    | Traceback (most recent call last):
localstack    |   File "/opt/code/localstack/localstack/aws/protocol/serializer.py", line 1003, in _serialize_type_structure
localstack    |     member_shape = members[member_key]
localstack    | KeyError: 'HashKeyRange'
````
When the errors appears the tables in  dynamodb are getting deleted.
Earlier I was using the dynamodb local jar and it was working fine there. 

### Expected Behavior

The error should not appear and tables should be enabled with dynamodb streams.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Mac 
- LocalStack: 0.14.2
```

**Comment by thrau** [comment]
hi @anekar3416, thanks for reporting. these errors are safe to ignore. is there a particular behavior of dynamodb that you are expecting and not seeing?

:eyes:  @alexrashed would probably be worth it setting this to warning.

**Comment by anekar3416** [comment]
@thrau Yes. I am starting the localstack using docker-compose file. When I try to ssh into the running docker image and run the ./bin/localstack status command it says that it is stopped. 

And I have created a dynamodb table programatically but when I run the awslocal dynamodb list-tables command It says zero tables. I dont understand what is causing this behavior?


Here is the yml file that I am using:

```
version: '3.8'
services:
 localstack:
    container_name: localstack
    image: localstack/localstack:0.14.2
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=kinesis,dynamodb
    volumes:
      - "localstack-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  localstack-data:
```
