### ISSUE TITLE
Create Lambda function using SAM template

### ISSUE THREAD

**Issue by emeraldBazaar** [localstack/localstack#632]
Is it possible to create a lambda function using SAM template? For example:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
     TestLambda:
            Type: 'AWS::Serverless::Function'
             Properties:
                    CodeUri: ./testLambda.zip
                     Handler: testLambda.handler
                      .......
```

When I try to package to s3 in localstack using the following command:

aws --endpoint-url=http://localhost:4581 cloudformation package --template-file test.yaml --output-template-file output.yaml --s3-bucket test-bucket

I get an error as follows:
Unable to upload artifact ./testLambda.zip referenced by CodeUri parameter of TestLambda resource. An error occurred (AccessDenied) when calling the PutObject operation: Access Denied.

Any help will be appreciated.

**Comment by 0rangeMan** [comment]
+1
Having the same issue

**Comment by Guy-Incognito** [comment]
+1

**Comment by tamanjoku** [comment]
+1
Having the same issue.

**Comment by byumark** [comment]
I think I got around this issue by packaging my code and uploading it myself, but then I started getting this error when running deploy.

https://github.com/localstack/localstack/issues/760

The deploy command eventually returns this:
`HTTPConnectionPool(host='localhost', port=4581): Read timed out.`

**Comment by whummer** [comment]
Thanks for reporting @emeraldBazaar @0rangeMan @Guy-Incognito @tamanjoku @baronswindle @byumark - this should be fixed in #1766 . Can you please give it a try with the latest version. Please re-open if the problem persists. Thanks

**Comment by ben-eb** [comment]
Same issue for me, with the following template:

```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello, world

Resources:
    HelloWorld:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./helloWorld/
            Handler: index.handler
            Runtime: nodejs10.x

```

and `index.js`:

```js
const handler = () => `Hello, world`;

exports.handler = handler;
```

After doing [`awslocal s3 mb s3://test-bucket`](https://github.com/localstack/awscli-local), I try `awslocal cloudformation package --template-file template.yaml --output-template-file output.yaml --s3-bucket test-bucket` and get the following error:

>Unable to upload artifact ./helloWorld/ referenced by CodeUri parameter of HelloWorld resource.
>
>An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.

For now I'm working around this by creating resources via the JS SDK, but it's not ideal. I am using the latest docker image if that helps. 😃
