### ISSUE TITLE
DynamoDB Streams not persists after restart docker container

### ISSUE THREAD

**Issue by JuanOrtizOvied** [localstack/localstack#6321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DynamoDB Streams not persists after restart docker container

### Expected Behavior

DynamoDB Streams should persist after container restart

### How are you starting LocalStack?

With a docker-compose file

### docker-compose.yml

```yml
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    depends_on:
      - elasticsearch
    environment:
      - ES_CUSTOM_BACKEND=http://elasticsearch:9200
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DEBUG=true
      - HOSTNAME_FROM_LAMBDA=localhost
      - LAMBDA_DOCKER_NETWORK=host
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  elasticsearch-data:
    driver: local
  localstack-data:
    driver: local
```

## Create DynamoDB table

```bash
aws --endpoint-url=http://localhost:4566 dynamodb create-table \     
  --table-name products \
  --attribute-definitions \
    AttributeName=PK,AttributeType=S \
    AttributeName=SK,AttributeType=S \
  --key-schema \
    AttributeName=PK,KeyType=HASH \
    AttributeName=SK,KeyType=RANGE \
  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
  --stream-specification \
    StreamViewType=NEW_AND_OLD_IMAGES,StreamEnabled=true
```

### The first time, show the streams list

```bash
aws --endpoint-url=http://localhost:4566 dynamodbstreams list-streams
```
![Captura de Pantalla 2022-06-20 a la(s) 9 25 30 a  m](https://user-images.githubusercontent.com/5817795/174623496-0b34c685-ed17-4e59-b02d-a232872609f1.png)

### After restart container

```bash
aws --endpoint-url=http://localhost:4566 dynamodbstreams list-streams
```

![Captura de Pantalla 2022-06-20 a la(s) 9 27 31 a  m](https://user-images.githubusercontent.com/5817795/174623871-9df04a27-fe34-4cd4-8e3e-73133aa52b12.png)

### Environment

```markdown
- OS: MacOS Monterrey 1.4 (21F79)
- LocalStack: 0.14.4.dev
- docker-compose version 1.29.2, build 5becea4c
```

**Comment by giograno** [comment]
Hi @JuanOrtizOvied, thanks for reporting the issue. I've been trying to replicate your issue. Could you please:
- show me what directories are saved under `/tmp/localstack/data` on your file system;
- explicitly specify the region with your AWS commands, adding `--region us-east-1` at the end
Thank you very much 🙏

**Comment by JuanOrtizOvied** [comment]
Hi @giograno.

## /tmp/localstack/data

![Captura de Pantalla 2022-06-25 a la(s) 6 22 19 p  m](https://user-images.githubusercontent.com/5817795/175793320-2acce79f-e93d-495c-ac47-c54894ee505e.png)

## with `--region us-east-1`, the same result

![Screenshot at Jun 25 6-31-29 PM](https://user-images.githubusercontent.com/5817795/175793542-cde2a52a-5301-4940-9d7e-1f060b9c2072.png)

Thanks in advance

**Comment by whummer** [comment]
Hi @JuanOrtizOvied , just to confirm - looks like you're not configuring an API key in your docker-compose.yml config. Please note that full support for persistence is currently only available in the Pro version of LocalStack. If you'd like to give it a try, you can sign up for a free trial under https://app.localstack.cloud . Please keep us posted on how it goes.. Thanks!

**Comment by mboudraa** [comment]
For what it's worth, we have the exact same problem. We're on localstack docker image v1.2.0 and we do have our LOCALSTACK_API_KEY setup.
here is our docker compose file

```yaml
  localstack:
    image: localstack/localstack-full:1.2.0
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4510-4559:4510-4559"
      - "4566-4597:4566-4597"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_DOCKER_NETWORK=tredish-saas_proxy

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
```
