### ISSUE TITLE
bug: Connection refused trying to access to an external container

### ISSUE THREAD

**Issue by Warkanlock** [localstack/localstack#6380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to connect two docker images in order to use a database inside a Lambda. One image is a normal postgresql instance hosted in another docker image and then I have the localstack image running on the background. 

I have configured everything with the following specs:

```
  localstack:
    debug: true
    host: "http://localhost"
    autostart: true
    stages:
      - local
    networks:
      - development
```

Everything looks OK until I want to access to the database using a HTTP connector inside the Lambda: I receive a Connection refused for 127.0.0.1:5732 which makes sense, since I'm trying to access to a different container, but I'm configuring the networks needed to make this communication possible and nothing happens.

I'm using the following `docker-compose.yml`

```
  db:
    container_name: api_db
    image: postgresql
    restart: always
    depends_on:
      - localstack
    links:
      - localstack
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=eu-north-1
      - EDGE_BIND_HOST=0.0.0.0
      - LAMBDA_EXECUTOR=docker
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - LAMBDA_REMOTE_DOCKER=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Expected Behavior

The connection should be established successfully 

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    1. create a docker-compose.yml with the services I described above
    2. use `serverless-localstack` to deploy everything into the docker container
    3. try to connect to another database on other docker image

### Environment

```markdown
- OS: Linux Ubuntu 20.04
- LocalStack: latest
```

### Anything else?

Does anyone knows how to connect a local lambda to a database running in other container? This issue is driving me crazy
