### ISSUE TITLE
bug: 'CreateQueue' for service 'sqs'

### ISSUE THREAD

**Issue by cannahum** [localstack/localstack#6466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In local environment (macOS Monterey) I can run localstack with docker compose, and create queues for unit tests, then take them down after tests end. When I compose the same localstack spec in Github Actions (ubuntu-latest) I get the following message: 

> operation error SQS: CreateQueue, https response error StatusCode: 501, RequestID: S2SY8A71JTE9X1FXLQJWF8HQOFSMP3QO8EJH8QUVYS0PYVVEJN1P, api error InternalFailure: API action 'CreateQueue' for service 'sqs' not yet implemented

My docker compose looks like this:
```yaml
version: '3.8'
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
#      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - SERVICES=dynamodb,sqs
      - PROVIDER_OVERRIDE_SQS=asf
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Expected Behavior

I would expect sqs Queue creation be supported in all environments; mostly because I couldn't find any documentation to suggest that this isn't supported.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose -f "docker-compose.yml" up -d --build

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```go
        var attrs map[string]string
	if isFifo {
		attrs = map[string]string{
			"FifoQueue":                 "true",
			"ContentBasedDeduplication": "true",
		}
	}

	qq, err := q.CreateQueue(context.TODO(), &sqs.CreateQueueInput{
		QueueName:  queueName,
		Attributes: attrs,
	})
```

### Environment

```markdown
- OS: ubuntu-latest (github actions)
- LocalStack:
```
