### ISSUE TITLE
bug: Step Function not saving after docker restart

### ISSUE THREAD

**Issue by jcanabarro** [localstack/localstack#6486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create a state machine everything seems ok, i can visualize using awslocal, but when i restart the docker-compose and try to list those state machines again, they are just gone, all the other resources that I'm currently using works fine with the volume, i also was having this problem at the version 0.14.

### Expected Behavior

Create a step machine on the localstack, restart the docker compose and still be able manipulate then.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack
    
```yml
  version: "3.8"
  
  services:
    localstack:
      container_name: localstack_main
      image: localstack/localstack:1.0.0
      ports:
        - "127.0.0.1:53:53"
        - "127.0.0.1:53:53/udp"
        - "127.0.0.1:443:443"
        - "127.0.0.1:4510-4559:4510-4559"
        - "127.0.0.1:4566:4566"
      environment:
        - DEFAULT_REGION=eu-west-3
        - LAMBDA_EXECUTOR=docker
        - LAMBDA_REMOTE_DOCKER=true
        - LAMBDA_REMOVE_CONTAINERS=true
        - DEBUG=0
        - PERSISTENCE=1
        - DOCKER_HOST=unix:///var/run/docker.sock
  
      volumes:
        - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
  
      env_file:
        - .env
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

- Create a new state machine
    ```bash
    awslocal stepfunctions create-state-machine --name test --role-arn arn:aws:iam::000000000000:role/lambda-local --definition '{"Comment": "A description of my state machine", "StartAt": "Lambda Invoke", "States": {"Lambda Invoke": {"Type": "Task", "Resource": "arn:aws:states:::lambda:invoke", "OutputPath": "$.Payload", "Parameters": {"Payload.$": "$", "FunctionName": "test"}, "Retry": [{"ErrorEquals": ["Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException"], "IntervalSeconds": 2, "MaxAttempts": 6, "BackoffRate": 2}], "End": true}}}'
    ```
- List the state machine using awslocal 
    ```bash
      awslocal stepfunctions list-state-machines --region us-east-1
      {
          "stateMachines": [
              {
                  "stateMachineArn": "arn:aws:states:us-east-1:000000000000:stateMachine:test",
                  "name": "test",
                  "type": "STANDARD",
                  "creationDate": "2022-07-19T15:57:29.848000-03:00"
              }
          ]
      }
    ```
- Restart the docker-compose
- Try to list again, and it's not there.
    ```bash
      awslocal stepfunctions list-state-machines --region us-east-1
      {
          "stateMachines": []
      }
    ```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: 1.0.0
- awscli-local 0.20
- python 3.10.4
```
