### ISSUE TITLE
bug:  "CommaDelimitedList" type not supported for SAM/CloudFormation template parameters

### ISSUE THREAD

**Issue by tinesoft** [localstack/localstack#6523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have 2 parameters in my SAM `template.yml`, which represent a list of Security GroupIds and SubnetIds.

```
AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31
Parameters:
  LambdaToEksSecurityGroupIds:
    Type: CommaDelimitedList
    Description: "List of security group ids in Eks VPC"
    Default: sg-xxxxxxxxxxxxx
  LambdaToEksSubnetIds:
    Type: CommaDelimitedList
    Description: "List of subnet ids in Eks VPC"
    Default: subnet-yyyyyyyyyy,subnet-zzzzzzzzzzzzz
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyLambdaFunction
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      CodeUri: functions/nodejs/my-lambda
      VpcConfig:
        SecurityGroupIds: !Ref LambdaToEksSecurityGroupIds
        SubnetIds: !Ref LambdaToEksSubnetIds
```

These parameters are provided at runtime through environment variables, when deploying with `samlocal`.

```
#!/bin/bash

export LAMBDA_TO_EKS_SUBNET_IDS="subnet-bbbbbbbbbb"
export LAMBDA_TO_EKS_SECURITY_GROUP_IDS="sg-aaaaaaaaaaaaa"

samlocal deploy \
	--stack-name "$DEPLOY_STACK_NAME" \
	--s3-bucket "$DEPLOY_S3_BUCKET_NAME" \
	--s3-prefix "$DEPLOY_S3_PREFIX" \
	--region "$AWS_DEFAULT_REGION" \
	--capabilities "CAPABILITY_IAM" \
	--no-confirm-changeset \
	--no-fail-on-empty-changeset \
	--disable-rollback \
	--parameter-overrides \
			"LambdaToEksSecurityGroupIds='$LAMBDA_TO_EKS_SECURITY_GROUP_IDS'" \
			"LambdaToEksSubnetIds='$LAMBDA_TO_EKS_SUBNET_IDS'" 
```

It works fine when deploying on AWS, with SAM. but the same command failed when deploying to Localstack, 
with the following error, when validating the above paramters:

```
localstack  | 2022-07-27T07:06:16.964:DEBUG:localstack.utils.cloudformation.template_deployer: Error applying changes for CloudFormation stack "aws-stack": Parameter validation failed:
localstack  | Invalid type for parameter VpcConfig.SecurityGroupIds, value: sg-aaaaaaaaaaaaa type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
localstack  | Invalid type for parameter VpcConfig.SubnetIds, value: subnet-bbbbbbbbbb, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'> Traceback (most recent call last):
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1548, in _run
localstack  |     self.do_apply_changes_in_loop(changes, stack, stack_name)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1618, in do_apply_changes_in_loop
localstack  |     self.apply_change(change, stack=stack)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1684, in apply_change
localstack  |     result = deploy_resource(self, resource_id)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 846, in deploy_resource
localstack  |     result = execute_resource_action(resource_id, stack, ACTION_CREATE)
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 887, in execute_resource_action
localstack  |     result = configure_resource_via_sdk(
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1020, in configure_resource_via_sdk
localstack  |     raise e
localstack  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 1010, in configure_resource_via_sdk
localstack  |     result = function(**params)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
localstack  |     return self._make_api_call(operation_name, kwargs)
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 878, in _make_api_call
localstack  |     request_dict = self._convert_to_request_dict(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 939, in _convert_to_request_dict
localstack  |     request_dict = self._serializer.serialize_to_request(
localstack  |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
localstack  |     raise ParamValidationError(report=report.generate_report())
localstack  | botocore.exceptions.ParamValidationError: Parameter validation failed:
localstack  | Invalid type for parameter VpcConfig.SecurityGroupIds, value: sg-aaaaaaaaaaaaa , type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
localstack  | Invalid type for parameter VpcConfig.SubnetIds, value: subnet-bbbbbbbbbb, type: <class 'str'>, valid types: <class 'list'>, <class 'tuple'>
```

### Expected Behavior

Parameters of type `CommaDelimitedList` should be properly treated as list of values

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#!/bin/bash

export LAMBDA_TO_EKS_SUBNET_IDS="subnet-bbbbbbbbbb"
export LAMBDA_TO_EKS_SECURITY_GROUP_IDS="sg-aaaaaaaaaaaaa"

samlocal deploy \
	--stack-name "$DEPLOY_STACK_NAME" \
	--s3-bucket "$DEPLOY_S3_BUCKET_NAME" \
	--s3-prefix "$DEPLOY_S3_PREFIX" \
	--region "$AWS_DEFAULT_REGION" \
	--capabilities "CAPABILITY_IAM" \
	--no-confirm-changeset \
	--no-fail-on-empty-changeset \
	--disable-rollback \
	--parameter-overrides \
			"LambdaToEksSecurityGroupIds='$LAMBDA_TO_EKS_SECURITY_GROUP_IDS'" \
			"LambdaToEksSubnetIds='$LAMBDA_TO_EKS_SUBNET_IDS'" 
```

### Environment

```markdown
- OS:
- LocalStack: 0.14.4.dev
```

### Anything else?

I tried different ways of providing the `--parameter-overrides` values, but none worked so far...

The documentation of Cloudformation on Localstack mentioned that the [support for parameters is partial](https://docs.localstack.cloud/aws/cloudformation/#:~:text=Parameters,Partial) ... 
What exactly is supported ?
