### ISSUE TITLE
bug: ENFORCE_IAM=1 does not stop a Lambda from sending a message to an SQS Queue that it has not been granted sendMessage permissions to

### ISSUE THREAD

**Issue by Garethp** [localstack/localstack#6600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In testing the IAM Enforcement feature of LocalStack Pro I wanted to check if my lambda's would fail to send messages to queues if I forgot to grant them permissions to do so. Not only does the lambda not fail with an error message like it would in AWS but I'm able to retrieve the error message from SQS.

### Expected Behavior

I would expect the lambda function to fail sending the message saying that it doesn't have an explicit permission to for sendMessages.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
I'm using the following `docker-compose.yaml` file and `index.ts` file for my CDK

```yaml
version: "3.5"
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "4571:4571"
    environment:
      - SERVICES=sqs, lambda, apigateway, s3, sts, ssm, cloudformation, ecr, kms, iam, rds
      - LOCALSTACK_HOSTNAME=172.26.0.1
      - HOSTNAME=172.26.0.1
      - HOSTNAME_EXTERNAL=172.26.0.1
      - SQS_PORT_EXTERNAL=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-2
      - TEST_AWS_ACCOUNT_ID=000000000000
      - LOCALSTACK_API_KEY=[LOCALSTACK_KEY]
      - ENFORCE_IAM=1
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

```ts
import { App, Stack } from "aws-cdk-lib";
import { Construct } from "constructs";
import { Queue } from "aws-cdk-lib/aws-sqs";
import { Distribution } from "aws-cdk-lib/aws-cloudfront";
import { HttpOrigin } from "aws-cdk-lib/aws-cloudfront-origins";
import { Certificate } from "aws-cdk-lib/aws-certificatemanager";
import { Function, InlineCode, Runtime } from "aws-cdk-lib/aws-lambda";

class TestStack extends Stack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new TestConstruct(this, "test");
  }
}

class TestConstruct extends Construct {
  public readonly queue: Queue;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    const queue = new Queue(this, "Queue", {
      fifo: true,
      contentBasedDeduplication: true,
    });

    const lambda = new Function(this, "Function", {
      code: new InlineCode(`
        var AWS = require('aws-sdk');
        
        exports.handler = async () => {
          const sqs = new AWS.SQS();
          await sqs
            .sendMessage({
              QueueUrl: process.env.QUEUE_URL,
              MessageBody: "test",
              MessageGroupId: "Default",
            })
            .promise();
        };
      `),
      handler: "index.handler",
      runtime: Runtime.NODEJS_14_X,
      environment: {
        QUEUE_URL: queue.queueUrl,
      },
    });

    lambda.addToRolePolicy(
      new PolicyStatement({
        effect: Effect.DENY,
        resources: ["*"],
        actions: ["*"],
      })
    );
  }
}

const app = new App();

new TestStack(app, "stack");
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
#!/bin/bash

cdklocal bootstrap

# This is a workaround for the bug detailed here https://github.com/localstack/localstack/issues/5436
awslocal iam attach-role-policy --role-name cdk-hnb659fds-deploy-role-000000000000-eu-west-2 --policy-arn arn:aws:iam::aws:policy/AdministratorAccess
cdklocal deploy --require-approval never

FUNCTION_NAME=$(awslocal lambda list-functions | jq -r .Functions[0].FunctionName)
awslocal lambda invoke --function-name $FUNCTION_NAME test.txt

QUEUE_URL=$(awslocal sqs list-queues | jq -r .QueueUrls[0])
awslocal sqs receive-message --queue-url $QUEUE_URL
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```
