### ISSUE TITLE
exit 139 using docker-compose

### ISSUE THREAD

**Issue by koooge** [localstack/localstack#662]
Hi!  I encounterd an issue on mac(high-sierra) when I type `docker-compose up -d`. 

my docker-compose. yml
```
...
  localstack:
    image: localstack/localstack:0.8.5
    ports:
      - "${LOCALSTACK_UI_PORT}:8080"
      - "${DYNAMODB_PORT}:4569" # dynamodb
      - "${SQS_PORT}:4576" # sqs
    restart: always
...
```

.env
```
LOCALSTACK_UI_PORT=61001
DYNAMODB_PORT=35001
SQS_PORT=60001
```

localstack continues to exit 139 and restart, and seems not to have any logs 😢 

```
5369b614f896        localstack/localstack:0.8.5   "/usr/bin/supervisor…"   47 seconds ago      Restarting (139) 16 seconds ago
```
