### ISSUE TITLE
bug: IAM User Does Not Persist

### ISSUE THREAD

**Issue by JRagone** [localstack/localstack#6656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With persistence enabled, if I create a user:

```sh
awslocal iam create-user --user-name Test
```

and restart Localstack, the user is no longer there.

Persistence is working for other services like S3, though.

### Expected Behavior

Given this issue https://github.com/localstack/localstack/issues/4814, I would expect the user to persist.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - LOCALSTACK_API_KEY=...
      - PERSISTENCE=1
    ports:
      - 4563-4584:4563-4584
    volumes:
      - ./volume:/var/lib/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal iam create-user --user-name Test
    awslocal iam list-users

Restart Localstack

    awslocal iam list-users

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```
