### ISSUE TITLE
Read timeout on endpoint URL: "http://localhost:4566/2015-03-31/functions/tournament-step-function-lambda/invocations"

### ISSUE THREAD

**Issue by sheshantzupee** [localstack/localstack#6681]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When i am invoking lambda function on localstack, i am getting no response and also no error logs:

```localstack_1                | 2022-08-16T12:32:32.051  INFO --- [  Thread-108] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack_1                | 2022-08-16T12:32:32.252  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 545.09ms
localstack_1                | Ready.
localstack_1                | 2022-08-16T12:33:10.270  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "_load_service_plugin" took 696.89ms
localstack_1                | 2022-08-16T12:33:10.326  INFO --- [   asgi_gw_0] localstack.services.infra  : Starting mock Lambda service on http port 4566 ...
localstack_1                | 2022-08-16T12:33:10.890  INFO --- [   asgi_gw_0] localstack.utils.bootstrap : Execution of "require" took 1316.56ms
localstack_1                | 2022-08-16T12:33:13.012  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS lambda.CreateFunction => 200
localstack_1                | 2022-08-16T12:33:42.940  INFO --- [uest_thread)] l.u.container_networking   : Determined main container network: root_default
localstack_1                | 2022-08-16T12:33:42.946  INFO --- [uest_thread)] l.u.container_networking   : Determined main container target IP: 172.18.0.3
localstack_1                | 2022-08-16T12:33:42.946  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:ap-south-1:000000000000:function:my-step-function
localstack_1                | 2022-08-16T12:34:41.972  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:ap-south-1:000000000000:function:my-step-function
localstack_1                | 2022-08-16T12:35:42.321  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:ap-south-1:000000000000:function:my-step-function
localstack_1                | 2022-08-16T12:36:42.949  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:ap-south-1:000000000000:function:my-step-function
localstack_1                | 2022-08-16T12:37:48.037  INFO --- [uest_thread)] l.s.a.lambda_executors     : Running lambda: arn:aws:lambda:ap-south-1:000000000000:function:my-step-function
```
> Docker-compose.yaml file 
```
services:
  localstack:
    image: localstack/localstack
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb,lambda,s3
      - KINESIS_PROVIDER=kinesalite
      - HOSTNAME_EXTERNAL=localstack
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
      - LAMBDA_EXECUTOR=docker
    ports:
      - '4566:4566'
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

> Healt status: `running`
```
{
    "features": {
        "initScripts": "initialized"
    },
    "services": {
        "acm": "available",
        "apigateway": "available",
        "cloudformation": "available",
        "cloudwatch": "available",
        "config": "available",
        "dynamodb": "available",
        "dynamodbstreams": "available",
        "ec2": "available",
        "es": "available",
        "events": "available",
        "firehose": "available",
        "iam": "available",
        "kinesis": "available",
        "kms": "available",
        "lambda": "running",
        "logs": "available",
        "opensearch": "available",
        "redshift": "available",
        "resource-groups": "available",
        "resourcegroupstaggingapi": "available",
        "route53": "available",
        "route53resolver": "available",
        "s3": "running",
        "s3control": "available",
        "secretsmanager": "available",
        "ses": "available",
        "sns": "available",
        "sqs": "available",
        "ssm": "available",
        "stepfunctions": "available",
        "sts": "available",
        "support": "available",
        "swf": "available"
    },
    "version": "0.14.2"
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```
    aws --endpoint-url=http://localhost:4566 lambda create-function --function-name my-step-function \
   --zip-file fileb://my-step-function.zip \
   --handler index.handler --runtime nodejs12.x \
   --role arn:aws:iam::000000000000:role/DummyRole
```
Invoke lambda function
```
aws --endpoint-url=http://localhost:4566 lambda invoke \
    --function-name my-step-function \
    --payload '{"key": "value"}' \
    response.json
```

### Environment

```markdown
- OS: Ubuntu 16.04.6 LTS
- LocalStack: 0.14.2
```
