### ISSUE TITLE
bug: Cloud formation S3 VersioningConfiguration property not working

### ISSUE THREAD

**Issue by cpsinghal** [localstack/localstack#6720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cloud formation S3 VersioningConfiguration property not working

### Expected Behavior

Based on VersioningConfiguration Status, 
`aws --region ap-south-1 --endpoint-url http://localstack:4566  s3api get-bucket-versioning --bucket dx-ref-cfn-s3` should return the expected value but command exit with empty response.

### How are you starting LocalStack?

With a docker-compose file

## Template file
```
Parameters:
  S3BucketName: # automatic
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: {Ref: S3BucketName }
      VersioningConfiguration:
        Status: Enabled
```

AWS CLI command
`aws --region ap-south-1 --endpoint-url http://localstack:4566 cloudformation create-stack --stack-name s3-v2-dx-ref-cfn-s3 --template-body file:///s3.yml --parameters ParameterKey=S3BucketName,ParameterValue=dx-ref-cfn-s3`

s3 bucket is getting created but without VersioningConfiguration status.

### Environment

```markdown
- OS:
- LocalStack: 0.14.2
```
