### ISSUE TITLE
localstack Dynamodb ResourceNotFoundException , ResourceInUseException: 

### ISSUE THREAD

**Issue by jatinmehrotra** [localstack/localstack#6742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever i am trying to run my tests on my local system, test suites which require localstack's dynamodb are failing.

However with the same configuration in the circle ci pipeline test job all cases are passed.

I am sorry if my report lacks important details, still new to localstack, feel free to ask for any other details to understand.

### Expected Behavior

I want test cases to be passed even in my local system not just circle ci pipeline

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose.yml`    

```
version: '3.3'

services:
  localstack:
    image: localstack/localstack:0.9.4
    ports:
      - '4569:4569'
      - '4572:4572'
      - '4576:4576'
      - '4584:4584'
    environment:
      - SERVICES=dynamodb,s3,secretsmanager,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
```

npm run docker:up -> `docker-compose up -d`
npm run test -> `jest`

### Environment

```markdown
- OS: macOS 11.4
- LocalStack:
```

### Anything else?

<img width="929" alt="Screenshot 2022-08-24 at 8 54 49 PM" src="https://user-images.githubusercontent.com/49259715/186412368-5eb6d5e4-b79d-4431-86f5-c9587a717654.png">
