### ISSUE TITLE
bug: SQS fifo message group processed out of order

### ISSUE THREAD

**Issue by talha5389** [localstack/localstack#6762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Queue 2 messages in fifo queue with same group id. 
2. Received messages with max receive count > 2 and visibility timeout of 5 minute. Both messages will be returned which is correct
3. Before 5 minute visibility timeout runs out, queue more messages in queue with same group id
4. Invoke receive message via cli.  Newly queued messages will be received even though messages for same group were waiting for visibility timeout

### Expected Behavior

Messages from same message group to not be received until earlier received messages from same message group are removed in subsequent receive message calls

![image](https://user-images.githubusercontent.com/14093306/186809935-90f3199e-b7f6-405c-83f0-c2cc0b855ad4.png)

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html
This is working as expected with AWS cloud but not working in localstack

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # - DEBUG=${DEBUG-}
      - PERSISTENCE=1
      # - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      # - DOCKER_HOST=tcp://host.docker.internal:2375
      # - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack:/var/lib/localstack"
volumes:
  localstack:
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
 aws sqs create-queue --queue-name test.fifo --endpoint-url http://localhost:4566 --attributes FifoQueue=true --region=us-east-1

aws sqs send-message --message-deduplication-id 1 --message-group-id g1 --message-body "m1" --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1

aws sqs send-message --message-deduplication-id 2 --message-group-id g1 --message-body "m2" --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1

#should receive 2 messages
aws sqs receive-message --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1 --attribute-name All --max-number-of-messages 5 --visibility-timeout 300

aws sqs send-message --message-deduplication-id 3 --message-group-id g1 --message-body "m3" --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1


aws sqs send-message --message-deduplication-id 4 --message-group-id g1 --message-body "m4" --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1

aws sqs send-message --message-deduplication-id 5 --message-group-id g1 --message-body "m5" --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1

#should not receive any message
aws sqs receive-message --queue-url http://localhost:4566/000000000000/test.fifo --endpoint-url http://localhost:4566 --no-sign-request --region=us-east-1 --attribute-name All --max-number-of-messages 5 --visibility-timeout 300
```

### Environment

```markdown
- OS: Windows 10
- LocalStack: latest

Docker Desktop in Hyper-V mode
```
