### ISSUE TITLE
bug: localstack s3 buckets getting deleted after restarting the container.

### ISSUE THREAD

**Issue by jkugsiya** [localstack/localstack#6799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when creating a bucket and storing some objects in it, after which restarting the container removes all the buckets and starts as new, all the data is getting lost.

### Expected Behavior

The buckets and data should be persisted even after restart of the container.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose file:
```
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    environment:
      - SERVICES=s3,s3api
      - PERSISTENCE=1
    ports:
      - '4566-4599:4566-4599'
    networks:
      - main_network
    volumes:
      - localstack_data:/var/lib/localstack
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3api create-bucket --bucket test
    {
        "Location": "/test"
    }
    awslocal s3api list-buckets
    {
        "Buckets": [
            {
                "Name": "test",
                "CreationDate": "2022-09-01T09:31:10.000Z"
            }
        ],
        "Owner": {
            "DisplayName": "webfile",
            "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
        }
    }

    docker restart localstack

    awslocal s3api list-buckets
    {
        "Buckets": [],
        "Owner": {
            "DisplayName": "webfile",
            "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
        }
    }

### Environment

```markdown
- OS:Linux
- LocalStack: latest
```

**Comment by thrau** [comment]
Hi @jkugsiya, just to verify:
1. are you using LocalStack pro? Persistence is currently a pro feature and will only work is you have an API key configured
2. Do you have the same issue if you use a bind mount to /var/lib/localstack instead of a named volume?

**Comment by jkugsiya** [comment]
> Hi @jkugsiya, just to verify:
> 
> 1. are you using LocalStack pro? Persistence is currently a pro feature and will only work is you have an API key configured
> 2. Do you have the same issue if you use a bind mount to /var/lib/localstack instead of a named volume?

Hello @thrau!
No, I don't have localstack pro. But the persistence did work in older versions of localstack.

**Comment by MikeG96** [comment]
> > Hi @jkugsiya, just to verify:
> > 
> > 1. are you using LocalStack pro? Persistence is currently a pro feature and will only work is you have an API key configured
> > 2. Do you have the same issue if you use a bind mount to /var/lib/localstack instead of a named volume?
> 
> Hello @thrau! No, I don't have localstack pro. But the persistence did work in older versions of localstack.

Hello

Currently is deprecated for Community Edition

**Comment by HariVamsiK** [comment]
Hi
I want to contribute on this issue. Please assign it to me. It would be a great addon for my academics.
Thanks

**Comment by guoyunhe** [comment]
I have a trail API key. However, the s3 data is not persist:

```yaml
version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=xxxxxx
      - REQUIRE_PRO=1
    volumes:
      - .volumes/localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
```
