### ISSUE TITLE
bug: Attempting to instantiate a new OpenSearch domain via CDK failing?

### ISSUE THREAD

**Issue by jonofoz** [localstack/localstack#6830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi again!

Please bear with me, as this may well be an error on my end: I'm still quite new to CDK and LocalStack. And to that end, I'm not sure it _this_ is the best place for this question, as it may be a CDK related issue and nothing to do with LocalStack.

I've followed the [AWS Quick start guide here](https://docs.aws.amazon.com/cdk/api/v1/docs/aws-opensearchservice-readme.html#importing-existing-domains) but have had no luck so far getting it to work as I was expecting within LocalStack. I even created the suggested service role (albeit with `awslocal`), but either I did something incorrectly or it didn't solve my issue.

Below are two snippets of code, the first trying to get an existing domain via endpoint but creating a new domain as necessary, and the second just trying to create a new domain from scratch. 

**Code A**
``` ts
const documentsDomain = documentsOpenSearchDomainEndpoint
  ? opensearch.Domain.fromDomainEndpoint(
      this,
      documentsOpenSearchDomainName,
      documentsOpenSearchDomainEndpoint
    )
  : new opensearch.Domain(this, documentsOpenSearchDomainName, {
      version: opensearch.EngineVersion.OPENSEARCH_1_0,
    });
```

**Code B**
``` ts
    const documentsDomain = new opensearch.Domain(
      this,
      documentsOpenSearchDomainName,
      {
        version: opensearch.EngineVersion.OPENSEARCH_1_0,
      }
    );
```

I've documented a number of scenarios I've tried with these two different sets of code, using Code A in every one except where stated. 
Please note, 
- `documentsOpenSearchDomainName` and `documentsOpenSearchDomainEndpoint` are indeed defined
- I recomposed my the `localstack` Docker container group each time for the clearest results 

**Scenarios**

1. ✅
  - See that `localstack status services` shows OpenSearch as available but not running
  - Run `create-domain` with `awslocal` and let processing complete
  - See that `localstack status services` shows OpenSearch as running
  - Run `cdklocal bootstrap; cdklocal deploy`
  - Deployment is seemingly successful with no errors

2. ❌
  - See that `localstack status services` shows OpenSearch as available but not running  
  - DON'T run `create-domain` with `awslocal` beforehand
  - Run `cdklocal bootstrap; cdklocal deploy`
  - Failure 
    - <img width="770" alt="image" src="https://user-images.githubusercontent.com/29444592/188678241-09a8445a-fb64-4fa1-bc70-dfe81762790c.png">
  - See that, despite failing to deploy, `localstack status services` shows OpenSearch as  running now
  - Run `list-domain-names` with `awslocal` to see if any domains were created despite the error
  - See no domains were created

3. ❌
  - Repeat all of the steps in Scenario 2
  - Run `cdklocal deploy` to see if it was a timing issue, since OpenSearch was shown to be "running" after it failed
  - Get failure message from Scenario 2 again

4. **✅?!?!?**
  - Repeat all of the steps in Scenario 1
  - Run `delete-domain` on the domain with `awslocal`
  - Run `list-domain-names` with `awslocal` to make sure it's gone
  - See the domain is gone
  - Run `cdklocal deploy` again, expecting failure
  - It deploys successfully???
  - Run `list-domain-names` with `awslocal` to see if any domains were created
  - See no domains were created

5. ❌
  - Repeat all of the steps in Scenario 1
  - Swap out Code A for Code B
  - Run `cdklocal deploy`
  - Get failure message from Scenario 2
  - Swap out Code B for Code A
  - Run `cdklocal deploy`
  - Get failure message from Scenario 2

Any ideas?

Thanks!

### Expected Behavior

A new OpenSearch domain is deployed to LocalStack when declared via CDK

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

From the directory where the `localstack` compose file is,
   `docker compose up -D`
   
(And here's the compose file:)
```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging: &loggingLocal
      driver: local 
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   cdklocal bootstrap; cdklocal deploy

### Environment

```markdown
- OS: MacOS Monterey v12.1
- LocalStack: latest
```
