### ISSUE TITLE
bug: Unable to execute HTTP request: Certificate for <localstack> doesn't match any of the subject alternative names 

### ISSUE THREAD

**Issue by pocockn** [localstack/localstack#6874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using local stack Kinesis with Apache Flink I get the following error:

`flink-compose-kinesis-master-1         | org.apache.flink.kinesis.shaded.com.amazonaws.SdkClientException: Unable to execute HTTP request: Certificate for <localstack> doesn't match any of the subject alternative names: [*.amplifyapp.localhost.localstack.cloud, *.cloudfront.localhost.localstack.cloud, *.execute-api.localhost.localstack.cloud, *.localhost.localstack.cloud, *.opensearch.localhost.localstack.cloud, *.s3.localhost.localstack.cloud, *.scm.localhost.localstack.cloud, localhost.localstack.cloud]`

My docker compose looks like

```
  localstack:
    image: "localstack/localstack:latest"
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - "SERVICES=kinesis"
      - "DEFAULT_REGION=us-east-1"
      - "KINESIS_INITIALIZE_STREAMS=customer-details:2:us-east-1"
      - "HOSTNAME=localstack"
      - "USE_SSL=1"
      - "LAMBDA_EXECUTOR=local"
      - "LAMBDA_REMOTE_DOCKER=false"
      - "DATA_DIR=/tmp/localstack/data"
    networks:
      - backplane
```      

### Expected Behavior

HTTPS works when using LocalStack Kinesis

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Run Kinesis local stack, point the Apache Flink statefun to the Kinesis stream and run

### Environment

```markdown
- OS: Mac
- LocalStack: latest
```
