### ISSUE TITLE
bug: CORS Error when using APIGateway on localhost

### ISSUE THREAD

**Issue by AlexCoursi** [localstack/localstack#6877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deploy a template SAM in localstack, the CORS are not disabled or took in account in the APIGateway service. 

I tried to put in my template: 
```
Globals:
    Api:
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"
```

or:

```
ApiDeployment:
        Type: AWS::Serverless::Api
        Properties:
            Cors:
                AllowMethods: "'*'"
                AllowHeaders: "'*'"
                AllowOrigin: "'*'
```

I launched localstack with the following command:
`DATA_DIR=/tmp/localstack/data DEFAULT_REGION=eu-west-3 DEBUG=1 DISABLE_CORS_CHECKS=1 localstack start
`
Then, I create a simple page in react and I tried to call my APIGateway (using this URL: `http://localhost:4566/restapis/qj51i59y9u/dev/_user_request_`)

And I get an error about CORS with Method OPTIONS and POST:

`Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://localhost:4566/restapis/qj51i59y9u/dev/_user_request_/readdb. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.`

It's working when I tried to call the local API with curl and it's working as well when I deploy on AWS, my simple page on local can call the API on AWS.

Before (around december 2021), it was working perfectly with localstack.

If I execute the following command it's working : 
`aws apigateway put-integration-response --rest-api-id oyhk02q4vs --resource-id r9k9d9cw1u --http-method OPTIONS --status-code 200 --selection-pattern 200 --response-parameters '{"method.response.header.Access-Control-Allow-Origin": "'"'"'*'"'"'","method.response.header.Access-Control-Allow-Methods": "'"'"'*'"'"'","method.response.header.Access-Control-Allow-Headers": "'"'"'*'"'"'"}' --endpoint-url=http://localhost:4566`

### Expected Behavior

I don't want to get CORS errors on localhost when I use:

`DATA_DIR=/tmp/localstack/data DEFAULT_REGION=eu-west-3 DEBUG=1 DISABLE_CORS_CHECKS=1 localstack start`

or

```
ApiDeployment:
        Type: AWS::Serverless::Api
        Properties:
            Cors:
                AllowMethods: "'*'"
                AllowHeaders: "'*'"
                AllowOrigin: "'*'
```

### How are you starting LocalStack?

With the `localstack` script

### Steps To Reproduce

- Create a template SAM with an APIGateway (POST Method)

- Deploy this template:

`samlocal deploy --guided --config-env dev`

- Create a simple page react ("create-react-app) and try to call the APIGateway

### Environment

```markdown
- OS:Ubuntu 20.04.5 LTS
- LocalStack:latest
```
