### ISSUE TITLE
bug: API Gateway Domains not saved between versions

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#6897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Domain names are not saved between API Gateway V1 and API Gateway V2. After creating a custom domain using the v2 endpoint (via terraform `aws_apigatewayv2_domain_name`) the domain can be listed via the v2 endpoint but not the v1.

### Expected Behavior

The different versions should have the resources synced between them.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose.yaml
```yaml
version: "3.3"
services:
  localstack:
    image: localstack/localstack
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "apigateway,iam,sts,ec2,secretsmanager,acm,route53"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DEBUG: "1"
      LS_LOG: "trace"
      TEST_AWS_ACCOUNT_ID: "000000000000"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```
main.tf
```terraform
resource "aws_apigatewayv2_domain_name" "mydomain" {
  domain_name = "mydomain.com"
  domain_name_configuration {
    certificate_arn = data.aws_acm_certificate.mydomain.arn
    endpoint_type   = "REGIONAL"
    security_policy = "TLS_1_2"
  }
}
```
```
% awslocal apigateway get-domain-names
{
    "items": []
}
% awslocal apigatewayv2 get-domain-names
{
    "Items": [
        {
            "DomainName": "mydomain.com",
            "DomainNameConfigurations": [
                {
                    "ApiGatewayDomainName": "mydomain.com",
                    "CertificateArn": "arn:aws:acm:us-east-1:000000000000:certificate/edfe3ffe-f0c9-4e3a-a74c-d076c3536960",
                    "DomainNameStatus": "AVAILABLE",
                    "DomainNameStatusMessage": "The domain name is available",
                    "EndpointType": "REGIONAL",
                    "SecurityPolicy": "TLS_1_2"
                }
            ],
            "Tags": {
                "environment": "local"
            }
        }
    ]
}
```

### Environment

```markdown
- OS:Monterey 12.6
- LocalStack: latest (91779a2a0731)
```
