### ISSUE TITLE
bug: Cloud Pod missing resources after injection

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#6914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After injecting a cloud pod into the running container there are resources that are missing. Specifically the resources I've found to go missing are ACM certificates and an API Gateway V2 domain name.

### Expected Behavior

All resources should be present after injection.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3.3"
services:
  localstack:
    image: localstack/localstack:1.1.0
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "apigateway,iam,sts,ec2,secretsmanager,acm,route53,logs,s3"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DEBUG: "1"
      LS_LOG: "trace"
      TEST_AWS_ACCOUNT_ID: "000000000000"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```

```bash
% docker-compose up -d
% awslocal acm request-certificate --domain-name 'example.com'
{
    "CertificateArn": "arn:aws:acm:us-east-1:000000000000:certificate/5590dfa0-a9ba-493d-81bc-89ed471550a9"
}
% awslocal apigatewayv2 create-domain-name --domain-name "example.com"
{
    "DomainName": "example.com",
    "DomainNameConfigurations": []
}
% awslocal s3api create-bucket --bucket mybucket
{
    "Location": "/mybucket"
}

% localstack pod push -n test
% docker-compose down
% docker-compose up -d

# this should return nothing since we restarted the container
% awslocal acm list-certificates
{
    "CertificateSummaryList": []
}
% awslocal apigatewayv2 get-domain-names
{
    "CertificateSummaryList": []
}
% awslocal s3api list-buckets
{
    "Buckets": [],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}

% localstack pod pull -n test
% awslocal acm list-certificates
{
    "CertificateSummaryList": []
}
% awslocal apigatewayv2 get-domain-names
{
    "Items": []
}
# as expected some resources do work
% awslocal s3api list-buckets
{
    "Buckets": [
        {
            "Name": "mybucket",
            "CreationDate": "2022-09-22T21:40:32.000Z"
        }
    ],
    "Owner": {
        "DisplayName": "webfile",
        "ID": "bcaf1ffd86f41161ca5fb16fd081034f"
    }
}
```

Was also unfortunately unable to test using latest `f2c7e670ebae` because running the pod pull command resulted in the following error:
`Error: Unable to reset service state via local management API http://localhost:4566/_pods/state/reset (code 500): b'{"message": "Unexpected exception", "error": "Ran out of input", "type": "EOFError"}'`

### Environment

```markdown
- OS: macos 12.6
- LocalStack: 1.1.0
```
