### ISSUE TITLE
bug: Cloud Pod will not inject using latest image

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#6920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the latest docker images I receive and error when trying to inject a cloud pod.

### Expected Behavior

Resources from the pod should load successfully

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3.3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "apigateway,iam,sts,ec2,secretsmanager,acm,route53,logs"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DEBUG: "1"
      LS_LOG: "trace"
      TEST_AWS_ACCOUNT_ID: "000000000000"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```

```bash
% docker-compose up -d
% awslocal s3api create-bucket --bucket mybucket
% localstack pod push -n mypod
% docker-compose down && docker-compose up -d
% localstack pod pull -n mypod
Error: Unable to reset service state via local management API http://localhost:4566/_pods/state/reset (code 500): b'{"message": "Unexpected exception", "error": "Ran out of input", "type": "EOFError"}'
```

### Environment

```markdown
- OS: macos v12.4
- LocalStack: latest `8dde0c2fbe2d`
```

### Anything else?

This issue does not occur with version 1.1.0.

Images attempted:
- f95d67f67b93
- 9dcc24910625
- bcf4bc400a32
