### ISSUE TITLE
bug: SNS multi subscription to lambda does not work using serverless

### ISSUE THREAD

**Issue by arielbeckjit** [localstack/localstack#6963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've created a serverless yaml with a super simple lambda + 2 sns subscriptions:
```
  mylambda:
    handler: handler.handler
    memorySize: 128
    events:
      - sns: 
          arn: arn:aws:sns::us-east-1:#{AWS::AccountId}:mytopic
          topicName: mytopic-:us-east-1
      - sns:
          arn: arn:aws:sns::us-east-2:#{AWS::AccountId}:mytopic
          topicName:mytopic-:us-east-2
```

I've tried with and without creating the topics in advance, but the deployment fails with:
```
2022-10-02T16:26:54.313:WARNING:localstack.utils.cloudformation.template_deployer: Error calling <bound method ClientCreator._create_api_method.<locals>._api_call of <botocore.client.SNS object at 0x7faa279b7af0>> with params: {'TopicArn': 'arn:aws:sns:us-east-1:000000000000:mytopic', 'Protocol': 'lambda', 'Endpoint': 'arn:aws:lambda:us-east-1:000000000000:function:mylambda', 'Attributes': {}} for resource: {'Type': 'AWS::SNS::Subscription', 'LogicalResourceId': 'CloudDashformationDashstackDashlistenerSnsSubscriptionmytopic', 'Properties': {'TopicArn': 'arn:aws:sns:us-east-1:000000000000:mytopic', 'Protocol': 'lambda', 'Endpoint': 'arn:aws:lambda:us-east-1:000000000000:function:mylambda'}, '_state_': {}}
```

Deploying the same configuration directly to AWS works.
There's also no informative error message and i'm at verbose (why?)

I've also tried to create the sns manually, but still doesn't work.

### Expected Behavior

The deployment should NOT fail

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    sls deploy with the above example.

### Environment

```markdown
- OS:both mac and a linux container
- LocalStack: 1.0.4
```
