### ISSUE TITLE
bug: API Gateway v2:  API Mapping fails to utilize mapping key

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#6984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm utilizing API Gateway v2 with a custom domain name and API mapping. All requests and responses for the creation are correct but when I make requests to the endpoint it does now behave as expected. Here is the setup:

- API Gateway
- Domain Name
- API Mapping
- Route
- Integration

```terraform
resource "aws_apigatewayv2_api" "api" {
  name          = "api"
  protocol_type = "HTTP"
}
resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.api.id
  name        = "$default"
  auto_deploy = true
}
resource "aws_apigatewayv2_integration" "lambda" {
  api_id                 = aws_apigatewayv2_api.api.id
  integration_type       = "AWS_PROXY"
  integration_method     = "POST"
  integration_uri        = module.lambda.lambda_function_invoke_arn
  payload_format_version = "2.0"
}
resource "aws_apigatewayv2_route" "endpoint" {
  api_id    = aws_apigatewayv2_api.api.id
  route_key = "GET /endpoint"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}
resource "aws_apigatewayv2_api_mapping" "mapping" {
  api_id          = aws_apigatewayv2_api.api.id
  domain_name = "api.mydomain.com"
  stage           = aws_apigatewayv2_stage.default.id
  api_mapping_key = "prefix"
}
```

With this configuration I would expect to be able to make requests to `https://api.mydomain.com/prefix/endpoint`. However, the behavior I see is that this endpoint is not found but I can make requests to `https://api.mydomain.com/endpoint` ignoring the API mapping prefix.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3.3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "apigateway,iam,sts,ec2,secretsmanager,acm,route53,logs,lambda"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DISABLE_CORS_CHECKS: 1
      DEBUG: "1"
      LS_LOG: "trace"
      TEST_AWS_ACCOUNT_ID: "000000000000"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```

### Environment

```markdown
- OS: macOS Monterey 12.6
- LocalStack: latest `86b855a67499`
```
