### ISSUE TITLE
bug:  Unknown parameter in GlobalSecondaryIndexes[0]: "ContributorInsightsSpecification"

### ISSUE THREAD

**Issue by johanvogelzang-topicus** [localstack/localstack#7007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploying the CloudFormation template below to localstack results in error:

`Unknown parameter in GlobalSecondaryIndexes[0]: "ContributorInsightsSpecification", must be one of: IndexName, KeySchema, Projection, ProvisionedThroughput`

According to the [AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-globalsecondaryindex.html) the ContributorInsightsSpecification seems a valid property of the GlobalSecondaryIndexes.

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  33ParticipantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: "mytesttable"
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: "ptpKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ptpKey"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "MyIndexName"
          KeySchema:
            - AttributeName: "cdKey"
              KeyType: "HASH"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "ptpKey"
          ContributorInsightsSpecification:
            Enabled: True
```

### Expected Behavior

succesful deployment without error

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   samlocal deploy --region="eu-west-1" \
    --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_IAM \
    --stack-name dynamodb-test \
    --s3-bucket "test-bucket" \
    --template-file "/test/dynamodb-out.yaml"

### Environment

```markdown
- OS:macOS
- LocalStack: image: localstack/localstack:1.2.0 (also 1.1.0)
```
