### ISSUE TITLE
bug: ResourceNotFoundException when calling the DescribeLogStreams operation

### ISSUE THREAD

**Issue by hemagso** [localstack/localstack#7021]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When working with lambda functions and cloudwatch localstack returns a ResourceNotFoundExceptio when listing log streams even when log groups exists.

This seems to be similar to #2003 and #6077, but I found no solution on those Issues.

### Expected Behavior

Localstack should list the log streams available in the log group.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

I'm running

```bash
docker-compose up
```

With the folowwing `docker-compose.yml` file:

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Firstly I provision the bare minimum infrastructure using the following `main.tf` file:

```tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.2.0"
    }
  }
}

provider "aws" {
    access_key = "fake"
    secret_key = "fake"
    region = "us-east-1"
    skip_credentials_validation = true
    skip_metadata_api_check = true
    skip_requesting_account_id = true

    endpoints {
      lambda = "http://localhost:4566"
      iam = "http://localhost:4566"
    }
}


resource "aws_iam_role" "main" {
    name = "lambda_execution_role"
    assume_role_policy = jsonencode({
        Version = "2012-10-17"
        Statement = [{
            Action = "sts:AssumeRole",
            Principal = {
                Service = "lambda.amazonaws.com"
            }
            Effect = "Allow"
            Sid = ""
        }]
    })
}

resource "aws_lambda_function" "main" {
    function_name = "hello_world"

    runtime = "python3.9"
    handler = "handler.lambda_handler"
    role = aws_iam_role.main.name

    filename = "build/handler.zip"
    source_code_hash = filebase64sha256("build/handler.zip")
}
```

The contents of the `handler.zip` file is a single `handler.py` file containing the following python code:

```python
def lambda_handler(event, context):
    print("Something for the logs")
    return "Hello World"
```

After that I use the AWS CLI to perform the following operations:"

- List all available log groups (describe-log-groups-1.log)
- Invoke the lambda function one (lambda-invoke.log)
- List all available log groups a second time (describe-log-groups-2.log)
- List the log streams for the log group for the lambda function (describe-log-streams.log)

The output of all commands are listed below:

*describe-log-groups-1.log*
Here we can see there are currently no logs in cloudwatch.
```txt
$ aws --endpoint-url=http://localhost:4566 logs describe-log-groups
{
    "logGroups": []
}
```

*lambda-invoke.log*
```txt
$ aws --endpoint-url=http://localhost:4566 lambda invoke --function-name=hello_world response.txt
{
    "StatusCode": 200,
    "LogResult": "",
    "ExecutedVersion": "$LATEST"
}
```

*describe-log-groups-2.log*
Here we can see that the invocation of the lambda function wrote some data to the logs.
```txt
$ aws --endpoint-url=http://localhost:4566 logs describe-log-groups
{
    "logGroups": [
        {
            "logGroupName": "/aws/lambda/hello_world",
            "creationTime": 1665714565772,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:us-east-1:000000000000:log-group:/aws/lambda/hello_world",
            "storedBytes": 333
        }
    ]
}
```

*describe-log-streams.log*
Here we see that an error occur, despite the log-group existing, as shown by the command above.
```txt
$ aws --endpoint-url=http://localhost:4566 logs describe-log-streams --log-group-name=/aws/lambda/hello_world

An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist
```

All files mentioned here are available on the attached zip folder.

[minimal-example.zip](https://github.com/localstack/localstack/files/9782015/minimal-example.zip)

### Environment

```markdown
- OS: Windows 10
- LocalStack: Latest as of 2022-10-13
```
