### ISSUE TITLE
bug: Setting TEST_AWS_ACCOUNT_ID does not change the account ID in ARNs on Ubuntu 22.04

### ISSUE THREAD

**Issue by devpaulosouza** [localstack/localstack#7068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`TEST_AWS_ACCOUNT_ID` environment variable is not changing ARN ids in Ubuntu 22.04.

I used the same docker-compose.yml on others OS (Linux Mint 20 and Windows 10), but when running on Ubuntu 22.04 the ARN is set to 000000000000, ignoring the environment variable `TEST_AWS_ACCOUNT_ID` in docker-compose.yml.

### Expected Behavior

I expected the queue to be created with the ARN given in the environment variable.

"QueueUrl": "http://localhost:4566/966432911111/my-queue"
instead of:
"QueueUrl": "http://localhost:4566/000000000000/my-queue"

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Here is docker-compose.yml

```yml
version: '3.7'
services:
  aws:
    image: 'localstack/localstack:latest'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=AAAAAAAAAAAAAAAAAA
      - AWS_SECRET_ACCESS_KEY=AAAAAAAAAAAAAA
      - TEST_AWS_ACCOUNT_ID=966432911111
    ports:
      - '4566:4566'
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
export SQS_ENDPOINT=http://localhost:4566
aws --endpoint-url $SQS_ENDPOINT sqs create-queue --queue-name my-queue --region us-east-1
```

Output:
```sh
$ export SQS_ENDPOINT=http://localhost:4566
aws --endpoint-url $SQS_ENDPOINT sqs create-queue --queue-name my-queue --region us-east-1
{
    "QueueUrl": "http://localhost:4566/000000000000/my-queue"
}

It was expected to be "QueueUrl": "http://localhost:4566/966432911111/my-queue"

```

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: latest
- Docker: 20.10.20
- docker-compose: 1.29.2
```

### Anything else?

I found a similar issue at https://github.com/localstack/localstack/issues/1728, but still happens on Ubuntu 22.04
