### ISSUE TITLE
bug: Liveness and readiness probe failed, even with huge initialDelay

### ISSUE THREAD

**Issue by dir** [localstack/localstack#7069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey guys, I am trying to set up localstack on my local minikube cluster. The steps I am taking are as follows:

When I go to describe the pod, I am getting this:

```
Name:             localstack-d8c8f8c55-m4hxm
Namespace:        luke
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Fri, 21 Oct 2022 13:55:48 -0500
Labels:           app=localstack
                  pod-template-hash=d8c8f8c55
Annotations:      <none>
Status:           Running
IP:               172.17.0.3
IPs:
  IP:           172.17.0.3
Controlled By:  ReplicaSet/localstack-d8c8f8c55
Containers:
  localstack:
    Container ID:   docker://8be051d80c18c2f4f17ddf73584fb6d9e2f3d6cf1596f5f2f34f457b8f683161
    Image:          localstack/localstack:latest
    Image ID:       docker-pullable://localstack/localstack@sha256:f80dbf636260ef08b686706b7522ed2162bb6edacea40b2893c19470060bf129
    Ports:          4566/TCP, 4571/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Fri, 21 Oct 2022 14:02:59 -0500
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 21 Oct 2022 13:56:22 -0500
      Finished:     Fri, 21 Oct 2022 14:02:58 -0500
    Ready:          False
    Restart Count:  1
    Liveness:       http-get http://:edge/health delay=300s timeout=10s period=10s #success=1 #failure=10
    Readiness:      http-get http://:edge/health delay=300s timeout=10s period=10s #success=1 #failure=10
    Environment:
      DEBUG:               0
      LOCALSTACK_API_KEY:  123456
    Mounts:
      /docker-entrypoint-initdb.d from init-localstack (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s7829 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  init-localstack:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      init-localstack
    Optional:  false
  kube-api-access-s7829:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  13m                     default-scheduler  Successfully assigned pdl/localstack-d8c8f8c55-m4hxm to minikube
  Normal   Pulling    13m                     kubelet            Pulling image "localstack/localstack:latest"
  Normal   Pulled     13m                     kubelet            Successfully pulled image "localstack/localstack:latest" in 33.288115015s
  Normal   Created    13m                     kubelet            Created container localstack
  Normal   Started    13m                     kubelet            Started container localstack
  Warning  Unhealthy  6m29s (x12 over 7m59s)  kubelet            Readiness probe failed: Get "http://172.17.0.3:4566/health": dial tcp 172.17.0.3:4566: connect: connection refused
  Warning  Unhealthy  79s (x11 over 7m59s)    kubelet            Liveness probe failed: Get "http://172.17.0.3:4566/health": dial tcp 172.17.0.3:4566: connect: connection refused
```

Anyone have any ideas? Thank you!

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

1. Create my deployment from this YAML file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: localstack
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG
          value: "0"
        - name: LOCALSTACK_API_KEY
          value: 1234567
        ports:
        - containerPort: 4566
          name: edge
          protocol: TCP
        - containerPort: 4571
          name: es
          protocol: TCP
        volumeMounts:
          - name: init-localstack
            mountPath: /docker-entrypoint-initdb.d
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: edge
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
          initialDelaySeconds: 300
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: edge
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
          initialDelaySeconds: 300
      volumes:
        - name: init-localstack
          configMap:
            name: init-localstack
            items:
              - key: init-script
                path: init-script.sh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-localstack
data:
  init-script: |-
    #!bin/bash

    echo "### Init S3 ###"


---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  ports:
  - name: edge
    nodePort: 31566
    port: 4566
    protocol: TCP
    targetPort: 4566
  - name: es
    nodePort: 31571
    port: 4571
    protocol: TCP
    targetPort: 4571
  selector:
    app: localstack
  type: NodePort
```

2. Run `minikube service localstack`

### Environment

```markdown
- OS: Mac w/ M1 Max
- LocalStack: latest
```
