### ISSUE TITLE
bug: latest Docker image doesn't support PERSISTENCE

### ISSUE THREAD

**Issue by guoyunhe** [localstack/localstack#7076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PERSISTENCE=1 doesn't make S3 data persist.

### Expected Behavior

PERSISTENCE=1 should make S3 data persist.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

```yaml
version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=xxxxxx
      - REQUIRE_PRO=1
    volumes:
      - .volumes/localstack:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3api create-bucket --bucket test

### Environment

```markdown
- OS: openSUSE Tumbleweed
- LocalStack: Docker latest image
```

### Anything else?

Docker image 1.1.0 works fine. But latest doesn't work.
