### ISSUE TITLE
bug: lambda_destination for EventBridge does not use correct payload.

### ISSUE THREAD

**Issue by diogo-pinho-cko** [localstack/localstack#7089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently on localstack the integration with `lambda_destination` for EventBridge is broken.

The method `_lambda_result_to_destination` defines a `payload` object which is in turn passed as a parameter to `send_event_to_target`  which in turn, when using the EventBridge integration, tries to fetch properties that are not defined on the payload itself such as `detail-type` for example.

Please see the snippets below for the code flow.

https://github.com/localstack/localstack/blob/434b9eb2daaf27a5dda6e1c6f75e56d7958fe3f8/localstack/services/awslambda/lambda_executors.py#L394-L435

https://github.com/localstack/localstack/blob/434b9eb2daaf27a5dda6e1c6f75e56d7958fe3f8/localstack/services/awslambda/lambda_executors.py#L435

https://github.com/localstack/localstack/blob/434b9eb2daaf27a5dda6e1c6f75e56d7958fe3f8/localstack/utils/aws/message_forwarding.py#L77-L89

### Expected Behavior

Integration should work, properties should not be fetch from the `payload` root but instead form the property `responsePayload` on the payload.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3.9"

services:
  localstack:
    container_name: "aws-local"
    image: localstack/localstack@sha256:877be662e62466621fbeecedfc0352c5f2464ace8b3bd7d9095decf22bb383b2 # stable version had a bug at the time, pull untagged latest instead.
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_STAY_OPEN_MODE=0 # disable for Hotswapping
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/localstack:/var/lib/localstack
      - ./src/:/var/lib/localstack/src
```

### Environment

```markdown
- OS: Windows 11 Pro 64-bit (10.0, Build 22000)
- LocalStack: @sha256:877be662e62466621fbeecedfc0352c5f2464ace8b3bd7d9095decf22bb383b2
```

### Anything else?

Sample logs for the error:

```
aws-local | 2022-10-25T13:51:23.043  INFO --- [cthread28781] localstack.utils.threads   : Thread run method <function LambdaExecutor.execute.<locals>.do_execute at 0x7f093894e170>(None) failed: Parameter validation failed:
aws-local | Invalid type for parameter Entries[0].Source, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
aws-local | Invalid type for parameter Entries[0].DetailType, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
aws-local | Invalid type for parameter Entries[0].Detail, value: None, type: <class 'NoneType'>, valid types: <class 'str'> Traceback (most recent call last):
aws-local |   File "/opt/code/localstack/localstack/utils/threads.py", line 58, in run
aws-local |     result = self.func(self.params, **kwargs)
aws-local |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 485, in do_execute
aws-local |     return _run(func_arn=func_arn)
aws-local |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
aws-local |     raise e
aws-local |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
aws-local |     result = func(*args, **kwargs)
aws-local |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 478, in _run
aws-local |     self._lambda_result_to_destination(
aws-local |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 435, in _lambda_result_to_destination
aws-local |     send_event_to_target(func_details.on_successful_invocation, payload)
aws-local |   File "/opt/code/localstack/localstack/utils/aws/message_forwarding.py", line 80, in send_event_to_target
aws-local |     events_client.put_events(
aws-local |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
aws-local |     return self._make_api_call(operation_name, kwargs)
aws-local |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 901, in _make_api_call
aws-local |     request_dict = self._convert_to_request_dict(
aws-local |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/client.py", line 962, in _convert_to_request_dict
aws-local |     request_dict = self._serializer.serialize_to_request(
aws-local |   File "/opt/code/localstack/.venv/lib/python3.10/site-packages/botocore/validate.py", line 381, in serialize_to_request
aws-local |     raise ParamValidationError(report=report.generate_report())
aws-local | botocore.exceptions.ParamValidationError: Parameter validation failed:
aws-local | Invalid type for parameter Entries[0].Source, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
aws-local | Invalid type for parameter Entries[0].DetailType, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
aws-local | Invalid type for parameter Entries[0].Detail, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```
