### ISSUE TITLE
bug: Pulumi Error while try to use s3 bucket localstack

### ISSUE THREAD

**Issue by aadi58002** [localstack/localstack#7090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to create a S3 bucket with pulumi i get the error 
```
Diagnostics:
  aws-native:s3:Bucket (my-bucket):
    error: could not get AWS account ID: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: e0b6e154-d165-4b14-9dc2-8a87643648bf, api error InvalidClientTokenId: The security token included in the request is invalid.
 ```

### Expected Behavior

To be able to create s3 buckets with pulumi

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    podman run --rm -it -p 4566:4566 -p 4510-4559:4510-4559 docker.io/localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   pulumi up
   ( With the default aws-native-python options and adding the followings to the Pulumi.dev.yaml -> https://pastebin.com/t0knn7YA

### Environment

```markdown
- OS: Arch Linux
- LocalStack: LocalStack version: 1.2.1.dev
- Pulumi version: 3.42.0
```

### Anything else?

I have followed the docs at https://docs.localstack.cloud/integrations/pulumi/#quickstart
I have also tried with pulumilocal but same error when i run `laws sts get-caller-identity`.
Its output is
```
{
    "UserId": "AKIAIOSFODNN7EXAMPLE",
    "Account": "000000000000",
    "Arn": "arn:aws:iam::000000000000:root"
}
```
Which seems to work perfectly fine

**Comment by steffyP** [comment]
Hi @aadi58002,

unfortunately I wasn't able yet to reproduce your issue. 
Do you also see this error, when you use the "quickstart" sample from pulumi, e.g. for `pulumi new aws-yaml` the default `Pulumi.yaml` will contain:
```
name: quickstart
description: A minimal AWS Pulumi YAML program
runtime: yaml
resources:
    # Create an AWS resource (S3 Bucket)
    my-bucket:
        type: aws:s3:Bucket
outputs:
    # Export the name of the bucket
    bucketName: ${my-bucket.id}
``` 

Is the example you tested, or do you have a different deployment configuration?
Could you also try pulling the `latest` image by running `docker pull localstack/localstack:latest` 🙏
