### ISSUE TITLE
bug: DynamoDB stores are not populated when localstack is restarted in persistent mode

### ISSUE THREAD

**Issue by moscoso-guillermo** [localstack/localstack#7119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DynamoDB stores are not populated after restarting the docker container.
This is the exact same issue explained in #6842 which is marked as resolved in the latest image at the time by @whummer.

### Expected Behavior

After restarting the docker container it should be possible to write to the previously created table.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Here are the steps to reproduce using awscli

#### Create a table

1. `aws dynamodb create-table --cli-input-json file://table.json --endpoint-url=http://localhost:4566`

```
# table.json
{
    "TableName": "MusicCollection2",
    "KeySchema": [
      { "AttributeName": "Artist", "KeyType": "HASH" },
      { "AttributeName": "SongTitle", "KeyType": "RANGE" }
    ],
    "AttributeDefinitions": [
      { "AttributeName": "Artist", "AttributeType": "S" },
      { "AttributeName": "SongTitle", "AttributeType": "S" }
    ],
    "ProvisionedThroughput": {
      "ReadCapacityUnits": 5,
      "WriteCapacityUnits": 5
    }
}
```

#### Write a transaction

2. `aws dynamodb transact-write-items --transact-items file://artist.json --endpoint-url=http://localhost:4566`

```
# artist.json
[{
  "Put": {
    "Item": {
      "Artist": {
        "S": "Test"
      },
      "SongTitle": {
        "S": "Test"
      }
    },
    "TableName": "MusicCollection2"
  }
}]
```

#### Restart container

3. restart localstack container

#### Validate that table is persisted 

4. `aws dynamodb describe-table --table-name MusicCollection2 --endpoint-url=http://localhost:4566`

```
# response
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "Artist",
                "AttributeType": "S"
            },
            {
                "AttributeName": "SongTitle",
                "AttributeType": "S"
            }
        ],
        "TableName": "MusicCollection2",
        "KeySchema": [
            {
                "AttributeName": "Artist",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "SongTitle",
                "KeyType": "RANGE"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2022-11-03T12:27:19.670000+01:00",
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": "1970-01-01T01:00:00+01:00",
            "LastDecreaseDateTime": "1970-01-01T01:00:00+01:00",
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5
        },
        "TableSizeBytes": 23,
        "ItemCount": 1,
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/MusicCollection2",
        "TableId": "131c6694-1966-44cb-81d8-4af26b8c1942"
    }
}
```

#### Write a new object

5. `aws dynamodb transact-write-items --transact-items file://artist2.json --endpoint-url=http://localhost:4566`

```
# artist2.json
[{
  "Put": {
    "Item": {
      "Artist": {
        "S": "Test123"
      },
      "SongTitle": {
        "S": "Test123"
      }
    },
    "TableName": "MusicCollection2"
  }
}]
```

#### Error:

```
2022-11-03 12:37:52,994 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli\clidriver.py", line 458, in main
  File "awscli\clidriver.py", line 593, in __call__
  File "awscli\clidriver.py", line 769, in __call__
  File "awscli\clidriver.py", line 900, in invoke
  File "awscli\clidriver.py", line 912, in _make_client_call
  File "awscli\botocore\client.py", line 309, in _api_call
  File "awscli\botocore\client.py", line 639, in _make_api_call
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the TransactWriteItems operation: Unknown table: MusicCollection2 not found in dict_keys([])

An error occurred (ResourceNotFoundException) when calling the TransactWriteItems operation: Unknown table: MusicCollection2 not found in dict_keys([])
```

### Environment

```markdown
- OS: Windows 10
- LocalStack version: 1.2.1.dev (same with 1.2.0)
- LocalStack Docker container id: 81aa97400253
- LocalStack build date: 2022-11-03
- LocalStack build git hash: e14d6270
```

### Anything else?

This is exactly the same issue described #6842 fixed by @whummer  
I have tried this out on latest release `1.2.0` and latest dev `1.2.1`.dev finding the same issue.

**Comment by viren-nadkarni** [comment]
Possibly related to #7118

**Comment by viren-nadkarni** [comment]
Hi @moscoso-guillermo 

Do note that persistence is a Pro feature and the environment variable `LOCALSTACK_API_KEY` must be set to your Pro key.

Would you mind sharing the Docker Compose file to help us debug this?

**Comment by moscoso-guillermo** [comment]
Hi @viren-nadkarni 

Indeed I have performed the test again with the trial API key the error is gone.

This did not occur in the original ticket #6482 where both Pro and free versions were affected.

So I am not sure whether this ticket still makes sense for you.

 but here is my docker compose file just in case:

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4569:4566"
      - "127.0.0.1:4583:4583"
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - localstack
```
