### ISSUE TITLE
bug: Step Function not saving after docker restart #6486 

### ISSUE THREAD

**Issue by lee-butn** [localstack/localstack#7125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Same as original issues

Here is my docker-compose.yaml:

version: '2.1'

services:
  localstack:
    image: "localstack/localstack:latest"
    ports:
      - "4510-4571:4510-4571"
    environment:
      - LS_LOG=debug   
      - LOCALSTACK_API_KEY=*******
      - DEFAULT_REGION=ap-southeast-2
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:      
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

Everything else is persisted but not stepfunction. The "volume/state/stepfunctions/backend_state" file always empty !!

### Expected Behavior

Step function to be persisted after restart docker

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Restart docker-compose
2. Losed all stepfunctions created. 

### Environment

```markdown
- OS:
- LocalStack:
```

**Comment by lee-butn** [comment]
Any update on this ticket ? it blocking our development. Thanks

**Comment by dominikschubert** [comment]
Hi @lee-butn ! Unfortunately I cannot reproduce your issue. Please pull the latest images and try the steps below:


```yaml
# docker-compose.yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - DEFAULT_REGION=ap-southeast-2  # note: this isn't really required
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

```text
# statemachine.json

{
    "Comment": "A Hello World example of the Amazon States Language using a Pass state",
    "StartAt": "HelloWorld",
    "States": {
        "HelloWorld": {
            "Type": "Pass",
            "Result": "Hello World!",
            "End": true
        }
    }
}
```


steps to reproduce

```bash
# start localstack in PRO mode with persistence enabled
LOCALSTACK_API_KEY=<api-key> PERSISTENCE=1 docker-compose up -d

# empty, since we didn't create anything yet
awslocal stepfunctions list-state-machines --region ap-southeast-2

#  does not exist yet
cat ./volume/state/stepfunctions/backend_state

# create state machine in ap-southeast-2
awslocal stepfunctions create-state-machine --region ap-southeast-2 --name my-statemachine-1 --role-arn "arn:aws:iam::000000000000:role/sfn-rolename" --definition file://./statemachine.json

# list and state are now not empty anymore
awslocal stepfunctions list-state-machines --region ap-southeast-2
cat ./volume/state/stepfunctions/backend_state

# shut down localstack and restart
docker-compose down
LOCALSTACK_API_KEY=<api-key> PERSISTENCE=1 docker-compose up -d

# list and state are still non-empty
awslocal stepfunctions list-state-machines --region ap-southeast-2
cat ./volume/state/stepfunctions/backend_state

```
