### ISSUE TITLE
bug: InvalidAccessKeyId while using terragrunt with s3 as remote state

### ISSUE THREAD

**Issue by nmofonseca** [localstack/localstack#7127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```bash
INFO[0000] The stack at /dev/iac/aws/terraform/eu-west-2/devops/inputs_test will be processed in the following order for command apply:
Group 1
- Module /home/nuno4793/dev/iac/aws/terraform/eu-west-2/devops/inputs_test
 
Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n) y
Remote state S3 bucket remote-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) y
ERRO[0005] Create S3 bucket with retry remote-state returned an error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
        status code: 403, request id: Q7CY0RY8PXTH8DYC, host id: sENROE+W+H/NGS/nDbFBPJs34JGbhIHALcNoCoP/Rr2VOU3n273oM2XE/mXHP7JW56+QJBQKMhQ=. Sleeping for 10s and will try again.  prefix=dev/iac/aws/terraform/eu-west-2/devops/inputs_test] 

```

This has been mentioned on another issue that however has been closed, actually doesn't have a solution

https://github.com/localstack/localstack/issues/2540

### Expected Behavior

To create Remote state bucket and DynamoDb table for lock state.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

compose file:
```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - http_proxy=${HTTP_PROXY}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 ```

Start localstack:

docker compose -f localstack.yaml up -d

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terragrunt.hcl:

```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  } 
  config = {
    bucket         = "${local.prefix}-${local.environment}-remote-state"
    key            = "${local.aws_region}/${basename(path_relative_to_include())}/terraform.tfstate"
    region         = "eu-west-2"
    encrypt        = true
    dynamodb_table = "${local.prefix}-remote-state-lock"
  }
}

generate "provider.tf" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>${local.provider_vars.locals.aws_version}"
    }
    %{ if local.provider_vars.locals.include_postgres }
    postgresql = {
      source = "cyrilgdn/postgresql"
      version = "1.17.1"
    }
    %{ endif }
  }
}

# Configure the AWS Provider
provider "aws" {
  access_key = "test"
  secret_key = "test"
  region  = "${local.aws_region}"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {

    acm            = "http://localhost:4566"
    eks            = "http://localhost:4566"  
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
    rds            = "http://localhost:4566"
    ec2            = "http://localhost:4566"
  }  
}
EOF
}
```

### Environment

```markdown
- OS:"Ubuntu 20.04.5 LTS"
- LocalStack: latest ("1.2.1.dev")
```
