### ISSUE TITLE
bug: AWS RDS skip_final_snapshot doesn't have the same behaviour as AWS

### ISSUE THREAD

**Issue by nmofonseca** [localstack/localstack#7130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Terraform + Terragrunt and the terraform aws RDS module.

skip_final_snapshot=false

Applying the first time works fine the database get's created, if I destroy everything, apply everything again and destroy again it will fail because it will state that the final snapshot already exists:

```bash

#First Apply
Apply complete! Resources: 1 added, 1 changed, 1 destroyed.

Outputs:

db_instance_address = "localhost"
db_instance_arn = "arn:aws:rds:eu-west-2:000000000000:db:wtw-devops-db"
db_instance_availability_zone = "eu-west-2a"
db_instance_endpoint = "localhost:4510"
db_instance_id = "db"
db_instance_name = "main"
db_instance_port = 5432
db_instance_resource_id = "db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U"
db_instance_status = "available"
db_parameter_group = {
  "db_parameter_group_arn" = "arn:aws:rds:eu-west-2:000000000000:pg:postgres13-db-param-grp"
  "db_parameter_group_id" = "postgres13-db-param-grp"
}

#First Destroy** 

module.db.module.db_instance.aws_db_instance.this[0]: Destroying... [id=wtw-devops-db]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=wtw-devops-db, 10s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=wtw-devops-db, 20s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Still destroying... [id=wtw-devops-db, 30s elapsed]
module.db.module.db_instance.aws_db_instance.this[0]: Destruction complete after 31s
module.db.module.db_instance.random_id.snapshot_identifier[0]: Destroying... [id=sqFoaQ]
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Destroying... [id=wtw-devops-db-20221104160757250500000001]
module.db.module.db_instance.random_id.snapshot_identifier[0]: Destruction complete after 0s
module.rds_sg.aws_security_group.this_name_prefix[0]: Destroying... [id=sg-78a886111b74a6c1c]
module.rds_db_parameter_group.aws_db_parameter_group.this[0]: Destroying... [id=wtw-devops-postgres13-db-param-grp]
module.db.module.db_subnet_group.aws_db_subnet_group.this[0]: Destruction complete after 0s
module.rds_db_parameter_group.aws_db_parameter_group.this[0]: Destruction complete after 0s
module.rds_sg.aws_security_group.this_name_prefix[0]: Destruction complete after 0s

Destroy complete! Resources: 5 destroyed.

#2nd Apply

Apply complete! Resources: 8 added, 0 changed, 0 destroyed.

Outputs:

db_instance_address = "localhost"
db_instance_arn = "arn:aws:rds:eu-west-2:000000000000:db:wtw-devops-db"
db_instance_availability_zone = "eu-west-2a"
db_instance_endpoint = "localhost:4510"
db_instance_id = "wtw-devops-db"
db_instance_name = "main"
db_instance_port = 5432
db_instance_resource_id = "db-M5ENSHXFPU6XHZ4G4ZEI5QIO2U"
db_instance_status = "available"
db_parameter_group = {
  "db_parameter_group_arn" = "arn:aws:rds:eu-west-2:000000000000:pg:wtw-devops-postgres13-db-param-grp"
  "db_parameter_group_id" = "wtw-devops-postgres13-db-param-grp"
}

#2nd destroy  Fails with final snapshot already exists
```

### Expected Behavior

To destroy the database without erroring as is the case in AWS which I have done several times

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker compose -f localstack.yaml up -d

compose file:
```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
      - http_proxy=${HTTP_PROXY}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
 ```

.env file
```yaml

LOCALSTACK_API_KEY=XXXXXXX
LOCALSTACK_DOCKER_NAME="localstack"
HTTP_PROXY=XXXXX
HTTPS_PROXY=XXXX
PERSISTENCE=1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terragrunt apply

terragrunt.hcl:

```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  } 
  config = {
    bucket         = "${local.prefix}-${local.environment}-remote-state"
    key            = "${local.aws_region}/${basename(path_relative_to_include())}/terraform.tfstate"
    region         = "eu-west-2"
    encrypt        = true
    dynamodb_table = "${local.prefix}-remote-state-lock"
  }
}

generate "provider.tf" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~>${local.provider_vars.locals.aws_version}"
    }
    %{ if local.provider_vars.locals.include_postgres }
    postgresql = {
      source = "cyrilgdn/postgresql"
      version = "1.17.1"
    }
    %{ endif }
  }
}

# Configure the AWS Provider
provider "aws" {
  access_key = "test"
  secret_key = "test"
  region  = "${local.aws_region}"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {

    acm            = "http://localhost:4566"
    eks            = "http://localhost:4566"  
    apigateway     = "http://localhost:4566"
    cloudformation = "http://localhost:4566"
    cloudwatch     = "http://localhost:4566"
    dynamodb       = "http://localhost:4566"
    es             = "http://localhost:4566"
    firehose       = "http://localhost:4566"
    iam            = "http://localhost:4566"
    kinesis        = "http://localhost:4566"
    lambda         = "http://localhost:4566"
    route53        = "http://localhost:4566"
    redshift       = "http://localhost:4566"
    s3             = "http://localhost:4566"
    secretsmanager = "http://localhost:4566"
    ses            = "http://localhost:4566"
    sns            = "http://localhost:4566"
    sqs            = "http://localhost:4566"
    ssm            = "http://localhost:4566"
    stepfunctions  = "http://localhost:4566"
    sts            = "http://localhost:4566"
    rds            = "http://localhost:4566"
    ec2            = "http://localhost:4566"
  }  
}
EOF
}
```

### Environment

```markdown
- OS:"Ubuntu 20.04.5 LTS"
- LocalStack: latest ("1.2.1.dev")
- Terraform: v1.3.3
- Terragrunt: v0.39.2
```

### Anything else?

In addition there is a few more issues:

Terragrunt/Terraform plan once things have been applied always reports it's going to recreate the resources which Are not what I expect

The Db parameter group doesn't actually change the database configuration
