### ISSUE TITLE
bug: SQS message does not trigger CloudWatch alarm

### ISSUE THREAD

**Issue by gdsgj** [localstack/localstack#7131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I have a CloudWatch alarm for a message received in an SQS queue, it does not change state when I send a message in the queue

### Expected Behavior

The alarm state would change to be in alarm after I send a message in the queue

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    samlocal build
    samlocal deploy --guided
    aws --endpoint http://localhost:4566 sqs list-queues
    aws --endpoint http://localhost:4566 sqs send-message --queue-url http://localhost:4566/000000000000/<queue name> --message-body hello
    aws --endpoint http://localhost:4566 cloudwatch describe-alarms

### Environment

```markdown
- OS: macOS 12.5
- LocalStack: 1.1.0
```

### Anything else?

CloudFormation template:
```
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Queue:
    Type: AWS::SQS::Queue

  Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt Queue.QueueName
      EvaluationPeriods: 1
      MetricName: NumberOfMessagesReceived
      Namespace: AWS/SQS
      Period: 60
      Statistic: Sum
      Threshold: 0
```
