### ISSUE TITLE
Initialization hooks with .py script

### ISSUE THREAD

**Issue by IvanDanilau** [localstack/localstack#7134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I' 've launched following docker-compose.yaml 
```
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns
    ports:
      - '4566:4566'
    volumes:
      - "./localstack_setup:/etc/localstack/ready.d"
      - "${DATA_STORAGE_PATH}/localstack/:/var/lib/localstack"
```
  
In localstack_setup I have next init.py script:

```

   import os

   os.system("echo it should works")
```
But during the lauch of container I've got following row

```
Ready.
common-localstack-1 | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initaws.d/a_setup.py
```
What I do wrong? Could you provide any sample of .py script in documentation? My script is executable with python init.py as mentioned in documentation.

### Expected Behavior

.py script should work for init hooks

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`docker-compose up`

### Environment

```markdown
LocalStack version: 1.2.1.dev
Windows 10
```
