### ISSUE TITLE
Python init script failed

### ISSUE THREAD

**Issue by IvanDanilau** [localstack/localstack#7135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My docker-compose:

```
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns
    ports:
      - '4566:4566'
    volumes:
      - "./localstack:/etc/localstack/init/ready.d/"
      - "${DATA_STORAGE_PATH}/localstack:/var/lib/localstack"
```

I'm using .py script for initialization:

```
import os

TOPICS = ("user-profile", "group")


def create_topic(topic):
    os.system(f"echo {topic} creating")


def init_topics():
    for topic in TOPICS:
        create_topic(topic)


init_topics()
```

In docker console I've got next error:

`: name 'TOPICS' is not defined`

When I've changed script to the following:
```
import os

def create_topic(topic):
    os.system(f"echo {topic} creating")


def init_topics():
    for topic in ("user-profile", "group"):
        create_topic(topic)


init_topics()
```

I see next error:

`: name 'create_topic' is not defined`

Seems it's could works only as spagetti script. It's not comfortable for me.

### Expected Behavior

python script working as usual python script

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up

### Environment

```markdown
- OS:Windows 10
- LocalStack version: 1.2.1.dev```
