### ISSUE TITLE
bug: SES sending email not firing events to SNS topic

### ISSUE THREAD

**Issue by AlbertMontolio** [localstack/localstack#7184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to receive SES events in a SNS topic using localstack. A queue is connected to the SNS topic in order to get messages.
As an example, with SES we send an email, we use a config set that says, that whenever we send an email, the delivery event is fired to an SNS topic.
Queue listens to the SNS topic, we get this information polling from the queue.

### Expected Behavior

When sending email via SES in localstack, the delivery event gets fired to the SNS topic.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I started localstack with docker-compose:

```
version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns,ses
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - ./localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  default:
    name: development-network
    external: true

```

## verify email address
`aws --endpoint-url=http://localhost:4566 ses verify-email-identity --email-address sender@test.com --profile test-profile --region eu-central-1 --output table | cat`

## create queue for SNS - SES events
`aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name ses_events_queue2 --attributes '{"SqsManagedSseEnabled": "false"}' --profile test-profile --region eu-central-1 --output table | cat`

## update queue policy
```
aws --endpoint-url=http://localhost:4566 sqs set-queue-attributes --queue-url http://localhost:4566/000000000000/ses_events_queue --attributes '{"Policy" : "{\"Id\": \"Policy1564523767951\",\"Version\": \"2012-10-17\",\"Statement\": [{\"Sid\": \"Stmt1564523766749\",\"Action\": \"sqs:*\",\"Effect\": \"Allow\",\"Resource\": \"arn:aws:sqs:eu-central-1:078250808814:ses_events_queue2\",\"Condition\": {\"ArnEquals\": {\"aws:SourceArn\": \"arn:aws:sns:eu-central-1:078250808814:ses_events_topic\"}},\"Principal\": \"*\"}]}"}' --profile test-profile --region eu-central-1 --output table | cat

aws --endpoint-url=http://localhost:4566 sqs get-queue-attributes --queue-url http://localhost:4566/000000000000/ses_events_queue --attribute-names All --profile test-profile --region eu-central-1 --output table | cat
```

## create SNS topic for SES events
`aws --endpoint-url=http://localhost:4566 sns create-topic --name ses_events_topic --region eu-central-1 --profile test-profile --output table`

## subscribe queue to topic
`aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:eu-central-1:000000000000:ses_events_topic --protocol sqs --notification-endpoint arn:aws:sqs:eu-central-1:000000000000:ses_events_queue --profile test-profile --region eu-central-1 --output table | cat`

## create config set
`aws --endpoint-url=http://localhost:4566 ses create-configuration-set --configuration-set "{\"Name\":\"ses_config_set\"}" --profile test-profile --region eu-central-1 --output table | cat`

## create event destination
`aws --endpoint-url=http://localhost:4566 ses create-configuration-set-event-destination --configuration-set-name ses_config_set --event-destination '{"Name":"some_name2","Enabled":true,"MatchingEventTypes":["send","bounce","delivery","open","click"],"SNSDestination":{"TopicARN":"arn:aws:sns:eu-central-1:078250808814:ses_events_topic"}}' --profile test-profile --region eu-central-1 --output table | cat`

## send email via ses with created set
```
aws ses send-email --endpoint-url=http://localhost:4566 --destination '{"ToAddresses":["receiver@mail.com"]}' --message '{"Subject":{"Data":"foo subject"},"Body":{"Text":{"Data":"saml body"}}}' --configuration-set-name ses_config_set --from 'sender@test.com' --profile test-profile --region eu-central-1 --output table | cat
```

When I check messages in queue, it's empty.

I use same commands pointing to a sandbox in aws, and everything worked. In the aws GUI, I could create the sns, the queue, the config sets using same commands as in localstack, fire the event, and I could see the event being sent to the queue.

In localstack is not working and it's very difficult to check which part is not working.

### Environment

```markdown
- OS: macOS Monterey Version 12.6
- LocalStack: https://hub.docker.com/r/localstack/localstack
```
