### ISSUE TITLE
Cannot deploy lambda function of type image with samlocal

### ISSUE THREAD

**Issue by gkpty** [localstack/localstack#7196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a lambda function of type image that ive deployed to AWS, i want to be able to test this lambda function locally. Ive made several attempts to deploy this function to localstack using samlocal and docker-compose.

**attempt 1:** 
```
samlocal build \
--use-container \
--container-env-var GH_TOKEN=$GH_TOKEN \
--template-file ./general-stack/template.yml \
--build-image public.ecr.aws/sam/build-python3.9

sam deploy --guided

Stack Name [general-stack-test]: 
AWS Region [us-east-1]: 
Parameter Env [test]: 
Parameter DatabaseUrl [******]: 
Confirm changes before deploy [Y/n]: 
Allow SAM CLI IAM role creation [Y/n]: 
Disable rollback [y/N]: 
Save arguments to configuration file [Y/n]: 
SAM configuration file [samconfig.toml]: 
SAM configuration environment [default]: 
```
The build runs succesfully but deploy gives me the following error: `Error: Unable to upload artifact triggerfunction:python3.9-v1 referenced by ImageUri parameter of TriggerFunction resource.
denied: Your Authorization Token is invalid.`

**attempt 2:**
I signed up for a localstack pro trial to be able to use ECR in localstack

now before the build i run `aws --endpoint-url=http://aws-local:4566 ecr create-repository --repository-name generalstackfunction` note i am running localstack with docker-compose and the name of the service in the docker-compose file is `aws-local`.

then i run:
```
samlocal deploy \
--stack-name general-stack-$ENV \
--template-file ./general-stack/template.yml \
--resolve-s3 \
--config-env $CONFIG_ENV \
--capabilities CAPABILITY_NAMED_IAM \
--image-repository aws-local:4510/generalstackfunction
--parameter-overrides \
ParameterKey=Env,ParameterValue=$ENV \
ParameterKey=DatabaseUrl,ParameterValue=$DATABASE_URL
```
and i get the following error `Error: Invalid value for '--image-repository': Invalid Image Repository ECR URI: aws-local:4510/generalstackfunction`

it seems that there is a regex validation in sam for the repository uri and must conform to something like 000000000000.dkr.ecr.us-east-1.amazonaws.com/generalstackteste
txyz345/triggerfunction43xyz

### Expected Behavior

samlocal should overwrite the regex validation imposed by aws sam and allow users to deploy functions to an ECR repository in localstack.

Even better would be for samlocal to create the local repository for you and upload the image automatically when the `--resolve-image-repos` flag is supplied like the actual sam cli does.

Any other suggestions on how i could deploy this function locally would also work :)

### How are you starting LocalStack?

With a docker-compose file

## docker-compose.yml file
```
version: '3.8'
services:
  postgres-local:
    image: postgres:latest
    restart: "no"
    ports:
      - "42069:5432"
    expose:
      - "42069"
    volumes:
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  aws-local:
    image: localstack/localstack:latest
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    expose:
      - "4566"
    user: root
    environment:
      LOCALSTACK_API_KEY: $LOCALSTACK_API_KEY
      LAMBDA_EXECUTOR: docker
      LAMBDA_REMOVE_CONTAINERS: 0
      LAMBDA_REMOTE_DOCKER: "true"
      DEBUG: 1
      LAMBDA_DOCKER_NETWORK: testlayer_default

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_TOKEN
        - AWS_REGION
        - AWS_DEFAULT_REGION
        - DATABASE_URL
        - ENV
        - CONFIG_ENV
        - LOCALSTACK_HOSTNAME
        - EDGE_PORT
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - SAM_CLI_TELEMETRY
        - LOCALSTACK_API_KEY
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWS_ACCESS_KEY_ID: FAKEACCESSKEY
      AWS_SECRET_ACCESS_KEY: FAKESECRETKEY
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      DATABASE_URL: ********
      ENV: test
      LOCALSTACK_HOSTNAME: aws-local
      EDGE_PORT: 4566
      CONFIG_ENV: default
      GH_TOKEN: $GH_TOKEN
      SAM_CLI_TELEMETRY: 0
      LOCALSTACK_API_KEY: $LOCALSTACK_API_KEY
    depends_on:
      - "aws-local"
      - "postgres-local"
 ```

## Dockerfile
```
FROM python:3.9
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install awscli-local[ver1]
RUN pip3 install aws-sam-cli-local
COPY . .
ARG GH_TOKEN
ARG AWS_REGION
ARG AWS_DEFAULT_REGION
ARG OPENSEARCH_HOST
ARG DATABASE_URL
ARG ENV
ARG CONFIG_ENV
ARG LOCALSTACK_HOSTNAME
ARG EDGE_PORT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG SAM_CLI_TELEMETRY
ARG LOCALSTACK_API_KEY
CMD ./build_deploy.sh
```

## build_deploy.sh
```
aws --endpoint-url=http://aws-local:4566 ecr create-repository --repository-name generalstackfunction

samlocal build \
--use-container \
--container-env-var GH_TOKEN=$GH_TOKEN \
--template-file ./general-stack/template.yml \
--build-image public.ecr.aws/sam/build-python3.9

samlocal deploy \
--stack-name general-stack-$ENV \
--template-file ./general-stack/template.yml \
--resolve-s3 \
--config-env $CONFIG_ENV \
--capabilities CAPABILITY_NAMED_IAM \
--image-repository aws-local:4510/generalstackfunction
--parameter-overrides \
ParameterKey=Env,ParameterValue=$ENV \
ParameterKey=DatabaseUrl,ParameterValue=$DATABASE_URL
```

finally run `docker-compose up --build`

### Environment

```markdown
- OS:Ubuntu 22.04.1 LTS
- LocalStack:latest
```

**Comment by booysej** [comment]
I have tried the same now as "attempt 1" above, and got the same....
"Your Authorization Token is invalid" when running "samlocal deploy" on my container lambda/api gateway deployment.
Not sure if we are doing something wrong or if docker image lambdas are not yet supported on localstack, i also have the pro version.

**Comment by samuelhgf** [comment]
I'm having the same problem #7754

**Comment by wwells-apixio** [comment]
Same issue here

**Comment by derekvantonder3DD** [comment]
I just ran into this as well, it's a deciding factor in our company purchasing LocalStack unfortunately - we wish to be able to use CloudFormation+Lambda and we have spent 2 days trying to solve this.

**Comment by rondinellimorais** [comment]
Just contributing a little, in my project I have some lambdas that are of type Image. Here's what I did to get around this issue:

### Localstack version

```bash
# docker-compose.yml
image: localstack/localstack-pro:2.3.2
```

My list of services has `ecr`, `ecs` and `eks`

### template.yaml
```yaml
Resources:
  MyTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Sub "${AWS::StackName}-MyTest"
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerBuildArgs:
        FUNCTION_DIR: src/functions/my_test
        SOURCE_DIR: src
```

### samconfig.dev.toml

```
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
image_repositories = ["MyTestFunction=localhost.localstack.cloud:4510/dev-stackname/mytestfunction00000000repo"]
```

So I built a make function to create the repository every time I do a local deploy:

### MakeFile

```make
deploy-local-dockerimage:
	aws ecr create-repository \
		--repository-name=dev-stackname/mytestfunction00000000repo \
		--endpoint-url=http://localhost:4566 \
		--no-cli-pager > /dev/null 2>&1 || true;

         # other function
	# aws ecr create-repository \
        #     --repository-name=dev-stackname/otherfunction00000000repo .....

	samlocal deploy --config-file samconfig.dev.toml
```

Finally here is the command I use to deploy:

```bash
sam build && make deploy-local-dockerimage
```

### Result

```
....
CREATE_COMPLETE             AWS::ApiGateway::Stage      RestApiGatewayStage         -                         
CREATE_COMPLETE             AWS::CloudFormation::Stac   dev-stackname             -                         
                            k                                                                                 
-------------------------------------------------------------------------------------------------------------

CloudFormation outputs from deployed stack
---------------------------------------------------------------------------------------------------------------
Outputs                                                                                                       
---------------------------------------------------------------------------------------------------------------
Key                 ApiURL                                                                             
Description         API endpoint URL                                                                  
Value               http://2yd3fnnboe.execute-api.localhost.localstack.cloud:4566/dev                                       
---------------------------------------------------------------------------------------------------------------


Successfully created/updated stack - dev-stackname in us-east-1
```

**Comment by derekvantonder3DD** [comment]
You're a legend @rondinellimorais, I was able to get this working 👍 
One note I might add is to be careful of the JSON syntax required for adding multiple lambda functions, refer to the AWS docs to see how that is done in the .toml file.

**Comment by rondinellimorais** [comment]
I'm glad it helped you.

If you have multiple lambdas you can separate them with commas in the `toml`, something like this:

```
image_repositories = ["MyFn001=repo","MyFn002=repo","MyFn002=repo"]
```

**Comment by derekvantonder3DD** [comment]
Now I have a new problem related to this - while samlocal deploy works great on my local machine, it fails on Azure Pipelines running on an Ubuntu host. Here is the Azure Pipelines YAML build script:

`pool:
    vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

services:
  localstack:
    image: localstack/localstack-pro:2.3.2
    ports:
      - '4563-4599:4563-4599' # Exposing LocalStack ports
    env:
      SERVICES: 'lambda,apigateway,iam,ecr,ecs,eks,s3,lambda,sqs,apigateway,cloudformation'
      DEBUG: 1
      LS_LOG: 'debug'
      ACTIVATE_PRO: 1
      LOCALSTACK_AUTH_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxx'

- script: |
    python -m pip install --upgrade pip
    python -m pip install localstack awscli-local[ver1]
    python -m pip install aws-sam-cli
    python -m pip install aws-sam-cli-local
  displayName: 'Install LocalStack & AWS SAM CLI using pip'

- script: |
    echo "Checking LocalStack port 4566 is open..."
    curl localhost:4566
    if [ $? -ne 0 ]; then
      echo "LocalStack is not running on port 4566! Failed AP job."
      exit 1
    else
      echo "LocalStack is running on port 4566."
    fi
  displayName: 'Checking LocalStack port 4566 is open...'

# Use AWS CloudFormation to deploy the CF YAML template & all resources under it to LocalStack
- script: |
    awslocal configure set endpoint_url http://localhost:4566 --profile localstack
    awslocal configure set aws_access_key_id test --profile localstack
    awslocal configure set aws_secret_access_key test --profile localstack
    awslocal configure set region us-east-1 --profile localstack
    awslocal configure list --profile localstack
    awslocal s3 ls --profile localstack
    cd XXXXXXXXXX-SAM
    make deploy-local-dockerimage
  condition: endsWith(variables['Build.SourceBranch'], 'dev')
  displayName: 'SAM Deploy -> LocalStack (DEV)'`


The output from the Linux runner on Azure Pipelines:
`access_key     ****************test shared-credentials-file    
secret_key     ****************test shared-credentials-file    
    region                us-east-1              env    AWS_DEFAULT_REGION
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile               localstack           manual    --profile
access_key     ****************test shared-credentials-file    
secret_key     ****************test shared-credentials-file    
    region                us-east-1      config-file    ~/.aws/config

Building codeuri: /home/vsts/work/1/s/XXXXXXXXXX-SAM runtime: None metadata: {'DockerTag': 'dotnet6-v1', 'DockerContext': '/home/vsts/work/1/s/XXXXXXXXXX-SAM/src/XXXXXXXXXXLambdas', 'Dockerfile': 'API-Lambdas/FunctionHandler/Dockerfile', 'DockerBuildArgs': {'SAM_BUILD_MODE': 'local'}} architecture: x86_64 functions: XXXXXXXXXXLambdasFunction
Building image for XXXXXXXXXXLambdasFunction function
Setting DockerBuildArgs: {'SAM_BUILD_MODE': 'local'} for XXXXXXXXXXLambdasFunction function
Step 1/15 : FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-image
6.0: Pulling from dotnet/sdk 
b5a0d5c14ba9: Pulling fs layer 


Step 14/15 : COPY --from=build-image /build/build_artifacts/ /var/task/
 ---> d143aad6592d
Step 15/15 : CMD ["XXXXXXXXXXLambdas::XXXXXXXXXXLambdas.FunctionHandlerLambda::FunctionHandler"]
 ---> Running in 74f34d79904f
Removing intermediate container 74f34d79904f
 ---> 2a1664cf35f8
Successfully built 2a1664cf35f8
Successfully tagged XXXXXXXXXXlambdasfunction:dotnet6-v1


Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
	Creating the required resources...
	Successfully created!

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXX3ff
		A different default S3 bucket can be set in samconfig.toml
		Or by specifying --s3-bucket explicitly.
Error: Unable to upload artifact XXXXXXXXXXlambdasfunction:dotnet6-v1 referenced by ImageUri parameter of XXXXXXXXXXLambdasFunction resource.
list index out of range
make: *** [makefile:2: deploy-local-dockerimage] Error 1

##[error]Bash exited with code '2'.`

Can't figure out why this is happening? The makefile looks like this:

`deploy-local-dockerimage:
	awslocal configure set endpoint_url http://localhost:4566 --profile localstack; \
	awslocal configure set aws_access_key_id test --profile localstack; \
	awslocal configure set aws_secret_access_key test --profile localstack; \
	awslocal configure set region us-east-1 --profile localstack; \
	awslocal configure list --profile localstack; \
	aws configure set endpoint_url http://localhost:4566 --profile localstack; \
	aws configure set aws_access_key_id test --profile localstack; \
	aws configure set aws_secret_access_key test --profile localstack; \
	aws configure set region us-east-1 --profile localstack; \
	aws configure list --profile localstack; \
	export EnvironmentType=local; \
	export LOCALSTACK_AUTH_TOKEN="XXXXXXXXXXXXXXXXXXXXX"; \
	samlocal build --parameter-overrides EnvironmentType=local; \
	awslocal ecr create-repository \
		--repository-name=XXXXXXXXXXXXXXXXXXXXX-lambdas/mytestfunction00000000repo \
		--endpoint-url=http://localhost:4566 \
		--no-cli-pager > /dev/null 2>&1 || true; \
	samlocal deploy --config-file samconfig.dev.toml --parameter-overrides EnvironmentType=local`

Any help would be appreciated. Here is the CloudFormation file:

`AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambdas, Queue Events and other AWS methods for the XXXXXXXXXXXXXXX
  
Parameters:
  EnvironmentType:
    Type: String
    Description: Deployment environment type
    AllowedValues:
      - local
      - production

Conditions:
  IsLocalEnvironment: !Equals [ !Ref EnvironmentType, local ]
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  XXXXXXXXXXXXX:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: XXXXXXXXXXXXX
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
        
  XXXXXXXXXXXXXX: # NOTE: Needs to match $s3BucketName in PS1 script, must be lowercase, case sensitive too
    Type: AWS::S3::Bucket
    Properties:
      BucketName: XXXXXXXXXXXXXX  # NOTE: Needs to match $s3BucketName in PS1 script
      
  PendingXXXXXXXXXXXXXQSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "PendingXXXXXXXXXXXXXQ"
      VisibilityTimeout: 65 # should be greater that lambda timeout

  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  XXXXXXXXXXXXXXLambdasFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Sub "${AWS::StackName}-FunctionHandler"
      Events:
        XXXXXXXXXXXXXXLambdasEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref RestApiGateway
    Metadata:
      DockerTag: dotnet6-v1
      DockerContext: ./src/XXXXXXXXXXXXXXLambdas
      Dockerfile: API-Lambdas/FunctionHandler/Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: !Ref EnvironmentType
`

**Comment by derekvantonder3DD** [comment]
Now I have a new problem related to this - while samlocal deploy works great on my local machine, it fails on Azure Pipelines running on an Ubuntu host. Here is the Azure Pipelines YAML build script:

```pool:
    vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

services:
  localstack:
    image: localstack/localstack-pro:2.3.2
    ports:
      - '4563-4599:4563-4599' # Exposing LocalStack ports
    env:
      SERVICES: 'lambda,apigateway,iam,ecr,ecs,eks,s3,lambda,sqs,apigateway,cloudformation'
      DEBUG: 1
      LS_LOG: 'debug'
      ACTIVATE_PRO: 1
      LOCALSTACK_AUTH_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxx'

- script: |
    python -m pip install --upgrade pip
    python -m pip install localstack awscli-local[ver1]
    python -m pip install aws-sam-cli
    python -m pip install aws-sam-cli-local
  displayName: 'Install LocalStack & AWS SAM CLI using pip'

- script: |
    echo "Checking LocalStack port 4566 is open..."
    curl localhost:4566
    if [ $? -ne 0 ]; then
      echo "LocalStack is not running on port 4566! Failed AP job."
      exit 1
    else
      echo "LocalStack is running on port 4566."
    fi
  displayName: 'Checking LocalStack port 4566 is open...'

# Use AWS CloudFormation to deploy the CF YAML template & all resources under it to LocalStack
- script: |
    awslocal configure set endpoint_url http://localhost:4566 --profile localstack
    awslocal configure set aws_access_key_id test --profile localstack
    awslocal configure set aws_secret_access_key test --profile localstack
    awslocal configure set region us-east-1 --profile localstack
    awslocal configure list --profile localstack
    awslocal s3 ls --profile localstack
    cd XXXXXXXXXX-SAM
    make deploy-local-dockerimage
  condition: endsWith(variables['Build.SourceBranch'], 'dev')
  displayName: 'SAM Deploy -> LocalStack (DEV)'
```


The output from the Linux runner on Azure Pipelines:
```
access_key     ****************test shared-credentials-file    
secret_key     ****************test shared-credentials-file    
    region                us-east-1              env    AWS_DEFAULT_REGION
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile               localstack           manual    --profile
access_key     ****************test shared-credentials-file    
secret_key     ****************test shared-credentials-file    
    region                us-east-1      config-file    ~/.aws/config

Building codeuri: /home/vsts/work/1/s/XXXXXXXXXX-SAM runtime: None metadata: {'DockerTag': 'dotnet6-v1', 'DockerContext': '/home/vsts/work/1/s/XXXXXXXXXX-SAM/src/XXXXXXXXXXLambdas', 'Dockerfile': 'API-Lambdas/FunctionHandler/Dockerfile', 'DockerBuildArgs': {'SAM_BUILD_MODE': 'local'}} architecture: x86_64 functions: XXXXXXXXXXLambdasFunction
Building image for XXXXXXXXXXLambdasFunction function
Setting DockerBuildArgs: {'SAM_BUILD_MODE': 'local'} for XXXXXXXXXXLambdasFunction function
Step 1/15 : FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-image
6.0: Pulling from dotnet/sdk 
b5a0d5c14ba9: Pulling fs layer 


Step 14/15 : COPY --from=build-image /build/build_artifacts/ /var/task/
 ---> d143aad6592d
Step 15/15 : CMD ["XXXXXXXXXXLambdas::XXXXXXXXXXLambdas.FunctionHandlerLambda::FunctionHandler"]
 ---> Running in 74f34d79904f
Removing intermediate container 74f34d79904f
 ---> 2a1664cf35f8
Successfully built 2a1664cf35f8
Successfully tagged XXXXXXXXXXlambdasfunction:dotnet6-v1


Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
	Creating the required resources...
	Successfully created!

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXX3ff
		A different default S3 bucket can be set in samconfig.toml
		Or by specifying --s3-bucket explicitly.
Error: Unable to upload artifact XXXXXXXXXXlambdasfunction:dotnet6-v1 referenced by ImageUri parameter of XXXXXXXXXXLambdasFunction resource.
list index out of range
make: *** [makefile:2: deploy-local-dockerimage] Error 1

##[error]Bash exited with code '2'.
```

Can't figure out why this is happening? The makefile looks like this:

```
deploy-local-dockerimage:
	awslocal configure set endpoint_url http://localhost:4566 --profile localstack; \
	awslocal configure set aws_access_key_id test --profile localstack; \
	awslocal configure set aws_secret_access_key test --profile localstack; \
	awslocal configure set region us-east-1 --profile localstack; \
	awslocal configure list --profile localstack; \
	aws configure set endpoint_url http://localhost:4566 --profile localstack; \
	aws configure set aws_access_key_id test --profile localstack; \
	aws configure set aws_secret_access_key test --profile localstack; \
	aws configure set region us-east-1 --profile localstack; \
	aws configure list --profile localstack; \
	export EnvironmentType=local; \
	export LOCALSTACK_AUTH_TOKEN="XXXXXXXXXXXXXXXXXXXXX"; \
	samlocal build --parameter-overrides EnvironmentType=local; \
	awslocal ecr create-repository \
		--repository-name=XXXXXXXXXXXXXXXXXXXXX-lambdas/mytestfunction00000000repo \
		--endpoint-url=http://localhost:4566 \
		--no-cli-pager > /dev/null 2>&1 || true; \
	samlocal deploy --config-file samconfig.dev.toml --parameter-overrides EnvironmentType=local
```

Any help would be appreciated. Here is the CloudFormation file:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambdas, Queue Events and other AWS methods for the XXXXXXXXXXXXXXX
  
Parameters:
  EnvironmentType:
    Type: String
    Description: Deployment environment type
    AllowedValues:
      - local
      - production

Conditions:
  IsLocalEnvironment: !Equals [ !Ref EnvironmentType, local ]
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  XXXXXXXXXXXXX:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: XXXXXXXXXXXXX
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
        
  XXXXXXXXXXXXXX: # NOTE: Needs to match $s3BucketName in PS1 script, must be lowercase, case sensitive too
    Type: AWS::S3::Bucket
    Properties:
      BucketName: XXXXXXXXXXXXXX  # NOTE: Needs to match $s3BucketName in PS1 script
      
  PendingXXXXXXXXXXXXXQSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "PendingXXXXXXXXXXXXXQ"
      VisibilityTimeout: 65 # should be greater that lambda timeout

  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  XXXXXXXXXXXXXXLambdasFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: !Sub "${AWS::StackName}-FunctionHandler"
      Events:
        XXXXXXXXXXXXXXLambdasEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref RestApiGateway
    Metadata:
      DockerTag: dotnet6-v1
      DockerContext: ./src/XXXXXXXXXXXXXXLambdas
      Dockerfile: API-Lambdas/FunctionHandler/Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: !Ref EnvironmentType
```

**Comment by rondinellimorais** [comment]
Hello. This error already seems to be very specific to the issue thread, but I'm curious and would like to understand more.

Tell me why you want to start localstack inside a CI? The containers will be stopped at the end of the Job so I'm trying to understand what you intend to do, tell me more about

**Comment by rondinellimorais** [comment]
Hi, this error already seems to be very specific to the issue thread, but here are some tips after analyzing the errors in your logs:

Here is the doc that can help you run localstack in CI environments
https://docs.localstack.cloud/user-guide/ci/

ECR requires external port 4510 to receive images, so don't forget to map this port in the localstack service
https://docs.localstack.cloud/references/external-ports/

Here is a basic example of how you can do it in Azure Pipelines:

```yaml
services:
  localstack:
    image: localstack/localstack-pro:2.3.2
    ports:
      - '4566-4597:4566-4597'  # LocalStack Gateway
      - '4510-4559:4510-4559'  # external services port range
    env:
      SERVICES: 'lambda,apigateway,iam,ecr,ecs,eks,s3,lambda,sqs,apigateway,cloudformation'
      DEBUG: 1
      LS_LOG: 'debug'
      ACTIVATE_PRO: 1
      LOCALSTACK_AUTH_TOKEN: $(LOCALSTACK_AUTH_TOKEN)

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install aws-sam-cli==1.88.0
    python3 -m pip install aws-sam-cli-local==1.55.0
  displayName: 'Install AWS SAM CLI using pip'

- script: sam build
  displayName: 'SAM Build'

- script: |
    aws ecr create-repository \
      --repository-name=lambda-type-image/mytestfunction00000000repo \
      --endpoint-url=${localstack_endpoint} \
      --no-cli-pager > /dev/null 2>&1 || true;
    samlocal deploy --config-file samconfig.dev.toml
  displayName: 'SAM Deploy -> LocalStack (DEV)'
  env:
    AWS_ACCESS_KEY_ID: local
    AWS_SECRET_ACCESS_KEY: local
    AWS_DEFAULT_REGION: us-east-1
```

**Comment by derekvantonder3DD** [comment]
Thanks for that @rondinellimorais, we tried it and still get the same error sadly.

I have contacted LocalStack support to see if they can help. Ideally, they should provide a guide for CI with Azure Pipelines.

**Comment by rondinellimorais** [comment]
@derekvantonder3DD I hope the Localstack team can help you.

But if you can, try this second approach without using services:

Based on [CircleCI example](https://docs.localstack.cloud/user-guide/ci/circle-ci/)

There are just 3 steps:
- Install
- Start localstack
- Build
- Deploy

```yaml
pool:
  vmImage: ubuntu-latest

steps:
- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install localstack
    python3 -m pip install aws-sam-cli==1.88.0
    python3 -m pip install aws-sam-cli-local==1.55.0
  displayName: 'Install AWS SAM CLI using pip'

- script: |
    docker pull localstack/localstack-pro:2.3.2
    localstack start -d

    echo "Waiting for LocalStack startup..."
    localstack wait -t 30
    echo "Startup complete"
  displayName: Start LocalStack
  env:
    LOCALSTACK_API_KEY: $(LOCALSTACK_API_KEY)

- script: make build
  displayName: SAM Build

- script: make deploy-local-dockerimage
  displayName: SAM Deploy
  env:
    AWS_ACCESS_KEY_ID: local
    AWS_SECRET_ACCESS_KEY: local
    AWS_DEFAULT_REGION: us-east-1
```

Use `LOCALSTACK_API_KEY` instead of `LOCALSTACK_AUTH_TOKEN` in your CI environment, generate a key to use in your pipeline at [CI Keys](https://app.localstack.cloud/workspace/ci-keys)

In the example repository I created a new branch `localstack+azurepipelines` that you can clone and try to upload to your Azure Pipelines => https://github.com/rondinellimorais/localstack-lambda-type-image/tree/localstack%2Bazurepipelines.

Make these modifications and I believe it will work for you too, use the [example application](https://github.com/rondinellimorais/localstack-lambda-type-image/tree/localstack%2Bazurepipelines) to isolate the problem

<img width="282" alt="Captura de Tela 2024-01-03 às 21 44 57" src="https://github.com/localstack/localstack/assets/3987557/6bff2c59-7950-48c5-9d19-41aa2500bb9d">

![Captura de Tela 2024-01-03 às 21 43 53](https://github.com/localstack/localstack/assets/3987557/f9518a28-f85f-49c9-9ad3-18b31d3264f5)

<img width="951" alt="Captura de Tela 2024-01-03 às 21 50 19" src="https://github.com/localstack/localstack/assets/3987557/2b3a605f-48d7-4be7-80e3-0e3530f864ef">


<img width="935" alt="Captura de Tela 2024-01-03 às 21 46 24" src="https://github.com/localstack/localstack/assets/3987557/b4d24bfb-7ae9-4de0-b352-4c55bd9ca3d2">

<img width="852" alt="Captura de Tela 2024-01-03 às 21 45 53" src="https://github.com/localstack/localstack/assets/3987557/90670fc2-bdf2-492d-978d-665b7b86c31c">
