### ISSUE TITLE
bug: Localstack doesn't delete SQS messages when using ReportBatchItemFailures

### ISSUE THREAD

**Issue by mike-gore-cko** [localstack/localstack#7217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a Lambda function that is using the SQS trigger in conjunction with the ReportBatchItemFailures feature. The following settings apply:
- SQS visibility timeout = 60s
- Lambda timeout = 30s
- Redrive policy on the SQS input queue tries 10 times before sending to a dead letter queue

We have a test that sends a message that will be processed successfully and one where the message should be forwarded to a DLQ. We end up with the message being retried constantly and the message isn't inserted into the dead letter queue.

Here is the batch failure report which shows one of the messages failed, which is what we expect.
```
Lambda partial SQS batch failure report: ok=[], failed=['40a627dd-9204-499a-8563-cc8d7294ea09']
```

This appears to be due to the error below:
```
aws-local               | 2022-11-21T19:12:43.047  INFO --- [  Thread-331] l.s.a.e.sqs_event_source_l : Unable to delete Lambda events from SQS queue (please check SQS visibility timeout settings): [] - An error occurred (AWS.SimpleQueueService.EmptyBatchRequest) when calling the DeleteMessageBatch operation: Unknown
```
We can remove this error by setting the SQS visibility timeout to a low value e.g. 2s. However, this isn't what we want to do in AWS as that would lead to duplicate processing.

### Expected Behavior

The healthy message is processed and deleted from the queue, whereas the unhealthy message is sent to the dead letter queue.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
version: "3.9"

services:
  localstack:
    container_name: "aws-local"
    image: localstack/localstack:1.2.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_STAY_OPEN_MODE=0
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=1
      - HOSTNAME_EXTERNAL=localstack
      - LAMBDA_DOCKER_NETWORK=test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/localstack:/var/lib/localstack
      - ./src/:/var/lib/localstack/src
      - s3:/fakeS3
    networks:
      - test-network

  # This container builds the lambda function as a ZIP and then runs Terraform to deploy the infrastructure
  lambdabuild:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - s3:/fakeS3
    networks:
      - test-network

networks:
 test-network:
    name: test-network
    
volumes:
  s3:

```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
We are invoking using a .NET test

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- LocalStack: 1.2.0
```
