### ISSUE TITLE
bug: error while loading shared libraries: libpython3.10.so.1.0

### ISSUE THREAD

**Issue by nicolkill** [localstack/localstack#7227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using the latest version of localstack docker image in docker-compose, the container logs shows an error with shared library and waits to the infinite to the localstack service starts, example of the logs

```
/usr/local/bin/python: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
```

### Expected Behavior

starts the services and use the localstack service in my project

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
aws-localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      SERVICES: s3
```

### Environment

```markdown
- OS: ElementaryOS 6.1 Jolnir
- LocalStack: Latest (Image ID	sha256:3f522567b265f92b1efe97147619cc8d81c15068c5538b8d1d98aec4e2bcc213)
```
