### ISSUE TITLE
bug: S3 Service not accessible inside of docker container

### ISSUE THREAD

**Issue by ecarlson94** [localstack/localstack#7273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Breaking change when upgrading from Docker Container version `1.2.0` to version `1.3.0`. The S3 service is no longer accessible on port 4566 (which is the default port number in version `1.2.0`).

I am using AWS SDK in dotnet and receive the following error after upgrading to version `1.3.0` when running `awslocal s3 ls`:
```
Could not connect to the endpoint URL: "http://localhost:4566/"
```

I am 100% certain that it is not due to my docker-compose configuration because my services are all in the same container and this issue does not exist when I pin the localstack container version to `1.2.0`

### Expected Behavior

`aws s3 ls` should be able to connect to and list the buckets stored in LocalStack

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Steps:
1. Make sure docker is installed
2. With VSCode open in an empty folder, create the following files
    - `.devcontainer/devcontainer.json`
      ```json
      // For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
      // https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/dotnet
      {
         "name": "C# (.NET), MongoDB, & Firebase",
         "dockerComposeFile": "docker-compose.yml",
         "service": "app",
         "workspaceFolder": "/workspace",
         // Set *default* container specific settings.json values on container create.
         "settings": {},
         // Add the IDs of extensions you want installed when the container is created.
         "extensions": [],
         // Use 'forwardPorts' to make a list of ports inside the container available locally.
         "forwardPorts": [
            // MongoDB
            27017,
            // Localstack
            4566 // AWS S3
         ],
         // Comment out connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
         "remoteUser": "vscode",
         "features": {}
      }
         ```
      - `.devcontainer/Dockerfile`
      ```dockerfile
      # See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/dotnet/.devcontainer/base.Dockerfile

      # [Choice] .NET version: 6.0, 5.0, 3.1, 6.0-bullseye, 5.0-bullseye, 3.1-bullseye, 6.0-focal, 5.0-focal, 3.1-focal
      ARG VARIANT="7.0-bullseye-slim"
      FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-${VARIANT}

      # [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
      ARG NODE_VERSION="none"
      RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

      # [Optional] Uncomment this section to install additional OS packages.
      RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
         && apt-get -y install --no-install-recommends protobuf-compiler libnss3-tools awscli

      ENV PATH="$PATH:$HOME/.dotnet/tools"
      ENV PATH="$PATH:/home/vscode/.dotnet/tools"
      RUN dotnet tool install -g dotnet-reportgenerator-globaltool

      # Install MongoDB command line tools if on buster and x86_64 (arm64 not supported)
      ARG MongoDbToolsVersion=100.5.1
      RUN wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian92-x86_64-$MongoDbToolsVersion.deb && \
         apt install ./mongodb-database-tools-*.deb && \
         rm -f mongodb-database-tools-*.deb

      # [Optional] Uncomment this line to install global node packages.
      # RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
      ```
    - `.devcontainer/docker-compose.yaml`
      ```yml
      version: '3.8'

      services:
      app:
         build:
            context: .
            dockerfile: Dockerfile
            args:
            VARIANT: "7.0"
            NODE_VERSION: 16
         init: true
         volumes:
            - ..:/workspace:cached

         # Overrides default command so things don't shut down after the process ends.
         command: sleep infinity

         # Runs app on the same network as the firebase container, allows "forwardPorts" in devcontainer.json function.
         network_mode: service:db
         # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
         # (Adding the "ports" property to this file will not forward from a Codespace.)

      db:
         image: mongo:latest
         restart: unless-stopped
         volumes:
            - mongodb-data:/data/db
         # Uncomment to change startup options
         # environment:
         #  MONGO_INITDB_ROOT_USERNAME: root
         #  MONGO_INITDB_ROOT_PASSWORD: example
         #  MONGO_INITDB_DATABASE: your-database-here

         # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
         # (Adding the "ports" property to this file will not forward from a Codespace.)

      localstack:
         image: localstack/localstack:latest
         environment:
            - SERVICES=s3
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
         network_mode: service:db
         volumes:
            - ./.localstack:/tmp/localstack
            - /var/run/docker.sock:/var/run/docker.sock

      volumes:
      mongodb-data:
      ```
3. Open the command prompt (CMD/CTRL+Shift+P)
4. Type `reopen in container` and hit enter
5. Wait for the container to finish building
6. In a terminal (CMD/CTRL+~) run the following command
    - `pip install awscli-local`
8. Run the following command
    - `awslocal s3 ls`

### Environment

```markdown
IDE: VSCode
VSCode Extensions: Remote Containers
LocalStack: 1.3.0

## OS
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
