### ISSUE TITLE
bug: Lambda code is not deleted when the function is deleted in LAMBDA_EXECUTOR local mode

### ISSUE THREAD

**Issue by floverfelt** [localstack/localstack#7276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are running localstack in a Docker container and setting the LAMBDA_EXECUTOR property to local. When a function is created via the CLI a file is created in the container's tmp/localstack/ directory named something like (md5 hash)zipfile.

When that function is deleted, the corresponding local file is _not_ deleted. When you do multiple deletions and redeployments of the lambdas to the environment, the tmp/ drive fills up with a large number of unused zipfiles.

### Expected Behavior

The zipfile/source code file should be deleted when the lambda is deleted as that code is stale/no longer used.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`
docker-compose up
`
with environment variables:

- LAMBDA_EXECUTOR=${LOCALSTACK_LAMBDA_EXECUTOR:-local}

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

aws lambda create-function

### Environment

```markdown
- OS: Docker
- LocalStack: latest
```

**Comment by joe4dev** [comment]
Hi @floverfelt. Thanks for reporting.

## Reproduce

I can confirm that zip files for deleted lambda functions don't get cleaned up (in both the `local` and `docker` execution modes). However, the `tmp` directory gets wiped after shutting down LocalStack. Hence, this is mainly an issue for long-running instances.

## Workaround

The new lambda provider available as of [v1.3.0](https://github.com/localstack/localstack/releases/tag/v1.3.0) stores Lambda code in S3 by default and does proper cleanup upon deleting functions.
Remember to pull the latest image if you're using `docker pull localstack/localstack` (or specify `:1.3.0`)

The new lambda provider can be enabled by setting `PROVIDER_OVERRIDE_LAMBDA=asf` in the `docker-compose.yml`:

```yml
environment:
  # Enable new Lambda provider
  - PROVIDER_OVERRIDE_LAMBDA=asf
  # Currently required for creating functions with the new provider
  - LAMBDA_EXECUTOR=docker
volumes:
  # Make Docker socket available for LocalStack
  - "/var/run/docker.sock:/var/run/docker.sock"
```

## Follow-Up

Does switching to the new lambda provider fix your issue or is `local` mode required for some reason?
