### ISSUE TITLE
Is there any need to use wait-for-it.sh with LocalStack?

### ISSUE THREAD

**Issue by djangofan** [localstack/localstack#732]
Is there any need to use wait-for-it.sh with LocalStack?   I have a test container that is marked with depends_on  localstack but  do I need to use a wait-for-it.sh  script  ( see https://docs.docker.com/compose/startup-order/ ) to wait for things like s3 or SQS to actually be ready?     I'm having trouble with a test-service not seeing a SQS queue and I suspect its because the SQS queue is not yet ready when the tests try to create the queue?

Better yet, is it possible there already is a custom wait for it script already in the localstack container that I can call?

I was thinking of something like this, but one that would check all services, not just s3:

```
#!/bin/bash
# wait-for-s3s.sh
# usage in docker-compose:
#  command: ["./wait-for-s3.sh"]

set -e

args="$@"

until aws --region us-west-2 --no-sign-request --endpoint-url=http://localstack:4572 s3 mb s3://mytestbucket; do
  >&2 echo "S3 is unavailable - sleeping"
  sleep 1
done

>&2 echo "S3 is up - executing command"
exec aws --region us-west-2 --no-sign-request --endpoint-url=http://localstack:4572 s3 ls s3://mytestbucket;
```

**Comment by andrezimmermann** [comment]
Yes, as anything else on docker, `depends_on` wait for container creation, not what's really running on it. 
I don't think localstack should provide scripts to check if the services are ready. And there are many solutions already coded that provides this feature. 

https://github.com/vishnubob/wait-for-it
https://github.com/maxcnunes/waitforit

Localstack asserts that it's ready to be used by reading it's logs until a reads a `Ready.` string.
https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/LocalstackTestRunner.java#L264

**Comment by djangofan** [comment]
thanks for the explanation/info .  :-)

**Comment by IsaiahJTurner** [comment]
Took me a while to figure this out so will save someone the time:
This is my start script (I used https://github.com/maxcnunes/waitforit):
```
FROM node:10

WORKDIR /usr/src/app

COPY . .

RUN npm install

EXPOSE 8080

ENV WAITFORIT_VERSION="v2.4.1"
RUN curl -o /usr/local/bin/waitforit -sSL https://github.com/maxcnunes/waitforit/releases/download/$WAITFORIT_VERSION/waitforit-linux_amd64 && \
    chmod +x /usr/local/bin/waitforit

CMD [ "waitforit", "-address=http://localstack:4571", "-timeout=120", "--",  "npm", "start" ]
```

"4571" is the elasticsearch port.

**Comment by gerryfletch** [comment]
In case anyone comes across this issue and cannot resolve it with `wait-for-it.sh`, I intermittently still come across this issue despite the 200 OK response from `wait-for-it`. Appending a timeout to the `aws` cli command helped: https://github.com/aws/aws-cli/issues/3842#issuecomment-515800020

**Comment by manas86** [comment]
@djangofan do you mind sharing docker-compose including wait-script?

**Comment by djangofan** [comment]
I did get it working ages ago.  here is an example I did:
https://github.com/djangofan/karate-test-prime-example

**Comment by amitlevy21** [comment]
Now that everything is served with the edge service with the single `4566` port, those shell scripts will not detect when all the services of localstack are ready.

Whats the solution for this?

**Comment by rodnaph** [comment]
The `/health` endpoint returns JSON indicating service status, so it's possible, but not as simple as checking a single 200.

```Javascript
{
  "services": {
    "sns": "running",
    "sqs": "starting",
    "s3": "running"
  }
}
```

**Comment by gerryfletch** [comment]
Here is what I use to check the JSON output of the `/health GET`:
```bash
#!/bin/bash
echo "Waiting for S3 at address ${AWS_S3_ENDPOINT}/health, attempting every 5s"
until $(curl --silent --fail ${AWS_S3_ENDPOINT}/health | grep "\"s3\": \"running\"" > /dev/null); do
    printf '.'
    sleep 5
done
echo ' Success: Reached S3'
```

In my case, it looks for `"s3": "running"` in the HTTP response with `grep`.

**Comment by evictor** [comment]
If you have `curl` and [`jq`](https://stedolan.github.io/jq/) (or can install `jq`—it's lightweight and pretty nifty, I installed via `brew`), you can do the following to get a command that will `exit 0` if the status of all services is "running", or `exit 1` otherwise:

```bash
$ test "$(curl -s http://localhost:4566/health | jq '[.services[] == "running"] | all')" == "true"
```

**Comment by iselind** [comment]
You can do this without using `jq` as well:
```sh
wait-for-it -s --timeout=60 "awsmock:4566" &&
while curl -s http://awsmock:4566/health | grep -v "\"initScripts\": \"initialized\""; do
    printf 'awsmock not up\n'
    sleep 10s
done && yourThingHere
```

**Comment by Clebiez** [comment]
For some services like SQS, just wait localstack to be running is not effective.
Because you start localstack and after this, you have to create the queue :
```
awslocal sqs create-queue --queue-name QUEUE_NAME
```

And it could take a moment.

So I wrote a script to check that the queue has been created and are ready :
```sh
#!/bin/bash
QUEUE_URL="http://queue:4566/000000000000/QUEUE_NAME"
echo "Waiting for SQS at address $QUEUE_URL, attempting every 5s"
until $(curl --silent --fail $QUEUE_URL | grep "<QueueUrl>$QUEUE_URL</QueueUrl>" > /dev/null); do
    printf '.'
    sleep 5
done
echo ' Success: Reached SQS'
```

**Comment by adrian-huminiuc** [comment]
I ended up with a combination of all of the above, a more in-depth example, make a script in file:
`./ops/local/scripts/is-localstack-ready.sh`

With the contents:
```bash
#!/bin/bash
until curl -s http://localstack:4566/health | grep -v "\"initScripts\": \"initialized\""; do
    sleep 5s
done
echo 'Localstack finished executing initScripts'
```

And in docker-compose.yml

```yaml
command: bash -c "./ops/local/scripts/is-localstack-ready.sh && npm run start:debug"

**Comment by TheJefe** [comment]
For anyone else stumbling on this old thread, you can use docker-compose's healthchecks for this now

```yaml
version: '2.1'

services:
  my_service:
    image: my_image
    depends_on:
      localstack:
        condition: service_healthy
  localstack:
    image: localstack/localstack:0.11.6
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      DEFAULT_REGION: us-west-2
      SERVICES: 'sqs'
      HOSTNAME_EXTERNAL: localstack
    healthcheck:
      test: curl http://localhost:4566 || exit 1
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
```

**Comment by TheJefe** [comment]
Revisiting my immediately above comment, I have now switched to the following, because the previous did not check for the individual aws services health

```yaml
version: '2.1'

services:
  my_service:
    image: my_image
    depends_on:
      localstack:
        condition: service_healthy
  localstack:
    image: localstack/localstack:0.11.6
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      DEFAULT_REGION: us-west-2
      SERVICES: 's3, sqs'
      HOSTNAME_EXTERNAL: localstack
    healthcheck:
      test: "curl --silent --fail localstack:4566/health | grep '\"s3\": \"running\"' | grep '\"sqs\": \"running\"'"
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s
```
