### ISSUE TITLE
bug: CloudFormation fails to create Route53 hosted zone with comment

### ISSUE THREAD

**Issue by wesleyhall** [localstack/localstack#7341]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

On the pro version of LocalStack, creating a CloudFormation stack, containing a Route53 hosted zone with a comment, throws errors to the LocalStack output. 

The relevant part would seem to be: 

```
File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/route53/responses.py", line 47, in list_or_create_hostzone_response
if zone_request.get("VPC", {}).get("VPCId", None):
AttributeError: 'NoneType' object has no attribute 'get'
```

I can provide a fuller log, but the steps to reproduce provided below seem to reproduce the problem reliably, at least on my setup. 

### Expected Behavior

Successful running of the CloudFormation stack and creation of Route53 hosted zone. 

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    localstack start

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

The simplest test case I can find is the following: 

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PublicDNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "somedomain.com"
      HostedZoneConfig:
        Comment: "Test comment"
```

Assuming this is in test.yaml... 

`awslocal cloudformation create-stack --stack-name test --template-body file://$PWD/test.yaml`

...generates errors in the localstack output. 

The following works fine: 

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PublicDNS:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "somedomain.com"
```

Both templates run fine on AWS. 

### Environment

```markdown
- OS: MacOSX 
- LocalStack: 1.3.0
```
