### ISSUE TITLE
feature request: Option to have the DNS server return a different IP address for LocalStack

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#7355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I’m using LocalStack with Docker Compose and would like to use its DNS server for the other services.

Currently this isn’t possible as it returns `127.0.0.1` when referring to resources on LocalStack (such as `localstack` or `s3.amazonaws.com`).

The ability to specify the IP address returned would be useful, possibly just external requests if you want to keep using `127.0.0.1` when the requests come from code running locally.

### Anything else?

Currently I am working around this by creating a `localstack` Docker network, giving the attached containers static IPv4 addresses, and then running `dnsmasq` on a separate container configured to forward requests to LocalStack’s DNS server, but to rewrite `127.0.0.1` responses to its IP address on the network, eg:

```yaml
  dns:
    image: myorg/dns
    command:
      - dnsmasq
      - --keep-in-foreground
      - --listen-address=192.168.48.4
      - --log-facility=-
      - --log-async
      - --log-debug
      - --log-queries
      # Rewrite 127.0.0.1 responses to point to localstack’s network IP
      - --alias=127.0.0.1,192.168.48.2,255.255.255.255
    networks:
      _localstack:
        ipv4_address: "192.168.48.4"
    dns:
      # Use LocalStack for DNS
      - "192.168.48.2"
      # Use Cloudflare’s DNS as a backup (eg. during initial startup)
      - "1.1.1.1"
    expose:
      - "53"
    cap_drop: ["ALL"]
    cap_add: ["CHOWN", "SETGID", "SETUID"]
    security_opt: ["no-new-privileges:true"]
    depends_on:
      - localstack
```

My other services are then configured to use _this_ container for DNS.

This works for now so this feature is a low priority for us, but I thought I’d create the Issue so it can be tracked.
