### ISSUE TITLE
bug: DynamoDB stream events do not encode binary fields as base64

### ISSUE THREAD

**Issue by csweichel** [localstack/localstack#7402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When receiving DynamoDB stream events in a lambda, the unmarshalling of those events fails when the event contains a binary [AttributeValue](https://pkg.go.dev/github.com/aws/aws-lambda-go/events#DynamoDBAttributeValue) field.

### Expected Behavior

The DynamoDB stream record should contain base64 encoded binary data instead of just string encoded data.

**Currently sent and broken record**
```json
{
    "Records": [
        {
            "eventID": "9f63baa0",
            "eventVersion": "1.0",
            "awsRegion": "us-west-2",
            "eventName": "MODIFY",
            "eventSourceARN": "arn:aws:dynamodb:us-west-2:000000000000:table/SubstrateResource/stream/2022-12-29T12:52:23.747",
            "eventSource": "aws:dynamodb",
            "dynamodb": {
                "ApproximateCreationDateTime": 1672318508.0,
                "Keys": {
                    "pk": {
                        "S": "foo"
                    },
                    "sk": {
                        "S": "bar"
                    }
                },
                "NewImage": {
                    "sk": {
                        "S": "bar"
                    },
                    "pk": {
                        "S": "foo"
                    },
                    "binaryValue": {
                        "B": "foobar"
                    }
                },
                "SequenceNumber": "49636560432194406394272562308790574342707260849192435714",
                "SizeBytes": 4735,
                "StreamViewType": "NEW_IMAGE"
            }
        }
    ]
}
```

Should be (notice the binaryValue):
```json
{
    "Records": [
        {
            "eventID": "9f63baa0",
            "eventVersion": "1.0",
            "awsRegion": "us-west-2",
            "eventName": "MODIFY",
            "eventSourceARN": "arn:aws:dynamodb:us-west-2:000000000000:table/SubstrateResource/stream/2022-12-29T12:52:23.747",
            "eventSource": "aws:dynamodb",
            "dynamodb": {
                "ApproximateCreationDateTime": 1672318508.0,
                "Keys": {
                    "pk": {
                        "S": "foo"
                    },
                    "sk": {
                        "S": "bar"
                    }
                },
                "NewImage": {
                    "sk": {
                        "S": "bar"
                    },
                    "pk": {
                        "S": "foo"
                    },
                    "binaryValue": {
                        "B": "Zm9vYmFyCg=="
                    }
                },
                "SequenceNumber": "49636560432194406394272562308790574342707260849192435714",
                "SizeBytes": 4735,
                "StreamViewType": "NEW_IMAGE"
            }
        }
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Using docker-compose
```YAML
version: "3.4"

services:
  localstack:
    image: localstack/localstack
    expose:
      - "4566"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LAMBDA_REMOTE_DOCKER=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=${LS_LOG:-info}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. Create a lambda triggered by a DynamoDB stream
2. Push a record which carries a binary field
3. Try to unmarshal that record, e.g. using:

```Go
package main

import (
	"context"
	"encoding/json"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

func main() {
	lambda.Start(func(ctx context.Context, rawEvent json.RawMessage) error {
		var act events.DynamoDBEvent
		return json.Unmarshal(rawEvent, &act)
	})
}
```

### Environment

```markdown
All tested in a [Gitpod](https://gitpod.io/) workspace
- OS: 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- LocalStack: 
  LocalStack version: 1.3.2.dev
  LocalStack Docker container id: e772c9ec3007
  LocalStack build date: 2022-12-28
  LocalStack build git hash: f1c26a44
```
