### ISSUE TITLE
Dynamodb ResourceNotFoundException) when calling the DeleteTable operation

### ISSUE THREAD

**Issue by pen1064** [localstack/localstack#7406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using localstack/ v.1.3.1, I have successfully created a dyanmodb table, put an item in it, but when I want to delete the table it gives me that error. I have double checked that the item is actually in the table that I have created,

Here is the code that I used to create the table:
```
CONFIG = botocore.config.Config(retries={"max_attempts": 0})

def get_dynamodb_client():
    return boto3.client(
        "dynamodb",
        aws_access_key_id="",
        aws_secret_access_key="",
        region_name="us-east-1",
        endpoint_url="http://localhost:4566",
        config=CONFIG,
    )

def create_dynamodb_table():
    dynamodb_client = get_dynamodb_client()
    dynamodb_client.create_table(
        TableName='test-meowmeow-table',
        AttributeDefinitions=[
            {
                "AttributeName": "year",
                "AttributeType": "N"
            },
            {
                "AttributeName": "author",
                "AttributeType": "S"
            },
        ],
        KeySchema=[
            {
                "AttributeName":"author",
                "KeyType":"HASH",
            },
            {
                "AttributeName": "year",
                "KeyType": "RANGE"
            }
        ],
        ProvisionedThroughput={
            "ReadCapacityUnits": 1,
            "WriteCapacityUnits": 1,
        },
    )
```

So I used the following to put an item into the table:
```
dynamodb_client = get_dynamodb_client()
dynamodb_client.put_item(
            TableName="test-meowmeow-table",
            Item={
                "year": {"N": str(2022)},
                "author": {"S": "meow"},
                "item": {"S": "Meow Meow World"},
            }
        )
```    

I checked the table with  `dynamodb_client.scan(TableName='test-meowmeow-table`)
```
{'items in test-meowmeow-table': {'Count': 1, 'Items': [{'author': {'S': 'meow'}, 'item': {'S': 'Meow Meow World'}, 'year': {'N': '2022'}}], 'ResponseMe
tadata': {'HTTPHeaders': {'access-control-allow-headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-o
```

So everything looks right up to this point, however when I do `dynaodb_client.delete_table(TableName="test-meowmeow-table")`, it gives me error of `ResourceNotFoundException`
```
E           botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DeleteTable operation: Cannot do operations on a non-existent table

..\..\venv\lib\site-packages\botocore\client.py:938: ResourceNotFoundException
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Here is my docker file:
```
version: "3.8"

services:
  localstack:
    image: localstack/localstack:1.3.1
    container_name: localstack-meowtest
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda, s3, dynamodb
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```
I am using windows, so I navigated to the directory with this docker file, then run:
```
docker-compose up
```
It doesn't look like there is issue with the container itself.

### Environment

```markdown
- OS: Windows
- LocalStack: v1.3.1
```
