### ISSUE TITLE
bug: Localstack external hostname not being respected.

### ISSUE THREAD

**Issue by FM1337** [localstack/localstack#7436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting an external hostname (something like `https://localstack.sigkill.local`) and then creating an SQS queue, instead of setting the SQS queue name/url starting with `https://localstack.sigkill.local` it starts with `http://localstack.sigkill.local` which then when I try to interact with the queue using the `https` it says `The specified queue does not exist for this wsdl version.`.

I have verified the region, account id and everything else is correct, the only difference is the http/https which I suspect this is what is breaking it.

Given my setup (using Traefik to simulate a load balancer I would use in production) I cannot use `http` (it is set up to automatically redirect to `https`)

### Expected Behavior

I would expect that any created queues would start with `https://localstack.sigkill.local`

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   `docker-compose.yml`
 ```
localstack:
    image: localstack/localstack
    environment:
      EDGE_BIND_HOST: "0.0.0.0"
      ENABLE_CONFIG_UPDATES: 1
      HOSTNAME_EXTERNAL: "https://localstack.sigkill.local"
      PERSISTENCE: 1
      DYNAMODB_SHARE_DB: 1
```
           
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   ` aws --endpoint-url=https://localstack.sigkill.local --no-verify-ssl sqs create-queue --queue-name test`

  Also have used the PHP SDK.

Both have http returned instead of https.

### Environment

```markdown
- OS: Mac OS (latest version)
- LocalStack: latest
```

### Anything else?

Was going to try manually modifying stored data to see if I could force the queue name/URL, but since y'all charging money for a basic feature (persisting data, aka saving to disk so you don't lose it when you need to restart the stack), that's really not on the table anymore.

**Comment by bentsku** [comment]
Hi @FM1337 and thanks for your report,

It seems `HOSTNAME_EXTERNAL` is not used to create the queue URL in SQS if you don't also specify `SQS_PORT_EXTERNAL`. 

Also, you included the `scheme` in your `HOSTNAME_EXTERNAL`.
`HOSTNAME_EXTERNAL` should only contains the host name and not the scheme you'd like to use: `localstack.sigkill.local`
Otherwise, your queue URL would look like that: `http://https://localstack.sigkill.local/000000000000/test`

I've tried to reproduce your sample without Traefik, as I don't have your configuration. 

This is my test `docker-compose.yaml`: 

```yaml
version: "3.8"

services:
  localstack:
    image: localstack/localstack
    environment:
      EDGE_BIND_HOST: "0.0.0.0"
      ENABLE_CONFIG_UPDATES: 1
      HOSTNAME_EXTERNAL: "https://localstack.sigkill.local"
      PERSISTENCE: 1
      DYNAMODB_SHARE_DB: 1
    networks:
      test_network:
        aliases:
          - localstack.sigkill.local

  localstack-cli:
    image: localstack/localstack
    networks:
      test_network:

networks:
  test_network:
```

Credentials located in `~./aws/credentials`
```cfg
[default]
aws_access_key_id = test
aws_secret_access_key = test
```

The URL returned by the `CreateQueue` will return `http` or `https` depending on the incoming call to LocalStack. If the call is using SSL, the returned URL will use `https://`, but as you're using Traefik, I suppose you're doing SSL termination there, which means LocalStack will always return a `QueueUrl` starting with `http://`: but it does not matter in the end, as Traefik redirects it to `https://`.
You can even replace the scheme of the `QueueUrl` to use `https` and the request will still hit LocalStack. 
The `scheme` is not used directly to retrieve your queue.
I've run a couple of commands to try it:

```bash
# skipping the SSL warnings messages
$ aws --endpoint-url=https://localstack.sigkill.local:4566 --region us-east-1  --no-verify-ssl sqs create-queue --queue-name test-with-https
{
    "QueueUrl": "https://localstack.sigkill.local:4566/000000000000/test-with-https"
}
# my queue returns with https as I'm hitting directly with no SSL termination in between, but it does not matter. 
# we create another queue with no https for testing
$ aws --endpoint-url=http://localstack.sigkill.local:4566 --region us-east-1  sqs create-queue --queue-name test-no-https
{
    "QueueUrl": "http://localstack.sigkill.local:4566/000000000000/test-no-https"
}
# we list the queues from an https call
$ aws --endpoint-url=https://localstack.sigkill.local:4566 --region us-east-1  --no-verify-ssl sqs list-queues
{
    "QueueUrls": [
        "https://localstack.sigkill.local:4566/000000000000/test-with-https",
        "https://localstack.sigkill.local:4566/000000000000/test-no-https"
    ]
}
# without http
$ aws --endpoint-url=http://localstack.sigkill.local:4566 --region us-east-1 sqs list-queues
{
    "QueueUrls": [
        "http://localstack.sigkill.local:4566/000000000000/test-with-https",
        "http://localstack.sigkill.local:4566/000000000000/test-no-https"
    ]
}
# deleting the queue created without https with an http URL with an https connection
$ aws --endpoint-url=https://localstack.sigkill.local:4566 --region us-east-1  --no-verify-ssl sqs delete-queue --queue-url http://localstack.sigkill.local:4566/000000000000/test-no-https
# deleting the queue created with https with an https URL with a regular http connection
$ aws --endpoint-url=http://localstack.sigkill.local:4566 --region us-east-1 sqs delete-queue --queue-url https://localstack.sigkill.local:4566/000000000000/test-with-https
# listing the queues to see if they've been deleted, but no error message received
$ aws --endpoint-url=https://localstack.sigkill.local:4566 --region us-east-1  --no-verify-ssl sqs list-queues
# no responses, queues have been deleted
```

So in the end, we can see the scheme in the `QueueUrl` is not important, the issue must stem from somewhere else.
Maybe you can give us more informations about your setup, and LocalStack logs for when it returns an error? That could help troubleshoot your issue.
Thanks!
