### ISSUE TITLE
bug: Cannot create SQS Queue from another docker container

### ISSUE THREAD

**Issue by rusakov92** [localstack/localstack#7521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, when I try to create a new queue from another container I receive a success message but listing the queues it does not show up.

Here is my docker-compose.yaml file from the container I have issues:
```
version: '3.7'
services:
  web:
    container_name: my-container
    depends_on:
    image: "my_image:latest"
    entrypoint: ["/opt/docker-entrypoint.sh", "auto"]
    ports:
        - "22122:22"
    networks:
        my_network:
            aliases:
                - my-alias
    extra_hosts:
        -  queue.localhost.localstack.cloud:192.168.65.2
        - s3.localhost.localstack.cloud:192.168.65.2
```
The docker-compose.yaml file that pulls latest version of localstack:
```
version: '3.8'
services:
    localstack-main:
        container_name: localstack-main
        image: "localstack/localstack"
        ports:
            - "127.0.0.1:4566:4566"            # LocalStack Gateway
        networks:
            - my_network
networks:
    my_network:
        name  : my_network
        driver: bridge
```

Here is how I try to create the queue on my-container, which returns a success message:
```
[root@26aa79353a15 /]# aws sqs create-queue --queue-name my-queue3 --endpoint http://queue.localhost.localstack.cloud:4566 --region eu-west-1
{
    "QueueUrl": "http://queue.localhost.localstack.cloud:4566/000000000000/my-queue3"
}
```

Going into localstack-main container and checking if the queue exists I don't see anything, I'm running this:
```
awslocal sqs list-queue
```

Running the same command on the localstack container works fine, running it from the host computer works fine, it does not work when I try to run it from another container in the same network.

Pushing messages and consuming them works fine when done from other containers.

I tried adding a new bucket using S3 API, it works fine by running:
```
aws s3api create-bucket --bucket sample-bucket --endpoint http://s3.localhost.localstack.cloud:4566 --region eu-west-1 --create-bucket-configuration LocationConstraint=eu-west-1
{
    "Location": "http://sample-bucket.s3.localhost.localstack.cloud:4566/"
}
```

Checking the result in localstack I see the bucket.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Prepare 2 containers that will run in the same container and add extra hosts for SQS endpoint `queue.localhost.localstack.cloud:192.168.65.2`, the IP may be different based on the internal network settings of your docker machine.

Start the 2 containers.

From the custom container that is using localstack run:
`aws sqs create-queue --queue-name my-queue --endpoint http://queue.localhost.localstack.cloud:4566 --region eu-west-1`

Expect in the localstack container to see the queue, run:
`awslocal sqs list-queues`

### Environment

```markdown
- OS: Docker container using CentOS 7, docker running on MacOS 13.0
- LocalStack: latest
```
