### ISSUE TITLE
SQS created queues do not persist

### ISSUE THREAD

**Issue by lonewarrior556** [localstack/localstack#754]
I'm trying to initialize my env once for further use.
Heres my `docker-compose.yml`
```
  localstack-aws:
    image: localstack/localstack
    container_name: localstack-aws
    ports:
      - $S3_PORT:4572
      - $SQS_PORT:4576
    volumes:
      - localstackdata:/tmp/localstack
    environment:
      DATA_DIR: /tmp/localstack/data
      HOSTNAME_EXTERNAL: localstack-aws
      SERVICES: s3,sqs

volumes:
  localstackdata:
```
I have an init script that runs the following 3 commands
```
pip install awscli-local
awslocal s3api create-bucket --bucket bucket-name
awslocal sqs create-queue --queue-name localSQS.fifo

```

I restart the container; docker exec -it localstack-aws bash...
```
> bash-4.3# awslocal s3 ls
2006-02-03 16:45:09 bucket-name
> bash-4.3# awslocal sqs list-queues
> bash-4.3#
```

Is there anyway to get created sqs queues to persist?
