### ISSUE TITLE
bug: SNS FIFO: The request includes MessageGroupId parameter that is not valid for this topic type

### ISSUE THREAD

**Issue by robsonpiere** [localstack/localstack#7562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Publishing to fifo topics is generating the error message: `The request includes MessageGroupId parameter that is not valid for this topic type` with 400 status code

The behavior occurs on amazon python and java sdk clients. (Works ok in aws cli)

### Expected Behavior

The message should be published successfully.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up using this example: 

```yaml
services:
  localstack:
    image: 'localstack/localstack:latest'
    environment:
      LOCALSTACK_SERVICES: 'sns,sqs'
      DEBUG: 1
    ports:
      - '4566:4566'
   
  aws-environment:
    image: 'amazon/aws-cli:latest'
    environment:
      AWS_ACCESS_KEY_ID: DEV123
      AWS_SECRET_ACCESS_KEY: DEV123
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: /bin/sh -c
    command: |
      "
        sleep 15
        aws sns create-topic --endpoint-url=http://localstack:4566 --name my-topic.fifo --attributes FifoTopic=true,ContentBasedDeduplication=true;
      "
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

Trying to publish a message using a python or java client:

```python
import json
import boto3


client = boto3.client('sns',
                      endpoint_url="http://localhost:4566",
                      region_name='us-east-1',
                      aws_access_key_id='DEV123',
                      aws_secret_access_key='DEV123')


message = {"foo": "bar"}
response = client.publish(
    TargetArn=
    'arn:aws:sns:us-east-1:000000000000:my-topic.fifo',
    Message=json.dumps({'default': json.dumps(message)}),
    MessageStructure='json',
    MessageGroupId="123"
)
print(response)
```

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack: latest
- Boto version: 1.24.96
- Python version: 3.8.16
- aws-java-sdk-sns: 1.12.392
```

### Anything else?

I checked these issues related to sqs:

- https://github.com/localstack/localstack/issues/5465
- https://github.com/localstack/localstack/issues/5374
- https://github.com/localstack/localstack/issues/5236

Testing in real aws environments or using [moto server](http://docs.getmoto.org/en/latest/docs/server_mode.html) the scripts worked normally
