### ISSUE TITLE
Implement EFS CreateAccessPoint and CreateMountTarget

### ISSUE THREAD

**Issue by mbollemeijer** [localstack/localstack#7684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

I am trying to mimic our already existing setup in localstack.
I need to pull a file from an S3 bucket and put it in a EFS Folder via an Lambda.

Unfortunately these calls are listed as missing on the coverage page and I cannot find anything in the repository that indicates that it is implemented.

Is there a workaround?

**Comment by dominikschubert** [comment]
Hey @mbollemeijer !

This is unfortunately not on our roadmap since this would add an enormous amount of complexity.

What I could imagine as a workaround would be manually mounting a local directory into your lambda container and just writing to that instead :thinking:  You can use `LAMBDA_DOCKER_FLAGS` to tell localstack to mount volumes in your lambda for this purpose.


But just to verify, do you need the actual behavior or would just adding the "CRUD" methods that you mentioned be enough for your use case?

**Comment by peldax** [comment]
Hi,
I have a similar request. We have an existing infrastructure on AWS using serveless framework. Our entire AWS infrastructure is declared using `resources` section in `serverless.yml`. We are currently trying to reduce our costs by moving our development environment on AWS to localhost by mimicking the infrastructure locally. 

Right now we are experimenting with localstack and everything works so far. There is only one drawback. We need to remove EFS related lines from `serverless.yml` in order for local deployment to succeed.
This includes following:

- `fileSystemConfig` in each of the lambda function declaration
```yml
fucntions:
    httpHandler:
        handler: httpHandler.js
        fileSystemConfig:
            localMountPath: /mnt/cache
            arn: !GetAtt AccessPoint.Arn
```
- EFS related resources - `AWS::EFS::FileSystem`, `AWS::EFS::AccessPoint` and `AWS::EFS::MountTarget`
```yml
resources:
    ElasticFileSystem:
        Type: AWS::EFS::FileSystem
        Properties:
            ...
    AccessPoint:
        Type: AWS::EFS::AccessPoint
        Properties:
            ...
        DependsOn:
            - MountTarget
    MountTarget:
        Type: AWS::EFS::MountTarget
        Properties:
            ...
```

As you can imagine, this is very annoying thing to do.

Isn't it possible for localstack to automatically create local `/tmp/` mount points from such EFS configuration? We don't need localstack to mimic EFS behavior completely to the tiniest details. We just need some place where lambda can write to. This can be done manually by docker mounting, as @dominikschubert describes, but I imagine this could be done automatically and without modification of local infrastructure files.

Thank you.

VP
