### ISSUE TITLE
bug: localstack response says dynamodb global secondary index is created, but it isn't

### ISSUE THREAD

**Issue by nickphbrown** [localstack/localstack#7707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using terraform to create a dynamodb table with a global secondary index. On creation, the response from localstack contains information on the Global Secondary Index. However, I can see that the GSI doesn't exist when running a describe-table operation against the table.

NB: I can create the GSI fine by making a python boto3 create_table call, so I'd say the issue is that localstack is responding to a (potentially incorrect) create table call as if it has worked as intended.

Terraform version: 0.12.31
Terraform AWS provider version 3.75.2
LocalStack version: 1.4.1.dev

terraform debug logs say gets this response on creating the table, which includes "GlobalSecondaryIndexes" and the Attribute that is to be the hash of the GSI

```2023-02-17T09:41:21.189Z [INFO]  plugin.terraform-provider-aws_v3.75.2_x5: 2023/02/17 09:41:21 [DEBUG] [aws-sdk-go] DEBUG: Response dynamodb/CreateTable Details:
---[ RESPONSE ]--------------------------------------
...
{"TableDescription": {"AttributeDefinitions": [{"AttributeName": "hash", "AttributeType": "S"}, {"AttributeName": "gsi_hash", "AttributeType": "S"}], "TableName": "example-name", ..., "GlobalSecondaryIndexes": [{"IndexName": "gsi_hash-index, "KeySchema": [{"AttributeName": "gsi_hash", "KeyType": "HASH"}], "Projection": {"ProjectionType": "KEYS_ONLY"}}], "TableId": "c70fe2c8-2138-4d0c-ad1f-a4cfd5bb90a7"}}
```

However, when I then use the awscli to describe that table in localstack, there is no global secondary index or the attribute associated with the gsi

```
aws dynamodb describe-table --table-name example-name --endpoint http://localhost:443
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "hash",
                "AttributeType": "S"
            }
        ],
        "TableName": "example-name",
        "KeySchema": [
            {
                "AttributeName": "hash",
                "KeyType": "HASH"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2023-02-17T10:55:48.863000+00:00",
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": "1970-01-01T00:00:00+00:00",
            "LastDecreaseDateTime": "1970-01-01T00:00:00+00:00",
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 0,
            "WriteCapacityUnits": 0
        },
        "TableSizeBytes": 227,
        "ItemCount": 1,
        "TableArn": "arn:aws:dynamodb:eu-west-1:000000000000:table/example-name",
        "TableId": "c70fe2c8-2138-4d0c-ad1f-a4cfd5bb90a7",
        "BillingModeSummary": {
            "BillingMode": "PAY_PER_REQUEST",
            "LastUpdateToPayPerRequestDateTime": "2023-02-17T10:55:48.863000+00:00"
        },
        "Replicas": []
    }
}
```

I am using localstack latest version:
```
CONTAINER ID   IMAGE                                   COMMAND                  CREATED          STATUS                    PORTS                                                     NAMES
caec1e9415b5   localstack/localstack:latest            "docker-entrypoint.sh"   20 minutes ago   Up 20 minutes (healthy)   4510-4559/tcp, 4566/tcp, 0.0.0.0:443->443/tcp, 5678/tcp   localstack
```

### Expected Behavior

global secondary index should either be created or I should get an error response back from localstack to say that the request is bad

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
docker-compose.yml
```
version: '3.5'
networks:
  network:
    name: network

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=lambda,stepfunctions,dynamodb,sns,events,iam,ec2,s3,cloudwatchlogs,sqs,ssm,kms,sts
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=network
      - EDGE_PORT=443
    ports:
      - '443:443'
    volumes:
      - /var/lib/localstack:/var/lib/localstack:delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
    networks:
      - network
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

terraform version: 0.12.31
terraform aws provider version: 3.75.2

dynamo_table.tf
```
resource "aws_dynamodb_table" "token_table" {
  name         = "example-name"
  hash_key     = "hash"
  billing_mode = "PAY_PER_REQUEST"

  attribute {
    name = "hash"
    type = "S"
  }

  attribute {
    name = "gsi_hash"
    type = "S"
  }

  ttl {
    attribute_name = "expiration_time"
    enabled        = true
  }

  global_secondary_index {
    name            = "gsi_hash-index"
    hash_key        = "gsi_hash"
    projection_type = "ALL"
  }
}
```

### Environment

```markdown
- OS: macOS Monterey v12.6.3
- LocalStack: latest
```
