### ISSUE TITLE
bug: Localstack version 1.4 Inaccessible host: '127.0.0.1' at port '4566'.

### ISSUE THREAD

**Issue by lkoida-boohoo** [localstack/localstack#7720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running localstack as docker-compose service permanently have this error when try to call `sqs` form nodejs application.
`UnknownEndpoint: Inaccessible host: '127.0.0.1' at port '4566'. This service may not be available in the eu-west-1' region.`

 Tried to change `127.0.0.1`  to `localhost` but without any success.
Tried to use latest aws-sdk, and the same - message - conection refused.

running request using curl do the job perfectly.

This is my docker-compose settings for nodejs and localstack:
```yaml
version: "3.5"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.local
    depends_on:
      - localstack
    ports:
      - "5000:5000"
    networks:
      - my_network
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_SDK_LOAD_CONFIG=1
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.4
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./scripts/localstack:/etc/localstack/init/ready.d/
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

```

### Expected Behavior

Expect to have successful comunication between localstack and node

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    `docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   in init scripts I have a couple of queues created on localstack start.
   And later I have to call them through nodejs api to send/receive messages

### Environment

```markdown
- OS:WSL Ubuntu 20.04
- LocalStack:1.4
```
