### ISSUE TITLE
bug: CAPABILITY_AUTO_EXPAND stopped working

### ISSUE THREAD

**Issue by ianwremmel** [localstack/localstack#7733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`sam deploy` throws the following

```
Error: Failed to create managed resources: An error occurred (InsufficientCapabilitiesException) when calling the CreateChangeSet operation: Requires capabilities : [CAPABILITY_AUTO_EXPAND]
```

### Expected Behavior

`sam deploy` succeeds

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```bash
init_localstack () {
  log "Starting LocalStack"
  docker-compose up -d

  log "Waiting for LocalStack startup..."
  npx wait-on http://127.0.0.1:4566
  log "Startup complete"
}
```

```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:1.4
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PROVIDER_OVERRIDE_LAMBDA=asf
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
samlocal deploy \
    --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
    --no-fail-on-empty-changeset \
    --resolve-s3 \
    --stack-name "$stackname" \
    --region "${AWS_REGION:-us-east-1}"
```

### Environment

```markdown
- OS: macOS 13.2
- LocalStack: 
    Working: `:1.4`
    Broken: `:latest`
```

### Anything else?

This broke somewhere between `localstack/localstack:1.4` and `localstack/localstack:latest`. I _think_ `:latest` was fine about three or four weeks ago, but can't narrow it down any further (without a lot of trial an error).
