### ISSUE TITLE
ready.d hook not working on k8s

### ISSUE THREAD

**Issue by astingengo** [localstack/localstack#7751]
# Current Behavior
init.sh is not executed
# Expected Behavior
init.sh to be executed

# Steps To Reproduce
Deployment file

```
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: localstack
    namespace: localstack
    labels:
      app: localstack
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: localstack
    template:
      metadata:
        labels:
          app: localstack
      spec:
        containers:
        - name: localstack
          image: localstack/localstack:1.3
          env:
            - name: LS_LOG
              value: DEBUG
          ports:
            - containerPort: 4566
              name: localstack
              protocol: TCP
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
            requests:
              memory: 300Mi
              cpu: "0.5"
          volumeMounts:
          - name: localstack-volume
            mountPath: /etc/localstack/init/ready.d/init.sh
            subPath: init.sh
        volumes:
        - name: localstack-volume
          configMap:
            name: localstack
            defaultMode: 0755
```

# Environment
- OS:22.04
- kube: v1.25.6+k3s1
- LocalStack: 1.3
