### ISSUE TITLE
bug: retagging an image on ecr with put-image doesn't work

### ISSUE THREAD

**Issue by TheoNoyau** [localstack/localstack#7795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
I want to add a new tag to a just pushed image on ECR.
To do so, I run the following commands:
```
REPOSITORY_NAME=test-repository
APP_NAME=test-app
LOCAL_REPOSITORY_URI=localhost:4510/test-repository

awslocal ecr create-repository --repository-name $REPOSITORY_NAME --image-tag-mutability MUTABLE --region eu-west-1
docker build -t $LOCAL_REPOSITORY_URI:test-tag .
docker push $LOCAL_REPOSITORY_URI:test-tag
```

which gives me:
```
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:eu-west-1:000000000000:repository/test-repository",
        "registryId": "000000000000",
        "repositoryName": "test-repository",
        "repositoryUri": "localhost.localstack.cloud:4510/test-repository",
        "createdAt": "2023-03-03T14:03:59+01:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": false
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}
```

Now I want to add a tag to the just pushed image.
```
MANIFEST=$(awslocal ecr batch-get-image --region eu-west-1 --repository-name test-repository --image-ids imageTag=test-tag --query 'images[].imageManifest' --output text)
awslocal ecr put-image --repository-name test-repository --image-tag new-tag --image-manifest "$MANIFEST" --region eu-west-1
```
Which returns:
```
{
    "image": {
        "registryId": "000000000000",
        "repositoryName": "test-repository",
        "imageId": {
            "imageDigest": "sha256:22d2d526aa28aff2609fa897680bf788064a0db592ae902410a7c2aad9d1e71a",
            "imageTag": "new-tag"
        },
        "imageManifest": "{\"schemaVersion\": 2, \"mediaType\": \"application/vnd.docker.distribution.manifest.v2+json\", \"config\": {\"mediaType\": \"application/vnd.docker.container.image.v1+json\", \"size\": 761, \"digest\": \"sha256:ab2d9458c326481a06031dac8378e87c7a8b2a58d1c0b948197fb105e7095f8c\"}, \"layers\": [{\"mediaType\": \"application/vnd.docker.image.rootfs.diff.tar.gzip\", \"size\": 3374446, \"digest\": \"sha256:63b65145d645c1250c391b2d16ebe53b3747c295ca8ba2fcb6b0cf064a4dc21c\"}]}"
    }
}
```
Now I want to check if tag got added by running:
```
awslocal ecr list-images --repository-name test-repository --region eu-west-1
```

I only get image with test-tag:

```
{
    "imageIds": [
        {
            "imageDigest": "sha256:fae3541c6b50868fc9f03d8474c8db61408dc0124aa144723e4d495ed84f8200",
            "imageTag": "test-tag"
        }
    ]
}
```
It might be linked to the fact that imageDigest from `test-tag` and the one from `new-tag` don't match although it's the exact same image.

### Expected Behavior

From what I understand, there should be a mention to new-tag when I run list-images.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
docker-compose.yml:
```
version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - LOCALSTACK_API_KEY=<API_KEY>
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - SERVICES=ecr
      - HOST_TMP_FOLDER="${TMPDIR:-/tmp}/localstack"
      - DEFAULT_REGION=eu-west-1
      - PORT_WEB_UI=8080
    ports:
      - '4510-4599:4510-4599'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

```
Dockerfile used to test:
```
FROM alpine
CMD ["echo", "test"]
```
### Environment

```markdown
- OS:Macos 13.1
- LocalStack:latest
```
