### ISSUE TITLE
Connection error on startup

### ISSUE THREAD

**Issue by tobilg** [localstack/localstack#781]
I'm seeing the following error when using docker-compose 

```yaml
version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4563-4583:4563-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=kinesis,sqs,s3,firehose,lambda,sns,cloudformation
      - LAMBDA_EXECUTOR=local
      - DEFAULT_REGION=eu-central-1
```

Error:

```text
localstack_1  | 2018-05-23T11:39:26:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb59d8ab10>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 72, in get
localstack_1  |     return request('get', url, params=params, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4563): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb59d8ab10>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  |
```
