### ISSUE TITLE
bug: S3TransferManager download operation is not working with localstakc

### ISSUE THREAD

**Issue by kunalvarpe** [localstack/localstack#7830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created the localstack config with s3 service. Under the volumes provided docker file created bucket with name `io-web-local` and uploaded file `test.txt` file in the bucket. I am trying to test the S3TransferManager download operation where downloading the content as byte array.  But this is not working with the localstack.

### Expected Behavior

The download as bytes array should work with localstack .

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```yaml
localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
        - "4566-4599:4566-4599"
        - "${PORT_WEB_UI-8055}:${PORT_WEB_UI-8055}"
    environment:
        - SERVICES=s3
        - AWS_DEFAULT_REGION=us-east-1
    volumes:
        - ./docker/files/test.txt:/home/test.txt
        - ./docker/files/init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows
- LocalStack: latest
- AWS SDK : 2.19.1
- AWS CRT : 0.20.3
```

### Anything else?

I have created the minimal reproducible example on my repo [here](https://github.com/kunalvarpe/aws-demo)
