### ISSUE TITLE
bug: ses:SendRawEmail stopped working in 1.4

### ISSUE THREAD

**Issue by dolohow** [localstack/localstack#7896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a code that sens raw messages.  It throws
```
MessageRejected: An error occurred (MessageRejected) when calling the SendRawEmail operation: Did not have authority to send from email system-dev@oskar.com.pl
```

while it should not

and in logs I have 
```
backend-aws-1       | 2023-03-17T13:25:10.423  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS ses.SendRawEmail => 400 (MessageRejected)
```

### Expected Behavior

No errors, sending email should just work

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
  aws:
    image: localstack/localstack:1.4
    volumes:
      - ./docker/aws:/etc/localstack/init/ready.d
    labels:
      - traefik.http.routers.aws.rule=Host(`aws.localhost`)
      - traefik.http.services.aws.loadbalancer.server.port=4566
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

   I am using this package to sent email https://pypi.org/project/django-ses/

### Environment

```markdown
- OS: Ubuntu 22.04
- LocalStack: 1.4
```

### Anything else?

When downgrading to `1.3` it starts to work again.

Also I have
```
awslocal ses verify-email-identity --email-address ...
```
