### ISSUE TITLE
feature request: AWS::ElastiCache::CacheCluster Port support in Cloudformation and CLI

### ISSUE THREAD

**Issue by hrishi-hugo** [localstack/localstack#7930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature description

If I deploy the following stack the `Port` property is not considered and Localstack still assigns ports sequentially instead of teh given port 
I want to give a static port for it
 ```
ElasticCacheCluster:
    DependsOn: [ ElasticCacheSubnetGroup ]
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      Port: 4541
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: 'cache.t2.medium'
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - Ref: ElasticCacheSecurityGroup
      CacheSubnetGroupName:
        Ref: ElasticCacheSubnetGroup
      Tags:
        - Key: "Name"
          Value: !Sub '${AWS::StackName}-elastic-cache'
```
