### ISSUE TITLE
bug: Log output fails if lambda outputs more than 4000 bytes containing multibyte characters

### ISSUE THREAD

**Issue by yamachu** [localstack/localstack#7940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In a SQS Queue with a very long payload containing multibyte characters, the following lambda will fail with log output.

```js
exports.handler = async function(event, context) {
	console.log(event);
	return event;
};
```

docker-compose logs shows ...
```
my-service-localstack-1 | 2023-03-23T13:17:27.211 DEBUG --- [functhread29] l.s.a.lambda_executors     : Calling http://172.28.0.24:9001 to run invocation in docker-reuse Lambda container
my-service-localstack-1 | 2023-03-23T13:17:27.275  INFO --- [functhread29] l.s.awslambda.lambda_api   : Error executing Lambda function arn:aws:lambda:ap-northeast-1:000000000000:function:show-sqs-events-as-records: 'utf-8' codec can't decode byte 0x9f in position 0: invalid start byte Traceback (most recent call last):
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 459, in run_lambda
my-service-localstack-1 |     result = LAMBDA_EXECUTOR.execute(
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 494, in execute
my-service-localstack-1 |     return do_execute()
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 484, in do_execute
my-service-localstack-1 |     return _run(func_arn=func_arn)
my-service-localstack-1 |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 183, in wrapped
my-service-localstack-1 |     raise e
my-service-localstack-1 |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 179, in wrapped
my-service-localstack-1 |     result = func(*args, **kwargs)
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 471, in _run
my-service-localstack-1 |     raise e
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 467, in _run
my-service-localstack-1 |     result = self._execute(lambda_function, inv_context)
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 933, in _execute
my-service-localstack-1 |     return super(LambdaExecutorReuseContainers, self)._execute(func_arn, *args, **kwargs)
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 790, in _execute
my-service-localstack-1 |     result = self.run_lambda_executor(lambda_function=lambda_function, inv_context=inv_context)
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 667, in run_lambda_executor
my-service-localstack-1 |     result, log_output = self.execute_in_container(
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 870, in execute_in_container
my-service-localstack-1 |     inv_result = self.invoke_lambda(lambda_function, inv_context, lambda_docker_ip)
my-service-localstack-1 |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 894, in invoke_lambda
my-service-localstack-1 |     log_output = base64.b64decode(response.get("LogResult") or b"").decode("utf-8")
my-service-localstack-1 | UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 0: invalid start byte
my-service-localstack-1 |
```

### Expected Behavior

No error and tail logs

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
    localstack:
        image: localstack/localstack:1.3.1
        environment:
            LAMBDA_EXECUTOR: docker-reuse
            DOCKER_HOST: unix:///var/run/docker.sock
            SERVICES: sqs,lambda
            DEBUG: 1
            LAMBDA_REMOVE_CONTAINERS: 0
            SQS_ENDPOINT_STRATEGY: path
        volumes:
          - "./localstack:/var/lib/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"
        mem_limit: 1024m
```

### Environment

```markdown
- OS: macOS 13.2.1 (arm64)
- LocalStack: 1.3.1
```
