### ISSUE TITLE
bug: lambda docker executor fails when using auto-generated port

### ISSUE THREAD

**Issue by LaurentGoderre** [localstack/localstack#7989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the Remote Debugging config from the docs for Lambda when debugging multiple lambda and trying to use random port, the containers fail to start.

docker-compose.yml

```yaml
localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect=0.0.0.0:9229 -p 9229
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMP_DIR:-./.localstack}:${TMP_DIR:-/tmp/localstack}"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Then

```bash
serverless deploy --stage local
serverless invoke --stage local --function hello
```

Localstack logs

```
serverless-localstack-localstack-1  | 2023-03-28T13:32:55.758  WARN --- [lo:$LATEST_0] l.u.c.container_client     : Overwriting Docker container privileged flag None with new value False
serverless-localstack-localstack-1  | 2023-03-28T13:32:56.799  WARN --- [lo:$LATEST_1] l.u.c.container_client     : Overwriting Docker container privileged flag None with new value False
serverless-localstack-localstack-1  | 2023-03-28T13:32:57.719  WARN --- [lo:$LATEST_0] l.u.c.container_client     : Overwriting Docker container privileged flag None with new value False
serverless-localstack-localstack-1  | 2023-03-28T13:32:58.888  WARN --- [lo:$LATEST_1] l.u.c.container_client     : Overwriting Docker container privileged flag None with new value False
serverless-localstack-localstack-1  | 2023-03-28T13:32:59.730  WARN --- [lo:$LATEST_0] l.u.c.container_client     : Overwriting Docker container privileged flag None with new value False
serverless-localstack-localstack-1  | 2023-03-28T13:33:00.779  WARN --- [lo:$LATEST_1] l.u.c.container_client     : Overwriting 
```

This line is repeated over and over

### Expected Behavior

A new container is started for the function with an auto-assigned host port mapped to the container port.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

serverless deploy --stage local
serverless invoke --stage local --function hello

### Environment

```markdown
- OS: Debian
- LocalStack: 2.0.0.dev
```

**Comment by dominikschubert** [comment]
Hi @LaurentGoderre !

This seems to be happening because of some incorrect quoting in the LAMBDA_DOCKER_FLAGS. I managed to reproduce this when starting a nodejs-based Lambda function with your provided `docker-compose.yml` configuration.

Changing your `docker-compose.yml` to the following should resolve your issue:

```yaml
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LAMBDA_DOCKER_FLAGS="-e NODE_OPTIONS=--inspect=0.0.0.0:9229 -p 9229"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMP_DIR:-./.localstack}:${TMP_DIR:-/tmp/localstack}"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

I've also removed `LAMBDA_REMOTE_DOCKER` and `LAMBDA_EXECUTOR` from the sample since they are not applicable to the new lambda implementation. You can find more information about which variables have been deprecated in our documentation: https://docs.localstack.cloud/references/lambda-provider-v2/#configuration
