### ISSUE TITLE
bug: Localstack cant find initilization hook files when using `conatinerd` feature in Docker

### ISSUE THREAD

**Issue by stephenpope** [localstack/localstack#8048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you enable Docker experimental feature for using `containerd` to pull and store images then script files mounted into the container do not get read by the initialization job.

![image](https://user-images.githubusercontent.com/689099/229525894-be65c0a8-9349-4053-8f54-2e4c1dc99d59.png)

*note*: This is more of an FYI than a bug, I have spent a lot of time trying to work out what was wrong and I'm sure other people will run into this odd behaviour. I dont know if this is more about putting a warning in the documentation to tell people to disable this feature when running `localstack`.

### Expected Behavior

The scripts files mounted should be executed on startup of `localstack`.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

1. Set correct permissions on file
`chmod +x ../localstack/boot.d/test.sh`

2. Start localstack and mount script into correct location:
  ```
  docker run -it --rm --mount type=bind,source="../localstack/boot.d/test.sh",target="/etc/localstack/init/boot.d/test.sh" -e  LOCALSTACK_API_KEY=XXXXXXX -e DEBUG=1 localstack/localstack-pro:latest;
  ```

-> Scripts are not discovered <-

Log output:

```
2023-04-03T11:59:46.895 DEBUG --- [  MainThread] localstack.runtime.init    : Init scripts discovered: {BOOT: [], START: [], READY: [], SHUTDOWN: []}
```

Inspection of the container shows the files are mounted to the correct place but for some reason are not read.

Disabling the `containerd` feature in Docker means this starts working again and scripts are located correctly.

### Environment

```markdown
- OS: MacOS 13.3 (Arm/M2)
- LocalStack: latest
- Docker: 4.17.0
```

### Anything else?

Thoughts: Im not sure if the files are not mounted fast enough/in a lazy fashion for `locastack` to pick them up.

**Comment by thrau** [comment]
hey @stephenpope , thanks for reporting! it's great feedback and interesting for us to see how localstack behaves on containerd.

out of curiosity: have you tried whether different stages work, like the ready stage? could you also check whether the scripts have `#!/bin/bash` header and are executable?

the boot scripts are a bit peculiar, but for start/ready scripts you should get decent log output as well.

**Comment by stephenpope** [comment]
Our deployments have scripts on all stages and all stages are *not* picked up when this is enabled (empty array in all parts of the “init scripts discovered” section - even when doing the curl call to “localhost:4566/_localstack/init” ). Everyone else in the teams version was working ok apart from mine.

All scripts have good bash headers/correct line endings and were marked executable. You could even shell into the container and execute the scripts from the mounted folder but the script couldnt see them for whatever reason. They are all bash (no python files tested).

**Comment by seankolczynski** [comment]
Also having this issue

**Comment by Limess** [comment]
Having the same issue with Docker Desktop on Windows, docker engine v20.10.24.

This only occurs when enabling experimental containerd support

**Comment by jbosse** [comment]
I have this issue without containerd enabled.

**Comment by zwang9973** [comment]
I'm also having the same issue and containerd is not enabled.

**Comment by joebowbeer** [comment]
This works for me 😄 but I did switch to a subPath mount because it seemed to work more reliably:

https://github.com/localstack/helm-charts/pull/81#discussion_r1182022513

> I have found that mounting the single file via subPath is less flaky.
> 
> Without subPath, the contents of the configMap are mounted as symlinks to ..data, and this can result in file-not-found the first time it is deployed.
> 
> The downside is that subPaths are not automatically updated when a ConfigMap is modified.

Note the subPath in the volumeMount:

```yaml
          volumeMounts:
            - mountPath: /etc/localstack/init/ready.d/01-setup.sh
              name: localstack-ready-scripts
              subPath: 01-setup.sh
```
```yaml
   volumes:
        - name: localstack-ready-scripts
          configMap:
            defaultMode: 0755
            name: localstack-ready-scripts-config
```
```yaml
configMapGenerator:
- name: localstack-ready-scripts-config
  files:
  - localstack-ready-scripts/01-setup.sh
```
