### ISSUE TITLE
TimeoutError: gave up waiting for service dynamodb to start

### ISSUE THREAD

**Issue by egoson** [localstack/localstack#8100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get the following error with version 2.0.0, with version 1.4.0 I don't see the error and the services are working. Still I have to say that the s3 service works well

```
TimeoutError: gave up waiting for service dynamodb to start
localstack           | , headers={'Content-Type': 'application/json', 'X-Amzn-Errortype': 'InternalError', 'Content-Length': '915', 'x-amzn-requestid': 'K9PDQZLBIDPJUCYD06CZHHFF27M6PF9D6QYNDA13IH0ONNCIFGV0', 'x-amz-crc32': '3843399666', 'Connection': 'close', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'Access-Control-Allow-Headers': 'authorization,cache-control,content-length,content-md5,content-type,etag,location,x-amz-acl,x-amz-content-sha256,x-amz-date,x-amz-request-id,x-amz-security-token,x-amz-tagging,x-amz-target,x-amz-user-agent,x-amz-version-id,x-amzn-requestid,x-localstack-target,amz-sdk-invocation-id,amz-sdk-request', 'Access-Control-Expose-Headers': 'etag,x-amz-version-id'})
```

docker compose version 3
 ```
 localstack:
    image: localstack/localstack:2.0.0
    container_name: localstack
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - LS_LOG=trace
    ports:
      - "4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

docker-compose up

aws --endpoint-url=http://localhost:4566 dynamodb list-tables --region=eu-central-1

### Environment

```markdown
- OS: Ubuntu 22
- LocalStack: 2.0.0
```
