### ISSUE TITLE
Deploying SQS queues on image build

### ISSUE THREAD

**Issue by mclark1129** [localstack/localstack#819]
When using localstack as the base of an image, is it somehow possible to temporarily spin up SQS on build so that I can create queues that will live in the image?  

So far I've been able to install awscli-local right on the image, and my hope is that I could just run the commands to create the necessary queues during this process.  Unfortunately, the CLI can't communicate with the service during the build process because SQS  hasn't started listening yet.

```
FROM localstack/localstack

RUN pip install awscli-local
RUN awslocal sqs create-queue --queue-name myqueue-incoming.fifo --attribute FifoQueue=true
```

The `awslocal` command fails with `Address not available`.  It be great to start SQS, run that command, and then stop SQS when the commands completed.

**Comment by mberlanda** [comment]
This sounds like something definitely possible. SQS implementation is based on elasticmq and this can be instantiate with default resources: https://github.com/adamw/elasticmq#automatically-creating-queues-on-startup 
I will try to have a look at this in the next few days

**Comment by mberlanda** [comment]
@mclark1129  This is something done around here: https://github.com/localstack/localstack/blob/fa1a64c954b89b88ac30e77fd12930efc04c04c5/localstack/services/sqs/sqs_starter.py#L16-L35

It looks however that this would be quite complicated to inject since you do not necessary know `LOCALSTACK_HOSTNAME, port, backend_port`.

One possible solution could be:
- mount a volume (e.g. something that will end up into `INSTALL_DIR_ELASTICMQ/bootstrap/`)
- add a configuration file

```yml
# sqs.yml
"dummy-fifo-queue.fifo":
  defaultVisibilityTimeout: 0 seconds
  delay: 5 seconds
  receiveMessageWait: 0 seconds
  fifo: true
  contentBasedDeduplication: true
queue1:
  defaultVisibilityTimeout: 10 seconds
  delay: 5 seconds
  receiveMessageWait: 0 seconds
  deadLettersQueue:
    name: "queue1-dead-letters"
    maxReceiveCount: 3
   fifo: false
   contentBasedDeduplication: false
   copyTo: "audit-queue-name"
   moveTo: "redirect-queue-name"
   tags:
     tag1: "tagged1"
     tag2: "tagged2"
"audit-queue-name":
"redirect-queue-name":
"queue1-dead-letters":
```

@whummer would it be interesting for the project? Would you see any other resource type that could be bootstrapped?

**Comment by bluedigits** [comment]
I want to use localstack for acceptance tests and therefore it's the most important feature to have a possibility to seed localstack (SQS/SNS/S3/DynamoDB etc. with some predefined data). So when localstack is up it should have all queues/data/buckets etc. set.

**Comment by viktorlarsson** [comment]
Did you find anything @bluedigits ?

**Comment by bluedigits** [comment]
@viktorlarsson 
I didn‘t find a way to seed during image build there‘s a way to seed when spinning up a docker composition. How? Just link a volume to your seed script as follows:

```
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4575:4575
      - 4576:4576
    environment:
      - SERVICES=sns,sqs
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
```

Then, within this folder you can provide a script that initially creates the queues needed for your application tests, for instance I got a file named `00_4576_configure_sqs.sh` with the following content:

```
#!/usr/bin/env bash

awslocal sqs create-queue --queue-name catchall-deadletter
awslocal sqs create-queue --queue-name local-catchall-queue --attributes '{ "RedrivePolicy":"{\"deadLetterTargetArn\":\"arn:aws:sqs:us-east-1:queue:catchall-deadletter\", \"maxReceiveCount\":\"1\"}"}'
```

Since awslocal is available in the localstack container itself you basically can do everything here.

This was exactly what I needed!
