### ISSUE TITLE
EC2 describe-images does not respect --filters option

### ISSUE THREAD

**Issue by ivansamartino** [localstack/localstack#8226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack does not apply `--filters` when the parameter `--image-ids` is also passed as input value to the API call `describe-images`

```shell
awslocal ec2 describe-images --image-ids ami-b2696206 --filters "Name=tag:Branch,Values=foobar"
{
    "Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2023-04-28T15:43:17.000Z",
            "ImageId": "ami-b2696206",
            "ImageLocation": "None",
            "ImageType": "machine",
            "Public": false,
            "KernelId": "None",
            "OwnerId": "000000000000",
            "Platform": "windows",
            "RamdiskId": "ari-1a2b3c4d",
            "State": "available",
            "BlockDeviceMappings": [
                {
                    "DeviceName": "/dev/sda1",
                    "Ebs": {
                        "DeleteOnTermination": false,
                        "SnapshotId": "snap-4cfac3b2",
                        "VolumeSize": 15,
                        "VolumeType": "standard"
                    }
                }
            ],
            "Description": "AMI used for testing",
            "Hypervisor": "xen",
            "ImageOwnerAlias": "amazon",
            "Name": "test_ami_sharing",
            "RootDeviceName": "/dev/sda1",
            "RootDeviceType": "ebs",
            "Tags": [],
            "VirtualizationType": "hvm"
        }
    ]
}

```

When the `--image-ids` parameter is not passed, we get an empty list as you would expect:

```shell
awslocal ec2 describe-images  --filters "Name=tag:Branch,Values=foobar"
{
    "Images": []
}
```

### Expected Behavior

When the `--filters` option is passed, localstack should apply this filter to the list of AMIs

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up -d

```yml
version: "3"

services:
  localstack:
    image: localstack/localstack-pro
    container_name: localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY
      - LOCALSTACK_ENFORCE_IAM=0
      - AWS_DEFAULT_REGION=eu-west-1
    volumes:
      - "${TMPDIR}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    `awslocal ec2 describe-images --image-ids ami-b2696206 --filters "Name=tag:Branch,Values=foobar"`

AMI ID should be any available image-id. It can be retrieved using: `awslocal ec2 describe-images` to get all the available ones.

### Environment

```markdown
- OS: macOS Monterrey
- LocalStack: localstack-pro
- Image Digest: sha256:b3646d0b70056692327ba5cd1c5d86b6a680af2deb08dfc46ea4e8ab134865c5
```

### Anything else?

AWS Documentation: https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html
