### ISSUE TITLE
S3 PutObject using HTTPS not working 

### ISSUE THREAD

**Issue by daphnenhuch-at** [localstack/localstack#8227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm currently trying to a `createMultipartUpload` using the S3 client using the Javascript SDK. I've set the `endoint` to `'https://localhost.localstack.cloud'`. (Note that this works fine when I set the endpoint to http://localhost:4566 and set `s3ForcePathStyle`). Once I've instantiated my S3 client and try to do `s3.createMultipartUploadAsync` I see the following error:

```
{
    "message": "Client network socket disconnected before secure TLS connection was established",
    "code": "TimeoutError",
    "path": null,
    "host": "\<uploads bucket name\>.localhost.localstack.cloud",
    "port": 443,
    "time": "2023-04-28T19:27:49.233Z",
    "region": "us-east-1",
    "hostname": "\<uploads bucket name\>.localhost.localstack.cloud",
    "retryable": true
}
```

### Expected Behavior

I would expect to be able to issue an S3 PUT request using https

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

My docker-compose.yml looks like:

```
version: '3.4'

services:
    localstack:
        # Keep pinned to the same version as localstack/docker-compose.dev.yml
        image: localstack/localstack:1.1.0
        environment:
            - LS_LOG=warn
            # - DEBUG=True - very noisy but can be useful to debug localstack itself.
            - EDGE_PORT_HTTP=1
            - DATA_DIR=/data
            - DOCKER_HOST=unix:///var/run/docker.sock
            # override the default KMS_PROVIDER since the default one does not fail
            # subsequent decrypt calls after the key has been disabled. See -
            # https://github.com/localstack/localstack/issues/5410#issuecomment-1239507078
            - KMS_PROVIDER=local-kms
     
            - USE_SSL=1

           ports:
            - '127.0.0.1:4566:4566'
            - '127.0.0.1:443:443'

        volumes:
            - ./init-scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh # ready hoo
        healthcheck:
            test: curl localhost:4566
            start_period: 60s
            interval: 5s
            timeout: 3s
            retries: 10
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
#!/bin/bash
development and testing
awslocal s3 mb s3://<upload bucket>
awslocal s3 mb s3://<serving bucket>

echo '{
    "CORSRules": [
        {
            "AllowedHeaders": ["*"],
            "AllowedMethods": ["GET", "PUT", "POST"],
            "AllowedOrigins": [
                "https://<my company url>.com:3000",
                "https://*.preview.alpha-shadowbox.cloud",
                "https://localhost.localstack.cloud"
            ],
            "ExposeHeaders": ["ETag"],
            "MaxAgeSeconds": 3000
        }
    ]
}' > attachments_upload_cors.config

awslocal s3api --endpoint-url=http://localhost:4566 put-bucket-cors --bucket <serving bucket> --cors-configuration file://attachments_upload_cors.config
awslocal s3api --endpoint-url=http://localhost:4566 get-bucket-cors --bucket <serving bucket>
```

### Environment

```markdown
- OS:
- LocalStack:
```
