### ISSUE TITLE
bug: EventBridge Rule not able to forward message when target is a Kinesis Stream

### ISSUE THREAD

**Issue by denisdifazio** [localstack/localstack#8285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

EventBridge Rule not able to forward message to target Kinesis Stream. Despite the lambda being able to send the message to the event bus `AWS events.PutEvents => 200`

By checking the docker logs, I see the following message:

> Unable to send event notification {'version': '0', 'id': '47cdf856-9a56-4e50-8da5-7f11e97ba07e', 'detail-type': 'normalization', 'sour... to target {'RuleArn': 'arn:aws:events:us-east-1:000000000000:rule/after-normalization-event-bus/normalized-entities', 'Id': 'normalization-stream', 'Arn': 'arn:aws:kinesis:us-east-1:000000000000:stream/normalization-stream', 'RoleArn': 'arn:aws:iam::000000000000:role/data-normalization-local-BusRole-a8b2a809', 'InputPath': '$.detail'}: 'id'

### Expected Behavior

After inserting the correct message into the first Kinesis Stream (cdc-stream), it's expected to see the normalized message in the second Kinesis Stream (normalized-entities). The message should pass through the event bus and be filtered by the event rule before appearing in the second stream.

This same configuration was tested directly onto AWS, and it's working as expected.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yml
# docker-compose.yml

version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

Set up the workflow below with the following serverless-localstack configuration:

Kinesis Stream -> Lambda -> EventBridge Bus -> EventBridge Rule -> Kinesis Stream

```yml
# serverless.yml

service: data-normalization

frameworkVersion: '3.19.0'

custom:
  localstack:
    stages: local
  defaultStage: local
  currentStage: ${opt:stage, self:custom.defaultStage}

plugins:
  - serverless-esbuild
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: ${self:custom.currentStage}
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            Fn::GetAtt: [EventBus, Arn]

resources:
  Resources:
    IngressStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: cdc-stream
        RetentionPeriodHours: 24
        ShardCount: 1
    EgressStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: normalization-stream
        RetentionPeriodHours: 24
        ShardCount: 1
    RecordsDLQ:
      Type: AWS::SQS::Queue
    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: after-normalization-event-bus
    BusRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: internal
            PolicyDocument:
              Statement:
                - Effect: Allow
                  Action:
                    - kinesis:PutRecord
                    - kinesis:PutRecords
                  Resource:
                    - Fn::GetAtt: [EgressStream, Arn]
    EventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: normalized-entities
        Description: Send normalized entities downstream
        EventBusName:
          Ref: EventBus
        EventPattern:
          detail:
            table:
              - entity
        Targets:
          - Id: normalization-stream
            Arn:
              Fn::GetAtt: [EgressStream, Arn]
            RoleArn:
              Fn::GetAtt: [BusRole, Arn]
            InputPath: $.detail

functions:
  dataNormalization:
    name: ${self:service}-${self:custom.currentStage}-handler
    handler: src/handlers/index.handler
    timeout: 60
    maximumRetryAttempts: 0
    events:
      - stream:
          enabled: true
          type: kinesis
          arn:
            Fn::GetAtt: [IngressStream, Arn]
          maximumRetryAttempts: 5
          batchSize: 10
          startingPosition: LATEST
          destinations:
            onFailure:
              type: sqs
              arn:
                Fn::GetAtt: [RecordsDLQ, Arn]
```

```ts
// src/handlers/index.ts

import { KinesisStreamHandler } from 'aws-lambda';
import { EventBridge } from 'aws-sdk';

let eventBridge: EventBridge;

if (process.env.LOCALSTACK_HOSTNAME) {
  eventBridge = new EventBridge({
    endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:4566`,
  });
} else {
  eventBridge = new EventBridge();
}

export const handler: KinesisStreamHandler = async (event) => {
  const events: EventBridge.PutEventsRequestEntryList = [];

  for (const record of event.Records) {
    const data = JSON.parse(Buffer.from(record.kinesis.data, 'base64').toString('utf8'));

    for (const modifiedRecord of data.records) {
        events.push({
          Source: 'lambda',
          DetailType: 'normalization',
          Detail: JSON.stringify(modifiedRecord),
          EventBusName: 'after-normalization-event-bus',
        });
    }
  }

  if (events.length > 0) {
    await eventBridge
      .putEvents({
        Entries: events,
      })
      .promise();
  }
};
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal kinesis put-record --stream-name cdc-stream --data '{"records":[{ "test": 1 }]}' --partition-key test1

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```
