### ISSUE TITLE
API Gateway GET returns No Such Bucket and Unable to find operation for request to service apigateway

### ISSUE THREAD

**Issue by stevendwood** [localstack/localstack#8294]
Hello, I am not sure this is a bug as it seems like others might have run in to it.  I'm following the guide [here](https://docs.localstack.cloud/user-guide/aws/apigateway/) more or less (except I have a cloud formation template which works OK on "real" AWS).  Because of "local DNS issues" I cannot use the recommended URL for the API Gateway endpoint and instead have used the alternative style

http://localhost:4566/restapis/0v1p6q6/local/_user_request_/my/path1

This just returns a "Bucket not found" error as described in https://github.com/localstack/localstack/issues/5418.  Following the advice I was able to add a header to the request (no good really as need to go through a browser) but that then throws another error which is that it is unable to find operation for request to service apigateway.   It seems like adding in the header  in 

`curl -H "Authorization: AWS4-HMAC-SHA256 Credential=testkey/date/eu-west-2/apigateway/aws4_request" http://localhost:4566/restapis/0v1p6q6/local/_user_request_/my/path1` 

would be the wrong thing to do anyway though ?

**Comment by thrau** [comment]
Hi Steven @stevendwood. Could you please let us know how you are starting localstack? Please add all the configuration options you are using. It would also be helpful if you could share the cloudformation template. Thanks!

**Comment by stevendwood** [comment]
Hi Thomas @thrau 

I start it using docker-compose 
```
version: '3.0'

services:
   localstack:
     image: localstack/localstack:latest
      environment:
         - AWS_DEFAULT_REGION=eu-west-2
         - EDGE_PORT=4566
      ports:
         - '4566-4597:4566-4597'
      volumes:
         - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
         - "/var/run/docker.sock:/var/run/docker.sock"

```

```
Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: my-api

  SportResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: sport

  NewsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: news

  NewsProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref NewsResource
      PathPart: '{proxy+}'

  NewsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref NewsResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: ANY
        Uri: https://www.bbc.co.uk/news
  
  NewsProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref NewsProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        Type: HTTP_PROXY
        RequestParameters:
          integration.request.path.proxy: 'method.request.path.proxy'
        IntegrationHttpMethod: ANY
        Uri: https://www.bbc.co.uk/news/{proxy}


  SportMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref SportResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: HTTP_PROXY
        IntegrationHttpMethod: GET
        Uri: https://www.bbc.co.uk/sport
```
