### ISSUE TITLE
bug: put-rule does not work on version 2.0

### ISSUE THREAD

**Issue by yairasco** [localstack/localstack#8298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
{
    "Rules": []
}
```

### Expected Behavior

```
{
    "Rules": [ 
        {
            "Name": "hello-event-rule",
            "Arn": "arn:aws:events:eu-west-1:000000000000:rule/hello-event-bus/hello-event-rule",
            "EventPattern": "{}",
            "State": "ENABLED",
            "EventBusName": "hello-event-bus"
        }
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 ```yml

version: '3.9'

services:
  localstack:
    image: localstack/localstack:2.0.2
    restart: always
    ports:
      - 4566:4566
      - "4567-4597:4567-4597"
      - "8080:8080"
    environment:
      - SERVICES=events,iam,lambda,cloudformation,sts,s3,logs
      - EAGER_SERVICE_LOADING=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_ACCOUNT_ID=00000000000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash 
$ aws --profile localstack --endpoint-url http://localhost:4566 events put-rule --name hello-event-rule --event-bus-name hello-event-bus --event-pattern "{}"
$ aws  --profile localstack --endpoint-url http://localhost:4566 events list-rules
```

### Environment

```markdown
- OS: MacOS 13.3.1
- LocalStack:2.0.2
```

### Anything else?

Tried the same with localStack v1.4 and it works so the bug is only in 2.0+
