### ISSUE TITLE
bug: API-Gateway-v2 does not recognize routes when using Custom-ID tag

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#8363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When configuring an API-GW-v2, the routes are not recognized by Localstack `2.0.2`, with the same non-deprecated configuration as in `1.4.0`. I get the following error:

> exception while calling apigateway with unknown operation
> OperationNotFoundParserError: Unable to find operation for request to service apigateway

This also happens with the `latest` image (at time of writing: `sha256:27c9d7cea53384ea127eed5998083fb2d72e5bec71e8fceea8e7e8c83104d22b`)

### Expected Behavior

I would expect Localstack to correctly find the route and call the integration, as it does in previous versions.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
  localstack:
    image: localstack/localstack-pro:2.0.2
    container_name: "localstack"
    networks:
      default:
        aliases:
          - redacted.localstack  # needed for routing with spring-boot
    env_file:
      - configuration/environment/localstack.env
      - ../localstack_api_key.env
    ports:
      - "4566:4566"
    volumes:
      - "./configuration/localstack/scripts:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Contents of `localstack.env`:

```
AWS_DEFAULT_REGION=eu-central-1
PERSISTENCE=1
DEBUG=1
DNS_LOCAL_NAME_PATTERNS='.*(lambda|s3).*.amazonaws.com'
DNS_SERVER=127.0.0.11
EAGER_SERVICE_LOADING=1
HOSTNAME=localstack
LOCALSTACK_HOST=localhost
LS_LOG=trace
SERVICES=s3,kms,serverless,secretsmanager
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following setup, backend-service is a Spring-Boot application running in a container on the same Docker-Compose setup that exposes multiple endpoints, from which `GET /test` just returns a HTTP-200 response.

Locastack setup:

```bash
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create the integration for all endpoints, save ID for route creation
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --integration-method=GET --integration-uri=http://backend-service:9010/{proxy}
# Add route using the greedy path variable
awslocal apigatewayv2 create-route --api-id=my-api --route-key="GET /{proxy+}" --target=integrations/a3707166  # replace ID here
```

Calling GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test triggers the above-mentioned bug.

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack: 2.0.2 Pro
```

### Anything else?

Maybe I'm using the API wrong, or I missed an explanation somewhere in the docs? Either way, thanks in advance for the help.
