### ISSUE TITLE
bug: impossible to create/update signatureversion on SNS (Terraform / CDKTF)

### ISSUE THREAD

**Issue by alexbchr** [localstack/localstack#8415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Terraform (via CDKTF) to create SNS Topics, explicitely stating that I want to use SignatureVersion 2:

```ts
const myTopic = new SnsTopic(this, 'topic', {
    name: 'myTopic',
    signatureVersion: 2,
  })
```

However, on every plan / apply, I see this logged, just like the signatureVersion wasn't set properly on the topic (see screenshot below showing the planned changes). I can also confirm that my Sns subscription receives a SignatureVersion of 1 all the time.

<img width="377" alt="image" src="https://github.com/localstack/localstack/assets/3542313/6039191e-56b3-4359-bcb3-02da94adca59">

### Expected Behavior

The SignatureVersion should be properly set on the SnsTopic to 2.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```yaml
version: '3.9'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro:2.1.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - LOCALSTACK_ENFORCE_IAM=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-~/.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  ```

Ran using `docker compose up -d localstack`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

NA

### Environment

```markdown
- OS: MacOs 13.3.1
- LocalStack: 2.1.0 (Pro)
```
