### ISSUE TITLE
bug: Cognito allows disabled users to login

### ISSUE THREAD

**Issue by NateDimick** [localstack/localstack#8454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localstack cognito will allow a disabled user to log in.

### Expected Behavior

AWS Cognito does not allow disabled users to log in

```sh
nate@laptop:~$ aws cognito-idp admin-initiate-auth --user-pool-id <redacted>  --client-id <redacted>  --auth-flow ADMIN_USER_PASSWORD_AUTH --auth-parameters '{"USERNAME": "disabled-user", "PASSWORD": "<redacted>"}'

An error occurred (NotAuthorizedException) when calling the AdminInitiateAuth operation: User is disabled.
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: '3.8'
services:
  localstack:
    image: localstack/localstack-pro
    environment:
      - REQUIRE_PRO=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=s3,cognito,dynamodb,ssm,elasticache,sqs,sns
      - DNS_ADDRESS=127.0.0.1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
awslocal cognito-idp create-user-pool --pool-name my-pool
awslocal cognito-idp create-user-pool-client --user-pool-id <pool-id> --client-name my-client --no-generate-secret --prevent-user-existence-errors ENABLED --explicit-auth-flows ALLOW_ADMIN_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH
awslocal cognito-idp admin-create-user --user-pool-id <pool-id> --username ted
awslocal cognito-idp admin-set-user-password --user-pool-id <pool-id> --username "ted" --password "detroit" --permanent
awslocal cognito-idp admin-disable-user --user-pool-id <pool-id> --username ted
awslocal cognito-idp admin-initiate-auth --user-pool-id <pool-id> --client-id <client-id> --auth-flow ADMIN_USER_PASSWORD_AUTH --auth-parameters '{"USERNAME": "ted", "PASSWORD": "detroit"}'
```

### Environment

```markdown
- OS:Ubuntu 20.04
- LocalStack: 2.0.3.dev20230516080016
```
