### ISSUE TITLE
bug: unable to upload zip files over 1mb

### ISSUE THREAD

**Issue by KleberMotta** [localstack/localstack#8477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to execute any command that could upload my zip files to localstack, for example:
```shell
awslocal s3 cp "over_1mb_zipped_file.zip" s3://my-lambda/lambdas/
```
Localstack hangs, with no error message.

For example, the following message is the last line when executing the `s3 cp ..` command:
```
INFO --- [   asgi_gw_0] localstack.request.aws     : AWS s3.CreateMultipartUpload => 200
```

When `DEBUG=1` it outputs the following log after a few seconds:
```
2023-06-10T20:22:34.230 DEBUG --- [   asgi_gw_0] plugin.manager             : instantiating plugin PluginSpec(localstack.aws.provider.cloudwatch:default = <function cloudwatch at 0x7f9de55c45e0>)
2023-06-10T20:22:34.230 DEBUG --- [   asgi_gw_0] plugin.manager             : loading plugin localstack.aws.provider:cloudwatch:default
2023-06-10T20:22:34.248 DEBUG --- [   asgi_gw_0] l.s.cloudwatch.provider    : starting cloudwatch scheduler
2023-06-10T20:22:34.248 DEBUG --- [   asgi_gw_0] l.services.plugins         : checking service health cloudwatch:4566
```

Obs.: the zipped files are Python lambda functions alongside their dependencies, they are roughly 1.10 MB in size.

### Expected Behavior

When running `awslocal s3 cp "over_1mb_zipped_file.zip" s3://my-lambda/lambdas/`, or any other command that could upload my zip files to localstack, be able to upload my zipped files.

### How are you starting LocalStack?

```shell
docker-compose run -e TAG="$(TAG)" -e ALL_LAMBDAS="$(ALL_LAMBDAS)" localstack
```

### docker-compose.yml
```yml
version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sns,sqs,s3,s3api,cloudwatch,lambda,iam
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=DEV123
      - AWS_SECRET_ACCESS_KEY=DEV123
    volumes:
      - "./.localstack:/etc/localstack/init/ready.d"
      - "./output:/tmp/zips"
```

### Client commands - The contents of the init script inside `.localstack/`:
```shell
#!/usr/bin/env bash

# Creating s3 bucket to receive lambdas
awslocal s3api create-bucket --bucket lambdas-bucket

# Creating wallet-cashout-sns topic SNS
awslocal sns create-topic --name wallet-cashout-sns;

# Creating wallet_registration_sns_topic
awslocal sns create-topic --name wallet_registration_sns_topic;

# Creating cashout-bank-account datalake SQS queue
awslocal sqs create-queue --queue-name wallet-cashout-bank-account-sqs;

# Creating olxbr-dl-olx-wallet s3 bucket
awslocal s3api create-bucket --bucket olxbr-dl-olx-wallet

echo "List created buckets"
awslocal s3api list-buckets

# Adding the lambdas folder
awslocal s3api put-object --bucket lambdas-bucket --key lambdas/

## Upload all lambda Zips to local bucket TODO try to use cp again
for LAMBDA_NAME in $ALL_LAMBDAS; do
  echo "uploading: lambda_${LAMBDA_NAME}_${TAG}.zip"
#  awslocal s3api put-object --bucket localstack-bucket --key "lambdas/lambda_${LAMBDA_NAME}_${TAG}.zip" --body "/tmp/zips/lambda_${LAMBDA_NAME}_${TAG}.zip"
  awslocal s3 cp "/tmp/zips/lambda_${LAMBDA_NAME}_${TAG}.zip" s3://lambdas-bucket/lambdas/
done

#echo "List all files added to localstack-bucket"
#awslocal s3 ls s3://lambdas-bucket

# Setup lambda roles
awslocal iam create-role --role-name lambda-role --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
awslocal iam attach-role-policy --role-name lambda-role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

# Setup bank_account function
awslocal lambda create-function \
--function-name wallet_datalake_bank_account_function \
--runtime python3.8 \
--role arn:aws:iam::000000000000:role/lambda-role \
--handler bank_account.handler \
--zip-file "fileb:///tmp/zips/lambda_bank_account_${TAG}.zip" \
```

### Environment

```markdown
- OS: macOS Ventura 13.2
- LocalStack: version: 2.1.1.dev, build date: 2023-06-09, build git hash: 3a590c02
```

### Anything else?

[localstack.log](https://github.com/localstack/localstack/files/11713359/localstack.log) execution log.

Please help 🥲

**Comment by KleberMotta** [comment]
@bentsku first of all, thanks for the suggestion of opening a new issue. Secondly, I'm here to help with whatever is needed :)

**Comment by KleberMotta** [comment]
My `docker-compose.yml` was missing some necessary configurations:

```yml
version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=sns,sqs,s3,s3api,cloudwatch,lambda,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=DEV123
      - AWS_SECRET_ACCESS_KEY=DEV123
      - TAG=${TAG}
      - ALL_LAMBDAS=${ALL_LAMBDAS}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/etc/localstack/init/ready.d"
      - "./output:/tmp/zips"
      - "./logs:/tmp/logs"
```

With this changes I was able to run it without problems on Windows 11 using WSL. The docker on my mac is running on virtualBox (due to some problems with M1 and other images that I use), so I figure that the problem is that my version of docker is old and incompatible with current Localstack. I will close this issue for now, as it seems that it had nothing to do with localstack per se.

Hope that this documented Issue helps someone and avoid an unnecessary ticket.
