### ISSUE TITLE
Persist Elasticsearch data across docker container restart

### ISSUE THREAD

**Issue by bridadan** [localstack/localstack#848]
I'm using the docker container found on docker hub: https://hub.docker.com/r/localstack/localstack/

I'm using the following configuration in my `docker-compose.yml`:

```yaml
aws:
        image: "localstack/localstack:0.8.7"
        environment:
            - SERVICES=s3,es
            - DATA_DIR=/tmp/localstack/data
```

On each reboot of the container however, my Elasticsearch data is being deleted. For my use case I'd like for this data to persist. I dug a little bit into the code base and found this: https://github.com/localstack/localstack/blob/master/localstack/services/es/es_starter.py#L24

Is the deletion of all Elasticsearch data on startup intended behavior? If so, would anyone be opposed to adding a config option for this? I'd be willing to contribute this if you could provide a little guidance.

**Comment by PeterBengtson** [comment]
You also need to declare a volume for the DATA_DIR. E.g.:

version: "3.6"
services:
  localstack:
    image: localstack/localstack
    restart: always
    ports:
      - "4567-4583:4567-4583"
      - "8080:8080"
    volumes:
      - ./localstack_data:/tmp/localstack/data
    environment:
      DATA_DIR: /tmp/localstack/data

**Comment by bridadan** [comment]
Oh duh, thanks for the help!

**Comment by bridadan** [comment]
Hi @Fly-Luck, I believe I was able to make it persist just fine. I had to create a volume and then specify which volume to bind to in the localstack service (like @PeterBengtson showed above) but it worked fine. Here's a slightly edited version of my configuration:

```yaml
version: '2'
services:
    aws:
        image: "localstack/localstack:0.8.7"
        environment:
            - SERVICES=es
            - DATA_DIR=/tmp/ls/localstack/data
        volumes:
            - persistent-data:/tmp/ls
volumes:
    persistent-data:
```
