### ISSUE TITLE
Support For Lambda in Rootless Podman Setup

### ISSUE THREAD

**Issue by pari08tosh** [localstack/localstack#8605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

I'm trying to setup localstack for lambda testing in a rootless Podman environment. I'm able to run the latest localstack image (2.1.0) on Podman in rootless mode. When attempting to create lambdas, it is able to download and start the image, but fails at the IP address resolution stage as rootless Podman containers don't have an IP address associated.

 I understand that IP address is required to communicate with the lambda container in the default bridge mode in docker. As this is not possible in rootless podman, it would be useful to configure a bypass to IP resolution and instead use port-mappings to communicate over localhost. 

I also found the `LAMBDA_DEV_PORT_EXPOSE` config in the code, which does exactly what would be required in rootless podman, assign a port mapping to container and communicate over 127.0.0.1. Unfortunately localstack attempts to fetch the lambda container IP and fails, before it sets the ip to 127.0.0.1.

### 🧑‍💻 Implementation

Add an ENV based configuration to run lambdas containers in Port Mapping mode instead of the bridge network mode, as using the default bridge or creating custom networks is not allowed in podman rootless mode. Also allow lambda containers to be run in host network, so they can be resolved over localhost from the localstack container. 

Eg: 
LAMBDA_CONTAINER_PORT_EXPOSE=true

**Comment by dfangl** [comment]
Hi @pari08tosh !
When using podman, we had great success with this docker-compose.yml template (of course it is run in podman):
```yaml
version: "3.8"

services:
 localstack:
   container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
   image: localstack/localstack
   ports:
     - "127.0.0.1:4566:4566"            # LocalStack Gateway
     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
   security_opt:
     - "label=disable"
   environment:
     # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
     - DEBUG=${DEBUG:-0}
     - PERSISTENCE=${PERSISTENCE:-0}
   volumes:
     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
     - "/var/run/docker.sock:/var/run/docker.sock"
```
It runs well in a rootless podman machine. You might need to enable the podman socket for it to work, if you are not spawning it in a machine.

It of course assumes that LocalStack is run inside a container as well.

Regarding the issue with the missing IP address:
Note that since podman 4.0, rootless users can use `netavark`: https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#bridge This will be necessary to use, to get a proper networking setup, with an IP address per pod.
