### ISSUE TITLE
SNS does not keep messages

### ISSUE THREAD

**Issue by black-snow** [localstack/localstack#8670]
I've set up localstack via compose:

```yaml
# volumes etc.

services:
  localstack:
    container_name: localstack_main
    image: ${LOCALSTACK_IMAGE:-localstack/localstack@sha256:6e08b20548aba3e3a4389ac190009161b4f7afb9e2c8875f94dc3b885be1a17a}
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

When I publish:
```
awslocal sns publish --topic-arn "arn:aws:sns:us-east-1:000000000000:test" --message '{"hello":1}'

{
    "MessageId": "1fdd1cfe-6dc3-41c3-a0f0-672065179815"
}
```

and query right after:
```
curl http://localhost:4566/_aws/sns/platform-endpoint-messages

{"platform_endpoint_messages": {}, "region": "us-east-1"}
```

There's nothing there. But it [should list](https://docs.localstack.cloud/aws/sns/#accessing-published-platform-messages) all the messages sent so far, right?

Is something off with my setup?
