### ISSUE TITLE
bug: `Exec format error` in custom ready hook script on apple silicon

### ISSUE THREAD

**Issue by Haegi** [localstack/localstack#8688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting localstack with a custom `init-aws.sh` ready hook script, it fails with the following error:
```
[  MainThread] localstack.runtime.init    : Error while running script Script(path='/etc/localstack/init/ready.d/init-aws.sh', stage=READY, state=ERROR): [Errno 8] Exec format error: '/etc/localstack/init/ready.d/init-aws.sh'
```

However, I can execute the file successfully when going into the container and executing the file manually.

I was able to reproduce this error in docker compose and in my local kubernetes (kind) cluster.

### Expected Behavior

The init scripts are successfully getting called.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yaml
```yaml
version: '3.5'

services:
  localstack:
    container_name: localstack_container
    image: localstack/localstack:2.0.2
    environment:
      SERVICES: 'secretsmanager,s3'
    ports:
      - '4566:4566'
    networks:
      - postgres_network
    volumes:
      - "/path/to/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"  # ready hook
```

init-aws.sh

```bash
awslocal s3 mb s3://localbucket
```

### Environment

```markdown
- OS: macOS 13.4.1, Apple M1 Pro
- LocalStack: 2.0.2 (also happens in 2.1.0)
- Docker Engine: 24.0.2
- Docker Client: 24.0.2
```
