### ISSUE TITLE
RDS EngineVersion is no longer being respected

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#8761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a new RDS Postgresql instance in localstack, I specify version 14, but get version 11.19 instead. This did work previously, but at some point between Localstack 1.4 and current this has broken.
```
response = self.rds_client.create_db_instance(
                    DBName=self.db.database_name,
                    DBInstanceIdentifier=self.db.database_identifier,
                    AllocatedStorage=100,
                    DBInstanceClass=f"db.{instance_class}",
                    Engine="postgres",
                    MasterUsername=self.db.database_username,
                    MasterUserPassword=self.db.database_password,
                    EngineVersion="14",
                    AutoMinorVersionUpgrade=True,
                    PubliclyAccessible=True,
                )
```

In psql, running `select version();`, I get `psql (15.3 (Ubuntu 15.3-1.pgdg22.04+1), server 11.19 (Debian 11.19-0+deb10u1))`

### Expected Behavior

Per the docs, https://docs.localstack.cloud/user-guide/aws/rds/#postgres-engine, `When creating an RDS DB cluster or instance with postgres/aurora-postgresql DB engine and a specific EngineVersion, LocalStack will install and provision the respective Postgres version on demand.` I expect to get version 14 when I specify 14.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose
```
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:2.0.2
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,dynamodb,rds,secretsmanager
      - HOST_TMP_FOLDER=${TMPDIR}
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=myapikey
      - EAGER_SERVICE_LOADING=1
      - RDS_PG_CUSTOM_VERSIONS=1
      # - LS_LOG=trace
    volumes:
      - "LocalStack_vol:/var/lib/localstack:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack:2.0.2
```
