### ISSUE TITLE
bug: Make possible to deploy APIGateway Custom ID with SAM 

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/localstack#8804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the tags provided in the AWS SAM template do not reproduce to the CloudFormation resources which affects the APIGateway Custom ID.

I think part of the issue is the unimplemented property [propagatetags](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-propagatetags).

I utilized the `samlocal init` and used the third option, reducing it to just the essential resource.

```yaml
Resources:
  HelloEfsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_efs/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Tags:
        _custom_id_: my-api
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
```

Result when deployed
```json
{
            "id": "lsc8c3caox",
            "name": "sam-app-ServerlessRestApi-ae1d0fc5",
            "createdDate": 1690977780.0,
            "version": "1.0",
            "apiKeySource": "HEADER",
            "endpointConfiguration": {
                "types": [
                    "EDGE"
                ]
            },
            "tags": {
                "aws:cloudformation:logical-id": "ServerlessRestApi",
                "aws:cloudformation:stack-name": "sam-app",
                "aws:cloudformation:stack-id": "arn:aws:cloudformation:us-east-1:000000000000:stack/sam-app/7cdf43b7"
            },
            "disableExecuteApiEndpoint": false
        }
```

### Expected Behavior

I should be able to see the API gateway with a custome ID.

```shell
$ awslocal apigateway get-rest-apis
{
    "items": [
        {
            "id": "myid123",
            "name": "my-api",
            "createdDate": 1690974942.0,
            "apiKeySource": "HEADER",
         ...
             ]
        }
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run localstack/localstack

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://mybucket

### Environment

```markdown
- OS: Windows
- LocalStack: 2.2.1.dev20230731233910
```
