### ISSUE TITLE
enhancement request: document proper docker compose healtcheck

### ISSUE THREAD

**Issue by Meemaw** [localstack/localstack#8834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Would be nice if there was an official way to properly do healtcheck in docker compose. There are plenty of different answers online, and its unclear what would be the best.

Related https://github.com/localstack/localstack/issues/1095

I thin this answer gives a good command to use, but I've been having some troubles converting that to the docker compose healthcheck:
https://github.com/localstack/localstack/issues/1095#issuecomment-1500569938

**Comment by simonrw** [comment]
Hi, thanks for suggesting this enhancement.

The default docker container for LocalStack includes a [health check directive already](https://github.com/localstack/localstack/blob/5a368bc6bac99c1b2ce856f010dad3e5a94d79d5/Dockerfile#L178) - is there a reason you need a separate health check?

If you do need to specify a health check from `docker-compose`, you could add something like:

```yaml
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 15s
```

which is in effect what the healthcheck specified in the `Dockerfile` does.

**Comment by Meemaw** [comment]
Hi, didn't know that.

Do you know if the healtcheck defined in `Dockerfile` automatically propagates to the compose?

**Comment by simonrw** [comment]
Yeah it seems to. When I run `docker compose up` I see "starting" in the `STATUS` column, which changes to "healthy" after 10 seconds (the first `interval` parameter). I believe that docker compose uses this health check internally.

**Comment by Meemaw** [comment]
Great, closing this then.

**Comment by jebl01** [comment]
This doesn't really cut it if you need to wait for resources to be created. In our setup we create a bunch of SQS queues that need to be there before the service starts up. We solved it like this in the docker-compose file:
```yaml
    healthcheck:
      test: >-
        curl -s localhost:4566/_localstack/health | grep -q '"initScripts": "initialized"'
      interval: 5s
      timeout: 5s
      start_period: 1m
      retries: 5
```

now `depends_on` in our application container will actually wait until all resources that are created using initialization scripts are ready 🎉

**Comment by itaranto** [comment]
> This doesn't really cut it if you need to wait for resources to be created. In our setup we create a bunch of SQS queues that need to be there before the service starts up. We solved it like this in the docker-compose file:
> 
> ```yaml
>     healthcheck:
>       test: >-
>         curl -s localhost:4566/_localstack/health | grep -q '"initScripts": "initialized"'
>       interval: 5s
>       timeout: 5s
>       start_period: 1m
>       retries: 5
> ```
> 
> now `depends_on` in our application container will actually wait until all resources that are created using initialization scripts are ready 🎉

This doesn't work anymore on newer LocalStack versions. There seems to be now a `init/<STAGE>` endpoint that checks for the specified stage.

This one worked for me:

```yaml
    healthcheck:
      test: >-
        curl -sf localhost:4566/_localstack/init/ready | grep -q '"completed": true,'
      interval: 5s
      timeout: 5s
      start_period: 1m
      retries: 5
```
