### ISSUE TITLE
bug: GLIBC not found

### ISSUE THREAD

**Issue by acraven** [localstack/localstack#8851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are experiencing the same behaviour as outlined in https://github.com/nsmithuk/local-kms/issues/58.

We are using LocalStack 2.1 and `KMS_PROVIDER=local-kms`

### Expected Behavior

I would expect KMS operations to work, but instead we get repeated errors in the logs (as per the OP):
```
[container-267b98d4a74d] 2023-08-07T09:22:43.599  INFO --- [functhread33] l.s.kms.local_kms_server   : /var/lib/localstack/lib/local-kms/latest/local-kms_linux-amd64.bin: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by /var/lib/localstack/lib/local-kms/latest/local-kms_linux-amd64.bin)

[container-267b98d4a74d] 2023-08-07T09:22:43.599  INFO --- [functhread33] l.s.kms.local_kms_server   : /var/lib/localstack/lib/local-kms/latest/local-kms_linux-amd64.bin: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by /var/lib/localstack/lib/local-kms/latest/local-kms_linux-amd64.bin)

[container-267b98d4a74d] 2023-08-07T09:22:43.599  INFO --- [functhread33] localstack.utils.run       : Restarting process (received exit code 1): ['/var/lib/localstack/lib/local-kms/latest/local-kms_linux-amd64.bin']
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

`run-dependencies.ps1`
```ps
docker-compose -f docker-compose.dependencies.yaml
```

`docker-compose.dependencies.yaml`
```yaml
version: "3"

services:
  localstack:
    image: localstack/localstack:2.1
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - KMS_PROVIDER=local-kms
    volumes:
      - ./Dependencies/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - ./Dependencies/localstack/localstack-keys.yaml:/init/seed.yaml
```

Any KMS iteration is likely to cause the error eg.
```ps
aws kms create-key --origin EXTERNAL --endpoint-url http://localhost:4566
```

### Environment

```markdown
- OS: Windows 11
- LocalStack: 2.1
```

### Anything else?

As per Slack comment https://localstack-community.slack.com/archives/CMAFN2KSP/p1691490131619919

Should LocalStack be pulling the `/localstack/v3/local-kms.linux.bin` file rather than `/3/local-kms_linux-amd64.bin`?

Forgive me if this is way off the mark, we're scratching around trying to fix the GLIBC error.

And on a related note, will LocalStack continue to use local-kms for the foreseeable future? I'm a little confused over the removal of `KMS_PROVIDER` which accepts either `moto` or `local-kms`. I can't tell if LS is moving to either one of those or something else.
