### ISSUE TITLE
bug: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.3.10

### ISSUE THREAD

**Issue by Meemaw** [localstack/localstack#8865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting the following errors in CI, during the initialization hooks.

2023-08-08T16:40:55.563787506Z 2023-08-08T16:40:55.563 ERROR --- [   asgi_gw_6] l.aws.handlers.logging     : exception during call chain: Could not get list of releases from https://api.github.com/repos/etspaceman/kinesis-mock/releases/tags/0.3.10: {"message":"API rate limit exceeded for 54.161.249.234. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

### Expected Behavior

There should be a way to work around this request/error, perhaps by pinning the release/tag somehow?

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce
```yaml
  localstack:
    image: 718537141989.dkr.ecr.us-east-1.amazonaws.com/ecr-public/localstack/localstack:2.2.0
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=warn
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - 4566:4566
    volumes:
      - "./scripts/setup_localstack.sh:/etc/localstack/init/ready.d/setup_localstack.sh"
      - /var/run/docker.sock:/var/run/docker.sock
```

### Environment

```markdown
- OS:
- LocalStack:2.2.0
```
