### ISSUE TITLE
bug: event.requestContext.connectionId not set in API Gateway v2 authorizer

### ISSUE THREAD

**Issue by bialad** [localstack/localstack#8893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`event.requestContext.connectionId` is undefined in authorizer lambda, but set in $connect lambda.

### Expected Behavior

`event.requestContext.connectionId` should also be set in authorizer lambda, as is the behavior in AWS.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:2.2
    networks:
      - local
    ports:
      - "4510-4519:4510-4519"
      - "4566:4566"
      - "4571:4571"
    env_file: .key
    environment:
      - SERVICES=dynamodb,lambda,apigateway,apigatewayv2,s3,iam,sts,ssm
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_DOCKER_NETWORK=local
    volumes:
      - ./tmp/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
const authorizer = await apigateway_v2.createAuthorizer({
    ApiId: apiId,
    AuthorizerUri: `arn:aws:apigateway:${process.env.REGION}:lambda:path/2015-03-31/functions/${functionArn}/invocations`,
    AuthorizerType: 'REQUEST',
    IdentitySource: ['route.request.header.Authorization'],
    Name: 'authorizer',
  }).promise();
  log.info('authorizer', authorizer);
```

```
const handler = async (event: APIGatewayRequestAuthorizerEvent) {
  const { connectionId } = event.requestContext;
}
```

### Environment

```markdown
- OS: Debian 12
- LocalStack: docker localstack/localstack-pro:2.2
```
