### ISSUE TITLE
bug: Route53 implementation doesn’t return caller reference associated with hosted zone

### ISSUE THREAD

**Issue by frank-lenormand** [localstack/localstack#8921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [Route53 documentation for the `create-hosted-zone` action](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/create_hosted_zone.html#Route53.Client.create_hosted_zone) indicates that hosted zones creation requests must be accompanied by a unique “caller reference id”.

The [Route53 documentation for the `get-hosted-zone` action](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/get_hosted_zone.html#Route53.Client.get_hosted_zone) indicates that the caller reference above is expected to be returns along with the hosted zone object.

This is not the behaviour I observe, when creating and subsequently querying a hosted zone on LocalStack:

```
aws --endpoint-url=http://localstack:4566 route53 create-hosted-zone --name test.me --caller-reference test-me-uniq
{
    "Location": "https://route53.amazonaws.com/2013-04-01/hostedzone/LU2N4H8R9C047W3",
    "HostedZone": {
        "Id": "/hostedzone/LU2N4H8R9C047W3",
        "Name": "test.me.",
        "Config": {
            "PrivateZone": false
        },
        "ResourceRecordSetCount": 2
    },
    "ChangeInfo": {
        "Id": "/change/C1PA6795UKMFR9",
        "Status": "INSYNC",
        "SubmittedAt": "2017-03-15T01:36:41.958000Z"
    },
    "DelegationSet": {
        "Id": "",
        "NameServers": [
            "ns-2048.awsdns-64.com",
            "ns-2049.awsdns-65.net",
            "ns-2050.awsdns-66.org",
            "ns-2051.awsdns-67.co.uk"
        ]
    }
}
```

```
aws --endpoint-url=http://localstack:4566 route53 get-hosted-zone --id /hostedzone/LU2N4H8R9C047W3
{
    "HostedZone": {
        "Id": "/hostedzone/LU2N4H8R9C047W3",
        "Name": "test.me.",
        "Config": {
            "PrivateZone": false
        },
        "ResourceRecordSetCount": 2
    },
    "DelegationSet": {
        "Id": "",
        "NameServers": [
            "ns-2048.awsdns-64.com",
            "ns-2049.awsdns-65.net",
            "ns-2050.awsdns-66.org",
            "ns-2051.awsdns-67.co.uk"
        ]
    }
}
```

The `HostedZone.CallerReference` field is missing from the object returned by the second query, above.

### Expected Behavior

The object returned by the `get-hosted-zone` action should include the `CallerReference` field with which the hosted zone was created. In the reproducer provided, that would be `test-me-uniq`.

References:

- https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/create_hosted_zone.html#Route53.Client.create_hosted_zone
- https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/route53/client/get_hosted_zone.html#Route53.Client.get_hosted_zone

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

I made sure to pull the latest Docker image before creating the issue:

```console
$ docker pull localstack/localstack
```

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Docker compose section:

```yaml
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "0.0.0.0:4566:4566"
      - "0.0.0.0:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME=localstack
      - HOSTNAME_EXTERNAL=localstack
      - DATA_DIR=/tmp/localstack/data
      - PERSISTENCE=1
    volumes:
      - localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - testing_net
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```console
$ aws --endpoint-url=http://localstack:4566 route53 create-hosted-zone --name test.me --caller-reference test-me-uniq
```

```console
$ aws --endpoint-url=http://localstack:4566 route53 get-hosted-zone --id …
```

### Environment

```markdown
- OS: `18.04.6 LTS (Bionic Beaver)`
- LocalStack: `latest`
```
