### ISSUE TITLE
enhancement request: Add ability to load pod state from within the localstack container

### ISSUE THREAD

**Issue by fl0rian-p** [localstack/localstack#8966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Hi, 

I trying to get rid local-kms in my projects and after finding this [issue](https://github.com/localstack/localstack/issues/8851#issuecomment-1671198650), I've taken a look at using cloud pods files for that.

I'm using docker-compose to boot several containers including localstack and I'd like to be able to load the state from within the container itself. 

At the moment though, the `pod` command is however not available from within as the output of the `--help` option show:

```
# ./bin/localstack --version
2.2.0
# ./bin/localstack --help
Usage: localstack [OPTIONS] COMMAND [ARGS]...

  The LocalStack Command Line Interface (CLI)

Options:
  -v, --version       Show the version and exit.
  -d, --debug         Enable CLI debugging mode
  -p, --profile TEXT  Set the configuration profile
  -h, --help          Show this message and exit.

Commands:
  completion  CLI shell completion
  config      Manage your LocalStack config
  infra       (Deprecated) Manage LocalStack infrastructure
  logs        Show LocalStack logs
  ssh         Obtain a shell in LocalStack
  start       Start LocalStack
  status      Query status info
  stop        Stop LocalStack
  update      Update LocalStack
  wait        Wait for LocalStack
```

Would it be possible for you to add that capability ? 

Kind regards

**Comment by giograno** [comment]
Hi @fl0rian-p, thanks for raising the issue! Could you try to update your CLI by executing the following `./bin/localstack update localstack-cli`? Keep us updated!

**Comment by fl0rian-p** [comment]
Hi @giograno ! 

Thanks for your response and sorry for my late reply. 

I might have not explained properly before, sorry about that 😅 

The CLI I've installed on my machine is up to date (2.2.0) and does have the `pod` command. What I'm wondering is why the CLI within the localstack container does not have it.

Basically, I have a similar `docker-compose.yml` to this:

```
version: '3.4'

services:

  aws:
    image: localstack/localstack:2.2.0
    ports:
      - 4566
    environment:
      - HOSTNAME_EXTERNAL=${DOCKER_HOST_IP-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: "curl -s localhost:4566/_localstack/init/ready | grep -q '\"completed\": true'"
      start_period: 10s
      interval: 2s
```

I'd like to be able to provide an init script that would execute the hereafter command upon startup:

```
$ /opt/code/localstack/bin/localstack pod load /path/to/my/state
```

Just to be sure, I've tried performing command you mentioned from within the container. It seems to be failing due to some missing dependencies. And then it tries to build them but fails as gcc is missing.


Thanks !
