### ISSUE TITLE
bug: localstack s3 saving file with incorrect url

### ISSUE THREAD

**Issue by israelcosta09** [localstack/localstack#8977]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have a docker-compose.yaml that configures localstack to run locally, and I have a service that uses it. To connect these containers I use the name of container, but when I save a file in localstack, it returns the url of connection **(e.g. http://localstack:4566/tests/image.png)**.

**docker-compose.yaml:**
```
version: '3.9'

services:
  localstack:
    image: localstack/localstack
    networks:
      - aws
    environment:
      SERVICES: s3
      EDGE_PORT: 4566
      AWS_DEFAULT_REGION: sa-east-1
      HOSTNAME_EXTERNAL: localhost
      LOCALSTACK_HOST: localhost
    ports:
      - 4566-4583:4566-4583
    volumes:
      - ${TEMPDIR:-/tmp/localstack}:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./aws:/etc/localstack/init/ready.d

  my-service:
    build: ../
    networks:
      - local
      - aws
    environment:
      S3_ACCESS_KEY: s3_access_key
      S3_SECRET_KEY: s3_secret_key
      S3_REGION: sa-east-1
      S3_BUCKET: tests
      S3_ENDPOINT: http://localstack:4566
    ports:
      - 3500:3500
      
networks:
  local:
    driver: bridge

  aws:
    driver: bridge
```

I tryied to use `HOSTNAME_EXTERNAL` and `LOCALSTACK_HOST` but not works.

### Expected Behavior

I need to have the return of image in a format that I can access by browser for example, to render in another app.

For example, I need to receive http://localhost:4566/tests/image.png instead of http://localstack:4566/tests/image.png

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal s3 mb s3://tests

### Environment

```markdown
- OS: Windows
- LocalStack: latest
```
