### ISSUE TITLE
Persist DynamoDb Streams

### ISSUE THREAD

**Issue by ccorcos** [localstack/localstack#900]
Localstack persists the DynamoDb data, but does not persist the streams configuration. 

The stream configuration is set up when you create or update a table. However, the table info is persisted so the table is already created. Thus you're stuck in an awkward position.

https://github.com/localstack/localstack/issues/519

Temporary workaround is to disable streams and reenable stream every time localstack boots up. Not ideal.

Another idea is just to iterate through the existing DynamoDb tables and set up any streams. That might be easier to implement.

Thanks,

Chet

**Comment by thecherrytree** [comment]
This is still an issue with latest as well? Is there a workaround?

```
PS > aws  dynamodbstreams list-streams --endpoint http://localhost:4570 --region us-east-1       
{
    "Streams": [],
    "LastEvaluatedStreamArn": "TODO"
}
```

**Comment by dolsem** [comment]
Any updates on this? This is pretty crucial for everyone who makes user of DynamoDB Streams in any way.

**Comment by whitelancer** [comment]
I've also run into this problem, and ... I guess there is still no workaround?  I spent a day on this and never could find a solution.

**Comment by dolsem** [comment]
@whitelancer I had to switch to DynamoDB Local which has proper Streams support.

**Comment by whitelancer** [comment]
@dolsem Thanks for the suggestion!  I did play with that for a bit, but must not have got things quite lined up right.  I will investigate some more there.  I appreciate the advice!

**Comment by thecherrytree** [comment]
@dolsem's solution works alright. We were far along enough in our development to just push out to AWS and finish our development there. Our use case case required dynamodb, dynamodb streams, lambda, API gateway, and ses (initially). If I recall correctly, streams was the only issue for us, but those streams were somewhat central to our concept.

**Comment by fabrizio-fal** [comment]
Any update on this? I have the same issue with the latest version (LocalStack release 0.12.17). Please fix.

**Comment by giograno** [comment]
Hi @ccorcos, we pushed some improvements that you can find in the `latest` Docker image. DynamoDB Streams should be now persisted and be available after restarting the container. Could you please confirm us that the problem is solved on your side? Thank you very much.

**Comment by JuanOrtizOvied** [comment]
Any solution on this? I have the same issue with the latest version (LocalStack release 0.14.4.dev). Please fix.

**Comment by JuanOrtizOvied** [comment]
# Steps to reproduce

- MacOS: Monterrey
- Version: 1.4 (21F79)
- docker-compose version 1.29.2, build 5becea4c

> :warning: DyanmoDB table and data persists after restart container but the DynamoDD Streams Don't

### docker-compose.yml

```yml
version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro (DNS)
      - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
      - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    depends_on:
      - elasticsearch
    environment:
      - ES_CUSTOM_BACKEND=http://elasticsearch:9200
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DEBUG=true
      - HOSTNAME_FROM_LAMBDA=localhost
      - LAMBDA_DOCKER_NETWORK=host
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack-data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  elasticsearch-data:
    driver: local
  localstack-data:
    driver: local
```

## Create DynamoDB table

```bash
aws --endpoint-url=http://localhost:4566 dynamodb create-table \     
  --table-name products \
  --attribute-definitions \
    AttributeName=PK,AttributeType=S \
    AttributeName=SK,AttributeType=S \
  --key-schema \
    AttributeName=PK,KeyType=HASH \
    AttributeName=SK,KeyType=RANGE \
  --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
  --stream-specification \
    StreamViewType=NEW_AND_OLD_IMAGES,StreamEnabled=true
```

### The first time, show the streams list

```bash
aws --endpoint-url=http://localhost:4566 dynamodbstreams list-streams
```
![Captura de Pantalla 2022-06-20 a la(s) 9 25 30 a  m](https://user-images.githubusercontent.com/5817795/174623496-0b34c685-ed17-4e59-b02d-a232872609f1.png)

### After restart container

```bash
aws --endpoint-url=http://localhost:4566 dynamodbstreams list-streams
```

![Captura de Pantalla 2022-06-20 a la(s) 9 27 31 a  m](https://user-images.githubusercontent.com/5817795/174623871-9df04a27-fe34-4cd4-8e3e-73133aa52b12.png)
