### ISSUE TITLE
bug: Unable to update stack when deploying through serverless deploy

### ISSUE THREAD

**Issue by timurguvenkaya** [localstack/localstack#9105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deploy to localstack using **serverless deploy** all works well the first time. However, if I make a change to lambda and do serverless deploy again, localstack throws an error on updating the stack 

Error:

```
Environment: darwin, node 18.17.1, framework 3.34.0 (local), plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
UPDATE_FAILED: api-dev (AWS::CloudFormation::Stack)
Resource deployment loop completed, pending resource changes:
```

```yaml
localstack:
    container_name: localstack_main
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

serverless.yml (custom)

```yaml
localstack:
    host: http://127.0.0.1
    stages:
      - dev
      - test
    autostart: false
```
I also use bundle plugin for serverless to bundle everything : https://www.npmjs.com/package/serverless-bundle#externals

### Expected Behavior

Stack should be updated

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

 1. docker compose up 

2. serverless deploy with STAGE set to dev in .env
3. Update lambda
4. do serverless deploy again

### Environment

```markdown
- OS: Macos Ventura M2 -> Version 13.5.1
- LocalStack: latest pro
```
