### ISSUE TITLE
bug: Localstack with mounted lambda on serverless module authorizer not found

### ISSUE THREAD

**Issue by timurguvenkaya** [localstack/localstack#9118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deployed through serverless with mountedCode: true, execution hangs on the authorizer with:

`2023-09-12T10:42:58.016  WARN --- [   asgi_gw_2] l.s.l.i.executor_endpoint  : Execution environment startup failed: {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'tokenApiAuthorizer'\nRequire stack:\n- /var/runtime/index.mjs","trace":["Runtime.ImportModuleError: Error: Cannot find module 'tokenApiAuthorizer'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)","    at async start (file:///var/runtime/index.mjs:1256:23)","    at async file:///var/runtime/index.mjs:1262:1"]}`

New Lambda is constantly created and destroyed 

however when deployed with mountedCode: false -> all works as expected

It is also the case with routes without any authorizer 

serverless.yml

```yaml
custom:
  documentation: ${file(serverless.doc.yml):documentation}
  dotenv:
    path: .env.local
  stage: ${opt:stage, env:STAGE, 'dev'}
  # mountStages:
  #   dev:
  #     mountCode: true
  #   test:
  #     mountCode: false
  localstack:
    host: http://127.0.0.1
    stages:
      - dev
      - test
    lambda:
      mountCode: true
    autostart: true
  bundle:
    linting: false
    tsConfig: "tsconfig.app.json"
    esbuild: true
```

I also tried with autostart: false and separately running docker through docker-compose

### Expected Behavior

Should be executed

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Through serverless directly 

### Environment

```markdown
- OS: macOS M2 Ventura 13.5.1 
- LocalStack: latest
```
