### ISSUE TITLE
bug: Unable to update resource type "AWS::CloudFormation::Stack"

### ISSUE THREAD

**Issue by TheWix** [localstack/localstack#9192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I need to make a change to a stack after it has been deployed LocalStack fails to update the existing stack. There is no error only a warning:
```
2023-09-20 15:00:55 2023-09-20T19:00:55.150 DEBUG --- [cthread11258] l.s.c.e.template_deployer  : Handling "Modify" for resource "MyStackNestedStackResourceC1AB4482" (1/8) type "AWS::CloudFormation::Stack" in loop iteration 1 (should_deploy=True)
2023-09-20 15:00:55 2023-09-20T19:00:55.150  WARN --- [cthread11258] l.s.c.resource_provider    : Unable to update resource type "AWS::CloudFormation::Stack", id MyStackNestedStackResourceC1AB4482"
```

 The only way to resolve the issue is to restart localstack and deploy again.

### Expected Behavior

I expect to be able to update existing resources.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Docker Compose looks like this:

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=0
    #     - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect-brk=0.0.0.0:9229 -p 9229:9229

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

```

1. Init a new CDK project `cdk init sample-app --language python`
2. Start localstack
3. Bootstrap project `cdklocal bootstrap`
4. Deploy project `cdklocal deploy`
5. Make any change to the stack
6. Deploy project again  `cdklocal deploy`

### Environment

```markdown
- OS: Ubuntu 20.04 (Also happens on any version of MacOS)
- LocalStack: 2.2.1.dev
```
