### ISSUE TITLE
bug: Duplicate Event Source Mappings Allowed for SQS and Lambda

### ISSUE THREAD

**Issue by Blind-Striker** [localstack/localstack#9219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

LocalStack allows the creation of multiple identical event source mappings between an SQS queue and a Lambda function without raising any errors. This behavior contrasts with AWS's approach. For instance, in LocalStack, if I repeatedly create a mapping between a specific SQS queue and a Lambda function, each attempt is successful and results in a new, yet identical, event source mapping.

### Expected Behavior

When trying to establish an event source mapping that already exists, LocalStack should raise a `ResourceConflictException`, similar to AWS's behavior. A unique mapping should be defined by its SQS ARN and the associated Lambda function. Duplicate mappings should not be permitted.

**Example:**
```bash
An error occurred (ResourceConflictException) when calling the CreateEventSourceMapping operation: An event source mapping with SQS arn (" arn:aws:sqs:eu-central-1:377140207735:profile-service-demo-queue ") and function (" message-handler-demo ") already exists. Please update or delete the existing mapping with UUID 836dd66d-f542-4844-b020-918b3ac1662d
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

- Create a Lambda function in LocalStack.
- Create an SQS queue in LocalStack.
- Set up an event source mapping between the SQS queue and the Lambda function.
- Attempt to set up the exact event source mapping again. This will succeed without errors, leading to multiple identical mappings.

```yml
version: "3.0"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"

    environment:
      - DEBUG="1"
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_DOCKER_NETWORK=development

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
```

### Environment

```markdown
- OS: Windows
- LocalStack: 2.2.1.dev
```

#### Observations:

- AWS verifies the uniqueness of an event source mapping based on the SQS ARN and the Lambda function.
- In LocalStack, it's currently possible to create an unlimited number of identical event source mappings using the same SQS ARN - and Lambda functions.
