### ISSUE TITLE
bug: The cloud dashboard does not use the instance bookmark for all operations.

### ISSUE THREAD

**Issue by SmashingQuasar** [localstack/localstack#9236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Foreword: We are using the latest pro version of Localstack.

As of today, when opening the resource browser on https://app.localstack.cloud, you can set a custom bookmark in case you are not using the default Localstack networks.

![image](https://github.com/localstack/localstack/assets/11139591/310b9466-1b2d-4a41-a074-f8fb80ebdf83)

This domain is not used by the code everywhere, leading to network failures and impossibility to use the dashboard properly.

![image](https://github.com/localstack/localstack/assets/11139591/124deee2-2ac0-4866-8ece-38b8654d5381)

### Expected Behavior

The minimal expected behaviour would be for the dashboard to exclusively use the provided domain so it can stay functional.

Now, in my opinion, and I have already made this case in another issue, Localstack should not embark a reverse-proxy and attempt to use networking hacks to make domains work locally. This is out of the scope of this library and causes major pain for any DevOps using advanced networking and custom reverse-proxies such as `Traefik`.
As we often say, the road to Hell is paved with good intentions, and this is a perfect example.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

You will at the very least need to setup a custom networking using a reverse-proxy to achieve this.
**It is also paramount that you are familiar with generating a custom certification authority and handling a reverse proxy to work on this issue.**

We are using `traefik` but you can achieve the same results using `nginx` or `HA Proxy` for example.

Here is an excerpt of our `docker-compose.yml` to help you reproduce the issue. You will need to setup `traefik` or your preferred reverse proxy as you see fit and matching your own system configuration to be able to use this `docker-compose.yml`. **It will not work out of the box!**

```yml
version: "3.8"
services:
  traefik:
    container_name: traefik
    restart: unless-stopped
    image: custom/traefik
    build:
      context: ./
      dockerfile: ./services/traefik/Dockerfile
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=https
      - traefik.http.routers.dashboard.rule=Host(`traefik.my-custom-domain.dev`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls
      - traefik.http.services.dashboard.loadbalancer.server.port=8080
    ports:
      - 80:80
      - 443:443
      - 2181:2181
      - 4000:4000
      - 4400:4400
      - 4566:4566
      - 5432:5432
      - 8080:8080
      - 9005:9005
      - 9092:9092
      - 9099:9099
      - 9150:9150
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "./services/traefik/certificates:/etc/traefik/certificates:ro"

  localstack:
    image: custom/localstack
    container_name: localstack
    build:
      context: ./
      dockerfile: ./services/localstack/Dockerfile
    environment:
      - SERVICES=s3,ses,sqs,sns
      - EDGE_BIND_HOST=0.0.0.0
      - S3_USE_HTTPS=0
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/tmp/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_REMOTE_DOCKER=0
      - LAMBDA_DOCKER_NETWORK=host
      - HOST_TMP_FOLDER=/var/lib/localstack/tmp
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
      - PERSISTENCE=1
      - LOCALSTACK_API_KEY=<YOUR_API_KEY>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/docker-volumes/qlip/localstack/lib:/var/lib/localstack
      - ./services/localstack/scripts:/etc/localstack/init/ready.d
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.localstack.service=localstack
      - traefik.http.routers.localstack.rule=Host(`localstack.my-custom-domain.dev`)
      - traefik.http.routers.localstack.entrypoints=https
      - traefik.http.routers.localstack.tls
      - traefik.http.services.localstack.loadbalancer.server.port=443
      - traefik.http.routers.localstack.middlewares=localstack-cors
      - traefik.http.middlewares.localstack-cors.headers.accessControlAllowMethods=GET,OPTIONS,POST,PUT,DELETE
      - traefik.http.middlewares.localstack-cors.headers.accessControlAllowHeaders=Set-Cookie,Cookie,Content-Type,Authorization,x-amz-content-sha256,x-amz-date,x-amz-user-agent
      - traefik.http.middlewares.localstack-cors.headers.accessControlAllowOriginList=https://app.localstack.cloud
      - traefik.http.middlewares.localstack-cors.headers.accessControlAllowCredentials=true
      - traefik.http.middlewares.localstack-cors.headers.accessControlMaxAge=100
      - traefik.http.middlewares.localstack-cors.headers.addVaryHeader=true
      - traefik.http.middlewares.localstack-cors.headers.isDevelopment=true
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: traefik_proxy
```

Here is our `Dockerfile` for `Localstack`:

```dockerfile
FROM localstack/localstack-pro:latest
```

We have initialisation scripts that are used in `Localstack` to create `S3` buckets, `SQS` queues and check the `SES` status but those are unnecessary to reproduce this issue.

### Environment

```markdown
- OS: Debian 12 (Bookworm)
- LocalStack: Localstack Pro (latest version used in the `Dockerfile`).
```

### Anything else?

Generally speaking, it would be much appreciated if the `Localstack` image would abide by the `Docker` best practices of not embedding several services into one image. The integrated reverse-proxy to provide networks is a nice touch for beginners but it severely cripples advanced users. It should be offered as an option instead of by hard-coded within the image.
