### ISSUE TITLE
Discrepancy in Terraform Behavior between Pro and Community

### ISSUE THREAD

**Issue by adinballew** [localstack/localstack#9239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am currently using the Pro Version of Localstack under a trial period. I noticed a discrepancy in behavior between the `localstack/localstack:latest` image and the `localstack/localstack-pro:latest` image. Everything works as expected in the community version (eg the lambda invokes correctly), but it is throwing an exception on the Pro Version. Here is the exception
```
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] time="2023-09-25T19:57:13Z" level=info msg="blocking the credentials service" func="go.amzn.com/lambda/core.(*credentialsServiceImpl).BlockService" file="/home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/core/credentials.go:84"
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] panic: (*logrus.Entry) 0xc00037e2a0
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] goroutine 13 [running]:
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] github.com/sirupsen/logrus.Entry.log({0xc0000c0000, 0xc000378ab0, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x2de
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] github.com/sirupsen/logrus.(*Entry).Log(0xc00037e0e0, 0x0, {0xc000141c20?, 0x0?, 0x98ca00?})
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xa8
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] github.com/sirupsen/logrus.(*Logger).Log(0xc0000c0000, 0x0, {0xc000141c20, 0x1, 0x1})
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x65
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] github.com/sirupsen/logrus.(*Logger).Panic(...)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] github.com/sirupsen/logrus.Panic(...)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] go.amzn.com/lambda/rapid.handleStart({0xc992b8, 0xc00041e240}, 0xc0000f4000, 0x0?, 0xc0000e8630)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/rapid/start.go:473 +0x51a
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] go.amzn.com/lambda/rapid.start({0xc992b8?, 0xc00041e240}, 0xc0000f4000)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/rapid/start.go:688 +0x545
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] go.amzn.com/lambda/rapid.Start(0xc0003800e0)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/rapid/sandbox.go:72 +0xdfe
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] go.amzn.com/lambda/rapidcore.(*SandboxBuilder).Create(0xc00041c2d0)
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/work/lambda-runtime-init/lambda-runtime-init/lambda/rapidcore/sandbox.go:209 +0xf8
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63] created by main.main
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]     /home/runner/work/lambda-runtime-init/lambda-runtime-init/cmd/localstack/main.go:194 +0xa4a
localstack-main | [lambda 2f7eb0e0f504b1c6b96b6f1f84c39b63]
```

### Expected Behavior

The Pro Image would work properly with invoking the lambda as it does in the Community Version.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
docker-compose.yml
```yaml
version: "3.8"

# containers
services:
  # local aws cloud services
  localstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: localstack-main
    environment:
      - LOCALSTACK_API_KEY=xxxxxxx
      - SERVICES=sqs,dynamodb,dynamodbstreams,lambda
      - GATEWAY_LISTEN=0.0.0.0:4566
      - EAGER_SERVICE_LOADING=1
      # AWS Credentials
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # Logging
      - DEBUG=1
      - LS_LOG=debug # debug, info, warn, error, trace, trace-internal
      - SQS_DISABLE_CLOUDWATCH_METRICS=1
      - KINESIS_MOCK_LOG_LEVEL=error
      # Other
      - APP_PATH=$PWD
      - ARCH=x86_64
    ports:
      - "4566:4566" # LocalStack Gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
      - $PWD/tmp/localstack:/tmp/localstack
      - $PWD/terraform:/opt/code/localstack/terraform
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
```

dockerfile
```dockerfile
FROM localstack/localstack:latest

ARG TARGETARCH
ENV ARCH=$TARGETARCH

RUN apt-get update && apt-get install -y \
    jq \
    unzip \
  && rm -rf /var/lib/apt/lists/*

ADD "https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_$TARGETARCH.zip" "terraform_1.5.6_linux_$TARGETARCH.zip"
RUN unzip "terraform_1.5.6_linux_$TARGETARCH.zip" \
  && mv terraform /usr/bin \
  && rm "terraform_1.5.6_linux_$TARGETARCH.zip"

# Install terraform-local
RUN pip install terraform-local
```

init hook
```bash
#!/bin/bash

set -x

# Remove tf state files
rm -r terraform/localstack_providers_override.tf 2>/dev/null
rm -r terraform/terraform.tfstate 2>/dev/null

# Execute terraform commands
cd terraform && \
tflocal init && \
tflocal apply -var "stage=dev" -var "lambda_mount_cwd=$APP_PATH" -auto-approve
```

main.tf
```terraform
provider "aws" {
  access_key                  = "test"
  secret_key                  = "test"
  region                      = var.AWS_REGION
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true

  endpoints {
    cloudformation  = "http://localhost:4566"
    cloudwatch      = "http://localhost:4566"
    dynamodb        = "http://localhost:4566"
    dynamodbstreams = "http://localhost:4566"
    lambda          = "http://localhost:4566"
    s3              = "http://localhost:4566"
    sqs             = "http://localhost:4566"
    iam             = "http://localhost:4566"
  }
}
```

lambda.tf
```terraform
resource "aws_iam_role" "lambda-execution-role" {
  name = "lambda-execution-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

# --------------------------------------
# Lambda Function: calibration-etl-manager
# --------------------------------------
resource "aws_lambda_function" "calibration_etl_manager" {
  s3_bucket = "hot-reload"
  s3_key    = "${var.lambda_mount_cwd}/build"

  function_name = "lambda"
  role          = aws_iam_role.lambda-execution-role.arn
  handler       = "lambda.run"
  runtime       = "python3.9"
  timeout       = var.lambda_etl_timeout

  environment {
    variables = {
      BWAPP_POSTGRES_HOST           = var.master_db_host,
      BWAPP_POSTGRES_PORT           = var.master_db_port,
      BWAPP_POSTGRES_DB_NAME        = var.master_db_name,
      BWAPP_POSTGRES_USERNAME       = var.master_db_user,
      BWAPP_POSTGRES_PASSWORD       = var.master_db_password,
      CALIBRATION_POSTGRES_HOST     = var.calibration_db_host,
      CALIBRATION_POSTGRES_PORT     = var.calibration_db_port,
      CALIBRATION_POSTGRES_DB       = var.calibration_db_name,
      CALIBRATION_POSTGRES_USERNAME = var.calibration_db_user,
      CALIBRATION_POSTGRES_PASSWORD = var.calibration_db_password,
      S3_ENDPOINT_URL               = var.s3_endpoint_url,
      S3_ACCESS_KEY_ID              = "xxxxxx"
      S3_ACCESS_KEY_SECRET          = "xxxxxx"
      S3_REGION_NAME                = var.AWS_REGION,
      S3_CAL_BUCKET_NAME            = module.s3_bucket.bucket_id,
      CALIBRATION_API_URL           = var.calibration_api_url,
      CALIBRATION_ETL_QUEUE_NAME    = aws_sqs_queue.calibration_etl_queue.name,
      BATCH_SIZE                    = "10",
    }
  }
 ```
 
 ```python
 import boto3
import logging
import os

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logging.getLogger().setLevel(logging.INFO)


def _getenv(name):
	return os.getenv(name)

queue_name = _getenv('QUEUE_NAME')
region_name = _getenv('AWS_REGION')

endpoint_url = None
if _getenv("LOCALSTACK_HOSTNAME"):
	endpoint_url = f'http://{_getenv("LOCALSTACK_HOSTNAME")}:{_getenv("EDGE_PORT")}'

sqs = boto3.resource(
	'sqs',
	endpoint_url=endpoint_url,
	region_name=region_name
)

queue = sqs.get_queue_by_name(QueueName=queue_name)

def run(event, context):
    # code goes here
    logging.info(event)
```

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest
```
