### ISSUE TITLE
bug: AppSync error "Unsupported AppSync DynamoDB template operation f\"None\""

### ISSUE THREAD

**Issue by andrew-sol** [localstack/localstack#9265]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

All GraphQL queries to resolvers that use DynamoDB tables as data sources fail with the following response:
```json
{
    "data": {},
    "errors": [
        {
            "message": "Unsupported AppSync DynamoDB template operation f\"None\"",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "users"
            ],
            "errorType": "Exception"
        }
    ]
}
```

**The same configuration deploys to AWS and works without any issues.** Tested in Insomnia and Postman.

### Expected Behavior

GraphQL queries do not return errors.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)
```sh
DYNAMODB_SHARE_DB=1 localstack start
```

### Environment

```markdown
- OS: macOS 13.4.1 (22F82)
- LocalStack: 2.2.0
```

### Anything else?

serverless.yml (`sls print` output):
```yml
service: api
frameworkVersion: ^3.15
configValidationMode: error
plugins:
  - serverless-esbuild
  - serverless-localstack
  - serverless-appsync-plugin
provider:
  name: aws
  runtime: nodejs18.x
  stage: local
  region: eu-central-1
  deploymentMethod: direct
  environment:
    NODE_ENV: local
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:eu-central-1:*:*
  versionFunctions: true
functions:
  onSignUp:
    handler: src/modules/user/functions/on-sign-up/handler.main
    events: []
    name: api-local-onSignUp
package:
  individually: true
  artifactsS3KeyDirname: serverless/api/local/code-artifacts
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node18
    define: {}
    platform: node
    concurrency: 10
  localstack:
    stages:
      - local
  dynamodbTableName: local-main
  cognitoUserPoolName: api-local-user-pool
  cognitoIdentityPoolName: api-local-identity-pool
appSync:
  name: local-appsync-api
  logging:
    enabled: true
    level: ALL
  authentication:
    type: API_KEY
  apiKeys:
    - appsync_api_key
  additionalAuthentications:
    - type: AMAZON_COGNITO_USER_POOLS
      config:
        userPoolId:
          Ref: AppUserPool
  schema: schema.graphql
  dataSources:
    usersTableDS:
      type: AMAZON_DYNAMODB
      description: users table
      config:
        tableName: local-users
    lambda:
      type: AWS_LAMBDA
      config:
        function:
          timeout: 30
          handler: src/modules/appsync/functions/lambda-resolver/handler.main
  resolvers:
    Query.getUser:
      functions:
        - dataSource: usersTableDS
          code: src/modules/user/resolvers/get-user.ts
    Query.users:
      functions:
        - dataSource: usersTableDS
          code: src/modules/user/resolvers/users.ts
  pipelineFunctions: {}
resources:
  Resources:
    AppUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: api-local-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            RequireUppercase: true
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
        LambdaConfig:
          PostConfirmation:
            Fn::GetAtt:
              - OnSignUpLambdaFunction
              - Arn
    AppUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: api-local-user-pool-client
        UserPoolId:
          Ref: AppUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: local-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
  Outputs:
    UserPoolClientId:
      Value:
        Ref: AppUserPoolClient
      Export:
        Name: local-UserPoolClientId
```

schema.graphql:
```graphql
schema {
  query: Query
}

type Query {
  getUser(id: ID!): User
  users(limit: Int, nextToken: String): PaginatedUsers!
}

type User {
  id: ID!
  createdAt: String!
  email: String!
}

type PaginatedUsers {
  users: [User!]!
  nextToken: String
}
```

`get-user.ts` resolver:
```ts
import { util } from '@aws-appsync/utils';

export const request = (ctx) => {
  return {
    operation: 'GetItem',
    key: util.dynamodb.toMapValues({ id: ctx.args.id }),
  };
};

export const response = (ctx) => ctx.result;
```

`users.ts` resolver:
```ts
export const request = (ctx) => {
  const { limit = 20, nextToken } = ctx.args;

  return {
    operation: 'Scan',
    limit,
    nextToken,
  };
};

export const response = (ctx) => {
  const { items: users = [], nextToken } = ctx.result;

  return { users, nextToken };
};
```

Example GraphQL queries:
```graphql
query GetUser {
    getUser(id: "qweasd") {
        id
        email
    }
}
```
```graphql
query GetUsers {
    users {
        nextToken
        users {
            id
            createdAt
            email
        }
    }
}
```
