### ISSUE TITLE
bug: Result of `sqs list-queue` differs from 2.2.0 to 2.3.0

### ISSUE THREAD

**Issue by pocari** [localstack/localstack#9301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws sqs list-queues --endpoint http://localhost:54566
#=> No response. However, the console on the localstack side shows the log of accepted requests.
#   localstack-check-localstack-1  | 2023-10-06T06:18:45.923  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS sqs.ListQueues => 200
```

### Expected Behavior

```
AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws sqs list-queues --endpoint http://localhost:54566
{
    "QueueUrls": [
        "http://localhost:54566/000000000000/my-sample-queue"
    ]
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml
```
version: '3.7'

services:
  localstack:
    # The behavior here changes depending on the version.
    # image: localstack/localstack:2.2
    image: localstack/localstack:2.3.0
    ports:
      - 54566:4566
    environment:
      SERVICES: sqs
      DEFAULT_REGION: ap-northeast-1
    volumes:
      - ./ready.d:/etc/localstack/init/ready.d
```

./ready.d/setup.sh
```
#!/bin/bash

awslocal sqs create-queue --queue-name=my-sample-queue
```

and run

`docker compose up`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

from docker host

```
AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test aws sqs list-queues --endpoint http://localhost:54566
```

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS 
- LocalStack: 2.3.0
```

### Anything else?
The following reproducible repositories summarize what we have so far.

https://github.com/pocari/localstack-2.3.0-check
