### ISSUE TITLE
Persistance with localstack using Cloud Pods

### ISSUE THREAD

**Issue by prometek** [localstack/localstack#9307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run localstack on a docker container and I want to make my S3 buckets data to persist. 
I know that persistence is coming only with pro edition, so I tried using cloud pods instead. 
I tried to implement it following the following response in a previous issue:

```yaml
version: "3.0"
services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:2.2.0
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
      - DEBUG=0
      - PERSISTENCE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./boot.sh:/etc/localstack/init/boot.d/boot.sh
      - ./ready.sh:/etc/localstack/init/ready.d/ready.sh
      - ./shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh
      - localstack_pods:/pods

volumes:
  localstack_pods:
``` 

./boot.sh
```sh
#!/bin/bash

set -euo pipefail

if ! test -f /opt/code/localstack/bin/localstack-cli; then
  echo "Installing global localstack cli"

  tmp_dir=$(mktemp -d)

  curl -s -L https://github.com/localstack/localstack-cli/releases/download/v2.2.0/localstack-cli-2.2.0-linux-amd64-onefile.tar.gz | tar xvzf - -C "$tmp_dir"
  mv "$tmp_dir/localstack" /opt/code/localstack/bin/localstack-cli

  rm -rf "$tmp_dir"
fi
```

./ready.sh
```sh
#!/bin/bash

set -euo pipefail

FILE="/pods/main"

if [[ -f "$FILE" && "${PERSISTENCE:-0}" == 1 ]]; then
  echo "Restoring from pod"

  /opt/code/localstack/bin/localstack-cli pod load file://${FILE}
else
  echo "No pod state found"
fi
```

./shutdown.sh
```sh
#!/bin/bash

set -euo pipefail

if [[ "${PERSISTENCE:-0}" == 1 ]]; then
  echo "Saving to pod"

  /opt/code/localstack/bin/localstack-cli pod save file:///pods/main
fi
```

_Originally posted by @lainosantos in https://github.com/localstack/localstack/issues/6281#issuecomment-1668171870_
          

However I get the following error when my docker container shutdown:
`Error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))  `

It seems that localstack is already disconnected when save run.

Does anyone has a clue on why I cannot save when docker shutdown ?

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

My docker-compose file:

```yaml
localstack:
    image: localstack/localstack:2.2.0
    stop_grace_period: 5m
    environment:
      - SERVICES=s3
      - DOCKER_SOCK=/var/run/docker.sock
      - DEBUG=0
      - PERSISTENCE=1
    ports:
      - "4566-4599:4566-4599"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/localstack/boot.sh:/etc/localstack/init/boot.d/boot.sh
      - ./scripts/localstack/ready.sh:/etc/localstack/init/ready.d/ready.sh
      - ./scripts/localstack/shutdown.sh:/etc/localstack/init/shutdown.d/shutdown.sh
      - localstack_pods:/pods
```

### Environment

```markdown
- OS:Ubuntu 22.04
- LocalStack:2.2.0
```
