### ISSUE TITLE
bug: Localstack Lambda invokes HTTPS POST request 404 error

### ISSUE THREAD

**Issue by lqtruong** [localstack/localstack#9351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I ran a docker-compose command to start `localstack-pro` and when I invoked a Lambda function, in turn, the Lambda function invokes an HTTPs request to external site e.g `https://appid.appsync-api.eu-central-1.amazonaws.com/graphql`. 

There was error that occurred as below
```js
2023-10-14 13:56:39 werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2023-10-14 13:56:39 
2023-10-14 13:56:39 The above exception was the direct cause of the following exception:
```
And then
```js
'localstack.aws.protocol.parser.OperationNotFoundParserError: Unable to find operation for request to service appsync: POST
```
Futher, i opened my Lambda container and go to its terminal. I tried the curl
```js
curl --location 'https://appid.appsync-api.eu-central-1.amazonaws.com/graphql' \
--header 'x-api-key: apikey' \
--header 'Content-Type: application/json' \
--data-raw '{
  "query":"query MyQuery($email: String!) {\n  testCallHttp(\n    email: $email)\n}",
  "variables": {
    "email":"myemail""
  },
  "operationName":"MyQuery"
}
'
```
And I got this error
```js
curl: (60) SSL: no alternative certificate subject name matches target host name 'appid.appsync-api.eu-central-1.amazonaws.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Interestingly, when I stand at the root `localstack_main` docker container host, the curl is working well. No issues complaint on SSL/TLS HTTPs certificate.

My docker-compose.yml
```yaml
services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack-pro:latest
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
      - '127.0.0.1:443:443'
      - '127.0.0.1:53:53'
      - '127.0.0.1:53:53/udp'
    environment:
      - DEBUG=1
      - SERVICES=lambda,dynamodb,sns,sqs
      - PERSISTENCE=${PERSISTENCE-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=30
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
```

Can you help to check if I missed any configuration for Lambda function container initialization in order to invoke an HTTPS POST request to outside of Lambda docker container via `localstack` ? Thank you very much

### Expected Behavior

`lambda function` container can call HTTPS POST to outside from `localstack` docker host without any complaints about SSL/TLS

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Inside a Lambda function, we use `axios` library to call HTTPS POST to site `https://appid.appsync-api.eu-central-1.amazonaws.com/graphql`

```js
const external_https_url = 'https://appid.appsync-api.eu-central-1.amazonaws.com/graphql';
const query = `query MyQuery($email: String!) {\n  testCallHttp(\n    email: $email)\n}"`;
const queryVariables = {"email":"myemail"};
const resp = await axios.post(
    `${external_https_url}`,
    {
      query,
      variables: queryVariables
    },
    {
      headers: {
        'x-api-key': apiKey
      }
    }
  );
```

### Environment

```markdown
- OS: MacOS Monterey
- LocalStack: version 2.2.0
```

### Anything else?

<img width="1158" alt="Screen Shot 2023-10-12 at 18 51 03" src="https://github.com/localstack/localstack/assets/37399174/e0204b91-aa7a-455b-b3b0-8e0322ccdac3">
