### ISSUE TITLE
bug: Error when executing and describing stepfunction execution on localstack:2.3.0 with new StepFunction provider

### ISSUE THREAD

**Issue by ayeganyan-atl** [localstack/localstack#9369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting execution of the step function I am getting the following errors in logs:
```
2023-10-17 13:30:55 2023-10-17T11:30:55.440 ERROR --- [ad-17 (eval)] l.s.s.a.c.eval_component   : Exception '<class 'localstack.services.stepfunctions.asl.component.common.error_name.failure_event.FailureEventException'>':'' at '[ASL] [gene] [StateTaskServiceAwsSdk]: '(StateTaskServiceAwsSdk| {'comment': None, 'input_path': (InputPath| {'input_path_src': '$'}), 'output_path': (OutputPath| {'output_path': '$'}), 'state_entered_event_type': 'TaskStateEntered', 'state_exited_event_type': 'TaskStateExited', 'result_path': None, 'result_selector': None, 'retry': None, 'catch': None, 'timeout': (TimeoutSeconds| {'timeout_seconds': 99999999, 'is_default': None}), 'heartbeat': None, 'parameters': (Parameters| {'payload_tmpl': (PayloadTmpl| {'payload_bindings': [(PayloadBindingValue| {'field': 'StreamArn', 'value': (PayloadValueStr| {'val': 'arn:aws:dynamodb:ap-south-1:000000000000:table/dx-ref-java-quarkus-im-dynamo/stream/2023-10-17T09:47:14.063'})})]})}), 'name': 'DescribeStream', 'state_type': <StateType.Task: 15>, 'continue_with': <localstack.services.stepfunctions.asl.component.state.state_continue_with.ContinueWithEnd object at 0xffff77771e90>, 'resource': (ServiceResource| {'resource_arn': 'arn:aws:states:::aws-sdk:dynamodbstreams:describeStream', 'partition': 'aws', 'region': 'us-east-1', 'account': '', 'service_name': 'aws-sdk', 'api_name': 'dynamodbstreams', 'api_action': 'describeStream', 'condition': None}), '_normalised_api_name': 'dynamodbstreams', '_normalised_api_action': 'describe_stream'})'.'
```

If I describe the execution, I am getting the following response (even response is 200 in the logs):
```json
{
    "executionArn": "arn:aws:states:ap-south-1:000000000000:execution:my-project.step-functions.dynamodb-stream-describe:cf47d2cc-8599-4395-b496-97e884ce23fb",
    "stateMachineArn": "arn:aws:states:ap-south-1:000000000000:stateMachine:my-project.step-functions.dynamodb-stream-describe",
    "name": "cf47d2cc-8599-4395-b496-97e884ce23fb",
    "status": "FAILED",
    "startDate": 1697542255.430311,
    "stopDate": 1697542255.440563,
    "input": "{}",
    "inputDetails": {
        "included": true
    },
    "error": "DynamoDBStreams.ResourceNotFoundException",
    "cause": "Stream arn:aws:dynamodb:ap-south-1:000000000000:table/dx-ref-java-quarkus-im-dynamo/stream/2023-10-17T09:47:14.063 was not found. (Service: DynamoDBStreams, Status Code: 400, Request ID: ed5d8af4-0087-4865-ae29-f74c95164abe)"
}
```

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose.yml`
```yaml
version: "3"
services:
  localstack:
    image: "localstack/localstack:2.3.0"
    ports:
     - "4566"
    environment:
      AWS_ACCESS_KEY_ID: "localAccessKeyId"
      AWS_SECRET_ACCESS_KEY: "localSecretAccessKey"
      DEBUG: "1"
      DISABLE_EVENTS: "1"
      PROVIDER_OVERRIDE_S3: "v3"
      PROVIDER_OVERRIDE_STEPFUNCTIONS: "v2"
      SKIP_SSL_CERT_DOWNLOAD: "1"
      SQS_DISABLE_CLOUDWATCH_METRICS: "1"
    volumes:
     - "./commands:/etc/localstack/init/ready.d"
     - "./dynamodbstream-statemachine.json:/my-project/dynamodbstream-statemachine.json"
```
`commands/resource-config-commands.sh`
```sh
#!/usr/bin/env bash

# Create resources
aws --region ap-south-1 --endpoint-url http://localstack:4566 dynamodb create-table --table-name dx-ref-java-quarkus-im-dynamo --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --stream-specification StreamEnabled=true,StreamViewType=NEW_AND_OLD_IMAGES
aws --region ap-south-1 --endpoint-url http://localstack:4566 dynamodb update-time-to-live --table-name dx-ref-java-quarkus-im-dynamo --time-to-live-specification 'Enabled=true, AttributeName=ttl'
aws --region ap-south-1 --endpoint-url http://localstack:4566 stepfunctions create-state-machine --name my-project.step-functions.dynamodb-stream-describe --definition file:///my-project/dynamodbstream-statemachine.json --role-arn arn:aws:iam::000000000000:role/DummyRole --query "stateMachineArn"
```

`dynamodbstream-statemachine.json`
```json
{
  "Comment": "A description of my state machine",
  "StartAt": "DescribeStream",
  "States": {
    "DescribeStream": {
      "Type": "Task",
      "End": true,
      "Parameters": {
        "StreamArn": "arn:aws:dynamodb:ap-south-1:000000000000:table/dx-ref-java-quarkus-im-dynamo/stream/2023-10-17T09:47:14.063"
      },
      "Resource": "arn:aws:states:::aws-sdk:dynamodbstreams:describeStream"
    }
  }
}
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
```sh
STATE_MACHINE_ARN=arn:aws:states:ap-south-1:000000000000:stateMachine:my-project.step-functions.dynamodb-stream-describe
EXECUTION_ARN=$(aws --region ap-south-1 --endpoint-url http://localstack:4566 stepfunctions start-execution --state-machine-arn "$STATE_MACHINE_ARN" --output text --query executionArn)
aws --region ap-south-1 --endpoint-url http://localstack:4566 stepfunctions describe-execution --execution-arn "$EXECUTION_ARN"
```

### Environment

```markdown
- OS: MacOS 13.6 (22G120) / M1
- LocalStack: 2.3.0
```
