### ISSUE TITLE
enhancement request: Support dynamic port on Lambda remote debugging

### ISSUE THREAD

**Issue by yamadayutaka** [localstack/localstack#9419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

After the following remote debugging configuration, multiple Lambda Function executions will cause port conflicts, so allow dynamic port specification.

https://docs.localstack.cloud/user-guide/tools/lambda-tools/debugging/#debugging-nodejs-lambdas

### 🧑‍💻 Implementation

Change the behavior to use dynamic ports when 0 is specified as the host port.

```yaml
#docker-compose.yml

services:
  localstack:
    ...
    environment:
      ...
      - LAMBDA_DOCKER_FLAGS=-e NODE_OPTIONS=--inspect-brk=0.0.0.0:9229 -p 0:9229
```

### Anything else?

I have a solution and create a PR https://github.com/localstack/localstack/pull/9420.
