### ISSUE TITLE
bug: SQS queue name defaults to region in Resource Browser

### ISSUE THREAD

**Issue by iyoung-tixr** [localstack/localstack#9532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I create an SQS queue in the LocalStack Web Application, I can see it in the list.  However, the value in the Name column is the name of the region.  If I click on that, I get a "the specified queue does not exist for this wsdl version" error, understandably, because there is no queue by that name.  If I change the URL in the browser's address bar to reflect the actual queue name, it displays the queue's details without any error.

### Expected Behavior

The link in the list of queues should show the queue name, not the region name.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    Open the LocalStack Web Application and go to Resource Browser -> SQS.  Create a queue and, when the new queue appears in the list, click on it.

### Environment

```markdown
- OS: macOS Ventura 13.5
- LocalStack: 2.3.2
- LocalStack Web Application: 0.3.1
```

### Anything else?

<img width="1308" alt="Screenshot 2023-11-01 at 19 20 53" src="https://github.com/localstack/localstack/assets/117106195/5ad51b5a-83bb-4c17-99aa-d0d6e165d94b">
<img width="1319" alt="Screenshot 2023-11-01 at 19 21 08" src="https://github.com/localstack/localstack/assets/117106195/025866a6-bf66-426c-8a2c-06a0912ce534">

Simplified docker-compose.yml for reference:
```yaml
version: '3.7'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    dns:
      - 172.20.0.20
    networks:
      tixr:
        ipv4_address: 172.20.0.20
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
      - 8000:4566
    environment:
      - DEBUG=${DEBUG-}
      - SQS_ENDPOINT_STRATEGY=path
      - MAIN_CONTAINER_NAME=localstack
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_ACCESS_KEY=test
networks:
  tixr:
    name: tixr
    ipam:
      config:
        - subnet: 172.20.0.0/24
```
