### ISSUE TITLE
S3 Presigned URL is not expiring with Localstack version >= 0.13.1

### ISSUE THREAD

**Issue by manoj-fd** [localstack/localstack#9538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am testing a scenario where Presigned url should expire after x seconds based on the value i am setting in `generatePresignedUrlRequest.setExpiration( expiration )`

Currently the url generated is expiring as expected with localstack version `0.13.0`, however when i tried to upgrade the local stack version to `> 0.13.0 or any 1.x  or any 2.x` , the test is not working  and the s3 Presigned URL is not getting expired.

Also when i checked with backward versions, i found that the url is expired as expected with versions `> 0.12.10` and not working with `0.12.0`

### Expected Behavior

Expecting an consistent behaviour with latest localstack versions.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

- Generate a s3 Presigned URL
- Set expiration

```
final GeneratePresignedUrlRequest generatePresignedUrlRequest = new GeneratePresignedUrlRequest(
					bucketName, objectKey );
			generatePresignedUrlRequest.setMethod( HttpMethod.GET );
			generatePresignedUrlRequest.setExpiration( expiration );
			final URL url = s3Client.generatePresignedUrl( generatePresignedUrlRequest );

			return Optional.ofNullable( url.toString() );

```

Verification

Try Accessing that url in Browser

### Environment

```markdown
OS: macOS Monterey
LocalStack: v 2.3.0
```

**Comment by bentsku** [comment]
Hello @manoj-fd and thanks for your report. In LocalStack version > `2.0`, S3 pre-signed URL validation is only opt-in, to avoid issues. You can enforce S3 pre-signed request validation with `S3_SKIP_SIGNATURE_VALIDATION=0`. See our documentation about configuration here: https://docs.localstack.cloud/references/configuration/#s3

**Comment by manoj-fd** [comment]
@bentsku  Thanks for the quick response, Could you please help me to understand where exactly i need to add this validation **S3_SKIP_SIGNATURE_VALIDATION=0**

**Comment by bentsku** [comment]
It will depend on how do you start LocalStack:
- if you use the cli, you can use it this way: `S3_SKIP_SIGNATURE_VALIDATION=0 localstack start`
- or in docker compose, you would need to add it to the `environment` list in your `docker-compose.yaml` file.
example: https://github.com/localstack/localstack/blob/master/docker-compose.yml
```yml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - S3_SKIP_SIGNATURE_VALIDATION=0
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Feel free to share how you are using LocalStack and I can help you further!
