### ISSUE TITLE
bug: User Pool Clients with custom IDs cannot be setup

### ISSUE THREAD

**Issue by Phxntxm** [localstack/localstack#9550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ID is randomized, name is just set exactly to the name it's given:

![image](https://github.com/localstack/localstack/assets/3664828/067b112a-684c-4e1d-b6af-f0a70985d43b)
(This is following the instructions here: https://docs.localstack.cloud/user-guide/aws/cognito/#using-predefined-ids-for-pool-creation)

### Expected Behavior

The Client ID is set to `thioepwqhtiopepwhqitewqiot` in the example given

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

`docker-compose up -d localstack`
Compose yaml file:
```
  localstack:
    image: localstack/localstack-pro:2.3.2
    environment:
      - PERSISTENCE=1
      - DISABLE_CORS_CHECKS=1
      - LOCALSTACK_API_KEY=<my_api_key>
      - USER_POOL_ID=${USER_POOL_ID:-}
      - USER_POOL_WEB_CLIENT_ID=${USER_POOL_WEB_CLIENT_ID:-}
      - USER_POOL_AUTH_DOMAIN=${USER_POOL_AUTH_DOMAIN:-}
      - INITIAL_USER_EMAIL=${INITIAL_USER_EMAIL:-}
      - INITIAL_USER_PASSWORD=${INITIAL_USER_PASSWORD:-}
      - INITIAL_USER_GIVEN_NAME=${INITIAL_USER_GIVEN_NAME:-}
      - INITIAL_USER_FAMILY_NAME=${INITIAL_USER_FAMILY_NAME:-}
    ports:
      - 4566:4566
```
.env file:
```
USER_POOL_ID=us-east-1_mypool123
USER_POOL_WEB_CLIENT_ID=myclient123
USER_POOL_AUTH_DOMAIN=https://localhost.localstack.cloud:4566/_aws/cognito-idp
INITIAL_USER_EMAIL=<myemail>
INITIAL_USER_PASSWORD=Password123!
INITIAL_USER_GIVEN_NAME=Dan
INITIAL_USER_FAMILY_NAME=Hess
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
# I do this inside the container, to mimic using a startup script 
`docker compose exec localstack bash`
`awslocal cognito-idp create-user-pool --pool-name CUP --user-pool-tags "_custom_id_=${USER_POOL_ID}"`
`awslocal cognito-idp create-user-pool-client --user-pool-id ${USER_POOL_ID} --client-name _custom_id_:${USER_POOL_WEB_CLIENT_ID}`

### Environment

```markdown
- OS: Ubuntu 23.04
- LocalStack: image: localstack/localstack-pro:2.3.2
```
