### ISSUE TITLE
bug: Parameter type ignored when passed to NestedStacks

### ISSUE THREAD

**Issue by lukasz-mazur2** [localstack/localstack#9558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears that parameters passed down to a Nested Stack are always treated as a string.

Template:
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RDSDevMysql:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://standard-common-modules.s3.localhost.localstack.cloud:443/templates/cloudformation-rds/4/0/cloudformation-rds-v4.0.1.yaml
      Parameters:
        ResourceNamePrefix: !Sub ${AWS::StackName}-dev-mysql
        Mode: dev
        Engine: mysql-8
        MasterUsername: testadmin
        VpcId: vpc-db9885d5
        SubnetIds: subnet-4f49ee6b,subnet-d560b0cb,subnet-c4723f8f
```

What nested stack template is expecting:
```
  SubnetIds:
    Type: CommaDelimitedList
```

Inside the rds nested stack template we use a [PyPlate macro](https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/PyPlate) and in its logs I can see that `SubnetIds` are a single string:

```
(...)
 "transformId":"000000000000::PyPlate",
   "params":{
      
   },
   "requestId":"021c8704-d328-4b55-a55a-8949a0ec322a",
   "templateParameterValues":{
      "ResourceNamePrefix":"rds-test-dev-mysql",
      "Mode":"dev",
      "Engine":"mysql-8",
      "MasterUsername":"testadmin",
      "VpcId":"vpc-db9885d5",
      "SubnetIds":"subnet-4f49ee6b,subnet-d560b0cb,subnet-c4723f8f",                     <---------------- single string
      "BackupRegion":"eu-central-1",
      "MysqlSlowQueryTime":5,
(...)
```

### Expected Behavior

This is how it looks on AWS:
```
(...)
 "transformId":"000000000000::PyPlate",
   "params":{
      
   },
   "requestId":"2de8a855-7e00-49c2-94fb-2b3e5959b7bd",
   "templateParameterValues":{
      "ResourceNamePrefix":"rds-test-dev-mysql",
      "Mode":"dev",
      "Engine":"mysql-8",
      "MasterUsername":"testadmin",
      "VpcId":"vpc-db9885d5",
      "SubnetIds": [
          "subnet-4f49ee6b",                  <------\
          "subnet-d560b0cb",                  <------->------ list
          "subnet-c4723f8f"                   <------/
      ],
      "BackupRegion":"eu-central-1",
      "MysqlSlowQueryTime":5,
(...)
```

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
docker run \
--rm \
--name localstack_main \
-p 4566:4566 \
-p 4510-4559:4510-4559 \
-e LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY \
-e PERSISTENCE=0\
-e LS_LOG=trace \
-e SNAPSHOT_LOAD_STRATEGY=ON_STARTUP \
-v ./localstack-volume:/var/lib/localstack \
-v /var/run/docker.sock:/var/run/docker.sock \
    localstack/localstack-pro
```
#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    awslocal cloudformation create-stack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --stack-name rds-test --template-body file://template.yaml && awslocal cloudformation wait stack-create-complete --stack-name rds-test

### Environment

```markdown
- OS: 5.15.90.1-microsoft-standard-WSL2
- LocalStack: 2.3.3.dev20231010111126
```

**Comment by lukasz-mazur2** [comment]
Another example from different template.

```
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Default: vpc-db9885d5

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: private-zone-sg-test-for-ingress
      GroupDescription: Test security group
      VpcId: !Ref VPC
  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:  private-zone-sg-test-for-ingress-source
      GroupDescription: Test source security group
      VpcId: !Ref VPC
  IngressCIDR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: http://standard-common-modules.s3.localhost.localstack.cloud:443/templates/cloudformation-private-zone-sg-ingress/1/0/cloudformation-private-zone-sg-ingress-v1.0.3.yaml
      Parameters:
        ResourceNamePrefix: sg-cidr
        GroupID: !GetAtt SecurityGroup.GroupId
        IPProtocol: tcp
        CIDR: 0.0.0.0/0
        From: 6000
        To: 7000
```

Results in Nested Stack parameter validation error:

`Parameter validation failed: Invalid type for parameter FromPort, value: 6000, type: <class 'str'>, valid types: <class 'int'> Invalid type for parameter ToPort, value: 7000, type: <class 'str'>, valid types: <class 'int'> Invalid type for parameter IpPermissions[0].FromPort, value: 6000, type: <class 'str'>, valid types: <class 'int'> Invalid type for parameter IpPermissions[0].ToPort, value: 7000, type: <class 'str'>, valid types: <class 'int'>`
