### ISSUE TITLE
default s3 buckets setup with docker 

### ISSUE THREAD

**Issue by sureshamk** [localstack/localstack#959]
Is there any way to specify a bunch of s3 buckets while starting localstack through a config file ?

**Comment by svnv** [comment]
You can use the `/docker-entrypoint-initaws.d`described here https://github.com/localstack/localstack#initializing-a-fresh-instance

If you use docker-compose you can define localstack like this in your `docker-compose.yml`

```yml
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    volumes:
      - './my_localstack_init:/docker-entrypoint-initaws.d'
```

And then you can add a file `./my_localstack_init/s3.sh`

```sh
#!/bin/sh
echo "Init localstack s3"
awslocal s3 mb s3://checkout_profiles_bucket
```
