### ISSUE TITLE
bug: Provisioned Lambda instances do not get used - a new Lambda instance is created instead.

### ISSUE THREAD

**Issue by RowlandBanks** [localstack/localstack#9658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have deployed a Lambda in LocalStack 2.3.2 and configured Provisioned Concurrency to have 2 instances. 

LocalStack correctly starts up 2 instances.

I invoke the Lambda and LocalStack spawns a new Lambda instance and uses the new instance for processing.

### Expected Behavior

I expect LocalStack to use one of the existing provisioned instances, rather than spawning a new instance.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Create the following files in a single folder, then run the commands below.

Dockerfile:
```dockerfile
# Build a lambda function in C# that will write to the console.
FROM mcr.microsoft.com/dotnet/sdk:6.0 as dotnet

RUN apt update
RUN apt install -y zip

WORKDIR /app
COPY Lambda.csproj Lambda.csproj
COPY Program.cs Program.cs
RUN dotnet publish Lambda.csproj -c Release --output publish

RUN cd publish && \
    zip -r /app/publish/deployment-archive.zip . && \
    cd ..

# Now copy the deployment archive containing the C# application to a
# new image based on LocalStack.
FROM localstack/localstack:2.3.2 AS localstack
RUN mkdir /app
COPY --from=dotnet /app/publish/deployment-archive.zip /app/deployment-archive.zip
```

docker-compose.yml
```yml
version: "3.9"
services:
  aws:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    expose: # Expose ports to other containers running in the same compose instance.
      - "4566"
    networks:
      - docker_network
    environment:
      - DEBUG=1
      - LS_LOG=trace
      - LAMBDA_DOCKER_NETWORK=my_docker_network
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker/output/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - .:/app/code

networks:
  docker_network:
    name: my_docker_network
    # We have to name this network, to permit the `LAMBDA_DOCKER_NETWORK` env var to be set.
    driver: bridge
```

Lambda.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.8.4" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.3.0" />
  </ItemGroup>

</Project>
```

Program.cs
```c#
using Amazon.Lambda.RuntimeSupport;

int numberOfExecutions = 0;

Func<Task> handler = () =>
{
    Console.WriteLine($"This is Execution #{++numberOfExecutions}");
    return Task.CompletedTask;
};

await LambdaBootstrapBuilder.Create(handler)
    .Build()
    .RunAsync();
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```bash
host$> docker-compose up -d --build --remove-orphans --force-recreate
host$> docker-compose exec -it aws /bin/bash

mkdir ~/.aws

cat << EOF > ~/.aws/config 
[default] 
aws_access_key_id=foo 
aws_secret_access_key=bar 
region=us-east-1 
EOF

location="--endpoint-url http://localhost:4566/ --no-verify-ssl"
deploymentBucket=deployment-bucket
lambda=my-test-lambda

aws s3api create-bucket $location --bucket $deploymentBucket

aws s3api put-object $location \
    --bucket $deploymentBucket \
    --key deployment-archive.zip \
    --body /app/deployment-archive.zip

aws lambda create-function $location \
    --handler "Lambda" \
    --function-name $lambda \
	--role arn:aws:iam::000000000000:role/lambda_roles/my-test-lambda \
    --code=S3Bucket=$deploymentBucket,S3Key=deployment-archive.zip --runtime dotnet6

aws lambda publish-version --function-name $lambda $location
aws lambda put-provisioned-concurrency-config --function-name $lambda --qualifier 1 --provisioned-concurrent-executions 2 $location
aws lambda list-provisioned-concurrency-configs --function-name $lambda  $location

aws lambda invoke --function-name $lambda $location /app/out.txt
```

### Environment

```markdown
- OS: Windows + WSL2 + Docker
- LocalStack: 2.3.2
```

### Anything else?

Ultimately, my aim is to execute multiple instances of a Lambda concurrently - so if there is another way to achieve this, that would be useful information too.
