### ISSUE TITLE
bug: ERROR : "'NoneType' object has no attribute 'copy'"

### ISSUE THREAD

**Issue by jr-araujo** [localstack/localstack#9675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there,

I've been trying to use the latest version of localstack 3.0.0 and I got an issue while deploying a very new fresh stack, after a while I deleted this stack, and then I tried to re-deploy the same stack again (after deletion), I saw that the stack was not created and looking into the described logs of the cloudformation stack I could find the **StackStatusReason** with this message: "'NoneType' object has no attribute 'copy'"

You can find below the output from `awslocal cloudformation describe-stacks`

{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/infra-s3-sqs-sns/6096e3f5",
            "StackName": "infra-s3-sqs-sns",
            "ChangeSetId": "arn:aws:cloudformation:us-east-1:000000000000:changeSet/awscli-cloudformation-package-deploy-1700223721/7b36d504",
            "Description": "Created by AWS CLI at 2023-11-17T12:19:18.437930 UTC",
            "CreationTime": "2023-11-17T12:19:18.940000Z",
            "DeletionTime": "2023-11-17T12:21:38.811000Z",
            "LastUpdatedTime": "2023-11-17T12:19:18.940000Z",
            "RollbackConfiguration": {},
            "StackStatus": "CREATE_FAILED",
            "StackStatusReason": "'NoneType' object has no attribute 'copy'",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Outputs": [
                {
                    "OutputKey": "S3BucketOutput",
                    "OutputValue": "s3-spring-boot-localstack"
                },
                {
                    "OutputKey": "SNSTopicOutput",
                    "OutputValue": "arn:aws:sns:us-east-1:000000000000:sns-spring-boot-localstack"
                },
                {
                    "OutputKey": "SQSQueueOutput",
                    "OutputValue": "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/sqs-spring-boot-localstack"
                },
                {
                    "OutputKey": "DLQOutput"
                }
            ],
            "Tags": [],
            "EnableTerminationProtection": false,
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}

### Expected Behavior

The stack should be re-deployed successfully, after deletion.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```shell
localstack start -d
```

#### CF Script template.yml

```
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creating a local-stack test with S3, SNS e o SQS"
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: s3-spring-boot-localstack
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "sns-spring-boot-localstack"
      DisplayName: "sns-spring-boot-localstack"
  SQSQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "sqs-spring-boot-localstack"
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - "DLQ"
            - "Arn"
        maxReceiveCount: 3
  DLQ:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "sqs-dlq-spring-boot-localstack"
  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Protocol: "sqs"
      TopicArn: !Ref SNSTopic
      Endpoint: !GetAtt SQSQueue.Arn
  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sqs:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: SNSTopic
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Resource:
              Fn::GetAtt:
                - SQSQueue
                - Arn
        Version: "2012-10-17"
      Queues:
        - Ref: SQSQueue

Outputs:
  S3BucketOutput:
    Value: !Ref S3Bucket
  SNSTopicOutput:
    Value: !Ref SNSTopic
  SQSQueueOutput:
    Value: !Ref SQSQueue
  DLQOutput:
    Value: !Ref DLQinfra-
``` 

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```shell
awslocal cloudformation deploy \
    --stack-name infra-template \
    --template-file "template.yml"
``` 

### Environment

```markdown
- OS: MacOS SONOMA
- LocalStack: 3.0.0
```
