### ISSUE TITLE
CloudFormation with DEFAULT_REGION=eu-central-1 leads to bad gateway

### ISSUE THREAD

**Issue by pingvinen** [localstack/localstack#968]
I am running LocalStack with docker-compose and using awscli to apply a CloudFormation template. Things seem to work until I set `DEFAULT_REGION: eu-central-1` which makes the cli fail with bad gateway.

I see this problem with both the "old" and the new 0.8.7 tag + latest.

This is my `docker-compose.yml`

```yaml
version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    restart: "no"
    environment:
      SERVICES: sns:4575,sqs:4576,cloudformation:4581
      DEFAULT_REGION: eu-central-1 ## <----------- if I remove this, then it works
    ports:
      - 20121:4575 ## sns - needed by service bootstrap
      - 20122:4576 ## sqs
      - 20123:4581 ## cloudformation
      - 20124:8080 ## dashboard

  awslocal:
    image: skarpdev/awscli-local
    environment:
      LOCALSTACK_HOST: localstack
    entrypoint: awslocal cloudformation create-stack --template-body file:///data/localstack-cloudformation.yml --stack-name teststack
    volumes:
      - ./.docker/templates:/data
    depends_on:
      - localstack
    links:
      - localstack
```

Which ends up saying this in the `awslocal` container
```
An error occurred (502) when calling the CreateStack operation (reached max retries: 4): Bad Gateway
```

The full docker-compose log

```
Attaching to myservice_awslocal_1, myservice_localstack_1
awslocal_1    | 
awslocal_1    | An error occurred (502) when calling the CreateStack operation (reached max retries: 4): Bad Gateway
localstack_1  | 2018-10-18 09:44:08,572 CRIT Supervisor running as root (no user in config file)
localstack_1  | 2018-10-18 09:44:08,573 INFO supervisord started with pid 1
localstack_1  | 2018-10-18 09:44:09,575 INFO spawned: 'dashboard' with pid 10
localstack_1  | 2018-10-18 09:44:09,576 INFO spawned: 'infra' with pid 11
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start)
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2018-10-18T09:44:10:INFO:werkzeug:  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
localstack_1  | 2018-10-18T09:44:10:INFO:werkzeug:  * Restarting with stat
localstack_1  | 2018-10-18T09:44:10:WARNING:werkzeug:  * Debugger is active!
localstack_1  | 2018-10-18 09:44:10,583 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2018-10-18 09:44:10,583 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2018-10-18T09:44:10:INFO:werkzeug:  * Debugger PIN: 201-702-772
localstack_1  | Starting mock CloudFormation (http port 4581)...
localstack_1  | Starting mock SQS (http port 4576)...
localstack_1  | Starting mock SNS (http port 4575)...
localstack_1  | 2018-10-18T09:44:12:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba7347a10>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba7347a10>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  | 
localstack_1  | 2018-10-18T09:44:12:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba7369ed0>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba7369ed0>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  | 
localstack_1  | 2018-10-18T09:44:12:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba7369f90>: Failed to establish a new connection: [Errno 111] Connection refused',)) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 201, in forward
localstack_1  |     headers=forward_headers, stream=True)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 112, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/api.py", line 58, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4559): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3ba7369f90>: Failed to establish a new connection: [Errno 111] Connection refused',))
localstack_1  | 
localstack_1  | Ready.
localstack_1  | 2018-10-18T09:44:16:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name teststack does not exist Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 218, in forward
localstack_1  |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
localstack_1  |     template_deployer.deploy_template(template, req_data.get('StackName')[0])
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 509, in deploy_template
localstack_1  |     stack_resources = describe_stack_resources(stack_name, resource_id)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 227, in describe_stack_resources
localstack_1  |     resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 623, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | ClientError: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name teststack does not exist
localstack_1  | 
localstack_1  | 2018-10-18T09:44:18:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name teststack does not exist Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 218, in forward
localstack_1  |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
localstack_1  |     template_deployer.deploy_template(template, req_data.get('StackName')[0])
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 509, in deploy_template
localstack_1  |     stack_resources = describe_stack_resources(stack_name, resource_id)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 227, in describe_stack_resources
localstack_1  |     resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 623, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | ClientError: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name teststack does not exist
localstack_1  | 
localstack_1  | 2018-10-18T09:44:24:ERROR:localstack.services.generic_proxy: Error forwarding request: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name teststack does not exist Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 218, in forward
localstack_1  |     updated_response = self.proxy.update_listener.return_response(**kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
localstack_1  |     template_deployer.deploy_template(template, req_data.get('StackName')[0])
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 509, in deploy_template
localstack_1  |     stack_resources = describe_stack_resources(stack_name, resource_id)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudformation/template_deployer.py", line 227, in describe_stack_resources
localstack_1  |     resources = client.describe_stack_resources(StackName=stack_name, LogicalResourceId=logical_resource_id)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
localstack_1  |     return self._make_api_call(operation_name, kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 623, in _make_api_call
localstack_1  |     raise error_class(parsed_response, operation_name)
localstack_1  | ClientError: An error occurred (ValidationError) when calling the DescribeStackResources operation: Stack with name teststack does not exist
localstack_1  | 
```

**Comment by pingvinen** [comment]
Turns out that the issue was with the use of `awslocal`. By adding `--region=eu-central-1` to the command it works.

Working `docker-compose.yml`

```
version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    restart: "no"
    environment:
      SERVICES: sns:4575,sqs:4576,cloudformation:4581
      DEFAULT_REGION: eu-central-1 ## <----------- this needs to be reflected in the awslocal command as well
    ports:
      - 20121:4575 ## sns - needed by service bootstrap
      - 20122:4576 ## sqs
      - 20123:4581 ## cloudformation
      - 20124:8080 ## dashboard

  awslocal:
    image: skarpdev/awscli-local
    environment:
      LOCALSTACK_HOST: localstack
    entrypoint: awslocal cloudformation create-stack --template-body file:///data/localstack-cloudformation.yml --stack-name teststack --region=eu-central-1
    volumes:
      - ./.docker/templates:/data
    depends_on:
      - localstack
    links:
      - localstack
```
