### ISSUE TITLE
bug: stepfunctions time data does not match format of ISO date with milliseconds

### ISSUE THREAD

**Issue by attila** [localstack/localstack#9722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

State machines do not recognise ISO dates with milliseconds as `TimeStampPath`.

Example state machine:

```json
{
  "Comment": "Wait with TimestampPath demo",
  "StartAt": "Wait",
  "States": {
    "Wait": {
      "Type": "Wait",
      "TimestampPath": "$.start_at",
      "End": true
    }
  }
}
```

When started with `{ "start_at": "2023-11-24T08:38:00.000Z" }`

Execution fails with

```text
localstack_main  | 2023-11-24T08:49:07.437 ERROR --- [ad-63 (eval)] l.s.s.a.c.eval_component   : Exception=ValueError, Details=["time data '2023-11-24T09:00:00.000Z' does not match format '%Y-%m-%dT%H:%M:%SZ'"] at '(TimestampPath| {'path': '$.start_at'}'
localstack_main  | 2023-11-24T08:49:07.437 ERROR --- [ad-63 (eval)] l.s.s.a.c.eval_component   : Exception=ValueError, Details=["time data '2023-11-24T09:00:00.000Z' does not match format '%Y-%m-%dT%H:%M:%SZ'"] at '(StateWait| {'comment': None, 'input_path': (InputPath| {'input_path_src': '$'}, 'output_path': (OutputPath| {'output_path': '$'}, 'state_entered_event_type': 'WaitStateEntered', 'state_exited_event_type': 'WaitStateExited', 'name': 'Wait', 'state_type': <StateType.Wait: 20>, 'continue_with': <localstack.services.stepfunctions.asl.component.state.state_continue_with.ContinueWithEnd object at 0x7f1ba0fec5d0>, 'wait_function': (TimestampPath| {'path': '$.start_at'}}'
localstack_main  | 2023-11-24T08:49:07.438 ERROR --- [ad-63 (eval)] l.s.s.a.c.program.program  : Stepfunctions computation ended with exception '<class 'ValueError'>(time data '2023-11-24T09:00:00.000Z' does not match format '%Y-%m-%dT%H:%M:%SZ')'.
```

### Expected Behavior

It should work like in the AWS service.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

```yml
version: '3.8'

services:
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
    image: localstack/localstack:3.0.0
    environment:
      - LOCALSTACK_HOST=localhost
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

1. Create IAM role and state machine

   ```bash
   awslocal iam create-role --role-name test --assume-role-policy-document '{}'

   awslocal stepfunctions create-state-machine --name test \
     --definition '{"Comment":"Wait with TimestampPath demo","StartAt":"Wait","States":{"Wait":{"Type":"Wait","TimestampPath":"$.start_at","End":true}}}' \
     --role-arn 'arn:aws:iam::000000000000:role/test'
   ```

2. Start state machine execution (with "start_at" being a date in the future)

   ```bash
   awslocal stepfunctions start-execution \
     --state-machine-arn 'arn:aws:states:eu-west-1:000000000000:stateMachine:test' \
     --input '{"start_at":"2023-11-24T09:00:00.000Z"}'
   ```

### Environment

```markdown
- OS: macOS 14.1.1
- LocalStack: 3.0.0
```
