### ISSUE TITLE
bug: Creating or updating a Route53 HealthCheck does not persist tags.

### ISSUE THREAD

**Issue by gitisz** [localstack/localstack#9734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When provisioning a CloudFormation template with a Route53 HealthCheck, the `HealthCheckTags` option is not resulting in a health check with tags.

### Expected Behavior

I expect that provisioning a Route53 HealthCheck with `HealthCheckTags` through CloudFormation or awslocal CLI command that tags are created and are able to be retrieved using awslocal CLI or boto3.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```
version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - SERVICES=s3,dynamodb,ecr,lambda,cloudformation,cloudwatch,sts,iam,apigateway,route53,elbv2,ecs,ec2,logs,events,apigatewayv2,application-autoscaling
      - PERSISTENCE=0
      - LOCALSTACK_API_KEY=IFduycO4uP
      - PORT_WEB_UI=18080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - SKIP_SSL_CERT_DOWNLOAD=1
      - OUTBOUND_HTTP_PROXY=${HTTP_PROXY}
      - OUTBOUND_HTTPS_PROXY=${HTTP_PROXY}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../../shared/localstack:/var/lib/localstack"
    networks:
      - "local"

networks:
  local:
    driver: "bridge"
 ```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)
   
```
	awslocal cloudformation create-stack \
		--stack-name ecs-service-route53 \
		--template-body file://features/templates/ecs-fargate/ecs-service-route53.yml \
		--parameters ParameterKey=HostedZoneId,ParameterValue=$$hostedZoneId \
			ParameterKey=HostedZoneName,ParameterValue=$$hostedZoneName 
		--region us-east-1 
```

CloudFormation Template
```
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Deploys a Route53 record set for either geolocation or weighted policies.

Parameters:
  Ba:
    Type: String
    Default: myapp
    Description: >
      The application to use.
  Environment:
    Type: String
    Default: Qa
    Description: >
      The environment name. Example: dev, qa, prod.
  HostedZoneId:
    Type: String
    Description: >
      The HostedZoneId of the private Hosted Zone.
  HostedZoneName:
    Type: String
    Description: >
      The HostedZoneName of the private Hosted Zone.
  ServiceName:
    Type: String
    Default: foo-service
    Description: >
      A name for the service.
  TopLevelRecordSetType:
    Type: String
    Default: 'geolocation'
    AllowedValues:
      - 'geolocation'
      - 'weighted'
    Description: Type of top level route (geolocation or weighted).

Mappings:
  Region:
    us-east-1:
      Alias: 'use1'
    us-west-2:
      Alias: 'usw2'
  Environment:
    Dev:
      Alias: 'dev'
    Qa:
      Alias: 'qa'
    Prod:
      Alias: 'prod'

Conditions:
  # TODO: support weighted
  CreateGeoLocationRecordSet: !Equals [ !Ref 'TopLevelRecordSetType', 'geolocation' ]
  CreateWeightRecordSet: !Equals [ !Ref 'TopLevelRecordSetType', 'weighted' ]

Resources:
  FailoverHealthCheckEast1:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: "CLOUDWATCH_METRIC"
        Inverted: False
        Disabled: False
        AlarmIdentifier:
          Region: us-west-2
          Name:
            Fn::Sub:
              - 'Cloud-${EnvironmentAlias}${ServicesNameAlias}-us-east-1-FailoverStatus'
              - EnvironmentAlias: !FindInMap [Environment, !Ref Environment, Alias]
                ServicesNameAlias: !Join [ '', !Split [ '-', !Ref ServiceName ] ]
        InsufficientDataHealthStatus: LastKnownStatus
      HealthCheckTags:
        - Key: cloud-enabled
          Value: true
```

### Environment

```markdown
- OS: MacOS
- LocalStack: latest
```

### Anything else?

After the CFT successfully completes, running the `awslocal` command:
```
$ awslocal route53 list-health-checks
```

Returns:
```
{
    "HealthChecks": [
        {
            "Id": "f78c56cb-1a87-4034-9a97-73364717499d",
            "CallerReference": "FailoverHealthCheckEast1-ecb2efa8",
            "HealthCheckConfig": {
                "IPAddress": "None",
                "Port": 80,
                "Type": "CLOUDWATCH_METRIC",
                "RequestInterval": 30,
                "FailureThreshold": 3,
                "MeasureLatency": false,
                "Inverted": false,
                "Disabled": false,
                "EnableSNI": false
            },
            "HealthCheckVersion": 1
        },
        {
            "Id": "b624bf94-2ea7-444b-ab94-6570356eca03",
            "CallerReference": "FailoverHealthCheckWest2-6cb1d89f",
            "HealthCheckConfig": {
                "IPAddress": "None",
                "Port": 80,
                "Type": "CLOUDWATCH_METRIC",
                "RequestInterval": 30,
                "FailureThreshold": 3,
                "MeasureLatency": false,
                "Inverted": false,
                "Disabled": false,
                "EnableSNI": false
            },
            "HealthCheckVersion": 1
        }
    ]
}

Furthermore, after executing the `Boto3` code:
```
response = client.change_tags_for_resource(
    ResourceType='healthcheck',
    ResourceId='f78c56cb-1a87-4034-9a97-73364717499d',
    AddTags=[
        {
            'Key': 'cloud-enabled',
            'Value': 'false'
        },
    ]
)
```
The response is 200, but the tags are not updated.
