### ISSUE TITLE
bug: After upgrading to 3.0 cannot connect to postgres/RDS from outside the container

### ISSUE THREAD

**Issue by trdyer** [localstack/localstack#9759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With 2.3 I am able to successfully connect to postgres/RDS from outside of the localstack container. After upgrading to 3.0 I am getting errors connecting to postgres such as 

```sh 
$: psql -d postgres -U myuser -p 4510 -h localhost -W
Password: 
psql: error: connection to server at "localhost" (::1), port 4510 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

I am also unable to connect to postgres from other containers

### Expected Behavior

The ability to connect to the container from the host syetm or other containers

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker compose up

where the service definition is
```yaml 
  localstack:
    image: localstack/localstack-pro:3.0.1
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=${DEBUG:-1}
      - PERSISTENCE=${PERSISTENCE:-1}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-}
      - SERVICES=rds,kms,secretsmanager,ec2
      - EAGER_SERVICE_LOADING=1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - myNetwork
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```
$: awslocal rds-data execute-statement \
    --database postgres \
    --resource-arn arn:aws:rds:us-east-1:000000000000:cluster:myCluster \
    --secret-arn arn:aws:secretsmanager:us-east-1:000000000000:secret:mySecret \
    --sql "CREATE DATABASE \"myDBNAME\" WITH OWNER \"myuser\""
```

```
$: psql -d postgres -U myuser -p 4510 -h localhost -W
Password: 
psql: error: connection to server at "localhost" (::1), port 4510 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

### Environment

```markdown
- OS: MacOS Sonoma 14.1.1 Apple M2 Pro
- LocalStack: pro, 3.0
```
