### ISSUE TITLE
Transcribe service always fails with sample_rate error for video codecs

### ISSUE THREAD

**Issue by kazazor** [localstack/localstack#9812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every call to the transcribe service starts a job, but then always fails with a `sample_rate` error.

### Expected Behavior

The job should be successful and the transcription should be returned.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Docker compose:
```yml
localstack:
    image: localstack/localstack-pro
    restart: always
    profiles: ["local-not-yet"] # TODO: Rename it back to "local" for the final stage of adding localstack
    # The localstack documentation (under GATEWAY_LISTEN: https://docs.localstack.cloud/references/configuration/) are not 100 great for macOS.
    # If we were to follow it we would have used: 127.0.0.1:4566:4566
    # The problem is IPv6 that could apply here and LocalSTack does not support it: https://docs.localstack.cloud/references/network-troubleshooting/
    # So we're defining the ports WITHOUT the localhost address
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
      - "53:53" # DNS config (required for Pro) - https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - "53:53/udp" # DNS config (required for Pro) - https://docs.localstack.cloud/user-guide/tools/transparent-endpoint-injection/
      - "443:443" # LocalStack HTTPS Gateway (required for Pro)
    environment:
      # LS_LOG: "trace" # Uncomment for getting much more debug logs from LocalStack
      DEBUG: 1 # Change to 0 if you would like to have less noise in the LocalStack container's logs
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN} # Add it to your .env file at the root of the project
      PERSISTENCE: 1
      ENFORCE_IAM: 0 # https://docs.localstack.cloud/references/configuration/#iam
      EXTRA_CORS_ALLOWED_ORIGINS: "*" # https://docs.localstack.cloud/references/configuration/#security
      DOCKER_HOST: unix:///var/run/docker.sock
      DNS_LOCAL_NAME_PATTERNS: ".*(secretsmanager).*.amazonaws.com" # The services that we would like their requests be redirected to AWS instead of Localstack. This is done via https://docs.localstack.cloud/user-guide/tools/dns-server/#skip-localstack-dns-resolution
      DNS_SERVER: 8.8.8.8 # DNS fallback server, all the non AWS requests will be forwarded to it
      DNS_ADDRESS: 127.0.0.1 # The LocalStack local DNS server address
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # Enable to use services that use external docker images, like Lambda functions
```

Steps:
SInce transcribe is setup by default, all you need to do is call it with an S3 `mp4` file:
```js
import {
  CreateVocabularyCommand,
  GetTranscriptionJobCommand,
  GetVocabularyCommand,
  StartTranscriptionJobCommand,
  TranscribeClient,
  UpdateVocabularyCommand
} from "@aws-sdk/client-transcribe";

this.transcribeClient = new TranscribeClient({ region: "us-east-1" });

    const transcriptJob = await this.transcribeClient.send(
      new StartTranscriptionJobCommand({
        TranscriptionJobName: "testName",
        LanguageCode: "en-US",
        MediaFormat: "mp4",
        Media: {
          MediaFileUri: <s3 URI>
        },
        OutputBucketName: <your value>,
        OutputKey: <your value>,
        Subtitles: { Formats: ["srt", "vtt"] },
      })
```

Then checking to see the status:
```js
    const transcriptionJob = await this.transcribeClient.send(
      new GetTranscriptionJobCommand({ TranscriptionJobName: "testName" })
    );
```

### Environment

```markdown
- OS: macOS 14.1.2
- LocalStack: Latest using docker-compose
```

### Anything else?

I verified with the team that this is indeed a bug: https://localstack-community.slack.com/archives/CMAFN2KSP/p1701843995174299?thread_ts=1701777783.269879&cid=CMAFN2KSP
