### ISSUE TITLE
IAM validation for  cloudformation:DescribeStackEvents incorrect when StackId is used

### ISSUE THREAD

**Issue by bram-tv** [localstack/localstack#9845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `cloudformation:DescribeStackEvents` function has a `StackName` parameter which is documented as:
>
> The name or the unique stack ID that's associated with the stack, which aren't always interchangeable:
> -  Running stacks: You can specify either the stack's name or its unique stack ID.
> -  Deleted stacks: You must specify the unique stack ID.

The commands:
- `awslocal cloudformation describe-stack-events --stack-name my-stack`
- `awslocal cloudformation describe-stack-events --stack-name arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6`

both return the same information but the IAM permission check is incorrect for the second one.

Logging for both calls (deliberately using a user that has no access):
For `--stack-name my-stack`:
```
Necessary permissions for this action: ["Action 'cloudformation:DescribeStackEvents' for 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/*'"]
```

For `--stack-name arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6`:
```
Necessary permissions for this action: ["Action 'cloudformation:DescribeStackEvents' for 'arn:aws:cloudformation:us-east-1:000000000000:stack/arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6/*'"]
```

=> `arn:aws:cloudformation:us-east-1:000000000000:stack/` is duplicated..

### Expected Behavior

The permission check for the second call should be:
- `Necessary permissions for this action: ["Action 'cloudformation:DescribeStackEvents' for 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6/*'"]` **OR**
- `Necessary permissions for this action: ["Action 'cloudformation:DescribeStackEvents' for 'arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6'"]` 

(I have no idea if the trailing `/*` is needed)

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

1. Create the `my-stack.yml` file:
```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:DescribeStackEvents
            Resource:
              - !Sub "arn:aws:cloudformation:${AWS::Region}:*:stack/my-stack/*"
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !Ref IAMPolicy
  IAMAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref IAMUser

Outputs:
  AwsAccessKeyId:
    Value: !Ref IAMAccessKey
  AwsSecretAccessKey:
    Value: !GetAtt IAMAccessKey.SecretAccessKey
```
2. Deploy it:
```
$ ./awslocal --region us-east-1 cloudformation deploy --template-file my-stack.yml --stack-name my-stack

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - my-stack
``` 
3. Describe the stack to get the `StackId`, `StackName` and the AWS key:
```
$ ./awslocal --region us-east-1 cloudformation describe-stacks --stack-name my-stack
{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6",
            "StackName": "my-stack",
            ...
            "Outputs": [
                {
                    "OutputKey": "AwsAccessKeyId",
                    "OutputValue": "LKIAQAAAAAAACOUVRZ3C"
                },
                {
                    "OutputKey": "AwsSecretAccessKey",
                    "OutputValue": "1owvzXMl1l2oNmWVqH6DtN+OqkiCYVSHjHCV+sMy"
                }
            ],
            ...
```
4. Describe stack events using StackName:
```
$ AWS_ACCESS_KEY_ID="LKIAQAAAAAAACOUVRZ3C" AWS_SECRET_ACCESS_KEY="1owvzXMl1l2oNmWVqH6DtN+OqkiCYVSHjHCV+sMy" ./awslocal --region us-east-1 cloudformation describe-stack-events --stack-name my-stack
{
    "StackEvents": [
        {
            ...
```
5. Describe stack events using StackId:
```
$ AWS_ACCESS_KEY_ID="LKIAQAAAAAAACOUVRZ3C" AWS_SECRET_ACCESS_KEY="1owvzXMl1l2oNmWVqH6DtN+OqkiCYVSHjHCV+sMy" ./awslocal --region us-east-1 cloudformation describe-stack-events --stack-name arn:aws:cloudformation:us-east-1:000000000000:stack/my-stack/731f00f6

An error occurred (AccessDeniedException) when calling the DescribeStackEvents operation: Access to the specified resource is denied
```

### Environment

```markdown
- LocalStack: (using LocalStack Pro with ENFORCE_IAM)
  - LocalStack version: 3.0.3.dev20231207105008
  - LocalStack Docker container id: 2aff981eb311
  - LocalStack build date: 2023-12-11
  - LocalStack build git hash: 8a86c29
```

### Anything else?

(The problem was first observed in a deployment via serverless. It appears that serverless always calls DescribeStackEvents with the StackId as StackName.)
