### ISSUE TITLE
The specified bucket does not exist trying to access API

### ISSUE THREAD

**Issue by kokokenada** [localstack/localstack#9946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

An API URL such as http://localhost:4566/restapis/pjfpww3gl4/api/graphql returns

```
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<RequestId>d9cc2253-2079-41f1-89b4-55e277d04aa5</RequestId>
<BucketName>restapis</BucketName>
</Error>
```

Using the docker compose template from https://github.com/localstack/localstack/blob/master/docker-compose.yml :

```
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    # image: localstack/localstack:3.0.2
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

A URL such as http://pjfpww3gl4.execute-api.localhost:4566/api/graphql does seem to make it to the code (but apollo client  baulks at that URL, so the http://localhost:4566/restapis for is required.

Function and API config deployed with serverless. Relevant parts from the serverless.yml:

```
app: quota-server
service: quota-${env:ENVIRONMENT}-${env:GIT_BRANCH}-svr

custom:
  prune:
    automatic: true
    number: 5
  localstack:
    stages:
      - local

plugins:
  - serverless-localstack
  - serverless-prune-plugin

provider:
  stage: ${env:STAGE}
  name: aws
  runtime: nodejs18.x
  tracing:
    apiGateway: true
    lambda: true
  region: ${env:AWS_REGION}
  httpApi:
    cors: true
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    GIT_BRANCH: ${env:GIT_BRANCH}
    VITE_GIT_BRANCH: ${env:VITE_GIT_BRANCH}
    VITE_COMMIT_REF: ${env:VITE_COMMIT_REF, "NOT_SET"}
    VITE_BUILD_ID: ${env:VITE_BUILD_ID, "NOT_SET"}
    VITE_BUILD_DATE: ${env:VITE_BUILD_DATE, "NOT_SET"}
    STAGE: ${env:GIT_BRANCH, 'dev'}
    ENVIRONMENT: ${env:ENVIRONMENT}
    DATABASE_URL: ${env:DATABASE_URL}
    EMAIL_SERVER_HOST: ${env:EMAIL_SERVER_HOST}
    EMAIL_SERVER_PORT: ${env:EMAIL_SERVER_PORT}
    EMAIL_SERVER_USERNAME: ${env:EMAIL_SERVER_USERNAME}
    EMAIL_SERVER_PASSWORD: ${env:EMAIL_SERVER_PASSWORD}
    VITE_APP_CLIENT_URL: ${env:VITE_APP_CLIENT_URL}
    VITE_ADMIN_CLIENT_URL: ${env:VITE_ADMIN_CLIENT_URL}
    VITE_API_URL: ${env:VITE_API_URL }
    HMAC_SECRET: ${env:HMAC_SECRET}
    ADMIN_MASTER_PWD: ${env:ADMIN_MASTER_PWD}
functions:
  api:
    name: quota-${env:ENVIRONMENT}-${env:GIT_BRANCH}-api
    tags:
      environment: ${env:ENVIRONMENT}
    handler: ${env:HANDLER}
    timeout: 30 # Note: API Gateway current maximum is 30 seconds
    events:
      - http:
          method: any
          path: /graphql/
```

### Expected Behavior

it should access the API, not look for a bucket

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose up

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

curl -X GET http://localhost:4566/restapis/5pxcj2mcj2/api/graphql
<?xml version='1.0' encoding='utf-8'?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><RequestId>fda924b9-2a23-4743-9d7e-ebb88cff7cab</RequestId><BucketName>restapis</BucketName></Error>

### Environment

```markdown
- OS:Linux DESKTOP-ALS1SP4 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- LocalStack:3.0.2
```
