### ISSUE TITLE
bug: Unable to run localstack

### ISSUE THREAD

**Issue by Ankush904** [localstack/localstack#9963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I recently changed my laptop from windows 11 to Mac. I have made a local docker setup in my previous laptop with documentation of how to create a local mongo collection for work purpose.
Code:
```
## Guidelines for development on local machine
1. Create a folder in the application root named `devtest`
2. Create a `docker-compose.yml` file and two folders
   1. `.devmongo` -> To create a local Mongo copy
   2. `.localstack` -> To simulate AWS S3
3. The `docker-compose.yml` file could be setup in the following manner:
```
version: '3.0'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - “****-****:****-****”
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=****
    volumes:
      - './.localstack/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  mongodb_container:
    image: mongo:4.4.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: local-dev
    ports:
      - 27017:27017
    volumes:
      - './.devmongo/data/db:/data/db'
      - '../mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
```

Then run docker-compose up in devtest folder to run the docker. And it’s working in windows. But in MacBook I am getting an error:
```
localstack           | ERROR: 'rm -rf "/tmp/localstack"': exit code 1; output: b"rm: cannot remove '/tmp/localstack': Device or resource busy\n"
localstack           | Traceback (most recent call last):
localstack           |   File "<frozen runpy>", line 198, in _run_module_as_main
localstack           |   File "<frozen runpy>", line 88, in _run_code
localstack           |   File "/opt/code/localstack/localstack/runtime/main.py", line 28, in <module>
localstack           |     main()
localstack           |   File "/opt/code/localstack/localstack/runtime/main.py", line 20, in main
localstack           |     infra.start_infra(asynchronous=False)
localstack           |   File "/opt/code/localstack/localstack/services/infra.py", line 235, in start_infra
localstack           |     files.rm_rf(config.dirs.tmp)
localstack           |   File "/opt/code/localstack/localstack/utils/files.py", line 214, in rm_rf
localstack           |     shutil.rmtree(path)
localstack           |   File "/usr/local/lib/python3.11/shutil.py", line 738, in rmtree
localstack           |     onerror(os.rmdir, path, sys.exc_info())
localstack           |   File "/usr/local/lib/python3.11/shutil.py", line 736, in rmtree
localstack           |     os.rmdir(path, dir_fd=dir_fd)
localstack           | OSError: [Errno 16] Device or resource busy: ‘/tmp/localstack'
```

I tried removing the file manually and restarting checking if there is any other local stask but nothing such case.

### Expected Behavior

I in windows both of the container run properly

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

## Guidelines for development on local machine
1. Create a folder in the application root named `devtest`
2. Create a `docker-compose.yml` file and two folders
   1. `.devmongo` -> To create a local Mongo copy
   2. `.localstack` -> To simulate AWS S3
3. The `docker-compose.yml` file could be setup in the following manner:
```
version: '3.0'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - “****-****:****-****”
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=****
    volumes:
      - './.localstack/tmp/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  mongodb_container:
    image: mongo:4.4.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: local-dev
    ports:
      - 27017:27017
    volumes:
      - './.devmongo/data/db:/data/db'
      - '../mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
```

### Environment

```markdown
- OS: Sonoma 14.2.1
- LocalStack: Latest
```

**Comment by MarcelStranak** [comment]
Hi @Ankush904,

Please consider using the default [docker-compose.yml](https://github.com/localstack/localstack/blob/master/docker-compose.yml) file provided by LocalStack: .
For the issue with the volume I would double-check if in the Docker Desktop you have enabled the access to the `volume` folder as you have in your docker-compose.yml file.

Please be aware that Mac needs a different configuration as Windows.
https://docs.docker.com/desktop/settings/mac/#file-sharing

**Comment by zwallacedev** [comment]
@MarcelStranak I have ran into this as well, since the latest update from `2.3.2`, and I was able to get around it by setting this in my docker-compose:
`- CLEAR_TMP_FOLDER=0`

This is not ideal, obviously, but it has created a major headache attempting to debug this. I continually get the following error message:

```
localstack | ERROR: 'rm -rf "/tmp/localstack"': exit code 1; output: b"rm: cannot remove '/tmp/localstack': Device or resource busy\n"
localstack | Traceback (most recent call last):
localstack | File "", line 198, in _run_module_as_main
localstack | File "", line 88, in _run_code
localstack | File "/opt/code/localstack/localstack/runtime/main.py", line 28, in
localstack | main()
localstack | File "/opt/code/localstack/localstack/runtime/main.py", line 20, in main
localstack | infra.start_infra(asynchronous=False)
localstack | File "/opt/code/localstack/localstack/services/infra.py", line 235, in start_infra
localstack | files.rm_rf(config.dirs.tmp)
localstack | File "/opt/code/localstack/localstack/utils/files.py", line 214, in rm_rf
localstack | shutil.rmtree(path)
localstack | File "/usr/local/lib/python3.11/shutil.py", line 738, in rmtree
localstack | onerror(os.rmdir, path, sys.exc_info())
localstack | File "/usr/local/lib/python3.11/shutil.py", line 736, in rmtree
localstack | os.rmdir(path, dir_fd=dir_fd)
localstack | OSError: [Errno 16] Device or resource busy: ‘/tmp/localstack'```

Here's how my docker-compose.yml looks now:

```
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT= xyzs
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CLEAR_TMP_FOLDER=0
    ports:
      - ...my ports 😄...
    volumes:
      - './localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  ```

**Comment by MarcelStranak** [comment]
Hi @zwallacedev,

For the solution, please refer to the latest [Docker Compose file](https://github.com/localstack/localstack/blob/master/docker-compose.yml) and the example below.

```yaml
version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
#      - DATA_DIR=/tmp/localstack/data # remove deprecated environment variable (more info https://docs.localstack.cloud/references/configuration/#legacy)
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
#      - './localstack:/tmp/localstack' #set correct pathing on docker container  - './localstack:/var/lib/localstack' (more info https://docs.localstack.cloud/references/filesystem/#localstack-volume)
      - './localstack:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
```
